window.QS_SET06 = [
  {
    n: 51,
    en: `A health insurance company stores personally identifiable information (PII) in an Amazon S3 bucket. The company uses server-side encryption with S3 managed encryption keys (SSE-S3) to encrypt the objects. According to a new requirement, all current and future objects in the S3 bucket must be encrypted by keys that the company’s security team manages. The S3 bucket does not have versioning enabled.<br/><br/>Which solution will meet these requirements?`,
    ko: `건강 보험 회사는 개인 식별 정보(PII)를 Amazon S3 버킷에 저장합니다. 회사는 S3 관리형 암호화 키(SSE-S3)를 사용한 서버 측 암호화를 사용하여 객체를 암호화합니다. 새로운 요구 사항에 따라 S3 버킷의 모든 현재 및 미래 객체는 회사 보안 팀이 관리하는 키로 암호화되어야 합니다. S3 버킷에는 버전 관리가 활성화되어 있지 않습니다. <br/><br/>어떤 솔루션이 이러한 요구 사항을 충족합니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`In the S3 bucket properties, change the default encryption to SSE-S3 with a customer managed key. Use the AWS CLI to re-upload all objects in the S3 bucket. Set an S3 bucket policy to deny unencrypted PutObject requests.`, ko:`S3 버킷 속성에서 고객 관리형 키를 사용하여 기본 암호화를 SSE-S3으로 변경합니다. AWS CLI를 사용하여 S3 버킷의 모든 객체를 다시 업로드합니다. 암호화되지 않은 PutObject 요청을 거부하도록 S3 버킷 정책을 설정합니다.` },
      { k:'B', en:`In the S3 bucket properties, change the default encryption to server-side encryption with AWS KMS managed encryption keys (SSE-KMS). Set an S3 bucket policy to deny unencrypted PutObject requests. Use the AWS CLI to re-upload all objects in the S3 bucket.`, ko:`S3 버킷 속성에서 기본 암호화를 AWS KMS 관리형 암호화 키(SSE-KMS)를 사용한 서버 측 암호화로 변경합니다. 암호화되지 않은 PutObject 요청을 거부하도록 S3 버킷 정책을 설정합니다. AWS CLI를 사용하여 S3 버킷의 모든 객체를 다시 업로드합니다.` },
      { k:'C', en:`In the S3 bucket properties, change the default encryption to server-side encryption with AWS KMS managed encryption keys (SSE-KMS). Set an S3 bucket policy to automatically encrypt objects on GetObject and PutObject requests.`, ko:`S3 버킷 속성에서 기본 암호화를 AWS KMS 관리형 암호화 키(SSE-KMS)를 사용한 서버 측 암호화로 변경합니다. GetObject 및 PutObject 요청 시 객체를 자동으로 암호화하도록 S3 버킷 정책을 설정합니다.` },
      { k:'D', en:`In the S3 bucket properties, change the default encryption to AES-256 with a customer managed key. Attach a policy to deny unencrypted PutObject requests to any entities that access the S3 bucket. Use the AWS CLI to re-upload all objects in the S3 bucket.`, ko:`S3 버킷 속성에서 고객 관리형 키를 사용하여 기본 암호화를 AES-256으로 변경합니다. S3 버킷에 액세스하는 모든 엔터티에 대한 암호화되지 않은 PutObject 요청을 거부하는 정책을 연결합니다. AWS CLI를 사용하여 S3 버킷의 모든 객체를 다시 업로드합니다.` },
    ],
    answer: ["B"],
    vote: '61% B, 38% D',
    explain: `<p><span class="mark-ok">✅ B</span></p><p>https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingKMSEncryption.html 따라서 정답은 B입니다. S3 버킷 속성에서 기본 암호화를 AWS KMS 관리형 암호화 키를 사용하는 서버 측 암호화로 변경합니다( SSE-KMS). 암호화되지 않은 PutObject 요청을 거부하도록 S3 버킷 정책을 설정합니다. AWS CLI를 사용하여 S3 버킷의 모든 객체를 다시 업로드합니다.</p>`,
    wrong: `<p><span class="mark-no">❌ A</span> — https://docs.aws.amazon.com/AmazonS3/latest/userguide/default-bucket-encryption.html에 따르면 - "고객 제공 키(SSE-C)를 사용한 서버 측 암호화는 기본 암호화에 지원되지 않습니다." 하지만 회사 보안팀이 관리하는 솔루션이 필요하므로 A만이 고객 제공 키로 암호화할 수 있습니다. 나는 </p><p><span class="mark-no">❌ D</span> — 내 생각엔 D가 맞는 것 같아. https://docs.aws.amazon.com/AmazonS3/latest/userguide/ServerSideEncryptionCustomerKeys.html</p>`,
    disc: [{ ans:'B', txt:'https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingKMSEncryption.html 따라서 정답은 B입니다. S3 버킷 속성에서 기본 암호화를 AWS KMS 관리형 암호화 키를 사용하는 서버 측 암호화로 변경합니다( SSE-KMS). 암호화되지 않은 PutObject 요청을 거부하도록 S3 버킷 정책을 설정합니다. AWS CLI를 사용하여 S3 버킷의 모든 객체를 다시 업로드합니다.' }, { ans:'D', txt:'내 생각엔 D가 맞는 것 같아. https://docs.aws.amazon.com/AmazonS3/latest/userguide/ServerSideEncryptionCustomerKeys.html' }, { ans:'D', txt:'I think D is correct. https://docs.aws.amazon.com/AmazonS3/latest/userguide/ServerSideEncryptionCustomerKeys.html' }, { ans:'B', txt:'회사 보안 팀에서 관리하는 키를 사용하여 Amazon S3 버킷의 현재 및 미래 객체를 모두 암호화하기 위한 요구 사항을 충족하려면 S3 버킷의 기본 암호화를 AWS KMS 관리형 키(SSE-KMS)를 사용하는 서버 측 암호화로 변경합니다. 암호화되지 않은 PutObject 요청을 거부하는 S3 버킷 정책을 구현하여 모든 새로운 업로드가 지정된 KMS 키로 암호화되도록 합니다. 그런 다음 AWS CLI를 사용하여 모든 기존 객체를 S3 버킷에 다시 업로드하고 현재 데이터에 새로운 암호화 정책을 적용합니다. 이 접근 방식은 중단을 일으키지 않고 새로운 개체와 기존 개체 모두에 KMS 암호화를 적용하여 규정 준수를 보장합니다.' }, { ans:'B', txt:'To meet the requirement for encrypting all current and future objects in an Amazon S3 bucket with keys managed by the company’s security team, change the S3 bucket’s default encryption to server-side encryption with AWS KMS managed keys (SSE-KMS). Implement an S3 bucket policy to deny unencrypted PutObject requests, ensuring all new uploads are encrypted with the specified KMS key. Then, use th...' }]
  },
  {
    n: 52,
    en: `A company is running a web application in the AWS Cloud. The application consists of dynamic content that is created on a set of Amazon EC2 instances. The EC2 instances run in an Auto Scaling group that is configured as a target group for an Application Load Balancer (ALB).<br/><br/>The company is using an Amazon CloudFront distribution to distribute the application globally. The CloudFront distribution uses the ALB as an origin. The company uses Amazon Route 53 for DNS and has created an A record of www.example.com for the CloudFront distribution.<br/><br/>A solutions architect must configure the application so that itis highly available and fault tolerant.<br/><br/>Which solution meets these requirements?`,
    ko: `한 회사가 AWS 클라우드에서 웹 애플리케이션을 실행하고 있습니다. 애플리케이션은 Amazon EC2 인스턴스 세트에서 생성된 동적 콘텐츠로 구성됩니다. EC2 인스턴스는 ALB(Application Load Balancer)의 대상 그룹으로 구성된 Auto Scaling 그룹에서 실행됩니다. <br/><br/>이 회사는 Amazon CloudFront 배포를 사용하여 애플리케이션을 전 세계적으로 배포하고 있습니다. CloudFront 배포판은 ALB를 오리진으로 사용합니다. 이 회사는 DNS에 Amazon Route 53을 사용하고 CloudFront 배포를 위해 www.example.com이라는 A 레코드를 생성했습니다. <br/><br/>솔루션 설계자는 가용성이 높고 내결함성이 있도록 애플리케이션을 구성해야 합니다. <br/><br/>이러한 요구 사항을 충족하는 솔루션은 무엇입니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Provision a full, secondary application deployment in a different AWS Region. Update the Route 53 A record to be a failover record. Add both of the CloudFront distributions as values. Create Route 53 health checks.`, ko:`다른 AWS 리전에서 전체 보조 애플리케이션 배포를 프로비저닝합니다. Route 53 A 레코드를 장애 조치 레코드로 업데이트합니다. 두 CloudFront 배포를 모두 값으로 추가합니다. Route 53 상태 확인을 생성합니다.` },
      { k:'B', en:`Provision an ALB, an Auto Scaling group, and EC2 instances in a different AWS Region. Update the CloudFront distribution, and create a second origin for the new ALCreate an origin group for the two origins. Configure one origin as primary and one origin as secondary.`, ko:`다른 AWS 지역에 ALB, Auto Scaling 그룹 및 EC2 인스턴스를 프로비저닝합니다. CloudFront 배포를 업데이트하고 새 AL에 대한 두 번째 오리진을 생성합니다. 두 오리진에 대한 오리진 그룹을 생성합니다. 하나의 원본을 기본으로 구성하고 하나의 원본을 보조로 구성합니다.` },
      { k:'C', en:`Provision an Auto Scaling group and EC2 instances in a different AWS Region. Create a second target for the new Auto Scaling group in the ALB. Set up the failover routing algorithm on the ALB.`, ko:`다른 AWS 지역에 Auto Scaling 그룹과 EC2 인스턴스를 프로비저닝합니다. ALB에서 새 Auto Scaling 그룹에 대한 두 번째 대상을 생성합니다. ALB에서 장애 조치 라우팅 알고리즘을 설정합니다.` },
      { k:'D', en:`Provision a full, secondary application deployment in a different AWS Region. Create a second CloudFront distribution, and add the new application setup as an origin. Create an AWS Global Accelerator accelerator. Add both of the CloudFront distributions as endpoints.`, ko:`다른 AWS 지역에 전체 보조 애플리케이션 배포를 프로비저닝합니다. 두 번째 CloudFront 배포를 생성하고 새 애플리케이션 설정을 오리진으로 추가합니다. AWS Global Accelerator 액셀러레이터를 생성합니다. 두 CloudFront 배포를 모두 엔드포인트로 추가합니다.` },
    ],
    answer: ["B"],
    vote: '100% B',
    explain: `<p><span class="mark-ok">✅ B</span></p><p>정답은 B입니다. 다른 AWS 지역의 ALB, Auto Scaling 그룹 및 EC2 인스턴스를 프로비저닝하면 애플리케이션에 대한 중복성 및 장애 조치 기능이 제공됩니다. CloudFront 배포는 두 번째 지역에 새 ALB에 대한 두 번째 오리진을 생성함으로써 기본 오리진에 문제가 있는 경우 트래픽을 정상 오리진으로 자동 라우팅할 수 있습니다. 이렇게 하면 애플리케이션의 가용성과 내결함성이 유지됩니다. 옵션 A는 Route 53 장애 조치 레코드를 사용하므로 올바르지 않습니다. 이로 인해 클라이언트의 지연 시간과 DNS 확인 시간이 늘어날 수 있습니다. 옵션 C는 애플리케이션의 중요한 구성 요소인 로드 밸런서에 대한 중복성을 제공하지 않기 때문에 올바르지 않습니다. 옵션 D는 첫 번째 지역의 기본 원...</p>`,
    wrong: ``,
    disc: [{ ans:'B', txt:'정답은 B입니다. 다른 AWS 지역의 ALB, Auto Scaling 그룹 및 EC2 인스턴스를 프로비저닝하면 애플리케이션에 대한 중복성 및 장애 조치 기능이 제공됩니다. CloudFront 배포는 두 번째 지역에 새 ALB에 대한 두 번째 오리진을 생성함으로써 기본 오리진에 문제가 있는 경우 트래픽을 정상 오리진으로 자동 라우팅할 수 있습니다. 이렇게 하면 애플리케이션의 가용성과 내결함성이 유지됩니다. 옵션 A는 Route 53 장애 조치 레코드를 사용하므로 올바르지 않습니다. 이로 인해 클라이언트의 지연 시간과 DNS 확인 시간이 늘어날 수 있습니다. 옵션 C는 애플리케이션의 중요한 구성 요소인 로드 밸런서에 대한 중복성을 제공하지 않기 때문에 올바르지 않습니다. 옵션 D는 첫 번째 지역의 기본 원...' }, { ans:'B', txt:'The correct answer is B. Provisioning an ALB, an Auto Scaling group, and EC2 instances in a different AWS region provides redundancy and failover capability for the application. By creating a second origin for the new ALB in the second region, the CloudFront distribution can automatically route traffic to the healthy origin in case of an issue with the primary origin. This ensures that the appl...' }, { ans:'B', txt:'CloudFront 배포판을 Route 53에 추가할 수 없기 때문에 A는 틀렸습니다. B는 맞습니다. ALB는 단일 지역이고 장애 조치를 수행하지 않기 때문에 C는 틀립니다. D는 작동하지만 이 맥락에서는 과도하게 설계되었습니다.' }, { ans:'B', txt:'A is wrong because CloudFront distros can\'t be added to Route 53. B is correct C is wrong because ALBs are single region and don\'t do failover. D would work, but is overengineered in this context.' }, { ans:'B', txt:'A와 B 모두 작동하지만 A는 장애 조치 수행 측면에서 훨씬 더 나쁘고(DNS에 의존하기 때문에) 이점이 거의 없습니다. CloudFront는 본질적으로 가용성이 높기 때문에 두 번째 CF 배포를 만들어도 성능이 향상되지 않습니다. 애플리케이션의 견고성.' }]
  },
  {
    n: 53,
    en: `A company has an organization in AWS Organizations that has a large number of AWS accounts. One of the AWS accounts is designated as a transit account and has a transit gateway that is shared with all of the other AWS accounts. AWS Site-to-Site VPN connections are configured between all of the company’s global offices and the transit account. The company has AWS Config enabled on all of its accounts.<br/><br/>The company’s networking team needs to centrally manage a list of internal IP address ranges that belong to the global offices. Developers will reference this list to gain access to their applications securely.<br/><br/>Which solution meets these requirements with the LEAST amount of operational overhead?`,
    ko: `회사에는 AWS 계정이 많은 AWS Organizations 조직이 있습니다. AWS 계정 중 하나가 전송 계정으로 지정되고 다른 모든 AWS 계정과 공유되는 전송 게이트웨이가 있습니다. AWS Site-to-Site VPN 연결은 회사의 모든 글로벌 사무소와 전송 계정 간에 구성됩니다. 회사는 모든 계정에서 AWS Config를 활성화했습니다. <br/><br/>회사의 네트워킹 팀은 글로벌 사무소에 속한 내부 IP 주소 범위 목록을 중앙에서 관리해야 합니다. 개발자는 이 목록을 참조하여 애플리케이션에 안전하게 액세스할 수 있습니다. <br/><br/>최소한의 운영 오버헤드로 이러한 요구 사항을 충족하는 솔루션은 무엇입니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Create a JSON file that is hosted in Amazon S3 and that lists all of the internal IP address ranges. Configure an Amazon Simple Notification Service (Amazon SNS) topic in each of the accounts that can be invoked when the JSON file is updated. Subscribe an AWS Lambda function to the SNS topic to update all relevant security group rules with the updated IP address ranges.`, ko:`Amazon S3에서 호스팅되고 모든 내부 IP 주소 범위를 나열하는 JSON 파일을 생성합니다. JSON 파일이 업데이트될 때 호출할 수 있는 각 계정에서 Amazon Simple 알림 서비스(Amazon SNS) 주제를 구성합니다. 업데이트된 IP 주소 범위로 모든 관련 보안 그룹 규칙을 업데이트하려면 SNS 주제에 대한 AWS Lambda 함수를 구독하세요.` },
      { k:'B', en:`Create a new AWS Config managed rule that contains all of the internal IP address ranges. Use the rule to check the security groups in each of the accounts to ensure compliance with the list of IP address ranges. Configure the rule to automatically remediate any noncompliant security group that is detected.`, ko:`모든 내부 IP 주소 범위를 포함하는 새로운 AWS Config 관리형 규칙을 생성합니다. 규칙을 사용하여 각 계정의 보안 그룹을 확인하여 IP 주소 범위 목록을 준수하는지 확인하세요. 감지된 모든 비준수 보안 그룹을 자동으로 교정하도록 규칙을 구성하십시오.` },
      { k:'C', en:`In the transit account, create a VPC prefix list with all of the internal IP address ranges. Use AWS Resource Access Manager to share the prefix list with all of the other accounts. Use the shared prefix list to configure security group rules in the other accounts.`, ko:`대중교통 계정에서 모든 내부 IP 주소 범위가 포함된 VPC 접두사 목록을 생성합니다. AWS Resource Access Manager를 사용하여 접두사 목록을 다른 모든 계정과 공유합니다. 공유 접두사 목록을 사용하여 다른 계정의 보안 그룹 규칙을 구성합니다.` },
      { k:'D', en:`In the transit account, create a security group with all of the internal IP address ranges. Configure the security groups in the other accounts to reference the transit account’s security group by using a nested security group reference of “<transit-account-id>/sg-1a2b3c4d”. </transit-account-id>`, ko:`대중교통 계정에서 모든 내부 IP 주소 범위를 포함하는 보안 그룹을 생성합니다. "라는 중첩된 보안 그룹 참조를 사용하여 전송 계정의 보안 그룹을 참조하도록 다른 계정의 보안 그룹을 구성합니다.<transit-account-id>/sg-1a2b3c4d”. </transit-account-id>` },
    ],
    answer: ["C"],
    vote: '100% C',
    explain: `<p><span class="mark-ok">✅ C</span></p><p>정답은 옵션 C입니다. 이 솔루션에서는 모든 내부 IP 주소 범위가 포함된 전송 계정에 VPC 접두사 목록이 생성된 다음 AWS Resource Access Manager를 사용하여 다른 모든 계정과 공유됩니다. 이를 통해 IP 주소 범위를 중앙에서 관리할 수 있으며 각 계정의 보안 그룹 규칙을 수동으로 업데이트할 필요가 없습니다. 또한 이 솔루션을 사용하면 AWS Config를 사용하여 규정 준수 검사를 실행하고 규정을 준수하지 않는 보안 그룹을 자동으로 교정할 수 있습니다. 옵션 A는 JSON 파일을 수동으로 업데이트해야 하고 개발자가 보안 그룹 규칙을 수동으로 업데이트해야 하므로 올바르지 않습니다. 이로 인해 운영 오버헤드가 발생할 수 있습니다. 옵션 B는 새로운 AWS Config 관리형 규칙을...</p>`,
    wrong: ``,
    disc: [{ ans:'C', txt:'정답은 옵션 C입니다. 이 솔루션에서는 모든 내부 IP 주소 범위가 포함된 전송 계정에 VPC 접두사 목록이 생성된 다음 AWS Resource Access Manager를 사용하여 다른 모든 계정과 공유됩니다. 이를 통해 IP 주소 범위를 중앙에서 관리할 수 있으며 각 계정의 보안 그룹 규칙을 수동으로 업데이트할 필요가 없습니다. 또한 이 솔루션을 사용하면 AWS Config를 사용하여 규정 준수 검사를 실행하고 규정을 준수하지 않는 보안 그룹을 자동으로 교정할 수 있습니다. 옵션 A는 JSON 파일을 수동으로 업데이트해야 하고 개발자가 보안 그룹 규칙을 수동으로 업데이트해야 하므로 올바르지 않습니다. 이로 인해 운영 오버헤드가 발생할 수 있습니다. 옵션 B는 새로운 AWS Config 관리형 규칙을...' }, { ans:'C', txt:'The correct answer is option C. In this solution, a VPC prefix list is created in the transit account with all of the internal IP address ranges, and then shared to all of the other accounts using AWS Resource Access Manager. This allows for central management of the IP address ranges, and eliminates the need for manual updates to security group rules in each account. This solution also allows ...' }, { ans:'C', txt:'A가 아닙니다. SG를 업데이트하려면 JSON 파일, 각 계정의 SNS 주제, Lambda를 유지해야 합니다. 이것은 많은 작업이며 어떤 계정이 JSON Not B를 사용하여 S3를 보유하고 있는지 명확하지 않습니다. 이 경우 https://docs.aws.amazon.com/에 도움이 될 수 있는 관리형 AWS Config 규칙을 찾을 수 없었습니다. config/latest/developerguide/managed-rules-by-aws-config.html (그러나 hart의 관리형 규칙이 기억나지 않으며 이는 원격 사용 사례처럼 들리지 않으므로 시험에서 이것이 나를 속일 수 있습니다.)' }, { ans:'C', txt:'Not A. This requires to maintain the JSON file, SNS topic in each account, Lambda to update SG. This is a lot of work, also not clear what accounts holds the S3 with the JSON Not B. I was not able to spot a managed AWS Config rule that could help in this case https://docs.aws.amazon.com/config/latest/developerguide/managed-rules-by-aws-config.html (but I do not recall managed rule by hart and t...' }, { ans:'C', txt:'https://aws.amazon.com/blogs/networking-and-content-delivery/simplify-network-routing-and-security-administration-with-vpc-prefix-lists/#:~:text=A%20Prefix%20List%20is%20a,Resource%20Access%20Manager%20(RAM).' }]
  },
  {
    n: 54,
    en: `A company runs a new application as a static website in Amazon S3. The company has deployed the application to a production AWS account and uses Amazon CloudFront to deliver the website. The website calls an Amazon API Gateway REST API. An AWS Lambda function backs each API method.<br/><br/>The company wants to create a CSV report every 2 weeks to show each API Lambda function’s recommended configured memory, recommended cost, and the price difference between current configurations and the recommendations. The company will store the reports in an S3 bucket.<br/><br/>Which solution will meet these requirements with the LEAST development time?`,
    ko: `회사는 Amazon S3에서 정적 웹 사이트로 새 애플리케이션을 실행합니다. 회사는 프로덕션 AWS 계정에 애플리케이션을 배포하고 Amazon CloudFront를 사용하여 웹 사이트를 제공합니다. 웹사이트는 Amazon API Gateway REST API를 호출합니다. AWS Lambda 함수는 각 API 메서드를 지원합니다. <br/><br/>회사는 각 API Lambda 함수의 권장 구성 메모리, 권장 비용, 현재 구성과 권장 사항 간의 가격 차이를 표시하기 위해 2주마다 CSV 보고서를 생성하려고 합니다. 회사는 보고서를 S3 버킷에 저장합니다. <br/><br/>가장 짧은 개발 시간으로 이러한 요구 사항을 충족하는 솔루션은 무엇입니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Create a Lambda function that extracts metrics data for each API Lambda function from Amazon CloudWatch Logs for the 2-week period. Collate the data into tabular format. Store the data as a .csv file in an S3 bucket. Create an Amazon EventBridge rule to schedule the Lambda function to run every 2 weeks.`, ko:`2주 동안 Amazon CloudWatch Logs에서 각 API Lambda 함수에 대한 지표 데이터를 추출하는 Lambda 함수를 생성합니다. 데이터를 표 형식으로 대조합니다. 데이터를 S3 버킷에 .csv 파일로 저장합니다. Amazon EventBridge 규칙을 생성하여 Lambda 함수가 2주마다 실행되도록 예약합니다.` },
      { k:'B', en:`Opt in to AWS Compute Optimizer. Create a Lambda function that calls the ExportLambdaFunctionRecommendations operation. Export the .csv file to an S3 bucket. Create an Amazon EventBridge rule to schedule the Lambda function to run every 2 weeks.`, ko:`AWS Compute Optimizer를 선택합니다. ImportLambdaFunctionRecommendations 작업을 호출하는 Lambda 함수를 생성합니다. .csv 파일을 S3 버킷으로 내보냅니다. Amazon EventBridge 규칙을 생성하여 Lambda 함수가 2주마다 실행되도록 예약합니다.` },
      { k:'C', en:`Opt in to AWS Compute Optimizer. Set up enhanced infrastructure metrics. Within the Compute Optimizer console, schedule a job to export the Lambda recommendations to a .csv file. Store the file in an S3 bucket every 2 weeks.`, ko:`AWS Compute Optimizer를 선택합니다. 향상된 인프라 측정항목을 설정하세요. Compute Optimizer 콘솔 내에서 Lambda 권장 사항을 .csv 파일로 내보내는 작업을 예약합니다. 2주마다 S3 버킷에 파일을 저장합니다.` },
      { k:'D', en:`Purchase the AWS Business Support plan for the production account. Opt in to AWS Compute Optimizer for AWS Trusted Advisor checks. In the Trusted Advisor console, schedule a job to export the cost optimization checks to a .csv file. Store the file in an S3 bucket every 2 weeks.`, ko:`프로덕션 계정에 대한 AWS Business Support 플랜을 구매합니다. AWS Trusted Advisor 점검을 위해 AWS Compute Optimizer를 선택합니다. Trusted Advisor 콘솔에서 비용 최적화 검사를 .csv 파일로 내보내는 작업을 예약합니다. 2주마다 S3 버킷에 파일을 저장합니다.` },
    ],
    answer: ["B"],
    vote: '81% B, 12% D, 8% C',
    explain: `<p><span class="mark-ok">✅ B</span></p><p>정답은 B입니다. AWS Compute Optimizer를 선택하고 ImportLambdaFunctionRecommendations 작업을 호출하는 Lambda 함수를 생성하는 것이 개발 시간이 가장 짧은 솔루션입니다. 이 옵션을 사용하면 내장된 AWS Compute Optimizer 서비스를 사용하여 지표 데이터를 추출하고 이를 CSV 파일로 내보낸 다음 S3 버킷에 저장할 수 있습니다. 옵션 A는 지표 데이터를 추출하고 이를 표 형식으로 대조하는 Lambda 함수의 개발이 필요하므로 올바르지 않으며 이로 인해 개발 시간이 추가됩니다. 옵션 C는 향상된 인프라 측정항목 설정이 필요하여 개발 시간이 추가되므로 올바르지 않습니다. 옵션 D는 AWS Business Support 플랜을 구매하고 Trust...</p>`,
    wrong: `<p><span class="mark-no">❌ C</span> — 정답은 C입니다. 옵션 A에는 CloudWatch Logs에서 지표 데이터를 추출하고 CSV 보고서를 생성하는 사용자 지정 Lambda 함수를 생성하는 작업이 포함되는데, 이는 Compute Optimizer 서비스를 사용할 때보다 개발 시간이 더 많이 필요합니다. 옵션 B는 Compute Optimizer 및 Lambda 함수를 사용하므로 부분적으로 정확</p><p><span class="mark-no">❌ D</span> — 람다 = 개발. 옵션 D에는 개발이 없습니다. 개발에 익숙하지 않은 경우 간단한 Lambda 함수를 게시하려면 AWS Lambda 내에서 올바르게 실행하기 위해 모든 Node.js, Python 또는 모든 프로그래밍 언어 라이브러리를 래핑해야 할 수 있습니다. Trusted Advisor(GUI) 구성 또는 작업 예약은 개발로 간주되지 않습니다.</p>`,
    disc: [{ ans:'B', txt:'정답은 B입니다. AWS Compute Optimizer를 선택하고 ImportLambdaFunctionRecommendations 작업을 호출하는 Lambda 함수를 생성하는 것이 개발 시간이 가장 짧은 솔루션입니다. 이 옵션을 사용하면 내장된 AWS Compute Optimizer 서비스를 사용하여 지표 데이터를 추출하고 이를 CSV 파일로 내보낸 다음 S3 버킷에 저장할 수 있습니다. 옵션 A는 지표 데이터를 추출하고 이를 표 형식으로 대조하는 Lambda 함수의 개발이 필요하므로 올바르지 않으며 이로 인해 개발 시간이 추가됩니다. 옵션 C는 향상된 인프라 측정항목 설정이 필요하여 개발 시간이 추가되므로 올바르지 않습니다. 옵션 D는 AWS Business Support 플랜을 구매하고 Trust...' }, { ans:'B', txt:'The correct answer is B. Opting in to AWS Compute Optimizer and creating a Lambda function that calls the ExportLambdaFunctionRecommendations operation is the least development time solution. This option allows you to use the built-in AWS Compute Optimizer service to extract metrics data and export it as a CSV file, which can then be stored in an S3 bucket. Option A is not correct because it re...' }, { ans:'B', txt:'AWS 컴퓨팅 옵티마이저+ 람다' }, { ans:'B', txt:'AWS compute optimizer+ lambda' }, { ans:'C', txt:'정답은 C입니다. 옵션 A에는 CloudWatch Logs에서 지표 데이터를 추출하고 CSV 보고서를 생성하는 사용자 지정 Lambda 함수를 생성하는 작업이 포함되는데, 이는 Compute Optimizer 서비스를 사용할 때보다 개발 시간이 더 많이 필요합니다. 옵션 B는 Compute Optimizer 및 Lambda 함수를 사용하므로 부분적으로 정확하지만 Compute Optimizer 콘솔 내에서 직접 반복 내보내기를 예약하는 기능이 없습니다. 옵션 D는 모범 사례 및 리소스를 모니터링하기 위한 서비스인 AWS Trusted Advisor를 사용할 것을 제안하지만 이 시나리오에 필요한 특정 Lambda 함수 메모리 및 비용 권장 사항은 제공하지 않습니다.' }]
  },
  {
    n: 55,
    en: `A company’s factory and automation applications are running in a single VPC. More than 20 applications run on a combination of Amazon EC2, Amazon Elastic Container Service (Amazon ECS), and Amazon RDS.<br/><br/>The company has software engineers spread across three teams. One of the three teams owns each application, and each time is responsible for the cost and performance of all of its applications. Team resources have tags that represent their application and team. The teams use IAM access for daily activities.<br/><br/>The company needs to determine which costs on the monthly AWS bill are attributable to each application or team. The company also must be able to create reports to compare costs from the last 12 months and to help forecast costs for the next 12 months. A solutions architect must recommend an AWS Billing and Cost Management solution that provides these cost reports.<br/><br/>Which combination of actions will meet these requirements? (Choose three.)`,
    ko: `회사의 공장 및 자동화 애플리케이션이 단일 VPC에서 실행되고 있습니다. Amazon EC2, Amazon Elastic Container Service(Amazon ECS) 및 Amazon RDS의 조합에서 20개 이상의 애플리케이션이 실행됩니다. <br/><br/>이 회사에는 세 팀에 소프트웨어 엔지니어가 분산되어 있습니다. 세 팀 중 하나가 각 애플리케이션을 소유하며, 매번 모든 애플리케이션의 비용과 성능을 책임집니다. 팀 리소스에는 해당 애플리케이션과 팀을 나타내는 태그가 있습니다. 팀은 일상 활동에 IAM 액세스를 사용합니다. <br/><br/>회사는 월별 AWS 청구서에서 각 애플리케이션이나 팀에 발생한 비용을 확인해야 합니다. 또한 회사는 지난 12개월의 비용을 비교하고 향후 12개월의 비용을 예측하는 데 도움이 되는 보고서를 작성할 수 있어야 합니다. 솔루션 아키텍트는 이러한 비용 보고서를 제공하는 AWS Billing and Cost Management 솔루션을 권장해야 합니다. <br/><br/>이러한 요구 사항을 충족하는 작업 조합은 무엇입니까? (3개를 선택하세요.)`,
    type: 'multi', multiCount: 3,
    choices: [
      { k:'A', en:`Activate the user-define cost allocation tags that represent the application and the team.`, ko:`애플리케이션과 팀을 나타내는 사용자 정의 비용 할당 태그를 활성화합니다.` },
      { k:'B', en:`Activate the AWS generated cost allocation tags that represent the application and the team.`, ko:`애플리케이션과 팀을 나타내는 AWS 생성 비용 할당 태그를 활성화합니다.` },
      { k:'C', en:`Create a cost category for each application in Billing and Cost Management.`, ko:`Billing and Cost Management에서 각 애플리케이션에 대한 비용 범주를 생성합니다.` },
      { k:'D', en:`Activate IAM access to Billing and Cost Management.`, ko:`Billing and Cost Management에 대한 IAM 액세스를 활성화합니다.` },
      { k:'E', en:`Create a cost budget.`, ko:`비용 예산을 수립합니다.` },
      { k:'F', en:`Enable Cost Explorer.`, ko:`비용 탐색기를 활성화합니다.` },
    ],
    answer: [],
    vote: '52% ACF, 48% ADF',
    explain: ``,
    wrong: `<p><span class="mark-no">❌ A</span> — A, C, F는 회사의 애플리케이션과 팀에 필요한 비용 보고서와 분석을 제공하므로 정답입니다. A. 애플리케이션과 팀을 나타내는 사용자 정의 비용 할당 태그를 활성화하면 회사는 특정 애플리케이션과 팀에 비용을 할당할 수 있습니다. 이를 통해 회사는 각 애플리케이션과 팀에서 비용이 얼마나 드는지 확인할 수 있으며, 이는 비용 예측 및 예산 책정에 중요합니다.</p><p><span class="mark-no">❌ C</span> — A, C, F는 회사의 애플리케이션과 팀에 필요한 비용 보고서와 분석을 제공하므로 정답입니다. A. 애플리케이션과 팀을 나타내는 사용자 정의 비용 할당 태그를 활성화하면 회사는 특정 애플리케이션과 팀에 비용을 할당할 수 있습니다. 이를 통해 회사는 각 애플리케이션과 팀에서 비용이 얼마나 드는지 확인할 수 있으며, 이는 비용 예측 및 예산 책정에 중요합니다.</p><p><span class="mark-no">❌ D</span> — 올바른 ADF - 리소스에 태그가 지정되었으므로 C에는 ?가 필요하지 않을 수 있습니다.</p><p><span class="mark-no">❌ F</span> — A, C, F는 회사의 애플리케이션과 팀에 필요한 비용 보고서와 분석을 제공하므로 정답입니다. A. 애플리케이션과 팀을 나타내는 사용자 정의 비용 할당 태그를 활성화하면 회사는 특정 애플리케이션과 팀에 비용을 할당할 수 있습니다. 이를 통해 회사는 각 애플리케이션과 팀에서 비용이 얼마나 드는지 확인할 수 있으며, 이는 비용 예측 및 예산 책정에 중요합니다.</p>`,
    disc: [{ ans:'A, C, F', txt:'A, C, F는 회사의 애플리케이션과 팀에 필요한 비용 보고서와 분석을 제공하므로 정답입니다. A. 애플리케이션과 팀을 나타내는 사용자 정의 비용 할당 태그를 활성화하면 회사는 특정 애플리케이션과 팀에 비용을 할당할 수 있습니다. 이를 통해 회사는 각 애플리케이션과 팀에서 비용이 얼마나 드는지 확인할 수 있으며, 이는 비용 예측 및 예산 책정에 중요합니다. C. Billing and Cost Management에서 각 애플리케이션에 대한 비용 범주를 생성하면 회사에서 애플리케이션별로 비용을 그룹화할 수 있습니다. 이를 통해 각 애플리케이션과 관련된 비용을 더 쉽게 이해하고 시간이 지남에 따라 다양한 애플리케이션의 비용을 비교할 수 있습니다. F. Cost Explorer를 활성화하면 회사는 시간 경과에...' }, { ans:'A, C, F', txt:'A, C and F are the correct answers because they provide the required cost reports and analysis for the company\'s applications and teams. A. Activating user-defined cost allocation tags that represent the application and the team allows the company to assign costs to specific applications and teams. This allows the company to see how much each application and team is costing them, which is impor...' }, { ans:'A, D, F', txt:'올바른 ADF - 리소스에 태그가 지정되었으므로 C에는 ?가 필요하지 않을 수 있습니다.' }, { ans:'A, D, F', txt:'Correct ADF - SInce resources are tagged, C may not require ?' }, { ans:'A, C, F', txt:'옵션 ACF 및 NOT ADF - 비용 할당은 조직 내에서 누가 무엇을 지출하는지 식별하는 데 도움이 됩니다. 비용 범주는 AWS 비용을 고유한 내부 비즈니스 구조에 매핑하는 데 도움이 되는 비용 할당 서비스입니다. https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/manage-cost-categories.html' }]
  },
  {
    n: 56,
    en: `An AWS customer has a web application that runs on premises. The web application fetches data from a third-party API that is behind a firewall. The third party accepts only one public CIDR block in each client’s allow list.<br/><br/>The customer wants to migrate their web application to the AWS Cloud. The application will be hosted on a set of Amazon EC2 instances behind an Application Load Balancer (ALB) in a VPC. The ALB is located in public subnets. The EC2 instances are located in private subnets. NAT gateways provide internet access to the private subnets.<br/><br/>How should a solutions architect ensure that the web application can continue to call the third-party API after the migration?`,
    ko: `AWS 고객은 온프레미스에서 실행되는 웹 애플리케이션을 보유하고 있습니다. 웹 애플리케이션은 방화벽 뒤에 있는 타사 API에서 데이터를 가져옵니다. 타사는 각 클라이언트의 허용 목록에서 하나의 공개 CIDR 블록만 허용합니다. <br/><br/>고객은 웹 애플리케이션을 AWS 클라우드로 마이그레이션하려고 합니다. 애플리케이션은 VPC의 ALB(Application Load Balancer) 뒤의 Amazon EC2 인스턴스 세트에서 호스팅됩니다. ALB는 퍼블릭 서브넷에 있습니다. EC2 인스턴스는 프라이빗 서브넷에 있습니다. NAT 게이트웨이는 프라이빗 서브넷에 대한 인터넷 액세스를 제공합니다. <br/><br/>솔루션 설계자는 마이그레이션 후에도 웹 애플리케이션이 계속해서 타사 API를 호출할 수 있도록 어떻게 보장해야 합니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Associate a block of customer-owned public IP addresses to the VPC. Enable public IP addressing for public subnets in the VPC.`, ko:`고객 소유의 퍼블릭 IP 주소 블록을 VPC에 연결합니다. VPC의 퍼블릭 서브넷에 대한 퍼블릭 IP 주소 지정을 활성화합니다.` },
      { k:'B', en:`Register a block of customer-owned public IP addresses in the AWS account. Create Elastic IP addresses from the address block and assign them to the NAT gateways in the VPC.`, ko:`AWS 계정에 고객 소유의 공용 IP 주소 블록을 등록합니다. 주소 블록에서 탄력적 IP 주소를 생성하고 이를 VPC의 NAT 게이트웨이에 할당합니다.` },
      { k:'C', en:`Create Elastic IP addresses from the block of customer-owned IP addresses. Assign the static Elastic IP addresses to the ALB.`, ko:`고객 소유 IP 주소 블록에서 탄력적 IP 주소를 생성합니다. ALB에 고정 탄력적 IP 주소를 할당합니다.` },
      { k:'D', en:`Register a block of customer-owned public IP addresses in the AWS account. Set up AWS Global Accelerator to use Elastic IP addresses from the address block. Set the ALB as the accelerator endpoint.`, ko:`AWS 계정에 고객 소유의 공용 IP 주소 블록을 등록합니다. 주소 블록의 탄력적 IP 주소를 사용하도록 AWS Global Accelerator를 설정합니다. ALB를 가속기 엔드포인트로 설정하십시오.` },
    ],
    answer: ["B"],
    vote: '100% B',
    explain: `<p><span class="mark-ok">✅ B</span></p><p>올바른 해결책은 B입니다. AWS 계정에 고객 소유의 퍼블릭 IP 주소 블록을 등록합니다. 주소 블록에서 탄력적 IP 주소를 생성하고 이를 VPC의 NAT 게이트웨이에 할당합니다. 이렇게 하면 웹 애플리케이션이 NAT 게이트웨이에 할당된 고객 소유 공용 IP 주소를 사용하여 마이그레이션 후에도 계속해서 타사 API를 호출할 수 있습니다. 이렇게 하면 타사 API가 허용 목록에 있는 고객 소유 IP 주소에서 들어오는 트래픽만 볼 수 있습니다. 옵션 A, C, D는 이 맥락에서 의미가 없습니다.</p>`,
    wrong: ``,
    disc: [{ ans:'B', txt:'올바른 해결책은 B입니다. AWS 계정에 고객 소유의 퍼블릭 IP 주소 블록을 등록합니다. 주소 블록에서 탄력적 IP 주소를 생성하고 이를 VPC의 NAT 게이트웨이에 할당합니다. 이렇게 하면 웹 애플리케이션이 NAT 게이트웨이에 할당된 고객 소유 공용 IP 주소를 사용하여 마이그레이션 후에도 계속해서 타사 API를 호출할 수 있습니다. 이렇게 하면 타사 API가 허용 목록에 있는 고객 소유 IP 주소에서 들어오는 트래픽만 볼 수 있습니다. 옵션 A, C, D는 이 맥락에서 의미가 없습니다.' }, { ans:'B', txt:'The correct solution is B. Register a block of customer-owned public IP addresses in the AWS account. Create Elastic IP addresses from the address block and assign them to the NAT gateways in the VPC. This will ensure that the web application can continue to call the third-party API after the migration by using the customer-owned public IP addresses that were assigned to the NAT gateways. This ...' }, { ans:'B', txt:'이 시나리오에서 EC2 인스턴스는 NAT 게이트웨이를 통해 3P API에 액세스합니다. 3P API FW는 NAT 게이트웨이의 IP를 참조하세요. 탄력적 IP를 NAT 게이트웨이에 할당할 수 있고, AWS 계정으로 가져온 풀의 IP 주소를 탄력적 IP에 할당할 수 있습니다. 따라서 B가 맞습니다. https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/elastic-ip-addresses-eip.html' }, { ans:'B', txt:'In this scenario EC2 instances access the 3P APIs via NAT Gateway. 3P API FW see IP of the NAT Gateway. You can assign Elastic IP to NAT Gateway and you can allocate an IP address from a pool that you have brought to your AWS account to the Elastic IP. Thus B is correct. https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/elastic-ip-addresses-eip.html' }, { ans:'B', txt:'정답은 B이다' }]
  },
  {
    n: 57,
    en: `A company with several AWS accounts is using AWS Organizations and service control policies (SCPs). An administrator created the following SCP and has attached it to an organizational unit (OU) that contains AWS account 1111-1111-1111:<br/><br/><img src="https://img.examtopics.com/aws-certified-solutions-architect-professional-sap-c02/image6.png"/><br/><br/>Developers working in account 1111-1111-1111 complain that they cannot create Amazon S3 buckets. How should the administrator address this problem?`,
    ko: `여러 AWS 계정을 보유한 회사가 AWS Organizations 및 서비스 제어 정책(SCP)을 사용하고 있습니다. 관리자가 다음 SCP를 생성하여 AWS 계정 1111-1111-1111이 포함된 조직 단위(OU)에 연결했습니다. <br/><br/><img src="https://img.examtopics.com/aws-certified-solutions-architect-professional-sap-c02/image6.png"/><br/><br/>계정 1111-1111-1111에서 작업하는 개발자는 Amazon S3 버킷을 생성할 수 없다고 불평합니다. 관리자는 이 문제를 어떻게 해결해야 합니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Add s3:CreateBucket with “Allow” effect to the SCP.`, ko:`"허용" 효과가 있는 s3:CreateBucket을 SCP에 추가합니다.` },
      { k:'B', en:`Remove the account from the OU, and attach the SCP directly to account 1111-1111-1111.`, ko:`OU에서 계정을 제거하고 SCP를 계정 1111-1111-1111에 직접 연결합니다.` },
      { k:'C', en:`Instruct the developers to add Amazon S3 permissions to their IAM entities.`, ko:`개발자에게 IAM 엔터티에 Amazon S3 권한을 추가하도록 지시합니다.` },
      { k:'D', en:`Remove the SCP from account 1111-1111-1111.`, ko:`계정 1111-1111-1111에서 SCP를 제거합니다.` },
    ],
    answer: ["C"],
    vote: '88% C, 12% A',
    explain: `<p><span class="mark-ok">✅ C</span></p><p>SCP가 권한을 부여하지 않습니다</p>`,
    wrong: `<p><span class="mark-no">❌ A</span> — SCP는 혼란스럽습니다. https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps_strategies.html#orgs_policies_allowlist 그들은 조직이 쉽게 제어할 수 있도록 이 아이디어를 가져왔습니다. C에서는 개발자에게 자신만의 권한을 추가하도</p>`,
    disc: [{ ans:'C', txt:'SCP가 권한을 부여하지 않습니다' }, { ans:'C', txt:'SCP doesn’t grant permission' }, { ans:'C', txt:'C, SCP는 방해 요소일 뿐이므로 사용자에게 직접적인 권한이 필요합니다.' }, { ans:'C', txt:'C, SCP is just a distractor, the users need direct permissions' }, { ans:'C', txt:'C - 사용자 및 역할에는 적절한 IAM 권한 정책을 통해 권한이 부여되어야 합니다. IAM 권한 정책이 없는 사용자는 해당 SCP가 모든 서비스와 모든 작업을 허용하더라도 전혀 액세스할 수 없습니다.' }]
  },
  {
    n: 58,
    en: `A company has a monolithic application that is critical to the company’s business. The company hosts the application on an Amazon EC2 instance that runs Amazon Linux 2. The company’s application team receives a directive from the legal department to back up the data from the instance’s encrypted Amazon Elastic Block Store (Amazon EBS) volume to an Amazon S3 bucket. The application team does not have the administrative SSH key pair for the instance. The application must continue to serve the users.<br/><br/>Which solution will meet these requirements?`,
    ko: `회사에는 회사 비즈니스에 중요한 모놀리식 애플리케이션이 있습니다. 회사는 Amazon Linux 2를 실행하는 Amazon EC2 인스턴스에서 애플리케이션을 호스팅합니다. 회사의 애플리케이션 팀은 법무 부서로부터 인스턴스의 암호화된 Amazon Elastic Block Store(Amazon EBS) 볼륨의 데이터를 Amazon S3 버킷에 백업하라는 지시를 받습니다. . 애플리케이션 팀에는 인스턴스에 대한 관리 SSH 키 쌍이 없습니다. 애플리케이션은 계속해서 사용자에게 서비스를 제공해야 합니다. <br/><br/>어떤 솔루션이 이러한 요구 사항을 충족합니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Attach a role to the instance with permission to write to Amazon S3. Use the AWS Systems Manager Session Manager option to gain access to the instance and run commands to copy data into Amazon S3.`, ko:`Amazon S3에 쓸 수 있는 권한이 있는 인스턴스에 역할을 연결합니다. AWS 시스템 관리자 세션 관리자 옵션을 사용하여 인스턴스에 액세스하고 명령을 실행하여 Amazon S3에 데이터를 복사합니다.` },
      { k:'B', en:`Create an image of the instance with the reboot option turned on. Launch a new EC2 instance from the image. Attach a role to the new instance with permission to write to Amazon S3. Run a command to copy data into Amazon S3.`, ko:`재부팅 옵션이 활성화된 인스턴스의 이미지를 생성합니다. 이미지에서 새 EC2 인스턴스를 시작합니다. Amazon S3에 쓰기 권한이 있는 새 인스턴스에 역할을 연결합니다. Amazon S3에 데이터를 복사하는 명령을 실행합니다.` },
      { k:'C', en:`Take a snapshot of the EBS volume by using Amazon Data Lifecycle Manager (Amazon DLM). Copy the data to Amazon S3.`, ko:`Amazon Data Lifecycle Manager(Amazon DLM)를 사용하여 EBS 볼륨의 스냅샷을 만듭니다. 데이터를 Amazon S3에 복사합니다.` },
      { k:'D', en:`Create an image of the instance. Launch a new EC2 instance from the image. Attach a role to the new instance with permission to write to Amazon S3. Run a command to copy data into Amazon S3.`, ko:`인스턴스의 이미지를 생성합니다. 이미지에서 새 EC2 인스턴스를 시작합니다. Amazon S3에 쓰기 권한이 있는 새 인스턴스에 역할을 연결합니다. Amazon S3에 데이터를 복사하는 명령을 실행합니다.` },
    ],
    answer: ["A"],
    vote: '56% A, 43% C',
    explain: `<p><span class="mark-ok">✅ A</span></p><p>s3에 데이터 백업을 가져옵니다. aws는 s3에서 스냅샷을 볼 수 없습니다</p>`,
    wrong: `<p><span class="mark-no">❌ C</span> — 정답은 C입니다. Amazon Data Lifecycle Manager(DLM)를 사용하여 EBS 볼륨의 스냅샷을 생성하면 인스턴스나 해당 SSH 키 페어에 액세스할 필요 없이 볼륨 백업을 생성할 수 있으므로 요구 사항을 충족합니다. 또한 DLM을 사용하면 특정 간격으로 백업이 발생하도록 예약할 수 있으며 스냅샷을 S3 버킷에 복사할 수도 있습니다. 백업은</p><p><span class="mark-no">❌ D</span> — A - 미션 크리티컬 애플리케이션이므로 실행 불가능 C - 암호화되었기 때문에 스냅샷을 찍을 수 없음 D - https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AmazonS3.html</p>`,
    disc: [{ ans:'C', txt:'정답은 C입니다. Amazon Data Lifecycle Manager(DLM)를 사용하여 EBS 볼륨의 스냅샷을 생성하면 인스턴스나 해당 SSH 키 페어에 액세스할 필요 없이 볼륨 백업을 생성할 수 있으므로 요구 사항을 충족합니다. 또한 DLM을 사용하면 특정 간격으로 백업이 발생하도록 예약할 수 있으며 스냅샷을 S3 버킷에 복사할 수도 있습니다. 백업은 EBS 볼륨 수준에서 수행되므로 이 접근 방식은 실행 중인 애플리케이션에 영향을 미치지 않습니다. 옵션 A는 올바르지 않습니다. 인스턴스에는 S3에 쓰기 권한이 있고 Systems Manager Session Manager를 통해 인스턴스에 액세스할 수 있는 권한이 있는 IAM 역할이 필요하기 때문입니다. 옵션 B는 실행 중인 애플리케이션에 영향을 ...' }, { ans:'C', txt:'The correct answer is C. Taking a snapshot of the EBS volume using Amazon Data Lifecycle Manager (DLM) will meet the requirements because it allows you to create a backup of the volume without the need to access the instance or its SSH key pair. Additionally, DLM allows you to schedule the backups to occur at specific intervals and also enables you to copy the snapshots to an S3 bucket. This ap...' }, { ans:'A', txt:'s3에 데이터 백업을 가져옵니다. aws는 s3에서 스냅샷을 볼 수 없습니다' }, { ans:'A', txt:'taking a backup of the data to s3. aws doesn\'t allow up to view snapshots in s3' }, { ans:'C', txt:'옵션 A는 SSM 세션 관리자를 통해 연결해야 하는 수동 프로세스입니다. 너무 지루하고 백업을 유지하는 데 막대한 수동 작업이 필요합니다. 따라서 C를 사용하면 S3에서 스냅샷을 관리할 수 없지만 문제가 발생하면 복원할 수 있습니다.' }]
  },
  {
    n: 59,
    en: `A solutions architect needs to copy data from an Amazon S3 bucket m an AWS account to a new S3 bucket in a new AWS account. The solutions architect must implement a solution that uses the AWS CLI.<br/><br/>Which combination of steps will successfully copy the data? (Choose three.)`,
    ko: `솔루션 아키텍트는 AWS 계정의 Amazon S3 버킷에서 새 AWS 계정의 새 S3 버킷으로 데이터를 복사해야 합니다. 솔루션 아키텍트는 AWS CLI를 사용하는 솔루션을 구현해야 합니다. <br/><br/>데이터를 성공적으로 복사하려면 어떤 단계를 조합해야 합니까? (3개를 선택하세요.)`,
    type: 'multi', multiCount: 3,
    choices: [
      { k:'A', en:`Create a bucket policy to allow the source bucket to list its contents and to put objects and set object ACLs in the destination bucket. Attach the bucket policy to the destination bucket.`, ko:`원본 버킷이 해당 콘텐츠를 나열하고 대상 버킷에 객체를 배치하고 객체 ACL을 설정할 수 있도록 버킷 정책을 생성합니다. 버킷 정책을 대상 버킷에 연결합니다.` },
      { k:'B', en:`Create a bucket policy to allow a user in the destination account to list the source bucket’s contents and read the source bucket’s objects. Attach the bucket policy to the source bucket.`, ko:`대상 계정의 사용자가 원본 버킷의 콘텐츠를 나열하고 원본 버킷의 객체를 읽을 수 있도록 허용하는 버킷 정책을 만듭니다. 버킷 정책을 원본 버킷에 연결합니다.` },
      { k:'C', en:`Create an IAM policy in the source account. Configure the policy to allow a user in the source account to list contents and get objects in the source bucket, and to list contents, put objects, and set object ACLs in the destination bucket. Attach the policy to the user.`, ko:`원본 계정에서 IAM 정책을 생성합니다. 원본 계정의 사용자가 원본 버킷에서 콘텐츠를 나열하고 객체를 가져올 수 있도록 허용하고, 대상 버킷에서 콘텐츠를 나열하고 객체를 넣고 객체 ACL을 설정할 수 있도록 정책을 구성합니다. 정책을 사용자에게 연결합니다.` },
      { k:'D', en:`Create an IAM policy in the destination account. Configure the policy to allow a user in the destination account to list contents and get objects in the source bucket, and to list contents, put objects, and set objectACLs in the destination bucket. Attach the policy to the user.`, ko:`대상 계정에 IAM 정책을 생성합니다. 대상 계정의 사용자가 원본 버킷에서 콘텐츠를 나열하고 객체를 가져올 수 있도록 허용하고, 대상 버킷에서 콘텐츠를 나열하고 객체를 넣고 objectACL을 설정할 수 있도록 정책을 구성합니다. 정책을 사용자에게 연결합니다.` },
      { k:'E', en:`Run the aws s3 sync command as a user in the source account. Specify the source and destination buckets to copy the data.`, ko:`원본 계정의 사용자로 aws s3 sync 명령을 실행합니다. 데이터를 복사할 소스 및 대상 버킷을 지정합니다.` },
      { k:'F', en:`Run the aws s3 sync command as a user in the destination account. Specify the source and destination buckets to copy the data.`, ko:`대상 계정의 사용자로 aws s3 sync 명령을 실행합니다. 데이터를 복사할 소스 및 대상 버킷을 지정합니다.` },
    ],
    answer: [],
    vote: '95% BDF',
    explain: ``,
    wrong: `<p><span class="mark-no">❌ B</span> — "위 명령은 대상 AWS IAM 사용자 계정 자격 증명으로만 실행해야 합니다. 그렇지 않으면 대상 S3 버킷에 복사된 객체는 여전히 원본 계정 권한을 가지며 대상 계정 사용자가 액세스할 수 없습니다." https://medium.com/tensult/copy-s3-bucket-objects-across-aws-accounts-e46c15c4b9e1에 따르면</p><p><span class="mark-no">❌ C</span> — BCE should also work Create bucket policy at destination bucket to allow permission on source aws user
Create IAM policy for source aws user to list/get/put on both buckets
Run s3 sync command from so</p><p><span class="mark-no">❌ D</span> — "위 명령은 대상 AWS IAM 사용자 계정 자격 증명으로만 실행해야 합니다. 그렇지 않으면 대상 S3 버킷에 복사된 객체는 여전히 원본 계정 권한을 가지며 대상 계정 사용자가 액세스할 수 없습니다." https://medium.com/tensult/copy-s3-bucket-objects-across-aws-accounts-e46c15c4b9e1에 따르면</p><p><span class="mark-no">❌ E</span> — 문제는 AWS CLI를 사용하여 데이터를 성공적으로 복사하는 단계의 조합을 요구하는 것입니다. 정답은 B, D, E입니다. B단계: 대상 계정의 사용자가 소스 버킷의 콘텐츠를 나열하고 읽을 수 있도록 허용하는 버킷 정책을 소스 계정에 생성해야 합니다. D단계: 사용자가 대상 버킷에 객체 ACL을 나열, 배치 및 설정할 수 있도록 대상 계정에 IAM 정책을 </p><p><span class="mark-no">❌ F</span> — "위 명령은 대상 AWS IAM 사용자 계정 자격 증명으로만 실행해야 합니다. 그렇지 않으면 대상 S3 버킷에 복사된 객체는 여전히 원본 계정 권한을 가지며 대상 계정 사용자가 액세스할 수 없습니다." https://medium.com/tensult/copy-s3-bucket-objects-across-aws-accounts-e46c15c4b9e1에 따르면</p>`,
    disc: [{ ans:'B, D, F', txt:'"위 명령은 대상 AWS IAM 사용자 계정 자격 증명으로만 실행해야 합니다. 그렇지 않으면 대상 S3 버킷에 복사된 객체는 여전히 원본 계정 권한을 가지며 대상 계정 사용자가 액세스할 수 없습니다." https://medium.com/tensult/copy-s3-bucket-objects-across-aws-accounts-e46c15c4b9e1에 따르면.' }, { ans:'B, D, F', txt:'"The above command should be executed with destination AWS IAM user account credentials only otherwise the copied objects in destination S3 bucket will still have the source account permissions and won’t be accessible by destination account users." According to https://medium.com/tensult/copy-s3-bucket-objects-across-aws-accounts-e46c15c4b9e1.' }, { ans:'B, D, F', txt:'BDF로 전환합니다. 대상 계정의 사용자가 원본 버킷에 액세스하고 해당 콘텐츠를 나열하고 객체를 읽는 데 필요한 권한을 가지려면 B 단계가 필요합니다. 대상 계정의 사용자가 대상 버킷에 액세스하고 콘텐츠를 나열하고, 객체를 넣고, 객체 ACL을 설정하는 데 필요한 권한을 가지려면 D 단계가 필요합니다. aws s3 sync 명령은 IAM 사용자를 사용하여 실행해야 하기 때문에 F 단계가 필요합니다. 개체가 복사된 후 대상 계정의 사용자에 대해 적절한 권한을 갖도록 대상 계정의 자격 증명입니다. 다른 선택은 올바르지 않습니다. A.와 C.는 원본 계정에서 정책을 생성하는 것에 관한 것이지만 데이터에 액세스하려는 사용자는 대상 계정에 있습니다. E.는 원본 계정으로 명령을 실행하는 것에 관한 것입니다. 대...' }, { ans:'B, D, F', txt:'I switch to BDF; Step B is necessary so that the user in the destination account has the necessary permissions to access the source bucket and list its contents, read its objects. Step D is needed so that the user in the destination account has the necessary permissions to access the destination bucket and list contents, put objects, and set object ACLs Step F is necessary because the aws s3 sy...' }, { ans:'B, D, F', txt:'B. 대상 계정의 사용자가 원본 버킷의 콘텐츠를 나열하고 원본 버킷의 객체를 읽을 수 있도록 허용하는 버킷 정책을 만듭니다. 버킷 정책을 원본 버킷에 연결합니다. 이 단계에서는 대상 계정에 원본 버킷의 데이터에 액세스하는 데 필요한 권한이 있는지 확인합니다. D. 대상 계정에 IAM 정책을 생성합니다. 대상 계정의 사용자가 원본 버킷에서 콘텐츠를 나열하고 객체를 가져올 수 있도록 허용하고, 대상 버킷에서 콘텐츠를 나열하고 객체를 넣고 객체 ACL을 설정할 수 있도록 정책을 구성합니다. 정책을 사용자에게 연결합니다. 이 단계에서는 대상 계정의 사용자가 원본 버킷의 콘텐츠에 액세스하고 대상 버킷에 쓰는 데 필요한 권한을 제공합니다.' }]
  },
  {
    n: 60,
    en: `A company built an application based on AWS Lambda deployed in an AWS CloudFormation stack. The last production release of the web application introduced an issue that resulted in an outage lasting several minutes. A solutions architect must adjust the deployment process to support a canary release.<br/><br/>Which solution will meet these requirements?`,
    ko: `한 회사는 AWS CloudFormation 스택에 배포된 AWS Lambda를 기반으로 애플리케이션을 구축했습니다. 웹 애플리케이션의 마지막 프로덕션 릴리스에서는 몇 분 동안 중단이 발생하는 문제가 발생했습니다. 솔루션 설계자는 Canary 릴리스를 지원하도록 배포 프로세스를 조정해야 합니다. <br/><br/>어떤 솔루션이 이러한 요구 사항을 충족합니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Create an alias for every new deployed version of the Lambda function. Use the AWS CLI update-alias command with the routing-config parameter to distribute the load.`, ko:`새로 배포된 모든 버전의 Lambda 함수에 대한 별칭을 생성합니다. AWS CLI update-alias 명령을 Routing-config 파라미터와 함께 사용하여 로드를 분산하십시오.` },
      { k:'B', en:`Deploy the application into a new CloudFormation stack. Use an Amazon Route 53 weighted routing policy to distribute the load.`, ko:`애플리케이션을 새로운 CloudFormation 스택에 배포합니다. 부하를 분산하려면 Amazon Route 53 가중치 기반 라우팅 정책을 사용하십시오.` },
      { k:'C', en:`Create a version for every new deployed Lambda function. Use the AWS CLI update-function-configuration command with the routing-config parameter to distribute the load.`, ko:`새로 배포된 모든 Lambda 함수에 대한 버전을 생성합니다. AWS CLI update-function-configuration 명령을 Routing-config 파라미터와 함께 사용하여 로드를 분산하십시오.` },
      { k:'D', en:`Configure AWS CodeDeploy and use CodeDeployDefault.OneAtATime in the Deployment configuration to distribute the load.`, ko:`AWS CodeDeploy를 구성하고 배포 구성에서 CodeDeployDefault.OneAtATime을 사용하여 로드를 분산시킵니다.` },
    ],
    answer: ["A"],
    vote: '98% A',
    explain: `<p><span class="mark-ok">✅ A</span></p><p>A. 새로 배포된 모든 버전의 Lambda 함수에 대한 별칭을 생성합니다. AWS CLI update-alias 명령을 Routing-config 매개변수와 함께 사용하여 로드를 분산시키는 것이 정답입니다. 이는 카나리아 릴리스 지원 요구 사항을 충족하므로 정답입니다. 옵션 B는 Canary 릴리스를 허용하지만 새 버전의 애플리케이션을 별도의 CloudFormation 스택에 배포해야 하기 때문에 올바르지 않습니다. 이는 새 버전에 대한 별칭을 생성하는 것에 비해 더 복잡하고 시간이 많이 소요되는 프로세스입니다. Lambda 함수 버전. 옵션 C는 Canary 릴리스를 허용하지만 새로 배포된 모든 Lambda 함수에 대한 버전을 생성해야 하기 때문에 올바르지 않습니다. 이는 새 버전의 Lambda에 대...</p>`,
    wrong: `<p><span class="mark-no">❌ D</span> — AWS CodeDeploy는 Amazon EC2 인스턴스 및 온프레미스 인스턴스를 포함한 모든 인스턴스에 대한 코드 배포를 자동화하는 서비스입니다. CodeDeploy를 사용하면 소프트웨어의 새 버전을 전체 인프라에 릴리스하기 전에 소수의 사용자 또는 시스템 하위 집합에 릴리스하는 기술인 카나리아 릴리스를 수행할 수 있습니다. 이를 통해 소프트웨어의 새 버</p>`,
    disc: [{ ans:'A', txt:'A. 새로 배포된 모든 버전의 Lambda 함수에 대한 별칭을 생성합니다. AWS CLI update-alias 명령을 Routing-config 매개변수와 함께 사용하여 로드를 분산시키는 것이 정답입니다. 이는 카나리아 릴리스 지원 요구 사항을 충족하므로 정답입니다. 옵션 B는 Canary 릴리스를 허용하지만 새 버전의 애플리케이션을 별도의 CloudFormation 스택에 배포해야 하기 때문에 올바르지 않습니다. 이는 새 버전에 대한 별칭을 생성하는 것에 비해 더 복잡하고 시간이 많이 소요되는 프로세스입니다. Lambda 함수 버전. 옵션 C는 Canary 릴리스를 허용하지만 새로 배포된 모든 Lambda 함수에 대한 버전을 생성해야 하기 때문에 올바르지 않습니다. 이는 새 버전의 Lambda에 대...' }, { ans:'A', txt:'A. Create an alias for every new deployed version of the Lambda function. Use the AWS CLI update-alias command with the routing-config parameter to distribute the load is the correct answer as it meets the requirement of supporting a canary release. Option B is not correct because while it would allow for a canary release, it would involve deploying the new version of the application into a sep...' }, { ans:'A', txt:'https://www.examtopics.com/discussions/amazon/view/28312-exam-aws-certified-solutions-architect-professional-topic-1/' }, { ans:'A', txt:'B가 아닙니다. 이는 시나리오에 R53을 도입하지만 R53이 시나리오에 적합한지 확실하지 않습니다. R53과 Lambda를 결합하려면 언급되지 않은 함수 URL을 사용해야 하며 앱이 공개인지 알 수 없습니다. 여기에는 많은 불확실성이 있습니다. C가 아닙니다. Routing-config는 Weighted Alias라고도 불리는 별칭 관련 구성이며 update-function-configuration 명령(https://docs.aws.amazon.com/cli/latest/reference/)에는 사용할 수 없습니다. Lambda/update-function-configuration.html D가 아닙니다. CodeDeployDefault.OneAtATime은 EC2/온프레미스용 CodeDeploy 옵...' }, { ans:'A', txt:'Not B. This introduces R53 in the scenario, but we are not sure if R53 fits in the scenario. To combine R53 and Lambda we should use function URL that is not mentioned and we don\'t know if the app is public. A lot of uncertainty here Not C. routing-config is an Alias specific configuration aka Weighted Alias and it is not available for the update-function-configuration command https://docs.aws....' }]
  }
];
