window.QS_SET34 = [
  {
    n: 331,
    en: `A company is migrating an application to the AWS Cloud. The application runs in an on-premises data center and writes thousands of images into a mounted NFS file system each night. After the company migrates the application, the company will host the application on an Amazon EC2 instance with a mounted Amazon Elastic File System (Amazon EFS) file system.<br/><br/>The company has established an AWS Direct Connect connection to AWS. Before the migration cutover, a solutions architect must build a process that will replicate the newly created on-premises images to the EFS file system.<br/><br/>What is the MOST operationally efficient way to replicate the images?`,
    ko: `한 회사가 애플리케이션을 AWS 클라우드로 마이그레이션하고 있습니다. 애플리케이션은 온프레미스 데이터 센터에서 실행되며 매일 밤 마운트된 NFS 파일 시스템에 수천 개의 이미지를 씁니다. 회사는 애플리케이션을 마이그레이션한 후 Amazon Elastic File System(Amazon EFS) 파일 시스템이 탑재된 Amazon EC2 인스턴스에서 애플리케이션을 호스팅합니다. <br/><br/>회사는 AWS에 대한 AWS Direct Connect 연결을 설정했습니다. 마이그레이션 중단 전에 솔루션 설계자는 새로 생성된 온프레미스 이미지를 EFS 파일 시스템에 복제하는 프로세스를 구축해야 합니다. <br/><br/>이미지를 복제하는 가장 운영상 효율적인 방법은 무엇입니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Configure a periodic process to run the aws s3 sync command from the on-premises file system to Amazon S3. Configure an AWS Lambda function to process event notifications from Amazon S3 and copy the images from Amazon S3 to the EFS file system.`, ko:`온프레미스 파일 시스템에서 Amazon S3로 aws s3 sync 명령을 실행하도록 정기적인 프로세스를 구성합니다. Amazon S3의 이벤트 알림을 처리하고 Amazon S3의 이미지를 EFS 파일 시스템으로 복사하도록 AWS Lambda 함수를 구성합니다.` },
      { k:'B', en:`Deploy an AWS Storage Gateway file gateway with an NFS mount point. Mount the file gateway file system on the on-premises server. Configure a process to periodically copy the images to the mount point.`, ko:`NFS 마운트 지점을 사용하여 AWS Storage Gateway 파일 게이트웨이를 배포합니다. 온프레미스 서버에 파일 게이트웨이 파일 시스템을 탑재합니다. 이미지를 마운트 지점에 주기적으로 복사하는 프로세스를 구성합니다.` },
      { k:'C', en:`Deploy an AWS DataSync agent to an on-premises server that has access to the NFS file system. Send data over the Direct Connect connection to an S3 bucket by using a public VIF. Configure an AWS Lambda function to process event notifications from Amazon S3 and copy the images from Amazon S3 to the EFS file system.`, ko:`NFS 파일 시스템에 액세스할 수 있는 온프레미스 서버에 AWS DataSync 에이전트를 배포합니다. 퍼블릭 VIF를 사용하여 Direct Connect 연결을 통해 S3 버킷으로 데이터를 보냅니다. Amazon S3의 이벤트 알림을 처리하고 Amazon S3의 이미지를 EFS 파일 시스템으로 복사하도록 AWS Lambda 함수를 구성합니다.` },
      { k:'D', en:`Deploy an AWS DataSync agent to an on-premises server that has access to the NFS file system. Send data over the Direct Connect connection to an AWS PrivateLink interface VPC endpoint for Amazon EFS by using a private VIF. Configure a DataSync scheduled task to send the images to the EFS file system every 24 hours.`, ko:`NFS 파일 시스템에 액세스할 수 있는 온프레미스 서버에 AWS DataSync 에이전트를 배포합니다. 프라이빗 VIF를 사용하여 Direct Connect 연결을 통해 Amazon EFS용 AWS PrivateLink 인터페이스 VPC 엔드포인트로 데이터를 보냅니다. 24시간마다 EFS 파일 시스템에 이미지를 보내도록 DataSync 예약 작업을 구성합니다.` },
    ],
    answer: ["D"],
    vote: '100% D',
    explain: `<p><span class="mark-ok">✅ D</span></p><p>옵션 D</p>`,
    wrong: ``,
    disc: [{ ans:'D', txt:'D 확실히요' }, { ans:'D', txt:'D for sure' }, { ans:'D', txt:'https://docs.aws.amazon.com/datasync/latest/userguide/datasync-in-vpc.html' }, { ans:'D', txt:'D일 가능성이 높다' }, { ans:'D', txt:'D is most likely' }]
  },
  {
    n: 332,
    en: `A company recently migrated a web application from an on-premises data center to the AWS Cloud. The web application infrastructure consists of an Amazon CloudFront distribution that routes to an Application Load Balancer (ALB), with Amazon Elastic Container Service (Amazon ECS) to process requests. A recent security audit revealed that the web application is accessible by using both CloudFront and ALB endpoints. However, the company requires that the web application must be accessible only by using the CloudFront endpoint.<br/><br/>Which solution will meet this requirement with the LEAST amount of effort?`,
    ko: `한 회사는 최근 온프레미스 데이터 센터에서 AWS 클라우드로 웹 애플리케이션을 마이그레이션했습니다. 웹 애플리케이션 인프라는 요청을 처리하기 위해 Amazon Elastic Container Service(Amazon ECS)를 사용하여 ALB(Application Load Balancer)로 라우팅하는 Amazon CloudFront 배포로 구성됩니다. 최근 보안 감사에서는 CloudFront와 ALB 엔드포인트를 모두 사용하여 웹 애플리케이션에 액세스할 수 있는 것으로 나타났습니다. 그러나 회사에서는 CloudFront 엔드포인트를 통해서만 웹 애플리케이션에 액세스할 수 있도록 요구합니다. <br/><br/>최소한의 노력으로 이 요구 사항을 충족할 수 있는 솔루션은 무엇입니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Create a new security group and attach it to the CloudFront distribution. Update the ALB security group ingress to allow access only from the CloudFront security group.`, ko:`새 보안 그룹을 생성하여 CloudFront 배포에 연결합니다. CloudFront 보안 그룹에서만 액세스를 허용하도록 ALB 보안 그룹 수신을 업데이트합니다.` },
      { k:'B', en:`Update ALB security group ingress to allow access only from the com.amazonaws.global.cloudfront.origin-facing CloudFront managed prefix list.`, ko:`com.amazonaws.global.cloudfront.origin-facing CloudFront 관리형 접두사 목록에서만 액세스를 허용하도록 ALB 보안 그룹 수신을 업데이트합니다.` },
      { k:'C', en:`Create a com.amazonaws.region.elasticloadbalancing VPC interface endpoint for Elastic Load Balancing. Update the ALB scheme from internet-facing to internal.`, ko:`Elastic Load Balancing을 위한 com.amazonaws.region.elasticloadbalancing VPC 인터페이스 엔드포인트를 생성합니다. ALB 체계를 인터넷 연결에서 내부로 업데이트합니다.` },
      { k:'D', en:`Extract CloudFront IPs from the AWS provided ip-ranges.json document. Update ALB security group ingress to allow access only from CloudFront IPs.`, ko:`AWS가 제공한 ip-ranges.json 문서에서 CloudFront IP를 추출합니다. CloudFront IP에서만 액세스를 허용하도록 ALB 보안 그룹 수신을 업데이트합니다.` },
    ],
    answer: ["B"],
    vote: '100% B',
    explain: `<p><span class="mark-ok">✅ B</span></p><p>https://aws.amazon.com/blogs/networking-and-content-delivery/limit-access-to-your-origins-using-the-aws-managed-prefix-list-for-amazon-cloudfront/</p>`,
    wrong: ``,
    disc: [{ ans:'B', txt:'CloudFront 접두사 목록에서만 ALB SG에 대한 수신 액세스를 허용합니다. 답 - B' }, { ans:'B', txt:'확실히 - B입니다. 왜냐하면 Cloudfront에서는 securityGroup을 할당할 수 없기 때문입니다. 또한 보안 그룹에는 규칙이 60개만 있을 수 있으므로 모든 CloudFront IP를 보안 그룹에 추가할 수 없으므로 접두사 목록' }, { ans:'B', txt:'ㄴ 확실히요' }, { ans:'B', txt:'Allow ingress access to ALB SG only from CloudFront prefix list. Answer - B' }, { ans:'B', txt:'Definitely - B, becase you can\'t assign securityGroup on Cloudfront. Also, security group can have only 60 rules, so you can\'t add ALL CloudFront IPs into it, so prefix list' }]
  },
  {
    n: 333,
    en: `A company hosts a community forum site using an Application Load Balancer (ALB) and a Docker application hosted in an Amazon ECS cluster. The site data is stored in Amazon RDS for MySQL and the container image is stored in ECR. The company needs to provide their customers with a disaster recovery SLA with an RTO of no more than 24 hours and RPO of no more than 8 hours.<br/><br/>Which of the following solutions is the MOST cost-effective way to meet the requirements?`,
    ko: `회사는 ALB(Application Load Balancer)와 Amazon ECS 클러스터에서 호스팅되는 Docker 애플리케이션을 사용하여 커뮤니티 포럼 사이트를 호스팅합니다. 사이트 데이터는 MySQL용 Amazon RDS에 저장되고 컨테이너 이미지는 ECR에 저장됩니다. 회사는 RTO가 24시간 이하, RPO가 8시간 이하인 재해 복구 SLA를 고객에게 제공해야 합니다. <br/><br/>다음 솔루션 중 요구 사항을 충족하는 가장 비용 효율적인 방법은 무엇입니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Use AWS CloudFormation to deploy identical ALB, EC2, ECS and RDS resources in two regions. Schedule RDS snapshots every 8 hours. Use RDS multi-region replication to update the secondary region's copy of the database. In the event of a failure, restore from the latest snapshot, and use an Amazon Route 53 DNS failover policy to automatically redirect customers to the ALB in the secondary region.`, ko:`AWS CloudFormation을 사용하여 두 지역에 동일한 ALB, EC2, ECS 및 RDS 리소스를 배포하십시오. 8시간마다 RDS 스냅샷을 예약합니다. RDS 다중 지역 복제를 사용하여 보조 지역의 데이터베이스 복사본을 업데이트합니다. 오류가 발생하면 최신 스냅샷에서 복원하고 Amazon Route 53 DNS 장애 조치 정책을 사용하여 자동으로 고객을 보조 지역의 ALB로 리디렉션합니다.` },
      { k:'B', en:`Store the Docker image in ECR in two regions. Schedule RDS snapshots every 8 hours with snapshots copied to the secondary region. In the event of a failure, use AWS CloudFormation to deploy the ALB, EC2, ECS and RDS resources in the secondary region, restore from the latest snapshot, and update the DNS record to point to the ALB in the secondary region.`, ko:`두 지역의 ECR에 Docker 이미지를 저장합니다. 스냅샷을 보조 지역에 복사하여 8시간마다 RDS 스냅샷을 예약합니다. 오류가 발생하는 경우 AWS CloudFormation을 사용하여 보조 지역에 ALB, EC2, ECS 및 RDS 리소스를 배포하고, 최신 스냅샷에서 복원하고, 보조 지역의 ALB를 가리키도록 DNS 레코드를 업데이트합니다.` },
      { k:'C', en:`Use AWS CloudFormation to deploy identical ALB, EC2, ECS, and RDS resources in a secondary region. Schedule hourly RDS MySQL backups to Amazon S3 and use cross-region replication to replicate data to a bucket in the secondary region. In the event of a failure, import the latest Docker image to Amazon ECR in the secondary region, deploy to the EC2 instance, restore the latest MySQL backup, and update the DNS record to point to the ALB in the secondary region.`, ko:`AWS CloudFormation을 사용하여 보조 지역에 동일한 ALB, EC2, ECS 및 RDS 리소스를 배포합니다. Amazon S3에 대한 시간별 RDS MySQL 백업을 예약하고 지역 간 복제를 사용하여 보조 지역의 버킷에 데이터를 복제합니다. 오류가 발생하면 최신 Docker 이미지를 보조 지역의 Amazon ECR로 가져오고, EC2 인스턴스에 배포하고, 최신 MySQL 백업을 복원하고, 보조 지역의 ALB를 가리키도록 DNS 레코드를 업데이트하세요.` },
      { k:'D', en:`Deploy a pilot light environment in a secondary region with an ALB and a minimal resource EC2 deployment for Docker in an AWS Auto Scaling group with a scaling policy to increase instance size and number of nodes. Create a cross-region read replica of the RDS data. In the event of a failure, promote the replica to primary, and update the DNS record to point to the ALB in the secondary region.`, ko:`인스턴스 크기와 노드 수를 늘리기 위한 조정 정책을 사용하여 AWS Auto Scaling 그룹의 Docker용 ALB 및 최소 리소스 EC2 배포를 사용하여 보조 지역에 파일럿 라이트 환경을 배포합니다. RDS 데이터의 리전 간 읽기 복제본을 생성합니다. 오류가 발생하는 경우 복제본을 기본으로 승격하고 보조 지역의 ALB를 가리키도록 DNS 레코드를 업데이트합니다.` },
    ],
    answer: ["B"],
    vote: '89% B, 11% D',
    explain: `<p><span class="mark-ok">✅ B</span></p><p>RTO가 24시간인 경우 '콜드' DR 솔루션 옵션 B를 사용하는 것이 가장 저렴합니다. 옵션 D는 다른 지역의 두 번째 ECR 컨테이너보다 장기적으로 더 비용이 많이 들 것으로 생각되는 DR 솔루션의 부분입니다.</p>`,
    wrong: `<p><span class="mark-no">❌ D</span> — 답은 D이다</p>`,
    disc: [{ ans:'B', txt:'RTO가 24시간인 경우 \'콜드\' DR 솔루션 옵션 B를 사용하는 것이 가장 저렴합니다. 옵션 D는 다른 지역의 두 번째 ECR 컨테이너보다 장기적으로 더 비용이 많이 들 것으로 생각되는 DR 솔루션의 부분입니다.' }, { ans:'B', txt:'With an RTO of 24 hours, using the \'Cold\' DR solution option B is the cheapest. Option D is a partial on DR solution which I would think would be more expensive in the long run then the 2nd ECR container in another region.' }, { ans:'B', txt:'옵션 B가 가장 저렴합니다.' }, { ans:'B', txt:'Option B is lowest cost.' }, { ans:'B', txt:'RTO는 24시간이므로 사이트 2에 이미 모든 리소스를 프로비저닝할 필요는 없습니다. RPO를 충족하려면 8시간마다 RDS 스냅샷을 생성하세요. DR의 경우 CF를 사용하여 환경을 배포하고 RDS 스냅샷을 복원합니다. 답 - B' }]
  },
  {
    n: 334,
    en: `A company is migrating its infrastructure to the AWS Cloud. The company must comply with a variety of regulatory standards for different projects. The company needs a multi-account environment.<br/><br/>A solutions architect needs to prepare the baseline infrastructure. The solution must provide a consistent baseline of management and security, but it must allow flexibility for different compliance requirements within various AWS accounts. The solution also needs to integrate with the existing on-premises Active Directory Federation Services (AD FS) server.<br/><br/>Which solution meets these requirements with the LEAST amount of operational overhead?`,
    ko: `한 회사가 인프라를 AWS 클라우드로 마이그레이션하고 있습니다. 회사는 다양한 프로젝트에 대한 다양한 규제 표준을 준수해야 합니다. 회사에는 다중 계정 환경이 필요합니다. <br/><br/>솔루션 아키텍트는 기본 인프라를 준비해야 합니다. 솔루션은 일관된 관리 및 보안 기준을 제공해야 하지만 다양한 AWS 계정 내의 다양한 규정 준수 요구 사항에 대한 유연성을 허용해야 합니다. 또한 솔루션은 기존 온-프레미스 AD FS(Active Directory Federation Services) 서버와 통합되어야 합니다. <br/><br/>최소한의 운영 오버헤드로 이러한 요구 사항을 충족하는 솔루션은 무엇입니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Create an organization in AWS Organizations. Create a single SCP for least privilege access across all accounts. Create a single OU for all accounts. Configure an IAM identity provider for federation with the on-premises AD FS server. Configure a central logging account with a defined process for log generating services to send log events to the central account. Enable AWS Config in the central account with conformance packs for all accounts.`, ko:`AWS Organizations에서 조직을 생성합니다. 모든 계정에 대한 최소 권한 액세스를 위해 단일 SCP를 만듭니다. 모든 계정에 대해 단일 OU를 만듭니다. 온프레미스 AD FS 서버와의 연동을 위해 IAM ID 공급자를 구성합니다. 로그 이벤트를 중앙 계정으로 보내려면 로그 생성 서비스에 대해 정의된 프로세스로 중앙 로깅 계정을 구성합니다. 모든 계정에 대한 적합성 팩을 사용하여 중앙 계정에서 AWS Config를 활성화합니다.` },
      { k:'B', en:`Create an organization in AWS Organizations. Enable AWS Control Tower on the organization. Review included controls (guardrails) for SCPs. Check AWS Config for areas that require additions. Add OUs as necessary. Connect AWS IAM Identity Center (AWS Single Sign-On) to the on-premises AD FS server.`, ko:`AWS Organizations에서 조직을 생성합니다. 조직에서 AWS Control Tower를 활성화합니다. SCP에 포함된 제어(가드레일)를 검토합니다. 추가가 필요한 영역은 AWS Config를 확인하세요. 필요에 따라 OU를 추가합니다. AWS IAM Identity Center(AWS Single Sign-On)를 온프레미스 AD FS 서버에 연결합니다.` },
      { k:'C', en:`Create an organization in AWS Organizations. Create SCPs for least privilege access. Create an OU structure, and use it to group AWS accounts. Connect AWS IAM Identity Center (AWS Single Sign-On) to the on-premises AD FS server. Configure a central logging account with a defined process for log generating services to send log events to the central account. Enable AWS Config in the central account with aggregators and conformance packs.`, ko:`AWS Organizations에서 조직을 생성합니다. 최소 권한 액세스를 위해 SCP를 생성합니다. OU 구조를 생성하고 이를 사용하여 AWS 계정을 그룹화합니다. AWS IAM Identity Center(AWS Single Sign-On)를 온프레미스 AD FS 서버에 연결합니다. 로그 이벤트를 중앙 계정으로 보내려면 로그 생성 서비스에 대해 정의된 프로세스로 중앙 로깅 계정을 구성합니다. 집계자 및 적합성 팩을 사용하여 중앙 계정에서 AWS Config를 활성화합니다.` },
      { k:'D', en:`Create an organization in AWS Organizations. Enable AWS Control Tower on the organization. Review included controls (guardrails) for SCPs. Check AWS Config for areas that require additions. Configure an IAM identity provider for federation with the on-premises AD FS server.`, ko:`AWS Organizations에서 조직을 생성합니다. 조직에서 AWS Control Tower를 활성화합니다. SCP에 포함된 제어(가드레일)를 검토합니다. 추가가 필요한 영역은 AWS Config를 확인하세요. 온프레미스 AD FS 서버와의 연동을 위해 IAM ID 공급자를 구성합니다.` },
    ],
    answer: ["B"],
    vote: '100% B',
    explain: `<p><span class="mark-ok">✅ B</span></p><p>B. 이유: (1) "최소한의 운영 오버헤드" 요구 사항이 Control Tower에서 충족됩니다. Control Tower는 모범 사례 청사진을 사용하여 잘 설계된 다중 계정 환경 생성을 자동화하며 (2) IAM Identity Center는 인력 인증 및 권한 부여에 권장되는 접근 방식입니다.</p>`,
    wrong: ``,
    disc: [{ ans:'B', txt:'ㄴ 확실히요' }, { ans:'B', txt:'B for sure' }, { ans:'B', txt:'B. 이유: (1) "최소한의 운영 오버헤드" 요구 사항이 Control Tower에서 충족됩니다. Control Tower는 모범 사례 청사진을 사용하여 잘 설계된 다중 계정 환경 생성을 자동화하며 (2) IAM Identity Center는 인력 인증 및 권한 부여에 권장되는 접근 방식입니다.' }, { ans:'B', txt:'B는 OU를 언급하므로 D보다 낫습니다.' }, { ans:'B', txt:'D 위에 B, OU를 추가해야 함' }]
  },
  {
    n: 335,
    en: `An online magazine will launch its latest edition this month. This edition will be the first to be distributed globally. The magazine's dynamic website currently uses an Application Load Balancer in front of the web tier, a fleet of Amazon EC2 instances for web and application servers, and Amazon Aurora MySQL. Portions of the website include static content and almost all traffic is read-only.<br/><br/>The magazine is expecting a significant spike in internet traffic when the new edition is launched. Optimal performance is a top priority for the week following the launch.<br/><br/>Which combination of steps should a solutions architect take to reduce system response times for a global audience? (Choose two.)`,
    ko: `온라인 잡지가 이번 달 최신판을 출시할 예정입니다. 이 버전은 전 세계적으로 최초로 배포될 예정입니다. 이 잡지의 동적 웹 사이트는 현재 웹 계층 앞에 Application Load Balancer, 웹 및 애플리케이션 서버용 Amazon EC2 인스턴스 집합, Amazon Aurora MySQL을 사용하고 있습니다. 웹사이트의 일부에는 정적 콘텐츠가 포함되어 있으며 거의 ​​모든 트래픽은 읽기 전용입니다. <br/><br/>이 잡지는 새 판이 출시되면 인터넷 트래픽이 크게 급증할 것으로 예상하고 있습니다. 출시 다음 주에는 최적의 성능이 최우선 과제입니다. <br/><br/>전 세계 사용자의 시스템 응답 시간을 줄이기 위해 솔루션 아키텍트가 수행해야 하는 단계 조합은 무엇입니까? (2개를 선택하세요.)`,
    type: 'multi', multiCount: 2,
    choices: [
      { k:'A', en:`Use logical cross-Region replication to replicate the Aurora MySQL database to a secondary Region. Replace the web servers with Amazon S3. Deploy S3 buckets in cross-Region replication mode.`, ko:`논리적 교차 리전 복제를 사용하여 Aurora MySQL 데이터베이스를 보조 리전에 복제하십시오. 웹 서버를 Amazon S3로 교체합니다. 리전 간 복제 모드로 S3 버킷을 배포합니다.` },
      { k:'B', en:`Ensure the web and application tiers are each in Auto Scaling groups. Introduce an AWS Direct Connect connection. Deploy the web and application tiers in Regions across the world.`, ko:`웹 및 애플리케이션 계층이 각각 Auto Scaling 그룹에 있는지 확인합니다. AWS Direct Connect 연결을 도입합니다. 전 세계 지역에 웹 및 애플리케이션 계층을 배포합니다.` },
      { k:'C', en:`Migrate the database from Amazon Aurora to Amazon RDS for MySQL. Ensure all three of the application tiers – web, application, and database – are in private subnets.`, ko:`Amazon Aurora에서 MySQL용 Amazon RDS로 데이터베이스를 마이그레이션합니다. 세 가지 애플리케이션 계층(웹, 애플리케이션, 데이터베이스)이 모두 프라이빗 서브넷에 있는지 확인하세요.` },
      { k:'D', en:`Use an Aurora global database for physical cross-Region replication. Use Amazon S3 with cross-Region replication for static content and resources. Deploy the web and application tiers in Regions across the world.`, ko:`물리적 교차 리전 복제를 위해 Aurora 글로벌 데이터베이스를 사용하십시오. 정적 콘텐츠 및 리소스에 대해 리전 간 복제와 함께 Amazon S3를 사용하십시오. 전 세계 지역에 웹 및 애플리케이션 계층을 배포합니다.` },
      { k:'E', en:`Introduce Amazon Route 53 with latency-based routing and Amazon CloudFront distributions. Ensure the web and application tiers are each in Auto Scaling groups.`, ko:`지연 시간 기반 라우팅 및 Amazon CloudFront 배포 기능을 갖춘 Amazon Route 53을 소개합니다. 웹 및 애플리케이션 계층이 각각 Auto Scaling 그룹에 있는지 확인합니다.` },
    ],
    answer: [],
    vote: '100% DE',
    explain: ``,
    wrong: `<p><span class="mark-no">❌ D</span> — D와 E.</p><p><span class="mark-no">❌ E</span> — D와 E.</p>`,
    disc: [{ ans:'D, E', txt:'Aurora 글로벌 데이터베이스, Route 53을 사용한 S3 지역 간 복제, Cloud Front. 답 - D&E' }, { ans:'D, E', txt:'Aurora Global databases, S3 cross region replication with Route 53, Cloud Front. Answer - D&E' }, { ans:'D, E', txt:'옳은' }, { ans:'D, E', txt:'Correct' }, { ans:'D, E', txt:'물론 E, D도 추가해야 합니다' }]
  },
  {
    n: 336,
    en: `An online gaming company needs to optimize the cost of its workloads on AWS. The company uses a dedicated account to host the production environment for its online gaming application and an analytics application.<br/><br/>Amazon EC2 instances host the gaming application and must always be available. The EC2 instances run all year. The analytics application uses data that is stored in Amazon S3. The analytics application can be interrupted and resumed without issue.<br/><br/>Which solution will meet these requirements MOST cost-effectively?`,
    ko: `온라인 게임 회사는 AWS에서 워크로드 비용을 최적화해야 합니다. 회사는 전용 계정을 사용하여 온라인 게임 애플리케이션과 분석 애플리케이션을 위한 프로덕션 환경을 호스팅합니다. <br/><br/>Amazon EC2 인스턴스는 게임 애플리케이션을 호스팅하며 항상 사용 가능해야 합니다. EC2 인스턴스는 일년 내내 실행됩니다. 분석 애플리케이션은 Amazon S3에 저장된 데이터를 사용합니다. 분석 애플리케이션은 문제 없이 중단되었다가 재개될 수 있습니다. <br/><br/>이러한 요구 사항을 가장 비용 효율적으로 충족하는 솔루션은 무엇입니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Purchase an EC2 Instance Savings Plan for the online gaming application instances. Use On-Demand Instances for the analytics application.`, ko:`온라인 게임 애플리케이션 인스턴스에 대한 EC2 Instance Savings Plan을 구매하십시오. 분석 애플리케이션에 온디맨드 인스턴스를 사용합니다.` },
      { k:'B', en:`Purchase an EC2 Instance Savings Plan for the online gaming application instances. Use Spot Instances for the analytics application.`, ko:`온라인 게임 애플리케이션 인스턴스에 대한 EC2 인스턴스 Savings Plan을 구매합니다. 분석 애플리케이션에 스팟 인스턴스를 사용합니다.` },
      { k:'C', en:`Use Spot Instances for the online gaming application and the analytics application. Set up a catalog in AWS Service Catalog to provision services at a discount.`, ko:`온라인 게임 애플리케이션 및 분석 애플리케이션에 스팟 인스턴스를 사용합니다. 할인된 가격으로 서비스를 프로비저닝하려면 AWS Service Catalog에 카탈로그를 설정하세요.` },
      { k:'D', en:`Use On-Demand Instances for the online gaming application. Use Spot Instances for the analytics application. Set up a catalog in AWS Service Catalog to provision services at a discount.`, ko:`온라인 게임 애플리케이션에 온디맨드 인스턴스를 사용합니다. 분석 애플리케이션에 스팟 인스턴스를 사용합니다. 할인된 가격으로 서비스를 프로비저닝하려면 AWS Service Catalog에 카탈로그를 설정하세요.` },
    ],
    answer: ["B"],
    vote: '100% B',
    explain: `<p><span class="mark-ok">✅ B</span></p><p>ㄴ 끝까지</p>`,
    wrong: ``,
    disc: [{ ans:'B', txt:'B... 분석 앱에는 스팟 인스턴스를 사용하고 게임에는 인스턴스 절약을 사용합니다.' }, { ans:'B', txt:'B... use spot instances for Analytics appln and Instance savings for Gaming' }, { ans:'B', txt:'B가 맞습니다. 분석 애플리케이션에 사용되는 스팟 인스턴스는 언제든지 중단되고 재개될 수 있습니다.' }, { ans:'B', txt:'ㄴ 틀림없지' }, { ans:'B', txt:'B is correct, Spot instances uses for the analytical application can be interrupted and resumed at any time.' }]
  },
  {
    n: 337,
    en: `A company runs applications in hundreds of production AWS accounts. The company uses AWS Organizations with all features enabled and has a centralized backup operation that uses AWS Backup.<br/><br/>The company is concerned about ransomware attacks. To address this concern, the company has created a new policy that all backups must be resilient to breaches of privileged-user credentials in any production account.<br/><br/>Which combination of steps will meet this new requirement? (Choose three.)`,
    ko: `회사는 수백 개의 프로덕션 AWS 계정에서 애플리케이션을 실행합니다. 회사는 모든 기능이 활성화된 AWS Organizations를 사용하며 AWS Backup을 사용하는 중앙 집중식 백업 작업을 수행합니다. <br/><br/>회사는 랜섬웨어 공격을 우려하고 있습니다. 이러한 문제를 해결하기 위해 회사는 모든 백업이 모든 프로덕션 계정의 권한 있는 사용자 자격 증명 위반에 대해 복원력을 가져야 한다는 새로운 정책을 만들었습니다. <br/><br/>이 새로운 요구 사항을 충족하는 단계 조합은 무엇입니까? (3개를 선택하세요.)`,
    type: 'multi', multiCount: 3,
    choices: [
      { k:'A', en:`Implement cross-account backup with AWS Backup vaults in designated non-production accounts.`, ko:`지정된 비프로덕션 계정에서 AWS Backup 볼트를 사용하여 교차 계정 백업을 구현합니다.` },
      { k:'B', en:`Add an SCP that restricts the modification of AWS Backup vaults.`, ko:`AWS Backup 볼트 수정을 제한하는 SCP를 추가합니다.` },
      { k:'C', en:`Implement AWS Backup Vault Lock in compliance mode.<br/>C. Implement least privilege access for the IAM service role that is assigned to AWS Backup.`, ko:`규정 준수 모드에서 AWS Backup Vault Lock을 구현합니다. <br/>C. AWS Backup에 할당된 IAM 서비스 역할에 대한 최소 권한 액세스를 구현합니다.` },
      { k:'D', en:`Configure the backup frequency, lifecycle, and retention period to ensure that at least one backup always exists in the cold tier.`, ko:`콜드 계층에 항상 하나 이상의 백업이 존재하도록 백업 빈도, 수명 주기 및 보존 기간을 구성합니다.` },
      { k:'E', en:`Configure AWS Backup to write all backups to an Amazon S3 bucket in a designated non-production account. Ensure that the S3 bucket has S3 Object Lock enabled.`, ko:`지정된 비프로덕션 계정의 Amazon S3 버킷에 모든 백업을 기록하도록 AWS Backup을 구성합니다. S3 버킷에 S3 객체 잠금이 활성화되어 있는지 확인하세요.` },
    ],
    answer: [],
    vote: '57% ABC, 23% ACD, 20% ACE',
    explain: ``,
    wrong: `<p><span class="mark-no">❌ A</span> — 확실한 ACE A. 지정된 비프로덕션 계정에서 AWS Backup 볼트를 사용하여 계정 간 백업을 구현합니다. 이를 통해 회사는 운영 또는 보안상의 이유로 조직에 속한 다른 계정에 백업을 안전하게 복사할 수 있습니다1. C. 규정 준수 모드에서 AWS Backup Vault Lock을 구현합니다. 이는 백업 볼트에 추가 보호 계층과 불변성을 제공하여 보존 </p><p><span class="mark-no">❌ B</span> — 해결책은 A, B, C1입니다. 교차 계정 백업 생성 -> 백업 계정에 넣기 -> SCP를 사용하여 백업 계정 수정을 제어해야 합니다. A. 지정된 비프로덕션 계정에서 AWS Backup 볼트를 사용하여 교차 계정 백업을 구현합니다. https://docs.aws.amazon.com/aws-backup/latest/devguide/manage-cross-a</p><p><span class="mark-no">❌ C</span> — 확실한 ACE A. 지정된 비프로덕션 계정에서 AWS Backup 볼트를 사용하여 계정 간 백업을 구현합니다. 이를 통해 회사는 운영 또는 보안상의 이유로 조직에 속한 다른 계정에 백업을 안전하게 복사할 수 있습니다1. C. 규정 준수 모드에서 AWS Backup Vault Lock을 구현합니다. 이는 백업 볼트에 추가 보호 계층과 불변성을 제공하여 보존 </p><p><span class="mark-no">❌ D</span> — ACD는 확실해요</p><p><span class="mark-no">❌ E</span> — 확실한 ACE A. 지정된 비프로덕션 계정에서 AWS Backup 볼트를 사용하여 계정 간 백업을 구현합니다. 이를 통해 회사는 운영 또는 보안상의 이유로 조직에 속한 다른 계정에 백업을 안전하게 복사할 수 있습니다1. C. 규정 준수 모드에서 AWS Backup Vault Lock을 구현합니다. 이는 백업 볼트에 추가 보호 계층과 불변성을 제공하여 보존 </p>`,
    disc: [{ ans:'A, C, E', txt:'확실한 ACE A. 지정된 비프로덕션 계정에서 AWS Backup 볼트를 사용하여 계정 간 백업을 구현합니다. 이를 통해 회사는 운영 또는 보안상의 이유로 조직에 속한 다른 계정에 백업을 안전하게 복사할 수 있습니다1. C. 규정 준수 모드에서 AWS Backup Vault Lock을 구현합니다. 이는 백업 볼트에 추가 보호 계층과 불변성을 제공하여 보존 기간이 완료될 때까지 모든 사용자(루트 사용자 포함) 또는 AWS가 백업을 삭제하거나 수정하는 것을 방지합니다2. E. 콜드 계층에 항상 하나 이상의 백업이 존재하도록 백업 빈도, 수명 주기 및 보존 기간을 구성합니다. 이를 통해 회사는 최소 보존 기간을 적용하고 백업을 저렴한 스토리지 계층2으로 이동하여 실수로 또는 악의적으로 백업을 삭제하는 것을 ...' }, { ans:'A, C, E', txt:'ACE for sure A. Implement cross-account backup with AWS Backup vaults in designated non-production accounts. This will allow the company to securely copy their backups to other accounts that are part of their organization for operational or security reasons1. C. Implement AWS Backup Vault Lock in compliance mode. This will provide an additional layer of protection and immutability to the backup...' }, { ans:'A, B, C', txt:'해결책은 A, B, C1입니다. 교차 계정 백업 생성 -> 백업 계정에 넣기 -> SCP를 사용하여 백업 계정 수정을 제어해야 합니다. A. 지정된 비프로덕션 계정에서 AWS Backup 볼트를 사용하여 교차 계정 백업을 구현합니다. https://docs.aws.amazon.com/aws-backup/latest/devguide/manage-cross-account.html B. AWS Backup 볼트 수정을 제한하는 SCP를 추가합니다. https://aws.amazon.com/blogs/storage/managing-access-to-backups-using-service-control-policies-with-aws-backup/ C1. 규정 준수 모드에서 AWS Backup Vault Loc...' }, { ans:'A, B, C', txt:'The solution is A, B and C1. We need to create a Cross Account Backup -> Put it in a Backup Account -> Control modification to the backup account with SCP. A. Implement cross-account backup with AWS Backup vaults in designated non-production accounts. https://docs.aws.amazon.com/aws-backup/latest/devguide/manage-cross-account.html B. Add an SCP that restricts the modification of AWS Backup vaul...' }, { ans:'A, B, C', txt:'나에게는 A, B, C.' }]
  },
  {
    n: 338,
    en: `A company needs to aggregate Amazon CloudWatch logs from its AWS accounts into one central logging account. The collected logs must remain in the AWS Region of creation. The central logging account will then process the logs, normalize the logs into standard output format, and stream the output logs to a security tool for more processing.<br/><br/>A solutions architect must design a solution that can handle a large volume of logging data that needs to be ingested. Less logging will occur outside normal business hours than during normal business hours. The logging solution must scale with the anticipated load. The solutions architect has decided to use an AWS Control Tower design to handle the multi-account logging process.<br/><br/>Which combination of steps should the solutions architect take to meet the requirements? (Choose three.)`,
    ko: `회사는 AWS 계정의 Amazon CloudWatch 로그를 하나의 중앙 로깅 계정으로 집계해야 합니다. 수집된 로그는 생성된 AWS 리전에 남아 있어야 합니다. 그런 다음 중앙 로깅 계정은 로그를 처리하고, 로그를 표준 출력 형식으로 정규화하고, 추가 처리를 위해 출력 로그를 보안 도구로 스트리밍합니다. <br/><br/>솔루션 설계자는 수집해야 하는 대량의 로깅 데이터를 처리할 수 있는 솔루션을 설계해야 합니다. 정규 업무 시간 동안보다 정규 업무 시간 외에는 로깅이 덜 발생합니다. 로깅 솔루션은 예상 부하에 따라 확장되어야 합니다. 솔루션 아키텍트는 다중 계정 로깅 프로세스를 처리하기 위해 AWS Control Tower 설계를 사용하기로 결정했습니다. <br/><br/>솔루션 설계자는 요구 사항을 충족하기 위해 어떤 단계 조합을 수행해야 합니까? (3개를 선택하세요.)`,
    type: 'multi', multiCount: 3,
    choices: [
      { k:'A', en:`Create a destination Amazon Kinesis data stream in the central logging account.`, ko:`중앙 로깅 계정에 대상 Amazon Kinesis 데이터 스트림을 생성합니다.` },
      { k:'B', en:`Create a destination Amazon Simple Queue Service (Amazon SQS) queue in the central logging account.`, ko:`중앙 로깅 계정에 대상 Amazon Simple Queue Service(Amazon SQS) 대기열을 생성합니다.` },
      { k:'C', en:`Create an IAM role that grants Amazon CloudWatch Logs the permission to add data to the Amazon Kinesis data stream. Create a trust policy. Specify the trust policy in the IAM role. In each member account, create a subscription filter for each log group to send data to the Kinesis data stream.`, ko:`Amazon CloudWatch Logs에 Amazon Kinesis 데이터 스트림에 데이터를 추가할 수 있는 권한을 부여하는 IAM 역할을 생성합니다. 신뢰 정책을 만듭니다. IAM 역할에 신뢰 정책을 지정합니다. 각 회원 계정에서 각 로그 그룹에 대한 구독 필터를 생성하여 Kinesis 데이터 스트림으로 데이터를 보냅니다.` },
      { k:'D', en:`Create an IAM role that grants Amazon CloudWatch Logs the permission to add data to the Amazon Simple Queue Service (Amazon SQS) queue. Create a trust policy. Specify the trust policy in the IAM role. In each member account, create a single subscription filter for all log groups to send data to the SQS queue.`, ko:`Amazon CloudWatch Logs에 Amazon Simple Queue Service(Amazon SQS) 대기열에 데이터를 추가할 수 있는 권한을 부여하는 IAM 역할을 생성합니다. 신뢰 정책을 만듭니다. IAM 역할에 신뢰 정책을 지정합니다. 각 회원 계정에서 모든 로그 그룹에 대한 단일 구독 필터를 생성하여 SQS 대기열로 데이터를 보냅니다.` },
      { k:'E', en:`Create an AWS Lambda function. Program the Lambda function to normalize the logs in the central logging account and to write the logs to the security tool.`, ko:`AWS Lambda 함수를 생성합니다. 중앙 로깅 계정의 로그를 정규화하고 보안 도구에 로그를 쓰도록 Lambda 함수를 프로그래밍합니다.` },
      { k:'F', en:`Create an AWS Lambda function. Program the Lambda function to normalize the logs in the member accounts and to write the logs to the security tool.`, ko:`AWS Lambda 함수를 생성합니다. 회원 계정의 로그를 정규화하고 보안 도구에 로그를 쓰도록 Lambda 함수를 프로그래밍합니다.` },
    ],
    answer: [],
    vote: '100% ACE',
    explain: ``,
    wrong: `<p><span class="mark-no">❌ A</span> — A, C, E</p><p><span class="mark-no">❌ C</span> — A, C, E</p><p><span class="mark-no">❌ E</span> — A, C, E</p>`,
    disc: [{ ans:'A, C, E', txt:'Cloud Watch 로그 -> Kinesis Data Streams -> Lambda - > 보안 도구 ACE' }, { ans:'A, C, E', txt:'나는 ACE에 투표한다' }, { ans:'A, C, E', txt:'당연히 - 에이스' }, { ans:'A, C, E', txt:'에이스가 확실해요' }, { ans:'A, C, E', txt:'Cloud Watch logs -> Kinesis Data Streams -> Lambda - > Security Tool ACE' }]
  },
  {
    n: 339,
    en: `A company is migrating a legacy application from an on-premises data center to AWS. The application consists of a single application server and a Microsoft SQL Server database server. Each server is deployed on a VMware VM that consumes 500 TB of data across multiple attached volumes.<br/><br/>The company has established a 10 Gbps AWS Direct Connect connection from the closest AWS Region to its on-premises data center. The Direct Connect connection is not currently in use by other services.<br/><br/>Which combination of steps should a solutions architect take to migrate the application with the LEAST amount of downtime? (Choose two.)`,
    ko: `회사는 온프레미스 데이터 센터의 레거시 애플리케이션을 AWS로 마이그레이션하고 있습니다. 애플리케이션은 단일 애플리케이션 서버와 Microsoft SQL Server 데이터베이스 서버로 구성됩니다. 각 서버는 연결된 여러 볼륨에서 500TB의 데이터를 소비하는 VMware VM에 배포됩니다. <br/><br/>이 회사는 가장 가까운 AWS 지역에서 온프레미스 데이터 센터까지 10Gbps AWS Direct Connect 연결을 설정했습니다. Direct Connect 연결은 현재 다른 서비스에서 사용되지 않습니다. <br/><br/>가동 중지 시간을 최소화하면서 애플리케이션을 마이그레이션하려면 솔루션 설계자가 수행해야 하는 단계 조합은 무엇입니까? (2개를 선택하세요.)`,
    type: 'multi', multiCount: 2,
    choices: [
      { k:'A', en:`Use an AWS Server Migration Service (AWS SMS) replication job to migrate the database server VM to AWS.`, ko:`AWS SMS(AWS Server Migration Service) 복제 작업을 사용하여 데이터베이스 서버 VM을 AWS로 마이그레이션합니다.` },
      { k:'B', en:`Use VM Import/Export to import the application server VM.`, ko:`VM Import/Export를 사용하여 애플리케이션 서버 VM을 가져옵니다.` },
      { k:'C', en:`Export the VM images to an AWS Snowball Edge Storage Optimized device.`, ko:`VM 이미지를 AWS Snowball Edge Storage Optimized 디바이스로 내보냅니다.` },
      { k:'D', en:`Use an AWS Server Migration Service (AWS SMS) replication job to migrate the application server VM to AWS.`, ko:`AWS SMS(AWS Server Migration Service) 복제 작업을 사용하여 애플리케이션 서버 VM을 AWS로 마이그레이션합니다.` },
      { k:'E', en:`Use an AWS Database Migration Service (AWS DMS) replication instance to migrate the database to an Amazon RDS DB instance.`, ko:`AWS DMS(AWS Database Migration Service) 복제 인스턴스를 사용하여 데이터베이스를 Amazon RDS DB 인스턴스로 마이그레이션합니다.` },
    ],
    answer: [],
    vote: '59% DE, 31% AD, 8% BE',
    explain: ``,
    wrong: `<p><span class="mark-no">❌ A</span> — AD, RDS 데이터베이스의 최대 크기는 500TB 미만이며 RDS를 사용할 수 없습니다!</p><p><span class="mark-no">❌ B</span> — VM 내보내기/가져오기를 사용하여 애플리케이션 마이그레이션 DB는 VM에서 실행되는 MS SQL이므로 DMS를 사용하여 RDS로 마이그레이션합니다.</p><p><span class="mark-no">❌ C</span> — 옵션 에이스. 전송 게이트웨이를 생성하고 라우팅 테이블에서 통신 라우팅 규칙을 설정한 다음 마지막으로 VPN에 대한 전송 게이트웨이 연결을 생성해야 합니다. 옵션 E - https://docs.aws.amazon.com/vpc/latest/tgw/tgw-vpn-attachments.html 옵션 A&C - https://docs.aws.amazon.com/</p><p><span class="mark-no">❌ D</span> — AD, RDS 데이터베이스의 최대 크기는 500TB 미만이며 RDS를 사용할 수 없습니다!</p><p><span class="mark-no">❌ E</span> — DE "최소 가동 중지 시간"이어야 합니다.</p>`,
    disc: [{ ans:'A, D', txt:'AD, RDS 데이터베이스의 최대 크기는 500TB 미만이며 RDS를 사용할 수 없습니다!' }, { ans:'A, D', txt:'AD, RDS Database has max size of less than 500TB, cannot use RDS!' }, { ans:'D, E', txt:'DE "최소 가동 중지 시간"이어야 합니다.' }, { ans:'D, E', txt:'Should be DE "LEAST amount of downtime"' }, { ans:'D, E', txt:'나를 위한' }]
  },
  {
    n: 340,
    en: `A company operates a fleet of servers on premises and operates a fleet of Amazon EC2 instances in its organization in AWS Organizations. The company's AWS accounts contain hundreds of VPCs. The company wants to connect its AWS accounts to its on-premises network. AWS Site-to-Site VPN connections are already established to a single AWS account. The company wants to control which VPCs can communicate with other VPCs.<br/><br/>Which combination of steps will achieve this level of control with the LEAST operational effort? (Choose three.)`,
    ko: `회사는 온프레미스로 서버 집합을 운영하고 AWS 조직의 조직에서 Amazon EC2 인스턴스 집합을 운영합니다. 회사의 AWS 계정에는 수백 개의 VPC가 포함되어 있습니다. 회사는 AWS 계정을 온프레미스 네트워크에 연결하려고 합니다. AWS Site-to-Site VPN 연결은 이미 단일 AWS 계정에 설정되어 있습니다. 회사는 어떤 VPC가 다른 VPC와 통신할 수 있는지 제어하려고 합니다. <br/><br/>최소한의 운영 노력으로 이러한 수준의 제어를 달성할 수 있는 단계 조합은 무엇입니까? (3개를 선택하세요.)`,
    type: 'multi', multiCount: 3,
    choices: [
      { k:'A', en:`Create a transit gateway in an AWS account. Share the transit gateway across accounts by using AWS Resource Access Manager (AWS RAM).`, ko:`AWS 계정에서 전송 게이트웨이를 생성하십시오. AWS Resource Access Manager(AWS RAM)를 사용하여 계정 간에 전송 게이트웨이를 공유합니다.` },
      { k:'B', en:`Configure attachments to all VPCs and VPNs.`, ko:`모든 VPC 및 VPN에 대한 연결을 구성합니다.` },
      { k:'C', en:`Setup transit gateway route tables. Associate the VPCs and VPNs with the route tables.`, ko:`Transit Gateway 라우팅 테이블을 설정합니다. VPC 및 VPN을 라우팅 테이블과 연결합니다.` },
      { k:'D', en:`Configure VPC peering between the VPCs.`, ko:`VPC 간 VPC 피어링을 구성합니다.` },
      { k:'E', en:`Configure attachments between the VPCs and VPNs.`, ko:`VPC와 VPN 간의 연결을 구성합니다.` },
      { k:'F', en:`Setup route tables on the VPCs and VPNs.`, ko:`VPC 및 VPN에 라우팅 테이블을 설정합니다.` },
    ],
    answer: [],
    vote: '63% ABC, 37% ACE',
    explain: ``,
    wrong: `<p><span class="mark-no">❌ A</span> — 아무래도 ACE인 것 같아요. 회사는 어떤 VPC가 다른 VPC와 통신할지 제어하려고 합니다. 즉, 모든 VPC에 대한 연결을 설정할 필요가 없습니다.</p><p><span class="mark-no">❌ B</span> — Transit Gateway는 모든 VPC와 VPN을 연결하는 허브 및 스포크 모델을 따르므로 더 적합합니다. 또한 VPC와 VPN 간은 유효하지 않습니다.</p><p><span class="mark-no">❌ C</span> — 아무래도 ACE인 것 같아요. 회사는 어떤 VPC가 다른 VPC와 통신할지 제어하려고 합니다. 즉, 모든 VPC에 대한 연결을 설정할 필요가 없습니다.</p><p><span class="mark-no">❌ E</span> — 아무래도 ACE인 것 같아요. 회사는 어떤 VPC가 다른 VPC와 통신할지 제어하려고 합니다. 즉, 모든 VPC에 대한 연결을 설정할 필요가 없습니다.</p>`,
    disc: [{ ans:'A, C, E', txt:'아무래도 ACE인 것 같아요. 회사는 어떤 VPC가 다른 VPC와 통신할지 제어하려고 합니다. 즉, 모든 VPC에 대한 연결을 설정할 필요가 없습니다.' }, { ans:'A, B, C', txt:'Transit Gateway는 모든 VPC와 VPN을 연결하는 허브 및 스포크 모델을 따르므로 더 적합합니다. 또한 VPC와 VPN 간은 유효하지 않습니다.' }, { ans:'A, C, E', txt:'I guess ACE. The company wants to control which VPC will communicate with other VPC, that means that we don\'t need to setup attachment for all VPCs' }, { ans:'A, B, C', txt:'As transit gateway follows a hub and spoke model connecting all VPCs and VPNs to it makes more sense. Moreover, between VPCs and VPNs is invalid.' }, { ans:'A, B, C', txt:'나를 위한 ABC' }]
  }
];
