window.QS_SET36 = [
  {
    n: 351,
    en: `A company has a project that is launching Amazon EC2 instances that are larger than required. The project's account cannot be part of the company's organization in AWS Organizations due to policy restrictions to keep this activity outside of corporate IT. The company wants to allow only the launch of t3.small EC2 instances by developers in the project's account. These EC2 instances must be restricted to the us-east-2 Region.<br/><br/>What should a solutions architect do to meet these requirements?`,
    ko: `회사에 필요한 것보다 더 큰 Amazon EC2 인스턴스를 시작하는 프로젝트가 있습니다. 이 활동을 기업 IT 외부에 유지하라는 정책 제한으로 인해 프로젝트 계정은 AWS Organizations의 회사 조직에 속할 수 없습니다. 회사에서는 프로젝트 계정의 개발자가 t3.small EC2 인스턴스를 시작하는 것만 허용하려고 합니다. 이러한 EC2 인스턴스는 us-east-2 리전으로 제한되어야 합니다. <br/><br/>솔루션 설계자는 이러한 요구 사항을 충족하기 위해 무엇을 해야 합니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Create a new developer account. Move all EC2 instances, users, and assets into us-east-2. Add the account to the company's organization in AWS Organizations. Enforce a tagging policy that denotes Region affinity.`, ko:`새 개발자 계정을 만드세요. 모든 EC2 인스턴스, 사용자 및 자산을 us-east-2로 이동합니다. AWS Organizations에서 회사 조직에 계정을 추가합니다. 지역 선호도를 나타내는 태그 지정 정책을 시행합니다.` },
      { k:'B', en:`Create an SCP that denies the launch of all EC2 instances except t3.small EC2 instances in us-east-2. Attach the SCP to the project's account.`, ko:`us-east-2에서 t3.small EC2 인스턴스를 제외한 모든 EC2 인스턴스의 시작을 거부하는 SCP를 생성합니다. SCP를 프로젝트 계정에 연결합니다.` },
      { k:'C', en:`Create and purchase a t3.small EC2 Reserved Instance for each developer in us-east-2. Assign each developer a specific EC2 instance with their name as the tag.`, ko:`us-east-2의 각 개발자에 대해 t3.small EC2 예약 인스턴스를 생성하고 구매합니다. 각 개발자에게 이름을 태그로 사용하여 특정 EC2 인스턴스를 할당합니다.` },
      { k:'D', en:`Create an IAM policy than allows the launch of only t3.small EC2 instances in us-east-2. Attach the policy to the roles and groups that the developers use in the project's account.`, ko:`us-east-2에서 t3.small EC2 인스턴스만 시작하도록 허용하는 IAM 정책을 생성합니다. 개발자가 프로젝트 계정에서 사용하는 역할 및 그룹에 정책을 연결합니다.` },
    ],
    answer: ["D"],
    vote: '91% D, 9% B',
    explain: `<p><span class="mark-ok">✅ D</span></p><p>유일한 방법</p>`,
    wrong: `<p><span class="mark-no">❌ B</span> — https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps_examples_ec2.html#example-ec2-1</p>`,
    disc: [{ ans:'D', txt:'유일한 방법' }, { ans:'D', txt:'only possible way' }, { ans:'D', txt:'답: D' }, { ans:'D', txt:'Answer: D' }, { ans:'D', txt:'옵션 D가 유일한 답입니다. 시나리오에는 이 프로젝트의 IT 팀이 조직의 일부가 될 수 없다고 명시되어 있습니다.' }]
  },
  {
    n: 352,
    en: `A scientific company needs to process text and image data from an Amazon S3 bucket. The data is collected from several radar stations during a live, time-critical phase of a deep space mission. The radar stations upload the data to the source S3 bucket. The data is prefixed by radar station identification number.<br/><br/>The company created a destination S3 bucket in a second account. Data must be copied from the source S3 bucket to the destination S3 bucket to meet a compliance objective. This replication occurs through the use of an S3 replication rule to cover all objects in the source S3 bucket.<br/><br/>One specific radar station is identified as having the most accurate data. Data replication at this radar station must be monitored for completion within 30 minutes after the radar station uploads the objects to the source S3 bucket.<br/><br/>What should a solutions architect do to meet these requirements?`,
    ko: `과학 회사는 Amazon S3 버킷의 텍스트 및 이미지 데이터를 처리해야 합니다. 데이터는 심우주 임무의 시간이 중요한 실시간 단계 동안 여러 레이더 스테이션에서 수집됩니다. 레이더 스테이션은 데이터를 소스 S3 버킷에 업로드합니다. 데이터 앞에는 레이더 스테이션 식별 번호가 붙습니다. <br/><br/>회사는 두 번째 계정에 대상 S3 버킷을 생성했습니다. 규정 준수 목표를 달성하려면 소스 S3 버킷에서 대상 S3 버킷으로 데이터를 복사해야 합니다. 이 복제는 원본 S3 버킷의 모든 객체를 포괄하는 S3 복제 규칙을 사용하여 발생합니다. <br/><br/>하나의 특정 레이더 스테이션이 가장 정확한 데이터를 보유한 것으로 식별됩니다. 이 레이더 스테이션의 데이터 복제는 레이더 스테이션이 소스 S3 버킷에 객체를 업로드한 후 30분 이내에 완료되도록 모니터링해야 합니다. <br/><br/>솔루션 설계자는 이러한 요구 사항을 충족하기 위해 무엇을 해야 합니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Setup an AWS DataSync agent to replicate the prefixed data from the source S3 bucket to the destination S3 bucket. Select to use all available bandwidth on the task, and monitor the task to ensure that itis in the TRANSFERRING status. Create an Amazon EventBridge rule to initiate an alert if this status changes.`, ko:`소스 S3 버킷에서 대상 S3 버킷으로 접두사가 붙은 데이터를 복제하도록 AWS DataSync 에이전트를 설정합니다. 작업에서 사용 가능한 모든 대역폭을 사용하도록 선택하고 작업을 모니터링하여 TRANSFERRING 상태인지 확인합니다. 이 상태가 변경되면 알림을 시작하는 Amazon EventBridge 규칙을 생성합니다.` },
      { k:'B', en:`In the second account, create another S3 bucket to receive data from the radar station with the most accurate data. Set up a new replication rule for this new S3 bucket to separate the replication from the other radar stations. Monitor the maximum replication time to the destination. Create an Amazon EventBridge rule to initiate an alert when the time exceeds the desired threshold.`, ko:`두 번째 계정에서는 가장 정확한 데이터로 레이더 스테이션으로부터 데이터를 수신하기 위해 또 다른 S3 버킷을 생성합니다. 복제를 다른 레이더 스테이션과 분리하려면 이 새로운 S3 버킷에 대한 새 복제 규칙을 설정하십시오. 대상까지의 최대 복제 시간을 모니터링합니다. 시간이 원하는 임계값을 초과하면 알림을 시작하는 Amazon EventBridge 규칙을 생성합니다.` },
      { k:'C', en:`Enable Amazon S3 Transfer Acceleration on the source S3 bucket, and configure the radar station with the most accurate data to use the new endpoint. Monitor the S3 destination bucket's TotalRequestLatency metric. Create an Amazon EventBridge rule to initiate an alert if this status changes.`, ko:`소스 S3 버킷에서 Amazon S3 Transfer Acceleration을 활성화하고 새 엔드포인트를 사용하도록 가장 정확한 데이터로 레이더 스테이션을 구성합니다. S3 대상 버킷의 TotalRequestLatency 지표를 모니터링합니다. 이 상태가 변경되면 알림을 시작하는 Amazon EventBridge 규칙을 생성합니다.` },
      { k:'D', en:`Create a new S3 replication rule on the source S3 bucket that filters for the keys that use the prefix of the radar station with the most accurate data. Enable S3 Replication Time Control (S3 RTC). Monitor the maximum replication time to the destination. Create an Amazon EventBridge rule to initiate an alert when the time exceeds the desired threshold.`, ko:`가장 정확한 데이터로 레이더 스테이션의 접두사를 사용하는 키를 필터링하는 소스 S3 버킷에 새로운 S3 복제 규칙을 만듭니다. S3 복제 시간 제어(S3 RTC)를 활성화합니다. 대상까지의 최대 복제 시간을 모니터링합니다. 시간이 원하는 임계값을 초과하면 알림을 시작하는 Amazon EventBridge 규칙을 생성합니다.` },
    ],
    answer: ["D"],
    vote: '100% D',
    explain: `<p><span class="mark-ok">✅ D</span></p><p>D 확실히요</p>`,
    wrong: ``,
    disc: [{ ans:'D', txt:'D 확실히요' }, { ans:'D', txt:'D for sure' }, { ans:'D', txt:'옵션 D' }, { ans:'D', txt:'Option D' }, { ans:'D', txt:'C도 괜찮지만 추가 버킷을 구성하고 데이터를 보내도록 센서를 수정하는 추가 오버헤드가 있으므로 내 옵션은 D입니다.' }]
  },
  {
    n: 353,
    en: `A company wants to migrate its on-premises data center to the AWS Cloud. This includes thousands of virtualized Linux and Microsoft Windows servers, SAN storage, Java and PHP applications with MySQL, and Oracle databases. There are many dependent services hosted either in the same data center or externally. The technical documentation is incomplete and outdated. A solutions architect needs to understand the current environment and estimate the cloud resource costs after the migration.<br/><br/>Which tools or services should the solutions architect use to plan the cloud migration? (Choose three.)`,
    ko: `회사에서 온프레미스 데이터 센터를 AWS 클라우드로 마이그레이션하려고 합니다. 여기에는 수천 개의 가상화된 Linux 및 Microsoft Windows 서버, SAN 스토리지, MySQL이 포함된 Java 및 PHP 애플리케이션, Oracle 데이터베이스가 포함됩니다. 동일한 데이터 센터 또는 외부에서 호스팅되는 종속 서비스가 많이 있습니다. 기술 문서가 불완전하고 오래되었습니다. 솔루션 아키텍트는 현재 환경을 이해하고 마이그레이션 후 클라우드 리소스 비용을 추정해야 합니다. <br/><br/>솔루션 설계자는 클라우드 마이그레이션을 계획하기 위해 어떤 도구 또는 서비스를 사용해야 합니까? (3개를 선택하세요.)`,
    type: 'multi', multiCount: 3,
    choices: [
      { k:'A', en:`AWS Application Discovery Service`, ko:`AWS 애플리케이션 검색 서비스` },
      { k:'B', en:`AWS SMS`, ko:`AWS SMS` },
      { k:'C', en:`AWS X-Ray`, ko:`AWS 엑스레이` },
      { k:'D', en:`AWS Cloud Adoption Readiness Tool (CART)`, ko:`AWS 클라우드 채택 준비 도구(CART)` },
      { k:'E', en:`Amazon Inspector`, ko:`아마존 인스펙터` },
      { k:'F', en:`AWS Migration Hub`, ko:`AWS 마이그레이션 허브` },
    ],
    answer: [],
    vote: '76% ADF, 10% ABF, 10% ABD, 5% ACF',
    explain: ``,
    wrong: `<p><span class="mark-no">❌ A</span> — 답:ADF</p><p><span class="mark-no">❌ B</span> — D. CART는 마이그레이션을 위해 온프레미스와 AWS 클라우드 간의 인력, 조직, 프로세스의 격차를 평가하고 찾는 질문 도구 중 일부일 뿐입니다. 직접적으로 필요하거나 시스템을 목표로 하지 않습니다.</p><p><span class="mark-no">❌ C</span> — 솔루션 아키텍트는 현재 환경을 이해하고 마이그레이션 후 클라우드 리소스 비용을 추정해야 합니다. A. AWS Application Discovery Service(ok): 마이그레이션 계획을 지원하기 위해 소스 서버에 대한 정보를 수집합니다. B. AWS SMS(?) : AWS Application Migration Service 아닌가요? C. AWS X</p><p><span class="mark-no">❌ D</span> — 답:ADF</p><p><span class="mark-no">❌ F</span> — 답:ADF</p>`,
    disc: [{ ans:'A, D, F', txt:'답:ADF' }, { ans:'A, D, F', txt:'Answer: ADF' }, { ans:'A, D, F', txt:'옵션 ADF(B 아님) - 2022년 3월 31일부터 Amazon Web Services는 서버 마이그레이션 서비스(Amazon Web Services SMS)를 중단합니다. 앞으로는 Amazon Web Services Application Migration Service(Amazon Web Services MGN) AWS CART - https://aws.amazon.com/blogs/publicsector/get-migration-ready-aws-cloud-adoption-readiness-tool/을 권장합니다.' }, { ans:'A, D, F', txt:'Option ADF not B - As of March 31, 2022, Amazon Web Services will discontinue Server Migration Service (Amazon Web Services SMS). Going forward, we recommend Amazon Web Services Application Migration Service (Amazon Web Services MGN) AWS CART - https://aws.amazon.com/blogs/publicsector/get-migration-ready-aws-cloud-adoption-readiness-tool/' }, { ans:'A, D, F', txt:'에이,디,에프' }]
  },
  {
    n: 354,
    en: `A solutions architect is reviewing an application's resilience before launch. The application runs on an Amazon EC2 instance that is deployed in a private subnet of a VPC. The EC2 instance is provisioned by an Auto Scaling group that has a minimum capacity of 1 and a maximum capacity of 1. The application stores data on an Amazon RDS for MySQL DB instance. The VPC has subnets configured in three Availability Zones and is configured with a single NAT gateway.<br/><br/>The solutions architect needs to recommend a solution to ensure that the application will operate across multiple Availability Zones.<br/><br/>Which solution will meet this requirement?`,
    ko: `솔루션 설계자는 출시 전에 애플리케이션의 복원력을 검토하고 있습니다. 애플리케이션은 VPC의 프라이빗 서브넷에 배포된 Amazon EC2 인스턴스에서 실행됩니다. EC2 인스턴스는 최소 용량이 1이고 최대 용량이 1인 Auto Scaling 그룹에 의해 프로비저닝됩니다. 애플리케이션은 MySQL용 Amazon RDS DB 인스턴스에 데이터를 저장합니다. VPC에는 3개의 가용 영역에 구성된 서브넷이 있으며 단일 NAT 게이트웨이로 구성됩니다. <br/><br/>솔루션 설계자는 애플리케이션이 여러 가용 영역에서 작동하도록 보장하는 솔루션을 권장해야 합니다. <br/><br/>이 요구 사항을 충족하는 솔루션은 무엇입니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Deploy an additional NAT gateway in the other Availability Zones. Update the route tables with appropriate routes. Modify the RDS for MySQL DB instance to a Multi-AZ configuration. Configure the Auto Scaling group to launch the instances across Availability Zones. Set the minimum capacity and maximum capacity of the Auto Scaling group to 3.`, ko:`다른 가용 영역에 추가 NAT 게이트웨이를 배포합니다. 적절한 경로로 경로 테이블을 업데이트합니다. MySQL용 RDS DB 인스턴스를 다중 AZ 구성으로 수정합니다. 가용 영역 전체에서 인스턴스를 시작하도록 Auto Scaling 그룹을 구성합니다. Auto Scaling 그룹의 최소 용량과 최대 용량을 3으로 설정합니다.` },
      { k:'B', en:`Replace the NAT gateway with a virtual private gateway. Replace the RDS for MySQL DB instance with an Amazon Aurora MySQL DB cluster. Configure the Auto Scaling group to launch instances across all subnets in the VPC. Set the minimum capacity and maximum capacity of the Auto Scaling group to 3.`, ko:`NAT 게이트웨이를 가상 프라이빗 게이트웨이로 교체합니다. MySQL용 RDS DB 인스턴스를 Amazon Aurora MySQL DB 클러스터로 교체합니다. VPC의 모든 서브넷에서 인스턴스를 시작하도록 Auto Scaling 그룹을 구성합니다. Auto Scaling 그룹의 최소 용량과 최대 용량을 3으로 설정합니다.` },
      { k:'C', en:`Replace the NAT gateway with a NAT instance. Migrate the RDS for MySQL DB instance to an RDS for PostgreSQL DB instance. Launch a new EC2 instance in the other Availability Zones.`, ko:`NAT 게이트웨이를 NAT 인스턴스로 교체합니다. MySQL용 RDS DB 인스턴스를 PostgreSQL용 RDS DB 인스턴스로 마이그레이션합니다. 다른 가용 영역에서 새 EC2 인스턴스를 시작합니다.` },
      { k:'D', en:`Deploy an additional NAT gateway in the other Availability Zones. Update the route tables with appropriate routes. Modify the RDS for MySQL DB instance to turn on automatic backups and retain the backups for 7 days. Configure the Auto Scaling group to launch instances across all subnets in the VPC. Keep the minimum capacity and the maximum capacity of the Auto Scaling group at 1.`, ko:`다른 가용 영역에 추가 NAT 게이트웨이를 배포합니다. 적절한 경로로 경로 테이블을 업데이트합니다. 자동 백업을 활성화하고 백업을 7일 동안 유지하도록 MySQL DB 인스턴스용 RDS를 수정합니다. VPC의 모든 서브넷에서 인스턴스를 시작하도록 Auto Scaling 그룹을 구성합니다. Auto Scaling 그룹의 최소 용량과 최대 용량을 1로 유지합니다.` },
    ],
    answer: ["A"],
    vote: '100% A',
    explain: `<p><span class="mark-ok">✅ A</span></p><p>옵션 A</p>`,
    wrong: ``,
    disc: [{ ans:'A', txt:'A. 이 시나리오에서는 다른 모든 옵션이 의미가 없습니다.' }, { ans:'A', txt:'A...다른 답변은 말이 안 돼요' }, { ans:'A', txt:'A. all the other options make no sense in this scenario' }, { ans:'A', txt:'A...other answers don\'t make sense' }, { ans:'A', txt:'옵션 A' }]
  },
  {
    n: 355,
    en: `A company is planning to migrate its on-premises transaction-processing application to AWS. The application runs inside Docker containers that are hosted on VMs in the company's data center. The Docker containers have shared storage where the application records transaction data.<br/><br/>The transactions are time sensitive. The volume of transactions inside the application is unpredictable. The company must implement a low-latency storage solution that will automatically scale throughput to meet increased demand. The company cannot develop the application further and cannot continue to administer the Docker hosting environment.<br/><br/>How should the company migrate the application to AWS to meet these requirements?`,
    ko: `한 회사가 온프레미스 트랜잭션 처리 애플리케이션을 AWS로 마이그레이션할 계획입니다. 애플리케이션은 회사 데이터 센터의 VM에서 호스팅되는 Docker 컨테이너 내에서 실행됩니다. Docker 컨테이너에는 애플리케이션이 트랜잭션 데이터를 기록하는 공유 스토리지가 있습니다. <br/><br/>거래는 시간에 민감합니다. 애플리케이션 내부의 거래량은 예측할 수 없습니다. 회사는 증가하는 수요에 맞춰 처리량을 자동으로 확장하는 지연 시간이 짧은 스토리지 솔루션을 구현해야 합니다. 회사는 애플리케이션을 더 이상 개발할 수 없으며 Docker 호스팅 환경을 계속 관리할 수 없습니다. <br/><br/>이러한 요구 사항을 충족하려면 회사에서 애플리케이션을 AWS로 어떻게 마이그레이션해야 합니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Migrate the containers that run the application to Amazon Elastic Kubernetes Service (Amazon EKS). Use Amazon S3 to store the transaction data that the containers share.`, ko:`애플리케이션을 실행하는 컨테이너를 Amazon Elastic Kubernetes Service(Amazon EKS)로 마이그레이션합니다. Amazon S3를 사용하여 컨테이너가 공유하는 거래 데이터를 저장합니다.` },
      { k:'B', en:`Migrate the containers that run the application to AWS Fargate for Amazon Elastic Container Service (Amazon ECS). Create an Amazon Elastic File System (Amazon EFS) file system. Create a Fargate task definition. Add a volume to the task definition to point to the EFS file system.`, ko:`애플리케이션을 실행하는 컨테이너를 Amazon Elastic Container Service(Amazon ECS)용 AWS Fargate로 마이그레이션합니다. Amazon Elastic File System(Amazon EFS) 파일 시스템을 생성합니다. Fargate 작업 정의를 생성합니다. EFS 파일 시스템을 가리키도록 작업 정의에 볼륨을 추가합니다.` },
      { k:'C', en:`Migrate the containers that run the application to AWS Fargate for Amazon Elastic Container Service (Amazon ECS). Create an Amazon Elastic Block Store (Amazon EBS) volume. Create a Fargate task definition. Attach the EBS volume to each running task.`, ko:`애플리케이션을 실행하는 컨테이너를 Amazon Elastic Container Service(Amazon ECS)용 AWS Fargate로 마이그레이션합니다. Amazon Elastic Block Store(Amazon EBS) 볼륨을 생성합니다. Fargate 작업 정의를 생성합니다. 실행 중인 각 작업에 EBS 볼륨을 연결합니다.` },
      { k:'D', en:`Launch Amazon EC2 instances. Install Docker on the EC2 instances. Migrate the containers to the EC2 instances. Create an Amazon Elastic File System (Amazon EFS) file system. Add a mount point to the EC2 instances for the EFS file system.`, ko:`Amazon EC2 인스턴스를 시작합니다. EC2 인스턴스에 Docker를 설치합니다. 컨테이너를 EC2 인스턴스로 마이그레이션합니다. Amazon Elastic File System(Amazon EFS) 파일 시스템을 생성합니다. EFS 파일 시스템의 EC2 인스턴스에 탑재 지점을 추가합니다.` },
    ],
    answer: ["B"],
    vote: '100% B',
    explain: `<p><span class="mark-ok">✅ B</span></p><p>Fargate 작업 또는 컨테이너에 Amazon EFS 파일 시스템을 탑재하려면 먼저 작업 정의를 생성해야 합니다. 그런 다음 해당 작업 정의를 AWS 리전의 모든 가용 영역에 걸쳐 작업의 컨테이너에서 사용할 수 있도록 만듭니다. 그런 다음 Fargate 작업은 Amazon EFS를 사용하여 작업 정의에 지정한 작업에 파일 시스템을 자동으로 탑재합니다. https://repost.aws/knowledge-center/ecs-fargate-mount-efs-containers-tasks</p>`,
    wrong: ``,
    disc: [{ ans:'B', txt:'ㄴ 확실히요' }, { ans:'B', txt:'답: ㄴ' }, { ans:'B', txt:'B for sure' }, { ans:'B', txt:'Answer: B' }, { ans:'B', txt:'Fargate 작업 또는 컨테이너에 Amazon EFS 파일 시스템을 탑재하려면 먼저 작업 정의를 생성해야 합니다. 그런 다음 해당 작업 정의를 AWS 리전의 모든 가용 영역에 걸쳐 작업의 컨테이너에서 사용할 수 있도록 만듭니다. 그런 다음 Fargate 작업은 Amazon EFS를 사용하여 작업 정의에 지정한 작업에 파일 시스템을 자동으로 탑재합니다. https://repost.aws/knowledge-center/ecs-fargate-mount-efs-containers-tasks' }]
  },
  {
    n: 356,
    en: `A company is planning to migrate to the AWS Cloud. The company hosts many applications on Windows servers and Linux servers. Some of the servers are physical, and some of the servers are virtual. The company uses several types of databases in its on-premises environment. The company does not have an accurate inventory of its on-premises servers and applications.<br/><br/>The company wants to rightsize its resources during migration. A solutions architect needs to obtain information about the network connections and the application relationships. The solutions architect must assess the company’s current environment and develop a migration plan.<br/><br/>Which solution will provide the solutions architect with the required information to develop the migration plan?`,
    ko: `한 회사가 AWS 클라우드로 마이그레이션할 계획을 갖고 있습니다. 이 회사는 Windows 서버와 Linux 서버에서 많은 애플리케이션을 호스팅합니다. 일부 서버는 물리적 서버이고 일부 서버는 가상 서버입니다. 회사는 온프레미스 환경에서 여러 유형의 데이터베이스를 사용합니다. 회사는 온프레미스 서버 및 애플리케이션에 대한 정확한 인벤토리를 보유하고 있지 않습니다. <br/><br/>회사는 마이그레이션 중에 리소스 크기를 조정하려고 합니다. 솔루션 설계자는 네트워크 연결 및 애플리케이션 관계에 대한 정보를 얻어야 합니다. 솔루션 설계자는 회사의 현재 환경을 평가하고 마이그레이션 계획을 개발해야 합니다. <br/><br/>솔루션 설계자에게 마이그레이션 계획을 개발하는 데 필요한 정보를 제공하는 솔루션은 무엇입니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Use Migration Evaluator to request an evaluation of the environment from AWS. Use the AWS Application Discovery Service Agentless Collector to import the details into a Migration Evaluator Quick Insights report.`, ko:`Migration Evaluator를 사용하여 AWS에 환경 평가를 요청하십시오. AWS Application Discovery Service Agentless Collector를 사용하여 Migration Evaluator Quick Insights 보고서로 세부 정보를 가져옵니다.` },
      { k:'B', en:`Use AWS Migration Hub and install the AWS Application Discovery Agent on the servers. Deploy the Migration Hub Strategy Recommendations application data collector. Generate a report by using Migration Hub Strategy Recommendations.`, ko:`AWS Migration Hub를 사용하고 서버에 AWS Application Discovery Agent를 설치하십시오. Migration Hub 전략 권장 사항 애플리케이션 데이터 수집기를 배포합니다. Migration Hub 전략 권장 사항을 사용하여 보고서를 생성합니다.` },
      { k:'C', en:`Use AWS Migration Hub and run the AWS Application Discovery Service Agentless Collector on the servers. Group the servers and databases by using AWS Application Migration Service. Generate a report by using Migration Hub Strategy Recommendations.`, ko:`AWS Migration Hub를 사용하고 서버에서 AWS Application Discovery Service Agentless Collector를 실행합니다. AWS Application Migration Service를 사용하여 서버와 데이터베이스를 그룹화합니다. Migration Hub 전략 권장 사항을 사용하여 보고서를 생성합니다.` },
      { k:'D', en:`Use the AWS Migration Hub import tool to load the details of the company’s on-premises environment. Generate a report by using Migration Hub Strategy Recommendations.`, ko:`AWS Migration Hub 가져오기 도구를 사용하여 회사의 온프레미스 환경에 대한 세부 정보를 로드합니다. Migration Hub 전략 권장 사항을 사용하여 보고서를 생성합니다.` },
    ],
    answer: ["B"],
    vote: '100% B',
    explain: `<p><span class="mark-ok">✅ B</span></p><p>항상 기억해. 1. 네트워크, 시스템 성능, 실행 중인 프로세스 등과 관련된 마이그레이션용 데이터를 찾고 싶은 경우 2. 찾아야 할 현재 온프레미스 로드에는 물리적 서버가 포함되어 있습니다. 항상 응용 프로그램 검색 에이전트를 사용하십시오. 따라서 A와 C는 제외되었습니다(온-프레미스 VM에만 사용되는 에이전트 없는 검색을 사용하기 때문에). B와 D 사이: D가 잘못되었습니다. 질문 자체에서는 현재 로드를 인식하지 못하므로 데이터 가져오기가 불가능하다고 언급합니다. 정답은 B입니다</p>`,
    wrong: ``,
    disc: [{ ans:'B', txt:'Discovery Agent는 시스템 구성, 시스템 성능, 실행 중인 프로세스, 시스템 간 네트워크 연결 세부 정보를 캡처합니다. Agentless Collector는 VMware vCenter에 OVA로만 설치되므로 모든 서버에 적용되지는 않습니다. https://aws.amazon.com/application-discovery/faqs/' }, { ans:'B', txt:'ㄴ 확실히요' }, { ans:'B', txt:'The Discovery Agent captures system configuration, system performance, running processes, and details of the network connections between systems. The Agentless Collector is only installed as an OVA on the VMware vCenter so it doesn\'t apply to all servers. https://aws.amazon.com/application-discovery/faqs/' }, { ans:'B', txt:'B for sure' }, { ans:'B', txt:'항상 기억해. 1. 네트워크, 시스템 성능, 실행 중인 프로세스 등과 관련된 마이그레이션용 데이터를 찾고 싶은 경우 2. 찾아야 할 현재 온프레미스 로드에는 물리적 서버가 포함되어 있습니다. 항상 응용 프로그램 검색 에이전트를 사용하십시오. 따라서 A와 C는 제외되었습니다(온-프레미스 VM에만 사용되는 에이전트 없는 검색을 사용하기 때문에). B와 D 사이: D가 잘못되었습니다. 질문 자체에서는 현재 로드를 인식하지 못하므로 데이터 가져오기가 불가능하다고 언급합니다. 정답은 B입니다' }]
  },
  {
    n: 357,
    en: `A financial services company sells its software-as-a-service (SaaS) platform for application compliance to large global banks. The SaaS platform runs on AWS and uses multiple AWS accounts that are managed in an organization in AWS Organizations. The SaaS platform uses many AWS resources globally.<br/><br/>For regulatory compliance, all API calls to AWS resources must be audited, tracked for changes, and stored in a durable and secure data store.<br/><br/>Which solution will meet these requirements with the LEAST operational overhead?`,
    ko: `금융 서비스 회사는 대규모 글로벌 은행에 애플리케이션 규정 준수를 위한 SaaS(Software-as-a-Service) 플랫폼을 판매합니다. SaaS 플랫폼은 AWS에서 실행되며 AWS Organizations의 조직에서 관리되는 여러 AWS 계정을 사용합니다. SaaS 플랫폼은 전 세계적으로 많은 AWS 리소스를 사용합니다. <br/><br/>규정 준수를 위해 AWS 리소스에 대한 모든 API 호출을 감사하고, 변경 사항을 추적하고, 내구성 있고 안전한 데이터 저장소에 저장해야 합니다. <br/><br/>최소한의 운영 오버헤드로 이러한 요구 사항을 충족하는 솔루션은 무엇입니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Create a new AWS CloudTrail trail. Use an existing Amazon S3 bucket in the organization's management account to store the logs. Deploy the trail to all AWS Regions. Enable MFA delete and encryption on the S3 bucket.`, ko:`새로운 AWS CloudTrail 추적을 생성합니다. 조직의 마스터 계정에 있는 기존 Amazon S3 버킷을 사용하여 로그를 저장합니다. 모든 AWS 리전에 추적을 배포합니다. S3 버킷에서 MFA 삭제 및 암호화를 활성화합니다.` },
      { k:'B', en:`Create a new AWS CloudTrail trail in each member account of the organization. Create new Amazon S3 buckets to store the logs. Deploy the trail to all AWS Regions. Enable MFA delete and encryption on the S3 buckets.`, ko:`조직의 각 구성원 계정에 새로운 AWS CloudTrail 추적을 생성합니다. 로그를 저장할 새 Amazon S3 버킷을 생성합니다. 모든 AWS 리전에 추적을 배포합니다. S3 버킷에서 MFA 삭제 및 암호화를 활성화합니다.` },
      { k:'C', en:`Create a new AWS CloudTrail trail in the organization's management account. Create a new Amazon S3 bucket with versioning turned on to store the logs. Deploy the trail for all accounts in the organization. Enable MFA delete and encryption on the S3 bucket.`, ko:`조직의 마스터 계정에 새로운 AWS CloudTrail 추적을 생성합니다. 로그를 저장하기 위해 버전 관리가 활성화된 새 Amazon S3 버킷을 생성합니다. 조직의 모든 계정에 대한 추적을 배포합니다. S3 버킷에서 MFA 삭제 및 암호화를 활성화합니다.` },
      { k:'D', en:`Create a new AWS CloudTrail trail in the organization's management account. Create a new Amazon S3 bucket to store the logs. Configure Amazon Simple Notification Service (Amazon SNS) to send log-file delivery notifications to an external management system that will track the logs. Enable MFA delete and encryption on the S3 bucket.`, ko:`조직의 마스터 계정에 새로운 AWS CloudTrail 추적을 생성합니다. 로그를 저장할 새 Amazon S3 버킷을 생성합니다. 로그를 추적할 외부 관리 시스템에 로그 파일 전송 알림을 보내도록 Amazon Simple 알림 서비스(Amazon SNS)를 구성합니다. S3 버킷에서 MFA 삭제 및 암호화를 활성화합니다.` },
    ],
    answer: ["C"],
    vote: '92% C, 8% A',
    explain: `<p><span class="mark-ok">✅ C</span></p><p>C가 맞습니다. "모든 계정에 대한 추적 배포"라는 문구에 속아 추적이 각 계정에 생성된다고 생각하지 마십시오. 이는 새로운 조직 수준 추적이 모든 계정에 대한 데이터를 캡처하도록 _구성_되었음을 의미합니다.</p>`,
    wrong: `<p><span class="mark-no">❌ A</span> — 확실히</p>`,
    disc: [{ ans:'C', txt:'C가 맞습니다. "모든 계정에 대한 추적 배포"라는 문구에 속아 추적이 각 계정에 생성된다고 생각하지 마십시오. 이는 새로운 조직 수준 추적이 모든 계정에 대한 데이터를 캡처하도록 _구성_되었음을 의미합니다.' }, { ans:'C', txt:'C is correct. Do not get fooled by the phrase "deploy the trail for all accounts" to think that a trail is created in each account – it means that the new organisational-level trail is _configured_ to capture data for all accounts.' }, { ans:'C', txt:'C가 맞아요' }, { ans:'C', txt:'내 생각엔 C가 정답인 것 같아' }, { ans:'C', txt:'C is correct' }]
  },
  {
    n: 358,
    en: `A company is deploying a distributed in-memory database on a fleet of Amazon EC2 instances. The fleet consists of a primary node and eight worker nodes. The primary node is responsible for monitoring cluster health, accepting user requests, distributing user requests to worker nodes, and sending an aggregate response back to a client. Worker nodes communicate with each other to replicate data partitions.<br/><br/>The company requires the lowest possible networking latency to achieve maximum performance.<br/><br/>Which solution will meet these requirements?`,
    ko: `한 회사가 Amazon EC2 인스턴스 집합에 분산된 인 메모리 데이터베이스를 배포하고 있습니다. 플릿은 기본 노드 1개와 작업자 노드 8개로 구성됩니다. 기본 노드는 클러스터 상태를 모니터링하고, 사용자 요청을 수락하고, 사용자 요청을 작업자 노드에 배포하고, 집계 응답을 클라이언트에 다시 보내는 일을 담당합니다. 작업자 노드는 서로 통신하여 데이터 파티션을 복제합니다. <br/><br/>회사는 최대 성능을 달성하기 위해 가능한 가장 낮은 네트워킹 대기 시간을 요구합니다. <br/><br/>어떤 솔루션이 이러한 요구 사항을 충족합니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Launch memory optimized EC2 instances in a partition placement group.`, ko:`파티션 배치 그룹에서 메모리 최적화 EC2 인스턴스를 시작합니다.` },
      { k:'B', en:`Launch compute optimized EC2 instances in a partition placement group.`, ko:`파티션 배치 그룹에서 컴퓨팅 최적화 EC2 인스턴스를 시작합니다.` },
      { k:'C', en:`Launch memory optimized EC2 instances in a cluster placement group.`, ko:`클러스터 배치 그룹에서 메모리 최적화 EC2 인스턴스를 시작합니다.` },
      { k:'D', en:`Launch compute optimized EC2 instances in a spread placement group.`, ko:`분산 배치 그룹에서 컴퓨팅 최적화 EC2 인스턴스를 시작합니다.` },
    ],
    answer: ["C"],
    vote: '100% C',
    explain: `<p><span class="mark-ok">✅ C</span></p><p>옵션 C</p>`,
    wrong: ``,
    disc: [{ ans:'C', txt:'옵션 C' }, { ans:'C', txt:'Option C' }, { ans:'C', txt:'답변 C. 작업자 노드 간의 짧은 대기 시간 복제를 위해 클러스터 배치 그룹에서 메모리가 최적화되었습니다.' }, { ans:'C', txt:'C는 괜찮아요' }, { ans:'C', txt:'Answer C. Memory optimized in Cluster placement group for low latency replication between worker nodes.' }]
  },
  {
    n: 359,
    en: `A company maintains information on premises in approximately 1 million.csv files that are hosted on a VM. The data initially is 10 TB in size and grows at a rate of 1 TB each week. The company needs to automate backups of the data to the AWS Cloud.<br/><br/>Backups of the data must occur daily. The company needs a solution that applies custom filters to back up only a subset of the data that is located in designated source directories. The company has set up an AWS Direct Connect connection.<br/><br/>Which solution will meet the backup requirements with the LEAST operational overhead?`,
    ko: `회사는 VM에서 호스팅되는 약 100만 개의.csv 파일로 온프레미스에 정보를 유지 관리합니다. 데이터 크기는 처음에 10TB이며 매주 1TB씩 증가합니다. 회사는 AWS 클라우드에 대한 데이터 백업을 자동화해야 합니다. <br/><br/>데이터 백업은 매일 이루어져야 합니다. 회사에는 지정된 소스 디렉터리에 있는 데이터의 하위 집합만 백업하기 위해 사용자 지정 필터를 적용하는 솔루션이 필요합니다. 회사는 AWS Direct Connect 연결을 설정했습니다. <br/><br/>최소한의 운영 오버헤드로 백업 요구 사항을 충족하는 솔루션은 무엇입니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Use the Amazon S3 CopyObject API operation with multipart upload to copy the existing data to Amazon S3. Use the CopyObject API operation to replicate new data to Amazon S3 daily.`, ko:`멀티파트 업로드와 함께 Amazon S3 CopyObject API 작업을 사용하여 기존 데이터를 Amazon S3에 복사합니다. CopyObject API 작업을 사용하여 매일 Amazon S3에 새 데이터를 복제합니다.` },
      { k:'B', en:`Create a backup plan in AWS Backup to back up the data to Amazon S3. Schedule the backup plan to run daily.`, ko:`AWS Backup에서 백업 계획을 생성하여 Amazon S3에 데이터를 백업합니다. 매일 실행되도록 백업 계획을 예약합니다.` },
      { k:'C', en:`Install the AWS DataSync agent as a VM that runs on the on-premises hypervisor. Configure a DataSync task to replicate the data to Amazon S3 daily.`, ko:`AWS DataSync 에이전트를 온프레미스 하이퍼바이저에서 실행되는 VM으로 설치합니다. 매일 Amazon S3에 데이터를 복제하도록 DataSync 작업을 구성합니다.` },
      { k:'D', en:`Use an AWS Snowball Edge device for the initial backup. Use AWS DataSync for incremental backups to Amazon S3 daily.`, ko:`초기 백업에는 AWS Snowball Edge 디바이스를 사용합니다. 매일 Amazon S3에 대한 증분 백업을 위해 AWS DataSync를 사용하십시오.` },
    ],
    answer: ["C"],
    vote: '86% C, 14% B',
    explain: `<p><span class="mark-ok">✅ C</span></p><p>이유: 회사에는 지정된 소스 디렉터리에 있는 데이터의 하위 집합만 백업하기 위해 사용자 지정 필터를 적용하는 솔루션이 필요합니다.</p>`,
    wrong: `<p><span class="mark-no">❌ B</span> — ㄴ 맞다. Datasync는 백업용이 아니기 때문에</p>`,
    disc: [{ ans:'C', txt:'이유: 회사에는 지정된 소스 디렉터리에 있는 데이터의 하위 집합만 백업하기 위해 사용자 지정 필터를 적용하는 솔루션이 필요합니다.' }, { ans:'C', txt:'Because of: The company needs a solution that applies custom filters to back up only a subset of the data that is located in designated source directories.' }, { ans:'C', txt:'옵션 C: https://docs.aws.amazon.com/datasync/latest/userguide/create-s3-location.html 방법' }, { ans:'C', txt:'Option C: How To https://docs.aws.amazon.com/datasync/latest/userguide/create-s3-location.html' }, { ans:'C', txt:'저에게는 두 가지 단서가 있습니다. 1 - Datasync에서 사용할 수 있는 "사용자 지정 필터" 2 - AWS Backup은 Storage Vault가 아닌 S3에 백업하지 않습니다.' }]
  },
  {
    n: 360,
    en: `A financial services company has an asset management product that thousands of customers use around the world. The customers provide feedback about the product through surveys. The company is building a new analytical solution that runs on Amazon EMR to analyze the data from these surveys. The following user personas need to access the analytical solution to perform different actions:<br/><br/>•	Administrator: Provisions the EMR cluster for the analytics team based on the team’s requirements<br/>•	Data engineer: Runs ETL scripts to process, transform, and enrich the datasets<br/>•	Data analyst: Runs SQL and Hive queries on the data<br/><br/>A solutions architect must ensure that all the user personas have least privilege access to only the resources that they need. The user personas must be able to launch only applications that are approved and authorized. The solution also must ensure tagging for all resources that the user personas create.<br/><br/>Which solution will meet these requirements?`,
    ko: `한 금융 서비스 회사에는 전 세계 수천 명의 고객이 사용하는 자산 관리 제품이 있습니다. 고객은 설문조사를 통해 제품에 대한 피드백을 제공합니다. 회사는 이러한 설문조사의 데이터를 분석하기 위해 Amazon EMR에서 실행되는 새로운 분석 솔루션을 구축하고 있습니다. 다음 사용자 페르소나는 다양한 작업을 수행하기 위해 분석 솔루션에 액세스해야 합니다. <br/><br/>• 관리자: 팀의 요구 사항에 따라 분석 팀을 위한 EMR 클러스터를 프로비저닝합니다. <br/>• 데이터 엔지니어: ETL 스크립트를 실행하여 데이터 세트를 처리, 변환 및 강화합니다. <br/>• 데이터 분석가 : 데이터에 대해 SQL 및 Hive 쿼리를 실행합니다. <br/><br/>솔루션 설계자는 모든 사용자 페르소나가 필요한 리소스에만 최소한의 액세스 권한을 갖도록 해야 합니다. 사용자 페르소나는 승인되고 권한이 부여된 애플리케이션만 시작할 수 있어야 합니다. 또한 솔루션은 사용자 페르소나가 생성하는 모든 리소스에 대한 태그 지정을 보장해야 합니다. <br/><br/>어떤 솔루션이 이러한 요구 사항을 충족합니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Create IAM roles for each user persona. Attach identity-based policies to define which actions the user who assumes the role can perform. Create an AWS Config rule to check for noncompliant resources. Configure the rule to notify the administrator to remediate the noncompliant resources.`, ko:`각 사용자 페르소나에 대한 IAM 역할을 생성합니다. 자격 증명 기반 정책을 연결하여 역할을 맡은 사용자가 수행할 수 있는 작업을 정의합니다. 비준수 리소스를 확인하는 AWS Config 규칙을 생성합니다. 비준수 리소스를 수정하도록 관리자에게 알리도록 규칙을 구성합니다.` },
      { k:'B', en:`Setup Kerberos-based authentication for EMR clusters upon launch. Specify a Kerberos security configuration along with cluster-specific Kerberos options.`, ko:`시작 시 EMR 클러스터에 대한 Kerberos 기반 인증을 설정합니다. 클러스터별 Kerberos 옵션과 함께 Kerberos 보안 구성을 지정합니다.` },
      { k:'C', en:`Use AWS Service Catalog to control the Amazon EMR versions available for deployment, the cluster configuration, and the permissions for each user persona.`, ko:`AWS Service Catalog를 사용하여 배포에 사용할 수 있는 Amazon EMR 버전, 클러스터 구성 및 각 사용자 페르소나에 대한 권한을 제어합니다.` },
      { k:'D', en:`Launch the EMR cluster by using AWS CloudFormation, Attach resource-based policies to the EMR cluster during cluster creation. Create an AWS. Config rule to check for noncompliant clusters and noncompliant Amazon S3 buckets. Configure the rule to notify the administrator to remediate the noncompliant resources.`, ko:`AWS CloudFormation을 사용하여 EMR 클러스터를 시작하고 클러스터 생성 중에 EMR 클러스터에 리소스 기반 정책을 연결합니다. AWS를 생성합니다. 비준수 클러스터 및 비준수 Amazon S3 버킷을 확인하는 구성 규칙입니다. 비준수 리소스를 수정하도록 관리자에게 알리도록 규칙을 구성합니다.` },
    ],
    answer: ["C"],
    vote: '79% C, 21% A',
    explain: `<p><span class="mark-ok">✅ C</span></p><p>옵션 C. 옵션 A는 리소스 및 구성 배포에 대한 제어를 제공하지 않습니다.</p>`,
    wrong: `<p><span class="mark-no">❌ A</span> — A - IAM 역할은 서비스 카탈로그가 리소스(EMR)에 관한 작업을 정의합니다.</p>`,
    disc: [{ ans:'A', txt:'A - IAM 역할은 서비스 카탈로그가 리소스(EMR)에 관한 작업을 정의합니다.' }, { ans:'C', txt:'GPT에서: AWS Service Catalog를 사용하면 특정 권한이 있는 포트폴리오와 제품을 정의하여 리소스에 대한 액세스를 제어하고 관리할 수 있습니다. 승인되고 승인된 애플리케이션으로 포트폴리오를 생성하여 지정된 애플리케이션만 실행되도록 할 수 있습니다. AWS Service Catalog는 프로비저닝된 리소스에 태그 지정을 적용하여 사용자 페르소나가 생성한 모든 리소스에 적절하게 태그가 지정되도록 할 수 있습니다.' }, { ans:'C', txt:'C가 맞습니다. AWS Service Catalog를 사용하면 조직은 AWS에서 사용하도록 승인된 IT 서비스 카탈로그를 생성하고 관리할 수 있습니다. 이는 사용자가 사용할 수 있는 Amazon EMR 버전 및 클러스터 구성을 제어하는 ​​데 이상적입니다. 각 사용자 페르소나에 대해 특정 클러스터 구성 및 권한을 설정하여 필요한 액세스 권한만 부여할 수 있습니다. 이는 최소 권한 원칙을 충족합니다. 사용자가 특정 애플리케이션만 실행할 수 있도록 서비스 카탈로그를 구성하여 승인된 소프트웨어에 대한 회사 정책을 준수할 수 있습니다. 리소스 태깅도 지원합니다.' }, { ans:'A', txt:'A - IAM Roles define actions Service Catalogue is about resources (EMR)' }, { ans:'C', txt:'From GPT: AWS Service Catalog allows you to control and manage access to resources by defining portfolios and products with specific permissions. Allows you to create portfolios with approved and authorized applications, ensuring that only the specified applications are launched. AWS Service Catalog can enforce tagging on provisioned resources, ensuring that all resources created by the user pe...' }]
  }
];
