window.QS_SET39 = [
  {
    n: 381,
    en: `A company built an ecommerce website on AWS using a three-tier web architecture. The application is Java-based and composed of an Amazon CloudFront distribution, an Apache web server layer of Amazon EC2 instances in an Auto Scaling group, and a backend Amazon Aurora MySQL database.<br/><br/>Last month, during a promotional sales event, users reported errors and timeouts while adding items to their shopping carts. The operations team recovered the logs created by the web servers and reviewed Aurora DB cluster performance metrics. Some of the web servers were terminated before logs could be collected and the Aurora metrics were not sufficient for query performance analysis.<br/><br/>Which combination of steps must the solutions architect take to improve application performance visibility during peak traffic events? (Choose three.)`,
    ko: `한 회사는 3계층 웹 아키텍처를 사용하여 AWS에 전자상거래 웹사이트를 구축했습니다. 애플리케이션은 Java 기반이며 Amazon CloudFront 배포, Auto Scaling 그룹에 있는 Amazon EC2 인스턴스의 Apache 웹 서버 계층, 백엔드 Amazon Aurora MySQL 데이터베이스로 구성됩니다. <br/><br/>지난 달 프로모션 판매 이벤트 중에 사용자가 장바구니에 항목을 추가하는 동안 오류 및 시간 초과가 발생했다고 보고했습니다. 운영팀은 웹 서버에서 생성된 로그를 복구하고 Aurora DB 클러스터 성능 지표를 검토했습니다. 로그가 수집되기 전에 일부 웹 서버가 종료되었으며 Aurora 지표가 쿼리 성능 분석에 충분하지 않았습니다. <br/><br/>피크 트래픽 이벤트 중에 애플리케이션 성능 가시성을 개선하기 위해 솔루션 설계자가 수행해야 하는 단계 조합은 무엇입니까? (3개를 선택하세요.)`,
    type: 'multi', multiCount: 3,
    choices: [
      { k:'A', en:`Configure the Aurora MySQL DB cluster to publish slow query and error logs to Amazon CloudWatch Logs.`, ko:`Amazon CloudWatch Logs에 느린 쿼리 및 오류 로그를 게시하도록 Aurora MySQL DB 클러스터를 구성하십시오.` },
      { k:'B', en:`Implement the AWS X-Ray SDK to trace incoming HTTP requests on the EC2 instances and implement tracing of SQL queries with the X-Ray SDK for Java.`, ko:`AWS X-Ray SDK를 구현하여 EC2 인스턴스에서 들어오는 HTTP 요청을 추적하고 Java용 X-Ray SDK를 사용하여 SQL 쿼리 추적을 구현합니다.` },
      { k:'C', en:`Configure the Aurora MySQL DB cluster to stream slow query and error logs to Amazon Kinesis.`, ko:`느린 쿼리 및 오류 로그를 Amazon Kinesis로 스트리밍하도록 Aurora MySQL DB 클러스터를 구성합니다.` },
      { k:'D', en:`Install and configure an Amazon CloudWatch Logs agent on the EC2 instances to send the Apache logs to CloudWatch Logs.`, ko:`EC2 인스턴스에 Amazon CloudWatch Logs 에이전트를 설치하고 구성하여 Apache 로그를 CloudWatch Logs로 보냅니다.` },
      { k:'E', en:`Enable and configure AWS CloudTrail to collect and analyze application activity from Amazon EC2 and Aurora`, ko:`Amazon EC2 및 Aurora에서 애플리케이션 활동을 수집하고 분석하도록 AWS CloudTrail을 활성화하고 구성합니다.` },
      { k:'F', en:`Enable Aurora MySQL DB cluster performance benchmarking and publish the stream to AWS X-Ray.`, ko:`Aurora MySQL DB 클러스터 성능 벤치마킹을 활성화하고 스트림을 AWS X-Ray에 게시합니다.` },
    ],
    answer: [],
    vote: '100% ABD',
    explain: ``,
    wrong: `<p><span class="mark-no">❌ A</span> — 에이, 비, 디</p><p><span class="mark-no">❌ B</span> — 에이, 비, 디</p><p><span class="mark-no">❌ D</span> — 에이, 비, 디</p>`,
    disc: [{ ans:'A, B, D', txt:'느린 쿼리 및 오류 로그를 CloudWatch Logs에 게시하면 데이터베이스 성능 문제를 더 잘 분석할 수 있습니다. 이는 애플리케이션 성능 문제의 원인이 될 수 있는 느리게 실행되는 쿼리를 식별하는 데 도움이 됩니다. AWS X-Ray SDK를 애플리케이션에 통합하면 EC2 인스턴스에서 수신되는 HTTP 요청을 추적할 수 있습니다. X-Ray SDK for Java를 사용하여 SQL 쿼리를 추적하면 데이터베이스 쿼리가 애플리케이션 성능에 어떤 영향을 미치는지에 대한 통찰력을 얻을 수 있습니다. X-Ray는 성능 병목 현상을 진단하는 데 필수적인 서비스 수준 및 데이터베이스 수준 작업 모두에 대한 자세한 분석을 제공할 수 있습니다. AWS X-Ray SDK를 애플리케이션에 통합하면 EC2 인스턴스에서...' }, { ans:'A, B, D', txt:'Publishing slow query and error logs to CloudWatch Logs will allow for better analysis of database performance issues. It helps in identifying slow-running queries that might be contributing to the application\'s performance problems. Integrating AWS X-Ray SDK into the application will enable tracing of incoming HTTP requests on the EC2 instances. Tracing SQL queries with the X-Ray SDK for Java ...' }, { ans:'A, B, D', txt:'Answer: A B D' }, { ans:'A, B, D', txt:'에이, 비, 디' }, { ans:'A, B, D', txt:'ABD - 효과적으로 로그를 수집하고(DB, 인스턴스에서) XRay를 사용하여 호출에서 요청 <-> 응답을 추적하여 무슨 일이 일어나고 있는지 이해해야 합니다. https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/USER_LogAccess.Concepts.MySQL.html#USER_LogAccess.MySQLDB.PublishAuroraMySQLtoCloudWatchLogs https://aws.amazon.com/blogs/mt/simplifying-apache-server -logs-with-amazon-cloudwatch-logs-insights/ https://docs.aws.amazon.com/xray/latest/devguide/xr...' }]
  },
  {
    n: 382,
    en: `A company that provisions job boards for a seasonal workforce is seeing an increase in traffic and usage. The backend services run on a pair of Amazon EC2 instances behind an Application Load Balancer with Amazon DynamoDB as the datastore. Application read and write traffic is slow during peak seasons.<br/><br/>Which option provides a scalable application architecture to handle peak seasons with the LEAST development effort?`,
    ko: `계절별 인력을 위한 채용 게시판을 제공하는 회사에서는 트래픽과 사용량이 증가하고 있습니다. 백엔드 서비스는 Amazon DynamoDB를 데이터 스토어로 사용하는 Application Load Balancer 뒤의 Amazon EC2 인스턴스 쌍에서 실행됩니다. 성수기에는 애플리케이션 읽기 및 쓰기 트래픽이 느립니다. <br/><br/>최소한의 개발 노력으로 성수기를 처리할 수 있는 확장 가능한 애플리케이션 아키텍처를 제공하는 옵션은 무엇입니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Migrate the backend services to AWS Lambda. Increase the read and write capacity of DynamoDB.`, ko:`백엔드 서비스를 AWS Lambda로 마이그레이션합니다. DynamoDB의 읽기 및 쓰기 용량을 늘립니다.` },
      { k:'B', en:`Migrate the backend services to AWS Lambda. Configure DynamoDB to use global tables.`, ko:`백엔드 서비스를 AWS Lambda로 마이그레이션합니다. 전역 테이블을 사용하도록 DynamoDB를 구성합니다.` },
      { k:'C', en:`Use Auto Scaling groups for the backend services. Use DynamoDB auto scaling.`, ko:`백엔드 서비스에 Auto Scaling 그룹을 사용합니다. DynamoDB Auto Scaling을 사용합니다.` },
      { k:'D', en:`Use Auto Scaling groups for the backend services. Use Amazon Simple Queue Service (Amazon SQS) and an AWS Lambda function to write to DynamoDB.`, ko:`백엔드 서비스에 Auto Scaling 그룹을 사용합니다. Amazon Simple Queue Service(Amazon SQS) 및 AWS Lambda 함수를 사용하여 DynamoDB에 씁니다.` },
    ],
    answer: ["C"],
    vote: '100% C',
    explain: `<p><span class="mark-ok">✅ C</span></p><p>정답입니다. 일반적으로 B는 옳지만 B에서 Lambda용 앱을 다시 작성하는 데 필요한 최소한의 개발 노력으로 확장 그룹을 구성하면 성수기 트래픽을 처리할 수 있도록 확장할 수 있습니다.</p>`,
    wrong: ``,
    disc: [{ ans:'C', txt:'자동 크기 조정' }, { ans:'C', txt:'C 확실히요' }, { ans:'C', txt:'답: C' }, { ans:'C', txt:'Auto scaling' }, { ans:'C', txt:'C for sure' }]
  },
  {
    n: 383,
    en: `A company is migrating to the cloud. It wants to evaluate the configurations of virtual machines in its existing data center environment to ensure that it can size new Amazon EC2 instances accurately. The company wants to collect metrics, such as CPU, memory, and disk utilization, and it needs an inventory of what processes are running on each instance. The company would also like to monitor network connections to map communications between servers.<br/><br/>Which would enable the collection of this data MOST cost effectively?`,
    ko: `한 회사가 클라우드로 마이그레이션하고 있습니다. 기존 데이터 센터 환경의 가상 머신 구성을 평가하여 새로운 Amazon EC2 인스턴스의 크기를 정확하게 조정할 수 있는지 확인하려고 합니다. 회사는 CPU, 메모리, 디스크 사용률과 같은 지표를 수집하려고 하며 각 인스턴스에서 실행 중인 프로세스에 대한 인벤토리가 필요합니다. 또한 회사는 네트워크 연결을 모니터링하여 서버 간의 통신을 매핑하려고 합니다. <br/><br/>이 데이터를 가장 비용 효율적으로 수집할 수 있는 방법은 무엇입니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Use AWS Application Discovery Service and deploy the data collection agent to each virtual machine in the data center.`, ko:`AWS Application Discovery Service를 사용하고 데이터 센터의 각 가상 머신에 데이터 수집 에이전트를 배포합니다.` },
      { k:'B', en:`Configure the Amazon CloudWatch agent on all servers within the local environment and publish metrics to Amazon CloudWatch Logs.`, ko:`로컬 환경 내의 모든 서버에서 Amazon CloudWatch 에이전트를 구성하고 Amazon CloudWatch Logs에 지표를 게시합니다.` },
      { k:'C', en:`Use AWS Application Discovery Service and enable agentless discovery in the existing virtualization environment.`, ko:`AWS Application Discovery Service를 사용하고 기존 가상화 환경에서 에이전트 없는 검색을 활성화합니다.` },
      { k:'D', en:`Enable AWS Application Discovery Service in the AWS Management Console and configure the corporate firewall to allow scans over a VPN.`, ko:`AWS Management Console에서 AWS Application Discovery Service를 활성화하고 VPN을 통한 검색을 허용하도록 회사 방화벽을 구성합니다.` },
    ],
    answer: ["A"],
    vote: '90% A, 5% B, 5% C',
    explain: `<p><span class="mark-ok">✅ A</span></p><p>답: A</p>`,
    wrong: `<p><span class="mark-no">❌ B</span> — ㄴ 확실히요</p><p><span class="mark-no">❌ C</span> — https://docs.aws.amazon.com/application-discovery/latest/userguide/what-is-appdiscovery.html</p>`,
    disc: [{ ans:'A', txt:'답: A' }, { ans:'A', txt:'Answer: A' }, { ans:'A', txt:'옵션 A' }, { ans:'A', txt:'Option A' }, { ans:'A', txt:'에이전트 없는 검색은 VMWare만 지원합니다. 질문에는 VMWare가 언급되지 않았습니다.' }]
  },
  {
    n: 384,
    en: `A company provides a software as a service (SaaS) application that runs in the AWS Cloud. The application runs on Amazon EC2 instances behind a Network Load Balancer (NLB). The instances are in an Auto Scaling group and are distributed across three Availability Zones in a single AWS Region.<br/><br/>The company is deploying the application into additional Regions. The company must provide static IP addresses for the application to customers so that the customers can add the IP addresses to allow lists. The solution must automatically route customers to the Region that is geographically closest to them.<br/><br/>Which solution will meet these requirements?`,
    ko: `회사는 AWS 클라우드에서 실행되는 SaaS(Software as a Service) 애플리케이션을 제공합니다. 애플리케이션은 NLB(Network Load Balancer) 뒤의 Amazon EC2 인스턴스에서 실행됩니다. 인스턴스는 Auto Scaling 그룹에 속하며 단일 AWS 지역의 3개 가용 영역에 분산됩니다. <br/><br/>회사는 추가 지역에 애플리케이션을 배포하고 있습니다. 회사는 고객이 IP 주소를 허용 목록에 추가할 수 있도록 애플리케이션에 대한 고정 IP 주소를 고객에게 제공해야 합니다. 솔루션은 고객을 지리적으로 가장 가까운 지역으로 자동 라우팅해야 합니다. <br/><br/>어떤 솔루션이 이러한 요구 사항을 충족합니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Create an Amazon CloudFront distribution. Create a CloudFront origin group. Add the NLB for each additional Region to the origin group. Provide customers with the IP address ranges of the distribution’s edge locations.`, ko:`Amazon CloudFront 배포판을 생성합니다. CloudFront 오리진 그룹을 생성합니다. 각 추가 지역에 대한 NLB를 원본 그룹에 추가합니다. 고객에게 배포 엣지 위치의 IP 주소 범위를 제공합니다.` },
      { k:'B', en:`Create an AWS Global Accelerator standard accelerator. Create a standard accelerator endpoint for the NLB in each additional Region. Provide customers with the Global Accelerator IP address.`, ko:`AWS Global Accelerator 표준 액셀러레이터를 생성합니다. 각 추가 지역에서 NLB에 대한 표준 가속기 엔드포인트를 생성합니다. 고객에게 Global Accelerator IP 주소를 제공합니다.` },
      { k:'C', en:`Create an Amazon CloudFront distribution. Create a custom origin for the NLB in each additional Region. Provide customers with the IP address ranges of the distribution’s edge locations.`, ko:`Amazon CloudFront 배포판을 생성합니다. 각 추가 지역에서 NLB에 대한 사용자 지정 원본을 만듭니다. 고객에게 배포 엣지 위치의 IP 주소 범위를 제공합니다.` },
      { k:'D', en:`Create an AWS Global Accelerator custom routing accelerator. Create a listener for the custom routing accelerator. Add the IP address and ports for the NLB in each additional Region. Provide customers with the Global Accelerator IP address.`, ko:`AWS Global Accelerator 사용자 지정 라우팅 액셀러레이터를 생성합니다. 사용자 정의 라우팅 가속기에 대한 수신기를 만듭니다. 각 추가 지역에 NLB에 대한 IP 주소와 포트를 추가합니다. 고객에게 Global Accelerator IP 주소를 제공합니다.` },
    ],
    answer: ["B"],
    vote: '89% B, 11% D',
    explain: `<p><span class="mark-ok">✅ B</span></p><p>대답은 D가 아니라 B입니다. CloudFront는 NLB와 작동하지 않으며 고정 IP 주소도 허용하지 않습니다. 표준 액셀러레이터는 사용자에게 가장 가까운 정상적인 엔드포인트로 트래픽을 자동으로 라우팅합니다. 트래픽의 로드 밸런싱을 위해 설계되었으므로 여러 사용자를 액셀러레이터 뒤의 특정 EC2 대상으로 결정적으로 라우팅할 수 없습니다. 사용자 정의 라우팅 가속기를 사용하면 바로 이러한 작업을 수행할 수 있습니다. 또 다른 차이점은 표준 라우팅 가속기가 Network Load Balancer, Application Load Balancer, EC2 인스턴스 및 탄력적 IP를 엔드포인트로 지원한다는 것입니다. 사용자 지정 라우팅 액셀러레이터는 애플리케이션을 실행하는 하나 이상의 EC2 인스턴스를 포함하...</p>`,
    wrong: `<p><span class="mark-no">❌ D</span> — https://aws.amazon.com/blogs/networking-and-content-delivery/introducing-aws-global-accelerator-custom-routing-accelerators/</p>`,
    disc: [{ ans:'B', txt:'대답은 D가 아니라 B입니다. CloudFront는 NLB와 작동하지 않으며 고정 IP 주소도 허용하지 않습니다. 표준 액셀러레이터는 사용자에게 가장 가까운 정상적인 엔드포인트로 트래픽을 자동으로 라우팅합니다. 트래픽의 로드 밸런싱을 위해 설계되었으므로 여러 사용자를 액셀러레이터 뒤의 특정 EC2 대상으로 결정적으로 라우팅할 수 없습니다. 사용자 정의 라우팅 가속기를 사용하면 바로 이러한 작업을 수행할 수 있습니다. 또 다른 차이점은 표준 라우팅 가속기가 Network Load Balancer, Application Load Balancer, EC2 인스턴스 및 탄력적 IP를 엔드포인트로 지원한다는 것입니다. 사용자 지정 라우팅 액셀러레이터는 애플리케이션을 실행하는 하나 이상의 EC2 인스턴스를 포함하...' }, { ans:'B', txt:'Answer is B not D. CloudFront does not work with NLB nor does it accept a fixed IP address A Standard accelerators automatically route traffic to a healthy endpoint that is nearest to your user. Since they\'re designed to load balance traffic, you can\'t deterministically route multiple users to a specific EC2 destination behind your accelerator. Custom routing accelerators allows you to do just ...' }, { ans:'B', txt:'B가 맞아요' }, { ans:'B', txt:'B is correct' }, { ans:'B', txt:'답변 B. 표준 액셀러레이터의 경우 엔드포인트는 Network Load Balancer, Application Load Balancer, Amazon EC2 인스턴스 또는 탄력적 IP 주소입니다. 사용자 지정 라우팅 액셀러레이터의 경우 엔드포인트는 하나 이상의 EC2 인스턴스가 있는 Virtual Private Cloud(VPC) 서브넷입니다.' }]
  },
  {
    n: 385,
    en: `A company is running multiple workloads in the AWS Cloud. The company has separate units for software development. The company uses AWS Organizations and federation with SAML to give permissions to developers to manage resources in their AWS accounts. The development units each deploy their production workloads into a common production account.<br/><br/>Recently, an incident occurred in the production account in which members of a development unit terminated an EC2 instance that belonged to a different development unit. A solutions architect must create a solution that prevents a similar incident from happening in the future. The solution also must allow developers the possibility to manage the instances used for their workloads.<br/><br/>Which strategy will meet these requirements?`,
    ko: `한 회사가 AWS 클라우드에서 여러 워크로드를 실행하고 있습니다. 회사에는 소프트웨어 개발을 위한 별도의 부서가 있습니다. 회사는 AWS Organizations 및 SAML과의 연동을 사용하여 개발자에게 AWS 계정의 리소스를 관리할 수 있는 권한을 부여합니다. 각 개발 단위는 프로덕션 워크로드를 공통 프로덕션 계정에 배포합니다. <br/><br/>최근 프로덕션 계정에서 개발 단위 구성원이 다른 개발 단위에 속한 EC2 인스턴스를 종료하는 사건이 발생했습니다. 솔루션 설계자는 향후 유사한 사고가 발생하지 않도록 방지하는 솔루션을 만들어야 합니다. 또한 솔루션을 통해 개발자는 워크로드에 사용되는 인스턴스를 관리할 수 있어야 합니다. <br/><br/>이러한 요구 사항을 충족하는 전략은 무엇입니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Create separate OUs in AWS Organizations for each development unit. Assign the created OUs to the company AWS accounts. Create separate SCP with a deny action and a StringNotEquals condition for the DevelopmentUnit resource tag that matches the development unit name. Assign the SCP to the corresponding OU.`, ko:`각 개발 단위에 대해 AWS Organizations에서 별도의 OU를 생성합니다. 생성된 OU를 회사 AWS 계정에 할당합니다. 개발 단위 이름과 일치하는 DevelopmentUnit 리소스 태그에 대한 거부 작업 및 StringNotEquals 조건을 사용하여 별도의 SCP를 생성합니다. 해당 OU에 SCP를 할당합니다.` },
      { k:'B', en:`Pass an attribute for DevelopmentUnit as an AWS Security Token Service (AWS STS) session tag during SAML federation. Update the IAM policy for the developers’ assumed IAM role with a deny action and a StringNotEquals condition for the DevelopmentUnit resource tag and aws:PrincipalTag/DevelopmentUnit.`, ko:`SAML 연동 중에 DevelopmentUnit의 속성을 AWS Security Token Service(AWS STS) 세션 태그로 전달합니다. DevelopmentUnit 리소스 태그 및 aws:PrincipalTag/DevelopmentUnit에 대한 거부 작업 및 StringNotEquals 조건을 사용하여 개발자가 맡은 IAM 역할에 대한 IAM 정책을 업데이트합니다.` },
      { k:'C', en:`Pass an attribute for DevelopmentUnit as an AWS Security Token Service (AWS STS) session tag during SAML federation. Create an SCP with an allow action and a StringEquals condition for the DevelopmentUnit resource tag and aws:PrincipalTag/DevelopmentUnit. Assign the SCP to the root OU.`, ko:`SAML 연동 중에 DevelopmentUnit의 속성을 AWS Security Token Service(AWS STS) 세션 태그로 전달합니다. DevelopmentUnit 리소스 태그 및 aws:PrincipalTag/DevelopmentUnit에 대한 허용 작업과 StringEquals 조건을 사용하여 SCP를 생성합니다. SCP를 루트 OU에 할당합니다.` },
      { k:'D', en:`Create separate IAM policies for each development unit. For every IAM policy, add an allow action and a StringEquals condition for the DevelopmentUnit resource tag and the development unit name. During SAML federation, use AWS Security Token Service (AWS STS) to assign the IAM policy and match the development unit name to the assumed IAM role.`, ko:`각 개발 단위에 대해 별도의 IAM 정책을 만듭니다. 모든 IAM 정책에 대해 DevelopmentUnit 리소스 태그와 개발 단위 이름에 대한 허용 작업과 StringEquals 조건을 추가합니다. SAML 연동 중에 AWS Security Token Service(AWS STS)를 사용하여 IAM 정책을 할당하고 개발 단위 이름을 가정된 IAM 역할과 일치시킵니다.` },
    ],
    answer: ["B"],
    vote: '73% B, 27% A',
    explain: `<p><span class="mark-ok">✅ B</span></p><p>옵션 A는 일반 프로덕션 계정에서 작동하지 않습니다.</p>`,
    wrong: `<p><span class="mark-no">❌ A</span> — 확실히</p>`,
    disc: [{ ans:'A', txt:'확실히' }, { ans:'A', txt:'A for sure' }, { ans:'B', txt:'B가 가장 좋은 대답입니다. 이 접근 방식에는 DevelopmentUnit 속성을 사용하여 연합 ID 세션에 태그를 지정한 다음 리소스의 DevelopmentUnit 태그가 aws:PrincipalTag/DevelopmentUnit와 일치하지 않는 경우 IAM 정책을 사용하여 작업을 거부하는 작업이 포함됩니다. 이 방법은 권한을 페더레이션 ID에 직접 연결하여 요구 사항에 맞게 더욱 세분화된 액세스 제어를 허용합니다.' }, { ans:'B', txt:'B is the best answer. This approach involves tagging federated identity sessions with a DevelopmentUnit attribute and then using IAM policies to deny actions if the DevelopmentUnit tag of the resource does not match the aws:PrincipalTag/DevelopmentUnit. This method directly ties permissions to the federated identity, allowing for finer-grained access control that aligns with your requirements.' }, { ans:'B', txt:'옵션 A는 일반 프로덕션 계정에서 작동하지 않습니다.' }]
  },
  {
    n: 386,
    en: `An enterprise company is building an infrastructure services platform for its users. The company has the following requirements:<br/><br/>•	Provide least privilege access to users when launching AWS infrastructure so users cannot provision unapproved services.<br/>•	Use a central account to manage the creation of infrastructure services.<br/>•	Provide the ability to distribute infrastructure services to multiple accounts in AWS Organizations.<br/>•	Provide the ability to enforce tags on any infrastructure that is started by users.<br/><br/>Which combination of actions using AWS services will meet these requirements? (Choose three.)`,
    ko: `한 엔터프라이즈 회사가 사용자를 위한 인프라 서비스 플랫폼을 구축하고 있습니다. 회사에는 다음과 같은 요구 사항이 있습니다. <br/><br/>• 사용자가 승인되지 않은 서비스를 프로비저닝할 수 없도록 AWS 인프라를 시작할 때 사용자에게 최소 권한 액세스를 제공합니다. <br/>• 중앙 계정을 사용하여 인프라 서비스 생성을 관리합니다. <br/>• AWS Organizations의 여러 계정에 인프라 서비스를 배포하는 기능을 제공합니다. <br/>• 사용자가 시작한 모든 인프라에 태그를 적용하는 기능을 제공합니다. <br/><br/>AWS 서비스를 사용하는 어떤 작업 조합이 이러한 요구 사항을 충족합니까? (3개를 선택하세요.)`,
    type: 'multi', multiCount: 3,
    choices: [
      { k:'A', en:`Develop infrastructure services using AWS CloudFormation templates. Add the templates to a central Amazon S3 bucket and add the IAM roles or users that require access to the S3 bucket policy.`, ko:`AWS CloudFormation 템플릿을 사용하여 인프라 서비스를 개발합니다. 중앙 Amazon S3 버킷에 템플릿을 추가하고 S3 버킷 정책에 액세스해야 하는 IAM 역할 또는 사용자를 추가합니다.` },
      { k:'B', en:`Develop infrastructure services using AWS CloudFormation templates. Upload each template as an AWS Service Catalog product to portfolios created in a central AWS account. Share these portfolios with the Organizations structure created for the company.`, ko:`AWS CloudFormation 템플릿을 사용하여 인프라 서비스를 개발합니다. 중앙 AWS 계정에서 생성된 포트폴리오에 각 템플릿을 AWS Service Catalog 제품으로 업로드합니다. 이러한 포트폴리오를 회사를 위해 생성된 조직 구조와 공유하세요.` },
      { k:'C', en:`Allow user IAM roles to have AWSCloudFormationFullAccess and AmazonS3ReadOnlyAccess permissions. Add an Organizations SCP at the AWS account root user level to deny all services except AWS CloudFormation and Amazon S3.`, ko:`사용자 IAM 역할이 AWSCloudFormationFullAccess 및 AmazonS3ReadOnlyAccess 권한을 갖도록 허용합니다. AWS CloudFormation 및 Amazon S3를 제외한 모든 서비스를 거부하려면 AWS 계정 루트 사용자 수준에서 조직 SCP를 추가합니다.` },
      { k:'D', en:`Allow user IAM roles to have ServiceCatalogEndUserAccess permissions only. Use an automation script to import the central portfolios to local AWS accounts, copy the TagOption, assign users access, and apply launch constraints.`, ko:`사용자 IAM 역할이 ServiceCatalogEndUserAccess 권한만 갖도록 허용합니다. 자동화 스크립트를 사용하여 중앙 포트폴리오를 로컬 AWS 계정으로 가져오고, TagOption을 복사하고, 사용자 액세스를 할당하고, 시작 제약 조건을 적용합니다.` },
      { k:'E', en:`Use the AWS Service Catalog TagOption Library to maintain a list of tags required by the company. Apply the TagOption to AWS Service Catalog products or portfolios.`, ko:`AWS Service Catalog TagOption 라이브러리를 사용하여 회사에서 요구하는 태그 목록을 유지 관리합니다. AWS Service Catalog 제품 또는 포트폴리오에 TagOption을 적용합니다.` },
      { k:'F', en:`Use the AWS CloudFormation Resource Tags property to enforce the application of tags to any CloudFormation templates that will be created for users.`, ko:`AWS CloudFormation 리소스 태그 속성을 사용하여 사용자를 위해 생성될 모든 CloudFormation 템플릿에 태그 적용을 적용합니다.` },
    ],
    answer: [],
    vote: '93% BDE, 7% BCE',
    explain: ``,
    wrong: `<p><span class="mark-no">❌ B</span> — BDE - 서비스 카탈로그 참조</p><p><span class="mark-no">❌ C</span> — Answer BCE</p><p><span class="mark-no">❌ D</span> — BDE - 서비스 카탈로그 참조</p><p><span class="mark-no">❌ E</span> — BDE - 서비스 카탈로그 참조</p>`,
    disc: [{ ans:'B, D, E', txt:'BDE - 서비스 카탈로그 참조' }, { ans:'B, D, E', txt:'BDE - refer Service Catalog' }, { ans:'B, D, E', txt:'승인됨 == 서비스 카탈로그' }, { ans:'B, D, E', txt:'Approved == Service Catalog' }, { ans:'B, D, E', txt:'우리는 서비스 카탈로그를 사용하기 때문에 정답은 BDE가 되어야 한다고 생각합니다. 따라서 다른 모든 옵션은 이를 참조해야 합니다.' }]
  },
  {
    n: 387,
    en: `A company deploys a new web application. As part of the setup, the company configures AWS WAF to log to Amazon S3 through Amazon Kinesis Data Firehose. The company develops an Amazon Athena query that runs once daily to return AWS WAF log data from the previous 24 hours. The volume of daily logs is constant. However, over time, the same query is taking more time to run.<br/><br/>A solutions architect needs to design a solution to prevent the query time from continuing to increase. The solution must minimize operational overhead.<br/><br/>Which solution will meet these requirements?`,
    ko: `회사에서 새로운 웹 애플리케이션을 배포합니다. 설정의 일부로 회사는 Amazon Kinesis Data Firehose를 통해 Amazon S3에 로그인하도록 AWS WAF를 구성합니다. 이 회사는 매일 한 번 실행되어 지난 24시간 동안의 AWS WAF 로그 데이터를 반환하는 Amazon Athena 쿼리를 개발합니다. 일일 로그의 양은 일정합니다. 그러나 시간이 지남에 따라 동일한 쿼리를 실행하는 데 더 많은 시간이 걸립니다. <br/><br/>솔루션 설계자는 쿼리 시간이 계속해서 증가하지 않도록 솔루션을 설계해야 합니다. 솔루션은 운영 오버헤드를 최소화해야 합니다. <br/><br/>어떤 솔루션이 이러한 요구 사항을 충족합니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Create an AWS Lambda function that consolidates each day's AWS WAF logs into one log file.`, ko:`매일의 AWS WAF 로그를 하나의 로그 파일로 통합하는 AWS Lambda 함수를 생성합니다.` },
      { k:'B', en:`Reduce the amount of data scanned by configuring AWS WAF to send logs to a different S3 bucket each day.`, ko:`매일 다른 S3 버킷으로 로그를 보내도록 AWS WAF를 구성하여 스캔되는 데이터의 양을 줄입니다.` },
      { k:'C', en:`Update the Kinesis Data Firehose configuration to partition the data in Amazon S3 by date and time. Create external tables for Amazon Redshift. Configure Amazon Redshift Spectrum to query the data source.`, ko:`Amazon S3의 데이터를 날짜 및 시간별로 분할하도록 Kinesis Data Firehose 구성을 업데이트합니다. Amazon Redshift용 외부 테이블을 생성합니다. 데이터 소스를 쿼리하도록 Amazon Redshift Spectrum을 구성합니다.` },
      { k:'D', en:`Modify the Kinesis Data Firehose configuration and Athena table definition to partition the data by date and time. Change the Athena query to view the relevant partitions.`, ko:`날짜 및 시간별로 데이터를 분할하도록 Kinesis Data Firehose 구성 및 Athena 테이블 정의를 수정합니다. 관련 파티션을 보려면 Athena 쿼리를 변경하세요.` },
    ],
    answer: ["D"],
    vote: '100% D',
    explain: `<p><span class="mark-ok">✅ D</span></p><p>옵션 D</p>`,
    wrong: ``,
    disc: [{ ans:'D', txt:'D는 괜찮아요' }, { ans:'D', txt:'D is ok' }, { ans:'D', txt:'옵션 D' }, { ans:'D', txt:'D. 사용자는 다양한 로그를 일별 파티션으로 분할할 수 있습니다. 일일 볼륨이 일정하므로 시간이 지나도 처리 시간이 늘어나지 않습니다.' }, { ans:'D', txt:'D는 간단하고 하기 쉽다' }]
  },
  {
    n: 388,
    en: `A company is developing a web application that runs on Amazon EC2 instances in an Auto Scaling group behind a public-facing Application Load Balancer (ALB). Only users from a specific country are allowed to access the application. The company needs the ability to log the access requests that have been blocked. The solution should require the least possible maintenance.<br/><br/>Which solution meets these requirements?`,
    ko: `한 회사는 공용 ALB(Application Load Balancer) 뒤에 있는 Auto Scaling 그룹의 Amazon EC2 인스턴스에서 실행되는 웹 애플리케이션을 개발하고 있습니다. 특정 국가의 사용자만 애플리케이션에 액세스할 수 있습니다. 회사에는 차단된 액세스 요청을 기록하는 기능이 필요합니다. 솔루션에는 최소한의 유지 관리만 필요합니다. <br/><br/>이러한 요구 사항을 충족하는 솔루션은 무엇입니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Create an IPSet containing a list of IP ranges that belong to the specified country. Create an AWS WAF web ACL. Configure a rule to block any requests that do not originate from an IP range in the IPSet. Associate the rule with the web ACL. Associate the web ACL with the ALB.`, ko:`지정된 국가에 속하는 IP 범위 목록을 포함하는 IPSet을 생성합니다. AWS WAF 웹 ACL을 생성합니다. IPSet의 IP 범위에서 발생하지 않는 요청을 차단하는 규칙을 구성합니다. 규칙을 웹 ACL과 연결합니다. 웹 ACL을 ALB와 연결합니다.` },
      { k:'B', en:`Create an AWS WAF web ACL. Configure a rule to block any requests that do not originate from the specified country. Associate the rule with the web ACL. Associate the web ACL with the ALB.`, ko:`AWS WAF 웹 ACL을 생성합니다. 지정된 국가에서 발생하지 않는 요청을 차단하는 규칙을 구성합니다. 규칙을 웹 ACL과 연결합니다. 웹 ACL을 ALB와 연결합니다.` },
      { k:'C', en:`Configure AWS Shield to block any requests that do not originate from the specified country. Associate AWS Shield with the ALB.`, ko:`지정된 국가에서 발생하지 않는 요청을 차단하도록 AWS Shield를 구성합니다. AWS Shield를 ALB와 연결합니다.` },
      { k:'D', en:`Create a security group rule that allows ports 80 and 443 from IP ranges that belong to the specified country. Associate the security group with the ALB.`, ko:`지정된 국가에 속한 IP 범위에서 포트 80 및 443을 허용하는 보안 그룹 규칙을 생성합니다. 보안 그룹을 ALB와 연결합니다.` },
    ],
    answer: ["B"],
    vote: '100% B',
    explain: `<p><span class="mark-ok">✅ B</span></p><p>옵션 B</p>`,
    wrong: ``,
    disc: [{ ans:'B', txt:'https://docs.aws.amazon.com/waf/latest/developerguide/waf-rule-statement-type-geo-match.html' }, { ans:'B', txt:'옵션 B' }, { ans:'B', txt:'답: ㄴ' }, { ans:'B', txt:'ㄴ 확실히요' }, { ans:'B', txt:'Option B' }]
  },
  {
    n: 389,
    en: `A company is migrating an application from on-premises infrastructure to the AWS Cloud. During migration design meetings, the company expressed concerns about the availability and recovery options for its legacy Windows file server. The file server contains sensitive business-critical data that cannot be recreated in the event of data corruption or data loss. According to compliance requirements, the data must not travel across the public internet. The company wants to move to AWS managed services where possible.<br/><br/>The company decides to store the data in an Amazon FSx for Windows File Server file system. A solutions architect must design a solution that copies the data to another AWS Region for disaster recovery (DR) purposes.<br/><br/>Which solution will meet these requirements?`,
    ko: `한 회사가 온프레미스 인프라에서 AWS 클라우드로 애플리케이션을 마이그레이션하고 있습니다. 마이그레이션 설계 회의에서 회사는 레거시 Windows 파일 서버의 가용성 및 복구 옵션에 대한 우려를 표명했습니다. 파일 서버에는 데이터 손상이나 데이터 손실 시 다시 생성할 수 없는 중요한 비즈니스 크리티컬 데이터가 포함되어 있습니다. 규정 준수 요구 사항에 따라 데이터는 공용 인터넷을 통해 이동해서는 안 됩니다. 회사는 가능한 경우 AWS 관리형 서비스로 전환하려고 합니다. <br/><br/>회사는 Amazon FSx for Windows File Server 파일 시스템에 데이터를 저장하기로 결정했습니다. 솔루션 아키텍트는 재해 복구(DR) 목적으로 데이터를 다른 AWS 리전에 복사하는 솔루션을 설계해야 합니다. <br/><br/>어떤 솔루션이 이러한 요구 사항을 충족합니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Create a destination Amazon S3 bucket in the DR Region. Establish connectivity between the FSx for Windows File Server file system in the primary Region and the S3 bucket in the DR Region by using Amazon FSx File Gateway. Configure the S3 bucket as a continuous backup source in FSx File Gateway.`, ko:`DR 지역에 대상 Amazon S3 버킷을 생성합니다. Amazon FSx 파일 게이트웨이를 사용하여 기본 지역의 FSx for Windows File Server 파일 시스템과 DR 지역의 S3 버킷 간에 연결을 설정합니다. FSx 파일 게이트웨이에서 S3 버킷을 연속 백업 소스로 구성합니다.` },
      { k:'B', en:`Create an FSx for Windows File Server file system in the DR Region. Establish connectivity between the VPC the primary Region and the VPC in the DR Region by using AWS Site-to-Site VPN. Configure AWS DataSync to communicate by using VPN endpoints.`, ko:`DR 지역에 FSx for Windows File Server 파일 시스템을 생성합니다. AWS Site-to-Site VPN을 사용하여 기본 리전인 VPC와 DR 리전의 VPC 간에 연결을 설정합니다. VPN 엔드포인트를 사용하여 통신하도록 AWS DataSync를 구성합니다.` },
      { k:'C', en:`Create an FSx for Windows File Server file system in the DR Region. Establish connectivity between the VPC in the primary Region and the VPC in the DR Region by using VPC peering. Configure AWS DataSync to communicate by using interface VPC endpoints with AWS PrivateLink.`, ko:`DR 지역에 FSx for Windows File Server 파일 시스템을 생성합니다. VPC 피어링을 사용하여 기본 지역의 VPC와 DR 지역의 VPC 간의 연결을 설정합니다. AWS PrivateLink와 인터페이스 VPC 엔드포인트를 사용하여 통신하도록 AWS DataSync를 구성합니다.` },
      { k:'D', en:`Create an FSx for Windows File Server file system in the DR Region. Establish connectivity between the VPC in the primary Region and the VPC in the DR Region by using AWS Transit Gateway in each Region. Use AWS Transfer Family to copy files between the FSx for Windows File Server file system in the primary Region and the FSx for Windows File Server file system in the DR Region over the private AWS backbone network.`, ko:`DR 지역에 FSx for Windows File Server 파일 시스템을 생성합니다. 각 리전의 AWS Transit Gateway를 사용하여 기본 리전의 VPC와 DR 리전의 VPC 간의 연결을 설정합니다. AWS Transfer Family를 사용하여 프라이빗 AWS 백본 네트워크를 통해 기본 지역의 FSx for Windows File Server 파일 시스템과 DR 지역의 FSx for Windows File Server 파일 시스템 간에 파일을 복사합니다.` },
    ],
    answer: ["C"],
    vote: '88% C, 12% A',
    explain: `<p><span class="mark-ok">✅ C</span></p><p>옵션 A는 DR 지역 간에 어떤 종류의 연결이 생성되는지 나타내지 않습니다. 옵션 C가 맞습니다.</p>`,
    wrong: `<p><span class="mark-no">❌ A</span> — 또 다른 끔찍하고 끔찍한 질문입니다. 어떤 답변도 모든 요구 사항을 충족하지 않습니다. - 데이터가 손상되거나 손실된 경우 데이터를 다시 생성할 수 없습니다. - 데이터는 공용 인터넷을 통해 이동해서는 안 됩니다. A - 인터넷 통과를 방지하는 방법을 지정하지 않지만(인터넷을 통과한다고 안전하게 가정할 수 있음) 적어도 기업이 손상되거나 삭제된 파일을 복구</p>`,
    disc: [{ ans:'C', txt:'A - S3의 경우 데이터는 인터넷을 통해 이동합니다. B - AWS 내의 2개 VPC에는 사이트 간 VPN이 필요하지 않습니다. C -VPC 피어링은 서로 다른 지역에 있는 2개의 VPC를 연결하는 데 가장 좋은 옵션입니다. D - 연결만 필요하므로 Transit Gateway가 필요하지 않습니다. 2개의 VPC 사이에서는 피어링이 더 비용 효율적입니다.' }, { ans:'C', txt:'VPC 피어링을 사용하여 FSx VPC를 연결합니다. DataSync 클라이언트가 PrivateLink https://aws.amazon.com/blogs/storage/how-to-replicate-amazon-fsx-file-server-data-across-aws-regions/를 사용하여 서버와 통신하도록 허용합니다.' }, { ans:'C', txt:'C는 괜찮아요' }, { ans:'C', txt:'A - for S3, data will traverse via internet B- Site to Site VPN is not required for 2 VPC within AWS C -VPC Peering is the best option for connecting 2 VPCs in different regions D - Transit Gateway not required as the connection is only between 2 VPC, Peering is more cost effective.' }, { ans:'C', txt:'Connect FSx VPCs using VPC peering. Allow DataSync client to communicate with server using PrivateLink https://aws.amazon.com/blogs/storage/how-to-replicate-amazon-fsx-file-server-data-across-aws-regions/' }]
  },
  {
    n: 390,
    en: `A company is currently in the design phase of an application that will need an RPO of less than 5 minutes and an RTO of less than 10 minutes. The solutions architecture team is forecasting that the database will store approximately 10 TB of data. As part of the design, they are looking for a database solution that will provide the company with the ability to fail over to a secondary Region.<br/><br/>Which solution will meet these business requirements at the LOWEST cost?`,
    ko: `한 회사는 현재 5분 미만의 RPO와 10분 미만의 RTO가 필요한 애플리케이션의 설계 단계에 있습니다. 솔루션 아키텍처 팀은 데이터베이스가 약 10TB의 데이터를 저장할 것으로 예상하고 있습니다. 설계의 일환으로 그들은 회사에 보조 지역으로 장애 조치할 수 있는 기능을 제공할 데이터베이스 솔루션을 찾고 있습니다. <br/><br/>가장 저렴한 비용으로 이러한 비즈니스 요구 사항을 충족할 수 있는 솔루션은 무엇입니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Deploy an Amazon Aurora DB cluster and take snapshots of the cluster every 5 minutes. Once a snapshot is complete, copy the snapshot to a secondary Region to serve as a backup in the event of a failure.`, ko:`Amazon Aurora DB 클러스터를 배포하고 5분마다 클러스터의 스냅샷을 찍습니다. 스냅샷이 완료되면 스냅샷을 보조 리전에 복사하여 장애 발생 시 백업으로 사용하세요.` },
      { k:'B', en:`Deploy an Amazon RDS instance with a cross-Region read replica in a secondary Region. In the event of a failure, promote the read replica to become the primary.`, ko:`보조 지역에 지역 간 읽기 전용 복제본이 있는 Amazon RDS 인스턴스를 배포합니다. 오류가 발생하면 읽기 전용 복제본을 기본 복제본으로 승격하세요.` },
      { k:'C', en:`Deploy an Amazon Aurora DB cluster in the primary Region and another in a secondary Region. Use AWS DMS to keep the secondary Region in sync.`, ko:`기본 지역에 Amazon Aurora DB 클러스터를 배포하고 보조 지역에 또 다른 클러스터를 배포합니다. AWS DMS를 사용하여 보조 리전을 동기화 상태로 유지하세요.` },
      { k:'D', en:`Deploy an Amazon RDS instance with a read replica in the same Region. In the event of a failure, promote the read replica to become the primary.`, ko:`동일한 지역에 읽기 전용 복제본이 있는 Amazon RDS 인스턴스를 배포합니다. 오류가 발생하면 읽기 전용 복제본을 기본 복제본으로 승격하세요.` },
    ],
    answer: ["B"],
    vote: '83% B, 17% C',
    explain: `<p><span class="mark-ok">✅ B</span></p><p>저는 B를 선택했습니다. C : Aurora DB가 자동으로 동기화를 지원합니다. 우리는 DMS를 사용하지 않습니다.</p>`,
    wrong: `<p><span class="mark-no">❌ C</span> — C 확실히요</p>`,
    disc: [{ ans:'B', txt:'답: ㄴ' }, { ans:'B', txt:'Answer: B' }, { ans:'B', txt:'물론 B입니다. C는 올바른 솔루션임에도 불구하고 너무 비쌉니다.' }, { ans:'C', txt:'C 확실히요' }, { ans:'B', txt:'B for sure, C is way too expensive even though it\'s a correct solution' }]
  }
];
