window.QS_SET30 = [
  {
    n: 291,
    en: `A company ingests and processes streaming market data. The data rate is constant. A nightly process that calculates aggregate statistics takes 4 hours to complete. The statistical analysis is not critical to the business, and data points are processed during the next iteration if a particular run fails.<br/><br/>The current architecture uses a pool of Amazon EC2 Reserved Instances with 1-year reservations. These EC2 instances run full time to ingest and store the streaming data in attached Amazon Elastic Block Store (Amazon EBS) volumes. A scheduled script launches EC2 On-Demand Instances each night to perform the nightly processing. The instances access the stored data from NFS shares on the ingestion servers. The script terminates the instances when the processing is complete.<br/><br/>The Reserved Instance reservations are expiring. The company needs to determine whether to purchase new reservations or implement a new design.<br/><br/>Which solution will meet these requirements MOST cost-effectively?`,
    ko: `회사는 스트리밍 시장 데이터를 수집하고 처리합니다. 데이터 속도는 일정합니다. 집계 통계를 계산하는 야간 프로세스는 완료하는 데 4시간이 걸립니다. 통계 분석은 비즈니스에 중요하지 않으며 특정 실행이 실패하면 다음 반복 중에 데이터 포인트가 처리됩니다. <br/><br/>현재 아키텍처는 1년 예약이 포함된 Amazon EC2 예약 인스턴스 풀을 사용합니다. 이러한 EC2 인스턴스는 풀타임으로 실행되어 연결된 Amazon Elastic Block Store(Amazon EBS) 볼륨에 스트리밍 데이터를 수집하고 저장합니다. 예약된 스크립트는 매일 밤 EC2 온디맨드 인스턴스를 시작하여 야간 처리를 수행합니다. 인스턴스는 수집 서버의 NFS 공유에 저장된 데이터에 액세스합니다. 처리가 완료되면 스크립트는 인스턴스를 종료합니다. <br/><br/>예약 인스턴스 예약이 만료됩니다. 회사는 새로운 예약을 구매할지 아니면 새로운 디자인을 구현할지 결정해야 합니다. <br/><br/>이러한 요구 사항을 가장 비용 효율적으로 충족하는 솔루션은 무엇입니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Update the ingestion process to use Amazon Kinesis Data Firehose to save data to Amazon S3. Use a scheduled script to launch a fleet of EC2 On-Demand Instances each night to perform the batch processing of the S3 data. Configure the script to terminate the instances when the processing is complete.`, ko:`Amazon Kinesis Data Firehose를 사용하여 Amazon S3에 데이터를 저장하도록 수집 프로세스를 업데이트합니다. 예약된 스크립트를 사용하여 매일 밤 EC2 온디맨드 인스턴스 집합을 시작하여 S3 데이터의 일괄 처리를 수행합니다. 처리가 완료되면 인스턴스를 종료하도록 스크립트를 구성합니다.` },
      { k:'B', en:`Update the ingestion process to use Amazon Kinesis Data Firehose to save data to Amazon S3. Use AWS Batch with Spot Instances to perform nightly processing with a maximum Spot price that is 50% of the On-Demand price.`, ko:`Amazon Kinesis Data Firehose를 사용하여 Amazon S3에 데이터를 저장하도록 수집 프로세스를 업데이트합니다. 스팟 인스턴스와 함께 AWS Batch를 사용하면 온디맨드 가격의 50%에 해당하는 최대 스팟 가격으로 야간 처리를 수행할 수 있습니다.` },
      { k:'C', en:`Update the ingestion process to use a fleet of EC2 Reserved Instances with 3-year reservations behind a Network LoadBalancer. Use AWS Batch with Spot Instances to perform nightly processing with a maximum Spot price that is 50% of the On-Demand price.`, ko:`Network LoadBalancer 뒤에 3년 예약이 포함된 EC2 예약 인스턴스 집합을 사용하도록 수집 프로세스를 업데이트합니다. 스팟 인스턴스와 함께 AWS Batch를 사용하면 온디맨드 가격의 50%에 해당하는 최대 스팟 가격으로 야간 처리를 수행할 수 있습니다.` },
      { k:'D', en:`Update the ingestion process to use Amazon Kinesis Data Firehose to save data to Amazon Redshift. Use Amazon EventBridge to schedule an AWS Lambda function to run nightly to query Amazon Redshift to generate the daily statistics.`, ko:`Amazon Kinesis Data Firehose를 사용하여 Amazon Redshift에 데이터를 저장하도록 수집 프로세스를 업데이트합니다. Amazon EventBridge를 사용하면 AWS Lambda 함수가 야간에 실행되어 Amazon Redshift에 쿼리하여 일일 통계를 생성하도록 예약할 수 있습니다.` },
    ],
    answer: ["B"],
    vote: '94% B, 6% C',
    explain: `<p><span class="mark-ok">✅ B</span></p><p>답변 B: https://docs.aws.amazon.com/batch/latest/userguide/best-practices.html</p>`,
    wrong: `<p><span class="mark-no">❌ C</span> — 안정적인 수집 속도를 위해 Firehose 및 S3API 비용보다 3년 예약 EC2를 선택합니다. 낮은 우선순위 집계에 스팟 인스턴스를 사용하면 비용이 더욱 절감됩니다.</p>`,
    disc: [{ ans:'B', txt:'A=> 예약된 스크립트를 사용하여 EC2 온디맨드 집합을 잘못 시작함 C=> EC2 예약 인스턴스 집합을 사용하도록 수집 프로세스를 업데이트함 D=> 람다가 잘못됨' }, { ans:'B', txt:'B - 맞습니다. 그리고 이것 때문에 -> "통계 분석은 비즈니스에 중요하지 않으며 특정 실행이 실패하면 다음 반복 중에 데이터 포인트가 처리됩니다." 스팟 인스턴스는 보장되지 않으며 위의 조건이 없다면 아마도 C보다 좋을 것입니다.' }, { ans:'B', txt:'A=> Use a scheduled script to launch a fleet of EC2 On-Demand wrong C=> Update the ingestion process to use a fleet of EC2 Reserved Instances wrong D=> lambda wrong' }, { ans:'B', txt:'B - Correct. And only because of this -> " The statistical analysis is not critical to the business, and data points are processed during the next iteration if a particular run fails." Spot instances are not guaranteed and if the condition above was not there, than probably C.' }, { ans:'B', txt:'B가 정답입니다. C에서는 3년 예약 인스턴스 NLB 외에 추가 비용이 발생합니다.' }]
  },
  {
    n: 292,
    en: `A company needs to migrate an on-premises SFTP site to AWS. The SFTP site currently runs on a Linux VM. Uploaded files are made available to downstream applications through an NFS share.<br/><br/>As part of the migration to AWS, a solutions architect must implement high availability. The solution must provide external vendors with a set of static public IP addresses that the vendors can allow. The company has set up an AWS Direct Connect connection between its on-premises data center and its VPC.<br/><br/>Which solution will meet these requirements with the LEAST operational overhead?`,
    ko: `회사는 온프레미스 SFTP 사이트를 AWS로 마이그레이션해야 합니다. SFTP 사이트는 현재 Linux VM에서 실행됩니다. 업로드된 파일은 NFS 공유를 통해 다운스트림 애플리케이션에서 사용할 수 있습니다. <br/><br/>AWS로 마이그레이션하는 과정에서 솔루션 아키텍트는 고가용성을 구현해야 합니다. 솔루션은 공급업체가 허용할 수 있는 고정 공용 IP 주소 집합을 외부 공급업체에 제공해야 합니다. 회사는 온프레미스 데이터 센터와 VPC 간에 AWS Direct Connect 연결을 설정했습니다. <br/><br/>최소한의 운영 오버헤드로 이러한 요구 사항을 충족하는 솔루션은 무엇입니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Create an AWS Transfer Family server. Configure an internet-facing VPC endpoint for the Transfer Family server. Specify an Elastic IP address for each subnet. Configure the Transfer Family server to place files into an Amazon Elastic File System (Amazon EFS) file system that is deployed across multiple Availability Zones. Modify the configuration on the downstream applications that access the existing NFS share to mount the EFS endpoint instead.`, ko:`AWS Transfer Family 서버를 생성합니다. Transfer Family 서버에 대한 인터넷 연결 VPC 엔드포인트를 구성합니다. 각 서브넷에 대해 탄력적 IP 주소를 지정합니다. 여러 가용 영역에 배포된 Amazon Elastic File System(Amazon EFS) 파일 시스템에 파일을 배치하도록 Transfer Family 서버를 구성합니다. 대신 EFS 엔드포인트를 탑재하도록 기존 NFS 공유에 액세스하는 다운스트림 애플리케이션의 구성을 수정합니다.` },
      { k:'B', en:`Create an AWS Transfer Family server. Configure a publicly accessible endpoint for the Transfer Family server. Configure the Transfer Family server to place files into an Amazon Elastic File System (Amazon EFS) file system that is deployed across multiple Availability Zones. Modify the configuration on the downstream applications that access the existing NFS share to mount the EFS endpoint instead.`, ko:`AWS Transfer Family 서버를 생성합니다. Transfer Family 서버에 대해 공개적으로 액세스 가능한 엔드포인트를 구성합니다. 여러 가용 영역에 배포된 Amazon Elastic File System(Amazon EFS) 파일 시스템에 파일을 배치하도록 Transfer Family 서버를 구성합니다. 대신 EFS 엔드포인트를 탑재하도록 기존 NFS 공유에 액세스하는 다운스트림 애플리케이션의 구성을 수정합니다.` },
      { k:'C', en:`Use AWS Application Migration Service to migrate the existing Linux VM to an Amazon EC2 instance. Assign an Elastic IP address to the EC2 instance. Mount an Amazon Elastic File System (Amazon EFS) file system to the EC2 instance. Configure the SFTP server to place files in the EFS file system. Modify the configuration on the downstream applications that access the existing NFS share to mount the EFS endpoint instead.`, ko:`AWS Application Migration Service를 사용하여 기존 Linux VM을 Amazon EC2 인스턴스로 마이그레이션합니다. EC2 인스턴스에 탄력적 IP 주소를 할당합니다. Amazon Elastic File System(Amazon EFS) 파일 시스템을 EC2 인스턴스에 탑재합니다. EFS 파일 시스템에 파일을 배치하도록 SFTP 서버를 구성합니다. 대신 EFS 엔드포인트를 탑재하도록 기존 NFS 공유에 액세스하는 다운스트림 애플리케이션의 구성을 수정합니다.` },
      { k:'D', en:`Use AWS Application Migration Service to migrate the existing Linux VM to an AWS Transfer Family server. Configure a publicly accessible endpoint for the Transfer Family server. Configure the Transfer Family server to place files into an Amazon FSx for Lustre file system that is deployed across multiple Availability Zones. Modify the configuration on the downstream applications that access the existing NFS share to mount the FSx for Lustre endpoint instead.`, ko:`AWS Application Migration Service를 사용하여 기존 Linux VM을 AWS Transfer Family 서버로 마이그레이션합니다. Transfer Family 서버에 대해 공개적으로 액세스 가능한 엔드포인트를 구성합니다. 여러 가용 영역에 배포되는 Amazon FSx for Lustre 파일 시스템에 파일을 배치하도록 Transfer Family 서버를 구성합니다. 대신 기존 NFS 공유에 액세스하는 다운스트림 애플리케이션의 구성을 수정하여 FSx for Lustre 엔드포인트를 탑재합니다.` },
    ],
    answer: ["A"],
    vote: '100% A',
    explain: `<p><span class="mark-ok">✅ A</span></p><p>옵션 A</p>`,
    wrong: ``,
    disc: [{ ans:'A', txt:'A는 정답입니다. B는 정답이 아닙니다. AWS Transfer Family의 공개적으로 액세스 가능한 엔드포인트의 경우 고정 IP 주소를 연결할 수 없기 때문입니다. AWS는 변경될 수 있는 IP 주소를 제공합니다. IP는 고정 Anycast IP 주소 https://repost.aws/knowledge-center/aws-sftp-endpoint-type을 사용하는 AWS Global Accelerator를 통해 제공됩니다.' }, { ans:'A', txt:'A is correct B is incorrect because for Publicly accessible endpoints for AWS Transfer Family you can’t attach a static IP address. AWS provides IP addresses that are subject to change. IPs are provided via AWS Global Accelerator, which uses static Anycast IP addresses https://repost.aws/knowledge-center/aws-sftp-endpoint-type' }, { ans:'A', txt:'옵션 A는 AWS Transfer Family 서버를 생성하고 이에 대한 인터넷 연결 VPC 엔드포인트를 구성할 것을 제안합니다. 각 서브넷에 대해 탄력적 IP 주소를 지정함으로써 회사는 외부 공급업체에 고정 공용 IP 주소 집합을 제공할 수 있습니다. Transfer Family 서버는 여러 가용 영역에 걸쳐 확장 가능하고 가용성이 높은 스토리지 솔루션을 제공하는 Amazon Elastic File System(Amazon EFS) 파일 시스템에 파일을 배치하도록 구성할 수 있습니다. 이를 통해 회사는 수동 개입이나 추가 운영 오버헤드 없이 SFTP 사이트 및 다운스트림 애플리케이션에 대한 고가용성을 유지할 수 있습니다.' }, { ans:'A', txt:'Option A suggests creating an AWS Transfer Family server and configuring an internet-facing VPC endpoint for it. By specifying an Elastic IP address for each subnet, the company can provide a set of static public IP addresses to external vendors. The Transfer Family server can be configured to place files into an Amazon Elastic File System (Amazon EFS) file system, which provides a scalable and...' }, { ans:'A', txt:'옵션 A' }]
  },
  {
    n: 293,
    en: `A solutions architect has an operational workload deployed on Amazon EC2 instances in an Auto Scaling group. The VPC architecture spans two Availability Zones (AZ) with a subnet in each that the Auto Scaling group is targeting. The VPC is connected to an on-premises environment and connectivity cannot be interrupted. The maximum size of the Auto Scaling group is 20 instances in service. The VPC IPv4 addressing is as follows:<br/><br/><br/>VPC CIDR: 10.0.0.0/23 -<br/><br/>AZ1 subnet CIDR: 10.0.0.0/24 -<br/><br/>AZ2 subnet CIDR: 10.0.1.0/24 -<br/><br/>Since deployment, a third AZ has become available in the Region. The solutions architect wants to adopt the new AZ without adding additional IPv4 address space and without service downtime. Which solution will meet these requirements?`,
    ko: `솔루션 아키텍트에는 Auto Scaling 그룹의 Amazon EC2 인스턴스에 배포된 운영 워크로드가 있습니다. VPC 아키텍처는 Auto Scaling 그룹이 대상으로 삼는 각각의 서브넷이 있는 두 개의 가용 영역(AZ)에 걸쳐 있습니다. VPC는 온프레미스 환경에 연결되어 있으며 연결이 중단될 수 없습니다. Auto Scaling 그룹의 최대 크기는 서비스 중인 인스턴스 20개입니다. VPC IPv4 주소 지정은 다음과 같습니다.<br/><br/><br/>VPC CIDR: 10.0.0.0/23 -<br/><br/>AZ1 subnet CIDR: 10.0.0.0/24 -<br/><br/>AZ2 subnet CIDR: 10.0.1.0/24 -<br/><br/>배포 이후 세 번째 AZ를 해당 지역에서 사용할 수 있게 되었습니다. 솔루션 설계자는 추가 IPv4 주소 공간을 추가하지 않고 서비스 가동 중지 시간 없이 새 AZ를 채택하기를 원합니다. 어떤 솔루션이 이러한 요구 사항을 충족합니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Update the Auto Scaling group to use the AZ2 subnet only. Delete and re-create the AZ1 subnet using half the previous address space. Adjust the Auto Scaling group to also use the new AZ1 subnet. When the instances are healthy, adjust the Auto Scaling group to use the AZ1 subnet only. Remove the current AZ2 subnet. Create a new AZ2 subnet using the second half of the address space from the original AZ1 subnet. Create a new AZ3 subnet using half the original AZ2 subnet address space, then update the Auto Scaling group to target all three new subnets.`, ko:`AZ2 서브넷만 사용하도록 Auto Scaling 그룹을 업데이트합니다. 이전 주소 공간의 절반을 사용하여 AZ1 서브넷을 삭제하고 다시 생성합니다. 새 AZ1 서브넷도 사용하도록 Auto Scaling 그룹을 조정합니다. 인스턴스가 정상이면 AZ1 서브넷만 사용하도록 Auto Scaling 그룹을 조정합니다. 현재 AZ2 서브넷을 제거합니다. 원래 AZ1 서브넷 주소 공간의 후반부를 사용하여 새 AZ2 서브넷을 생성합니다. 원래 AZ2 서브넷 주소 공간의 절반을 사용하여 새 AZ3 서브넷을 생성한 다음 세 개의 새 서브넷을 모두 대상으로 지정하도록 Auto Scaling 그룹을 업데이트합니다.` },
      { k:'B', en:`Terminate the EC2 instances in the AZ1 subnet. Delete and re-create the AZ1 subnet using half the address space. Update the Auto Scaling group to use this new subnet. Repeat this for the second AZ. Define a new subnet in AZ3, then update the Auto Scaling group to target all three new subnets.`, ko:`AZ1 서브넷에서 EC2 인스턴스를 종료합니다. 주소 공간의 절반을 사용하여 AZ1 서브넷을 삭제하고 다시 생성합니다. 이 새 서브넷을 사용하도록 Auto Scaling 그룹을 업데이트합니다. 두 번째 AZ에 대해 이를 반복합니다. AZ3에서 새 서브넷을 정의한 다음 세 개의 새 서브넷을 모두 대상으로 지정하도록 Auto Scaling 그룹을 업데이트합니다.` },
      { k:'C', en:`Create a new VPC with the same IPv4 address space and define three subnets, with one for each AZ. Update the existing Auto Scaling group to target the new subnets in the new VPC.`, ko:`동일한 IPv4 주소 공간으로 새 VPC를 생성하고 각 AZ마다 하나씩 3개의 서브넷을 정의합니다. 새 VPC의 새 서브넷을 대상으로 지정하도록 기존 Auto Scaling 그룹을 업데이트합니다.` },
      { k:'D', en:`Update the Auto Scaling group to use the AZ2 subnet only. Update the AZ1 subnet to have half the previous address space. Adjust the Auto Scaling group to also use the AZ1 subnet again. When the instances are healthy, adjust the Auto Scaling group to use the AZ1 subnet only. Update the current AZ2 subnet and assign the second half of the address space from the original AZ1 subnet. Create a new AZ3 subnet using half the original AZ2 subnet address space, then update the Auto Scaling group to target all three new subnets.`, ko:`AZ2 서브넷만 사용하도록 Auto Scaling 그룹을 업데이트합니다. 이전 주소 공간의 절반을 갖도록 AZ1 서브넷을 업데이트합니다. AZ1 서브넷도 다시 사용하도록 Auto Scaling 그룹을 조정합니다. 인스턴스가 정상이면 AZ1 서브넷만 사용하도록 Auto Scaling 그룹을 조정합니다. 현재 AZ2 서브넷을 업데이트하고 원래 AZ1 서브넷에서 주소 공간의 두 번째 절반을 할당합니다. 원래 AZ2 서브넷 주소 공간의 절반을 사용하여 새 AZ3 서브넷을 생성한 다음 세 개의 새 서브넷을 모두 대상으로 지정하도록 Auto Scaling 그룹을 업데이트합니다.` },
    ],
    answer: ["A"],
    vote: '85% A, 15% D',
    explain: `<p><span class="mark-ok">✅ A</span></p><p>답 - A
D가 가장 가깝지만 서브넷을 수정할 수 없으므로 잘못된 것입니다. 삭제하고 다시 만들어야 합니다.</p>`,
    wrong: `<p><span class="mark-no">❌ D</span> — D가 더 쉬우므로 서브넷을 삭제할 필요가 없습니다. https://docs.aws.amazon.com/vpc/latest/userguide/subnet-cidr-reservation.html</p>`,
    disc: [{ ans:'A', txt:'D: "AZ1 서브넷 업데이트" D에서는 불가능합니다. 서브넷을 삭제하고 다시 생성해야 하며 업데이트 옵션이 없습니다. B: 서비스 중단 C: 농담이에요.....' }, { ans:'A', txt:'D: "Update the AZ1 subnet" in D is not possible. you have to delete and recreate a subnet, there is no update option B: service intruption C: is a joke.....' }, { ans:'A', txt:'확실히 3분짜리 질문은 아니었습니다. 다행히 CIDR 예약을 혼합하지 않았습니다.' }, { ans:'A', txt:'Surely wasn\'t a 3 min ques. Thankfully they did not throw CIDR reservations into the mix' }, { ans:'D', txt:'D가 더 쉬우므로 서브넷을 삭제할 필요가 없습니다. https://docs.aws.amazon.com/vpc/latest/userguide/subnet-cidr-reservation.html' }]
  },
  {
    n: 294,
    en: `A company uses an organization in AWS Organizations to manage the company's AWS accounts. The company uses AWS CloudFormation to deploy all infrastructure. A finance team wants to build a chargeback model. The finance team asked each business unit to tag resources by using a predefined list of project values.<br/><br/>When the finance team used the AWS Cost and Usage Report in AWS Cost Explorer and filtered based on project, the team noticed noncompliant project values. The company wants to enforce the use of project tags for new resources.<br/><br/>Which solution will meet these requirements with the LEAST effort?`,
    ko: `회사는 AWS Organizations의 조직을 사용하여 회사의 AWS 계정을 관리합니다. 회사는 AWS CloudFormation을 사용하여 모든 인프라를 배포합니다. 재무팀에서 지불 거절 모델을 구축하려고 합니다. 재무팀은 각 사업부에게 사전 정의된 프로젝트 값 목록을 사용하여 리소스에 태그를 지정하도록 요청했습니다. <br/><br/>재무팀은 AWS Cost Explorer에서 AWS 비용 및 사용 보고서를 사용하고 프로젝트를 기준으로 필터링했을 때 규정을 준수하지 않는 프로젝트 값을 발견했습니다. 회사는 새 리소스에 대해 프로젝트 태그 사용을 시행하려고 합니다. <br/><br/>최소한의 노력으로 이러한 요구 사항을 충족할 수 있는 솔루션은 무엇입니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Create a tag policy that contains the allowed project tag values in the organization's management account. Create an SCP that denies the cloudformation:CreateStack API operation unless a project tag is added. Attach the SCP to each OU.`, ko:`조직의 마스터 계정에 허용된 프로젝트 태그 값을 포함하는 태그 정책을 생성합니다. 프로젝트 태그가 추가되지 않는 한 cloudformation:CreateStack API 작업을 거부하는 SCP를 생성합니다. SCP를 각 OU에 연결합니다.` },
      { k:'B', en:`Create a tag policy that contains the allowed project tag values in each OU. Create an SCP that denies the cloudformation:CreateStack API operation unless a project tag is added. Attach the SCP to each OU.`, ko:`각 OU에 허용되는 프로젝트 태그 값을 포함하는 태그 정책을 생성합니다. 프로젝트 태그가 추가되지 않는 한 cloudformation:CreateStack API 작업을 거부하는 SCP를 생성합니다. SCP를 각 OU에 연결합니다.` },
      { k:'C', en:`Create a tag policy that contains the allowed project tag values in the AWS management account. Create an IAM policy that denies the cloudformation:CreateStack API operation unless a project tag is added. Assign the policy to each user.`, ko:`AWS 마스터 계정에서 허용되는 프로젝트 태그 값을 포함하는 태그 정책을 생성합니다. 프로젝트 태그가 추가되지 않는 한 cloudformation:CreateStack API 작업을 거부하는 IAM 정책을 생성합니다. 각 사용자에게 정책을 할당합니다.` },
      { k:'D', en:`Use AWS Service Catalog to manage the CloudFormation stacks as products. Use a TagOptions library to control project tag values. Share the portfolio with all OUs that are in the organization.`, ko:`AWS Service Catalog를 사용하여 CloudFormation 스택을 제품으로 관리합니다. TagOptions 라이브러리를 사용하여 프로젝트 태그 값을 제어합니다. 조직에 있는 모든 OU와 포트폴리오를 공유합니다.` },
    ],
    answer: ["A"],
    vote: '100% A',
    explain: `<p><span class="mark-ok">✅ A</span></p><p>정답의 핵심은 A, B의 첫 번째 문장에 있습니다. OU는 '계정'이 아니고 정책이 적용되는 대상이므로 OU가 아닌 관리 계정에서 태그 정책을 생성할 수 있습니다. 태그 정책은 SCP와 동일하지 않습니다. 참조: https://aws.amazon.com/blogs/mt/implement-aws-resource-tagged-strategy-using-aws-tag-policies-and-service-control-policies-scps/</p>`,
    wrong: ``,
    disc: [{ ans:'A', txt:'A는 맞지만 옵션 A의 마지막 줄이 마음에 들지 않았습니다. "각 OU에 SCP를 연결하세요"라고 적혀 있습니다. SCP를 각 OU에 연결해야 하는 이유 RootOU에 연결하여 하위 OU에 상속할 수는 없나요?' }, { ans:'A', txt:'A is correct BUT I did NOT like the last line in option A. It says "Attach the SCP to each OU". Why should you attach SCP to each OU. Can\'t you just attach to RootOU so it gets inherited to child OUs' }, { ans:'A', txt:'A) 모든 조직 사용의 마스터 계정에서 정확합니다. SCP는 B보다 오버헤드가 적습니다. B) 각 OU에서 SCP를 생성하기 때문에 A보다 오버헤드가 많습니다. C) 모든 계정의 IAM이 오버헤드가 더 큽니다. D) 유효하지만 다른 옵션을 제한하지 않습니다. o 생성 CLI 또는 콘솔을 사용하여 태그 없이 나머지 서비스를 사용하면 A가 맞습니다.' }, { ans:'A', txt:'A) Is correct in the master account of all organization use SCP is less overhead than B B ) is more overhead than A because in each OU create SCP C ) IAM in all account is more overhead D) is valid but not restrict other options o create with CLI or console the rest service without tags Then A is correct' }, { ans:'A', txt:'A. 마스터 계정에서 태그 정책 생성' }]
  },
  {
    n: 295,
    en: `An application is deployed on Amazon EC2 instances that run in an Auto Scaling group. The Auto Scaling group configuration uses only one type of instance.<br/><br/>CPU and memory utilization metrics show that the instances are underutilized. A solutions architect needs to implement a solution to permanently reduce the EC2 cost and increase the utilization.<br/><br/>Which solution will meet these requirements with the LEAST number of configuration changes in the future?`,
    ko: `Auto Scaling 그룹에서 실행되는 Amazon EC2 인스턴스에 애플리케이션이 배포됩니다. Auto Scaling 그룹 구성은 한 가지 유형의 인스턴스만 사용합니다. <br/><br/>CPU 및 메모리 사용률 지표는 인스턴스의 사용률이 낮은 것으로 나타났습니다. 솔루션 아키텍트는 EC2 비용을 영구적으로 줄이고 활용도를 높이는 솔루션을 구현해야 합니다. <br/><br/>앞으로 최소한의 구성 변경으로 이러한 요구 사항을 충족할 솔루션은 무엇입니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`List instance types that have properties that are similar to the properties that the current instances have. Modify the Auto Scaling group's launch template configuration to use multiple instance types from the list.`, ko:`현재 인스턴스의 속성과 유사한 속성을 가진 인스턴스 유형을 나열합니다. 목록에 있는 여러 인스턴스 유형을 사용하도록 Auto Scaling 그룹의 시작 템플릿 구성을 수정합니다.` },
      { k:'B', en:`Use the information about the application's CPU and memory utilization to select an instance type that matches the requirements. Modify the Auto Scaling group's configuration by adding the new instance type. Remove the current instance type from the configuration.`, ko:`애플리케이션의 CPU 및 메모리 사용률에 대한 정보를 사용하여 요구 사항에 맞는 인스턴스 유형을 선택합니다. 새 인스턴스 유형을 추가하여 Auto Scaling 그룹의 구성을 수정합니다. 구성에서 현재 인스턴스 유형을 제거합니다.` },
      { k:'C', en:`Use the information about the application's CPU and memory utilization to specify CPU and memory requirements in a new revision of the Auto Scaling group's launch template. Remove the current instance type from the configuration.`, ko:`애플리케이션의 CPU 및 메모리 사용률에 대한 정보를 사용하여 Auto Scaling 그룹 시작 템플릿의 새 개정판에서 CPU 및 메모리 요구 사항을 지정합니다. 구성에서 현재 인스턴스 유형을 제거합니다.` },
      { k:'D', en:`Create a script that selects the appropriate instance types from the AWS Price List Bulk API. Use the selected instance types to create a new revision of the Auto Scaling group's launch template.`, ko:`AWS Price List Bulk API에서 적절한 인스턴스 유형을 선택하는 스크립트를 생성합니다. 선택한 인스턴스 유형을 사용하여 Auto Scaling 그룹 시작 템플릿의 새 개정판을 생성합니다.` },
    ],
    answer: ["C"],
    vote: '68% C, 32% B',
    explain: `<p><span class="mark-ok">✅ C</span></p><p>C입니다. ASG가 아닌 시작 템플릿에서 인스턴스 유형/크기를 변경합니다. ASG는 인스턴스 유형이 아닌 최소/최대 크기를 변경할 수 있습니다.</p>`,
    wrong: `<p><span class="mark-no">❌ B</span> — 시작 템플릿에서는 하나의 인스턴스 유형만 선택할 수 있습니다. 그러나 ASG 구성에서 시작 템플릿을 재정의하고 여러 인스턴스 유형을 지정할 수 있습니다.</p>`,
    disc: [{ ans:'C', txt:'C입니다. ASG가 아닌 시작 템플릿에서 인스턴스 유형/크기를 변경합니다. ASG는 인스턴스 유형이 아닌 최소/최대 크기를 변경할 수 있습니다.' }, { ans:'C', txt:'It\'s C. You change the instance type/size in the launch template not the ASG. ASG can change the min/max size, not instance type.' }, { ans:'B', txt:'시작 템플릿에서는 하나의 인스턴스 유형만 선택할 수 있습니다. 그러나 ASG 구성에서 시작 템플릿을 재정의하고 여러 인스턴스 유형을 지정할 수 있습니다.' }, { ans:'B', txt:'In the launch template, you can only select one instance type. You can however override the Launch Template in the ASG configuration and specify multiple instance types.' }, { ans:'C', txt:'나에게는 C' }]
  },
  {
    n: 296,
    en: `A company implements a containerized application by using Amazon Elastic Container Service (Amazon ECS) and Amazon API Gateway The application data is stored in Amazon Aurora databases and Amazon DynamoDB databases. The company automates infrastructure provisioning by using AWS CloudFormation. The company automates application deployment by using AWS CodePipeline.<br/><br/>A solutions architect needs to implement a disaster recovery (DR) strategy that meets an RPO of 2 hours and an RTO of 4 hours.<br/><br/>Which solution will meet these requirements MOST cost-effectively?`,
    ko: `회사는 Amazon Elastic Container Service(Amazon ECS) 및 Amazon API Gateway를 사용하여 컨테이너화된 애플리케이션을 구현합니다. 애플리케이션 데이터는 Amazon Aurora 데이터베이스 및 Amazon DynamoDB 데이터베이스에 저장됩니다. 회사는 AWS CloudFormation을 사용하여 인프라 프로비저닝을 자동화합니다. 회사는 AWS CodePipeline을 사용하여 애플리케이션 배포를 자동화합니다. <br/><br/>솔루션 아키텍트는 2시간의 RPO와 4시간의 RTO를 충족하는 재해 복구(DR) 전략을 구현해야 합니다. <br/><br/>이러한 요구 사항을 가장 비용 효율적으로 충족하는 솔루션은 무엇입니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Set up an Aurora global database and DynamoDB global tables to replicate the databases to a secondary AWS Region. In the primary Region and in the secondary Region, configure an API Gateway API with a Regional endpoint. Implement Amazon CloudFront with origin failover to route traffic to the secondary Region during a DR scenario.`, ko:`데이터베이스를 보조 AWS 리전에 복제하도록 Aurora 글로벌 데이터베이스와 DynamoDB 글로벌 테이블을 설정합니다. 기본 리전과 보조 리전에서 리전 엔드포인트를 사용하여 API Gateway API를 구성합니다. DR 시나리오 중에 트래픽을 보조 리전으로 라우팅하기 위해 오리진 장애 조치가 포함된 Amazon CloudFront를 구현합니다.` },
      { k:'B', en:`Use AWS Database Migration Service (AWS DMS), Amazon EventBridge, and AWS Lambda to replicate the Aurora databases to a secondary AWS Region. Use DynamoDB Streams, EventBridge. and Lambda to replicate the DynamoDB databases to the secondary Region. In the primary Region and in the secondary Region, configure an API Gateway API with a Regional endpoint. Implement Amazon Route 53 failover routing to switch traffic from the primary Region to the secondary Region.`, ko:`AWS DMS(AWS Database Migration Service), Amazon EventBridge 및 AWS Lambda를 사용하여 Aurora 데이터베이스를 보조 AWS 지역에 복제합니다. DynamoDB 스트림, EventBridge를 사용합니다. DynamoDB 데이터베이스를 보조 리전에 복제하는 Lambda. 기본 리전과 보조 리전에서 리전 엔드포인트를 사용하여 API Gateway API를 구성합니다. Amazon Route 53 장애 조치 라우팅을 구현하여 기본 지역에서 보조 지역으로 트래픽을 전환합니다.` },
      { k:'C', en:`Use AWS Backup to create backups of the Aurora databases and the DynamoDB databases in a secondary AWS Region. In the primary Region and in the secondary Region, configure an API Gateway API with a Regional endpoint. Implement Amazon Route 53 failover routing to switch traffic from the primary Region to the secondary Region.`, ko:`AWS 백업을 사용하여 보조 AWS 리전에 Aurora 데이터베이스 및 DynamoDB 데이터베이스의 백업을 생성하십시오. 기본 리전과 보조 리전에서 리전 엔드포인트를 사용하여 API Gateway API를 구성합니다. Amazon Route 53 장애 조치 라우팅을 구현하여 기본 지역에서 보조 지역으로 트래픽을 전환합니다.` },
      { k:'D', en:`Set up an Aurora global database and DynamoDB global tables to replicate the databases to a secondary AWS Region. In the primary Region and in the secondary Region, configure an API Gateway API with a Regional endpoint. Implement Amazon Route 53 failover routing to switch traffic from the primary Region to the secondary Region.`, ko:`데이터베이스를 보조 AWS 리전에 복제하도록 Aurora 글로벌 데이터베이스와 DynamoDB 글로벌 테이블을 설정합니다. 기본 리전과 보조 리전에서 리전 엔드포인트를 사용하여 API Gateway API를 구성합니다. Amazon Route 53 장애 조치 라우팅을 구현하여 기본 지역에서 보조 지역으로 트래픽을 전환합니다.` },
    ],
    answer: ["C"],
    vote: '58% C, 37% D, 5% B',
    explain: `<p><span class="mark-ok">✅ C</span></p><p>답변: C 이상한 질문입니다. 때때로 나는 BEST 답변이 없으며 사람들을 혼란스럽게 하기 위해 만들어진 것이라고 생각합니다. 어쨌든, 비용과 언급된 RPO 및 RTO를 생각하면 여전히 C를 선택할 것입니다(더 길면 질문 중에서 선택하는 것이 더 쉬울 것입니다).</p>`,
    wrong: `<p><span class="mark-no">❌ B</span> — Github Copilot 답변: 귀하가 제안한 솔루션은 재해 복구(DR) 전략을 구현하기 위한 좋은 접근 방식입니다. 작동 방식은 다음과 같습니다. 1. **AWS Database Migration Service(DMS)**: 이 서비스는 기본 지역의 Amazon Aurora 데이터베이스에서 보조 지역으로 데이터를 복제하는 데 사용할 수 있습니다. 이렇게</p><p><span class="mark-no">❌ D</span> — 우리는 DB의 크기를 전혀 모르기 때문에 백업을 사용하여 4시간의 RTO에 도달할 수 있다고 가정할 수 없습니다. D는 A, B, D 중에서 가장 저렴한 솔루션입니다.</p>`,
    disc: [{ ans:'C', txt:'답변: C 이상한 질문입니다. 때때로 나는 BEST 답변이 없으며 사람들을 혼란스럽게 하기 위해 만들어진 것이라고 생각합니다. 어쨌든, 비용과 언급된 RPO 및 RTO를 생각하면 여전히 C를 선택할 것입니다(더 길면 질문 중에서 선택하는 것이 더 쉬울 것입니다).' }, { ans:'C', txt:'Answer: C Weird question. Sometimes I think there is no BEST answer and that they were created just to confuse people. Anyway, thinking on cost and the mentioned RPO and RTO, I would still go with C (if they were longer, it would be easier to choose among the questions).' }, { ans:'C', txt:'나에게는 C' }, { ans:'C', txt:'C for me' }, { ans:'D', txt:'대답은 D입니다. 이 솔루션은 Amazon Aurora 글로벌 데이터베이스와 DynamoDB 글로벌 테이블을 사용하여 데이터베이스를 보조 AWS 리전에 복제하기 때문에 가장 비용 효율적입니다. 이 복제는 자동으로 실시간으로 수행되므로 RPO는 0초입니다. 보조 지역이 이미 구성되어 재해 발생 시 인계받을 준비가 되어 있으므로 RTO도 낮습니다.' }]
  },
  {
    n: 297,
    en: `A company has a complex web application that leverages Amazon CloudFront for global scalability and performance. Over time, users report that the web application is slowing down.<br/><br/>The company's operations team reports that the CloudFront cache hit ratio has been dropping steadily. The cache metrics report indicates that query strings on some URLs are inconsistently ordered and are specified sometimes in mixed-case letters and sometimes in lowercase letters.<br/><br/>Which set of actions should the solutions architect take to increase the cache hit ratio as quickly as possible?`,
    ko: `한 회사에는 글로벌 확장성과 성능을 위해 Amazon CloudFront를 활용하는 복잡한 웹 애플리케이션이 있습니다. 시간이 지나면서 사용자들은 웹 애플리케이션 속도가 느려지고 있다고 보고합니다. <br/><br/>회사 운영 팀은 CloudFront 캐시 적중률이 꾸준히 감소하고 있다고 보고합니다. 캐시 지표 보고서는 일부 URL의 쿼리 문자열이 일관되지 않게 정렬되어 있으며 때로는 대소문자가 혼합되어 지정되거나 소문자로 지정된다는 것을 나타냅니다. <br/><br/>캐시 적중률을 최대한 빨리 높이기 위해 솔루션 설계자는 어떤 조치를 취해야 합니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Deploy a Lambda@Edge function to sort parameters by name and force them to be lowercase. Select the CloudFront viewer request trigger to invoke the function.`, ko:`매개변수를 이름별로 정렬하고 소문자로 강제 지정하려면 Lambda@Edge 함수를 배포하세요. CloudFront 뷰어 요청 트리거를 선택하여 함수를 호출합니다.` },
      { k:'B', en:`Update the CloudFront distribution to disable caching based on query string parameters.`, ko:`쿼리 문자열 매개변수를 기반으로 캐싱을 비활성화하도록 CloudFront 배포를 업데이트합니다.` },
      { k:'C', en:`Deploy a reverse proxy after the load balancer to post-process the emitted URLs in the application to force the URL strings to be lowercase.`, ko:`로드 밸런서 뒤에 역방향 프록시를 배포하여 애플리케이션에서 내보낸 URL을 사후 처리하여 URL 문자열을 소문자로 만듭니다.` },
      { k:'D', en:`Update the CloudFront distribution to specify casing-insensitive query string processing.`, ko:`대소문자를 구분하지 않는 쿼리 문자열 처리를 지정하도록 CloudFront 배포를 업데이트합니다.` },
    ],
    answer: ["A"],
    vote: '89% A, 11% C',
    explain: `<p><span class="mark-ok">✅ A</span></p><p>AD가 지원된다면 좋을 것입니다.</p>`,
    wrong: `<p><span class="mark-no">❌ C</span> — 세상에, 이제 내 CDN을 통과하는 모든 단일 GET 요청에 대해 Lambda를 호출하고 비용을 지불해야 합니까? 아니, 젠장. D가 지원되지 않으면 ciao bella s/Cloudfront/Cloudflare/g를 입력하고 mod_substitute를 실행하는 Apache에 인사하세요. 정말 감사합니다.</p>`,
    disc: [{ ans:'C', txt:'세상에, 이제 내 CDN을 통과하는 모든 단일 GET 요청에 대해 Lambda를 호출하고 비용을 지불해야 합니까? 아니, 젠장. D가 지원되지 않으면 ciao bella s/Cloudfront/Cloudflare/g를 입력하고 mod_substitute를 실행하는 Apache에 인사하세요. 정말 감사합니다.' }, { ans:'C', txt:'OMG so now I have to invoke and pay for a Lambda for every single GET request that traverses my CDN? No, F*** that. If D isn\'t supported then ciao bella s/Cloudfront/Cloudflare/g and say hello to Apache running mod_substitute thank you very much.' }, { ans:'A', txt:'A - https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-examples.html#lambda-examples-normalize-query-string-parameters' }, { ans:'A', txt:'A, 이 버전 1에서도 동일한 질문이 있습니다 https://www.examtopics.com/discussions/amazon/view/27789-exam-aws-certified-solutions-architect-professional-topic-1/' }, { ans:'A', txt:'A , same questions this version 1 https://www.examtopics.com/discussions/amazon/view/27789-exam-aws-certified-solutions-architect-professional-topic-1/' }]
  },
  {
    n: 298,
    en: `A company runs an ecommerce application in a single AWS Region. The application uses a five-node Amazon Aurora MySQL DB cluster to store information about customers and their recent orders. The DB cluster experiences a large number of write transactions throughout the day.<br/><br/>The company needs to replicate the data in the Aurora database to another Region to meet disaster recovery requirements. The company has an RPO of 1 hour.<br/><br/>Which solution will meet these requirements with the LOWEST cost?`,
    ko: `회사는 단일 AWS 리전에서 전자상거래 애플리케이션을 실행합니다. 이 애플리케이션은 5노드 Amazon Aurora MySQL DB 클러스터를 사용하여 고객 및 고객의 최근 주문에 대한 정보를 저장합니다. DB 클러스터에서는 하루 종일 많은 수의 쓰기 트랜잭션이 발생합니다. <br/><br/>회사는 재해 복구 요구 사항을 충족하기 위해 Aurora 데이터베이스의 데이터를 다른 지역으로 복제해야 합니다. 회사의 RPO는 1시간입니다. <br/><br/>가장 저렴한 비용으로 이러한 요구 사항을 충족할 수 있는 솔루션은 무엇입니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Modify the Aurora database to be an Aurora global database. Create a second Aurora database in another Region.`, ko:`Aurora 데이터베이스를 Aurora 글로벌 데이터베이스로 수정하십시오. 다른 리전에 두 번째 Aurora 데이터베이스를 생성합니다.` },
      { k:'B', en:`Enable the Backtrack feature for the Aurora database. Create an AWS Lambda function that runs daily to copy the snapshots of the database to a backup Region.`, ko:`Aurora 데이터베이스에 대한 역추적 기능을 활성화합니다. 데이터베이스의 스냅샷을 백업 리전에 복사하기 위해 매일 실행되는 AWS Lambda 함수를 생성합니다.` },
      { k:'C', en:`Use AWS Database Migration Service (AWS DMS). Create a DMS change data capture (CDC) task that replicates the ongoing changes from the Aurora database to an Amazon S3 bucket in another Region.`, ko:`AWS Database Migration Service(AWS DMS)를 사용한다. Aurora 데이터베이스에서 다른 리전의 Amazon S3 버킷으로 진행 중인 변경 사항을 복제하는 DMS 변경 데이터 캡처(CDC) 작업을 생성합니다.` },
      { k:'D', en:`Turn off automated Aurora backups. Configure Aurora backups with a backup frequency of 1 hour. Specify another Region as the destination Region. Select the Aurora database as the resource assignment.`, ko:`자동화된 Aurora 백업을 끄십시오. 1시간의 백업 빈도로 Aurora 백업을 구성하십시오. 다른 지역을 대상 지역으로 지정하세요. 리소스 할당으로 Aurora 데이터베이스를 선택합니다.` },
    ],
    answer: ["C"],
    vote: '69% C, 25% A, 7% D',
    explain: `<p><span class="mark-ok">✅ C</span></p><p>시험에 행운을 빕니다. 나는 질문을 읽는 데만 3시간이 걸리기 때문에 실패할 것이라는 것을 알고 있습니다. >:(</p>`,
    wrong: `<p><span class="mark-no">❌ A</span> — 마지막 2개의 질문을 읽고 나서 머리가 아프고 45분이 지나도 여전히 혼란스럽습니다. 핵심 요구 사항, RPO <1시간, DR 요구 사항 충족, 최저 비용을 살펴보고 있습니다. 아래 링크와 모든 의견을 읽은 후 옵션 A가 질문의 모든 요구 사항을 충족한다고 생각합니다. https://docs.aws.amazon.com/AmazonRDS/latest/Auro</p><p><span class="mark-no">❌ D</span> — 옵션 D는 1시간 빈도의 Aurora 백업과 지역 간 복제를 활용하여 원하는 RPO로 재해 복구 요구 사항을 충족함으로써 가장 비용 효율적인 솔루션을 제공합니다.</p>`,
    disc: [{ ans:'C', txt:'시험에 행운을 빕니다. 나는 질문을 읽는 데만 3시간이 걸리기 때문에 실패할 것이라는 것을 알고 있습니다. >:(' }, { ans:'C', txt:'Good luck for the exams. I know I\'m gonna fail coz it takes me 3 hours just to read the questions. >:(' }, { ans:'D', txt:'옵션 D는 1시간 빈도의 Aurora 백업과 지역 간 복제를 활용하여 원하는 RPO로 재해 복구 요구 사항을 충족함으로써 가장 비용 효율적인 솔루션을 제공합니다.' }, { ans:'D', txt:'option D provides the most cost-effective solution by leveraging Aurora backups with a 1-hour frequency and cross-Region replication to meet the disaster recovery requirements with the desired RPO.' }, { ans:'A', txt:'마지막 2개의 질문을 읽고 나서 머리가 아프고 45분이 지나도 여전히 혼란스럽습니다. 핵심 요구 사항, RPO <1시간, DR 요구 사항 충족, 최저 비용을 살펴보고 있습니다. 아래 링크와 모든 의견을 읽은 후 옵션 A가 질문의 모든 요구 사항을 충족한다고 생각합니다. https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-global-database.html' }]
  },
  {
    n: 299,
    en: `A company's solutions architect is evaluating an AWS workload that was deployed several years ago. The application tier is stateless and runs on a single large Amazon EC2 instance that was launched from an AMI. The application stores data in a MySQL database that runs on a single EC2 instance.<br/><br/>The CPU utilization on the application server EC2 instance often reaches 100% and causes the application to stop responding. The company manually installs patches on the instances. Patching has caused downtime in the past. The company needs to make the application highly available.<br/><br/>Which solution will meet these requirements with the LEAST development me?`,
    ko: `한 회사의 솔루션 아키텍트가 몇 년 전에 배포된 AWS 워크로드를 평가하고 있습니다. 애플리케이션 계층은 상태 비저장이며 AMI에서 시작된 단일 대규모 Amazon EC2 인스턴스에서 실행됩니다. 애플리케이션은 단일 EC2 인스턴스에서 실행되는 MySQL 데이터베이스에 데이터를 저장합니다. <br/><br/>애플리케이션 서버 EC2 인스턴스의 CPU 사용률이 100%에 도달하는 경우가 많아 애플리케이션이 응답을 중지합니다. 회사는 인스턴스에 패치를 수동으로 설치합니다. 과거에는 패치 적용으로 인해 다운타임이 발생했습니다. 회사는 애플리케이션의 가용성을 높여야 합니다. <br/><br/>최소한의 개발로 이러한 요구 사항을 충족할 수 있는 솔루션은 무엇입니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Move the application tier to AWS Lambda functions in the existing VPC. Create an Application Load Balancer to distribute traffic across the Lambda functions. Use Amazon GuardDuty to scan the Lambda functions. Migrate the database to Amazon DocumentDB (with MongoDB compatibility.`, ko:`애플리케이션 계층을 기존 VPC의 AWS Lambda 함수로 이동합니다. Lambda 함수 전체에 트래픽을 분산시키기 위해 Application Load Balancer를 생성합니다. Amazon GuardDuty를 사용하여 Lambda 함수를 스캔합니다. 데이터베이스를 Amazon DocumentDB로 마이그레이션합니다(MongoDB와 호환됩니다.` },
      { k:'B', en:`Change the EC2 instance type to a smaller Graviton powered instance type. Use the existing AMI to create a launch template for an Auto Scaling group. Create an Application Load Balancer to distribute traffic across the instances in the Auto Scaling group. Set the Auto Scaling group to scale based on CPU utilization. Migrate the database to Amazon DynamoDB.`, ko:`EC2 인스턴스 유형을 더 작은 Graviton 기반 인스턴스 유형으로 변경합니다. 기존 AMI를 사용하여 Auto Scaling 그룹에 대한 시작 템플릿을 생성합니다. Auto Scaling 그룹의 인스턴스 전체에 트래픽을 분산시키기 위해 Application Load Balancer를 생성합니다. CPU 사용률에 따라 조정되도록 Auto Scaling 그룹을 설정합니다. 데이터베이스를 Amazon DynamoDB로 마이그레이션합니다.` },
      { k:'C', en:`Move the application tier to containers by using Docker. Run the containers on Amazon Elastic Container Service (Amazon ECS) with EC2 instances. Create an Application Load Balancer to distribute traffic across the ECS cluster. Configure the ECS cluster to scale based on CPU utilization. Migrate the database to Amazon Neptune.`, ko:`Docker를 사용하여 애플리케이션 계층을 컨테이너로 이동합니다. EC2 인스턴스를 사용하여 Amazon Elastic Container Service(Amazon ECS)에서 컨테이너를 실행합니다. ECS 클러스터 전체에 트래픽을 분산시키기 위해 Application Load Balancer를 생성합니다. CPU 사용률에 따라 확장되도록 ECS 클러스터를 구성합니다. 데이터베이스를 Amazon Neptune으로 마이그레이션합니다.` },
      { k:'D', en:`Create a now AMI that is configured with AWS Systems Manager Agent (SSM Agent). Use the new AMI to create a launch template for an Auto Scaling group. Use smaller instances in the Auto Scaling group. Create an Application Load Balancer to distribute traffic across the instances in the Auto Scaling group. Set the Auto Scaling group to scale based on CPU utilization. Migrate the database to Amazon Aurora MySQL.`, ko:`AWS 시스템 관리자 에이전트(SSM 에이전트)로 구성된 Now AMI를 생성합니다. 새 AMI를 사용하여 Auto Scaling 그룹에 대한 시작 템플릿을 생성합니다. Auto Scaling 그룹에서 더 작은 인스턴스를 사용합니다. Auto Scaling 그룹의 인스턴스 전체에 트래픽을 분산시키기 위해 Application Load Balancer를 생성합니다. CPU 사용률에 따라 조정되도록 Auto Scaling 그룹을 설정합니다. 데이터베이스를 Amazon Aurora MySQL로 마이그레이션합니다.` },
    ],
    answer: ["D"],
    vote: '100% D',
    explain: `<p><span class="mark-ok">✅ D</span></p><p>개발 노력이 필요하지 않으므로 nonSQL이나 Neptune으로 마이그레이션할 필요가 없습니다. 람다를 기반으로 재작업할 필요가 없습니다.</p>`,
    wrong: ``,
    disc: [{ ans:'D', txt:'개발 노력이 필요하지 않으므로 nonSQL이나 Neptune으로 마이그레이션할 필요가 없습니다. 람다를 기반으로 재작업할 필요가 없습니다.' }, { ans:'D', txt:'A: 작업이 Lambda의 15분 제한 내에 완료된다는 보장은 없습니다. B, C: MySQL을 DynamoDB 또는 Neptune으로 마이그레이션하시겠습니까? 요구 사항에 명시되지 않는 한 다른 유형의 데이터베이스로 마이그레이션할 필요가 없습니다. D: 클래식 아키텍처: ALB + ASG + EC2, 비용 최적화를 위해 CPU 사용률을 기반으로 확장됩니다. ASG의 시작 템플릿용 AMI를 생성하기 위해 SSM을 사용하는 것이 정확합니다. Aurora MySQL은 현재 MySQL 데이터베이스와 호환됩니다.' }, { ans:'D', txt:'A - 이전 플랫폼을 lamdba 기능에 적용하는 데 약간의 시간이 소요됩니다. + 애플리케이션은 mongodb가 아닌 mysql에서 작동합니다. B - 성능 문제가 있을 때 더 작은 인스턴스를 원하지 않습니다. C - 전체 애플리케이션을 다시 적용해야 합니다. 이론적으로 유지 관리가 덜 필요하더라도 가장 유연한 가상화 플랫폼이 아닌 ECS의 컨테이너화 D - 이러한 애플리케이션을 마이그레이션하는 가장 고전적인 방법: 새 플랫폼을 생성하고 ASG를 사용하여 애플리케이션의 확장성을 높이고 마이그레이션 과부하된 EC2 인스턴스에서 관리형 서비스로 MySQL 서버를 이동합니다.' }, { ans:'D', txt:'MySQL에서 Amazon Aurora MySQL까지 개발 시간을 최소화하세요.' }, { ans:'D', txt:'내 생각엔 D' }]
  },
  {
    n: 300,
    en: `A company is planning to migrate several applications to AWS. The company does not have a good understanding of its entire application estate. The estate consists of a mixture of physical machines and VMs.<br/><br/>One application that the company will migrate has many dependencies that are sensitive to latency. The company is unsure what all the dependencies are. However the company knows that the low-latency communications use a custom IP-based protocol that runs on port 1000. The company wants to migrate the application and these dependencies together to move all the low-latency interfaces to AWS at the same time.<br/><br/>The company has installed the AWS Application Discovery Agent and has been collecting data for several months.<br/><br/>What should the company do to identify the dependencies that need to be migrated in the same phase as the application?`,
    ko: `한 회사에서 여러 애플리케이션을 AWS로 마이그레이션할 계획입니다. 회사는 전체 애플리케이션 자산을 제대로 이해하지 못하고 있습니다. 자산은 물리적 머신과 VM의 혼합으로 구성됩니다. <br/><br/>회사가 마이그레이션할 한 애플리케이션에는 대기 시간에 민감한 종속성이 많이 있습니다. 회사는 모든 종속성이 무엇인지 확신하지 못합니다. 그러나 회사는 지연 시간이 짧은 통신이 포트 1000에서 실행되는 사용자 지정 IP 기반 프로토콜을 사용한다는 것을 알고 있습니다. 회사는 애플리케이션과 이러한 종속성을 함께 마이그레이션하여 지연 시간이 짧은 모든 인터페이스를 동시에 AWS로 이동하려고 합니다. <br/><br/>회사는 AWS Application Discovery Agent를 설치하고 몇 달 동안 데이터를 수집해 왔습니다. <br/><br/>애플리케이션과 동일한 단계에서 마이그레이션해야 하는 종속성을 식별하려면 회사는 무엇을 해야 합니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Use AWS Migration Hub and select the servers that host the application. Visualize the network graph to find servers that interact with the application. Turn on data exploration in Amazon Athena. Query the data that is transferred between the servers to identify the servers that communicate on port 1000. Return to Migration Hub. Create a move group that is based on the findings from the Athena queries.`, ko:`AWS Migration Hub를 사용하고 애플리케이션을 호스팅하는 서버를 선택하십시오. 네트워크 그래프를 시각화하여 애플리케이션과 상호 작용하는 서버를 찾으세요. Amazon Athena에서 데이터 탐색을 활성화합니다. 서버 간에 전송되는 데이터를 쿼리하여 포트 1000에서 통신하는 서버를 식별합니다. Migration Hub로 돌아갑니다. Athena 쿼리 결과를 기반으로 이동 그룹을 만듭니다.` },
      { k:'B', en:`Use AWS Application Migration Service and select the servers that host the application. Visualize the network graph to find servers that interact with the application. Configure Application Migration Service to launch test instances for all the servers that interact with the application. Perform acceptance tests on the test instances. If no issues are identified, create a move group that is based on the tested servers.`, ko:`AWS Application Migration Service를 사용하고 애플리케이션을 호스팅하는 서버를 선택합니다. 네트워크 그래프를 시각화하여 애플리케이션과 상호 작용하는 서버를 찾으세요. 애플리케이션과 상호 작용하는 모든 서버에 대해 테스트 인스턴스를 시작하도록 Application Migration Service를 구성합니다. 테스트 인스턴스에 대한 승인 테스트를 수행합니다. 문제가 식별되지 않으면 테스트된 서버를 기반으로 이동 그룹을 만듭니다.` },
      { k:'C', en:`Use AWS Migration Hub and select the servers that host the application. Turn on data exploration in Network Access Analyzer. Use the Network Access Analyzer console to select the servers that host the application. Select a Network Access Scope of port 1000 and note the matching servers. Return to Migration Hub. Create a move group that is based on the findings from Network Access Analyzer.`, ko:`AWS Migration Hub를 사용하고 애플리케이션을 호스팅하는 서버를 선택합니다. 네트워크 액세스 분석기에서 데이터 탐색을 활성화합니다. 네트워크 액세스 분석기 콘솔을 사용하여 애플리케이션을 호스팅하는 서버를 선택합니다. 포트 1000의 네트워크 액세스 범위를 선택하고 일치하는 서버를 기록해 둡니다. 마이그레이션 허브로 돌아갑니다. Network Access Analyser의 결과를 기반으로 이동 그룹을 만듭니다.` },
      { k:'D', en:`Use AWS Migration Hub and select the servers that host the application. Push the Amazon CloudWalch agent to the identified servers by using the AWS Application Discovery Agent. Export the CloudWatch logs that the agents collect to Amazon S3. Use Amazon Athena to query the logs to find servers that communicate on port 1000. Return to Migration Hub Create a move group that is based on the findings from the Athena queries.`, ko:`AWS Migration Hub를 사용하고 애플리케이션을 호스팅하는 서버를 선택합니다. AWS Application Discovery Agent를 사용하여 Amazon CloudWalch 에이전트를 식별된 서버로 푸시합니다. 에이전트가 수집하는 CloudWatch 로그를 Amazon S3로 내보냅니다. Amazon Athena를 사용하여 로그를 쿼리하여 포트 1000에서 통신하는 서버를 찾습니다. Migration Hub로 돌아가기 Athena 쿼리 결과를 기반으로 이동 그룹을 생성합니다.` },
    ],
    answer: ["A"],
    vote: '95% A, 5% C',
    explain: `<p><span class="mark-ok">✅ A</span></p><p>대답 A. 네트워크 액세스 분석기는 온프레미스가 아닌 aws 서비스의 유효한 네트워크 사용을 위한 것입니다. 마이그레이션 허브에는 네트워크 시각화 기능이 있으며 Athena는 데이터를 쿼리하는 데 사용할 수 있습니다 https://aws.amazon.com/blogs/mt/using-aws-migration -hub-network-visualization-to-overcome-application-and-server-dependent-challenges/ https://aws.amazon.com/about-aws/whats-new/2020/11/aws-migration-hub-includes -네트워크 시각화/</p>`,
    wrong: `<p><span class="mark-no">❌ C</span> — c와 함께 작동해야 함</p>`,
    disc: [{ ans:'A', txt:'대답 A. 네트워크 액세스 분석기는 온프레미스가 아닌 aws 서비스의 유효한 네트워크 사용을 위한 것입니다. 마이그레이션 허브에는 네트워크 시각화 기능이 있으며 Athena는 데이터를 쿼리하는 데 사용할 수 있습니다 https://aws.amazon.com/blogs/mt/using-aws-migration -hub-network-visualization-to-overcome-application-and-server-dependent-challenges/ https://aws.amazon.com/about-aws/whats-new/2020/11/aws-migration-hub-includes -네트워크 시각화/' }, { ans:'A', txt:'Answer A . Network access analyzer is to valid network usage OF aws services and not on-prem Migration hub has feature for network visualization and Athena can be used to query data https://aws.amazon.com/blogs/mt/using-aws-migration-hub-network-visualization-to-overcome-application-and-server-dependency-challenges/ https://aws.amazon.com/about-aws/whats-new/2020/11/aws-migration-hub-includes-n...' }, { ans:'A', txt:'아키텍처 패턴은 데이터 탐색을 위한 Discovery Service + Migration Hub + Athena입니다. https://docs.aws.amazon.com/application-discovery/latest/userguide/explore-data.html A: 괜찮아 보입니다. B: AWS Application Migration Service는 다음과 같습니다. 리프트 앤 시프트용, 종속성 매핑용 아님 C: 온프레미스용이 아닌 AWS 리소스 전용 네트워크 액세스 분석기 D: CloudWatch 사용 사례 아님.' }, { ans:'A', txt:'Architecture pattern is Discovery Service + Migration Hub + Athena for data exploration: https://docs.aws.amazon.com/application-discovery/latest/userguide/explore-data.html A: looks fine B: AWS Application Migration Service is for lift and shift, not for dependency mapping C: Network Access Analyzer only for AWS resource, not for on prem D: not the use case of CloudWatch.' }, { ans:'A', txt:'참조: https://docs.aws.amazon.com/migrationhub/latest/ug/network-diagram.html 및 https://aws.amazon.com/about-aws/whats-new/2020/11/aws- 마이그레이션-허브-포함-네트워크-시각화/' }]
  }
];
