window.QS_SET24 = [
  {
    n: 231,
    en: `A company has an on-premises Microsoft SQL Server database that writes a nightly 200 GB export to a local drive. The company wants to move the backups to more robust cloud storage on Amazon S3. The company has set up a 10 Gbps AWS Direct Connect connection between the on-premises data center and AWS.<br/><br/>Which solution meets these requirements MOST cost-effectively?`,
    ko: `회사에는 야간에 로컬 드라이브에 200GB 내보내기를 쓰는 온프레미스 Microsoft SQL Server 데이터베이스가 있습니다. 회사는 백업을 Amazon S3의 더욱 강력한 클라우드 스토리지로 옮기기를 원합니다. 회사는 온프레미스 데이터 센터와 AWS 간에 10Gbps AWS Direct Connect 연결을 설정했습니다. <br/><br/>이러한 요구 사항을 가장 비용 효율적으로 충족하는 솔루션은 무엇입니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Create a new S3 bucket. Deploy an AWS Storage Gateway file gateway within the VPC that is connected to the Direct Connect connection. Create a new SMB file share. Write nightly database exports to the new SMB file share.`, ko:`새 S3 버킷을 생성합니다. Direct Connect 연결에 연결된 VPC 내에 AWS Storage Gateway 파일 게이트웨이를 배포합니다. 새 SMB 파일 공유를 만듭니다. 야간 데이터베이스 내보내기를 새 SMB 파일 공유에 기록합니다.` },
      { k:'B', en:`Create an Amazon FSx for Windows File Server Single-AZ file system within the VPC that is connected to the Direct Connect connection. Create a new SMB file share. Write nightly database exports to an SMB file share on the Amazon FSx file system. Enable nightly backups.`, ko:`Direct Connect 연결에 연결된 VPC 내에 Windows 파일 서버 단일 AZ 파일 시스템용 Amazon FSx를 생성합니다. 새 SMB 파일 공유를 만듭니다. Amazon FSx 파일 시스템의 SMB 파일 공유에 야간 데이터베이스 내보내기를 기록합니다. 야간 백업을 활성화합니다.` },
      { k:'C', en:`Create an Amazon FSx for Windows File Server Multi-AZ file system within the VPC that is connected to the Direct Connect connection. Create a new SMB file share. Write nightly database exports to an SMB file share on the Amazon FSx file system. Enable nightly backups.`, ko:`Direct Connect 연결에 연결된 VPC 내에서 Windows 파일 서버 다중 AZ 파일 시스템용 Amazon FSx를 생성합니다. 새 SMB 파일 공유를 만듭니다. Amazon FSx 파일 시스템의 SMB 파일 공유에 야간 데이터베이스 내보내기를 기록합니다. 야간 백업을 활성화합니다.` },
      { k:'D', en:`Create a new S3 bucket. Deploy an AWS Storage Gateway volume gateway within the VPC that is connected to the Direct Connect connection. Create a new SMB file share. Write nightly database exports to the new SMB file share on the volume gateway, and automate copies of this data to an S3 bucket.`, ko:`새 S3 버킷을 생성합니다. Direct Connect 연결에 연결된 VPC 내에 AWS Storage Gateway 볼륨 게이트웨이를 배포합니다. 새 SMB 파일 공유를 만듭니다. 볼륨 게이트웨이의 새 SMB 파일 공유에 야간 데이터베이스 내보내기를 작성하고 이 데이터를 S3 버킷에 자동으로 복사합니다.` },
    ],
    answer: ["A"],
    vote: '93% A, 7% D',
    explain: `<p><span class="mark-ok">✅ A</span></p><p>파일 게이트웨이 == SMB, NFS 볼륨 게이트웨이 == iSCSI 테이프 게이트웨이 = VTL</p>`,
    wrong: `<p><span class="mark-no">❌ D</span> — olabiba.ai는 D 옵션 D: AWS Storage Gateway 볼륨 게이트웨이를 사용하면 볼륨 게이트웨이의 SMB 파일 공유에 야간 데이터베이스 내보내기를 기록할 수 있으며, 이를 로컬에 저장하고 S3 버킷에 자동으로 백업할 수 있습니다. 이 솔루션은 기존 Direct Connect 연결을 활용하고 최소한의 추가 인프라만 필요하므로 비용 효율적입니</p>`,
    disc: [{ ans:'A', txt:'파일 게이트웨이 == SMB, NFS 볼륨 게이트웨이 == iSCSI 테이프 게이트웨이 = VTL' }, { ans:'A', txt:'File Gateway == SMB , NFS Volumes Gateway == iSCSI Tape Gateway = VTL' }, { ans:'A', txt:'파일 게이트웨이는 SMB 파일 공유로 매핑될 수 있으며 데이터베이스 또는 기타 자동화에서 데이터베이스 백업을 전송하는 데 사용될 수 있습니다. 볼륨 게이트웨이는 온프레미스 시스템에서 볼륨 스냅샷을 수행하는 데 더 많이 사용되므로 여기서는 이것이 지속 가능한 접근 방식이라고 생각하지 않습니다.' }, { ans:'A', txt:'File Gateway could be mapped as SMB file share and used by the database or other automation to transfer database backups. Volume Gateway is more used to perform volume snapshots on the on-premise system so I don\'t believe it\'s a sustainable approach here.' }, { ans:'A', txt:'A - SMB 마운트 = 파일 gwy' }]
  },
  {
    n: 232,
    en: `A company needs to establish a connection from its on-premises data center to AWS. The company needs to connect all of its VPCs that are located in different AWS Regions with transitive routing capabilities between VPC networks. The company also must reduce network outbound traffic costs, increase bandwidth throughput, and provide a consistent network experience for end users.<br/><br/>Which solution will meet these requirements?`,
    ko: `회사는 온프레미스 데이터 센터에서 AWS로 연결을 설정해야 합니다. 회사는 VPC 네트워크 간의 전이적 라우팅 기능을 사용하여 다양한 AWS 지역에 있는 모든 VPC를 연결해야 합니다. 또한 회사는 네트워크 아웃바운드 트래픽 비용을 줄이고, 대역폭 처리량을 늘리며, 최종 사용자에게 일관된 네트워크 경험을 제공해야 합니다. <br/><br/>어떤 솔루션이 이러한 요구 사항을 충족합니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Create an AWS Site-to-Site VPN connection between the on-premises data center and a new central VPC. Create VPC peering connections that initiate from the central VPC to all other VPCs.`, ko:`온프레미스 데이터 센터와 새로운 중앙 VPC 간에 AWS Site-to-Site VPN 연결을 생성합니다. 중앙 VPC에서 다른 모든 VPC로 시작되는 VPC 피어링 연결을 생성합니다.` },
      { k:'B', en:`Create an AWS Direct Connect connection between the on-premises data center and AWS. Provision a transit VIF, and connect it to a Direct Connect gateway. Connect the Direct Connect gateway to all the other VPCs by using a transit gateway in each Region.`, ko:`온프레미스 데이터 센터와 AWS 간에 AWS Direct Connect 연결을 생성합니다. 전송 VIF를 프로비저닝하고 이를 Direct Connect 게이트웨이에 연결합니다. 각 리전의 전송 게이트웨이를 사용하여 Direct Connect 게이트웨이를 다른 모든 VPC에 연결합니다.` },
      { k:'C', en:`Create an AWS Site-to-Site VPN connection between the on-premises data center and a new central VPUse a transit gateway with dynamic routing. Connect the transit gateway to all other VPCs.`, ko:`온프레미스 데이터 센터와 새로운 중앙 VP 간에 AWS Site-to-Site VPN 연결을 생성합니다. 동적 라우팅이 포함된 전송 게이트웨이를 사용합니다. Transit Gateway를 다른 모든 VPC에 연결합니다.` },
      { k:'D', en:`Create an AWS Direct Connect connection between the on-premises data center and AWS. Establish an AWS Site-to-Site VPN connection between all VPCs in each Region. Create VPC peering connections that initiate from the central VPC to all other VPCs.`, ko:`온프레미스 데이터 센터와 AWS 간에 AWS Direct Connect 연결을 생성합니다. 각 리전의 모든 VPC 간에 AWS Site-to-Site VPN 연결을 설정합니다. 중앙 VPC에서 다른 모든 VPC로 시작되는 VPC 피어링 연결을 생성합니다.` },
    ],
    answer: ["B"],
    vote: '100% B',
    explain: `<p><span class="mark-ok">✅ B</span></p><p>실제로 사이트 간 VPN은 Direct Connect 임대 회선을 배포하는 것보다 더 저렴합니다. 그러나 AWS는 처리량(사이트 간만 최대 1.25Gbps를 달성할 수 있음)과 일관된 사용자 경험(AWS Direct Connect > Site-to-Site VPN)을 늘려 B가 더 나은 선택이 되십시오.</p>`,
    wrong: ``,
    disc: [{ ans:'B', txt:'실제로 사이트 간 VPN은 Direct Connect 임대 회선을 배포하는 것보다 더 저렴합니다. 그러나 AWS는 처리량(사이트 간만 최대 1.25Gbps를 달성할 수 있음)과 일관된 사용자 경험(AWS Direct Connect > Site-to-Site VPN)을 늘려 B가 더 나은 선택이 되십시오.' }, { ans:'B', txt:'In fact site to site VPN would be more affordable than deploying a Direct Connect leased line. However, AWS also wants to market their product by stating that there is a need to increase throughput (site to site only can achieve max of 1.25Gbps) and consistent user experience (AWS Direct Connect > Site-to-Site VPN) so B would be a better choice.' }, { ans:'B', txt:'https://docs.aws.amazon.com/whitepapers/latest/aws-vpc-connectivity-options/aws-direct-connect-aws-transit-gateway.html' }, { ans:'B', txt:'직접 연결 + vpc = 직접 연결 gw + TGW. 그래서 B' }, { ans:'B', txt:'direct connect + vpc = direct connect gw + TGW. so B' }]
  },
  {
    n: 233,
    en: `A company is migrating its development and production workloads to a new organization in AWS Organizations. The company has created a separate member account for development and a separate member account for production. Consolidated billing is linked to the management account. In the management account, a solutions architect needs to create an IAM user that can stop or terminate resources in both member accounts.<br/><br/>Which solution will meet this requirement?`,
    ko: `한 회사가 개발 및 생산 워크로드를 AWS Organizations의 새로운 조직으로 마이그레이션하고 있습니다. 회사는 개발용 회원계정과 제작용 회원계정을 별도로 개설하였습니다. 통합결제는 마스터 계정에 연결됩니다. 마스터 계정에서 솔루션 아키텍트는 두 멤버 계정 모두에서 리소스를 중지하거나 종료할 수 있는 IAM 사용자를 생성해야 합니다.<br/><br/>이 요구 사항을 충족하는 솔루션은 무엇입니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Create an IAM user and a cross-account role in the management account. Configure the cross-account role with least privilege access to the member accounts.`, ko:`마스터 계정에서 IAM 사용자 및 교차 계정 역할을 생성합니다. 멤버 계정에 대한 최소 권한 액세스로 교차 계정 역할을 구성합니다.` },
      { k:'B', en:`Create an IAM user in each member account. In the management account, create a cross-account role that has least privilege access. Grant the IAM users access to the cross-account role by using a trust policy.`, ko:`각 회원 계정에 IAM 사용자를 생성합니다. 마스터 계정에서 최소 액세스 권한이 있는 교차 계정 역할을 생성합니다. 신뢰 정책을 사용하여 IAM 사용자에게 교차 계정 역할에 대한 액세스 권한을 부여합니다.` },
      { k:'C', en:`Create an IAM user in the management account. In the member accounts, create an IAM group that has least privilege access. Add the IAM user from the management account to each IAM group in the member accounts.`, ko:`마스터 계정에서 IAM 사용자를 생성합니다. 회원 계정에서 최소 액세스 권한이 있는 IAM 그룹을 생성합니다. 마스터 계정의 IAM 사용자를 멤버 계정의 각 IAM 그룹에 추가합니다.` },
      { k:'D', en:`Create an IAM user in the management account. In the member accounts, create cross-account roles that have least privilege access. Grant the IAM user access to the roles by using a trust policy.`, ko:`마스터 계정에서 IAM 사용자를 생성합니다. 멤버 계정에서 최소 액세스 권한이 있는 교차 계정 역할을 생성합니다. 신뢰 정책을 사용하여 IAM 사용자에게 역할에 대한 액세스 권한을 부여합니다.` },
    ],
    answer: ["D"],
    vote: '100% D',
    explain: `<p><span class="mark-ok">✅ D</span></p><p>옵션 D</p>`,
    wrong: ``,
    disc: [{ ans:'D', txt:'D - 대상(멤버) 계정에 교차 계정 역할을 생성해야 합니다. 역할에는 마스터 계정에 대한 신뢰 엔터티가 있습니다.' }, { ans:'D', txt:'D - Cross account role should be created in destination(member) account. The role has trust entity to master account.' }, { ans:'D', txt:'옵션 D' }, { ans:'D', txt:'D야' }, { ans:'D', txt:'D - 대상 계정(멤버 계정)에 교차 계정 역할이 생성되어야 하며 신뢰 정책이 있어야 합니다.' }]
  },
  {
    n: 234,
    en: `A company wants to use AWS for disaster recovery for an on-premises application. The company has hundreds of Windows-based servers that run the application. All the servers mount a common share.<br/><br/>The company has an RTO of 15 minutes and an RPO of 5 minutes. The solution must support native failover and fallback capabilities.<br/><br/>Which solution will meet these requirements MOST cost-effectively?`,
    ko: `회사에서는 온프레미스 애플리케이션의 재해 복구를 위해 AWS를 사용하려고 합니다. 이 회사는 애플리케이션을 실행하는 수백 대의 Windows 기반 서버를 보유하고 있습니다. 모든 서버는 공통 공유를 마운트합니다. <br/><br/>이 회사의 RTO는 15분, RPO는 5분입니다. 솔루션은 기본 장애 조치 및 대체 기능을 지원해야 합니다. <br/><br/>이러한 요구 사항을 가장 비용 효율적으로 충족하는 솔루션은 무엇입니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Create an AWS Storage Gateway File Gateway. Schedule daily Windows server backups. Save the data to Amazon S3. During a disaster, recover the on-premises servers from the backup. During tailback, run the on-premises servers on Amazon EC2 instances.`, ko:`AWS Storage Gateway 파일 게이트웨이를 생성합니다. 매일 Windows 서버 백업을 예약합니다. 데이터를 Amazon S3에 저장합니다. 재해 발생 시 백업에서 온프레미스 서버를 복구합니다. 테일백 중에 Amazon EC2 인스턴스에서 온프레미스 서버를 실행합니다.` },
      { k:'B', en:`Create a set of AWS CloudFormation templates to create infrastructure. Replicate all data to Amazon Elastic File System (Amazon EFS) by using AWS DataSync. During a disaster, use AWS CodePipeline to deploy the templates to restore the on-premises servers. Fail back the data by using DataSync.`, ko:`AWS CloudFormation 템플릿 세트를 생성하여 인프라를 생성합니다. AWS DataSync를 사용하여 모든 데이터를 Amazon Elastic File System(Amazon EFS)에 복제합니다. 재해 발생 시 AWS CodePipeline을 사용하여 온프레미스 서버를 복원하는 템플릿을 배포합니다. DataSync를 사용하여 데이터를 장애 복구합니다.` },
      { k:'C', en:`Create an AWS Cloud Development Kit (AWS CDK) pipeline to stand up a multi-site active-active environment on AWS. Replicate data into Amazon S3 by using the s3 sync command. During a disaster, swap DNS endpoints to point to AWS. Fail back the data by using the s3 sync command.`, ko:`AWS CDK(AWS Cloud Development Kit) 파이프라인을 생성하여 AWS에서 다중 사이트 Active-Active 환경을 구축합니다. s3 sync 명령을 사용하여 데이터를 Amazon S3에 복제합니다. 재해가 발생하면 DNS 엔드포인트를 AWS를 가리키도록 교체하세요. s3 sync 명령을 사용하여 데이터를 장애 복구합니다.` },
      { k:'D', en:`Use AWS Elastic Disaster Recovery to replicate the on-premises servers. Replicate data to an Amazon FSx for Windows File Server file system by using AWS DataSync. Mount the file system to AWS servers. During a disaster, fail over the on-premises servers to AWS. Fail back to new or existing servers by using Elastic Disaster Recovery.`, ko:`AWS Elastic Disaster Recovery를 사용하여 온프레미스 서버를 복제합니다. AWS DataSync를 사용하여 Amazon FSx for Windows File Server 파일 시스템에 데이터를 복제합니다. 파일 시스템을 AWS 서버에 탑재합니다. 재해 발생 시 온프레미스 서버를 AWS로 장애 조치합니다. Elastic Disaster Recovery를 사용하여 신규 또는 기존 서버로 장애 복구합니다.` },
    ],
    answer: ["D"],
    vote: '100% D',
    explain: `<p><span class="mark-ok">✅ D</span></p><p>방법에 대한 단계 - https://aws.amazon.com/blogs/storage/recovering-network-file-shares-with-aws-elastic-disaster-recovery-and-aws-datasync/</p>`,
    wrong: ``,
    disc: [{ ans:'D', txt:'Windows용 FSX 및 탄력적 재해 복구' }, { ans:'D', txt:'FSX for Windows and Elastic Disaster Recovery' }, { ans:'D', txt:'RTO와 RPO를 고려하면 D가 정답입니다. A는 오답입니다. 백업이 s3에 있다고 생각하면 15분 RTO와 5분 RPO 내에 ec2를 복구할 수 없기 때문입니다.' }, { ans:'D', txt:'Considering RTO and RPO, D is correct answer A is incorrect because, thought backups are in s3, its not possible to recover ec2 within 15-minute RTO and a 5-minute RPO' }, { ans:'D', txt:'EFS가 아닌 FSx가 필요하고 S3가 아닌 def가 필요합니다.' }]
  },
  {
    n: 235,
    en: `A company has built a high performance computing (HPC) cluster in AWS for a tightly coupled workload that generates a large number of shared files stored in Amazon EFS. The cluster was performing well when the number of Amazon EC2 instances in the cluster was 100. However, when the company increased the cluster size to 1.000 EC2 instances, overall performance was well below expectations.<br/><br/>Which collection of design choices should a solutions architect make to achieve the maximum performance from the HPC cluster? (Choose three.)`,
    ko: `한 회사는 Amazon EFS에 저장된 대량의 공유 파일을 생성하는 긴밀하게 결합된 워크로드를 위해 AWS에 고성능 컴퓨팅(HPC) 클러스터를 구축했습니다. 클러스터의 Amazon EC2 인스턴스 수가 100개일 때는 클러스터 성능이 좋았습니다. 그러나 회사가 클러스터 크기를 EC2 인스턴스 1,000개로 늘렸을 때 전체 성능은 기대보다 훨씬 낮았습니다. <br/><br/>솔루션 아키텍트는 HPC 클러스터에서 최대 성능을 달성하기 위해 어떤 디자인 선택을 해야 합니까? (3개를 선택하세요.)`,
    type: 'multi', multiCount: 3,
    choices: [
      { k:'A', en:`Ensure the HPC cluster is launched within a single Availability Zone.`, ko:`HPC 클러스터가 단일 가용 영역 내에서 시작되는지 확인하세요.` },
      { k:'B', en:`Launch the EC2 instances and attach elastic network interfaces in multiples of four.`, ko:`EC2 인스턴스를 시작하고 탄력적 네트워크 인터페이스를 4의 배수로 연결합니다.` },
      { k:'C', en:`Select EC2 instance types with an Elastic Fabric Adapter (EFA) enabled.`, ko:`EFA(Elastic Fabric Adapter)가 활성화된 EC2 인스턴스 유형을 선택합니다.` },
      { k:'D', en:`Ensure the cluster is launched across multiple Availability Zones.`, ko:`클러스터가 여러 가용 영역에서 시작되는지 확인합니다.` },
      { k:'E', en:`Replace Amazon EFS with multiple Amazon EBS volumes in a RAID array.`, ko:`Amazon EFS를 RAID 어레이의 여러 Amazon EBS 볼륨으로 교체합니다.` },
      { k:'F', en:`Replace Amazon EFS with Amazon FSx for Lustre.`, ko:`Amazon EFS를 Lustre용 Amazon FSx로 교체합니다.` },
    ],
    answer: [],
    vote: '88% ACF, 12% CDF',
    explain: ``,
    wrong: `<p><span class="mark-no">❌ A</span> — A. HPC 클러스터가 단일 가용 영역 내에서 시작되는지 확인합니다. 이렇게 선택하면 클러스터의 EC2 인스턴스가 동일한 데이터 센터 내에 위치하므로 네트워크 지연 시간이 짧고 대역폭이 높습니다. C. EFA(Elastic Fabric Adapter)가 활성화된 EC2 인스턴스 유형을 선택합니다. EFA는 EC2 인스턴스 간에 지연 시간이 짧고 고대역폭 통</p><p><span class="mark-no">❌ C</span> — A. HPC 클러스터가 단일 가용 영역 내에서 시작되는지 확인합니다. 이렇게 선택하면 클러스터의 EC2 인스턴스가 동일한 데이터 센터 내에 위치하므로 네트워크 지연 시간이 짧고 대역폭이 높습니다. C. EFA(Elastic Fabric Adapter)가 활성화된 EC2 인스턴스 유형을 선택합니다. EFA는 EC2 인스턴스 간에 지연 시간이 짧고 고대역폭 통</p><p><span class="mark-no">❌ D</span> — B: 인터페이스가 많다고 해서 속도가 빨라지는 것은 아닙니다. 그래서 B는 좋은 선택이 아닙니다. E: RAID? Cloud Platform에서는 권장되지 않는 경우가 많으므로 aws는 이미 언더레이용 드라이브를 습격했습니다. A: HPC에서는 다중 지역을 사용하는 것이 좋습니다. 그래서 CDF</p><p><span class="mark-no">❌ F</span> — A. HPC 클러스터가 단일 가용 영역 내에서 시작되는지 확인합니다. 이렇게 선택하면 클러스터의 EC2 인스턴스가 동일한 데이터 센터 내에 위치하므로 네트워크 지연 시간이 짧고 대역폭이 높습니다. C. EFA(Elastic Fabric Adapter)가 활성화된 EC2 인스턴스 유형을 선택합니다. EFA는 EC2 인스턴스 간에 지연 시간이 짧고 고대역폭 통</p>`,
    disc: [{ ans:'A, C, F', txt:'A. HPC 클러스터가 단일 가용 영역 내에서 시작되는지 확인합니다. 이렇게 선택하면 클러스터의 EC2 인스턴스가 동일한 데이터 센터 내에 위치하므로 네트워크 지연 시간이 짧고 대역폭이 높습니다. C. EFA(Elastic Fabric Adapter)가 활성화된 EC2 인스턴스 유형을 선택합니다. EFA는 EC2 인스턴스 간에 지연 시간이 짧고 고대역폭 통신을 제공하는 네트워크 인터페이스입니다. EFA가 활성화된 인스턴스 유형을 선택하면 클러스터는 향상된 인스턴스 간 통신의 이점을 누릴 수 있습니다. F. Amazon EFS를 Lustre용 Amazon FSx로 교체: Lustre용 Amazon FSx는 HPC 워크로드에 최적화된 고성능 파일 시스템입니다. Amazon EFS 대신 FSx for Lus...' }, { ans:'A, C, F', txt:'A. Ensure the HPC cluster is launched within a single Availability Zone: This choice ensures that the EC2 instances in the cluster have low network latency and high bandwidth, as they are located within the same data center. C. Select EC2 instance types with an Elastic Fabric Adapter (EFA) enabled: EFA is a network interface that provides low-latency, high-bandwidth communication between EC2 in...' }, { ans:'A, C, F', txt:'ACF로 가는데 논리적인 것 같아' }, { ans:'A, C, F', txt:'에이, 씨, 에프' }, { ans:'A, C, F', txt:'성능을 위한 ACF' }]
  },
  {
    n: 236,
    en: `A company is designing an AWS Organizations structure. The company wants to standardize a process to apply tags across the entire organization. The company will require tags with specific values when a user creates a new resource. Each of the company's OUs will have unique tag values.<br/><br/>Which solution will meet these requirements?`,
    ko: `한 회사가 AWS Organizations 구조를 설계하고 있습니다. 회사는 전체 조직에 태그를 적용하는 프로세스를 표준화하려고 합니다. 회사에서는 사용자가 새 리소스를 생성할 때 특정 값이 포함된 태그를 요구합니다. 회사의 각 OU에는 고유한 태그 값이 있습니다. <br/><br/>어떤 솔루션이 이러한 요구 사항을 충족합니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Use an SCP to deny the creation of resources that do not have the required tags. Create a tag policy that includes the tag values that the company has assigned to each OU. Attach the tag policies to the OUs.`, ko:`필수 태그가 없는 리소스 생성을 거부하려면 SCP를 사용하십시오. 회사가 각 OU에 할당한 태그 값을 포함하는 태그 정책을 생성합니다. 태그 정책을 OU에 연결합니다.` },
      { k:'B', en:`Use an SCP to deny the creation of resources that do not have the required tags. Create a tag policy that includes the tag values that the company has assigned to each OU. Attach the tag policies to the organization's management account.`, ko:`SCP를 사용하여 필수 태그가 없는 리소스 생성을 거부합니다. 회사가 각 OU에 할당한 태그 값을 포함하는 태그 정책을 생성합니다. 태그 정책을 조직의 마스터 계정에 연결합니다.` },
      { k:'C', en:`Use an SCP to allow the creation of resources only when the resources have the required tags. Create a tag policy that includes the tag values that the company has assigned to each OU. Attach the tag policies to the OUs.`, ko:`SCP를 사용하여 리소스에 필수 태그가 있는 경우에만 리소스 생성을 허용합니다. 회사가 각 OU에 할당한 태그 값을 포함하는 태그 정책을 생성합니다. 태그 정책을 OU에 연결합니다.` },
      { k:'D', en:`Use an SCP to deny the creation of resources that do not have the required tags. Define the list of tags. Attach the SCP to the OUs.`, ko:`SCP를 사용하여 필수 태그가 없는 리소스 생성을 거부합니다. 태그 목록을 정의합니다. SCP를 OU에 연결합니다.` },
    ],
    answer: ["A"],
    vote: '82% A, 18% B',
    explain: `<p><span class="mark-ok">✅ A</span></p><p>옵션 A</p>`,
    wrong: `<p><span class="mark-no">❌ B</span> — B - 각 계정 또는 OU에 적용 SCP가 없습니다. 태그 정책을 조직의 마스터 계정에 연결하면 정책이 조직 내의 모든 OU에 일관되게 적용됩니다. SCP는 ALLOW 작업에 사용되지 않기 때문에 C는 올바르지 않습니다. DENY 작업(경계 설정)에 사용됩니다.</p>`,
    disc: [{ ans:'A', txt:'마스터 계정 -> 조직 콘솔 -> 정책 -> 정책 태그 -> "정책 이름" -> OU에 연결로 이동합니다. 그렇군요 - A가 맞습니다' }, { ans:'A', txt:'You go to the management account -> Organizations console -> Policies -> Tag policies -> "name of the policy" -> attach to OU. That\'s it - A is correct' }, { ans:'A', txt:'A 입니다. 계정마다 정책이 다르기 때문에 마스터 계정에 할당할 수 없습니다. 똑같은 시나리오: https://aws.amazon.com/blogs/mt/implement-aws-resource-tagged-strategy-using-aws-tag-policies-and-service-control-policies-scps/' }, { ans:'B', txt:'B - 각 계정 또는 OU에 적용 SCP가 없습니다. 태그 정책을 조직의 마스터 계정에 연결하면 정책이 조직 내의 모든 OU에 일관되게 적용됩니다. SCP는 ALLOW 작업에 사용되지 않기 때문에 C는 올바르지 않습니다. DENY 작업(경계 설정)에 사용됩니다.' }, { ans:'A', txt:'It\'s A. The policies are different for each account, so you can\'t assign it to the management account. Exact same scenario: https://aws.amazon.com/blogs/mt/implement-aws-resource-tagging-strategy-using-aws-tag-policies-and-service-control-policies-scps/' }]
  },
  {
    n: 237,
    en: `A company has more than 10,000 sensors that send data to an on-premises Apache Kafka server by using the Message Queuing Telemetry Transport (MQTT) protocol. The on-premises Kafka server transforms the data and then stores the results as objects in an Amazon S3 bucket.<br/><br/>Recently, the Kafka server crashed. The company lost sensor data while the server was being restored. A solutions architect must create a new design on AWS that is highly available and scalable to prevent a similar occurrence.<br/><br/>Which solution will meet these requirements?`,
    ko: `한 회사에는 MQTT(Message Queuing Telemetry Transport) 프로토콜을 사용하여 온프레미스 Apache Kafka 서버에 데이터를 보내는 10,000개 이상의 센서가 있습니다. 온프레미스 Kafka 서버는 데이터를 변환한 다음 결과를 Amazon S3 버킷에 객체로 저장합니다. <br/><br/>최근 Kafka 서버가 다운되었습니다. 서버를 복원하는 동안 회사에서 센서 데이터가 손실되었습니다. 솔루션 아키텍트는 유사한 발생을 방지하기 위해 가용성과 확장성이 뛰어난 새로운 설계를 AWS에서 생성해야 합니다. <br/><br/>어떤 솔루션이 이러한 요구 사항을 충족합니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Launch two Amazon EC2 instances to host the Kafka server in an active/standby configuration across two Availability Zones. Create a domain name in Amazon Route 53. Create a Route 53 failover policy. Route the sensors to send the data to the domain name.`, ko:`두 개의 Amazon EC2 인스턴스를 시작하여 두 개의 가용 영역에 걸쳐 활성/대기 구성으로 Kafka 서버를 호스팅합니다. Amazon Route 53에서 도메인 이름을 생성합니다. Route 53 장애 조치 정책을 생성합니다. 데이터를 도메인 이름으로 보내도록 센서를 라우팅합니다.` },
      { k:'B', en:`Migrate the on-premises Kafka server to Amazon Managed Streaming for Apache Kafka (Amazon MSK). Create a Network Load Balancer (NLB) that points to the Amazon MSK broker. Enable NLB health checks. Route the sensors to send the data to the NLB.`, ko:`온프레미스 Kafka 서버를 Amazon Managed Streaming for Apache Kafka(Amazon MSK)로 마이그레이션합니다. Amazon MSK 브로커를 가리키는 NLB(Network Load Balancer)를 생성합니다. NLB 상태 확인을 활성화합니다. 데이터를 NLB로 보내도록 센서를 라우팅합니다.` },
      { k:'C', en:`Deploy AWS IoT Core, and connect it to an Amazon Kinesis Data Firehose delivery stream. Use an AWS Lambda function to handle data transformation. Route the sensors to send the data to AWS IoT Core.`, ko:`AWS IoT Core를 배포하고 Amazon Kinesis Data Firehose 전송 스트림에 연결합니다. AWS Lambda 함수를 사용하여 데이터 변환을 처리합니다. 데이터를 AWS IoT Core로 보내도록 센서를 라우팅합니다.` },
      { k:'D', en:`Deploy AWS IoT Core, and launch an Amazon EC2 instance to host the Kafka server. Configure AWS IoT Core to send the data to the EC2 instance. Route the sensors to send the data to AWS IoT Core.`, ko:`AWS IoT Core를 배포하고 Amazon EC2 인스턴스를 시작하여 Kafka 서버를 호스팅합니다. 데이터를 EC2 인스턴스로 보내도록 AWS IoT Core를 구성합니다. 데이터를 AWS IoT Core로 보내도록 센서를 라우팅합니다.` },
    ],
    answer: ["C"],
    vote: '79% C, 21% B',
    explain: `<p><span class="mark-ok">✅ C</span></p><p>MSK는 데이터를 변환할 수 없습니다.</p>`,
    wrong: `<p><span class="mark-no">❌ B</span> — B와 C 모두 작동할까요? NLB + MSK는 잘 정의된 패턴입니다. MSK는 가용성과 확장성이 뛰어납니다. MQTT는 단지 네트워크 포트이므로 NLB를 통과합니다. 응용 프로그램에는 변경 사항이 없습니다. C도 작동하지만 더 많은 리팩토링이 필요한 것 같습니다.</p>`,
    disc: [{ ans:'C', txt:'옵션 B에는 Lambda에서 수행할 데이터 변환이 누락되어 있습니다.' }, { ans:'C', txt:'C, 새로운 디자인과 분명히 IoT가 AWS에서 권장하는 것이라고 말했기 때문입니다.' }, { ans:'C', txt:'Option B is missing the Data Transformation to be done by Lambda' }, { ans:'C', txt:'C, because it said new design and obviously IoT is what aws recommend.' }, { ans:'B', txt:'B와 C 모두 작동할까요? NLB + MSK는 잘 정의된 패턴입니다. MSK는 가용성과 확장성이 뛰어납니다. MQTT는 단지 네트워크 포트이므로 NLB를 통과합니다. 응용 프로그램에는 변경 사항이 없습니다. C도 작동하지만 더 많은 리팩토링이 필요한 것 같습니다.' }]
  },
  {
    n: 238,
    en: `A company recently started hosting new application workloads in the AWS Cloud. The company is using Amazon EC2 instances. Amazon Elastic File System (Amazon EFS) file systems, and Amazon RDS DB instances.<br/><br/>To meet regulatory and business requirements, the company must make the following changes for data backups:<br/><br/>•	Backups must be retained based on custom daily, weekly, and monthly requirements.<br/>•	Backups must be replicated to at least one other AWS Region immediately after capture.<br/>•	The backup solution must provide a single source of backup status across the AWS environment.<br/>•	The backup solution must send immediate notifications upon failure of any resource backup.<br/><br/>Which combination of steps will meet these requirements with the LEAST amount of operational overhead? (Choose three.)`,
    ko: `한 회사는 최근 AWS 클라우드에서 새로운 애플리케이션 워크로드를 호스팅하기 시작했습니다. 회사는 Amazon EC2 인스턴스를 사용하고 있습니다. Amazon Elastic File System(Amazon EFS) 파일 시스템 및 Amazon RDS DB 인스턴스. <br/><br/>규정 및 비즈니스 요구 사항을 충족하기 위해 회사는 데이터 백업에 대해 다음과 같은 변경을 수행해야 합니다. <br/><br/>• 백업은 사용자 지정 일일, 주간 및 월간 요구 사항에 따라 유지되어야 합니다. <br/>• 백업은 캡처 후 즉시 하나 이상의 다른 AWS 리전에 복제되어야 합니다. <br/>• 백업 솔루션은 AWS 환경 전반에 걸쳐 백업 상태에 대한 단일 소스를 제공해야 합니다. <br/>• 백업 솔루션은 리소스 백업 실패 시 즉시 알림을 보내야 합니다. <br/><br/>최소한의 운영 오버헤드로 이러한 요구 사항을 충족하는 단계 조합은 무엇입니까? (3개를 선택하세요.)`,
    type: 'multi', multiCount: 3,
    choices: [
      { k:'A', en:`Create an AWS Backup plan with a backup rule for each of the retention requirements.`, ko:`각 보존 요구 사항에 대한 백업 규칙을 사용하여 AWS 백업 계획을 생성합니다.` },
      { k:'B', en:`Configure an AWS Backup plan to copy backups to another Region.`, ko:`백업을 다른 지역으로 복사하도록 AWS 백업 계획을 구성합니다.` },
      { k:'C', en:`Create an AWS Lambda function to replicate backups to another Region and send notification if a failure occurs.`, ko:`백업을 다른 리전에 복제하고 오류가 발생하면 알림을 보내는 AWS Lambda 함수를 생성합니다.` },
      { k:'D', en:`Add an Amazon Simple Notification Service (Amazon SNS) topic to the backup plan to send a notification for finished jobs that have any status except BACKUP_JOB_COMPLETED.`, ko:`BACKUP_JOB_COMPLETED를 제외한 모든 상태의 완료된 작업에 대한 알림을 보내려면 백업 계획에 Amazon Simple 알림 서비스(Amazon SNS) 주제를 추가합니다.` },
      { k:'E', en:`Create an Amazon Data Lifecycle Manager (Amazon DLM) snapshot lifecycle policy for each of the retention requirements.`, ko:`각 보존 요구 사항에 대한 Amazon Data Lifecycle Manager(Amazon DLM) 스냅샷 수명 주기 정책을 생성합니다.` },
      { k:'F', en:`Set up RDS snapshots on each database.`, ko:`각 데이터베이스에 RDS 스냅샷을 설정합니다.` },
    ],
    answer: [],
    vote: '100% ABD',
    explain: ``,
    wrong: `<p><span class="mark-no">❌ A</span> — Amazon Data Lifecycle Manager가 EBS 스냅샷 및 EBS 지원 AMI의 생성, 보존 및 삭제를 자동화하는 데 사용되었기 때문에 ABD E는 올바르지 않습니다. ec2, EFS, RDS https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/snapshot-lifecycle.html의 백업에는</p><p><span class="mark-no">❌ B</span> — Amazon Data Lifecycle Manager가 EBS 스냅샷 및 EBS 지원 AMI의 생성, 보존 및 삭제를 자동화하는 데 사용되었기 때문에 ABD E는 올바르지 않습니다. ec2, EFS, RDS https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/snapshot-lifecycle.html의 백업에는</p><p><span class="mark-no">❌ D</span> — Amazon Data Lifecycle Manager가 EBS 스냅샷 및 EBS 지원 AMI의 생성, 보존 및 삭제를 자동화하는 데 사용되었기 때문에 ABD E는 올바르지 않습니다. ec2, EFS, RDS https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/snapshot-lifecycle.html의 백업에는</p>`,
    disc: [{ ans:'A, B, D', txt:'Amazon Data Lifecycle Manager가 EBS 스냅샷 및 EBS 지원 AMI의 생성, 보존 및 삭제를 자동화하는 데 사용되었기 때문에 ABD E는 올바르지 않습니다. ec2, EFS, RDS https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/snapshot-lifecycle.html의 백업에는 사용할 수 없습니다.' }, { ans:'A, B, D', txt:'ABD E is incorrect because Amazon Data Lifecycle Manager to used to automate the creation, retention, and deletion of EBS snapshots and EBS-backed AMIs. It CANNOT be used for backups for ec2, EFS, RDS https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/snapshot-lifecycle.html' }, { ans:'A, B, D', txt:'AWS 백업 계획 - https://docs.aws.amazon.com/aws-backup/latest/devguide/about-backup-plans.html AWS 지역 간 백업 복사 - https://docs.aws.amazon.com/aws -backup/latest/devguide/cross-region-backup.html AWS 지역 간 백업 비디오 - https://www.youtube.com/watch?v=qMN18Lpj3PE' }, { ans:'A, B, D', txt:'AWS Backup Plan - https://docs.aws.amazon.com/aws-backup/latest/devguide/about-backup-plans.html Backup Copy across AWS Regions - https://docs.aws.amazon.com/aws-backup/latest/devguide/cross-region-backup.html Backup across AWS regions video - https://www.youtube.com/watch?v=qMN18Lpj3PE' }, { ans:'A, B, D', txt:'옵션 ABD' }]
  },
  {
    n: 239,
    en: `A company is developing a gene reporting device that will collect genomic information to assist researchers with collecting large samples of data from a diverse population. The device will push 8 KB of genomic data every second to a data platform that will need to process and analyze the data and provide information back to researchers. The data platform must meet the following requirements:<br/><br/>•	Provide near-real-time analytics of the inbound genomic data<br/>•	Ensure the data is flexible, parallel, and durable<br/>•	Deliver results of processing to a data warehouse<br/><br/>Which strategy should a solutions architect use to meet these requirements?`,
    ko: `한 회사는 연구자들이 다양한 집단으로부터 대량의 데이터 샘플을 수집하는 데 도움이 되도록 게놈 정보를 수집하는 유전자 보고 장치를 개발하고 있습니다. 이 장치는 데이터를 처리 및 분석하고 연구자들에게 정보를 다시 제공해야 하는 데이터 플랫폼에 매초 8KB의 게놈 데이터를 푸시합니다. 데이터 플랫폼은 다음 요구 사항을 충족해야 합니다. <br/><br/>• 인바운드 게놈 데이터에 대한 거의 실시간 분석 제공 <br/>• 데이터의 유연성, 병렬성 및 내구성 보장 <br/>• 처리 결과를 데이터 웨어하우스에 전달 <br/><br/>솔루션 설계자가 사용해야 하는 전략 이러한 요구 사항을 충족합니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Use Amazon Kinesis Data Firehose to collect the inbound sensor data, analyze the data with Kinesis clients, and save the results to an Amazon RDS instance.`, ko:`Amazon Kinesis Data Firehose를 사용하여 인바운드 센서 데이터를 수집하고, Kinesis 클라이언트로 데이터를 분석하고, 결과를 Amazon RDS 인스턴스에 저장합니다.` },
      { k:'B', en:`Use Amazon Kinesis Data Streams to collect the inbound sensor data, analyze the data with Kinesis clients, and save the results to an Amazon Redshift cluster using Amazon EMR.`, ko:`Amazon Kinesis Data Streams를 사용하여 인바운드 센서 데이터를 수집하고, Kinesis 클라이언트로 데이터를 분석하고, Amazon EMR을 사용하여 Amazon Redshift 클러스터에 결과를 저장합니다.` },
      { k:'C', en:`Use Amazon S3 to collect the inbound device data, analyze the data from Amazon SQS with Kinesis, and save the results to an Amazon Redshift cluster.`, ko:`Amazon S3를 사용하여 인바운드 장치 데이터를 수집하고, Kinesis를 사용하여 Amazon SQS에서 데이터를 분석하고, 결과를 Amazon Redshift 클러스터에 저장합니다.` },
      { k:'D', en:`Use an Amazon API Gateway to put requests into an Amazon SQS queue, analyze the data with an AWS Lambda function, and save the results to an Amazon Redshift cluster using Amazon EMR.`, ko:`Amazon API Gateway를 사용하여 Amazon SQS 대기열에 요청을 넣고, AWS Lambda 함수로 데이터를 분석하고, Amazon EMR을 사용하여 Amazon Redshift 클러스터에 결과를 저장합니다.` },
    ],
    answer: ["B"],
    vote: '94% B, 6% D',
    explain: `<p><span class="mark-ok">✅ B</span></p><p>답변 B. 옵션 A는 거의 실시간에 가까운 Firehose일 수 있지만 대상은 RDS이지만 요청은 Datawarehouse(Redshift)입니다.</p>`,
    wrong: `<p><span class="mark-no">❌ D</span> — Kinesis 클라이언트는 라이브러리입니다. 이를 사용하려면 사용자가 Kinesis Client Library로 애플리케이션을 작성해야 합니다. A와 B 모두 애플리케이션이 작성되고 배포되는 방식을 언급하지 않고 "Kinesis 클라이언트를 사용하여 데이터를 분석"한다고 말합니다. 따라서 A와 B는 모두 제외되었습니다. 배포 모델이 요구 사항을 충족하기 위</p>`,
    disc: [{ ans:'B', txt:'답변 B. 옵션 A는 거의 실시간에 가까운 Firehose일 수 있지만 대상은 RDS이지만 요청은 Datawarehouse(Redshift)입니다.' }, { ans:'B', txt:'Answer B. Option A might be close enough, near-real time, which is Firehose, but the target is RDS but the ask is for Datawarehouse (Redshift)' }, { ans:'D', txt:'Kinesis 클라이언트는 라이브러리입니다. 이를 사용하려면 사용자가 Kinesis Client Library로 애플리케이션을 작성해야 합니다. A와 B 모두 애플리케이션이 작성되고 배포되는 방식을 언급하지 않고 "Kinesis 클라이언트를 사용하여 데이터를 분석"한다고 말합니다. 따라서 A와 B는 모두 제외되었습니다. 배포 모델이 요구 사항을 충족하기 위한 질문의 핵심이기 때문입니다. C에는 "Kinesis를 사용하여 Amazon SQS의 데이터를 분석"이라는 잘못된 설명이 있습니다. D는 실행 가능한 솔루션입니다.' }, { ans:'D', txt:'Kinesis client is a library. Users need to write an application with the Kinesis Client Library to use it. Both A and B states “analyze the data with Kinesis clients” without mentioning how the application is written and deployed. So, both A and B are out, cause the deployment model is the key of the question to satisfy the requirement. C has an incorrect statement “analyze the data from Amazon...' }, { ans:'B', txt:'B가 맞습니다. B - Kinesis Data Streams는 실시간 스트리밍 서비스이며 거의 실시간 분석을 제공합니다. 또한 "처리 결과를 데이터 웨어하우스로 전달"이라는 질문에 이 옵션에는 대규모 분석 워크로드를 처리할 수 있는 강력한 데이터 웨어하우징 솔루션인 redshift 클러스터가 있습니다. A - Kinesis Data Firehose는 실시간에 가까운 분석에 적합하지 않으며 데이터 처리 파이프라인에 약간의 지연 시간이 발생할 수 있으므로 정답이 아닙니다. 또한 결과를 Amazon RDS 인스턴스에 저장하면 대량의 게놈 데이터를 처리하고 분석하는 데 필요한 확장성과 유연성이 제공되지 않을 수 있습니다.' }]
  },
  {
    n: 240,
    en: `A solutions architect needs to define a reference architecture for a solution for three-tier applications with web. application, and NoSQL data layers. The reference architecture must meet the following requirements:<br/><br/>•	High availability within an AWS Region<br/>•	Able to fail over in 1 minute to another AWS Region for disaster recovery<br/>•	Provide the most efficient solution while minimizing the impact on the user experience<br/><br/>Which combination of steps will meet these requirements? (Choose three.)`,
    ko: `솔루션 설계자는 웹을 사용하는 3계층 애플리케이션용 솔루션에 대한 참조 아키텍처를 정의해야 합니다. 애플리케이션 및 NoSQL 데이터 계층. 참조 아키텍처는 다음 요구 사항을 충족해야 합니다. <br/><br/>• AWS 리전 내 고가용성 <br/>• 재해 복구를 위해 1분 안에 다른 AWS 리전으로 장애 조치 가능 <br/>• 사용자 경험에 미치는 영향을 최소화하면서 가장 효율적인 솔루션 제공 <br/><br/>어떤 단계를 조합해야 할까요? 이러한 요구 사항을 충족합니까? (3개를 선택하세요.)`,
    type: 'multi', multiCount: 3,
    choices: [
      { k:'A', en:`Use an Amazon Route 53 weighted routing policy set to 100/0 across the two selected Regions. Set Time to Live (TTL) to 1 hour.`, ko:`선택한 두 리전에서 100/0으로 설정된 Amazon Route 53 가중치 라우팅 정책을 사용하십시오. TTL(Time to Live)을 1시간으로 설정합니다.` },
      { k:'B', en:`Use an Amazon Route 53 failover routing policy for failover from the primary Region to the disaster recovery Region. Set Time to Live (TTL) to 30 seconds.`, ko:`기본 지역에서 재해 복구 지역으로의 장애 조치를 위해 Amazon Route 53 장애 조치 라우팅 정책을 사용합니다. TTL(Time to Live)을 30초로 설정합니다.` },
      { k:'C', en:`Use a global table within Amazon DynamoDB so data can be accessed in the two selected Regions.`, ko:`선택한 두 리전에서 데이터에 액세스할 수 있도록 Amazon DynamoDB 내의 글로벌 테이블을 사용합니다.` },
      { k:'D', en:`Back up data from an Amazon DynamoDB table in the primary Region every 60 minutes and then write the data to Amazon S3. Use S3 cross-Region replication to copy the data from the primary Region to the disaster recovery Region. Have a script import the data into DynamoDB in a disaster recovery scenario.`, ko:`60분마다 기본 리전의 Amazon DynamoDB 테이블에서 데이터를 백업한 다음 Amazon S3에 데이터를 씁니다. S3 교차 리전 복제를 사용하여 기본 리전의 데이터를 재해 복구 리전으로 복사합니다. 재해 복구 시나리오에서 스크립트를 통해 데이터를 DynamoDB로 가져오도록 합니다.` },
      { k:'E', en:`Implement a hot standby model using Auto Scaling groups for the web and application layers across multiple Availability Zones in the Regions. Use zonal Reserved Instances for the minimum number of servers and On-Demand Instances for any additional resources.`, ko:`지역의 여러 가용 영역에 걸쳐 웹 및 애플리케이션 계층에 대한 Auto Scaling 그룹을 사용하여 상시 대기 모델을 구현합니다. 최소 서버 수에는 영역 예약 인스턴스를 사용하고 추가 리소스에는 온디맨드 인스턴스를 사용합니다.` },
      { k:'F', en:`Use Auto Scaling groups for the web and application layers across multiple Availability Zones in the Regions. Use Spot Instances for the required resources.`, ko:`리전의 여러 가용 영역에 걸쳐 웹 및 애플리케이션 계층에 Auto Scaling 그룹을 사용합니다. 필요한 리소스에 스팟 인스턴스를 사용하십시오.` },
    ],
    answer: [],
    vote: '92% BCE, 8% ACE',
    explain: ``,
    wrong: `<p><span class="mark-no">❌ A</span> — A - 장애 조치 Rt 53 C - 지역 복제를 관리하는 글로벌 DynamoDB 테이블 E - 예약 및 온디맨드로 지역 간 최소 EC2</p><p><span class="mark-no">❌ B</span> — not sure how these answers are generated, poor quality!
Correct answer - BCE
Hot standby, DynamoDB Global tables, Route53 failover routing policy.</p><p><span class="mark-no">❌ C</span> — A - 장애 조치 Rt 53 C - 지역 복제를 관리하는 글로벌 DynamoDB 테이블 E - 예약 및 온디맨드로 지역 간 최소 EC2</p><p><span class="mark-no">❌ E</span> — A - 장애 조치 Rt 53 C - 지역 복제를 관리하는 글로벌 DynamoDB 테이블 E - 예약 및 온디맨드로 지역 간 최소 EC2</p>`,
    disc: [{ ans:'기원전', txt:'비, 씨, E' }, { ans:'기원전', txt:'확실히 기원전' }, { ans:'B, C, E', txt:'B, C and E' }, { ans:'B, C, E', txt:'BCE for sure' }, { ans:'기원전', txt:'이러한 답변이 어떻게 생성되는지 잘 모르겠습니다. 품질이 좋지 않습니다! 정답 - BCE 상시 대기, DynamoDB 글로벌 테이블, Route53 장애 조치 라우팅 정책.' }]
  }
];
