window.QS_SET33 = [
  {
    n: 321,
    en: `A research company is running daily simulations in the AWS Cloud to meet high demand. The simulations run on several hundred Amazon EC2 instances that are based on Amazon Linux 2. Occasionally, a simulation gets stuck and requires a cloud operations engineer to solve the problem by connecting to an EC2 instance through SSH.<br/><br/>Company policy states that no EC2 instance can use the same SSH key and that all connections must be logged in AWS CloudTrail.<br/><br/>How can a solutions architect meet these requirements?`,
    ko: `한 연구 회사는 높은 수요를 충족하기 위해 AWS 클라우드에서 매일 시뮬레이션을 실행하고 있습니다. 시뮬레이션은 Amazon Linux 2를 기반으로 하는 수백 개의 Amazon EC2 인스턴스에서 실행됩니다. 때때로 시뮬레이션이 중단되고 클라우드 운영 엔지니어가 SSH를 통해 EC2 인스턴스에 연결하여 문제를 해결해야 합니다. <br/><br/>회사 정책에 따르면 EC2 인스턴스는 동일한 SSH 키를 사용할 수 없으며 모든 연결은 AWS CloudTrail에 기록되어야 합니다. <br/><br/>솔루션 설계자는 이러한 요구 사항을 어떻게 충족할 수 있습니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Launch new EC2 instances, and generate an individual SSH key for each instance. Store the SSH key in AWS Secrets Manager. Create a new IAM policy, and attach it to the engineers’ IAM role with an Allow statement for the GetSecretValue action. Instruct the engineers to fetch the SSH key from Secrets Manager when they connect through any SSH client.`, ko:`새로운 EC2 인스턴스를 시작하고 각 인스턴스에 대해 개별 SSH 키를 생성하십시오. AWS Secrets Manager에 SSH 키를 저장합니다. 새 IAM 정책을 생성하고 GetSecretValue 작업에 대한 Allow 문을 사용하여 이를 엔지니어의 IAM 역할에 연결합니다. SSH 클라이언트를 통해 연결할 때 Secrets Manager에서 SSH 키를 가져오도록 엔지니어에게 지시합니다.` },
      { k:'B', en:`Create an AWS Systems Manager document to run commands on EC2 instances to set a new unique SSH key. Create a new IAM policy, and attach it to the engineers’ IAM role with an Allow statement to run Systems Manager documents. Instruct the engineers to run the document to set an SSH key and to connect through any SSH client.`, ko:`EC2 인스턴스에서 명령을 실행하여 새로운 고유 SSH 키를 설정하는 AWS 시스템 관리자 문서를 생성합니다. 새 IAM 정책을 생성하고 이를 엔지니어의 IAM 역할에 연결하여 시스템 관리자 문서를 실행하도록 허용합니다. 엔지니어에게 문서를 실행하여 SSH 키를 설정하고 SSH 클라이언트를 통해 연결하도록 지시하십시오.` },
      { k:'C', en:`Launch new EC2 instances without setting up any SSH key for the instances. Set up EC2 Instance Connect on each instance. Create a new IAM policy, and attach it to the engineers’ IAM role with an Allow statement for the SendSSHPublicKey action. Instruct the engineers to connect to the instance by using a browser-based SSH client from the EC2 console.`, ko:`인스턴스에 대한 SSH 키를 설정하지 않고 새 EC2 인스턴스를 시작합니다. 각 인스턴스에 EC2 Instance Connect를 설정합니다. 새 IAM 정책을 생성하고 SendSSHPublicKey 작업에 대한 Allow 문을 사용하여 이를 엔지니어의 IAM 역할에 연결합니다. EC2 콘솔에서 브라우저 기반 SSH 클라이언트를 사용하여 인스턴스에 연결하도록 엔지니어에게 지시합니다.` },
      { k:'D', en:`Set up AWS Secrets Manager to store the EC2 SSH key. Create a new AWS Lambda function to create a new SSH key and to call AWS Systems Manager Session Manager to set the SSH key on the EC2 instance. Configure Secrets Manager to use the Lambda function for automatic rotation once daily. Instruct the engineers to fetch the SSH key from Secrets Manager when they connect through any SSH client.`, ko:`EC2 SSH 키를 저장하도록 AWS Secrets Manager를 설정합니다. 새 AWS Lambda 함수를 생성하여 새 SSH 키를 생성하고 AWS Systems Manager Session Manager를 호출하여 EC2 인스턴스에 SSH 키를 설정합니다. 매일 한 번씩 자동 교체를 위해 Lambda 함수를 사용하도록 Secrets Manager를 구성합니다. SSH 클라이언트를 통해 연결할 때 Secrets Manager에서 SSH 키를 가져오도록 엔지니어에게 지시합니다.` },
    ],
    answer: ["C"],
    vote: '100% C',
    explain: `<p><span class="mark-ok">✅ C</span></p><p>https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/connect-linux-inst-eic.html</p>`,
    wrong: ``,
    disc: [{ ans:'C', txt:'https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/connect-linux-inst-eic.html' }, { ans:'C', txt:'답변 C는 다음과 같은 이유로 정답입니다. 키워드: "EC2 인스턴스는 동일한 SSH 키를 사용할 수 없습니다." AND "모든 연결은 AWS CloudTrail에 기록되어야 합니다." 1. 임시 SSH 키를 사용하여 EC2 인스턴스 연결, 사용자가 연결할 때마다 일회성 SSH 키 2. EC2 Instance Connect를 통한 사용자 연결은 AWS CloudTrail에 기록됩니다.' }, { ans:'C', txt:'Answer C is correct with the following reasons: The keywords: "no EC2 instance can use the same SSH key" AND " all connections must be logged in AWS CloudTrail." 1. EC2 Instance connect using temporary ssh key, one-time SSH keys each time the user connects 2. User connections via EC2 Instance Connect are logged to AWS CloudTrail' }, { ans:'C', txt:'옵션 C' }, { ans:'C', txt:'Option C' }]
  },
  {
    n: 322,
    en: `A company is migrating mobile banking applications to run on Amazon EC2 instances in a VPC. Backend service applications run in an on-premises data center. The data center has an AWS Direct Connect connection into AWS. The applications that run in the VPC need to resolve DNS requests to an on-premises Active Directory domain that runs in the data center.<br/><br/>Which solution will meet these requirements with the LEAST administrative overhead?`,
    ko: `한 회사가 VPC의 Amazon EC2 인스턴스에서 실행되도록 모바일 뱅킹 애플리케이션을 마이그레이션하고 있습니다. 백엔드 서비스 애플리케이션은 온프레미스 데이터 센터에서 실행됩니다. 데이터 센터에는 AWS에 대한 AWS Direct Connect 연결이 있습니다. VPC에서 실행되는 애플리케이션은 데이터 센터에서 실행되는 온프레미스 Active Directory 도메인에 대한 DNS 요청을 확인해야 합니다. <br/><br/>최소한의 관리 오버헤드로 이러한 요구 사항을 충족하는 솔루션은 무엇입니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Provision a set of EC2 instances across two Availability Zones in the VPC as caching DNS servers to resolve DNS queries from the application servers within the VPC.`, ko:`VPC 내 애플리케이션 서버의 DNS 쿼리를 해결하기 위해 캐싱 DNS 서버로 VPC의 두 가용 영역에 걸쳐 EC2 인스턴스 세트를 프로비저닝합니다.` },
      { k:'B', en:`Provision an Amazon Route 53 private hosted zone. Configure NS records that point to on-premises DNS servers.`, ko:`Amazon Route 53 프라이빗 호스팅 영역을 프로비저닝합니다. 온프레미스 DNS 서버를 가리키는 NS 레코드를 구성합니다.` },
      { k:'C', en:`Create DNS endpoints by using Amazon Route 53 Resolver. Add conditional forwarding rules to resolve DNS namespaces between the on-premises data center and the VPC.`, ko:`Amazon Route 53 Resolver를 사용하여 DNS 엔드포인트를 생성합니다. 온프레미스 데이터 센터와 VPC 간의 DNS 네임스페이스를 확인하기 위한 조건부 전달 규칙을 추가합니다.` },
      { k:'D', en:`Provision a new Active Directory domain controller in the VPC with a bidirectional trust between this new domain and the on-premises Active Directory domain.`, ko:`이 새 도메인과 온프레미스 Active Directory 도메인 간의 양방향 신뢰를 통해 VPC에 새 Active Directory 도메인 컨트롤러를 프로비저닝합니다.` },
    ],
    answer: ["C"],
    vote: '100% C',
    explain: `<p><span class="mark-ok">✅ C</span></p><p>옵션 C</p>`,
    wrong: ``,
    disc: [{ ans:'C', txt:'옵션 C: Amazon Route 53 Resolver > 조건부 전달 EC2를 사용하는 옵션 A보다 유지 관리가 더 낮습니다.' }, { ans:'C', txt:'Option C: Amazon Route 53 Resolver > Conditional Forwarding Lower Maintenance than Option A which using EC2.' }, { ans:'C', txt:'VPC에서 네트워크로 DNS 쿼리를 전달하려면 아웃바운드 엔드포인트를 생성합니다. 참조: https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resolver-forwarding-outbound-queries.html' }, { ans:'C', txt:'https://aws.amazon.com/blogs/security/how-to-set-up-dns-solution-between-on-premise-networks-and-aws-using-aws-directory-service-and-amazon- 경로-53/' }, { ans:'C', txt:'To forward DNS queries from your VPCs to your network, you create an outbound endpoint. reference: https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resolver-forwarding-outbound-queries.html' }]
  },
  {
    n: 323,
    en: `A company processes environmental data. The company has set up sensors to provide a continuous stream of data from different areas in a city. The data is available in JSON format.<br/><br/>The company wants to use an AWS solution to send the data to a database that does not require fixed schemas for storage. The data must be sent in real time.<br/><br/>Which solution will meet these requirements?`,
    ko: `회사에서 환경 데이터를 처리합니다. 이 회사는 도시의 다양한 영역에서 지속적인 데이터 스트림을 제공하기 위해 센서를 설치했습니다. 데이터는 JSON 형식으로 제공됩니다. <br/><br/>회사는 AWS 솔루션을 사용하여 저장을 위해 고정된 스키마가 필요하지 않은 데이터베이스에 데이터를 전송하려고 합니다. 데이터는 실시간으로 전송되어야 합니다. <br/><br/>어떤 솔루션이 이러한 요구 사항을 충족합니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Use Amazon Kinesis Data Firehose to send the data to Amazon Redshift.`, ko:`Amazon Kinesis Data Firehose를 사용하여 Amazon Redshift로 데이터를 보냅니다.` },
      { k:'B', en:`Use Amazon Kinesis Data Streams to send the data to Amazon DynamoDB.`, ko:`Amazon Kinesis Data Streams를 사용하여 Amazon DynamoDB로 데이터를 보냅니다.` },
      { k:'C', en:`Use Amazon Managed Streaming for Apache Kafka (Amazon MSK) to send the data to Amazon Aurora.`, ko:`Amazon Managed Streaming for Apache Kafka(Amazon MSK)를 사용하여 데이터를 Amazon Aurora로 보냅니다.` },
      { k:'D', en:`Use Amazon Kinesis Data Firehose to send the data to Amazon Keyspaces (for Apache Cassandra).`, ko:`Amazon Kinesis Data Firehose를 사용하여 Amazon Keyspaces(Apache Cassandra용)로 데이터를 보냅니다.` },
    ],
    answer: ["B"],
    vote: '100% B',
    explain: `<p><span class="mark-ok">✅ B</span></p><p>Kinesis Data 스트림은 실시간입니다. Firehose는 거의 실시간입니다. DynamDB는 관계형 DB가 아니며 테이블에 고정 스키마를 적용하지 않습니다. 답은 B이다</p>`,
    wrong: ``,
    disc: [{ ans:'B', txt:'Kinesis Data 스트림은 실시간입니다. Firehose는 거의 실시간입니다. DynamDB는 관계형 DB가 아니며 테이블에 고정 스키마를 적용하지 않습니다. 답은 B이다' }, { ans:'B', txt:'Kinesis Data streams is real-time. Firehose is near real-time. DynamDB is not a relational DB and does not enforce fixed schemas on its tables. Answer is B' }, { ans:'B', txt:'올바른 B' }, { ans:'B', txt:'DynamoDB에 json 형식 로드' }, { ans:'B', txt:'Correct B' }]
  },
  {
    n: 324,
    en: `A company is migrating a legacy application from an on-premises data center to AWS. The application uses MongoDB as a key-value database. According to the company's technical guidelines, all Amazon EC2 instances must be hosted in a private subnet without an internet connection. In addition, all connectivity between applications and databases must be encrypted. The database must be able to scale based on demand.<br/><br/>Which solution will meet these requirements?`,
    ko: `회사는 온프레미스 데이터 센터의 레거시 애플리케이션을 AWS로 마이그레이션하고 있습니다. 애플리케이션은 MongoDB를 키-값 데이터베이스로 사용합니다. 회사의 기술 지침에 따라 모든 Amazon EC2 인스턴스는 인터넷 연결 없이 프라이빗 서브넷에서 호스팅되어야 합니다. 또한 애플리케이션과 데이터베이스 간의 모든 연결은 암호화되어야 합니다. 데이터베이스는 수요에 따라 확장할 수 있어야 합니다. <br/><br/>어떤 솔루션이 이러한 요구 사항을 충족합니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Create new Amazon DocumentDB (with MongoDB compatibility) tables for the application with Provisioned IOPS volumes. Use the instance endpoint to connect to Amazon DocumentDB.`, ko:`프로비저닝된 IOPS 볼륨이 있는 애플리케이션을 위한 새로운 Amazon DocumentDB(MongoDB 호환) 테이블을 생성합니다. 인스턴스 엔드포인트를 사용하여 Amazon DocumentDB에 연결합니다.` },
      { k:'B', en:`Create new Amazon DynamoDB tables for the application with on-demand capacity. Use a gateway VPC endpoint for DynamoDB to connect to the DynamoDB tables.`, ko:`온디맨드 용량을 갖춘 애플리케이션을 위한 새로운 Amazon DynamoDB 테이블을 생성합니다. DynamoDB용 게이트웨이 VPC 엔드포인트를 사용하여 DynamoDB 테이블에 연결합니다.` },
      { k:'C', en:`Create new Amazon DynamoDB tables for the application with on-demand capacity. Use an interface VPC endpoint for DynamoDB to connect to the DynamoDB tables.`, ko:`온디맨드 용량을 갖춘 애플리케이션을 위한 새로운 Amazon DynamoDB 테이블을 생성합니다. DynamoDB용 인터페이스 VPC 엔드포인트를 사용하여 DynamoDB 테이블에 연결합니다.` },
      { k:'D', en:`Create new Amazon DocumentDB (with MongoDB compatibility) tables for the application with Provisioned IOPS volumes. Use the cluster endpoint to connect to Amazon DocumentDB.`, ko:`프로비저닝된 IOPS 볼륨이 있는 애플리케이션을 위한 새로운 Amazon DocumentDB(MongoDB 호환) 테이블을 생성합니다. 클러스터 엔드포인트를 사용하여 Amazon DocumentDB에 연결합니다.` },
    ],
    answer: ["B"],
    vote: '53% B, 37% D, 10% C',
    explain: `<p><span class="mark-ok">✅ B</span></p><p>B: MongoDB가 키-값 저장소로 사용되는 경우 게이트웨이 엔드포인트는 간단한 키-값 저장소인 DynamoDB에 연결하는 방법입니다.</p>`,
    wrong: `<p><span class="mark-no">❌ C</span> — DocumentDB는 DynamoDB가 아닙니다. 게이트웨이 끝점은 DocumentDB를 지원하지 않습니다.</p><p><span class="mark-no">❌ D</span> — D가 올바른 옵션입니다. 인스턴스 엔드포인트는 특정 인스턴스(기본 또는 복제본)를 연결하기 위한 것이며 권장되지 않습니다.</p>`,
    disc: [{ ans:'D', txt:'D가 올바른 옵션입니다. 인스턴스 엔드포인트는 특정 인스턴스(기본 또는 복제본)를 연결하기 위한 것이며 권장되지 않습니다.' }, { ans:'D', txt:'D is right option. Instance endpoint is for connecting specific instance (primary or replica) and not recommended.' }, { ans:'B', txt:'정답은 B입니다. 질문에는 "데이터베이스는 수요에 따라 확장할 수 있어야 합니다"라고 나와 있습니다. 따라서 이 솔루션은 프라이빗 서브넷 내에서 작동하는 동안 요청에 따른 확장성 요구 사항을 충족하여 애플리케이션과 데이터베이스 간의 암호화된 연결을 보장합니다. DynamoDB의 온디맨드 용량 프로비저닝을 활용합니다.' }, { ans:'B', txt:'The correct answer is B. The question states "The database must be able to scale based on demand" Therefore, this solution would meet the need for scalability on demand while operating within a private subnet, ensuring encrypted connectivity between the application and the database, and utilizing DynamoDB\'s on-demand capacity provisioning.' }, { ans:'D', txt:'답 D' }]
  },
  {
    n: 325,
    en: `A company is running an application on Amazon EC2 instances in the AWS Cloud. The application is using a MongoDB database with a replica set as its data tier. The MongoDB database is installed on systems in the company’s on-premises data center and is accessible through an AWS Direct Connect connection to the data center environment.<br/><br/>A solutions architect must migrate the on-premises MongoDB database to Amazon DocumentDB (with MongoDB compatibility).<br/><br/>Which strategy should the solutions architect choose to perform this migration?`,
    ko: `한 회사가 AWS 클라우드의 Amazon EC2 인스턴스에서 애플리케이션을 실행하고 있습니다. 애플리케이션은 복제본 세트를 데이터 계층으로 사용하는 MongoDB 데이터베이스를 사용하고 있습니다. MongoDB 데이터베이스는 회사의 온프레미스 데이터 센터 시스템에 설치되며 데이터 센터 환경에 대한 AWS Direct Connect 연결을 통해 액세스할 수 있습니다. <br/><br/>솔루션 설계자는 온프레미스 MongoDB 데이터베이스를 Amazon DocumentDB(MongoDB와 호환 가능)로 마이그레이션해야 합니다. <br/><br/>솔루션 설계자는 이 마이그레이션을 수행하기 위해 어떤 전략을 선택해야 합니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Create a fleet of EC2 instances. Install MongoDB Community Edition on the EC2 instances, and create a database. Configure continuous synchronous replication with the database that is running in the on-premises data center.`, ko:`EC2 인스턴스 집합을 생성합니다. EC2 인스턴스에 MongoDB Community Edition을 설치하고 데이터베이스를 생성합니다. 온프레미스 데이터 센터에서 실행 중인 데이터베이스를 사용하여 연속 동기 복제를 구성합니다.` },
      { k:'B', en:`Create an AWS Database Migration Service (AWS DMS) replication instance. Create a source endpoint for the on-premises MongoDB database by using change data capture (CDC). Create a target endpoint for the Amazon DocumentDB database. Create and run a DMS migration task.`, ko:`AWS Database Migration Service(AWS DMS) 복제 인스턴스를 생성합니다. 변경 데이터 캡처(CDC)를 사용하여 온프레미스 MongoDB 데이터베이스에 대한 소스 엔드포인트를 만듭니다. Amazon DocumentDB 데이터베이스에 대한 대상 엔드포인트를 생성합니다. DMS 마이그레이션 작업을 생성하고 실행합니다.` },
      { k:'C', en:`Create a data migration pipeline by using AWS Data Pipeline. Define data nodes for the on-premises MongoDB database and the Amazon DocumentDB database. Create a scheduled task to run the data pipeline.`, ko:`AWS Data Pipeline을 사용하여 데이터 마이그레이션 파이프라인을 생성합니다. 온프레미스 MongoDB 데이터베이스 및 Amazon DocumentDB 데이터베이스에 대한 데이터 노드를 정의합니다. 데이터 파이프라인을 실행하기 위한 예약된 작업을 만듭니다.` },
      { k:'D', en:`Create a source endpoint for the on-premises MongoDB database by using AWS Glue crawlers. Configure continuous asynchronous replication between the MongoDB database and the Amazon DocumentDB database.`, ko:`AWS Glue 크롤러를 사용하여 온프레미스 MongoDB 데이터베이스에 대한 소스 엔드포인트를 생성합니다. MongoDB 데이터베이스와 Amazon DocumentDB 데이터베이스 간의 연속 비동기 복제를 구성합니다.` },
    ],
    answer: ["B"],
    vote: '100% B',
    explain: `<p><span class="mark-ok">✅ B</span></p><p>옵션 B</p>`,
    wrong: ``,
    disc: [{ ans:'B', txt:'B가 올바른 선택입니다.' }, { ans:'B', txt:'B is right option.' }, { ans:'B', txt:'B는 간단하다. DMS를 사용하여 AWS의 Mongo DB 호환 문서 DB 인스턴스로 마이그레이션합니다. 옳은!' }, { ans:'B', txt:'B가 맞아요' }, { ans:'B', txt:'B is straightforward. Use DMS to migrate to a Mongo DB Compatible Document DB instance on AWS. Correct!' }]
  },
  {
    n: 326,
    en: `A company is rearchitecting its applications to run on AWS. The company’s infrastructure includes multiple Amazon EC2 instances. The company's development team needs different levels of access. The company wants to implement a policy that requires all Windows EC2 instances to be joined to an Active Directory domain on AWS. The company also wants to implement enhanced security processes such as multi-factor authentication (MFA). The company wants to use managed AWS services wherever possible.<br/><br/>Which solution will meet these requirements?`,
    ko: `한 회사가 AWS에서 실행되도록 애플리케이션을 재설계하고 있습니다. 회사의 인프라에는 여러 Amazon EC2 인스턴스가 포함되어 있습니다. 회사의 개발팀에는 다양한 수준의 액세스가 필요합니다. 회사는 모든 Windows EC2 인스턴스를 AWS의 Active Directory 도메인에 조인하도록 요구하는 정책을 구현하려고 합니다. 또한 회사는 다중 요소 인증(MFA)과 같은 향상된 보안 프로세스를 구현하려고 합니다. 회사는 가능한 한 관리형 AWS 서비스를 사용하기를 원합니다. <br/><br/>어떤 솔루션이 이러한 요구 사항을 충족합니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Create an AWS Directory Service for Microsoft Active Directory implementation. Launch an Amazon Workspace. Connect to and use the Workspace for domain security configuration tasks.`, ko:`Microsoft Active Directory 구현을 위한 AWS 디렉터리 서비스를 생성합니다. Amazon Workspace를 시작하십시오. 도메인 보안 구성 작업을 위해 Workspace에 연결하고 사용합니다.` },
      { k:'B', en:`Create an AWS Directory Service for Microsoft Active Directory implementation. Launch an EC2 instance. Connect to and use the EC2 instance for domain security configuration tasks.`, ko:`Microsoft Active Directory 구현을 위한 AWS 디렉터리 서비스를 생성합니다. EC2 인스턴스를 시작합니다. 도메인 보안 구성 작업을 위해 EC2 인스턴스에 연결하고 사용합니다.` },
      { k:'C', en:`Create an AWS Directory Service Simple AD implementation. Launch an EC2 instance. Connect to and use the EC2 instance for domain security configuration tasks.`, ko:`AWS Directory Service Simple AD 구현을 생성합니다. EC2 인스턴스를 시작합니다. 도메인 보안 구성 작업을 위해 EC2 인스턴스에 연결하고 사용합니다.` },
      { k:'D', en:`Create an AWS Directory Service Simple AD implementation. Launch an Amazon Workspace. Connect to and use the Workspace for domain security configuration tasks.`, ko:`AWS Directory Service Simple AD 구현을 생성합니다. Amazon Workspace를 시작하십시오. 도메인 보안 구성 작업을 위해 Workspace에 연결하고 사용합니다.` },
    ],
    answer: ["B"],
    vote: '59% B, 41% A',
    explain: `<p><span class="mark-ok">✅ B</span></p><p>EC2가 권장되는 다음 링크에 따라 B도 지원합니다: https://docs.aws.amazon.com/workspaces/latest/adminguide/directory_administration.html</p>`,
    wrong: `<p><span class="mark-no">❌ A</span> — A - 맞습니다.</p>`,
    disc: [{ ans:'B', txt:'EC2가 권장되는 다음 링크에 따라 B도 지원합니다: https://docs.aws.amazon.com/workspaces/latest/adminguide/directory_administration.html' }, { ans:'B', txt:'I support B as well per this link where EC2 is recommended: https://docs.aws.amazon.com/workspaces/latest/adminguide/directory_administration.html' }, { ans:'B', txt:'B가 맞습니다. 질문에는 "Windows 사용자 데스크톱"이 아닌 "Windows EC2"가 언급되어 있습니다. 어쩌면 Windows EC2가 Windows Server일 수도 있습니다.' }, { ans:'B', txt:'B is correct. The question mention "Windows EC2", no "Windows user desktops". Maybe the Windows EC2 can be Windows Servers.' }, { ans:'B', txt:'나는 B에 투표할 것입니다. Windows ec2 인스턴스가 "사용자 데스크톱"이라는 내용은 어디에도 없습니다. A의 경우라면 그렇습니다.' }]
  },
  {
    n: 327,
    en: `A company wants to migrate its on-premises application to AWS. The database for the application stores structured product data and temporary user session data. The company needs to decouple the product data from the user session data. The company also needs to implement replication in another AWS Region for disaster recovery.<br/><br/>Which solution will meet these requirements with the HIGHEST performance?`,
    ko: `회사에서 온프레미스 애플리케이션을 AWS로 마이그레이션하려고 합니다. 애플리케이션용 데이터베이스는 구조화된 제품 데이터와 임시 사용자 세션 데이터를 저장합니다. 회사는 사용자 세션 데이터에서 제품 데이터를 분리해야 합니다. 또한 회사는 재해 복구를 위해 다른 AWS 리전에 복제를 구현해야 합니다. <br/><br/>최고의 성능으로 이러한 요구 사항을 충족하는 솔루션은 무엇입니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Create an Amazon RDS DB instance with separate schemas to host the product data and the user session data. Configure a read replica for the DB instance in another Region.`, ko:`제품 데이터와 사용자 세션 데이터를 호스팅하기 위해 별도의 스키마를 사용하여 Amazon RDS DB 인스턴스를 생성합니다. 다른 리전의 DB 인스턴스에 대한 읽기 전용 복제본을 구성합니다.` },
      { k:'B', en:`Create an Amazon RDS DB instance to host the product data. Configure a read replica for the DB instance in another Region. Create a global datastore in Amazon ElastiCache for Memcached to host the user session data.`, ko:`제품 데이터를 호스팅할 Amazon RDS DB 인스턴스를 생성합니다. 다른 리전의 DB 인스턴스에 대한 읽기 전용 복제본을 구성합니다. 사용자 세션 데이터를 호스팅하기 위해 Amazon ElastiCache for Memcached에 글로벌 데이터 스토어를 생성합니다.` },
      { k:'C', en:`Create two Amazon DynamoDB global tables. Use one global table to host the product data. Use the other global table to host the user session data. Use DynamoDB Accelerator (DAX) for caching.`, ko:`두 개의 Amazon DynamoDB 글로벌 테이블을 생성합니다. 하나의 글로벌 테이블을 사용하여 제품 데이터를 호스팅합니다. 다른 전역 테이블을 사용하여 사용자 세션 데이터를 호스팅합니다. 캐싱에는 DynamoDB Accelerator(DAX)를 사용합니다.` },
      { k:'D', en:`Create an Amazon RDS DB instance to host the product data. Configure a read replica for the DB instance in another Region. Create an Amazon DynamoDB global table to host the user session data.`, ko:`제품 데이터를 호스팅할 Amazon RDS DB 인스턴스를 생성합니다. 다른 리전의 DB 인스턴스에 대한 읽기 전용 복제본을 구성합니다. 사용자 세션 데이터를 호스팅할 Amazon DynamoDB 전역 테이블을 생성합니다.` },
    ],
    answer: ["D"],
    vote: '53% D, 31% C, 16% B',
    explain: `<p><span class="mark-ok">✅ D</span></p><p>구조화된 데이터 = RDS</p>`,
    wrong: `<p><span class="mark-no">❌ B</span> — 저는 "2개의 DynamoDB 전역 테이블 생성"이 마음에 들지 않았지만, 최고 성능에 대한 질문이 나오자 마자 DAX를 가리키게 되었습니다. C가 정답입니다.</p><p><span class="mark-no">❌ C</span> — C - DynamoDB는 구조화된 데이터, 반구조화된 데이터, 구조화되지 않은 데이터용입니다. 따라서 제품 데이터도 보관할 수 있습니다. 실제로 많은 전자상거래 상점에서는 DynamoDB를 사용하여 제품 카탈로그를 저장합니다. 제품 데이터에 대해 DynamoDB를 제외하는 질문은 없습니다. C에는 DAX와 캐싱이 있으므로 캐싱이 없고 동일한 지역에 읽기 복</p>`,
    disc: [{ ans:'C', txt:'C - DynamoDB는 구조화된 데이터, 반구조화된 데이터, 구조화되지 않은 데이터용입니다. 따라서 제품 데이터도 보관할 수 있습니다. 실제로 많은 전자상거래 상점에서는 DynamoDB를 사용하여 제품 카탈로그를 저장합니다. 제품 데이터에 대해 DynamoDB를 제외하는 질문은 없습니다. C에는 DAX와 캐싱이 있으므로 캐싱이 없고 동일한 지역에 읽기 복제본도 없는 D보다 확실히 성능이 더 높습니다.' }, { ans:'C', txt:'C - DynamoDB is for structured, semi-structured and unstructured data. So it can also hold the product data. Indeed many e-commerce shops use DynamoDB to save the product catalogue. There is nothing in the questin that would exclude DynamoDB for the product data. C has caching with DAX so it definitely has a higher performance than D which does not have caching and even no read replica in the s...' }, { ans:'D', txt:'구조화된 데이터 = RDS' }, { ans:'D', txt:'Structured Data = RDS' }, { ans:'D', txt:'따라서 애플리케이션용 데이터베이스는 구조화된 제품 데이터와 임시 사용자 세션 데이터를 저장합니다. 옵션 D' }]
  },
  {
    n: 328,
    en: `A company orchestrates a multi-account structure on AWS by using AWS Control Tower. The company is using AWS Organizations, AWS Config, and AWS Trusted Advisor. The company has a specific OU for development accounts that developers use to experiment on AWS. The company has hundreds of developers, and each developer has an individual development account.<br/><br/>The company wants to optimize costs in these development accounts. Amazon EC2 instances and Amazon RDS instances in these accounts must be burstable. The company wants to disallow the use of other services that are not relevant.<br/><br/>What should a solutions architect recommend to meet these requirements?`,
    ko: `회사는 AWS Control Tower를 사용하여 AWS에서 다중 계정 구조를 조정합니다. 회사는 AWS Organizations, AWS Config 및 AWS Trusted Advisor를 사용하고 있습니다. 회사에는 개발자가 AWS에서 실험하는 데 사용하는 개발 계정에 대한 특정 OU가 있습니다. 회사에는 수백 명의 개발자가 있으며 각 개발자는 개별 개발 계정을 가지고 있습니다. <br/><br/>회사는 이러한 개발 계정의 비용을 최적화하려고 합니다. 이러한 계정의 Amazon EC2 인스턴스와 Amazon RDS 인스턴스는 버스트 가능해야 합니다. 회사는 관련성이 없는 기타 서비스의 이용을 거부하고자 합니다. <br/><br/>솔루션 설계자는 이러한 요구 사항을 충족하기 위해 무엇을 권장해야 합니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Create a custom SCP in AWS Organizations to allow the deployment of only burstable instances and to disallow services that are not relevant. Apply the SCP to the development OU.`, ko:`AWS Organizations에서 사용자 지정 SCP를 생성하여 버스트 가능한 인스턴스의 배포만 허용하고 관련 없는 서비스는 허용하지 않습니다. 개발 OU에 SCP를 적용합니다.` },
      { k:'B', en:`Create a custom detective control (guardrail) in AWS Control Tower. Configure the control (guardrail) to allow the deployment of only burstable instances and to disallow services that are not relevant. Apply the control (guardrail) to the development OU.`, ko:`AWS Control Tower에서 사용자 지정 탐지 제어(가드레일)를 생성합니다. 버스트 가능한 인스턴스의 배포만 허용하고 관련 없는 서비스는 허용하지 않도록 제어(가드레일)를 구성합니다. 개발 OU에 제어(가드레일)를 적용합니다.` },
      { k:'C', en:`Create a custom preventive control (guardrail) in AWS Control Tower. Configure the control (guardrail) to allow the deployment of only burstable instances and to disallow services that are not relevant. Apply the control (guardrail) to the development OU.`, ko:`AWS Control Tower에서 사용자 지정 예방 제어(가드레일)를 생성합니다. 버스트 가능한 인스턴스의 배포만 허용하고 관련 없는 서비스는 허용하지 않도록 제어(가드레일)를 구성합니다. 개발 OU에 제어(가드레일)를 적용합니다.` },
      { k:'D', en:`Create an AWS Config rule in the AWS Control Tower account. Configure the AWS Config rule to allow the deployment of only burstable instances and to disallow services that are not relevant. Deploy the AWS Config rule to the development OU by using AWS CloudFormation StackSets.`, ko:`AWS Control Tower 계정에서 AWS Config 규칙을 생성합니다. 버스트 가능한 인스턴스의 배포만 허용하고 관련 없는 서비스는 허용하지 않도록 AWS Config 규칙을 구성합니다. AWS CloudFormation StackSets를 사용하여 개발 OU에 AWS Config 규칙을 배포합니다.` },
    ],
    answer: ["C"],
    vote: '57% C, 43% A',
    explain: `<p><span class="mark-ok">✅ C</span></p><p>itexamstest.com 토론 없음 c :)</p>`,
    wrong: `<p><span class="mark-no">❌ A</span> — 사용자 지정 SCP를 개발 OU에 적용하면 해당 OU 내의 모든 계정에 제한이 적용되어 개발자가 허용된 리소스 및 서비스만 사용하도록 효과적으로 제한됩니다. AWS Control Tower 가드레일(옵션 B 및 C)은 세분화된 서비스 수준 제한보다는 주로 거버넌스 및 규정 준수 목적으로 사용되기 때문에 이 경우 이상적인 솔루션이 아닙니다.</p>`,
    disc: [{ ans:'C', txt:'itexamstest.com 토론 없음 c :)' }, { ans:'C', txt:'itexamstest.com no disscusion c :)' }, { ans:'C', txt:'조직에서 Control Tower가 관리하는 OU로 SCP를 변경하는 것은 드리프트를 유발하므로 적절하지 않다고 생각합니다. 권장되는 방법은 예방으로 설정하는 것입니다. https://docs.aws.amazon.com/controltower/latest/userguide/controls.html https://docs.aws.amazon.com/controltower/latest/userguide/governance-drift.html' }, { ans:'C', txt:'I don\'t think it\'s appropriate to make SCP changes from Organization to an OU managed by Control Tower, as it will cause drift. The recommended method is to set it as Preventive. https://docs.aws.amazon.com/controltower/latest/userguide/controls.html https://docs.aws.amazon.com/controltower/latest/userguide/governance-drift.html' }, { ans:'A', txt:'사용자 지정 SCP를 개발 OU에 적용하면 해당 OU 내의 모든 계정에 제한이 적용되어 개발자가 허용된 리소스 및 서비스만 사용하도록 효과적으로 제한됩니다. AWS Control Tower 가드레일(옵션 B 및 C)은 세분화된 서비스 수준 제한보다는 주로 거버넌스 및 규정 준수 목적으로 사용되기 때문에 이 경우 이상적인 솔루션이 아닙니다.' }]
  },
  {
    n: 329,
    en: `A financial services company runs a complex, multi-tier application on Amazon EC2 instances and AWS Lambda functions. The application stores temporary data in Amazon S3. The S3 objects are valid for only 45 minutes and are deleted after 24 hours.<br/><br/>The company deploys each version of the application by launching an AWS CloudFormation stack. The stack creates all resources that are required to run the application. When the company deploys and validates a new application version, the company deletes the CloudFormation stack of the old version.<br/><br/>The company recently tried to delete the CloudFormation stack of an old application version, but the operation failed. An analysis shows that CloudFormation failed to delete an existing S3 bucket. A solutions architect needs to resolve this issue without making major changes to the application's architecture.<br/><br/>Which solution meets these requirements?`,
    ko: `금융 서비스 회사는 Amazon EC2 인스턴스 및 AWS Lambda 함수에서 복잡한 다중 계층 애플리케이션을 실행합니다. 애플리케이션은 Amazon S3에 임시 데이터를 저장합니다. S3 객체는 45분 동안만 유효하며 24시간 후에 삭제됩니다. <br/><br/>회사는 AWS CloudFormation 스택을 시작하여 애플리케이션의 각 버전을 배포합니다. 스택은 애플리케이션을 실행하는 데 필요한 모든 리소스를 생성합니다. 회사가 새 애플리케이션 버전을 배포하고 검증할 때 회사는 이전 버전의 CloudFormation 스택을 삭제합니다. <br/><br/>회사는 최근 이전 애플리케이션 버전의 CloudFormation 스택을 삭제하려고 시도했지만 작업이 실패했습니다. 분석에 따르면 CloudFormation이 기존 S3 버킷을 삭제하지 못한 것으로 나타났습니다. 솔루션 설계자는 애플리케이션 아키텍처를 크게 변경하지 않고 이 문제를 해결해야 합니다. <br/><br/>이러한 요구 사항을 충족하는 솔루션은 무엇입니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Implement a Lambda function that deletes all files from a given S3 bucket. Integrate this Lambda function as a custom resource into the CloudFormation stack. Ensure that the custom resource has a DependsOn attribute that points to the S3 bucket's resource.`, ko:`특정 S3 버킷에서 모든 파일을 삭제하는 Lambda 함수를 구현합니다. 이 Lambda 함수를 CloudFormation 스택에 사용자 지정 리소스로 통합합니다. 사용자 지정 리소스에 S3 버킷의 리소스를 가리키는 DoesOn 속성이 있는지 확인하세요.` },
      { k:'B', en:`Modify the CloudFormation template to provision an Amazon Elastic File System (Amazon EFS) file system to store the temporary files there instead of in Amazon S3. Configure the Lambda functions to run in the same VPC as the file system. Mount the file system to the EC2 instances and Lambda functions.`, ko:`Amazon Elastic File System(Amazon EFS) 파일 시스템을 프로비저닝하여 Amazon S3 대신 임시 파일을 저장하도록 CloudFormation 템플릿을 수정합니다. 파일 시스템과 동일한 VPC에서 실행되도록 Lambda 함수를 구성합니다. 파일 시스템을 EC2 인스턴스 및 Lambda 함수에 탑재합니다.` },
      { k:'C', en:`Modify the CloudF ormation stack to create an S3 Lifecycle rule that expires all objects 45 minutes after creation. Add a DependsOn attribute that points to the S3 bucket’s resource.`, ko:`CloudF 구성 스택을 수정하여 생성 후 45분 후에 모든 객체가 만료되는 S3 수명 주기 규칙을 생성합니다. S3 버킷의 리소스를 가리키는 DoesOn 속성을 추가합니다.` },
      { k:'D', en:`Modify the CloudFormation stack to attach a DeletionPolicy attribute with a value of Delete to the S3 bucket.`, ko:`CloudFormation 스택을 수정하여 값이 삭제된 DeletionPolicy 속성을 S3 버킷에 연결합니다.` },
    ],
    answer: ["A"],
    vote: '92% A, 8% D',
    explain: `<p><span class="mark-ok">✅ A</span></p><p>DeletionPolicy를 사용하면 버킷을 유지하거나 삭제할 수만 있지만 버킷이 비어 있지 않으면 버킷을 삭제할 수 없으므로 A여야 합니다. 이 경우 더 좋은 방법은 람다 함수를 사용자 지정 리소스로 생성하여 삭제하기 전에 버킷을 정리하는 것입니다. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html https://awstut.com/en/2022/05/08/create-and-delete-s3-object -by-cfn-custom-resource-en/</p>`,
    wrong: `<p><span class="mark-no">❌ D</span> — 확실히 D</p>`,
    disc: [{ ans:'A', txt:'DeletionPolicy를 사용하면 버킷을 유지하거나 삭제할 수만 있지만 버킷이 비어 있지 않으면 버킷을 삭제할 수 없으므로 A여야 합니다. 이 경우 더 좋은 방법은 람다 함수를 사용자 지정 리소스로 생성하여 삭제하기 전에 버킷을 정리하는 것입니다. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html https://awstut.com/en/2022/05/08/create-and-delete-s3-object -by-cfn-custom-resource-en/' }, { ans:'A', txt:'It should be A, becase with DeletionPolicy you can only keep or delete bucket, but bucket can\'t be deleted if it is not empty. So better way in that case - to create a lambda function as a custom resource, that will clean bucket before deletion. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html https://awstut.com/en/2022/05/08/create-and-delete-s3-...' }, { ans:'A', txt:'A 왜냐하면 HunkyBunky라는 이름을 사용하는 사람은 누구나 자신이 말하는 내용을 알고 있어야 하기 때문입니다.' }, { ans:'A', txt:'대답은 A입니다. S3 버킷은 비어 있지 않으면 삭제할 수 없습니다. 버킷을 삭제할 수 있도록 버킷을 비우는 Lambda 함수를 생성합니다.' }, { ans:'A', txt:'A because anyone who goes by the name of HunkyBunky must know what they are talking about' }]
  },
  {
    n: 330,
    en: `A company has developed a mobile game. The backend for the game runs on several virtual machines located in an on-premises data center. The business logic is exposed using a REST API with multiple functions. Player session data is stored in central file storage. Backend services use different API keys for throttling and to distinguish between live and test traffic.<br/><br/>The load on the game backend varies throughout the day. During peak hours, the server capacity is not sufficient. There are also latency issues when fetching player session data. Management has asked a solutions architect to present a cloud architecture that can handle the game’s varying load and provide low-latency data access. The API model should not be changed.<br/><br/>Which solution meets these requirements?`,
    ko: `한 회사에서 모바일 게임을 개발했습니다. 게임의 백엔드는 온프레미스 데이터 센터에 있는 여러 가상 머신에서 실행됩니다. 비즈니스 로직은 여러 기능이 포함된 REST API를 사용하여 노출됩니다. 플레이어 세션 데이터는 중앙 파일 저장소에 저장됩니다. 백엔드 서비스는 조절을 위해 그리고 라이브 트래픽과 테스트 트래픽을 구별하기 위해 다양한 API 키를 사용합니다. <br/><br/>게임 백엔드의 부하는 하루 종일 달라집니다. 피크 시간대에는 서버 용량이 충분하지 않습니다. 플레이어 세션 데이터를 가져올 때 지연 시간 문제도 있습니다. 경영진은 솔루션 설계자에게 게임의 다양한 로드를 처리하고 대기 시간이 짧은 데이터 액세스를 제공할 수 있는 클라우드 아키텍처를 제시하도록 요청했습니다. API 모델은 변경되어서는 안 됩니다. <br/><br/>이러한 요구 사항을 충족하는 솔루션은 무엇입니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Implement the REST API using a Network Load Balancer (NLB). Run the business logic on an Amazon EC2 instance behind the NLB. Store player session data in Amazon Aurora Serverless.`, ko:`NLB(Network Load Balancer)를 사용하여 REST API를 구현합니다. NLB 뒤의 Amazon EC2 인스턴스에서 비즈니스 로직을 실행합니다. Amazon Aurora Serverless에 플레이어 세션 데이터를 저장합니다.` },
      { k:'B', en:`Implement the REST API using an Application Load Balancer (ALB). Run the business logic in AWS Lambda. Store player session data in Amazon DynamoDB with on-demand capacity.`, ko:`ALB(Application Load Balancer)를 사용하여 REST API를 구현합니다. AWS Lambda에서 비즈니스 로직을 실행합니다. 온디맨드 용량으로 Amazon DynamoDB에 플레이어 세션 데이터를 저장합니다.` },
      { k:'C', en:`Implement the REST API using Amazon API Gateway. Run the business logic in AWS Lambda. Store player session data in Amazon DynamoDB with on-demand capacity.`, ko:`Amazon API Gateway를 사용하여 REST API를 구현합니다. AWS Lambda에서 비즈니스 로직을 실행합니다. 온디맨드 용량으로 Amazon DynamoDB에 플레이어 세션 데이터를 저장합니다.` },
      { k:'D', en:`Implement the REST API using AWS AppSync. Run the business logic in AWS Lambda. Store player session data in Amazon Aurora Serverless.`, ko:`AWS AppSync를 사용하여 REST API를 구현합니다. AWS Lambda에서 비즈니스 로직을 실행합니다. Amazon Aurora Serverless에 플레이어 세션 데이터를 저장합니다.` },
    ],
    answer: ["C"],
    vote: '100% C',
    explain: `<p><span class="mark-ok">✅ C</span></p><p>옵션 C</p>`,
    wrong: ``,
    disc: [{ ans:'C', txt:'C가 정답입니다. APIGW는 다양한 로드를 효율적으로 처리하고 자동으로 확장할 수 있으므로 REST API를 노출하는 데 이상적인 선택입니다. API Gateway는 또한 이 솔루션의 비즈니스 로직에 사용되는 AWS Lambda와 원활하게 통합됩니다. 이 설정을 사용하면 관리가 쉽고 수동 개입 없이 트래픽 급증을 처리할 수 있습니다.' }, { ans:'C', txt:'C 확실히요' }, { ans:'C', txt:'C is the right Answer: APIGW is the ideal choice for exposing the REST API because it can handle varying loads efficiently and scale automatically. API Gateway also integrates seamlessly with AWS Lambda, which is used for the business logic in this solution. This setup allows for easy management and can handle peaks in traffic without manual intervention.' }, { ans:'C', txt:'C for sure' }, { ans:'C', txt:'옵션 C' }]
  }
];
