window.QS_SET18 = [
  {
    n: 171,
    en: `A company uses an AWS CodeCommit repository. The company must store a backup copy of the data that is in the repository in a second AWS Region.<br/><br/>Which solution will meet these requirements?`,
    ko: `회사는 AWS CodeCommit 리포지토리를 사용합니다. 회사는 두 번째 AWS 지역의 리포지토리에 있는 데이터의 백업 복사본을 저장해야 합니다.<br/><br/>이러한 요구 사항을 충족하는 솔루션은 무엇입니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Configure AWS Elastic Disaster Recovery to replicate the CodeCommit repository data to the second Region.`, ko:`CodeCommit 리포지토리 데이터를 두 번째 리전에 복제하도록 AWS Elastic Disaster Recovery를 구성합니다.` },
      { k:'B', en:`Use AWS Backup to back up the CodeCommit repository on an hourly schedule. Create a cross-Region copy in the second Region.`, ko:`AWS Backup을 사용하여 시간별 일정에 따라 CodeCommit 리포지토리를 백업합니다. 두 번째 리전에 교차 리전 복사본을 생성합니다.` },
      { k:'C', en:`Create an Amazon EventBridge rule to invoke AWS CodeBuild when the company pushes code to the repository. Use CodeBuild to clone the repository. Create a .zip file of the content. Copy the file to an S3 bucket in the second Region.`, ko:`회사가 리포지토리에 코드를 푸시할 때 AWS CodeBuild를 호출하는 Amazon EventBridge 규칙을 생성합니다. CodeBuild를 사용하여 리포지토리를 복제합니다. 콘텐츠의 .zip 파일을 만듭니다. 두 번째 리전의 S3 버킷에 파일을 복사합니다.` },
      { k:'D', en:`Create an AWS Step Functions workflow on an hourly schedule to take a snapshot of the CodeCommit repository. Configure the workflow to copy the snapshot to an S3 bucket in the second Region`, ko:`CodeCommit 리포지토리의 스냅샷을 찍기 위해 매 시간마다 AWS Step Functions 워크플로를 생성합니다. 두 번째 리전의 S3 버킷에 스냅샷을 복사하도록 워크플로를 구성합니다.` },
    ],
    answer: ["C"],
    vote: '95% C, 5% B',
    explain: `<p><span class="mark-ok">✅ C</span></p><p>https://docs.aws.amazon.com/prescriptive-guidance/latest/patterns/automate-event-driven-backups-from-codecommit-to-amazon-s3-using-codebuild-and-cloudwatch-events.html
AWS의 제품이 이렇게 아마추어적인 방식으로 설계될 수 있다는 것이 믿기지 않습니다.</p>`,
    wrong: `<p><span class="mark-no">❌ B</span> — 백업이라고 되어 있으므로 B가 답이라고 생각합니다. B. AWS Backup을 사용하여 시간별 일정에 따라 CodeCommit 리포지토리를 백업합니다. 두 번째 리전에 교차 리전 복사본을 생성합니다.</p>`,
    disc: [{ ans:'C', txt:'https://www.automat-it.com/post/backup-aws-codecommit' }, { ans:'C', txt:'옵션 C' }, { ans:'C', txt:'C 확실히요' }, { ans:'C', txt:'Option C' }, { ans:'C', txt:'C for sure' }]
  },
  {
    n: 172,
    en: `A company has multiple business units that each have separate accounts on AWS. Each business unit manages its own network with several VPCs that have CIDR ranges that overlap. The company’s marketing team has created a new internal application and wants to make the application accessible to all the other business units. The solution must use private IP addresses only.<br/><br/>Which solution will meet these requirements with the LEAST operational overhead?`,
    ko: `회사에는 AWS에 각각 별도의 계정이 있는 여러 사업부가 있습니다. 각 사업부는 CIDR 범위가 겹치는 여러 VPC로 자체 네트워크를 관리합니다. 회사의 마케팅 팀은 새로운 내부 애플리케이션을 생성했으며 다른 모든 사업부에서 이 애플리케이션에 액세스할 수 있도록 하려고 합니다. 솔루션은 개인 IP 주소만 사용해야 합니다. <br/><br/>최소한의 운영 오버헤드로 이러한 요구 사항을 충족하는 솔루션은 무엇입니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Instruct each business unit to add a unique secondary CIDR range to the business unit's VPC. Peer the VPCs and use a private NAT gateway in the secondary range to route traffic to the marketing team.`, ko:`각 사업부에 고유한 보조 CIDR 범위를 사업부의 VPC에 추가하도록 지시합니다. VPC를 피어링하고 보조 범위의 개인 NAT 게이트웨이를 사용하여 트래픽을 마케팅 팀으로 라우팅합니다.` },
      { k:'B', en:`Create an Amazon EC2 instance to serve as a virtual appliance in the marketing account's VPC. Create an AWS Site-to-Site VPN connection between the marketing team and each business unit's VPC. Perform NAT where necessary.`, ko:`마케팅 계정의 VPC에서 가상 어플라이언스 역할을 할 Amazon EC2 인스턴스를 생성합니다. 마케팅 팀과 각 사업부의 VPC 간에 AWS Site-to-Site VPN 연결을 생성합니다. 필요한 경우 NAT를 수행합니다.` },
      { k:'C', en:`Create an AWS PrivateLink endpoint service to share the marketing application. Grant permission to specific AWS accounts to connect to the service. Create interface VPC endpoints in other accounts to access the application by using private IP addresses.`, ko:`마케팅 애플리케이션을 공유하기 위해 AWS PrivateLink 엔드포인트 서비스를 생성합니다. 특정 AWS 계정에 서비스에 연결할 수 있는 권한을 부여합니다. 프라이빗 IP 주소를 사용하여 애플리케이션에 액세스하려면 다른 계정에 인터페이스 VPC 엔드포인트를 생성하세요.` },
      { k:'D', en:`Create a Network Load Balancer (NLB) in front of the marketing application in a private subnet. Create an API Gateway API. Use the Amazon API Gateway private integration to connect the API to the NLB. Activate IAM authorization for the API. Grant access to the accounts of the other business units.`, ko:`프라이빗 서브넷의 마케팅 애플리케이션 앞에 NLB(Network Load Balancer)를 생성합니다. API 게이트웨이 API를 생성합니다. Amazon API Gateway 프라이빗 통합을 사용하여 API를 NLB에 연결합니다. API에 대한 IAM 승인을 활성화합니다. 다른 사업부의 계정에 대한 액세스 권한을 부여합니다.` },
    ],
    answer: ["C"],
    vote: '94% C, 6% B',
    explain: `<p><span class="mark-ok">✅ C</span></p><p>비공개 링크는 IP 중첩을 위한 솔루션이며 계정 간 앱에 안전하게 액세스합니다.</p>`,
    wrong: `<p><span class="mark-no">❌ B</span> — "최소 운영 오버헤드" - 질문의 핵심 단어입니다. 온프레미스 인프라를 AWS로 마이그레이션하는 것은 그리 쉽지 않습니다. 여기 답변을 보면 이전에 아무도 그렇게 하지 않았으며 AWS 문서에서와 같이 답변한 것으로 보입니다. 온프레미스 인프라를 마이그레이션하는 가장 쉬운 방법 - ec2</p>`,
    disc: [{ ans:'C', txt:'비공개 링크는 IP 중첩을 위한 솔루션이며 계정 간 앱에 안전하게 액세스합니다.' }, { ans:'C', txt:'Private link is the solution for IP Overlapping and Securely access the app between accounts' }, { ans:'C', txt:'AWS PrivateLink를 사용하면 마케팅 팀은 프라이빗 IP 주소를 사용하여 내부 애플리케이션을 다른 계정과 안전하게 공유하는 엔드포인트 서비스를 생성할 수 있습니다. 특정 AWS 계정에 서비스에 연결할 수 있는 권한을 부여하고 다른 계정에 인터페이스 VPC 엔드포인트를 생성하여 프라이빗 IP 주소를 사용하여 애플리케이션에 액세스할 수 있습니다. 이 옵션은 다른 사업부의 네트워크를 변경할 필요가 없으며 피어링이나 NAT가 필요하지 않습니다. 이 솔루션은 확장 가능하고 안전합니다.' }, { ans:'C', txt:'With AWS PrivateLink, the marketing team can create an endpoint service to share their internal application with other accounts securely using private IP addresses. They can grant permission to specific AWS accounts to connect to the service and create interface VPC endpoints in the other accounts to access the application by using private IP addresses. This option does not require any changes ...' }, { ans:'B', txt:'"최소 운영 오버헤드" - 질문의 핵심 단어입니다. 온프레미스 인프라를 AWS로 마이그레이션하는 것은 그리 쉽지 않습니다. 여기 답변을 보면 이전에 아무도 그렇게 하지 않았으며 AWS 문서에서와 같이 답변한 것으로 보입니다. 온프레미스 인프라를 마이그레이션하는 가장 쉬운 방법 - ec2' }]
  },
  {
    n: 173,
    en: `A company needs to audit the security posture of a newly acquired AWS account. The company’s data security team requires a notification only when an Amazon S3 bucket becomes publicly exposed. The company has already established an Amazon Simple Notification Service (Amazon SNS) topic that has the data security team's email address subscribed.<br/><br/>Which solution will meet these requirements?`,
    ko: `회사는 새로 취득한 AWS 계정의 보안 상태를 감사해야 합니다. 회사의 데이터 보안 팀은 Amazon S3 버킷이 공개적으로 노출되는 경우에만 알림을 요구합니다. 회사는 이미 데이터 보안 팀의 이메일 주소를 구독하는 Amazon Simple 알림 서비스(Amazon SNS) 주제를 설정했습니다. <br/><br/>어떤 솔루션이 이러한 요구 사항을 충족합니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Create an S3 event notification on all S3 buckets for the isPublic event. Select the SNS topic as the target for the event notifications.`, ko:`isPublic 이벤트에 대해 모든 S3 버킷에 S3 이벤트 알림을 생성합니다. 이벤트 알림 대상으로 SNS 주제를 선택합니다.` },
      { k:'B', en:`Create an analyzer in AWS Identity and Access Management Access Analyzer. Create an Amazon EventBridge rule for the event type “Access Analyzer Finding” with a filter for “isPublic: true.” Select the SNS topic as the EventBridge rule target.`, ko:`AWS Identity and Access Management Access Analyser에서 분석기를 생성합니다. "isPublic: true"에 대한 필터를 사용하여 이벤트 유형 "액세스 분석기 찾기"에 대한 Amazon EventBridge 규칙을 생성합니다. EventBridge 규칙 대상으로 SNS 주제를 선택합니다.` },
      { k:'C', en:`Create an Amazon EventBridge rule for the event type “Bucket-Level API Call via CloudTrail” with a filter for “PutBucketPolicy.” Select the SNS topic as the EventBridge rule target.`, ko:`"PutBucketPolicy"에 대한 필터를 사용하여 "CloudTrail을 통한 버킷 수준 API 호출" 이벤트 유형에 대한 Amazon EventBridge 규칙을 생성합니다. EventBridge 규칙 대상으로 SNS 주제를 선택합니다.` },
      { k:'D', en:`Activate AWS Config and add the cloudtrail-s3-dataevents-enabled rule. Create an Amazon EventBridge rule for the event type “Config Rules Re-evaluation Status” with a filter for “NON_COMPLIANT.” Select the SNS topic as the EventBridge rule target.`, ko:`AWS Config를 활성화하고 cloudtrail-s3-dataevents-enabled 규칙을 추가합니다. "NON_COMPLIANT" 필터를 사용하여 이벤트 유형 "구성 규칙 재평가 상태"에 대한 Amazon EventBridge 규칙을 생성합니다. EventBridge 규칙 대상으로 SNS 주제를 선택합니다.` },
    ],
    answer: ["B"],
    vote: '94% B, 6% D',
    explain: `<p><span class="mark-ok">✅ B</span></p><p>https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-analyzer.html</p>`,
    wrong: `<p><span class="mark-no">❌ D</span> — 제거 규칙에 따른 D</p>`,
    disc: [{ ans:'B', txt:'https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-analyzer.html' }, { ans:'B', txt:'B는 AWS Identity and Access Management Access Analyser를 사용하여 액세스 제어 구성을 지속적으로 모니터링하고 공개적으로 액세스할 수 있도록 구성된 S3 버킷이 있는지 감지하므로 올바른 솔루션입니다. 공개적으로 액세스 가능한 버킷이 감지되면 Amazon EventBridge 규칙이 트리거되고 SNS 주제에 결과가 통보됩니다.' }, { ans:'B', txt:'B is the correct solution because it uses AWS Identity and Access Management Access Analyzer to continuously monitor access control configurations and detect whether any S3 buckets have been configured to be publicly accessible. When a publicly accessible bucket is detected, an Amazon EventBridge rule is triggered, and the SNS topic is notified with the finding.' }, { ans:'B', txt:'B야' }, { ans:'B', txt:'B eventbirdge 및 액세스 분석기' }]
  },
  {
    n: 174,
    en: `A solutions architect needs to assess a newly acquired company’s portfolio of applications and databases. The solutions architect must create a business case to migrate the portfolio to AWS. The newly acquired company runs applications in an on-premises data center. The data center is not well documented. The solutions architect cannot immediately determine how many applications and databases exist. Traffic for the applications is variable. Some applications are batch processes that run at the end of each month.<br/><br/>The solutions architect must gain a better understanding of the portfolio before a migration to AWS can begin.<br/><br/>Which solution will meet these requirements?`,
    ko: `솔루션 설계자는 새로 인수한 회사의 애플리케이션 및 데이터베이스 포트폴리오를 평가해야 합니다. 솔루션 아키텍트는 포트폴리오를 AWS로 마이그레이션하기 위한 비즈니스 사례를 생성해야 합니다. 새로 인수된 회사는 온프레미스 데이터 센터에서 애플리케이션을 실행합니다. 데이터 센터에 대한 문서화가 잘 되어 있지 않습니다. 솔루션 설계자는 얼마나 많은 애플리케이션과 데이터베이스가 존재하는지 즉시 확인할 수 없습니다. 애플리케이션의 트래픽은 가변적입니다. 일부 애플리케이션은 매월 말에 실행되는 일괄 프로세스입니다. <br/><br/>솔루션 아키텍트는 AWS로의 마이그레이션을 시작하기 전에 포트폴리오를 더 잘 이해해야 합니다. <br/><br/>어떤 솔루션이 이러한 요구 사항을 충족합니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Use AWS Server Migration Service (AWS SMS) and AWS Database Migration Service (AWS DMS) to evaluate migration. Use AWS Service Catalog to understand application and database dependencies.`, ko:`AWS Server Migration Service(AWS SMS) 및 AWS Database Migration Service(AWS DMS)를 사용하여 마이그레이션을 평가합니다. AWS Service Catalog를 사용하여 애플리케이션 및 데이터베이스 종속성을 이해합니다.` },
      { k:'B', en:`Use AWS Application Migration Service. Run agents on the on-premises infrastructure. Manage the agents by using AWS Migration Hub. Use AWS Storage Gateway to assess local storage needs and database dependencies.`, ko:`AWS 애플리케이션 마이그레이션 서비스를 사용하십시오. 온프레미스 인프라에서 에이전트를 실행합니다. AWS Migration Hub를 사용하여 에이전트를 관리합니다. AWS Storage Gateway를 사용하여 로컬 스토리지 요구 사항과 데이터베이스 종속성을 평가합니다.` },
      { k:'C', en:`Use Migration Evaluator to generate a list of servers. Build a report for a business case. Use AWS Migration Hub to view the portfolio. Use AWS Application Discovery Service to gain an understanding of application dependencies.`, ko:`마이그레이션 평가기를 사용하여 서버 목록을 생성합니다. 비즈니스 사례에 대한 보고서를 작성하세요. AWS Migration Hub를 사용하여 포트폴리오를 확인하세요. AWS Application Discovery Service를 사용하여 애플리케이션 종속성을 이해하십시오.` },
      { k:'D', en:`Use AWS Control Tower in the destination account to generate an application portfolio. Use AWS Server Migration Service (AWS SMS) to generate deeper reports and a business case. Use a landing zone for core accounts and resources.`, ko:`대상 계정에서 AWS Control Tower를 사용하여 애플리케이션 포트폴리오를 생성합니다. AWS Server Migration Service(AWS SMS)를 사용하여 심층적인 보고서와 비즈니스 사례를 생성하십시오. 핵심 계정 및 리소스에 대한 랜딩 존을 사용하십시오.` },
    ],
    answer: ["C"],
    vote: '96% C',
    explain: `<p><span class="mark-ok">✅ C</span></p><p>먼저 평가가 필요하다</p>`,
    wrong: `<p><span class="mark-no">❌ B</span> — 응용 프로그램에 중점을 둡니다. "일부 응용 프로그램은 매월 말에 실행되는 일괄 프로세스입니다." C가 B보다 나은 이유를 모르겠습니다.</p>`,
    disc: [{ ans:'C', txt:'먼저 평가가 필요하다' }, { ans:'C', txt:'First need to evaluate' }, { ans:'C', txt:'C. 마이그레이션 평가기를 사용하여 서버 목록을 생성합니다. 비즈니스 사례에 대한 보고서를 작성하세요. AWS Migration Hub를 사용하여 포트폴리오를 확인하세요. AWS Application Discovery Service를 사용하여 애플리케이션 종속성을 이해하십시오.' }, { ans:'C', txt:'C. Use Migration Evaluator to generate a list of servers. Build a report for a business case. Use AWS Migration Hub to view the portfolio. Use AWS Application Discovery Service to gain an understanding of application dependencies.' }, { ans:'C', txt:'옵션 C' }]
  },
  {
    n: 175,
    en: `A company has an application that runs as a ReplicaSet of multiple pods in an Amazon Elastic Kubernetes Service (Amazon EKS) cluster. The EKS cluster has nodes in multiple Availability Zones. The application generates many small files that must be accessible across all running instances of the application. The company needs to back up the files and retain the backups for 1 year.<br/><br/>Which solution will meet these requirements while providing the FASTEST storage performance?`,
    ko: `회사에는 Amazon Elastic Kubernetes Service(Amazon EKS) 클러스터에서 여러 포드의 ReplicaSet으로 실행되는 애플리케이션이 있습니다. EKS 클러스터에는 여러 가용 영역에 노드가 있습니다. 애플리케이션은 실행 중인 모든 애플리케이션 인스턴스에서 액세스할 수 있어야 하는 많은 작은 파일을 생성합니다. 회사는 해당 파일을 백업하고, 백업본을 1년간 보관해야 합니다. <br/><br/>가장 빠른 스토리지 성능을 제공하면서 이러한 요구 사항을 충족하는 솔루션은 무엇입니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Create an Amazon Elastic File System (Amazon EFS) file system and a mount target for each subnet that contains nodes in the EKS cluster. Configure the ReplicaSet to mount the file system. Direct the application to store files in the file system. Configure AWS Backup to back up and retain copies of the data for 1 year.`, ko:`EKS 클러스터의 노드가 포함된 각 서브넷에 대해 Amazon Elastic File System(Amazon EFS) 파일 시스템과 탑재 대상을 생성합니다. 파일 시스템을 마운트하도록 ReplicaSet를 구성합니다. 파일 시스템에 파일을 저장하도록 애플리케이션에 지시합니다. 1년 동안 데이터 복사본을 백업하고 보관하도록 AWS Backup을 구성합니다.` },
      { k:'B', en:`Create an Amazon Elastic Block Store (Amazon EBS) volume. Enable the EBS Multi-Attach feature. Configure the ReplicaSet to mount the EBS volume. Direct the application to store files in the EBS volume. Configure AWS Backup to back up and retain copies of the data for 1 year.`, ko:`Amazon Elastic Block Store(Amazon EBS) 볼륨을 생성합니다. EBS 다중 연결 기능을 활성화합니다. EBS 볼륨을 마운트하도록 ReplicaSet를 구성합니다. EBS 볼륨에 파일을 저장하도록 애플리케이션에 지시합니다. 1년 동안 데이터 복사본을 백업하고 보관하도록 AWS Backup을 구성합니다.` },
      { k:'C', en:`Create an Amazon S3 bucket. Configure the ReplicaSet to mount the S3 bucket. Direct the application to store files in the S3 bucket. Configure S3 Versioning to retain copies of the data. Configure an S3 Lifecycle policy to delete objects after 1 year.`, ko:`Amazon S3 버킷을 생성합니다. S3 버킷을 마운트하도록 ReplicaSet를 구성합니다. 애플리케이션이 S3 버킷에 파일을 저장하도록 지시합니다. 데이터 복사본을 유지하도록 S3 버전 관리를 구성합니다. 1년 후에 객체를 삭제하도록 S3 수명 주기 정책을 구성합니다.` },
      { k:'D', en:`Configure the ReplicaSet to use the storage available on each of the running application pods to store the files locally. Use a third-party tool to back up the EKS cluster for 1 year.`, ko:`실행 중인 각 애플리케이션 포드에서 사용 가능한 스토리지를 사용하여 파일을 로컬에 저장하도록 ReplicaSet를 구성합니다. 타사 도구를 사용하여 EKS 클러스터를 1년 동안 백업합니다.` },
    ],
    answer: ["A"],
    vote: '100% A',
    explain: `<p><span class="mark-ok">✅ A</span></p><p>설명: Amazon EFS는 가용성과 내구성이 뛰어난 공유 파일 스토리지를 제공합니다. 클러스터의 여러 인스턴스에서 실행되는 컨테이너 간에 파일을 공유하는 이상적인 솔루션입니다. 각 서브넷에 Amazon EFS 파일 시스템을 탑재하면 서로 다른 가용 영역에서 실행되는 여러 인스턴스에 대한 공유 파일 시스템이 제공됩니다. 또한 AWS Backup은 Amazon EFS 파일 시스템의 자동화된 백업 및 복구를 제공합니다.</p>`,
    wrong: ``,
    disc: [{ ans:'A', txt:'설명: Amazon EFS는 가용성과 내구성이 뛰어난 공유 파일 스토리지를 제공합니다. 클러스터의 여러 인스턴스에서 실행되는 컨테이너 간에 파일을 공유하는 이상적인 솔루션입니다. 각 서브넷에 Amazon EFS 파일 시스템을 탑재하면 서로 다른 가용 영역에서 실행되는 여러 인스턴스에 대한 공유 파일 시스템이 제공됩니다. 또한 AWS Backup은 Amazon EFS 파일 시스템의 자동화된 백업 및 복구를 제공합니다.' }, { ans:'A', txt:'EFS = S3/EBS에 비해 가장 빠른 스토리지 성능' }, { ans:'A', txt:'Explanation: Amazon EFS provides shared file storage that is highly available and durable. It is an ideal solution to share files between containers running on multiple instances in a cluster. Mounting an Amazon EFS file system on each subnet provides a shared file system for multiple instances running in different Availability Zones. Additionally, AWS Backup provides automated backup and recov...' }, { ans:'A', txt:'EFS = Fastest storage performance compare to S3/EBS' }, { ans:'A', txt:'옵션 A' }]
  },
  {
    n: 176,
    en: `A company runs a customer service center that accepts calls and automatically sends all customers a managed, interactive, two-way experience survey by text message. The applications that support the customer service center run on machines that the company hosts in an on-premises data center. The hardware that the company uses is old, and the company is experiencing downtime with the system. The company wants to migrate the system to AWS to improve reliability.<br/><br/>Which solution will meet these requirements with the LEAST ongoing operational overhead?`,
    ko: `한 회사는 전화를 받고 모든 고객에게 문자 메시지를 통해 관리되는 대화형 양방향 경험 설문조사를 자동으로 보내는 고객 서비스 센터를 운영하고 있습니다. 고객 서비스 센터를 지원하는 애플리케이션은 회사가 온프레미스 데이터 센터에서 호스팅하는 시스템에서 실행됩니다. 회사에서 사용하는 하드웨어가 오래되어 회사 시스템에 다운타임이 발생하고 있습니다. 회사는 안정성을 향상하기 위해 시스템을 AWS로 마이그레이션하려고 합니다. <br/><br/>최소한의 운영 오버헤드로 이러한 요구 사항을 충족하는 솔루션은 무엇입니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Use Amazon Connect to replace the old call center hardware. Use Amazon Pinpoint to send text message surveys to customers.`, ko:`Amazon Connect를 사용하여 기존 콜센터 하드웨어를 교체하십시오. Amazon Pinpoint를 사용하여 고객에게 문자 메시지 설문조사를 보냅니다.` },
      { k:'B', en:`Use Amazon Connect to replace the old call center hardware. Use Amazon Simple Notification Service (Amazon SNS) to send text message surveys to customers.`, ko:`Amazon Connect를 사용하여 기존 콜센터 하드웨어를 교체하십시오. Amazon Simple 알림 서비스(Amazon SNS)를 사용하여 고객에게 문자 메시지 설문조사를 보냅니다.` },
      { k:'C', en:`Migrate the call center software to Amazon EC2 instances that are in an Auto Scaling group. Use the EC2 instances to send text message surveys to customers.`, ko:`콜센터 소프트웨어를 Auto Scaling 그룹에 있는 Amazon EC2 인스턴스로 마이그레이션합니다. EC2 인스턴스를 사용하여 고객에게 문자 메시지 설문조사를 보냅니다.` },
      { k:'D', en:`Use Amazon Pinpoint to replace the old call center hardware and to send text message surveys to customers.`, ko:`Amazon Pinpoint를 사용하여 기존 콜센터 하드웨어를 교체하고 고객에게 문자 메시지 설문조사를 보냅니다.` },
    ],
    answer: ["A"],
    vote: '100% A',
    explain: `<p><span class="mark-ok">✅ A</span></p><p>Amazon Connect는 비즈니스를 위한 가상 콜센터를 설정할 수 있는 클라우드 기반 콜센터 서비스입니다. 음성 및 채팅을 통해 고객 상호 작용을 관리하기 위한 사용하기 쉬운 인터페이스를 제공합니다. Amazon Connect는 Amazon S3 및 Amazon Kinesis와 같은 다른 AWS 서비스와 통합되어 고객 데이터를 수집, 저장 및 분석하여 고객 행동 및 추세에 대한 통찰력을 제공합니다. 반면, Amazon Pinpoint는 이메일, SMS, 푸시 알림, 음성 등 다양한 채널을 통해 고객과 소통할 수 있는 마케팅 자동화 및 분석 서비스입니다. 이를 통해 사용자 행동을 기반으로 개인화된 캠페인을 생성하고 사용자 참여 및 유지를 추적할 수 있습니다. 두 서비스 모두 고객과 소통할 수 있지만 ...</p>`,
    wrong: ``,
    disc: [{ ans:'A', txt:'Amazon Connect는 비즈니스를 위한 가상 콜센터를 설정할 수 있는 클라우드 기반 콜센터 서비스입니다. 음성 및 채팅을 통해 고객 상호 작용을 관리하기 위한 사용하기 쉬운 인터페이스를 제공합니다. Amazon Connect는 Amazon S3 및 Amazon Kinesis와 같은 다른 AWS 서비스와 통합되어 고객 데이터를 수집, 저장 및 분석하여 고객 행동 및 추세에 대한 통찰력을 제공합니다. 반면, Amazon Pinpoint는 이메일, SMS, 푸시 알림, 음성 등 다양한 채널을 통해 고객과 소통할 수 있는 마케팅 자동화 및 분석 서비스입니다. 이를 통해 사용자 행동을 기반으로 개인화된 캠페인을 생성하고 사용자 참여 및 유지를 추적할 수 있습니다. 두 서비스 모두 고객과 소통할 수 있지만 ...' }, { ans:'A', txt:'Amazon Connect is a cloud-based contact center service that allows you to set up a virtual call center for your business. It provides an easy-to-use interface for managing customer interactions through voice and chat. Amazon Connect integrates with other AWS services, such as Amazon S3 and Amazon Kinesis, to help you collect, store, and analyze customer data for insights into customer behavior ...' }, { ans:'A', txt:'최소한의 운영 오버헤드로 회사의 요구 사항을 충족하고 양방향 경험 설문조사를 보내는 솔루션은 Amazon Connect를 사용하여 기존 콜센터 하드웨어를 교체하고 Amazon Pinpoint를 사용하여 고객에게 문자 메시지 설문조사를 보내는 것입니다. Amazon Connect는 설정 및 구성이 쉬운 완전 관리형 클라우드 기반 콜센터 서비스이며, Amazon Pinpoint를 사용하여 문자 메시지 설문조사를 보내고 응답을 수집할 수 있습니다. 이러한 서비스를 사용함으로써 회사는 콜 센터 하드웨어 및 설문 조사 시스템을 실행하고 유지 관리하는 운영 오버헤드를 AWS로 오프로드할 수 있습니다.' }, { ans:'A', txt:'The solution that will meet the company\'s requirements with the LEAST ongoing operational overhead and send two-way experience survey is to use Amazon Connect to replace the old call center hardware and use Amazon Pinpoint to send text message surveys to customers. Amazon Connect is a fully managed, cloud-based contact center service that is easy to set up and configure, while Amazon Pinpoint c...' }, { ans:'A', txt:'https://docs.aws.amazon.com/pinpoint/latest/userguide/channels-sms-two-way.html' }]
  },
  {
    n: 177,
    en: `A company is building a call center by using Amazon Connect. The company’s operations team is defining a disaster recovery (DR) strategy across AWS Regions. The contact center has dozens of contact flows, hundreds of users, and dozens of claimed phone numbers.<br/><br/>Which solution will provide DR with the LOWEST RTO?`,
    ko: `한 회사에서 Amazon Connect를 사용하여 콜센터를 구축하고 있습니다. 회사의 운영 팀은 AWS 지역 전반에 걸쳐 재해 복구(DR) 전략을 정의하고 있습니다. 연락 센터에는 수십 개의 연락 흐름, 수백 명의 사용자, 수십 개의 청구된 전화 번호가 있습니다. <br/><br/>DR에 가장 낮은 RTO를 제공하는 솔루션은 무엇입니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Create an AWS Lambda function to check the availability of the Amazon Connect instance and to send a notification to the operations team in case of unavailability. Create an Amazon EventBridge rule to invoke the Lambda function every 5 minutes. After notification, instruct the operations team to use the AWS Management Console to provision a new Amazon Connect instance in a second Region. Deploy the contact flows, users, and claimed phone numbers by using an AWS CloudFormation template.`, ko:`Amazon Connect 인스턴스의 가용성을 확인하고 사용할 수 없는 경우 운영 팀에 알림을 보내는 AWS Lambda 함수를 생성하십시오. 5분마다 Lambda 함수를 호출하는 Amazon EventBridge 규칙을 생성합니다. 알림을 받은 후 운영 팀에 AWS Management Console을 사용하여 두 번째 지역에 새 Amazon Connect 인스턴스를 프로비저닝하도록 지시하십시오. AWS CloudFormation 템플릿을 사용하여 고객 응대 흐름, 사용자 및 청구된 전화번호를 배포합니다.` },
      { k:'B', en:`Provision a new Amazon Connect instance with all existing users in a second Region. Create an AWS Lambda function to check the availability of the Amazon Connect instance. Create an Amazon EventBridge rule to invoke the Lambda function every 5 minutes. In the event of an issue, configure the Lambda function to deploy an AWS CloudFormation template that provisions contact flows and claimed numbers in the second Region.`, ko:`두 번째 지역의 모든 기존 사용자와 함께 새로운 Amazon Connect 인스턴스를 프로비저닝합니다. Amazon Connect 인스턴스의 가용성을 확인하는 AWS Lambda 함수를 생성합니다. 5분마다 Lambda 함수를 호출하는 Amazon EventBridge 규칙을 생성합니다. 문제가 발생하는 경우 두 번째 지역에서 고객 응대 흐름 및 청구 번호를 프로비저닝하는 AWS CloudFormation 템플릿을 배포하도록 Lambda 함수를 구성합니다.` },
      { k:'C', en:`Provision a new Amazon Connect instance with all existing contact flows and claimed phone numbers in a second Region. Create an Amazon Route 53 health check for the URL of the Amazon Connect instance. Create an Amazon CloudWatch alarm for failed health checks. Create an AWS Lambda function to deploy an AWS CloudFormation template that provisions all users. Configure the alarm to invoke the Lambda function.`, ko:`두 번째 지역에서 모든 기존 고객 응대 흐름과 청구된 전화번호를 사용하여 새로운 Amazon Connect 인스턴스를 프로비저닝합니다. Amazon Connect 인스턴스의 URL에 대한 Amazon Route 53 상태 확인을 생성합니다. 상태 확인 실패에 대한 Amazon CloudWatch 경보를 생성합니다. 모든 사용자를 프로비저닝하는 AWS CloudFormation 템플릿을 배포하는 AWS Lambda 함수를 생성합니다. Lambda 함수를 호출하도록 경보를 구성합니다.` },
      { k:'D', en:`Provision a new Amazon Connect instance with all existing users and contact flows in a second Region. Create an Amazon Route 53 health check for the URL of the Amazon Connect instance. Create an Amazon CloudWatch alarm for failed health checks. Create an AWS Lambda function to deploy an AWS CloudFormation template that provisions claimed phone numbers. Configure the alarm to invoke the Lambda function.`, ko:`두 번째 지역의 모든 기존 사용자 및 고객 응대 흐름을 사용하여 새로운 Amazon Connect 인스턴스를 프로비저닝합니다. Amazon Connect 인스턴스의 URL에 대한 Amazon Route 53 상태 확인을 생성합니다. 상태 확인 실패에 대한 Amazon CloudWatch 경보를 생성합니다. 청구된 전화번호를 프로비저닝하는 AWS CloudFormation 템플릿을 배포하는 AWS Lambda 함수를 생성합니다. Lambda 함수를 호출하도록 경보를 구성합니다.` },
    ],
    answer: ["D"],
    vote: '85% D, 15% B',
    explain: `<p><span class="mark-ok">✅ D</span></p><p>D가 가장 적절해 보인다</p>`,
    wrong: `<p><span class="mark-no">❌ B</span> — 분명히 Route 53은 Amazon Connect DNS 이름이나 상태 확인을 관리할 수 없습니다. https://docs.aws.amazon.com/connect/latest/adminguide/update-your-connect-domain.html#new-domain-custom</p>`,
    disc: [{ ans:'D', txt:'D가 가장 적절해 보인다' }, { ans:'D', txt:'D looks most appropriate' }, { ans:'D', txt:'DR에 가장 낮은 RTO(복구 시간 목표)를 제공하는 솔루션은 옵션 D입니다. 옵션 D는 두 번째 지역의 모든 기존 사용자 및 고객 응대 흐름을 사용하여 새로운 Amazon Connect 인스턴스를 프로비저닝합니다. 또한 Amazon Connect 인스턴스의 URL에 대한 Amazon Route 53 상태 확인, 상태 확인 실패에 대한 Amazon CloudWatch 경보, 요청된 전화번호를 제공하는 AWS CloudFormation 템플릿을 배포하기 위한 AWS Lambda 함수를 설정합니다. 이 옵션을 사용하면 필요한 모든 구성 요소가 이미 프로비저닝되어 두 번째 지역에 들어갈 준비가 되었기 때문에 가장 빠른 복구 시간이 가능합니다. 재해가 발생하는 경우 상태 확인이 실패하면 AWS Lambda 함...' }, { ans:'D', txt:'The solution that will provide DR with the LOWEST RTO (Recovery Time Objective) is option D. Option D provisions a new Amazon Connect instance with all existing users and contact flows in a second Region. It also sets up an Amazon Route 53 health check for the URL of the Amazon Connect instance, an Amazon CloudWatch alarm for failed health checks, and an AWS Lambda function to deploy an AWS Clo...' }, { ans:'D', txt:'D. 두 번째 지역의 모든 기존 사용자 및 고객 응대 흐름을 사용하여 새로운 Amazon Connect 인스턴스를 프로비저닝합니다.' }]
  },
  {
    n: 178,
    en: `A company runs an application on AWS. The company curates data from several different sources. The company uses proprietary algorithms to perform data transformations and aggregations. After the company performs ETL processes, the company stores the results in Amazon Redshift tables. The company sells this data to other companies. The company downloads the data as files from the Amazon Redshift tables and transmits the files to several data customers by using FTP. The number of data customers has grown significantly. Management of the data customers has become difficult.<br/><br/>The company will use AWS Data Exchange to create a data product that the company can use to share data with customers. The company wants to confirm the identities of the customers before the company shares data. The customers also need access to the most recent data when the company publishes the data.<br/><br/>Which solution will meet these requirements with the LEAST operational overhead?`,
    ko: `한 회사가 AWS에서 애플리케이션을 실행하고 있습니다. 회사는 다양한 소스로부터 데이터를 선별합니다. 회사는 독점 알고리즘을 사용하여 데이터 변환 및 집계를 수행합니다. 회사는 ETL 프로세스를 수행한 후 결과를 Amazon Redshift 테이블에 저장합니다. 회사는 이 데이터를 다른 회사에 판매합니다. 회사는 Amazon Redshift 테이블에서 데이터를 파일로 다운로드하고 FTP를 사용하여 여러 데이터 고객에게 파일을 전송합니다. 데이터 고객 수가 크게 늘어났습니다. 데이터 고객 관리가 어려워졌습니다. <br/><br/>회사는 AWS Data Exchange를 사용하여 회사가 고객과 데이터를 공유하는 데 사용할 수 있는 데이터 제품을 만들 것입니다. 회사는 데이터를 공유하기 전에 고객의 신원을 확인하기를 원합니다. 또한 고객은 회사가 데이터를 게시할 때 최신 데이터에 액세스해야 합니다. <br/><br/>최소한의 운영 오버헤드로 이러한 요구 사항을 충족하는 솔루션은 무엇입니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Use AWS Data Exchange for APIs to share data with customers. Configure subscription verification. In the AWS account of the company that produces the data, create an Amazon API Gateway Data API service integration with Amazon Redshift. Require the data customers to subscribe to the data product.`, ko:`API용 AWS Data Exchange를 사용하여 고객과 데이터를 공유하십시오. 구독 확인을 구성합니다. 데이터를 생산하는 회사의 AWS 계정에서 Amazon Redshift와 Amazon API Gateway 데이터 API 서비스 통합을 생성합니다. 데이터 고객에게 데이터 제품을 구독하도록 요구합니다.` },
      { k:'B', en:`In the AWS account of the company that produces the data, create an AWS Data Exchange datashare by connecting AWS Data Exchange to the Redshift cluster. Configure subscription verification. Require the data customers to subscribe to the data product.`, ko:`데이터를 생산하는 회사의 AWS 계정에서 AWS Data Exchange를 Redshift 클러스터에 연결하여 AWS Data Exchange 데이터 공유를 생성합니다. 구독 확인을 구성합니다. 데이터 고객에게 데이터 제품을 구독하도록 요구합니다.` },
      { k:'C', en:`Download the data from the Amazon Redshift tables to an Amazon S3 bucket periodically. Use AWS Data Exchange for S3 to share data with customers. Configure subscription verification. Require the data customers to subscribe to the data product.`, ko:`Amazon Redshift 테이블의 데이터를 주기적으로 Amazon S3 버킷으로 다운로드합니다. S3용 AWS Data Exchange를 사용하여 고객과 데이터를 공유하십시오. 구독 확인을 구성합니다. 데이터 고객에게 데이터 제품을 구독하도록 요구합니다.` },
      { k:'D', en:`Publish the Amazon Redshift data to an Open Data on AWS Data Exchange. Require the customers to subscribe to the data product in AWS Data Exchange. In the AWS account of the company that produces the data, attach IAM resource-based policies to the Amazon Redshift tables to allow access only to verified AWS accounts.`, ko:`Amazon Redshift 데이터를 AWS Data Exchange의 개방형 데이터에 게시합니다. 고객에게 AWS Data Exchange의 데이터 제품을 구독하도록 요구합니다. 데이터를 생산하는 회사의 AWS 계정에서 IAM 리소스 기반 정책을 Amazon Redshift 테이블에 연결하여 확인된 AWS 계정에만 액세스를 허용합니다.` },
    ],
    answer: ["B"],
    vote: '83% B, 17% C',
    explain: `<p><span class="mark-ok">✅ B</span></p><p>회사는 데이터를 공유하기 전에 고객의 신원을 확인하기를 원합니다. 또한 고객은 회사가 데이터를 게시할 때 최신 데이터에 액세스해야 합니다. B를 사용하면 고객은 시간 지연이나 추가 작업 없이 Redshift에서 직접 데이터를 얻을 수 있습니다.</p>`,
    wrong: `<p><span class="mark-no">❌ C</span> — 데이터의 고객수는 대폭 증가한 대책에 S3</p>`,
    disc: [{ ans:'B', txt:'회사는 데이터를 공유하기 전에 고객의 신원을 확인하기를 원합니다. 또한 고객은 회사가 데이터를 게시할 때 최신 데이터에 액세스해야 합니다. B를 사용하면 고객은 시간 지연이나 추가 작업 없이 Redshift에서 직접 데이터를 얻을 수 있습니다.' }, { ans:'B', txt:'The company wants to confirm the identities of the customers before the company shares data. The customers also need access to the most recent data when the company publishes the data. With B, customer can get data from Redshift directly with no time lag and additional operations.' }, { ans:'B', txt:'그건 B야' }, { ans:'B', txt:'it\'s a B' }, { ans:'B', txt:'B인 것 같아요. https://aws.amazon.com/data-exchange/why-aws-data-exchange/redshift-data-tables/에 따르면 고객은 AWS Data Exchange에서 타사 데이터를 찾아 구독할 수 있으며 데이터를 추출, 변환 또는 로드하지 않고도 Amazon Redshift에서 몇 분 만에 데이터를 직접 쿼리할 수 있습니다. B에서는 고객이 Redshift를 직접 쿼리할 수 있습니다. S3를 주기적으로 사용할 필요가 없습니다. 운영 오버헤드를 최소화합니다.' }]
  },
  {
    n: 179,
    en: `A solutions architect is designing a solution to process events. The solution must have the ability to scale in and out based on the number of events that the solution receives. If a processing error occurs, the event must move into a separate queue for review.<br/><br/>Which solution will meet these requirements?`,
    ko: `솔루션 설계자는 이벤트를 처리하기 위한 솔루션을 설계하고 있습니다. 솔루션에는 솔루션이 수신하는 이벤트 수에 따라 규모를 확대 및 축소할 수 있는 기능이 있어야 합니다. 처리 오류가 발생하는 경우 이벤트는 검토를 위해 별도의 대기열로 이동해야 합니다. <br/><br/>어떤 솔루션이 이러한 요구 사항을 충족합니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Send event details to an Amazon Simple Notification Service (Amazon SNS) topic. Configure an AWS Lambda function as a subscriber to the SNS topic to process the events. Add an on-failure destination to the function. Set an Amazon Simple Queue Service (Amazon SQS) queue as the target.`, ko:`Amazon SNS(Amazon SNS) 주제로 이벤트 세부 정보를 보냅니다. 이벤트를 처리하려면 AWS Lambda 함수를 SNS 주제의 구독자로 구성하세요. 실패 시 대상을 함수에 추가합니다. Amazon Simple Queue Service(Amazon SQS) 대기열을 대상으로 설정합니다.` },
      { k:'B', en:`Publish events to an Amazon Simple Queue Service (Amazon SQS) queue. Create an Amazon EC2 Auto Scaling group. Configure the Auto Scaling group to scale in and out based on the ApproximateAgeOfOldestMessage metric of the queue. Configure the application to write failed messages to a dead-letter queue.`, ko:`Amazon Simple Queue Service(Amazon SQS) 대기열에 이벤트를 게시합니다. Amazon EC2 Auto Scaling 그룹을 생성합니다. 대기열의 ApproximateAgeOfOldestMessage 지표를 기반으로 확장 및 축소하도록 Auto Scaling 그룹을 구성합니다. 실패한 메시지를 배달 못한 편지 대기열에 쓰도록 애플리케이션을 구성합니다.` },
      { k:'C', en:`Write events to an Amazon DynamoDB table. Configure a DynamoDB stream for the table. Configure the stream to invoke an AWS Lambda function. Configure the Lambda function to process the events.`, ko:`Amazon DynamoDB 테이블에 이벤트를 씁니다. 테이블에 대한 DynamoDB 스트림을 구성합니다. AWS Lambda 함수를 호출하도록 스트림을 구성합니다. 이벤트를 처리하도록 Lambda 함수를 구성합니다.` },
      { k:'D', en:`Publish events to an Amazon EventBndge event bus. Create and run an application on an Amazon EC2 instance with an Auto Scaling group that is behind an Application Load Balancer (ALB). Set the ALB as the event bus target. Configure the event bus to retry events. Write messages to a dead-letter queue if the application cannot process the messages.`, ko:`Amazon EventBndge 이벤트 버스에 이벤트를 게시합니다. Application Load Balancer(ALB) 뒤에 있는 Auto Scaling 그룹을 사용하여 Amazon EC2 인스턴스에서 애플리케이션을 생성하고 실행합니다. ALB를 이벤트 버스 대상으로 설정합니다. 이벤트를 재시도하도록 이벤트 버스를 구성합니다. 애플리케이션이 메시지를 처리할 수 없는 경우 배달 못한 편지 대기열에 메시지를 씁니다.` },
    ],
    answer: ["A"],
    vote: '58% A, 42% B',
    explain: `<p><span class="mark-ok">✅ A</span></p><p>A에게 투표하세요</p>`,
    wrong: `<p><span class="mark-no">❌ B</span> — 나는 단지 표현 때문에 B를 선택하겠습니다. 나는 A가 잘 작동해야 한다고 생각하지만 질문은 "이벤트 수에 따라 규모 확대 및 축소"를 요구합니다. 제 생각에는 SNS->Lambda->SQS(DLQ)도 그렇게 할 것 같습니다. 나는 SNS->Lambda 축소/축소 동작이 더 암시적이라고 생각합니다. 그래서 나는 B가 더 명확하기 때문에 여기서 B를 선택하겠</p>`,
    disc: [{ ans:'B', txt:'나는 단지 표현 때문에 B를 선택하겠습니다. 나는 A가 잘 작동해야 한다고 생각하지만 질문은 "이벤트 수에 따라 규모 확대 및 축소"를 요구합니다. 제 생각에는 SNS->Lambda->SQS(DLQ)도 그렇게 할 것 같습니다. 나는 SNS->Lambda 축소/축소 동작이 더 암시적이라고 생각합니다. 그래서 나는 B가 더 명확하기 때문에 여기서 B를 선택하겠습니다.' }, { ans:'B', txt:'I would go with B just because of the wording. I believe A should work just fine, but the question asks for "scale in and out based on the number of events." In my opinion, that is what SNS->Lambda->SQS(DLQ) would do, too; I think the SNS->Lambda scale in/out behavior is more implicit. So I will go with B here because it is more explicit.' }, { ans:'B', txt:'DLQ가 포함된 SQSQ' }, { ans:'B', txt:'SQSQ with DLQ' }, { ans:'B', txt:'SQS 대기열에 이벤트 게시, 대기열의 ApproximateAgeOfOldestMessage 지표를 기반으로 확장되는 EC2 Auto Scaling 그룹 생성, 실패한 메시지를 배달 못한 편지 대기열에 쓰도록 애플리케이션 구성은 확장 가능하고 내결함성이 있으며 비용 효율적인 솔루션을 제공합니다. 처리 오류를 별도로 처리하는 기능을 갖춘 이벤트 처리.' }]
  },
  {
    n: 180,
    en: `A company runs a processing engine in the AWS Cloud. The engine processes environmental data from logistics centers to calculate a sustainability index. The company has millions of devices in logistics centers that are spread across Europe. The devices send information to the processing engine through a RESTful API.<br/><br/>The API experiences unpredictable bursts of traffic. The company must implement a solution to process all data that the devices send to the processing engine. Data loss is unacceptable.<br/><br/>Which solution will meet these requirements?`,
    ko: `회사는 AWS 클라우드에서 처리 엔진을 실행합니다. 엔진은 물류센터의 환경 데이터를 처리하여 지속가능성 지수를 계산합니다. 이 회사는 유럽 전역에 분산된 물류 센터에 수백만 대의 장치를 보유하고 있습니다. 장치는 RESTful API를 통해 처리 엔진에 정보를 보냅니다. <br/><br/>API에서 예측할 수 없는 트래픽 급증이 발생합니다. 회사는 장치가 처리 엔진으로 보내는 모든 데이터를 처리하는 솔루션을 구현해야 합니다. 데이터 손실은 용납될 수 없습니다. <br/><br/>어떤 솔루션이 이러한 요구 사항을 충족합니까?`,
    type: 'single',
    choices: [
      { k:'A', en:`Create an Application Load Balancer (ALB) for the RESTful API. Create an Amazon Simple Queue Service (Amazon SQS) queue. Create a listener and a target group for the ALB Add the SQS queue as the target. Use a container that runs in Amazon Elastic Container Service (Amazon ECS) with the Fargate launch type to process messages in the queue.`, ko:`RESTful API용 ALB(Application Load Balancer)를 생성합니다. Amazon Simple Queue Service(Amazon SQS) 대기열을 생성합니다. ALB에 대한 리스너 및 대상 그룹을 생성합니다. SQS 대기열을 대상으로 추가합니다. Fargate 시작 유형과 함께 Amazon Elastic Container Service(Amazon ECS)에서 실행되는 컨테이너를 사용하여 대기열의 메시지를 처리합니다.` },
      { k:'B', en:`Create an Amazon API Gateway HTTP API that implements the RESTful API. Create an Amazon Simple Queue Service (Amazon SQS) queue. Create an API Gateway service integration with the SQS queue. Create an AWS Lambda function to process messages in the SQS queue.`, ko:`RESTful API를 구현하는 Amazon API Gateway HTTP API를 생성합니다. Amazon Simple Queue Service(Amazon SQS) 대기열을 생성합니다. SQS 대기열과 API Gateway 서비스 통합을 생성합니다. SQS 대기열의 메시지를 처리하는 AWS Lambda 함수를 생성합니다.` },
      { k:'C', en:`Create an Amazon API Gateway REST API that implements the RESTful API. Create a fleet of Amazon EC2 instances in an Auto Scaling group. Create an API Gateway Auto Scaling group proxy integration. Use the EC2 instances to process incoming data.`, ko:`RESTful API를 구현하는 Amazon API Gateway REST API를 생성합니다. Auto Scaling 그룹에 Amazon EC2 인스턴스 플릿을 생성합니다. API Gateway Auto Scaling 그룹 프록시 통합을 생성합니다. EC2 인스턴스를 사용하여 수신 데이터를 처리합니다.` },
      { k:'D', en:`Create an Amazon CloudFront distribution for the RESTful API. Create a data stream in Amazon Kinesis Data Streams. Set the data stream as the origin for the distribution. Create an AWS Lambda function to consume and process data in the data stream.`, ko:`RESTful API용 Amazon CloudFront 배포판을 생성합니다. Amazon Kinesis Data Streams에서 데이터 스트림을 생성합니다. 데이터 스트림을 배포 원본으로 설정합니다. 데이터 스트림의 데이터를 소비하고 처리하는 AWS Lambda 함수를 생성합니다.` },
    ],
    answer: ["B"],
    vote: '89% B, 8% D',
    explain: `<p><span class="mark-ok">✅ B</span></p><p>ALB(Application Load Balancer)는 Amazon SQS 대기열을 직접 대상으로 지정할 수 없기 때문에 옵션 A는 올바르지 않습니다. Amazon API Gateway 및 EC2 Auto Scaling은 높은 로드를 처리할 수 있지만 모든 메시지가 손실 없이 처리되도록 보장하는 내장 메커니즘을 제공하지 않기 때문에 옵션 C는 올바르지 않습니다. Amazon CloudFront는 CDN(콘텐츠 전송 네트워크)이고 일반적으로 수신 API 요청을 처리하는 데 사용되지 않으므로 옵션 D는 올바르지 않습니다. 주로 콘텐츠를 캐시하고 사용자에게 전달하는 데 사용됩니다.</p>`,
    wrong: `<p><span class="mark-no">❌ A</span> — 정답에 대한 고유한 키워드 조합은 다음과 같습니다. RESTful API용 ALB(Application Load Balancer)를 생성합니다. Amazon Simple Queue Service(Amazon SQS) 대기열을 생성합니다. ALB에 대한 리스너와 대상 그룹을 생성합니다. SQS 대기열을 대상으로 추가합니다. Fargate 시작 유형과 함께 A</p><p><span class="mark-no">❌ D</span> — Kinesis 보존</p>`,
    disc: [{ ans:'B', txt:'ALB(Application Load Balancer)는 Amazon SQS 대기열을 직접 대상으로 지정할 수 없기 때문에 옵션 A는 올바르지 않습니다. Amazon API Gateway 및 EC2 Auto Scaling은 높은 로드를 처리할 수 있지만 모든 메시지가 손실 없이 처리되도록 보장하는 내장 메커니즘을 제공하지 않기 때문에 옵션 C는 올바르지 않습니다. Amazon CloudFront는 CDN(콘텐츠 전송 네트워크)이고 일반적으로 수신 API 요청을 처리하는 데 사용되지 않으므로 옵션 D는 올바르지 않습니다. 주로 콘텐츠를 캐시하고 사용자에게 전달하는 데 사용됩니다.' }, { ans:'B', txt:'Option A is incorrect because Application Load Balancer (ALB) can\'t directly target an Amazon SQS queue. Option C is incorrect because while Amazon API Gateway and EC2 Auto Scaling can handle high loads, they don\'t provide a built-in mechanism to ensure that all messages are processed without loss. Option D is incorrect because Amazon CloudFront is a content delivery network (CDN), and it is no...' }, { ans:'B', txt:'AWS SDK를 사용하여 API 게이트웨이를 SQS 대기열과 통합할 수 있으며, API 게이트웨이 구현 내에서 코드를 작성하여 메시지를 SQS 대기열로 직접 보낼 수 있습니다.' }, { ans:'B', txt:'You can integrate API Gateway with an SQS queue using the AWS SDK, you can write code within your API Gateway implementation to send messages directly to an SQS queue.' }, { ans:'B', txt:'실생활에서는 SQS가 그렇게 많은 양의 데이터를 처리한다고 믿지 않을 것입니다.' }]
  }
];
