window.QS_SET22 = [
{
  n: 211,
  en: `A DevOps engineer is building an application that uses an AWS Lambda function to query an Amazon Aurora MySQL DB cluster. The Lambda function performs only read queries. Amazon EventBridge events invoke the Lambda function.<br><br>As more events invoke the Lambda function each second, the database's latency increases and the database's throughput decreases. The DevOps engineer needs to improve the performance of the application.<br><br>Which combination of steps will meet these requirements? (Choose three.)`,
  ko: `DevOps 엔지니어가 AWS Lambda 함수를 사용하여 Amazon Aurora MySQL DB 클러스터를 쿼리하는 애플리케이션을 빌드하고 있습니다. Lambda 함수는 읽기 쿼리만 수행합니다. Amazon EventBridge 이벤트가 Lambda 함수를 호출합니다.<br><br>초당 Lambda 함수를 호출하는 이벤트가 많아질수록 데이터베이스의 지연 시간이 증가하고 처리량이 감소합니다. DevOps 엔지니어는 애플리케이션의 성능을 개선해야 합니다.<br><br>이러한 요구 사항을 충족하는 단계 조합은 무엇입니까? (세 가지를 선택하세요.)`,
  type: 'multi', multiCount: 3,
  choices: [
    { k:'A', en:`Use Amazon RDS Proxy to create a proxy. Connect the proxy to the Aurora cluster reader endpoint. Set a maximum connections percentage on the proxy.`, ko:`Amazon RDS Proxy를 사용하여 프록시를 만듭니다. 프록시를 Aurora 클러스터 리더 엔드포인트에 연결합니다. 프록시에서 최대 연결 백분율을 설정합니다.` },
    { k:'B', en:`Implement database connection pooling inside the Lambda code. Set a maximum number of connections on the database connection pool.`, ko:`Lambda 코드 내에서 데이터베이스 연결 풀링을 구현합니다. 데이터베이스 연결 풀에서 최대 연결 수를 설정합니다.` },
    { k:'C', en:`Implement the database connection opening outside the Lambda event handler code.`, ko:`Lambda 이벤트 핸들러 코드 외부에서 데이터베이스 연결 열기를 구현합니다.` },
    { k:'D', en:`Implement the database connection opening and closing inside the Lambda event handler code.`, ko:`Lambda 이벤트 핸들러 코드 내에서 데이터베이스 연결 열기 및 닫기를 구현합니다.` },
    { k:'E', en:`Connect to the proxy endpoint from the Lambda function.`, ko:`Lambda 함수에서 프록시 엔드포인트에 연결합니다.` },
    { k:'F', en:`Connect to the Aurora cluster endpoint from the Lambda function.`, ko:`Lambda 함수에서 Aurora 클러스터 엔드포인트에 연결합니다.` },
  ],
  answer: ['A','C','E'],
  vote: '83% ACE',
  explain: `<p><span class="mark-ok">✅ A — RDS Proxy를 리더 엔드포인트에 연결</span></p><p>RDS Proxy는 데이터베이스 연결을 풀링·재사용하여 Aurora에 대한 연결 부하를 줄입니다. 읽기 전용 쿼리이므로 리더 엔드포인트를 대상으로 하는 것이 적합합니다.</p><p><span class="mark-ok">✅ C — 핸들러 외부에서 DB 연결 초기화</span></p><p>Lambda 핸들러 외부에서 DB 연결을 열면 실행 환경이 재사용될 때 연결이 유지(warm 상태)되어 매 호출마다 새 연결을 맺는 오버헤드를 줄일 수 있습니다.</p><p><span class="mark-ok">✅ E — 프록시 엔드포인트에 연결</span></p><p>Lambda 함수가 Aurora 클러스터 직접이 아닌 RDS Proxy 엔드포인트에 연결하도록 업데이트해야 프록시의 연결 풀링 이점을 실제로 활용할 수 있습니다.</p>`,
  wrong: `<p><span class="mark-no">❌ B</span> — Lambda 코드 내에서 수동으로 연결 풀링을 구현하는 것은 RDS Proxy보다 복잡하고, Lambda의 무상태 특성상 실질적인 풀링 효과가 제한됩니다.</p><p><span class="mark-no">❌ D</span> — 핸들러 내부에서 연결 열기/닫기를 구현하면 매 Lambda 호출마다 새 연결이 생성·소멸되어 오버헤드가 증가합니다.</p><p><span class="mark-no">❌ F</span> — Aurora 클러스터 엔드포인트에 직접 연결하면 RDS Proxy의 이점을 활용할 수 없습니다.</p>`,
  disc: [{ ans:'ACE (83%)', txt:'RDS Proxy + 핸들러 외부 연결 초기화 + 프록시 엔드포인트 사용이 공식 AWS 권장 패턴(Lambda + RDS Proxy 블로그 포스트 참조).' }]
},
{
  n: 212,
  en: `A company has an AWS CloudFormation stack that is deployed in a single AWS account. The company has configured the stack to send event notifications to an Amazon Simple Notification Service (Amazon SNS) topic.<br><br>A DevOps engineer must implement an automated solution that applies a tag to the specific CloudFormation stack instance only after a successful stack update occurs. The DevOps engineer has created an AWS Lambda function that applies and updates this tag for the specific stack instance.<br><br>Which solution will meet these requirements?`,
  ko: `한 회사에 단일 AWS 계정에 배포된 AWS CloudFormation 스택이 있습니다. 이 회사는 스택이 Amazon Simple Notification Service(Amazon SNS) 토픽에 이벤트 알림을 보내도록 구성했습니다.<br><br>DevOps 엔지니어는 성공적인 스택 업데이트가 발생한 후에만 특정 CloudFormation 스택 인스턴스에 태그를 적용하는 자동화된 솔루션을 구현해야 합니다. DevOps 엔지니어는 특정 스택 인스턴스에 이 태그를 적용하고 업데이트하는 AWS Lambda 함수를 만들었습니다.<br><br>어떤 솔루션이 이러한 요구 사항을 충족할까요?`,
  type: 'single',
  choices: [
    { k:'A', en:`Run the AWS-UpdateCloudFormationStack AWS Systems Manager Automation runbook when Systems Manager detects an UPDATE_COMPLETE event for the instance status of the CloudFormation stack. Configure the runbook to invoke the Lambda function.`, ko:`Systems Manager가 CloudFormation 스택의 인스턴스 상태에 대한 UPDATE_COMPLETE 이벤트를 감지하면 AWS-UpdateCloudFormationStack AWS Systems Manager Automation 런북을 실행합니다. Lambda 함수를 호출하도록 런북을 구성합니다.` },
    { k:'B', en:`Create a custom AWS Config rule that produces a compliance change event if the CloudFormation stack has an UPDATE_COMPLETE instance status. Configure AWS Config to directly invoke the Lambda function to automatically remediate the change event.`, ko:`CloudFormation 스택에 UPDATE_COMPLETE 인스턴스 상태가 있는 경우 규정 준수 변경 이벤트를 생성하는 사용자 지정 AWS Config 규칙을 만듭니다. AWS Config를 구성하여 Lambda 함수를 직접 호출하여 변경 이벤트를 자동으로 수정합니다.` },
    { k:'C', en:`Create an Amazon EventBridge rule that matches the UPDATE_COMPLETE event pattern for the instance status of the CloudFormation stack. Configure the rule to invoke the Lambda function.`, ko:`CloudFormation 스택의 인스턴스 상태에 대한 UPDATE_COMPLETE 이벤트 패턴과 일치하는 Amazon EventBridge 규칙을 만듭니다. Lambda 함수를 호출하도록 규칙을 구성합니다.` },
    { k:'D', en:`Adjust the configuration of the CloudFormation stack to send notifications for only an UPDATE_COMPLETE instance status event to the SNS topic. Subscribe the Lambda function to the SNS topic.`, ko:`CloudFormation 스택의 구성을 조정하여 UPDATE_COMPLETE 인스턴스 상태 이벤트에 대한 알림만 SNS 토픽으로 보냅니다. Lambda 함수를 SNS 토픽에 구독합니다.` },
  ],
  answer: ['C'],
  vote: '100% C',
  explain: `<p><span class="mark-ok">✅ C — EventBridge 규칙 + Lambda</span></p><p>Amazon EventBridge는 CloudFormation의 <code>UPDATE_COMPLETE</code> 상태 변경 이벤트를 직접 감지할 수 있습니다. EventBridge 규칙을 통해 해당 이벤트가 발생할 때 Lambda 함수를 즉시 트리거할 수 있어 가장 직접적이고 효율적인 방법입니다. 추가 SNS 구성이 필요 없습니다.</p>`,
  wrong: `<p><span class="mark-no">❌ A</span> — AWS Systems Manager의 AWS-UpdateCloudFormationStack 런북은 스택 업데이트를 수행하는 용도이며, UPDATE_COMPLETE 이벤트를 자동으로 감지하지 않습니다.</p><p><span class="mark-no">❌ B</span> — AWS Config 규칙은 구성 변경을 평가하지만 CloudFormation 스택 업데이트 상태를 실시간으로 감지하는 데는 적합하지 않으며, 불필요한 복잡성을 추가합니다.</p><p><span class="mark-no">❌ D</span> — D도 동작하지만, SNS 구독 + Lambda 방식은 C보다 더 많은 구성 단계가 필요합니다. C가 더 간단하고 직접적입니다.</p>`,
  disc: [{ ans:'C (100%)', txt:'EventBridge + Lambda는 CloudFormation 이벤트 기반 자동화의 표준 패턴. D는 작동하지만 불필요한 SNS 레이어 추가.' }]
},
{
  n: 213,
  en: `A company deploys an application to two AWS Regions. The application creates and stores objects in an Amazon S3 bucket that is in the same Region as the application. Both deployments of the application need to have access to all the objects and their metadata from both Regions. The company has configured two-way replication between the S3 buckets and has enabled S3 Replication metrics on each S3 bucket.<br><br>A DevOps engineer needs to implement a solution that retries the replication process if an object fails to replicate.<br><br>Which solution will meet these requirements?`,
  ko: `한 회사가 두 개의 AWS 리전에 애플리케이션을 배포합니다. 애플리케이션은 애플리케이션과 동일한 리전에 있는 Amazon S3 버킷에 객체를 생성하고 저장합니다. 두 애플리케이션 배포 모두 두 리전의 모든 객체와 해당 메타데이터에 액세스할 수 있어야 합니다. 회사는 S3 버킷 간에 양방향 복제를 구성하고 각 S3 버킷에서 S3 복제 메트릭을 활성화했습니다.<br><br>DevOps 엔지니어는 객체가 복제에 실패하면 복제 프로세스를 재시도하는 솔루션을 구현해야 합니다.<br><br>어떤 솔루션이 이러한 요구 사항을 충족할까요?`,
  type: 'single',
  choices: [
    { k:'A', en:`Create an Amazon EventBridge rule that listens to S3 event notifications for failed replication events. Create an AWS Lambda function that downloads the failed replication object and then runs a PutObject command for the object to the destination bucket. Configure the EventBridge rule to invoke the Lambda function to handle the object that failed to replicate.`, ko:`실패한 복제 이벤트에 대한 S3 이벤트 알림을 수신하는 Amazon EventBridge 규칙을 만듭니다. 실패한 복제 객체를 다운로드한 다음 대상 버킷에 객체에 대한 PutObject 명령을 실행하는 AWS Lambda 함수를 만듭니다. 복제에 실패한 객체를 처리하기 위해 Lambda 함수를 호출하도록 EventBridge 규칙을 구성합니다.` },
    { k:'B', en:`Create an Amazon Simple Queue Service (Amazon SQS) queue. Configure S3 event notifications to send failed replication notifications to the SQS queue. Create an AWS Lambda function that downloads the failed replication object and then runs a PutObject command for the object to the destination bucket. Configure the Lambda function to poll the queue for notifications to process.`, ko:`Amazon Simple Queue Service(Amazon SQS) 대기열을 만듭니다. S3 이벤트 알림을 구성하여 실패한 복제 알림을 SQS 대기열로 보냅니다. 실패한 복제 객체를 다운로드한 다음 대상 버킷에 객체에 대한 PutObject 명령을 실행하는 AWS Lambda 함수를 만듭니다. Lambda 함수가 알림 처리를 위해 대기열을 폴링하도록 구성합니다.` },
    { k:'C', en:`Create an Amazon EventBridge rule that listens to S3 event notifications for failed replications. Create an AWS Lambda function that downloads the failed replication object and then runs a PutObject command for the object to the destination bucket.`, ko:`실패한 복제에 대한 S3 이벤트 알림을 수신하는 Amazon EventBridge 규칙을 만듭니다. 실패한 복제 객체를 다운로드한 다음 대상 버킷에 객체에 대한 PutObject 명령을 실행하는 AWS Lambda 함수를 만듭니다.` },
    { k:'D', en:`Create an AWS Lambda function that will use S3 batch operations to retry the replication on the existing object for a failed replication. Configure S3 event notifications to send failed replication notifications to the Lambda function.`, ko:`S3 배치 작업을 사용하여 실패한 복제에 대한 기존 객체에서 복제를 재시도하는 AWS Lambda 함수를 만듭니다. 실패한 복제 알림을 Lambda 함수로 보내도록 S3 이벤트 알림을 구성합니다.` },
  ],
  answer: ['D'],
  vote: '85% D',
  explain: `<p><span class="mark-ok">✅ D — S3 배치 작업으로 복제 재시도</span></p><p>S3 배치 복제(S3 Batch Replication)는 복제에 실패한 객체를 포함하여 기존 객체에 대해 복제를 재시도할 수 있는 AWS 공식 기능입니다. S3 이벤트 알림으로 실패를 감지하고 Lambda를 통해 S3 배치 작업을 트리거하는 것이 AWS 권장 패턴입니다.</p>`,
  wrong: `<p><span class="mark-no">❌ A, B, C</span> — 객체를 다운로드 후 PutObject로 재업로드하는 방식은 메타데이터(복제 상태, ETag 등)를 보존하지 않을 수 있으며, S3 배치 복제에 비해 신뢰성이 낮습니다. A와 C는 EventBridge 규칙을 구성하지만 Lambda에서 복제를 트리거하는 연결이 불완전합니다.</p>`,
  disc: [{ ans:'D (85%)', txt:'AWS 공식 문서(s3-batch-replication-batch.html): S3 배치 복제는 복제 실패 객체 재시도에 특화된 기능. PutObject 방식(A/B/C)은 복제 메타데이터 손실 위험.' }]
},
{
  n: 214,
  en: `A company needs to implement failover for its application. The application includes an Amazon CloudFront distribution and a public Application Load Balancer (ALB) in an AWS Region. The company has configured the ALB as the default origin for the distribution.<br><br>After some recent application outages, the company wants a zero-second RTO. The company deploys the application to a secondary Region in a warm standby configuration. A DevOps engineer needs to automate the failover of the application to the secondary Region so that HTTP GET requests meet the desired RTO.<br><br>Which solution will meet these requirements?`,
  ko: `한 회사가 애플리케이션에 대한 장애 조치를 구현해야 합니다. 애플리케이션에는 Amazon CloudFront 배포와 AWS 리전의 퍼블릭 Application Load Balancer(ALB)가 포함됩니다. 회사는 ALB를 배포의 기본 오리진으로 구성했습니다.<br><br>최근 애플리케이션 중단 후 회사는 0초 RTO를 원합니다. 회사는 웜 스탠바이 구성에서 보조 리전에 애플리케이션을 배포합니다. DevOps 엔지니어는 HTTP GET 요청이 원하는 RTO를 충족하도록 보조 리전으로의 애플리케이션 장애 조치를 자동화해야 합니다.<br><br>어떤 솔루션이 이러한 요구 사항을 충족할까요?`,
  type: 'single',
  choices: [
    { k:'A', en:`Create a second CloudFront distribution that has the secondary ALB as the default origin. Create Amazon Route 53 alias records that have a failover policy and Evaluate Target Health set to Yes for both CloudFront distributions. Update the application to use the new record set.`, ko:`보조 ALB를 기본 오리진으로 하는 두 번째 CloudFront 배포를 만듭니다. 두 CloudFront 배포 모두에 대해 장애 조치 정책 및 Evaluate Target Health를 Yes로 설정한 Amazon Route 53 별칭 레코드를 만듭니다. 새 레코드 세트를 사용하도록 애플리케이션을 업데이트합니다.` },
    { k:'B', en:`Create a new origin on the distribution for the secondary ALB. Create a new origin group. Set the original ALB as the primary origin. Configure the origin group to fail over for HTTP 5xx status codes. Update the default behavior to use the origin group.`, ko:`보조 ALB에 대한 배포에서 새 오리진을 만듭니다. 새 오리진 그룹을 만듭니다. 원래 ALB를 기본 오리진으로 설정합니다. HTTP 5xx 상태 코드에 대해 장애 조치하도록 오리진 그룹을 구성합니다. 오리진 그룹을 사용하도록 기본 동작을 업데이트합니다.` },
    { k:'C', en:`Create Amazon Route 53 alias records that have a failover policy and Evaluate Target Health set to Yes for both ALBs. Set the TTL of both records to 0. Update the distribution's origin to use the new record set.`, ko:`두 ALB 모두에 대해 장애 조치 정책 및 Evaluate Target Health를 Yes로 설정한 Amazon Route 53 별칭 레코드를 만듭니다. 두 레코드의 TTL을 0으로 설정합니다. 배포의 오리진을 업데이트하여 새 레코드 세트를 사용합니다.` },
    { k:'D', en:`Create a CloudFront function that detects HTTP 5xx status codes. Configure the function to return a 307 Temporary Redirect error response to the secondary ALB if the function detects 5xx status codes. Update the distribution's default behavior to send origin responses to the function.`, ko:`HTTP 5xx 상태 코드를 감지하는 CloudFront 함수를 만듭니다. 함수가 5xx 상태 코드를 감지하면 보조 ALB에 307 임시 리디렉션 오류 응답을 반환하도록 함수를 구성합니다. 배포의 기본 동작을 업데이트하여 원본 응답을 함수에 보냅니다.` },
  ],
  answer: ['B'],
  vote: '100% B',
  explain: `<p><span class="mark-ok">✅ B — CloudFront 오리진 그룹 + 오리진 장애 조치</span></p><p>CloudFront의 오리진 그룹(Origin Group) 기능을 사용하면 기본 오리진이 HTTP 5xx 오류를 반환할 때 자동으로 보조 오리진으로 요청을 라우팅합니다. 이 전환은 CloudFront 엣지 레벨에서 자동으로 발생하므로 DNS TTL이나 Route 53 헬스 체크 전파 지연 없이 실질적인 0초 RTO에 가까운 장애 조치가 가능합니다.</p>`,
  wrong: `<p><span class="mark-no">❌ A</span> — Route 53 장애 조치는 DNS 기반으로 TTL 및 헬스 체크 전파 시간이 있어 RTO가 0초를 보장하지 않습니다.</p><p><span class="mark-no">❌ C</span> — Route 53 별칭 레코드 TTL을 0으로 설정해도 헬스 체크 감지 및 전파에 수십 초가 소요될 수 있습니다.</p><p><span class="mark-no">❌ D</span> — CloudFront 함수는 요청/응답 변환에 사용되며, 5xx를 감지하여 클라이언트에 307 리디렉션을 반환하면 추가 왕복이 필요해 RTO가 증가합니다.</p>`,
  disc: [{ ans:'B (100%)', txt:'CloudFront 오리진 장애 조치는 엣지에서 즉시 발생하여 0초 RTO에 가장 가깝습니다. AWS 문서(high_availability_origin_failover.html) 참조.' }]
},
{
  n: 215,
  en: `A cloud team uses AWS Organizations and AWS IAM Identity Center (AWS Single Sign-On) to manage a company's AWS accounts. The company recently established a research team. The research team requires the ability to fully manage the resources in its account. The research team must not be able to create IAM users.<br><br>The cloud team creates a Research Administrator permission set in IAM Identity Center for the research team. The permission set has the AdministratorAccess AWS managed policy attached. The cloud team must ensure that no one on the research team can create IAM users.<br><br>Which solution will meet these requirements?`,
  ko: `클라우드 팀은 AWS Organizations와 AWS IAM Identity Center(AWS Single Sign-On)를 사용하여 회사의 AWS 계정을 관리합니다. 이 회사는 최근 연구팀을 구성했습니다. 연구팀에는 계정의 리소스를 완전히 관리할 수 있는 기능이 필요합니다. 연구팀은 IAM 사용자를 만들 수 없어야 합니다.<br><br>클라우드 팀은 연구팀을 위해 IAM Identity Center에서 Research Administrator 권한 집합을 만듭니다. 권한 집합에는 AdministratorAccess AWS 관리형 정책이 연결되어 있습니다. 클라우드 팀은 연구팀의 누구도 IAM 사용자를 만들 수 없도록 해야 합니다.<br><br>어떤 솔루션이 이러한 요구 사항을 충족할까요?`,
  type: 'single',
  choices: [
    { k:'A', en:`Create an IAM policy that denies the iam:CreateUser action. Attach the IAM policy to the Research Administrator permission set.`, ko:`<code>iam:CreateUser</code> 작업을 거부하는 IAM 정책을 만듭니다. IAM 정책을 Research Administrator 권한 집합에 연결합니다.` },
    { k:'B', en:`Create an IAM policy that allows all actions except the iam:CreateUser action. Use the IAM policy to set the permissions boundary for the Research Administrator permission set.`, ko:`<code>iam:CreateUser</code> 작업을 제외한 모든 작업을 허용하는 IAM 정책을 만듭니다. IAM 정책을 사용하여 Research Administrator 권한 집합에 대한 권한 경계를 설정합니다.` },
    { k:'C', en:`Create an SCP that denies the iam:CreateUser action. Attach the SCP to the research team's AWS account.`, ko:`<code>iam:CreateUser</code> 작업을 거부하는 SCP를 만듭니다. SCP를 연구팀의 AWS 계정에 연결합니다.` },
    { k:'D', en:`Create an AWS Lambda function that deletes IAM users. Create an Amazon EventBridge rule that detects the IAM CreateUser event. Configure the rule to invoke the Lambda function.`, ko:`IAM 사용자를 삭제하는 AWS Lambda 함수를 만듭니다. IAM CreateUser 이벤트를 감지하는 Amazon EventBridge 규칙을 만듭니다. Lambda 함수를 호출하도록 규칙을 구성합니다.` },
  ],
  answer: ['C'],
  vote: '51% C / 49% A',
  explain: `<p><span class="mark-ok">✅ C — SCP로 계정 수준 차단 (제안 정답)</span></p><p>SCP는 AWS 계정 또는 OU에 직접 연결할 수 있으며, 연결된 계정 내의 모든 IAM 엔티티(사용자, 역할, 루트 포함)에 대해 <code>iam:CreateUser</code>를 거부합니다. 이 방식은 연구팀 계정 전체에 일관되게 적용되어 권한 우회를 방지합니다.</p><p><strong>※ 논쟁 포인트:</strong> A(커뮤니티 49%)도 유효합니다. 권한 집합에 거부 정책을 직접 추가하면 연구팀 사용자에게만 적용되어 더 세밀한 제어가 가능합니다. 시험에서는 C가 제안 정답입니다.</p>`,
  wrong: `<p><span class="mark-no">❌ B</span> — 권한 경계는 최대 허용 권한을 설정하는 것으로, 단순히 CreateUser를 제외하는 방식은 AdministratorAccess와 결합 시 예상치 못한 제한이 생길 수 있습니다.</p><p><span class="mark-no">❌ D</span> — Lambda로 생성된 사용자를 삭제하는 것은 반응적(reactive) 접근으로, 사용자가 일시적으로 존재하는 보안 공백이 발생합니다. 예방적(preventive) 제어가 아닙니다.</p>`,
  disc: [{ ans:'C(51%) vs A(49%) 팽팽', txt:'C는 계정 전체 적용(SCP), A는 연구팀 권한 집합에만 적용. 모두 요건을 충족하지만 시험 제안 정답은 C. SCP는 계정에 직접 연결 가능(docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps_attach.html).' }]
},
{
  n: 216,
  en: `A company releases a new application in a new AWS account. The application includes an AWS Lambda function that processes messages from an Amazon Simple Queue Service (Amazon SQS) standard queue. The Lambda function stores the results in an Amazon S3 bucket for further downstream processing. The Lambda function needs to process the messages within a specific period of time after the messages are published. The Lambda function has a batch size of 10 messages and takes a few seconds to process a batch of messages.<br><br>As load increases on the application's first day of service, messages in the queue accumulate at a greater rate than the Lambda function can process the messages. Some messages miss the required processing timelines. The logs show that many messages in the queue have data that is not valid. The company needs to meet the timeline requirements for messages that have valid data.<br><br>Which solution will meet these requirements?`,
  ko: `한 회사가 새 AWS 계정에서 새 애플리케이션을 출시합니다. 이 애플리케이션에는 Amazon Simple Queue Service(Amazon SQS) 표준 대기열에서 메시지를 처리하는 AWS Lambda 함수가 포함되어 있습니다. Lambda 함수는 추가 다운스트림 처리를 위해 Amazon S3 버킷에 결과를 저장합니다. Lambda 함수는 메시지가 게시된 후 특정 기간 내에 메시지를 처리해야 합니다. Lambda 함수의 배치 크기는 10개 메시지이며 메시지 배치를 처리하는 데 몇 초가 걸립니다.<br><br>첫 서비스 날 부하가 증가함에 따라 대기열의 메시지가 Lambda 함수가 처리할 수 있는 속도보다 더 빠른 속도로 누적됩니다. 일부 메시지는 필요한 처리 타임라인을 놓칩니다. 로그에 따르면 대기열의 많은 메시지에 유효하지 않은 데이터가 있습니다. 이 회사는 유효한 데이터가 있는 메시지에 대한 타임라인 요구 사항을 충족해야 합니다.<br><br>이러한 요구 사항을 충족하는 솔루션은 무엇입니까?`,
  type: 'single',
  choices: [
    { k:'A', en:`Increase the Lambda function's batch size. Change the SQS standard queue to an SQS FIFO queue. Request a Lambda concurrency increase in the AWS Region.`, ko:`Lambda 함수의 배치 크기를 늘립니다. SQS 표준 대기열을 SQS FIFO 대기열로 변경합니다. AWS 리전에서 Lambda 동시성 증가를 요청합니다.` },
    { k:'B', en:`Reduce the Lambda function's batch size. Increase the SQS message throughput quota. Request a Lambda concurrency increase in the AWS Region.`, ko:`Lambda 함수의 배치 크기를 줄입니다. SQS 메시지 처리량 할당량을 늘립니다. AWS 리전에서 Lambda 동시성 증가를 요청합니다.` },
    { k:'C', en:`Increase the Lambda function's batch size. Configure S3 Transfer Acceleration on the S3 bucket. Configure an SQS dead-letter queue.`, ko:`Lambda 함수의 배치 크기를 늘립니다. S3 버킷에서 S3 Transfer Acceleration을 구성합니다. SQS Dead-Letter 대기열을 구성합니다.` },
    { k:'D', en:`Keep the Lambda function's batch size the same. Configure the Lambda function to report failed batch items. Configure an SQS dead-letter queue.`, ko:`Lambda 함수의 배치 크기를 동일하게 유지합니다. 실패한 배치 항목을 보고하도록 Lambda 함수를 구성합니다. SQS Dead-Letter 대기열을 구성합니다.` },
  ],
  answer: ['D'],
  vote: '89% D',
  explain: `<p><span class="mark-ok">✅ D — 실패 항목 보고 + DLQ</span></p><p>핵심 문제는 유효하지 않은 데이터가 있는 메시지가 배치 전체를 실패시켜 유효한 메시지까지 지연시키는 것입니다. Lambda의 <code>ReportBatchItemFailures</code> 기능을 활성화하면 배치 내 특정 메시지만 실패로 표시하고 나머지 유효한 메시지는 정상 처리됩니다. SQS Dead-Letter Queue(DLQ)를 구성하면 반복 실패 메시지를 격리하여 유효한 메시지의 처리 흐름이 차단되지 않습니다.</p>`,
  wrong: `<p><span class="mark-no">❌ A</span> — FIFO 대기열로 변경하면 Lambda 동시성이 제한되어 오히려 처리 속도가 느려질 수 있습니다.</p><p><span class="mark-no">❌ B</span> — 배치 크기를 줄이면 Lambda 호출 횟수가 늘어나 오히려 동시성 부하가 증가할 수 있습니다.</p><p><span class="mark-no">❌ C</span> — S3 Transfer Acceleration은 S3 업로드 속도를 개선하지만 SQS 처리 병목을 해결하지 못합니다. DLQ만으로는 유효하지 않은 메시지로 인한 배치 전체 실패 문제를 해결하지 못합니다.</p>`,
  disc: [{ ans:'D (89%)', txt:'ReportBatchItemFailures로 부분 배치 실패 보고 + DLQ로 무효 메시지 격리가 핵심. 유효 메시지의 타임라인 요건 충족. AWS prescriptive guidance 참조.' }]
},
{
  n: 217,
  en: `A company has an application that runs on AWS Lambda and sends logs to Amazon CloudWatch Logs. An Amazon Kinesis data stream is subscribed to the log groups in CloudWatch Logs. A single consumer Lambda function processes the logs from the data stream and stores the logs in an Amazon S3 bucket.<br><br>The company's DevOps team has noticed high latency during the processing and ingestion of some logs.<br><br>Which combination of steps will reduce the latency? (Choose three.)`,
  ko: `한 회사에 AWS Lambda에서 실행되고 Amazon CloudWatch Logs에 로그를 보내는 애플리케이션이 있습니다. Amazon Kinesis 데이터 스트림이 CloudWatch Logs의 로그 그룹에 구독되어 있습니다. 단일 소비자 Lambda 함수가 데이터 스트림의 로그를 처리하고 Amazon S3 버킷에 로그를 저장합니다.<br><br>회사의 DevOps 팀은 일부 로그의 처리 및 수집 중에 높은 지연 시간을 발견했습니다.<br><br>어떤 단계 조합이 지연 시간을 줄일 수 있을까요? (세 가지를 선택하세요.)`,
  type: 'multi', multiCount: 3,
  choices: [
    { k:'A', en:`Create a data stream consumer with enhanced fan-out. Set the Lambda function that processes the logs as the consumer.`, ko:`향상된 팬아웃(enhanced fan-out)을 사용하여 데이터 스트림 소비자를 만듭니다. 로그를 처리하는 Lambda 함수를 소비자로 설정합니다.` },
    { k:'B', en:`Increase the ParallelizationFactor setting in the Lambda event source mapping.`, ko:`Lambda 이벤트 소스 매핑에서 ParallelizationFactor 설정을 늘립니다.` },
    { k:'C', en:`Configure reserved concurrency for the Lambda function that processes the logs.`, ko:`로그를 처리하는 Lambda 함수에 대해 예약된 동시성을 구성합니다.` },
    { k:'D', en:`Increase the batch size in the Kinesis data stream.`, ko:`Kinesis 데이터 스트림의 배치 크기를 늘립니다.` },
    { k:'E', en:`Turn off the ReportBatchItemFailures setting in the Lambda event source mapping.`, ko:`Lambda 이벤트 소스 매핑에서 ReportBatchItemFailures 설정을 끕니다.` },
    { k:'F', en:`Increase the number of shards in the Kinesis data stream.`, ko:`Kinesis 데이터 스트림의 샤드 수를 늘립니다.` },
  ],
  answer: ['A','B','F'],
  vote: '100% ABF',
  explain: `<p><span class="mark-ok">✅ A — Enhanced Fan-Out 소비자</span></p><p>Kinesis Enhanced Fan-Out을 사용하면 소비자가 샤드당 초당 최대 2MB의 전용 처리량으로 데이터를 수신합니다. 다른 소비자와 처리량을 공유하지 않아 지연 시간이 크게 줄어듭니다.</p><p><span class="mark-ok">✅ B — ParallelizationFactor 증가</span></p><p>Kinesis와 Lambda의 이벤트 소스 매핑에서 ParallelizationFactor를 늘리면 동일 샤드에서 여러 Lambda 인스턴스가 병렬로 처리할 수 있어 처리량이 향상됩니다.</p><p><span class="mark-ok">✅ F — 샤드 수 증가</span></p><p>Kinesis 데이터 스트림의 샤드 수를 늘리면 스트림의 총 데이터 용량과 처리 병렬성이 증가하여 지연 시간이 감소합니다.</p>`,
  wrong: `<p><span class="mark-no">❌ C</span> — 예약된 동시성은 최대 동시 인스턴스를 제한하며 지연 시간 개선에 직접적인 도움이 되지 않습니다.</p><p><span class="mark-no">❌ D</span> — 배치 크기 증가는 처리량은 늘리지만 각 레코드의 지연 시간은 오히려 증가할 수 있습니다.</p><p><span class="mark-no">❌ E</span> — ReportBatchItemFailures 비활성화는 오류 처리 방식에만 영향을 미치며 지연 시간 개선과 무관합니다.</p>`,
  disc: [{ ans:'ABF (100%)', txt:'Enhanced fan-out(A) + ParallelizationFactor(B) + 샤드 수 증가(F)의 조합이 Kinesis→Lambda 처리 지연 감소의 3대 요소.' }]
},
{
  n: 218,
  en: `A company operates sensitive workloads across the AWS accounts that are in the company's organization in AWS Organizations. The company uses an IP address range to delegate IP addresses for Amazon VPC CIDR blocks and all non-cloud hardware.<br><br>The company needs a solution that prevents principals that are outside the company's IP address range from performing AWS actions in the organization's accounts.<br><br>Which solution will meet these requirements?`,
  ko: `한 회사가 AWS Organizations의 회사 조직에 있는 AWS 계정 전반에서 민감한 워크로드를 운영합니다. 이 회사는 Amazon VPC CIDR 블록과 모든 비클라우드 하드웨어에 대한 IP 주소를 위임하기 위해 IP 주소 범위를 사용합니다.<br><br>이 회사는 회사의 IP 주소 범위 밖에 있는 주체가 조직의 계정에서 AWS 작업을 수행하지 못하도록 하는 솔루션이 필요합니다.<br><br>어떤 솔루션이 이러한 요구 사항을 충족할까요?`,
  type: 'single',
  choices: [
    { k:'A', en:`Configure AWS Firewall Manager for the organization. Create an AWS Network Firewall policy that allows only source traffic from the company's IP address range. Set the policy scope to all accounts in the organization.`, ko:`조직에 대한 AWS Firewall Manager를 구성합니다. 회사의 IP 주소 범위에서만 소스 트래픽을 허용하는 AWS Network Firewall 정책을 만듭니다. 정책 범위를 조직의 모든 계정으로 설정합니다.` },
    { k:'B', en:`In Organizations, create an SCP that denies source IP addresses that are outside of the company's IP address range. Attach the SCP to the organization's root.`, ko:`조직에서 회사의 IP 주소 범위 밖의 소스 IP 주소를 거부하는 SCP를 만듭니다. SCP를 조직의 루트에 연결합니다.` },
    { k:'C', en:`Configure Amazon GuardDuty for the organization. Create a GuardDuty trusted IP address list for the company's IP range. Activate the trusted IP list for the organization.`, ko:`조직에 Amazon GuardDuty를 구성합니다. 회사의 IP 범위에 대한 GuardDuty 신뢰할 수 있는 IP 주소 목록을 만듭니다. 조직에 대한 신뢰할 수 있는 IP 목록을 활성화합니다.` },
    { k:'D', en:`In Organizations, create an SCP that allows source IP addresses that are inside of the company's IP address range. Attach the SCP to the organization's root.`, ko:`조직에서 회사의 IP 주소 범위 내에 있는 소스 IP 주소를 허용하는 SCP를 만듭니다. SCP를 조직의 루트에 연결합니다.` },
  ],
  answer: ['B'],
  vote: '100% B',
  explain: `<p><span class="mark-ok">✅ B — SCP로 IP 범위 밖 거부 + 루트에 연결</span></p><p>SCP에서 <code>aws:SourceIp</code> 조건 키를 사용하여 회사의 IP 주소 범위 밖에서 오는 요청을 거부하면 조직의 모든 계정에서 일관되게 적용됩니다. SCP를 조직 루트에 연결하면 모든 계정과 OU에 자동으로 상속됩니다. 이 방식은 AWS IAM 공식 예제(deny-ip)에도 소개된 표준 패턴입니다.</p>`,
  wrong: `<p><span class="mark-no">❌ A</span> — AWS Network Firewall은 VPC 내 네트워크 트래픽을 제어하는 것으로, AWS API 호출(콘솔, CLI, SDK)을 차단하지 않습니다.</p><p><span class="mark-no">❌ C</span> — GuardDuty의 신뢰할 수 있는 IP 목록은 해당 IP에서 발생하는 활동에 대한 GuardDuty 경고를 억제하는 것이지, 접근을 차단하지 않습니다.</p><p><span class="mark-no">❌ D</span> — SCP는 허용 목록(Allow)만으로는 동작하지 않습니다. SCP는 최대 허용 권한을 제한하는 것이며, Allow만으로는 다른 IP 주소를 차단할 수 없습니다.</p>`,
  disc: [{ ans:'B (100%)', txt:'SCP + aws:SourceIp 조건으로 IP 범위 외 거부는 AWS IAM 공식 예제(reference_policies_examples_aws_deny-ip.html)에 명시된 표준 패턴.' }]
},
{
  n: 219,
  en: `A company deploys an application in two AWS Regions. The application currently uses an Amazon S3 bucket in the primary Region to store data.<br><br>A DevOps engineer needs to ensure that the application is highly available in both Regions. The DevOps engineer has created a new S3 bucket in the secondary Region. All existing and new objects must be in both S3 buckets. The application must fail over between the Regions with no data loss.<br><br>Which combination of steps will meet these requirements with the MOST operational efficiency? (Choose three.)`,
  ko: `한 회사가 두 개의 AWS 리전에 애플리케이션을 배포합니다. 애플리케이션은 현재 기본 리전의 Amazon S3 버킷을 사용하여 데이터를 저장합니다.<br><br>DevOps 엔지니어는 두 리전 모두에서 애플리케이션이 고가용성인지 확인해야 합니다. DevOps 엔지니어는 보조 리전에 새 S3 버킷을 만들었습니다. 모든 기존 및 새 객체는 두 S3 버킷 모두에 있어야 합니다. 애플리케이션은 데이터 손실 없이 두 리전 간에 장애 조치되어야 합니다.<br><br>어떤 단계 조합이 이러한 요구 사항을 가장 높은 운영 효율성으로 충족할 수 있을까요? (세 가지를 선택하세요.)`,
  type: 'multi', multiCount: 3,
  choices: [
    { k:'A', en:`Create a new IAM role that allows the Amazon S3 and S3 Batch Operations service principals to assume the role that has the necessary permissions for S3 replication.`, ko:`Amazon S3 및 S3 Batch Operations 서비스 주체가 S3 복제에 필요한 권한이 있는 역할을 수임할 수 있도록 새로운 IAM 역할을 생성합니다.` },
    { k:'B', en:`Create a new IAM role that allows the AWS Batch service principal to assume the role that has the necessary permissions for S3 replication.`, ko:`AWS Batch 서비스 주체가 S3 복제에 필요한 권한이 있는 역할을 수임할 수 있도록 새로운 IAM 역할을 생성합니다.` },
    { k:'C', en:`Create an S3 Cross-Region Replication (CRR) rule on the source S3 bucket. Configure the rule to use the IAM role for Amazon S3 to replicate to the target S3 bucket.`, ko:`소스 S3 버킷에서 S3 Cross-Region Replication(CRR) 규칙을 만듭니다. Amazon S3의 IAM 역할을 사용하여 대상 S3 버킷에 복제하도록 규칙을 구성합니다.` },
    { k:'D', en:`Create a two-way replication rule on the source S3 bucket. Configure the rule to use the IAM role for Amazon S3 to replicate to the target S3 bucket.`, ko:`소스 S3 버킷에서 양방향 복제 규칙을 만듭니다. Amazon S3의 IAM 역할을 사용하여 대상 S3 버킷에 복제하도록 규칙을 구성합니다.` },
    { k:'E', en:`Create an AWS Batch job that has an AWS Fargate orchestration type. Configure the job to use the IAM role for AWS Batch. Specify a Bash command to use the AWS CLI to synchronize the contents of the source S3 bucket and the target S3 bucket.`, ko:`AWS Fargate 오케스트레이션 유형이 있는 AWS Batch 작업을 만듭니다. AWS Batch에 대한 IAM 역할을 사용하도록 작업을 구성합니다. AWS CLI를 사용하여 소스 S3 버킷과 대상 S3 버킷의 내용을 동기화하는 Bash 명령을 지정합니다.` },
    { k:'F', en:`Create an operation in S3 Batch Operations to replicate the contents of the source S3 bucket to the target S3 bucket. Configure the operation to use the IAM role for Amazon S3.`, ko:`S3 Batch Operations에서 소스 S3 버킷의 내용을 대상 S3 버킷으로 복제하는 작업을 만듭니다. Amazon S3에 대한 IAM 역할을 사용하도록 작업을 구성합니다.` },
  ],
  answer: ['A','D','F'],
  vote: '66% ADF',
  explain: `<p><span class="mark-ok">✅ A — S3 및 S3 Batch Operations 서비스 주체를 위한 IAM 역할</span></p><p>S3 복제와 S3 배치 작업 모두 실행하려면 Amazon S3 서비스 주체(<code>s3.amazonaws.com</code>)와 S3 배치 작업 서비스 주체(<code>batchoperations.s3.amazonaws.com</code>) 모두가 역할을 수임할 수 있어야 합니다.</p><p><span class="mark-ok">✅ D — 양방향 복제 규칙</span></p><p>두 리전 모두에서 쓰기가 발생하는 액티브-액티브 구성에서는 양방향 복제가 필요합니다. 장애 조치 후 보조 리전에서 생성된 데이터도 기본 리전으로 복제되어야 데이터 손실이 없습니다.</p><p><span class="mark-ok">✅ F — S3 Batch Operations으로 기존 객체 복제</span></p><p>CRR/양방향 복제 규칙은 설정 이후 생성된 새 객체에만 적용됩니다. 기존 객체를 복제하려면 S3 Batch Operations의 복제 작업을 별도로 실행해야 합니다.</p>`,
  wrong: `<p><span class="mark-no">❌ B</span> — AWS Batch 서비스 주체는 S3 복제와 관련이 없습니다.</p><p><span class="mark-no">❌ C</span> — CRR은 단방향 복제로, 보조 리전에서 기본 리전으로 복제되지 않아 데이터 손실 위험이 있습니다.</p><p><span class="mark-no">❌ E</span> — AWS Batch + CLI 동기화는 수동적이고 비효율적인 방법으로, 운영 효율성이 낮습니다.</p>`,
  disc: [{ ans:'ADF(66%) vs ACF(34%)', txt:'데이터 손실 없는 장애 조치를 위해 양방향 복제(D)가 필수. C는 단방향이라 보조→기본 복제 없음. F는 기존 객체 복제. A는 S3+BatchOps 서비스 주체 모두 포함.' }]
},
{
  n: 220,
  en: `A company uses an organization in AWS Organizations to manage multiple AWS accounts. The company needs an automated process across all AWS accounts to isolate any compromised Amazon EC2 instances when the instances receive a specific tag.<br><br>Which combination of steps will meet these requirements? (Choose two.)`,
  ko: `한 회사가 AWS Organizations의 조직을 사용하여 여러 AWS 계정을 관리합니다. 이 회사는 인스턴스가 특정 태그를 받을 때 손상된 Amazon EC2 인스턴스를 격리하기 위해 모든 AWS 계정에서 자동화된 프로세스가 필요합니다.<br><br>이러한 요구 사항을 충족하는 단계 조합은 무엇입니까? (두 가지를 선택하세요.)`,
  type: 'multi', multiCount: 2,
  choices: [
    { k:'A', en:`Use AWS CloudFormation StackSets to deploy the CloudFormation stacks in all AWS accounts.`, ko:`AWS CloudFormation StackSets를 사용하여 모든 AWS 계정에 CloudFormation 스택을 배포합니다.` },
    { k:'B', en:`Create an SCP that has a Deny statement for the ec2:* action with a condition of "aws:RequestTag/isolation": false.`, ko:`<code>"aws:RequestTag/isolation": false</code> 조건이 있는 <code>ec2:*</code> 작업에 대한 Deny 문이 있는 SCP를 만듭니다.` },
    { k:'C', en:`Attach the SCP to the root of the organization.`, ko:`SCP를 조직의 루트에 연결합니다.` },
    { k:'D', en:`Create an AWS CloudFormation template that creates an EC2 instance role that has no IAM policies attached. Configure the template to have a security group that has an explicit Deny rule on all traffic. Use the CloudFormation template to create an AWS Lambda function that attaches the IAM role to instances. Configure the Lambda function to add a network ACL. Set up an Amazon EventBridge rule to invoke the Lambda function when a specific tag is applied to a compromised EC2 instance.`, ko:`IAM 정책이 연결되지 않은 EC2 인스턴스 역할을 만드는 AWS CloudFormation 템플릿을 만듭니다. 모든 트래픽에 대한 명시적 거부 규칙이 있는 보안 그룹을 갖도록 템플릿을 구성합니다. CloudFormation 템플릿을 사용하여 인스턴스에 IAM 역할을 연결하는 AWS Lambda 함수를 만듭니다. Lambda 함수를 구성하여 네트워크 ACL을 추가합니다. 특정 태그가 손상된 EC2 인스턴스에 적용될 때 Lambda 함수를 호출하도록 Amazon EventBridge 규칙을 설정합니다.` },
    { k:'E', en:`Create an AWS CloudFormation template that creates an EC2 instance role that has no IAM policies attached. Configure the template to have a security group that has no inbound rules or outbound rules. Use the CloudFormation template to create an AWS Lambda function that attaches the IAM role to instances. Configure the Lambda function to replace any existing security groups with the new security group. Set up an Amazon EventBridge rule to invoke the Lambda function when a specific tag is applied to a compromised EC2 instance.`, ko:`IAM 정책이 연결되지 않은 EC2 인스턴스 역할을 만드는 AWS CloudFormation 템플릿을 만듭니다. 인바운드 규칙이나 아웃바운드 규칙이 없는 보안 그룹을 갖도록 템플릿을 구성합니다. CloudFormation 템플릿을 사용하여 인스턴스에 IAM 역할을 연결하는 AWS Lambda 함수를 만듭니다. 기존 보안 그룹을 새 보안 그룹으로 교체하도록 Lambda 함수를 구성합니다. 특정 태그가 손상된 EC2 인스턴스에 적용될 때 Lambda 함수를 호출하도록 Amazon EventBridge 규칙을 설정합니다.` },
  ],
  answer: ['A','E'],
  vote: '79% AE',
  explain: `<p><span class="mark-ok">✅ A — CloudFormation StackSets로 전 계정 배포</span></p><p>StackSets를 사용하면 조직 내 모든 AWS 계정에 동일한 CloudFormation 스택(Lambda 함수, EventBridge 규칙, 격리용 보안 그룹 등)을 일관되게 배포할 수 있습니다.</p><p><span class="mark-ok">✅ E — 빈 보안 그룹 교체 + Lambda + EventBridge</span></p><p>인바운드/아웃바운드 규칙이 없는 보안 그룹으로 교체하면 모든 네트워크 트래픽이 차단되어 EC2 인스턴스가 네트워크적으로 격리됩니다. IAM 역할도 교체하여 AWS API 접근도 차단합니다. EventBridge 규칙이 태그 적용 이벤트를 감지하여 Lambda를 트리거합니다.</p>`,
  wrong: `<p><span class="mark-no">❌ B, C</span> — SCP로 <code>ec2:*</code>를 거부하면 손상된 인스턴스에 대한 네트워크 격리가 아니라 EC2 API 호출 자체를 차단합니다. 이는 격리가 아닌 API 레벨의 차단으로 인스턴스는 여전히 네트워크에 연결되어 있습니다.</p><p><span class="mark-no">❌ D</span> — 보안 그룹은 명시적 거부(Deny) 규칙을 지원하지 않습니다. 보안 그룹은 허용(Allow) 기반으로 동작하며, 규칙이 없으면 기본적으로 거부됩니다. D는 잘못된 설명입니다.</p>`,
  disc: [{ ans:'AE (79%)', txt:'격리 = 네트워크 트래픽 차단. 빈 보안 그룹으로 교체(E) + StackSets로 전 계정 배포(A). SCP(B/C)는 API 차단이지 네트워크 격리가 아님. 보안 그룹은 명시적 Deny 불지원(D 오류).' }]
}
];
