window.QS_SET05 = [
{
  n:41,
  en:`A DevOps engineer is building a multistage pipeline with AWS CodePipeline to build, verify, stage, test, and deploy an application. A manual approval stage is required between the test stage and the deploy stage. The development team uses a custom chat tool with webhook support that requires near-real-time notifications.<br><br><strong>How should the DevOps engineer configure status updates for pipeline activity and approval requests to post to the chat tool?</strong>`,
  ko:`DevOps 엔지니어가 AWS CodePipeline을 사용하여 애플리케이션을 빌드, 검증, 스테이징, 테스트 및 배포하기 위한 다단계 파이프라인을 구축하고 있습니다. 테스트 단계와 배포 단계 사이에 수동 승인 단계가 필요합니다. 개발팀은 거의 실시간 알림이 필요한 웹훅 지원이 있는 사용자 지정 채팅 도구를 사용합니다.<br><br><strong>DevOps 엔지니어는 파이프라인 활동 및 채팅 도구에 게시할 승인 요청에 대한 상태 업데이트를 어떻게 구성해야 합니까?</strong>`,
  type:'single',
  choices:[
    {k:'A', en:`Create an Amazon CloudWatch Logs subscription that filters on CodePipeline Pipeline Execution State Change. Publish subscription events to an Amazon Simple Notification Service (Amazon SNS) topic. Subscribe the chat webhook URL to the SNS topic, and complete the subscription validation.`, ko:`CodePipeline 파이프라인 실행 상태 변경을 필터링하는 Amazon CloudWatch Logs 구독을 만듭니다. Amazon SNS 토픽에 구독 이벤트를 게시합니다. 채팅 웹훅 URL을 SNS 토픽에 구독하고 구독 검증을 완료합니다.`},
    {k:'B', en:`Create an AWS Lambda function that is invoked by AWS CloudTrail events. When a CodePipeline Pipeline Execution State Change event is detected, send the event details to the chat webhook URL.`, ko:`AWS CloudTrail 이벤트에서 호출되는 AWS Lambda 함수를 만듭니다. CodePipeline 파이프라인 실행 상태 변경 이벤트가 감지되면 이벤트 세부 정보를 채팅 웹훅 URL로 보냅니다.`},
    {k:'C', en:`Create an Amazon EventBridge rule that filters on CodePipeline Pipeline Execution State Change. Publish the events to an Amazon Simple Notification Service (Amazon SNS) topic. Create an AWS Lambda function that sends event details to the chat webhook URL. Subscribe the function to the SNS topic.`, ko:`CodePipeline 파이프라인 실행 상태 변경을 필터링하는 Amazon EventBridge 규칙을 만듭니다. Amazon SNS 토픽에 이벤트를 게시합니다. 채팅 웹훅 URL에 이벤트 세부 정보를 보내는 AWS Lambda 함수를 만듭니다. 함수를 SNS 토픽에 구독합니다.`},
    {k:'D', en:`Modify the pipeline code to send the event details to the chat webhook URL at the end of each stage. Parameterize the URL so that each pipeline can send to a different URL based on the pipeline environment.`, ko:`파이프라인 코드를 수정하여 각 단계의 끝에 이벤트 세부 정보를 채팅 웹훅 URL로 보냅니다. 각 파이프라인이 파이프라인 환경에 따라 다른 URL로 보낼 수 있도록 URL을 매개변수화합니다.`},
  ],
  answer:['C'],
  vote:'100% C',
  explain:`<p><span class="mark-ok">✅ C — EventBridge → SNS → Lambda → 채팅 웹훅</span></p><p>CodePipeline 파이프라인 실행 상태 변경 이벤트는 <strong>Amazon EventBridge</strong>(기본 이벤트 버스)에서 발생합니다. EventBridge 규칙 → SNS 토픽 → Lambda 함수(웹훅 호출) 순서로 연결하면 거의 실시간으로 채팅 도구에 알림을 보낼 수 있습니다. SNS에 Lambda를 구독시켜 채팅 웹훅 URL에 맞는 요청 형식으로 변환해 전송합니다.</p>`,
  wrong:`<p><span class="mark-no">❌ A</span> — CloudWatch Logs 구독 필터는 로그 분석용이며 CodePipeline 상태 이벤트를 직접 구독할 수 없습니다. 또한 SNS가 임의 웹훅 URL을 직접 구독할 수 없습니다(HTTPS 엔드포인트 구독 검증 필요).</p><p style="margin-top:8px;"><span class="mark-no">❌ B</span> — CloudTrail은 API 호출 로깅용이며 Lambda를 직접 트리거하지 않습니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ D</span> — 파이프라인 코드를 수정하는 것은 불필요한 복잡성을 추가하며 유지 관리 부담이 큽니다.</p>`,
  disc:[{ans:'C (100%)',txt:'시험 팁: 이벤트 또는 액션과 관련된 문제라면 → EventBridge를 활용합니다. CodePipeline 실행 상태 변경은 API 호출이 아닌 이벤트이므로 EventBridge로 캡처해야 합니다.'}]
},
{
  n:42,
  en:`A company's application development team uses Linux-based Amazon EC2 instances as bastion hosts. Inbound SSH access to the bastion hosts is restricted to specific IP addresses, as defined in the associated security groups. The company's security team wants to receive a notification if the security group rules are modified to allow SSH access from any IP address.<br><br><strong>What should a DevOps engineer do to meet this requirement?</strong>`,
  ko:`회사의 애플리케이션 개발팀은 Linux 기반 Amazon EC2 인스턴스를 베스천 호스트로 사용합니다. 베스천 호스트에 대한 인바운드 SSH 액세스는 연관된 보안 그룹에 정의된 대로 특정 IP 주소로 제한됩니다. 회사의 보안팀은 보안 그룹 규칙이 모든 IP 주소에서 SSH 액세스를 허용하도록 수정되면 알림을 받고 싶어합니다.<br><br><strong>DevOps 엔지니어는 이 요구 사항을 충족하기 위해 무엇을 해야 합니까?</strong>`,
  type:'single',
  choices:[
    {k:'A', en:`Create an Amazon EventBridge rule with a source of aws.cloudtrail and the event name AuthorizeSecurityGroupIngress. Define an Amazon Simple Notification Service (Amazon SNS) topic as the target.`, ko:`aws.cloudtrail 소스와 AuthorizeSecurityGroupIngress 이벤트 이름으로 Amazon EventBridge 규칙을 만듭니다. Amazon SNS 토픽을 대상으로 정의합니다.`},
    {k:'B', en:`Enable Amazon GuardDuty and check the findings for security groups in AWS Security Hub. Configure an Amazon EventBridge rule with a custom pattern that matches GuardDuty events with an output of NON_COMPLIANT. Define an Amazon Simple Notification Service (Amazon SNS) topic as the target.`, ko:`Amazon GuardDuty를 활성화하고 AWS Security Hub에서 보안 그룹에 대한 결과를 확인합니다. NON_COMPLIANT 출력이 있는 GuardDuty 이벤트와 일치하는 사용자 지정 패턴으로 Amazon EventBridge 규칙을 구성합니다. Amazon SNS 토픽을 대상으로 정의합니다.`},
    {k:'C', en:`Create an AWS Config rule by using the restricted-ssh managed rule to check whether security groups disallow unrestricted incoming SSH traffic. Configure automatic remediation to publish a message to an Amazon Simple Notification Service (Amazon SNS) topic.`, ko:`restricted-ssh 관리 규칙을 사용하여 AWS Config 규칙을 만들어 보안 그룹이 무제한 수신 SSH 트래픽을 허용하지 않는지 확인합니다. Amazon SNS 토픽에 메시지를 게시하도록 자동 수정을 구성합니다.`},
    {k:'D', en:`Enable Amazon Inspector. Include the Common Vulnerabilities and Exposures-1.1 rules package to check the security groups that are associated with the bastion hosts. Configure Amazon Inspector to publish a message to an Amazon Simple Notification Service (Amazon SNS) topic.`, ko:`Amazon Inspector를 활성화합니다. Common Vulnerabilities and Exposures-1.1 규칙 패키지를 포함하여 베스천 호스트와 연관된 보안 그룹을 확인합니다. Amazon Inspector를 구성하여 Amazon SNS 토픽에 메시지를 게시합니다.`},
  ],
  answer:['C'],
  vote:'69% C',
  explain:`<p><span class="mark-ok">✅ C — AWS Config restricted-ssh 관리형 규칙 + SNS</span></p><p>AWS Config의 <strong>restricted-ssh</strong> 관리형 규칙은 보안 그룹의 수신 SSH 트래픽 IP 주소가 <code>0.0.0.0/0</code>인 경우(모든 IP 허용) NON_COMPLIANT로 표시합니다. 이는 정확히 "모든 IP 주소에서 SSH 접근 허용" 조건을 탐지합니다. SNS 토픽에 알림을 게시하도록 구성하면 요구 사항을 충족합니다.</p>`,
  wrong:`<p><span class="mark-no">❌ A</span> — AuthorizeSecurityGroupIngress 이벤트는 보안 그룹에 대한 <em>모든</em> 인바운드 규칙 변경을 캡처합니다. 0.0.0.0/0(모든 IP) 여부를 구분하지 않으므로 너무 광범위합니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ B</span> — GuardDuty는 위협 탐지 서비스이며 보안 그룹 설정의 규정 준수를 직접 확인하지 않습니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ D</span> — Inspector는 EC2 인스턴스의 취약점을 스캔하는 서비스이며 이 사용 사례에 적합하지 않습니다.</p>`,
  disc:[{ans:'C (69%) vs A (31%)',txt:'논쟁: A는 모든 SG 변경에 알림을 보내고, C는 0.0.0.0/0만 탐지합니다. "모든 IP 주소에서 SSH 허용"은 0.0.0.0/0을 의미하므로 C가 요구사항에 더 정확합니다. restricted-ssh 규칙: CIDR이 0.0.0.0/0이면 NON_COMPLIANT 반환.'}]
},
{
  n:43,
  en:`A DevOps team manages an API running on-premises that serves as a backend for an Amazon API Gateway endpoint. Customers have been complaining about high response latencies, which the development team has verified using the API Gateway latency metrics in Amazon CloudWatch. To identify the cause, the team needs to collect relevant data without introducing additional latency.<br><br><strong>Which actions should be taken to accomplish this? (Choose two.)</strong>`,
  ko:`DevOps 팀은 Amazon API Gateway 엔드포인트의 백엔드 역할을 하는 온프레미스에서 실행되는 API를 관리합니다. 고객들은 높은 응답 지연에 대해 불평해 왔으며, 개발 팀은 Amazon CloudWatch의 API Gateway 지연 메트릭을 사용하여 이를 확인했습니다. 원인을 파악하기 위해 팀은 추가 지연을 발생시키지 않고 관련 데이터를 수집해야 합니다.<br><br><strong>이를 달성하기 위해 어떤 조치를 취해야 합니까? (두 가지를 선택하세요.)</strong>`,
  type:'multi',
  multiCount:2,
  choices:[
    {k:'A', en:`Install the CloudWatch agent server side and configure the agent to upload relevant logs to CloudWatch.`, ko:`CloudWatch 에이전트 서버 측을 설치하고 에이전트가 관련 로그를 CloudWatch에 업로드하도록 구성합니다.`},
    {k:'B', en:`Enable AWS X-Ray tracing in API Gateway, modify the application to capture request segments, and upload those segments to X-Ray during each request.`, ko:`API Gateway에서 AWS X-Ray 추적을 활성화하고, 요청 세그먼트를 캡처하도록 애플리케이션을 수정하고, 각 요청 중에 해당 세그먼트를 X-Ray에 업로드합니다.`},
    {k:'C', en:`Enable AWS X-Ray tracing in API Gateway, modify the application to capture request segments, and use the X-Ray daemon to upload segments to X-Ray.`, ko:`API Gateway에서 AWS X-Ray 추적을 활성화하고, 요청 세그먼트를 캡처하도록 애플리케이션을 수정하고, X-Ray 데몬을 사용하여 세그먼트를 X-Ray에 업로드합니다.`},
    {k:'D', en:`Modify the on-premises application to send log information back to API Gateway with each request.`, ko:`온프레미스 애플리케이션을 수정하여 각 요청과 함께 로그 정보를 API Gateway로 다시 보냅니다.`},
    {k:'E', en:`Modify the on-premises application to calculate and upload statistical data relevant to the API service requests to CloudWatch metrics.`, ko:`온프레미스 애플리케이션을 수정하여 API 서비스 요청과 관련된 통계 데이터를 계산하고 CloudWatch 메트릭에 업로드합니다.`},
  ],
  answer:['A','C'],
  vote:'88% AC',
  explain:`<p><span class="mark-ok">✅ A</span>: 온프레미스 서버에 <strong>CloudWatch 에이전트</strong>를 설치하면 애플리케이션 로그를 CloudWatch Logs에 업로드합니다. 에이전트는 백그라운드에서 동작하므로 추가 지연이 없습니다.</p><p style="margin-top:8px;"><span class="mark-ok">✅ C</span>: API Gateway에서 X-Ray 추적을 활성화하고, <strong>X-Ray 데몬</strong>을 사용하면 세그먼트를 비동기적으로 배치 업로드하므로 요청 처리 중 추가 지연이 발생하지 않습니다.</p>`,
  wrong:`<p><span class="mark-no">❌ B</span> — 각 요청 중에 세그먼트를 직접 X-Ray에 업로드하면 동기 처리로 인해 추가 지연이 발생합니다. X-Ray 데몬(C)을 사용해야 합니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ D, E</span> — 애플리케이션을 수정하여 요청마다 추가 데이터를 보내거나 계산하면 지연이 증가합니다.</p>`,
  disc:[{ans:'AC (88%)',txt:'X-Ray 데몬은 백그라운드에서 세그먼트를 일괄 처리하고 업로드하므로 추가 지연이 없습니다. CloudWatch 에이전트도 백그라운드에서 비동기적으로 로그를 업로드합니다.'}]
},
{
  n:44,
  en:`A company has an application that is using a MySQL-compatible Amazon Aurora Multi-AZ DB cluster as the database. A cross-Region read replica has been created for disaster recovery purposes. A DevOps engineer wants to automate the promotion of the replica so it becomes the primary database instance in the event of a failure.<br><br><strong>Which solution will accomplish this?</strong>`,
  ko:`한 회사에 MySQL 호환 Amazon Aurora Multi-AZ DB 클러스터를 데이터베이스로 사용하는 애플리케이션이 있습니다. 재해 복구 목적으로 교차 리전 읽기 복제본이 생성되었습니다. DevOps 엔지니어는 장애 발생 시 복제본이 기본 데이터베이스 인스턴스가 되도록 복제본의 승격을 자동화하려고 합니다.<br><br><strong>어떤 솔루션이 이를 달성합니까?</strong>`,
  type:'single',
  choices:[
    {k:'A', en:`Configure a latency-based Amazon Route 53 CNAME with health checks so it points to both the primary and replica endpoints. Subscribe an Amazon SNS topic to Amazon RDS failure notifications from AWS CloudTrail and use that topic to invoke an AWS Lambda function that will promote the replica instance as the primary.`, ko:`상태 점검을 통해 지연 기반 Amazon Route 53 CNAME을 구성하여 기본 및 복제본 엔드포인트를 모두 가리키도록 합니다. Amazon SNS 토픽을 AWS CloudTrail의 Amazon RDS 실패 알림에 구독하고 해당 토픽을 사용하여 복제본 인스턴스를 기본으로 승격하는 AWS Lambda 함수를 호출합니다.`},
    {k:'B', en:`Create an Aurora custom endpoint to point to the primary database instance. Configure the application to use this endpoint. Configure AWS CloudTrail to run an AWS Lambda function to promote the replica instance and modify the custom endpoint to point to the newly promoted instance.`, ko:`기본 데이터베이스 인스턴스를 가리키도록 Aurora 사용자 지정 엔드포인트를 만듭니다. 이 엔드포인트를 사용하도록 애플리케이션을 구성합니다. AWS CloudTrail을 구성하여 AWS Lambda 함수를 실행하여 복제본 인스턴스를 승격시키고 사용자 지정 엔드포인트를 수정하여 새로 승격된 인스턴스를 가리키도록 합니다.`},
    {k:'C', en:`Create an AWS Lambda function to modify the application's AWS CloudFormation template to promote the replica, apply the template to update the stack, and point the application to the newly promoted instance. Create an Amazon CloudWatch alarm to invoke this Lambda function after the failure event occurs.`, ko:`AWS Lambda 함수를 생성하여 복제본을 승격시키고, 템플릿을 적용하여 스택을 업데이트하고, 애플리케이션을 새로 승격된 인스턴스로 가리키도록 애플리케이션의 AWS CloudFormation 템플릿을 수정합니다. 실패 이벤트가 발생한 후 이 Lambda 함수를 호출하기 위해 Amazon CloudWatch 알람을 생성합니다.`},
    {k:'D', en:`Store the Aurora endpoint in AWS Systems Manager Parameter Store. Create an Amazon EventBridge event that detects the database failure and runs an AWS Lambda function to promote the replica instance and update the endpoint URL stored in AWS Systems Manager Parameter Store. Code the application to reload the endpoint from Parameter Store if a database connection fails.`, ko:`AWS Systems Manager Parameter Store에 Aurora 엔드포인트를 저장합니다. 데이터베이스 장애를 감지하고 AWS Lambda 함수를 실행하여 복제본 인스턴스를 승격하고 AWS Systems Manager Parameter Store에 저장된 엔드포인트 URL을 업데이트하는 Amazon EventBridge 이벤트를 만듭니다. 데이터베이스 연결이 실패하면 Parameter Store에서 엔드포인트를 다시 로드하도록 애플리케이션을 코딩합니다.`},
  ],
  answer:['D'],
  vote:'100% D',
  explain:`<p><span class="mark-ok">✅ D — EventBridge → Lambda → 복제본 승격 + Parameter Store 업데이트</span></p><p>EventBridge가 RDS 장애 이벤트를 감지하면 Lambda 함수를 트리거하여 교차 리전 읽기 복제본을 기본 인스턴스로 승격합니다. 새 엔드포인트를 <strong>Parameter Store</strong>에 저장하고, 애플리케이션은 연결 실패 시 Parameter Store에서 엔드포인트를 다시 로드합니다. 엔드포인트를 하드코딩하지 않아 자동 장애 조치가 가능합니다.</p>`,
  wrong:`<p><span class="mark-no">❌ A</span> — CloudTrail에서 SNS → Lambda로 복제본을 승격하는 방식은 자동화가 불완전합니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ B</span> — CloudTrail로 Lambda를 직접 트리거할 수 없습니다. EventBridge를 사용해야 합니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ C</span> — CloudFormation 템플릿 수정은 수동 개입이 필요하고 자동화하기 어렵습니다.</p>`,
  disc:[{ans:'D (100%)',txt:'교차 리전 Aurora DR 자동화 패턴: EventBridge(장애 감지) → Lambda(복제본 승격 + Parameter Store 업데이트) → 애플리케이션(연결 실패 시 Parameter Store에서 새 엔드포인트 로드).'}]
},
{
  n:45,
  en:`A company hosts its staging website using an Amazon EC2 instance backed with Amazon EBS storage. The company wants to recover quickly with minimal data losses in the event of network connectivity issues or power failures on the EC2 instance.<br><br><strong>Which solution will meet these requirements?</strong>`,
  ko:`한 회사가 Amazon EBS 스토리지로 백업된 Amazon EC2 인스턴스를 사용하여 스테이징 웹사이트를 호스팅합니다. 이 회사는 EC2 인스턴스에서 네트워크 연결 문제나 정전이 발생할 경우 최소한의 데이터 손실로 빠르게 복구하려고 합니다.<br><br><strong>어떤 솔루션이 이러한 요구 사항을 충족합니까?</strong>`,
  type:'single',
  choices:[
    {k:'A', en:`Add the instance to an EC2 Auto Scaling group with the minimum, maximum, and desired capacity set to 1.`, ko:`최소, 최대 및 원하는 용량을 1로 설정하여 EC2 Auto Scaling 그룹에 인스턴스를 추가합니다.`},
    {k:'B', en:`Add the instance to an EC2 Auto Scaling group with a lifecycle hook to detach the EBS volume when the EC2 instance shuts down or terminates.`, ko:`EC2 인스턴스가 종료되거나 종료될 때 EBS 볼륨을 분리하기 위해 라이프사이클 후크를 사용하여 EC2 Auto Scaling 그룹에 인스턴스를 추가합니다.`},
    {k:'C', en:`Create an Amazon CloudWatch alarm for the StatusCheckFailed System metric and select the EC2 action to recover the instance.`, ko:`StatusCheckFailed System 메트릭에 대한 Amazon CloudWatch 알람을 생성하고 인스턴스를 복구하기 위한 EC2 작업을 선택합니다.`},
    {k:'D', en:`Create an Amazon CloudWatch alarm for the StatusCheckFailed Instance metric and select the EC2 action to reboot the instance.`, ko:`StatusCheckFailed Instance 메트릭에 대한 Amazon CloudWatch 알람을 생성하고 EC2 작업을 선택하여 인스턴스를 재부팅합니다.`},
  ],
  answer:['C'],
  vote:'95% C',
  explain:`<p><span class="mark-ok">✅ C — StatusCheckFailed_System + CloudWatch EC2 복구 작업</span></p><p><strong>StatusCheckFailed_System</strong>은 AWS 기반 시스템(네트워크 연결, 시스템 전원, 물리 호스트 소프트웨어 등) 문제를 감지합니다. CloudWatch 알람의 <strong>"이 인스턴스 복구"</strong> EC2 작업을 설정하면 시스템 장애 발생 시 동일한 EBS 볼륨을 유지한 채 자동으로 인스턴스를 복구합니다. 데이터 손실이 최소화됩니다.</p>`,
  wrong:`<p><span class="mark-no">❌ A</span> — Auto Scaling 그룹에 속한 인스턴스는 간소화된 자동 복구가 시작되지 않습니다. ASG는 손상된 인스턴스를 교체(새 인스턴스 시작)하므로 EBS 데이터가 손실될 수 있습니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ D</span> — StatusCheckFailed_Instance는 인스턴스 소프트웨어/설정 문제를 감지하며 재부팅만 수행합니다. 네트워크 연결 문제나 정전(시스템 레벨 문제)에는 적합하지 않습니다.</p>`,
  disc:[{ans:'C (95%)',txt:'EC2 인스턴스 복구 조건: EBS 백업 인스턴스, Auto Scaling 그룹에 속하지 않아야 함. 복구 후 동일한 인스턴스 ID, EIP, EBS 볼륨, 프라이빗 IP 유지. — AWS EC2 문서'}]
},
{
  n:46,
  en:`A company wants to use AWS development tools to replace its current bash deployment scripts. The company currently deploys a LAMP application to a group of Amazon EC2 instances behind an Application Load Balancer (ALB). During the deployments, the company unit tests the committed application, stops and starts services, unregisters and re-registers instances with the load balancer, and updates file permissions. The company wants to maintain the same deployment functionality through the shift to using AWS services.<br><br><strong>Which solution will meet these requirements?</strong>`,
  ko:`한 회사에서 AWS 개발 도구를 사용하여 현재 bash 배포 스크립트를 대체하려고 합니다. 이 회사는 현재 Application Load Balancer(ALB) 뒤에 있는 Amazon EC2 인스턴스 그룹에 LAMP 애플리케이션을 배포합니다. 배포 중에 회사는 커밋된 애플리케이션을 단위 테스트하고, 서비스를 중지하고 시작하고, 로드 밸런서에서 인스턴스를 등록 취소하고 다시 등록하고, 파일 권한을 업데이트합니다. 이 회사는 AWS 서비스 사용으로 전환하는 동안 동일한 배포 기능을 유지하려고 합니다.<br><br><strong>어떤 솔루션이 이러한 요구 사항을 충족합니까?</strong>`,
  type:'single',
  choices:[
    {k:'A', en:`Use AWS CodeBuild to test the application. Use bash scripts invoked by AWS CodeDeploy's appspec.yml file to restart services, and deregister and register instances with the ALB. Use the appspec.yml file to update file permissions without a custom script.`, ko:`AWS CodeBuild를 사용하여 애플리케이션을 테스트합니다. AWS CodeDeploy의 appspec.yml 파일에서 호출한 bash 스크립트를 사용하여 서비스를 다시 시작하고 ALB에 인스턴스를 등록 해제하고 등록합니다. appspec.yml 파일을 사용하여 사용자 지정 스크립트 없이 파일 권한을 업데이트합니다.`},
    {k:'B', en:`Use AWS CodePipeline to move the application from the AWS CodeCommit repository to AWS CodeDeploy. Use CodeDeploy's deployment group to test the application, unregister and re-register instances with the ALB, and restart services. Use the appspec.yml file to update file permissions without a custom script.`, ko:`AWS CodePipeline을 사용하여 AWS CodeCommit 리포지토리에서 AWS CodeDeploy로 애플리케이션을 이동합니다. CodeDeploy의 배포 그룹을 사용하여 애플리케이션을 테스트하고, ALB로 인스턴스를 등록 해제하고 다시 등록하고, 서비스를 다시 시작합니다. appspec.yml 파일을 사용하여 사용자 지정 스크립트 없이 파일 권한을 업데이트합니다.`},
    {k:'C', en:`Use AWS CodePipeline to move the application source code from the AWS CodeCommit repository to AWS CodeDeploy. Use CodeDeploy to test the application. Use CodeDeploy's appspec.yml file to restart services and update permissions without a custom script. Use AWS CodeBuild to unregister and re-register instances with the ALB.`, ko:`AWS CodePipeline을 사용하여 애플리케이션 소스 코드를 AWS CodeCommit 리포지토리에서 AWS CodeDeploy로 옮깁니다. CodeDeploy를 사용하여 애플리케이션을 테스트합니다. CodeDeploy의 appspec.yml 파일을 사용하여 서비스를 다시 시작하고 사용자 지정 스크립트 없이 권한을 업데이트합니다. AWS CodeBuild를 사용하여 ALB에 인스턴스를 등록 취소하고 다시 등록합니다.`},
    {k:'D', en:`Use AWS CodePipeline to trigger AWS CodeBuild to test the application. Use bash scripts invoked by AWS CodeDeploy's appspec.yml file to restart services. Unregister and re-register the instances in the AWS CodeDeploy deployment group with the ALB. Update the appspec.yml file to update file permissions without a custom script.`, ko:`AWS CodePipeline을 사용하여 AWS CodeBuild를 트리거하여 애플리케이션을 테스트합니다. AWS CodeDeploy의 appspec.yml 파일에서 호출한 bash 스크립트를 사용하여 서비스를 다시 시작합니다. ALB에서 AWS CodeDeploy 배포 그룹의 인스턴스를 등록 해제했다가 다시 등록합니다. 사용자 지정 스크립트 없이 파일 권한을 업데이트하려면 appspec.yml 파일을 업데이트합니다.`},
  ],
  answer:['D'],
  vote:'88% D',
  explain:`<p><span class="mark-ok">✅ D — CodePipeline → CodeBuild(테스트) → CodeDeploy(배포)</span></p><p>CodePipeline이 전체 파이프라인을 조율합니다. CodeBuild가 단위 테스트를 수행하고, CodeDeploy의 appspec.yml이 서비스 재시작·파일 권한 업데이트를 처리합니다. CodeDeploy 배포 그룹이 ALB와 연동하여 인스턴스 등록 해제/재등록을 자동으로 처리합니다.</p>`,
  wrong:`<p><span class="mark-no">❌ A</span> — CodePipeline 없이 CodeBuild → CodeDeploy 연결이 없으므로 파이프라인을 조율할 수 없습니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ B, C</span> — CodeCommit 저장소를 직접 CodeDeploy로 이동하는 것은 불가능합니다. CodeDeploy는 코드를 저장하지 않습니다. 또한 CodeDeploy가 애플리케이션을 테스트하는 것이 아닌 CodeBuild가 테스트해야 합니다.</p>`,
  disc:[{ans:'D (88%)',txt:'AWS LAMP 배포 모범 사례: CodePipeline(조율) → CodeBuild(테스트) → CodeDeploy(배포, appspec.yml로 서비스 관리, 배포 그룹으로 ALB 인스턴스 등록/해제).'}]
},
{
  n:47,
  en:`A company runs an application with an Amazon EC2 and on-premises configuration. A DevOps engineer needs to standardize patching across both environments. Company policy dictates that patching only happens during non-business hours.<br><br><strong>Which combination of actions will meet these requirements? (Choose three.)</strong>`,
  ko:`한 회사가 Amazon EC2와 온프레미스 구성으로 애플리케이션을 실행합니다. DevOps 엔지니어는 두 환경에서 패치를 표준화해야 합니다. 회사 정책에 따르면 패치는 비업무 시간에만 실행해야 합니다.<br><br><strong>이러한 요구 사항을 충족하는 작업 조합은 무엇입니까? (세 가지를 선택하세요.)</strong>`,
  type:'multi',
  multiCount:3,
  choices:[
    {k:'A', en:`Add the physical machines into AWS Systems Manager using Systems Manager Hybrid Activations.`, ko:`Systems Manager Hybrid Activations를 사용하여 물리적 머신을 AWS Systems Manager에 추가합니다.`},
    {k:'B', en:`Attach an IAM role to the EC2 instances, allowing them to be managed by AWS Systems Manager.`, ko:`EC2 인스턴스에 IAM 역할을 연결하여 AWS Systems Manager에서 관리할 수 있도록 합니다.`},
    {k:'C', en:`Create IAM access keys for the on-premises machines to interact with AWS Systems Manager.`, ko:`온프레미스 머신이 AWS Systems Manager와 상호 작용할 수 있도록 IAM 액세스 키를 생성합니다.`},
    {k:'D', en:`Run an AWS Systems Manager Automation document to patch the systems every hour.`, ko:`AWS Systems Manager Automation 문서를 실행하여 매시간 시스템에 패치를 적용합니다.`},
    {k:'E', en:`Use Amazon EventBridge scheduled events to schedule a patch window.`, ko:`Amazon EventBridge 예약된 이벤트를 사용하여 패치 창을 예약합니다.`},
    {k:'F', en:`Use AWS Systems Manager Maintenance Windows to schedule a patch window.`, ko:`AWS Systems Manager Maintenance Windows를 사용하여 패치 창을 예약합니다.`},
  ],
  answer:['A','B','F'],
  vote:'82% ABF',
  explain:`<p><span class="mark-ok">✅ A</span>: <strong>Hybrid Activations</strong>를 사용하여 온프레미스 물리 머신을 Systems Manager 관리 노드로 등록합니다.</p><p style="margin-top:8px;"><span class="mark-ok">✅ B</span>: EC2 인스턴스에 <strong>IAM 역할</strong>을 연결하면 Systems Manager Agent가 AWS와 통신하여 관리됩니다.</p><p style="margin-top:8px;"><span class="mark-ok">✅ F</span>: <strong>Systems Manager Maintenance Windows</strong>는 비업무 시간에 패치를 예약하는 AWS 전용 기능입니다.</p>`,
  wrong:`<p><span class="mark-no">❌ C</span> — 온프레미스 머신에 대한 액세스는 Hybrid Activations(IAM 역할 기반)로 처리합니다. IAM 액세스 키를 온프레미스 머신에 사용하는 것은 보안 모범 사례에 맞지 않습니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ D</span> — 매시간 패치를 실행하는 것은 비업무 시간에만 실행해야 한다는 정책에 위배됩니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ E</span> — AWS에는 패치 예약 전용 서비스(Maintenance Windows)가 있습니다. EventBridge를 사용하면 불필요한 복잡성이 추가됩니다.</p>`,
  disc:[{ans:'ABF (82%)',txt:'Hybrid Activations: 온프레미스 서버, VM, IoT 디바이스 등을 Systems Manager에 등록. EC2는 IAM 역할로, 온프레미스는 Hybrid Activations로 관리. Maintenance Windows로 비업무 시간 패치 예약.'}]
},
{
  n:48,
  en:`A company has chosen AWS to host a new application. The company needs to implement a multi-account strategy. A DevOps engineer creates a new AWS account and an organization in AWS Organizations. The DevOps engineer also creates the OU structure for the organization and sets up a landing zone by using AWS Control Tower.<br><br>The DevOps engineer must implement a solution that automatically deploys resources for new accounts that users create through AWS Control Tower Account Factory. When a user creates a new account, the solution must apply AWS CloudFormation templates and SCPs that are customized for the OU or the account to automatically deploy all the resources that are attached to the account. All the OUs are enrolled in AWS Control Tower.<br><br><strong>Which solution will meet these requirements in the MOST automated way?</strong>`,
  ko:`한 회사가 새 애플리케이션을 호스팅하기 위해 AWS를 선택했습니다. 이 회사는 다중 계정 전략을 구현해야 합니다. DevOps 엔지니어가 AWS Organizations에서 새 AWS 계정과 조직을 만듭니다. DevOps 엔지니어는 또한 조직의 OU 구조를 만들고 AWS Control Tower를 사용하여 랜딩 존을 설정합니다.<br><br>DevOps 엔지니어는 사용자가 AWS Control Tower Account Factory를 통해 만든 새 계정에 대한 리소스를 자동으로 배포하는 솔루션을 구현해야 합니다. 사용자가 새 계정을 만들면 솔루션은 OU 또는 계정에 맞게 사용자 지정된 AWS CloudFormation 템플릿과 SCP를 적용하여 계정에 연결된 모든 리소스를 자동으로 배포해야 합니다. 모든 OU는 AWS Control Tower에 등록됩니다.<br><br><strong>어떤 솔루션이 가장 자동화된 방식으로 이러한 요구 사항을 충족합니까?</strong>`,
  type:'single',
  choices:[
    {k:'A', en:`Use AWS Service Catalog with AWS Control Tower. Create portfolios and products in AWS Service Catalog. Grant granular permissions to provision these resources. Deploy SCPs by using the AWS CLI and JSON documents.`, ko:`AWS Control Tower와 함께 AWS Service Catalog를 사용합니다. AWS Service Catalog에서 포트폴리오와 제품을 만듭니다. 이러한 리소스를 프로비저닝하기 위한 세부적인 권한을 부여합니다. AWS CLI 및 JSON 문서를 사용하여 SCP를 배포합니다.`},
    {k:'B', en:`Deploy CloudFormation stack sets by using the required templates. Enable automatic deployment. Deploy stack instances to the required accounts. Deploy a CloudFormation stack set to the organization's management account to deploy SCPs.`, ko:`필요한 템플릿을 사용하여 CloudFormation 스택 세트를 배포합니다. 자동 배포를 활성화합니다. 필요한 계정에 스택 인스턴스를 배포합니다. SCP를 배포하기 위해 조직의 관리 계정에 CloudFormation 스택 세트를 배포합니다.`},
    {k:'C', en:`Create an Amazon EventBridge rule to detect the CreateManagedAccount event. Configure AWS Service Catalog as the target to deploy resources to any new accounts. Deploy SCPs by using the AWS CLI and JSON documents.`, ko:`CreateManagedAccount 이벤트를 감지하기 위한 Amazon EventBridge 규칙을 만듭니다. AWS Service Catalog를 대상으로 구성하여 모든 새 계정에 리소스를 배포합니다. AWS CLI 및 JSON 문서를 사용하여 SCP를 배포합니다.`},
    {k:'D', en:`Deploy the Customizations for AWS Control Tower (CfCT) solution. Use an AWS CodeCommit repository as the source. In the repository, create a custom package that includes the CloudFormation templates and the SCP JSON documents.`, ko:`AWS Control Tower(CfCT) 솔루션에 대한 사용자 지정을 배포합니다. AWS CodeCommit 리포지토리를 소스로 사용합니다. 리포지토리에서 CloudFormation 템플릿과 SCP JSON 문서를 포함하는 사용자 지정 패키지를 만듭니다.`},
  ],
  answer:['D'],
  vote:'92% D',
  explain:`<p><span class="mark-ok">✅ D — CfCT (Customizations for AWS Control Tower)</span></p><p><strong>CfCT</strong>는 Control Tower 랜딩 존을 사용자 지정하는 전용 솔루션입니다. Control Tower 라이프사이클 이벤트(Account Factory를 통한 새 계정 생성)와 통합되어, 새 계정이 생성될 때 CodeCommit 리포지토리의 CloudFormation 템플릿과 SCP를 자동으로 적용합니다. OU별/계정별 사용자 지정도 지원합니다.</p>`,
  wrong:`<p><span class="mark-no">❌ A, C</span> — AWS CLI로 SCP를 배포하는 것은 수동 작업이며 자동화되지 않습니다. CloudFormation 템플릿 적용도 자동화가 부족합니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ B</span> — CloudFormation StackSets는 Control Tower와 직접 통합되지 않으며, 조직 관리 계정에 스택 인스턴스를 배포할 수 없습니다.</p>`,
  disc:[{ans:'D (92%)',txt:'CfCT 핵심 기능: "새 계정이 Account Factory를 통해 생성되면 계정의 OU에 연결된 모든 리소스가 자동으로 배포됩니다." CloudFormation 템플릿과 SCP를 CodeCommit 리포지토리에서 관리. — AWS Control Tower 공식 문서'}]
},
{
  n:49,
  en:`An online retail company based in the United States plans to expand its operations to Europe and Asia in the next six months. Its product currently runs on Amazon EC2 instances behind an Application Load Balancer. The instances run in an Amazon EC2 Auto Scaling group across multiple Availability Zones. All data is stored in an Amazon Aurora database instance.<br><br>When the product is deployed in multiple regions, the company wants a single product catalog across all regions, but for compliance purposes, its customer information and purchases must be kept in each region.<br><br><strong>How should the company meet these requirements with the LEAST amount of application changes?</strong>`,
  ko:`미국에 본사를 둔 온라인 리테일 회사가 향후 6개월 내에 유럽과 아시아로 사업을 확장할 계획입니다. 제품은 현재 Application Load Balancer 뒤의 Amazon EC2 인스턴스에서 실행됩니다. 인스턴스는 여러 가용 영역에 걸쳐 Amazon EC2 Auto Scaling 그룹에서 실행됩니다. 모든 데이터는 Amazon Aurora 데이터베이스 인스턴스에 저장됩니다.<br><br>제품이 여러 리전에 배포되는 경우 회사는 모든 리전에 걸쳐 단일 제품 카탈로그를 원하지만 규정 준수를 위해 고객 정보와 구매 내역은 각 리전에 보관해야 합니다.<br><br><strong>회사는 최소한의 애플리케이션 변경으로 이러한 요구 사항을 어떻게 충족해야 합니까?</strong>`,
  type:'single',
  choices:[
    {k:'A', en:`Use Amazon Redshift for the product catalog and Amazon DynamoDB tables for the customer information and purchases.`, ko:`제품 카탈로그에는 Amazon Redshift를 사용하고 고객 정보와 구매 내역에는 Amazon DynamoDB 테이블을 사용합니다.`},
    {k:'B', en:`Use Amazon DynamoDB global tables for the product catalog and regional tables for the customer information and purchases.`, ko:`제품 카탈로그에는 Amazon DynamoDB 글로벌 테이블을 사용하고 고객 정보와 구매에는 지역 테이블을 사용합니다.`},
    {k:'C', en:`Use Aurora with read replicas for the product catalog and additional local Aurora instances in each region for the customer information and purchases.`, ko:`제품 카탈로그에 대한 읽기 복제본과 각 리전의 고객 정보 및 구매에 대한 추가 로컬 Aurora 인스턴스를 사용하여 Aurora를 사용합니다.`},
    {k:'D', en:`Use Aurora for the product catalog and Amazon DynamoDB global tables for the customer information and purchases.`, ko:`제품 카탈로그에는 Aurora를 사용하고 고객 정보와 구매 내역에는 Amazon DynamoDB 글로벌 테이블을 사용합니다.`},
  ],
  answer:['C'],
  vote:'100% C',
  explain:`<p><span class="mark-ok">✅ C — Aurora 읽기 복제본(제품 카탈로그) + 로컬 Aurora 인스턴스(고객 정보)</span></p><p>현재 Aurora를 사용 중이므로 <strong>애플리케이션 변경이 최소화</strong>됩니다. 제품 카탈로그는 Aurora 교차 리전 읽기 복제본으로 모든 리전에서 단일 카탈로그를 유지합니다. 고객 정보와 구매 내역은 각 리전의 로컬 Aurora 인스턴스에 저장하여 규정 준수 요건을 충족합니다.</p>`,
  wrong:`<p><span class="mark-no">❌ A</span> — Redshift는 데이터 웨어하우징 전용이며 이 사용 사례에 부적합합니다. DynamoDB로 전환하면 애플리케이션 변경이 큽니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ B, D</span> — DynamoDB(NoSQL)로 전환하면 현재 Aurora(관계형) 기반 애플리케이션의 대대적인 수정이 필요합니다. "최소한의 변경" 요건에 위배됩니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ D</span> — DynamoDB 글로벌 테이블은 고객 정보를 모든 리전에 복제하므로 "각 리전에 보관" 규정 준수 요건에도 위배됩니다.</p>`,
  disc:[{ans:'C (100%)',txt:'최소 변경 원칙: 현재 Aurora 사용 → Aurora 계속 사용. 교차 리전 읽기 복제본으로 제품 카탈로그 글로벌 공유, 리전별 Aurora 인스턴스로 고객 데이터 격리.'}]
},
{
  n:50,
  en:`A company is implementing a well-architected design for its globally accessible API stack. The design needs to ensure both high reliability and fast response times for users located in North America and Europe.<br><br>The API stack contains the following three tiers:<br>- Amazon API Gateway<br>- AWS Lambda<br>- Amazon DynamoDB<br><br><strong>Which solution will meet the requirements?</strong>`,
  ko:`한 회사가 전 세계적으로 접근 가능한 API 스택에 잘 설계된 디자인을 구현하고 있습니다. 이 디자인은 북미와 유럽에 있는 사용자에게 높은 신뢰성과 빠른 응답 시간을 모두 보장해야 합니다.<br><br>API 스택에는 다음 세 가지 계층이 있습니다.<br>- Amazon API Gateway<br>- AWS Lambda<br>- Amazon DynamoDB<br><br><strong>어떤 솔루션이 요구 사항을 충족합니까?</strong>`,
  type:'single',
  choices:[
    {k:'A', en:`Configure Amazon Route 53 to point to API Gateway APIs in North America and Europe using health checks. Configure the APIs to forward requests to a Lambda function in that Region. Configure the Lambda functions to retrieve and update the data in a DynamoDB table in the same Region as the Lambda function.`, ko:`상태 점검을 사용하여 북미와 유럽의 API Gateway API를 가리키도록 Amazon Route 53을 구성합니다. 해당 리전의 Lambda 함수에 요청을 전달하도록 API를 구성합니다. Lambda 함수와 동일한 리전의 DynamoDB 테이블에서 데이터를 검색하고 업데이트하도록 Lambda 함수를 구성합니다.`},
    {k:'B', en:`Configure Amazon Route 53 to point to API Gateway APIs in North America and Europe using latency-based routing and health checks. Configure the APIs to forward requests to a Lambda function in that Region. Configure the Lambda functions to retrieve and update the data in a DynamoDB global table.`, ko:`지연 기반 라우팅 및 상태 확인을 사용하여 북미 및 유럽의 API Gateway API를 가리키도록 Amazon Route 53을 구성합니다. 해당 리전의 Lambda 함수로 요청을 전달하도록 API를 구성합니다. DynamoDB 글로벌 테이블에서 데이터를 검색하고 업데이트하도록 Lambda 함수를 구성합니다.`},
    {k:'C', en:`Configure Amazon Route 53 to point to API Gateway in North America, create a disaster recovery API in Europe, and configure both APIs to forward requests to the Lambda functions in that Region. Retrieve the data from a DynamoDB global table. Deploy a Lambda function to check the North America API health every 5 minutes. In the event of a failure, update Route 53 to point to the disaster recovery API.`, ko:`Amazon Route 53을 북미의 API Gateway를 가리키도록 구성하고, 유럽에서 재해 복구 API를 만들고, 두 API를 모두 해당 리전의 Lambda 함수로 요청을 전달하도록 구성합니다. DynamoDB 글로벌 테이블에서 데이터를 검색합니다. Lambda 함수를 배포하여 5분마다 북미 API 상태를 확인합니다. 장애가 발생하면 Route 53을 업데이트하여 재해 복구 API를 가리킵니다.`},
    {k:'D', en:`Configure Amazon Route 53 to point to API Gateway API in North America using latency-based routing. Configure the API to forward requests to the Lambda function in the Region nearest to the user. Configure the Lambda function to retrieve and update the data in a DynamoDB table.`, ko:`지연 기반 라우팅을 사용하여 북미의 API Gateway API를 가리키도록 Amazon Route 53을 구성합니다. API를 구성하여 사용자에게 가장 가까운 리전의 Lambda 함수로 요청을 전달합니다. Lambda 함수를 구성하여 DynamoDB 테이블의 데이터를 검색하고 업데이트합니다.`},
  ],
  answer:['B'],
  vote:'100% B',
  explain:`<p><span class="mark-ok">✅ B — Route 53 지연 기반 라우팅 + 상태 확인 + DynamoDB 글로벌 테이블</span></p><p><strong>지연 기반 라우팅</strong>은 사용자를 가장 가까운 리전(북미 또는 유럽)의 API Gateway로 안내하여 빠른 응답 시간을 보장합니다. <strong>상태 확인</strong>은 장애 발생 시 트래픽을 정상 리전으로 자동 전환하여 고가용성을 제공합니다. <strong>DynamoDB 글로벌 테이블</strong>은 모든 리전에서 낮은 지연으로 데이터에 접근할 수 있습니다.</p>`,
  wrong:`<p><span class="mark-no">❌ A</span> — 상태 확인만으로는 빠른 응답 시간이 보장되지 않습니다. 지연 기반 라우팅이 없으면 북미 사용자가 유럽 엔드포인트로 라우팅될 수 있습니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ C</span> — 모든 트래픽이 기본적으로 북미로만 라우팅됩니다. 유럽 사용자 근처에 진입점이 없어 지연이 높습니다. 5분 간격 수동 상태 확인은 비효율적입니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ D</span> — 북미 API Gateway만 가리키므로 유럽 진입점이 없습니다. 단일 DynamoDB 테이블은 교차 리전 접근 시 지연이 높습니다.</p>`,
  disc:[{ans:'B (100%)',txt:'지연 기반 라우팅(빠른 응답) + 상태 확인(고가용성) + DynamoDB 글로벌 테이블(글로벌 저지연 데이터 접근) = 북미/유럽 사용자 모두에게 최적화된 글로벌 API 스택.'}]
}
];
