window.QS_SET02 = [
{
  n:11,
  ko:`전자상거래 회사가 새로운 플랫폼을 호스팅하기 위해 AWS를 선택했습니다. 이 회사의 DevOps 팀은 AWS Control Tower 랜딩 존을 구축하기 시작했습니다. DevOps 팀은 AWS IAM Identity Center(AWS Single Sign-On) 내의 ID 저장소를 외부 ID 공급자(IdP)로 설정하고 SAML 2.0을 구성했습니다.<br><br>DevOps 팀은 최소 권한 원칙을 적용하는 강력한 권한 모델을 원합니다. 이 모델은 팀이 팀 자체 리소스만 빌드하고 관리할 수 있도록 허용해야 합니다.<br><br><strong>이러한 요구 사항을 충족하는 단계의 조합은 무엇입니까? (세 가지를 선택하십시오.)</strong>`,
  en:`An ecommerce company has chosen AWS to host its new platform. The company's DevOps team has started building an AWS Control Tower landing zone. The DevOps team has set the identity store within AWS IAM Identity Center (AWS Single Sign-On) to external identity provider (IdP) and has configured SAML 2.0.<br><br>The DevOps team wants a robust permission model that applies the principle of least privilege. The model must allow the team to build and manage only the team's own resources.<br><br><strong>Which combination of steps will meet these requirements? (Choose three.)</strong>`,
  type:'multi',
  multiCount:3,
  choices:[
    {k:'A', ko:`필요한 권한을 포함하는 IAM 정책을 만듭니다. <code>aws:PrincipalTag</code> 조건 키를 포함합니다.`, en:`Create IAM policies that include the required permissions. Include the aws:PrincipalTag condition key.`},
    {k:'B', ko:`권한 집합을 만듭니다. 필요한 권한을 포함하고 <code>aws:PrincipalTag</code> 조건 키를 사용하여 권한 범위를 지정하는 인라인 정책을 연결합니다.`, en:`Create permission sets. Attach an inline policy that includes the required permissions and uses the aws:PrincipalTag condition key to scope the permissions.`},
    {k:'C', ko:`IdP에서 그룹을 만듭니다. 그룹에 사용자를 배치합니다. 그룹을 IAM Identity Center의 계정 및 권한 집합에 할당합니다.`, en:`Create a group in the IdP. Place users in the group. Assign the group to accounts and the permission sets in IAM Identity Center.`},
    {k:'D', ko:`IdP에서 그룹을 만듭니다. 그룹에 사용자를 배치합니다. 그룹을 OU 및 IAM 정책에 할당합니다.`, en:`Create a group in the IdP. Place users in the group. Assign the group to OUs and IAM policies.`},
    {k:'E', ko:`IAM Identity Center에서 액세스 제어를 위한 속성을 활성화합니다. 사용자에게 태그를 적용합니다. 태그를 키-값 쌍으로 매핑합니다.`, en:`Enable attributes for access control in IAM Identity Center. Apply tags to users. Map the tags as key-value pairs.`},
    {k:'F', ko:`IAM Identity Center에서 액세스 제어를 위한 속성을 활성화합니다. IdP에서 속성을 키-값 쌍으로 매핑합니다.`, en:`Enable attributes for access control in IAM Identity Center. Map attributes from the IdP as key-value pairs.`},
  ],
  answer:['B','C','F'],
  vote:'100% BCF',
  explain:`<p><span class="mark-ok">✅ B</span>: IAM Identity Center에서는 <strong>권한 집합(Permission Set)</strong>을 사용합니다. 인라인 정책에 <code>aws:PrincipalTag</code> 조건 키를 포함하면 사용자 속성(태그)에 따라 리소스 접근을 동적으로 제한할 수 있습니다(ABAC 패턴).</p><p style="margin-top:8px;"><span class="mark-ok">✅ C</span>: IdP에서 그룹을 생성하고 사용자를 배치한 후, 그룹을 IAM Identity Center의 계정과 권한 집합에 할당합니다. 이것이 IAM Identity Center의 표준 사용 방식입니다.</p><p style="margin-top:8px;"><span class="mark-ok">✅ F</span>: IdP의 속성(예: department, team)을 키-값 쌍으로 매핑하여 ABAC에 사용합니다. 외부 IdP에는 태그가 아닌 <strong>속성(Attribute)</strong>이 있으므로 F가 E보다 적절합니다.</p>`,
  wrong:`<p><span class="mark-no">❌ A</span> — IAM Identity Center에서는 IAM 정책이 아닌 권한 집합을 사용합니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ D</span> — 그룹을 OU에 할당하거나 IAM 정책에 직접 할당할 수 없습니다. 권한 집합을 통해 계정에 할당해야 합니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ E</span> — 외부 IdP 사용 시 태그를 직접 IAM Identity Center 사용자에게 적용하는 것이 아니라 IdP의 속성(Attribute)을 매핑해야 합니다.</p>`,
  disc:[{ans:'BCF (100%)',txt:'IAM Identity Center + 외부 IdP + ABAC 구성: B(권한 집합+PrincipalTag 조건), C(IdP 그룹→계정+권한집합 할당), F(IdP 속성→키-값 쌍 매핑). IAM 정책 직접 사용(A)이나 태그 직접 적용(E)은 IAM Identity Center 패턴과 맞지 않습니다.'}]
},
{
  n:12,
  ko:`전자상거래 회사에서 주문 내역 페이지에서 주문 처리 상태를 반영하는 데 지연이 발생한다는 보고를 받고 있습니다. 주문 처리 시스템은 예약된 동시성을 사용하는 AWS Lambda 함수로 구성되어 있습니다. Lambda 함수는 Amazon Simple Queue Service(Amazon SQS) 대기열에서 주문 메시지를 처리하고 처리된 주문을 Amazon DynamoDB 테이블에 삽입합니다. DynamoDB 테이블은 읽기 및 쓰기 용량에 대해 자동 확장이 활성화되어 있습니다.<br><br><strong>DevOps 엔지니어는 이 지연을 해결하기 위해 어떤 조치를 취해야 합니까? (두 가지를 선택하십시오.)</strong>`,
  en:`An ecommerce company is receiving reports that its order history page is experiencing delays in reflecting the processing status of orders. The order processing system consists of an AWS Lambda function that uses reserved concurrency. The Lambda function processes order messages from an Amazon Simple Queue Service (Amazon SQS) queue and inserts processed orders into an Amazon DynamoDB table. The DynamoDB table has auto scaling enabled for read and write capacity.<br><br><strong>Which actions should a DevOps engineer take to resolve this delay? (Choose two.)</strong>`,
  type:'multi',
  multiCount:2,
  choices:[
    {k:'A', ko:`SQS 대기열에 대한 <code>ApproximateAgeOfOldestMessage</code> 메트릭을 확인합니다. Lambda 함수 동시성 한도를 늘립니다.`, en:`Check the ApproximateAgeOfOldestMessage metric for the SQS queue. Increase the Lambda function concurrency limit.`},
    {k:'B', ko:`SQS 대기열의 <code>ApproximateAgeOfOldestMessage</code> 메트릭을 확인합니다. SQS 대기열에 대한 재구동(redrive) 정책을 구성합니다.`, en:`Check the ApproximateAgeOfOldestMessage metric for the SQS queue. Configure a redrive policy on the SQS queue.`},
    {k:'C', ko:`SQS 대기열에 대한 <code>NumberOfMessagesSent</code> 메트릭을 확인합니다. SQS 대기열 가시성 타임아웃을 늘립니다.`, en:`Check the NumberOfMessagesSent metric for the SQS queue. Increase the SQS queue visibility timeout.`},
    {k:'D', ko:`DynamoDB 테이블에 대한 <code>WriteThrottleEvents</code> 메트릭을 확인합니다. 테이블의 확장 정책에 대한 최대 쓰기 용량 단위(WCU)를 늘립니다.`, en:`Check the WriteThrottleEvents metric for the DynamoDB table. Increase the maximum write capacity units (WCUs) for the table's scaling policy.`},
    {k:'E', ko:`Lambda 함수의 <code>Throttles</code> 메트릭을 확인합니다. Lambda 함수 타임아웃을 늘립니다.`, en:`Check the Throttles metric for the Lambda function. Increase the Lambda function timeout.`},
  ],
  answer:['A','D'],
  vote:'100% AD',
  explain:`<p><span class="mark-ok">✅ A</span>: <code>ApproximateAgeOfOldestMessage</code>가 높으면 메시지가 오랫동안 처리되지 않고 있다는 신호입니다. Lambda의 예약된 동시성이 너무 낮아 처리 속도가 부족한 경우 동시성 한도를 늘려 처리량을 높입니다.</p><p style="margin-top:8px;"><span class="mark-ok">✅ D</span>: <code>WriteThrottleEvents</code>가 높으면 DynamoDB가 쓰기 작업을 제한하고 있다는 의미입니다. 자동 확장이 활성화되어 있어도 최대 WCU 한도가 낮으면 급격한 트래픽 증가에 대응하지 못합니다. 최대 WCU를 늘려 확장 범위를 넓힙니다.</p>`,
  wrong:`<p><span class="mark-no">❌ B</span> — 재구동 정책은 처리에 실패한 메시지를 DLQ로 이동하는 기능으로, 처리 속도 지연을 해결하지 않습니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ C</span> — 가시성 타임아웃 증가는 메시지 처리 중 중복 처리를 방지하는 설정이며 처리 지연의 직접적인 해결책이 아닙니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ E</span> — Lambda 타임아웃을 늘려도 처리 속도(동시성)는 향상되지 않습니다.</p>`,
  disc:[{ans:'AD (100%)',txt:'지연 원인 진단: A=SQS 대기열 백로그(메시지 처리 지연) → Lambda 동시성 증가로 처리량 향상. D=DynamoDB 쓰기 제한 → 최대 WCU 증가로 자동 확장 범위 확대. 두 가지 병목을 함께 해결해야 합니다.'}]
},
{
  n:13,
  ko:`한 회사에 단일 AWS 리전에서 수백 개의 Amazon EC2 인스턴스를 실행하는 단일 AWS 계정이 있습니다. 계정에서 매 시간 새로운 EC2 인스턴스가 시작되고 종료됩니다. 이 계정에는 1주일 이상 실행된 기존 EC2 인스턴스도 포함됩니다.<br><br>회사의 보안 정책에 따라 실행 중인 모든 EC2 인스턴스는 EC2 인스턴스 프로필을 사용해야 합니다. EC2 인스턴스에 인스턴스 프로필이 연결되지 않은 경우 EC2 인스턴스는 IAM 권한이 할당되지 않은 기본 인스턴스 프로필을 사용해야 합니다.<br><br>DevOps 엔지니어가 계정을 검토하고 인스턴스 프로필 없이 실행 중인 EC2 인스턴스를 발견합니다. 검토하는 동안 DevOps 엔지니어는 인스턴스 프로필 없이 새로운 EC2 인스턴스가 시작되고 있다는 사실도 관찰합니다.<br><br><strong>어떤 솔루션으로 해당 리전의 모든 기존 및 향후 EC2 인스턴스에 인스턴스 프로필이 연결되도록 할 수 있습니까?</strong>`,
  en:`A company has a single AWS account that runs hundreds of Amazon EC2 instances in a single AWS Region. New EC2 instances are launched and terminated each hour in the account. The account also includes existing EC2 instances that have been running for longer than a week.<br><br>The company's security policy requires all running EC2 instances to use an EC2 instance profile. If an EC2 instance does not have an instance profile attached, the EC2 instance must use a default instance profile that has no IAM permissions assigned.<br><br>A DevOps engineer reviews the account and discovers EC2 instances that are running without an instance profile. During the review, the DevOps engineer also observes that new EC2 instances are being launched without an instance profile.<br><br><strong>Which solution will ensure that an instance profile is attached to all existing and future EC2 instances in the Region?</strong>`,
  type:'single',
  choices:[
    {k:'A', ko:`EC2 RunInstances API 호출에 반응하는 Amazon EventBridge 규칙을 구성합니다. AWS Lambda 함수를 호출하여 기본 인스턴스 프로필을 EC2 인스턴스에 연결하도록 규칙을 구성합니다.`, en:`Configure an Amazon EventBridge rule that reacts to EC2 RunInstances API calls. Configure the rule to invoke an AWS Lambda function to attach the default instance profile to the EC2 instances.`},
    {k:'B', ko:`구성 변경의 트리거 유형으로 <code>ec2-instance-profile-attached</code> AWS Config 관리형 규칙을 구성합니다. 기본 인스턴스 프로필을 EC2 인스턴스에 연결하기 위해 AWS Systems Manager Automation 런북을 호출하는 자동 수정 작업을 구성합니다.`, en:`Configure the ec2-instance-profile-attached AWS Config managed rule with a trigger type of configuration changes. Configure an automatic remediation action that invokes an AWS Systems Manager Automation runbook to attach the default instance profile to the EC2 instances.`},
    {k:'C', ko:`EC2 StartInstances API 호출에 반응하는 Amazon EventBridge 규칙을 구성합니다. AWS Systems Manager Automation 런북을 호출하여 기본 인스턴스 프로필을 EC2 인스턴스에 연결하도록 규칙을 구성합니다.`, en:`Configure an Amazon EventBridge rule that reacts to EC2 StartInstances API calls. Configure the rule to invoke an AWS Systems Manager Automation runbook to attach the default instance profile to the EC2 instances.`},
    {k:'D', ko:`구성 변경의 트리거 유형으로 <code>iam-role-managed-policy-check</code> AWS Config 관리형 규칙을 구성합니다. 기본 인스턴스 프로필을 EC2 인스턴스에 연결하기 위해 AWS Lambda 함수를 호출하는 자동 수정 작업을 구성합니다.`, en:`Configure the iam-role-managed-policy-check AWS Config managed rule with a trigger type of configuration changes. Configure an automatic remediation action that invokes an AWS Lambda function to attach the default instance profile to the EC2 instances.`},
  ],
  answer:['B'],
  vote:'100% B',
  explain:`<p><span class="mark-ok">✅ B — ec2-instance-profile-attached Config 관리형 규칙 + SSM Automation 수정 작업</span></p><p>AWS Config의 <code>ec2-instance-profile-attached</code> 관리형 규칙은 <strong>기존 인스턴스와 새 인스턴스 모두</strong>에 대해 지속적으로 인스턴스 프로필 연결 여부를 평가합니다. 구성 변경 트리거로 설정하면 새 인스턴스 시작 시에도 즉시 평가됩니다. SSM Automation 런북(<code>AWSSupport-GrantPermissionsToIAMUser</code> 등)을 수정 작업으로 지정하여 자동으로 기본 프로필을 연결합니다.</p>`,
  wrong:`<p><span class="mark-no">❌ A</span> — RunInstances API는 새로 시작되는 인스턴스만 처리합니다. 기존에 실행 중인 인스턴스는 처리하지 못합니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ C</span> — StartInstances는 중지된 인스턴스를 시작할 때의 이벤트입니다. 모든 케이스를 커버하지 못합니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ D</span> — <code>iam-role-managed-policy-check</code>는 IAM 역할의 관리형 정책을 검사하는 규칙으로, EC2 인스턴스 프로필 연결 여부 확인에 적합하지 않습니다.</p>`,
  disc:[{ans:'B (100%)',txt:'ec2-instance-profile-attached Config 관리형 규칙은 인스턴스 프로필이 연결되지 않은 EC2 인스턴스를 식별합니다. SSM Automation으로 수정 작업을 자동화합니다. — AWS Config 문서'}]
},
{
  n:14,
  ko:`DevOps 엔지니어가 AWS Lambda 함수를 사용하는 서버리스 애플리케이션에 대한 지속적인 배포 파이프라인을 구축하고 있습니다. 이 회사는 실패한 배포로 인한 고객 영향을 줄이고자 합니다. 또한 이 회사는 문제를 모니터링하고자 합니다.<br><br><strong>어떤 배포 단계 구성이 이러한 요구 사항을 충족합니까?</strong>`,
  en:`A DevOps engineer is building a continuous deployment pipeline for a serverless application that uses AWS Lambda functions. The company wants to reduce the customer impact of an unsuccessful deployment. The company also wants to monitor for issues.<br><br><strong>Which deploy stage configuration will meet these requirements?</strong>`,
  type:'single',
  choices:[
    {k:'A', ko:`AWS Serverless Application Model(AWS SAM) 템플릿을 사용하여 서버리스 애플리케이션을 정의합니다. AWS CodeDeploy를 사용하여 <code>Canary10Percent15Minutes</code> 배포 기본 설정 유형으로 Lambda 함수를 배포합니다. Amazon CloudWatch 알람을 사용하여 함수의 상태를 모니터링합니다.`, en:`Use an AWS Serverless Application Model (AWS SAM) template to define the serverless application. Use AWS CodeDeploy to deploy the Lambda functions with the Canary10Percent15Minutes Deployment Preference Type. Use Amazon CloudWatch alarms to monitor the health of the functions.`},
    {k:'B', ko:`AWS CloudFormation을 사용하여 새 스택 업데이트를 게시하고 모든 리소스에 Amazon CloudWatch 알람을 포함합니다. 개발자가 AWS CloudFormation 변경 세트를 확인하고 승인할 수 있도록 AWS CodePipeline 승인 작업을 설정합니다.`, en:`Use AWS CloudFormation to publish a new stack update, and include Amazon CloudWatch alarms on all resources. Set up an AWS CodePipeline approval action for a developer to verify and approve the AWS CloudFormation change set.`},
    {k:'C', ko:`AWS CloudFormation을 사용하여 모든 스택 업데이트에 새 버전을 게시하고 모든 리소스에 Amazon CloudWatch 알람을 포함합니다. <code>AWS::Lambda::Alias</code> 리소스의 <code>RoutingConfig</code> 속성을 사용하여 스택 업데이트 중에 트래픽 라우팅을 업데이트합니다.`, en:`Use AWS CloudFormation to publish a new version on every stack update, and include Amazon CloudWatch alarms on all resources. Use the RoutingConfig property of the AWS::Lambda::Alias resource to update the traffic routing during the stack update.`},
    {k:'D', ko:`AWS CodeBuild를 사용하여 Lambda 함수에 테스트용 샘플 이벤트 페이로드를 추가합니다. 함수의 새 버전을 게시하고 Amazon CloudWatch 알람을 포함합니다. 프로덕션 별칭을 업데이트하여 새 버전을 가리킵니다. 알람이 ALARM 상태일 때 롤백이 발생하도록 구성합니다.`, en:`Use AWS CodeBuild to add sample event payloads for testing to the Lambda functions. Publish a new version of the functions, and include Amazon CloudWatch alarms. Update the production alias to point to the new version. Configure rollbacks to occur when an alarm is in the ALARM state.`},
  ],
  answer:['A'],
  vote:'83% A',
  explain:`<p><span class="mark-ok">✅ A — AWS SAM + CodeDeploy Canary + CloudWatch 알람</span></p><p>AWS SAM은 서버리스 애플리케이션 정의에 최적화된 프레임워크입니다. <code>Canary10Percent15Minutes</code> 배포 유형은 처음 15분간 트래픽의 10%만 새 버전으로 전송하고, 문제가 없으면 나머지를 전환합니다. CloudWatch 알람이 ALARM 상태가 되면 CodeDeploy가 자동으로 롤백합니다.</p><p style="margin-top:8px;"><em>💡 팁: Lambda + CloudFormation 관련 시험 문제는 대부분 SAM이 정답입니다.</em></p>`,
  wrong:`<p><span class="mark-no">❌ B</span> — 수동 승인 작업은 배포 속도를 늦추며 자동화된 롤백 메커니즘을 제공하지 않습니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ D</span> — CodeBuild는 빌드와 테스트를 위한 도구이며 점진적 배포(카나리아)를 직접 지원하지 않습니다.</p>`,
  disc:[{ans:'A (83%)',txt:'SAM 배포 기본 설정 유형: Canary10Percent15Minutes, Canary10Percent5Minutes, Linear10PercentEvery10Minutes 등. CloudWatch 알람과 연동하여 자동 롤백이 구성됩니다. — AWS SAM 공식 문서'}]
},
{
  n:15,
  ko:`애플리케이션을 실행하기 위해 DevOps 엔지니어는 퍼블릭 서브넷에서 퍼블릭 IP 주소로 Amazon EC2 인스턴스를 시작합니다. 사용자 데이터 스크립트는 애플리케이션 아티팩트를 가져와서 시작 시 인스턴스에 설치합니다. 이제 애플리케이션의 보안 분류가 변경되어 인스턴스가 인터넷에 액세스할 수 없이 실행되어야 합니다. 인스턴스가 성공적으로 시작되고 정상으로 표시되지만 애플리케이션이 설치되지 않은 것 같습니다.<br><br><strong>다음 중 어떤 것이 새 규칙을 준수하면서 애플리케이션을 성공적으로 설치합니까?</strong>`,
  en:`To run an application, a DevOps engineer launches an Amazon EC2 instance with public IP addresses in a public subnet. A user data script obtains the application artifacts and installs them on the instances upon launch. A change to the security classification of the application now requires the instances to run with no access to the internet. While the instances launch successfully and show as healthy, the application does not seem to be installed.<br><br><strong>Which of the following should successfully install the application while complying with the new rule?</strong>`,
  type:'single',
  choices:[
    {k:'A', ko:`Elastic IP 주소가 연결된 퍼블릭 서브넷에서 인스턴스를 시작합니다. 애플리케이션이 설치되고 실행되면 나중에 Elastic IP 주소를 분리하기 위한 스크립트를 실행합니다.`, en:`Launch the instances in a public subnet with Elastic IP addresses attached. Once the application is installed and running, run a script to disassociate the Elastic IP addresses afterwards.`},
    {k:'B', ko:`NAT 게이트웨이를 설정합니다. EC2 인스턴스를 프라이빗 서브넷에 배포합니다. 프라이빗 서브넷의 경로 테이블을 업데이트하여 NAT 게이트웨이를 기본 경로로 사용합니다.`, en:`Set up a NAT gateway. Deploy the EC2 instances to a private subnet. Update the private subnet's route table to use the NAT gateway as the default route.`},
    {k:'C', ko:`Amazon S3 버킷에 애플리케이션 아티팩트를 게시하고 S3에 대한 VPC 엔드포인트를 만듭니다. EC2 인스턴스에 IAM 인스턴스 프로필을 할당하여 S3 버킷에서 애플리케이션 아티팩트를 읽을 수 있도록 합니다.`, en:`Publish the application artifacts to an Amazon S3 bucket and create a VPC endpoint for S3. Assign an IAM instance profile to the EC2 instances so they can read the application artifacts from the S3 bucket.`},
    {k:'D', ko:`애플리케이션 인스턴스에 대한 보안 그룹을 만들고 아티팩트 저장소로의 아웃바운드 트래픽만 허용합니다. 설치가 완료되면 보안 그룹 규칙을 제거합니다.`, en:`Create a security group for the application instances and allow only outbound traffic to the artifact repository. Remove the security group rule once the install is complete.`},
  ],
  answer:['C'],
  vote:'91% C',
  explain:`<p><span class="mark-ok">✅ C — S3 버킷 + VPC 엔드포인트 + IAM 인스턴스 프로필</span></p><p>S3 VPC 게이트웨이 엔드포인트를 사용하면 EC2 인스턴스에서 인터넷 게이트웨이나 NAT 장치 없이 Amazon S3에 직접 접근할 수 있습니다. 이는 완전히 인터넷을 통하지 않는 AWS 내부 네트워크를 사용합니다. IAM 인스턴스 프로필로 S3 버킷 읽기 권한을 부여합니다.</p>`,
  wrong:`<p><span class="mark-no">❌ B</span> — NAT 게이트웨이는 인스턴스에서 인터넷으로 아웃바운드 접근을 허용합니다. 요구사항은 "인터넷에 액세스할 수 없이"이므로 NAT 게이트웨이도 규정을 위반합니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ A</span> — 설치 중에 잠시라도 인터넷에 접근하는 것은 새 보안 규정을 위반합니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ D</span> — 여전히 인터넷에 있는 외부 저장소에 접근하는 것이므로 규정을 위반합니다.</p>`,
  disc:[{ans:'C (91%)',txt:'S3 VPC 게이트웨이 엔드포인트는 추가 비용 없이 VPC에서 S3에 직접 접근합니다. 인터넷 게이트웨이나 NAT 장치가 필요하지 않습니다. — AWS VPC PrivateLink 문서'}]
},
{
  n:16,
  ko:`개발팀은 AWS CodeCommit을 사용하여 애플리케이션 코드의 버전을 제어하고 AWS CodePipeline을 사용하여 소프트웨어 배포를 조율합니다. 이 팀은 파이프라인이 코드 변경 사항을 통합하도록 원격 메인 브랜치를 트리거로 사용하기로 결정했습니다. 개발자는 코드 변경 사항을 CodeCommit 리포지토리에 푸시했지만 파이프라인이 10분이 지나도 아무런 반응이 없다는 것을 알아챘습니다.<br><br><strong>이 문제를 해결하려면 다음 중 어떤 조치를 취해야 합니까?</strong>`,
  en:`A development team is using AWS CodeCommit to version control application code and AWS CodePipeline to orchestrate software deployments. The team has decided to use a remote main branch as the trigger for the pipeline to integrate code changes. A developer has pushed code changes to the CodeCommit repository, but noticed that the pipeline had no reaction, even after 10 minutes.<br><br><strong>Which of the following actions should be taken to troubleshoot this issue?</strong>`,
  type:'single',
  choices:[
    {k:'A', ko:`파이프라인을 트리거하기 위해 메인 브랜치에 대한 Amazon EventBridge 규칙이 생성되었는지 확인합니다.`, en:`Check that an Amazon EventBridge rule has been created for the main branch to trigger the pipeline.`},
    {k:'B', ko:`CodePipeline 서비스 역할에 CodeCommit 저장소에 액세스할 수 있는 권한이 있는지 확인합니다.`, en:`Check that the CodePipeline service role has permission to access the CodeCommit repository.`},
    {k:'C', ko:`개발자의 IAM 역할에 CodeCommit 저장소에 푸시할 수 있는 권한이 있는지 확인합니다.`, en:`Check that the developer's IAM role has permission to push to the CodeCommit repository.`},
    {k:'D', ko:`Amazon CloudWatch Logs의 CodeCommit 오류로 인해 파이프라인이 시작되지 않았는지 확인합니다.`, en:`Check to see if the pipeline failed to start because of CodeCommit errors in Amazon CloudWatch Logs.`},
  ],
  answer:['A'],
  vote:'60% A (37% B)',
  explain:`<p><span class="mark-ok">✅ A — EventBridge 규칙 확인</span></p><p>CodePipeline이 CodeCommit 소스에서 자동으로 트리거되려면 <strong>Amazon EventBridge 규칙</strong>이 필요합니다. 콘솔을 통해 파이프라인을 생성하면 자동으로 EventBridge 규칙이 생성되지만, CLI나 IaC로 생성 시 직접 만들어야 합니다. 파이프라인에 "아무 반응이 없다"는 것은 트리거 자체가 작동하지 않았다는 의미로, EventBridge 규칙 미설정이 가장 가능성 높은 원인입니다.</p>`,
  wrong:`<p><span class="mark-no">❌ B</span> — 권한 문제였다면 파이프라인이 시작은 되었다가 "권한 거부" 오류와 함께 즉시 실패했을 것입니다. 10분간 아무 반응 없음은 트리거 자체 문제를 시사합니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ C</span> — 개발자가 이미 저장소에 성공적으로 푸시했으므로 푸시 권한은 문제없습니다.</p><p style="margin-top:8px;"><em>참고: B도 일부 전문가들이 지지(37%)하지만, A가 공식 권장 사항입니다.</em></p>`,
  disc:[{ans:'A (60%) vs B (37%) — 논쟁',txt:'"After you select the repository name and branch, a message displays the Amazon CloudWatch Events rule to be created for this pipeline." — AWS CodePipeline 튜토리얼. 기본 이벤트 기반 트리거 방식은 EventBridge 규칙입니다.'}]
},
{
  n:17,
  ko:`한 회사의 개발자가 Amazon EC2 인스턴스를 원격 워크스테이션으로 사용합니다. 이 회사는 사용자가 EC2 보안 그룹을 만들거나 수정하여 무제한 인바운드 액세스를 허용할 수 있다는 점에 대해 우려하고 있습니다.<br><br>DevOps 엔지니어는 사용자가 무제한 보안 그룹 규칙을 만들 때 이를 감지하는 솔루션을 개발해야 합니다. 이 솔루션은 거의 실시간으로 보안 그룹 규칙의 변경 사항을 감지하고, 무제한 규칙을 제거하고, 보안 팀에 이메일 알림을 보내야 합니다. DevOps 엔지니어는 입력에서 보안 그룹 ID를 확인하고, 무제한 액세스를 허용하는 규칙을 제거하고, Amazon Simple Notification Service(Amazon SNS)를 통해 알림을 보내는 AWS Lambda 함수를 만들었습니다.<br><br><strong>DevOps 엔지니어는 요구 사항을 충족하기 위해 다음에 무엇을 해야 합니까?</strong>`,
  en:`A company's developers use Amazon EC2 instances as remote workstations. The company is concerned that users can create or modify EC2 security groups to allow unrestricted inbound access.<br><br>A DevOps engineer needs to develop a solution to detect when users create unrestricted security group rules. The solution must detect changes to security group rules in near real time, remove unrestricted rules, and send email notifications to the security team. The DevOps engineer has created an AWS Lambda function that checks for security group ID from input, removes rules that grant unrestricted access, and sends notifications through Amazon Simple Notification Service (Amazon SNS).<br><br><strong>What should the DevOps engineer do next to meet the requirements?</strong>`,
  type:'single',
  choices:[
    {k:'A', ko:`SNS 토픽에서 호출할 Lambda 함수를 구성합니다. SNS 토픽에 대한 AWS CloudTrail 구독을 만듭니다. 보안 그룹 수정 이벤트에 대한 구독 필터를 구성합니다.`, en:`Configure the Lambda function to be invoked by the SNS topic. Create an AWS CloudTrail subscription for the SNS topic. Configure a subscription filter for security group modification events.`},
    {k:'B', ko:`Lambda 함수를 호출하기 위한 Amazon EventBridge 예약 규칙을 만듭니다. 매 시간 Lambda 함수를 실행하는 스케줄 패턴을 정의합니다.`, en:`Create an Amazon EventBridge scheduled rule to invoke the Lambda function. Define a schedule pattern that runs the Lambda function every hour.`},
    {k:'C', ko:`기본 이벤트 버스를 소스로 하는 Amazon EventBridge 이벤트 규칙을 만듭니다. EC2 보안 그룹 생성 및 수정 이벤트와 일치하도록 규칙의 이벤트 패턴을 정의합니다. Lambda 함수를 호출하도록 규칙을 구성합니다.`, en:`Create an Amazon EventBridge event rule that has the default event bus as the source. Define the rule's event pattern to match EC2 security group creation and modification events. Configure the rule to invoke the Lambda function.`},
    {k:'D', ko:`모든 AWS 서비스의 이벤트를 구독하는 Amazon EventBridge 사용자 지정 이벤트 버스를 만듭니다. 사용자 지정 이벤트 버스에서 호출할 Lambda 함수를 구성합니다.`, en:`Create an Amazon EventBridge custom event bus that subscribes to events from all AWS services. Configure the Lambda function to be invoked by the custom event bus.`},
  ],
  answer:['C'],
  vote:'100% C',
  explain:`<p><span class="mark-ok">✅ C — EventBridge 기본 이벤트 버스 + EC2 보안 그룹 이벤트 패턴 → Lambda</span></p><p>AWS 서비스 이벤트는 <strong>기본 이벤트 버스</strong>로 전달됩니다. EventBridge 이벤트 규칙에서 EC2 보안 그룹 생성/수정 이벤트를 패턴으로 정의하면 거의 실시간으로 변경을 감지합니다. Lambda 함수를 대상으로 지정하여 자동으로 무제한 규칙을 제거하고 SNS로 알림을 전송합니다.</p>`,
  wrong:`<p><span class="mark-no">❌ B</span> — 매 시간 실행하는 스케줄은 "거의 실시간" 요구사항을 충족하지 않습니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ D</span> — AWS 서비스 이벤트는 기본 이벤트 버스에서 발생합니다. 사용자 지정 이벤트 버스는 교차 계정/리전 이벤트나 파트너 이벤트에 사용합니다. 모든 AWS 서비스를 구독하면 불필요한 비용이 발생합니다.</p>`,
  disc:[{ans:'C (100%)',txt:'기본 이벤트 버스: 계정 내 AWS 서비스 이벤트 수신. 사용자 지정 이벤트 버스: 다른 계정/파트너 이벤트 수신. EC2 보안 그룹 변경은 기본 이벤트 버스에서 처리합니다.'}]
},
{
  n:18,
  ko:`DevOps 엔지니어가 웹 서비스를 배포하기 위해 AWS CloudFormation 템플릿을 만들고 있습니다. 웹 서비스는 Application Load Balancer(ALB) 뒤의 프라이빗 서브넷에 있는 Amazon EC2 인스턴스에서 실행됩니다. DevOps 엔지니어는 서비스가 IPv6 주소가 있는 클라이언트의 요청을 수락할 수 있는지 확인해야 합니다.<br><br><strong>IPv6 클라이언트가 웹 서비스에 액세스할 수 있도록 DevOps 엔지니어는 CloudFormation 템플릿으로 무엇을 해야 합니까?</strong>`,
  en:`A DevOps engineer is creating an AWS CloudFormation template to deploy a web service. The web service will run on Amazon EC2 instances in a private subnet behind an Application Load Balancer (ALB). The DevOps engineer must ensure that the service can accept requests from clients that have IPv6 addresses.<br><br><strong>What should the DevOps engineer do with the CloudFormation template so that IPv6 clients can access the web service?</strong>`,
  type:'single',
  choices:[
    {k:'A', ko:`EC2 인스턴스의 VPC와 프라이빗 서브넷에 IPv6 CIDR 블록을 추가합니다. IPv6 네트워크에 대한 경로 테이블 항목을 만들고, IPv6를 지원하는 EC2 인스턴스 유형을 사용하고, 각 EC2 인스턴스에 IPv6 주소를 할당합니다.`, en:`Add an IPv6 CIDR block to the VPC and the private subnet for the EC2 instances. Create route table entries for the IPv6 network, use EC2 instance types that support IPv6, and assign IPv6 addresses to each EC2 instance.`},
    {k:'B', ko:`각 EC2 인스턴스에 IPv6 Elastic IP 주소를 할당합니다. 대상 그룹을 만들고 EC2 인스턴스를 대상으로 추가합니다. ALB의 포트 443에 리스너를 만들고 대상 그룹을 ALB와 연결합니다.`, en:`Assign each EC2 instance an IPv6 Elastic IP address. Create a target group, and add the EC2 instances as targets. Create a listener on port 443 of the ALB, and associate the target group with the ALB.`},
    {k:'C', ko:`ALB를 Network Load Balancer(NLB)로 교체합니다. NLB의 VPC와 서브넷에 IPv6 CIDR 블록을 추가하고 NLB에 IPv6 탄력적 IP 주소를 할당합니다.`, en:`Replace the ALB with a Network Load Balancer (NLB). Add an IPv6 CIDR block to the VPC and subnets for the NLB, and assign the NLB an IPv6 Elastic IP address.`},
    {k:'D', ko:`ALB의 VPC와 서브넷에 IPv6 CIDR 블록을 추가합니다. 포트 443에 리스너를 만들고 ALB에서 <code>dualstack</code> IP 주소 유형을 지정합니다. 대상 그룹을 만들고 EC2 인스턴스를 대상으로 추가합니다. 대상 그룹을 ALB와 연결합니다.`, en:`Add an IPv6 CIDR block to the VPC and subnets for the ALB. Create a listener on port 443, and specify the dualstack IP address type on the ALB. Create a target group, and add the EC2 instances as targets. Associate the target group with the ALB.`},
  ],
  answer:['D'],
  vote:'100% D',
  explain:`<p><span class="mark-ok">✅ D — ALB dualstack IP 주소 유형</span></p><p>IPv6를 지원하려면 ALB를 <strong>dualstack</strong> IP 주소 유형으로 구성합니다. Dualstack 모드에서 ALB는 IPv4와 IPv6 주소를 모두 제공하고 A와 AAAA DNS 레코드를 생성합니다. 백엔드 EC2 인스턴스는 IPv4만 사용해도 됩니다. ALB의 VPC와 서브넷에 IPv6 CIDR 블록을 추가해야 ALB가 IPv6 주소를 받을 수 있습니다.</p>`,
  wrong:`<p><span class="mark-no">❌ A</span> — 프라이빗 서브넷의 EC2 인스턴스에 IPv6를 직접 할당하는 방식입니다. 인터넷에서 IPv6로 직접 접근은 보안상 문제가 있으며, 요구사항은 ALB를 통한 접근입니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ C</span> — ALB를 NLB로 교체할 필요가 없습니다. ALB도 dualstack을 지원합니다.</p>`,
  disc:[{ans:'D (100%)',txt:'"To support IPv6, configure your ALBs or NLBs with the dualstack IP address type. This means clients can communicate using both IPv4 and IPv6 addresses." — AWS IPv6 아키텍처 문서'}]
},
{
  n:19,
  ko:`한 회사에서는 AWS Organizations와 AWS Control Tower를 사용하여 회사의 모든 AWS 계정을 관리합니다. 이 회사는 Enterprise Support 플랜을 사용합니다.<br><br>DevOps 엔지니어는 Account Factory for Terraform(AFT)을 사용하여 새 계정을 프로비저닝합니다. 새 계정이 프로비저닝되면 DevOps 엔지니어는 새 계정에 대한 지원 플랜이 Basic Support 플랜으로 설정되어 있음을 알게 됩니다. DevOps 엔지니어는 Enterprise Support 플랜으로 새 계정을 프로비저닝하는 솔루션을 구현해야 합니다.<br><br><strong>어떤 솔루션이 이러한 요구 사항을 충족합니까?</strong>`,
  en:`A company uses AWS Organizations and AWS Control Tower to manage all the company's AWS accounts. The company uses the Enterprise Support plan.<br><br>A DevOps engineer is using Account Factory for Terraform (AFT) to provision new accounts. When new accounts are provisioned, the DevOps engineer notices that the support plan for the new accounts is set to the Basic Support plan. The DevOps engineer needs to implement a solution to provision the new accounts with the Enterprise Support plan.<br><br><strong>Which solution will meet these requirements?</strong>`,
  type:'single',
  choices:[
    {k:'A', ko:`AWS Config 적합성 팩을 사용하여 조직의 일부인 계정 AWS Config 규칙을 배포하고 규정을 준수하지 않는 모든 계정을 자동으로 수정합니다.`, en:`Use an AWS Config conformance pack to deploy the account-part-of-organizations AWS Config rule and to automatically remediate any noncompliant accounts.`},
    {k:'B', ko:`AWS Lambda 함수를 만들어 AWS Support에서 Enterprise Support 플랜에 계정을 추가하기 위한 티켓을 만듭니다. Lambda 함수에 <code>support:ResolveCase</code> 권한을 부여합니다.`, en:`Create an AWS Lambda function to create a ticket for AWS Support to add the account to the Enterprise Support plan. Grant the Lambda function the support:ResolveCase permission.`},
    {k:'C', ko:`<code>control_tower_parameters</code> 입력에 추가 값을 추가하여 <code>AWSEnterpriseSupport</code> 매개변수를 조직의 관리 계정 번호로 설정합니다.`, en:`Add an additional value to the control_tower_parameters input to set the AWSEnterpriseSupport parameter as the organization's management account number.`},
    {k:'D', ko:`AFT 배포 입력 구성에서 <code>aft_feature_enterprise_support</code> 기능 플래그를 True로 설정합니다. AFT를 다시 배포하고 변경 사항을 적용합니다.`, en:`Set the aft_feature_enterprise_support feature flag to True in the AFT deployment input configuration. Redeploy AFT and apply the changes.`},
  ],
  answer:['D'],
  vote:'100% D',
  explain:`<p><span class="mark-ok">✅ D — aft_feature_enterprise_support 기능 플래그</span></p><p>AFT(Account Factory for Terraform)는 <code>aft_feature_enterprise_support</code> 기능 플래그를 제공합니다. 이 플래그를 <code>True</code>로 설정하면 AFT로 프로비저닝되는 새 계정에 자동으로 Enterprise Support 플랜이 적용됩니다. IaC 도구(Terraform)를 사용할 때는 콘솔에서 직접 변경하는 대신 구성 파일에서 변경해야 합니다.</p>`,
  wrong:`<p><span class="mark-no">❌ A</span> — AWS Config 적합성 팩은 지원 플랜 변경과 무관합니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ B</span> — <code>support:ResolveCase</code>는 지원 케이스를 해결하는 권한이며 지원 플랜 변경과 관련 없습니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ C</span> — AFT의 <code>control_tower_parameters</code>에는 <code>AWSEnterpriseSupport</code> 매개변수가 없습니다.</p>`,
  disc:[{ans:'D (100%)',txt:'AFT 기능 플래그: aft_feature_enterprise_support=true. 이 설정으로 프로비저닝되는 모든 새 계정에 Enterprise Support가 자동 적용됩니다. — AWS Control Tower AFT 기능 옵션 문서'}]
},
{
  n:20,
  ko:`한 회사의 DevOps 엔지니어가 AWS Systems Manager를 사용하여 유지 관리 기간 동안 유지 관리 작업을 수행합니다. 이 회사에는 AWS Health에서 알림을 받은 후 재시작이 필요한 Amazon EC2 인스턴스가 몇 개 있습니다. DevOps 엔지니어는 이러한 알림을 수정하기 위한 자동화된 솔루션을 구현해야 합니다. DevOps 엔지니어가 Amazon EventBridge 규칙을 만듭니다.<br><br><strong>DevOps 엔지니어는 이러한 요구 사항을 충족하기 위해 EventBridge 규칙을 어떻게 구성해야 합니까?</strong>`,
  en:`A company's DevOps engineer uses AWS Systems Manager to perform maintenance tasks during maintenance windows. The company has a few Amazon EC2 instances that require a restart after notifications from AWS Health. The DevOps engineer needs to implement an automated solution to remediate these notifications. The DevOps engineer creates an Amazon EventBridge rule.<br><br><strong>How should the DevOps engineer configure the EventBridge rule to meet these requirements?</strong>`,
  type:'single',
  choices:[
    {k:'A', ko:`EC2의 서비스인 AWS Health의 이벤트 소스와 인스턴스 유지 관리를 나타내는 이벤트 유형을 구성합니다. EC2 인스턴스를 다시 시작하려면 Systems Manager 문서를 대상으로 지정합니다.`, en:`Configure an event source of AWS Health, a service of EC2, and an event type that indicates instance maintenance. Target a Systems Manager document to restart the EC2 instance.`},
    {k:'B', ko:`Systems Manager의 이벤트 소스와 유지 관리 기간을 나타내는 이벤트 유형을 구성합니다. EC2 인스턴스를 다시 시작하려면 Systems Manager 문서를 대상으로 지정합니다.`, en:`Configure an event source of Systems Manager and an event type that indicates a maintenance window. Target a Systems Manager document to restart the EC2 instance.`},
    {k:'C', ko:`EC2의 서비스인 AWS Health의 이벤트 소스와 인스턴스 유지 관리를 나타내는 이벤트 유형을 구성합니다. 유지 관리 기간 동안 EC2 인스턴스를 다시 시작하는 자동화 작업을 등록하는 새로 생성된 AWS Lambda 함수를 대상으로 합니다.`, en:`Configure an event source of AWS Health, a service of EC2, and an event type that indicates instance maintenance. Target a newly created AWS Lambda function that registers an automation task to restart the EC2 instance during a maintenance window.`},
    {k:'D', ko:`EC2의 이벤트 소스와 인스턴스 유지 관리를 나타내는 이벤트 유형을 구성합니다. 유지 관리 기간 동안 EC2 인스턴스를 다시 시작하기 위한 자동화 작업을 등록하는 새로 생성된 AWS Lambda 함수를 대상으로 합니다.`, en:`Configure an event source of EC2 and an event type that indicates instance maintenance. Target a newly created AWS Lambda function that registers an automation task to restart the EC2 instance during a maintenance window.`},
  ],
  answer:['A'],
  vote:'65% A (31% C)',
  explain:`<p><span class="mark-ok">✅ A — AWS Health 이벤트 소스 + SSM Automation 문서 대상</span></p><p>AWS Health가 EC2 인스턴스 유지 관리 이벤트를 발생시키면 EventBridge 규칙이 이를 감지합니다. EventBridge 대상으로 <strong>Systems Manager Automation</strong>을 지정하고 <code>AWS-RestartEC2Instance</code> 런북을 실행합니다. 회사가 이미 SSM을 사용 중이므로 별도의 Lambda를 만들 필요가 없습니다. AWS Training & Certification 연습 시험에서 A가 정답으로 확인되었습니다.</p>`,
  wrong:`<p><span class="mark-no">❌ B</span> — 이벤트 소스는 AWS Health여야 합니다. Systems Manager 이벤트는 SSM 내부 작업 이벤트이며 AWS Health 알림과 무관합니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ C, D</span> — 회사에서 이미 SSM을 사용하고 있으므로 Lambda를 별도로 만들 필요가 없습니다. EventBridge는 SSM Automation을 직접 대상으로 지정할 수 있습니다.</p>`,
  disc:[{ans:'A (65%) vs C (31%) — 논쟁',txt:'AWS Training & Certification 연습 시험에서 A가 정답으로 확인됩니다. EventBridge → SSM Automation(AWS-RestartEC2Instance)을 직접 연결할 수 있습니다. Lambda는 이미 SSM이 있는 환경에서 불필요한 복잡성을 추가합니다.'}]
}
];
