window.QS_SET34 = [
{
  n: 331,
  en: `A company has deployed a new REST API by using Amazon API Gateway. The company uses the API to access confidential data. The API must be accessed from only specific VPCs in the company.<br>Which solution will meet these requirements?`,
  ko: `한 회사가 Amazon API Gateway를 사용하여 새로운 REST API를 배포했습니다. 회사는 API를 사용하여 기밀 데이터에 액세스합니다. API는 회사의 특정 VPC에서만 액세스해야 합니다.<br>이 요구 사항을 충족하는 솔루션은 무엇입니까?`,
  type: 'single',
  choices: [
    { k:'A', en:`Create and attach a resource policy to the API Gateway API. Configure the resource policy to allow only the specific VPC IDs.`, ko:`API Gateway API에 리소스 정책을 생성하여 연결합니다. 특정 VPC ID만 허용하도록 리소스 정책을 구성합니다.` },
    { k:'B', en:`Add a security group to the API Gateway API. Configure the inbound rules to allow only the specific VPC IP address ranges.`, ko:`API Gateway API에 보안 그룹을 추가합니다. 특정 VPC IP 주소 범위만 허용하도록 인바운드 규칙을 구성합니다.` },
    { k:'C', en:`Create and attach an IAM role to the API Gateway API. Configure the IAM role to allow only the specific VPC IDs.`, ko:`API Gateway API에 IAM 역할을 생성하여 연결합니다. 특정 VPC ID만 허용하도록 IAM 역할을 구성합니다.` },
    { k:'D', en:`Add an ACL to the API Gateway API. Configure the outbound rules to allow only the specific VPC IP address ranges.`, ko:`API Gateway API에 ACL을 추가합니다. 특정 VPC IP 주소 범위만 허용하도록 아웃바운드 규칙을 구성합니다.` },
  ],
  answer: ['A'],
  vote: '100% A',
  explain: `<p><span class="mark-ok">✅ A — API Gateway 리소스 정책 (VPC ID 기반)</span></p><p>Amazon API Gateway는 리소스 정책을 지원합니다. 리소스 정책에서 <code>aws:sourceVpc</code> 조건 키를 사용하여 특정 VPC ID에서만 API에 액세스할 수 있도록 제한할 수 있습니다. 이는 프라이빗 API 엔드포인트 구성에 권장되는 방법입니다.</p>`,
  wrong: `<p><span class="mark-no">❌ B</span> — API Gateway에는 보안 그룹을 직접 연결할 수 없습니다.</p><p><span class="mark-no">❌ C</span> — IAM 역할은 API에 연결하는 것이 아니라 API를 호출하는 주체에 연결합니다.</p><p><span class="mark-no">❌ D</span> — API Gateway에는 ACL이 없으며 아웃바운드 규칙 설정도 존재하지 않습니다.</p>`,
  disc: [{ ans:'A (100%)', txt:'API Gateway 리소스 정책에서 VPC ID를 기반으로 액세스를 제한하는 것이 올바른 방법이라는 의견이 일치합니다.' }]
},
{
  n: 332,
  en: `A company runs a website by using an Amazon Elastic Container Service (Amazon ECS) service that is connected to an Application Load Balancer (ALB). The service was in a steady state with tasks responding to requests successfully.<br>A DevOps engineer updated the task definition with a new container image and deployed the new task definition to the service. The DevOps engineer noticed that the service is frequently stopping and starting new tasks because the ALB health checks are failing.<br>What should the DevOps engineer do to troubleshoot the failed deployment?`,
  ko: `한 회사가 ALB에 연결된 Amazon ECS 서비스를 사용하여 웹사이트를 운영합니다. 서비스는 작업이 요청에 성공적으로 응답하는 안정적인 상태였습니다.<br>DevOps 엔지니어가 새 컨테이너 이미지로 작업 정의를 업데이트하고 새 작업 정의를 서비스에 배포했습니다. ALB 상태 검사 실패로 서비스가 자주 중지되고 새 작업이 시작된다는 것을 알아챘습니다.<br>실패한 배포 문제를 해결하기 위해 무엇을 해야 합니까?`,
  type: 'single',
  choices: [
    { k:'A', en:`Ensure that a security group associated with the service allows traffic from the ALB.`, ko:`서비스와 연결된 보안 그룹이 ALB의 트래픽을 허용하는지 확인합니다.` },
    { k:'B', en:`Increase the ALB health check grace period for the service.`, ko:`서비스에 대한 ALB 상태 검사 유예 기간을 늘립니다.` },
    { k:'C', en:`Increase the service minimum healthy percent setting.`, ko:`서비스 최소 건강 비율 설정을 늘립니다.` },
    { k:'D', en:`Decrease the ALB health check interval.`, ko:`ALB 상태 점검 간격을 줄입니다.` },
  ],
  answer: ['B'],
  vote: '100% B',
  explain: `<p><span class="mark-ok">✅ B — ALB 상태 검사 유예 기간 증가</span></p><p>새 컨테이너 이미지를 배포할 때 컨테이너가 시작되고 정상 상태가 되는 데 시간이 걸릴 수 있습니다. ALB 상태 검사 유예 기간이 너무 짧으면 컨테이너가 완전히 준비되기 전에 ALB가 비정상으로 표시합니다. 유예 기간을 늘리면 새 작업이 ALB에서 비정상으로 표시되기 전에 시작되고 정상 상태로 될 충분한 시간을 확보합니다.</p>`,
  wrong: `<p><span class="mark-no">❌ A</span> — 이미지만 업데이트했으므로 보안 그룹은 변경되지 않았고 이전에 정상이었습니다.</p><p><span class="mark-no">❌ C</span> — 최소 건강 비율은 배포 중 최소 유지해야 하는 작업 비율로, 상태 검사 실패 원인을 해결하지 못합니다.</p><p><span class="mark-no">❌ D</span> — 상태 검사 간격을 줄이면 더 자주 실패를 감지하여 문제를 악화시킵니다.</p>`,
  disc: [{ ans:'B (100%)', txt:'새 컨테이너 이미지가 시작 시간이 더 걸릴 수 있으므로 ALB 상태 검사 유예 기간을 늘리는 것이 올바른 해결책입니다.' }]
},
{
  n: 333,
  en: `A company that uses electronic patient health records runs a fleet of Amazon EC2 instances with an Amazon Linux operating system. The company must continuously ensure that the EC2 instances are running operating system patches and application patches that are in compliance with current privacy regulations. The company uses a custom repository to store application patches.<br>A DevOps engineer needs to automate the deployment of operating system patches and application patches. The DevOps engineer wants to use both the default operating system patch repository and the custom patch repository.<br>Which solution will meet these requirements with the LEAST effort?`,
  ko: `전자 환자 건강 기록을 사용하는 회사가 Amazon Linux 운영 체제를 사용하여 Amazon EC2 인스턴스 플릿을 실행합니다. 회사는 EC2 인스턴스가 현재 개인 정보 보호 규정을 준수하는 운영 체제 패치와 애플리케이션 패치를 실행하고 있는지 지속적으로 확인해야 합니다. 회사는 애플리케이션 패치를 저장하기 위해 사용자 지정 리포지토리를 사용합니다.<br>DevOps 엔지니어는 운영 체제 패치와 애플리케이션 패치의 배포를 자동화해야 합니다. 기본 운영 체제 패치 리포지토리와 사용자 지정 패치 리포지토리를 모두 사용하려 합니다.<br>최소한의 노력으로 이 요구 사항을 충족하는 솔루션은 무엇입니까?`,
  type: 'single',
  choices: [
    { k:'A', en:`Use AWS Systems Manager to create a new custom patch baseline that includes the default operating system repository and the custom repository. Run the AWS-RunPatchBaseline document by using the Run command to verify and install patches. Use the BaselineOverride API to configure the new custom patch baseline.`, ko:`AWS Systems Manager를 사용하여 기본 운영 체제 리포지토리와 사용자 지정 리포지토리를 포함하는 새 사용자 지정 패치 기준선을 생성합니다. Run 명령을 사용하여 AWS-RunPatchBaseline 문서를 실행하여 패치를 확인하고 설치합니다. BaselineOverride API를 사용하여 새 사용자 지정 패치 기준선을 구성합니다.` },
    { k:'B', en:`Use AWS Direct Connect to integrate the custom repository with the EC2 instances. Use Amazon EventBridge events to deploy the patches.`, ko:`AWS Direct Connect를 사용하여 사용자 지정 리포지토리를 EC2 인스턴스와 통합합니다. Amazon EventBridge 이벤트를 사용하여 패치를 배포합니다.` },
    { k:'C', en:`Use the yum-config-manager command to add the custom repository to the /etc/yum.repos.d configuration. Run the yum-config-manager-enable command to activate the new repository.`, ko:`yum-config-manager 명령을 사용하여 사용자 지정 리포지토리를 /etc/yum.repos.d 구성에 추가합니다. yum-config-manager-enable 명령을 실행하여 새 리포지토리를 활성화합니다.` },
    { k:'D', en:`Use AWS Systems Manager to create a patch baseline for the default operating system repository and a second patch baseline for the custom repository. Run the AWS-RunPatchBaseline document by using the Run command to verify and install patches. Use the BaselineOverride API to configure the default patch baseline and the custom patch baseline.`, ko:`AWS Systems Manager를 사용하여 기본 운영 체제 리포지토리에 대한 패치 기준선과 사용자 지정 리포지토리에 대한 두 번째 패치 기준선을 생성합니다. Run 명령을 사용하여 AWS-RunPatchBaseline 문서를 실행하여 패치를 확인하고 설치합니다. BaselineOverride API를 사용하여 기본 패치 기준선과 사용자 지정 패치 기준선을 구성합니다.` },
  ],
  answer: ['A'],
  vote: '100% A',
  explain: `<p><span class="mark-ok">✅ A — 단일 사용자 지정 패치 기준선으로 통합</span></p><p>AWS Systems Manager Patch Manager는 기본 OS 리포지토리와 사용자 지정 리포지토리를 모두 포함하는 단일 사용자 지정 패치 기준선을 지원합니다. AWS-RunPatchBaseline 문서와 BaselineOverride API를 사용하여 패치 검증 및 설치를 자동화합니다. 단일 패치 기준선으로 관리가 간소화됩니다.</p>`,
  wrong: `<p><span class="mark-no">❌ B</span> — Direct Connect는 네트워크 연결 서비스이며 패치 관리와 관련 없습니다.</p><p><span class="mark-no">❌ C</span> — 수동 yum 명령은 자동화되지 않고 규모 확장이 어렵습니다.</p><p><span class="mark-no">❌ D</span> — 두 개의 별도 패치 기준선을 관리하는 것은 단일 기준선(A)보다 복잡하고 불필요합니다.</p>`,
  disc: [{ ans:'A (100%)', txt:'기본 OS 리포지토리와 사용자 지정 리포지토리를 단일 패치 기준선으로 통합하는 것이 최소 노력 솔루션입니다.' }]
},
{
  n: 334,
  en: `A company use an organization in AWS Organizations to manage multiple AWS accounts. The company has enabled all features enabled for the organization. The company configured the organization as a hierarchy of OUs under the root OU. The company recently registered all its OUs and enrolled all its AWS accounts in AWS Control Tower.<br>The company needs to customize the AWS Control Tower managed AWS Config configuration recorder in each of the company's AWS accounts. The company needs to apply the customizations to both the existing AWS accounts and to any new AWS accounts that the company enrolls in AWS Control Tower in the future.<br>Which combination of steps will meet these requirements? (Choose three.)`,
  ko: `한 회사가 AWS Organizations의 조직을 사용하여 여러 AWS 계정을 관리합니다. 회사는 모든 기능이 활성화되어 있습니다. 회사는 조직을 루트 OU 아래의 OU 계층으로 구성했습니다. 회사는 최근에 모든 OU를 등록하고 모든 AWS 계정을 AWS Control Tower에 등록했습니다.<br>회사는 각 AWS 계정에서 AWS Control Tower 관리 AWS Config 구성 레코더를 사용자 지정해야 합니다. 기존 AWS 계정과 앞으로 등록하는 새 AWS 계정 모두에 사용자 지정을 적용해야 합니다.<br>이 요구 사항을 충족하는 단계 조합은 무엇입니까? (3개 선택)`,
  type: 'multi', multiCount: 3,
  choices: [
    { k:'A', en:`Create a new AWS account. Create an AWS Lambda function in the new account to apply the customizations to the AWS Config configuration recorder in each AWS account in the organization.`, ko:`새 AWS 계정을 생성합니다. 조직의 각 AWS 계정에서 AWS Config 구성 레코더에 사용자 지정을 적용하기 위해 새 계정에서 AWS Lambda 함수를 생성합니다.` },
    { k:'B', en:`Create a new AWS account as an AWS Config delegated administrator. Create an AWS Lambda function in the delegated administrator account to apply the customizations to the AWS Config configuration recorder in the delegated administrator account.`, ko:`AWS Config 위임 관리자로 새 AWS 계정을 생성합니다. 위임 관리자 계정에서 AWS Lambda 함수를 생성하여 위임 관리자 계정의 AWS Config 구성 레코더에 사용자 지정을 적용합니다.` },
    { k:'C', en:`Configure an Amazon EventBridge rule in the AWS Control Tower management account to invoke an AWS Lambda function when the Organizations OU is registered or reregistered. Re-register the root Organizations OU.`, ko:`AWS Control Tower 관리 계정에서 Organizations OU가 등록되거나 재등록될 때 AWS Lambda 함수를 호출하는 Amazon EventBridge 규칙을 구성합니다. 루트 Organizations OU를 재등록합니다.` },
    { k:'D', en:`Configure the AWSControlTowerExecution IAM role in each AWS account in the organization to be assumable by an AWS Lambda function. Configure the Lambda function to assume the AWSControlTowerExecution IAM role.`, ko:`조직의 각 AWS 계정에서 AWSControlTowerExecution IAM 역할을 AWS Lambda 함수에서 맡을 수 있도록 구성합니다. Lambda 함수가 AWSControlTowerExecution IAM 역할을 맡도록 구성합니다.` },
    { k:'E', en:`Create an IAM role in the AWS Control Tower management account that an AWS Lambda function can assume. Grant the IAM role permission to assume the AWSControlTowerExecution IAM role in any account in the organization. Configure the Lambda function to use the new IAM role.`, ko:`AWS Lambda 함수가 맡을 수 있는 AWS Control Tower 관리 계정에서 IAM 역할을 생성합니다. 조직의 모든 계정에서 AWSControlTowerExecution IAM 역할을 맡을 수 있는 IAM 역할 권한을 부여합니다. Lambda 함수가 새 IAM 역할을 사용하도록 구성합니다.` },
    { k:'F', en:`Configure an Amazon EventBridge rule in the AWS Control Tower management account to invoke an AWS Lambda function when an AWS account is updated or enrolled in AWS Control Tower or when the landing zone is updated. Re-register each Organizations OU in the organization.`, ko:`AWS Control Tower 관리 계정에서 AWS 계정이 업데이트되거나 AWS Control Tower에 등록되거나 랜딩 존이 업데이트될 때 AWS Lambda 함수를 호출하는 Amazon EventBridge 규칙을 구성합니다. 조직의 각 Organizations OU를 재등록합니다.` },
  ],
  answer: ['A','E','F'],
  vote: '50% AEF',
  explain: `<p><span class="mark-ok">✅ A — AWS Config 위임 관리자 계정에서 Lambda 함수</span></p><p>Config 위임 관리자 계정(옵션 A에 오타가 있지만)에서 Lambda 함수를 생성하여 중앙에서 모든 계정의 Config 레코더를 사용자 지정합니다.</p><p><span class="mark-ok">✅ E — 관리 계정 IAM 역할 + AWSControlTowerExecution 역할 수임</span></p><p>Lambda 함수가 멤버 계정에서 AWSControlTowerExecution 역할을 수임하여 Config 레코더를 수정할 수 있도록 합니다.</p><p><span class="mark-ok">✅ F — 계정 등록/랜딩 존 업데이트 시 EventBridge 트리거</span></p><p>새 계정 등록 또는 랜딩 존 업데이트 시 자동으로 Lambda를 호출하여 새 계정에도 사용자 지정이 적용됩니다.</p>`,
  wrong: `<p><span class="mark-no">❌ C</span> — EventBridge는 OU 등록/재등록 이벤트를 발생시키지 않습니다.</p><p><span class="mark-no">❌ D</span> — 각 계정의 AWSControlTowerExecution 역할을 수정하면 Control Tower 관리 역할이 손상됩니다.</p>`,
  disc: [{ ans:'AEF (50%) vs CEF (20%)', txt:'AEF와 CEF 중 커뮤니티 의견이 나뉘지만, AWS 공식 가이드(customizing-aws-config-resources-in-aws-control-tower)에 따르면 AEF가 권장됩니다.' }]
},
{
  n: 335,
  en: `A company runs an application in an Auto Scaling group of Amazon EC2 instances behind an Application Load Balancer (ALB). The EC2 instances run Docker containers that make requests to a MySQL database that runs on separate EC2 instances.<br>A DevOps engineer needs to update the application to use a serverless architecture.<br>Which solution will meet this requirement with the FEWEST changes?`,
  ko: `한 회사가 ALB 뒤의 Amazon EC2 인스턴스의 Auto Scaling 그룹에서 애플리케이션을 실행합니다. EC2 인스턴스는 별도의 EC2 인스턴스에서 실행되는 MySQL 데이터베이스에 요청을 하는 Docker 컨테이너를 실행합니다.<br>DevOps 엔지니어는 서버리스 아키텍처를 사용하도록 애플리케이션을 업데이트해야 합니다.<br>가장 적은 변경으로 이 요구 사항을 충족하는 솔루션은 무엇입니까?`,
  type: 'single',
  choices: [
    { k:'A', en:`Replace the containers that run on EC2 instances and the ALB with AWS Lambda functions. Replace the MySQL database with an Amazon Aurora Serverless v2 database that is compatible with MySQL.`, ko:`EC2 인스턴스와 ALB에서 실행되는 컨테이너를 AWS Lambda 함수로 교체합니다. MySQL 데이터베이스를 MySQL과 호환되는 Amazon Aurora Serverless v2 데이터베이스로 교체합니다.` },
    { k:'B', en:`Replace the containers that run on EC2 instances with AWS Fargate. Replace the MySQL database with an Amazon Aurora Serverless v2 database that is compatible with MySQL.`, ko:`EC2 인스턴스에서 실행되는 컨테이너를 AWS Fargate로 교체합니다. MySQL 데이터베이스를 MySQL과 호환되는 Amazon Aurora Serverless v2 데이터베이스로 교체합니다.` },
    { k:'C', en:`Replace the containers that run on EC2 instances and the ALB with AWS Lambda functions. Replace the MySQL database with Amazon DynamoDB tables.`, ko:`EC2 인스턴스와 ALB에서 실행되는 컨테이너를 AWS Lambda 함수로 교체합니다. MySQL 데이터베이스를 Amazon DynamoDB 테이블로 교체합니다.` },
    { k:'D', en:`Replace the containers that run on EC2 instances with AWS Fargate. Replace the MySQL database with Amazon DynamoDB tables.`, ko:`EC2 인스턴스에서 실행되는 컨테이너를 AWS Fargate로 교체합니다. MySQL 데이터베이스를 Amazon DynamoDB 테이블로 교체합니다.` },
  ],
  answer: ['B'],
  vote: '86% B',
  explain: `<p><span class="mark-ok">✅ B — AWS Fargate + Aurora Serverless v2(MySQL 호환)</span></p><p>가장 적은 변경으로 서버리스 전환: Docker 컨테이너는 그대로 AWS Fargate에서 실행(EC2 관리 불필요), ALB는 유지(변경 없음), MySQL은 Aurora Serverless v2(MySQL 호환)로 마이그레이션(코드 변경 최소화).</p>`,
  wrong: `<p><span class="mark-no">❌ A</span> — Docker에서 Lambda로 전환은 코드 재작성이 필요합니다. Lambda는 컨테이너 실행 방식과 다릅니다.</p><p><span class="mark-no">❌ C, D</span> — MySQL에서 DynamoDB로 전환은 SQL에서 NoSQL로의 대규모 코드 변경이 필요합니다.</p>`,
  disc: [{ ans:'B (86%)', txt:'Fargate로 컨테이너 유지 + Aurora Serverless v2 MySQL 호환이 가장 적은 변경으로 서버리스 전환을 달성합니다.' }]
},
{
  n: 336,
  en: `A company uses an organization in AWS Organizations to manage 10 AWS accounts. All features are enabled, and trusted access for AWS CloudFormation is enabled.<br>A DevOps engineer needs to use CloudFormation to deploy an IAM role to the Organizations management account and all member accounts in the organization.<br>Which solution will meet these requirements with the LEAST operational overhead?`,
  ko: `한 회사가 AWS Organizations의 조직을 사용하여 10개의 AWS 계정을 관리합니다. 모든 기능이 활성화되어 있고 AWS CloudFormation에 대한 신뢰할 수 있는 액세스가 활성화되어 있습니다.<br>DevOps 엔지니어는 CloudFormation을 사용하여 Organizations 관리 계정과 조직의 모든 멤버 계정에 IAM 역할을 배포해야 합니다.<br>최소한의 운영 오버헤드로 이 요구 사항을 충족하는 솔루션은 무엇입니까?`,
  type: 'single',
  choices: [
    { k:'A', en:`Create a CloudFormation StackSet that has service-managed permissions. Set the root OU as a deployment target.`, ko:`서비스 관리 권한이 있는 CloudFormation StackSet을 생성합니다. 루트 OU를 배포 대상으로 설정합니다.` },
    { k:'B', en:`Create a CloudFormation StackSet that has service-managed permissions. Set the root OU as a deployment target. Deploy a separate CloudFormation stack in the Organizations management account.`, ko:`서비스 관리 권한이 있는 CloudFormation StackSet을 생성합니다. 루트 OU를 배포 대상으로 설정합니다. Organizations 관리 계정에 별도의 CloudFormation 스택을 배포합니다.` },
    { k:'C', en:`Create a CloudFormation StackSet that has self-managed permissions. Set the root OU as a deployment target.`, ko:`자체 관리 권한이 있는 CloudFormation StackSet을 생성합니다. 루트 OU를 배포 대상으로 설정합니다.` },
    { k:'D', en:`Create a CloudFormation StackSet that has self-managed permissions. Set the root OU as a deployment target. Deploy a separate CloudFormation stack in the Organizations management account.`, ko:`자체 관리 권한이 있는 CloudFormation StackSet을 생성합니다. 루트 OU를 배포 대상으로 설정합니다. Organizations 관리 계정에 별도의 CloudFormation 스택을 배포합니다.` },
  ],
  answer: ['B'],
  vote: '59% B',
  explain: `<p><span class="mark-ok">✅ B — 서비스 관리 StackSet + 루트 OU + 관리 계정 별도 스택</span></p><p>AWS 공식 문서에 따르면 서비스 관리 권한이 있는 StackSet은 관리 계정에 스택 인스턴스를 배포하지 않습니다. 관리 계정에도 IAM 역할을 배포하려면 별도의 CloudFormation 스택을 관리 계정에 직접 배포해야 합니다.</p>`,
  wrong: `<p><span class="mark-no">❌ A</span> — 서비스 관리 StackSet은 관리 계정에 배포하지 않으므로 관리 계정이 누락됩니다.</p><p><span class="mark-no">❌ C, D</span> — 자체 관리 권한은 수동으로 역할을 설정해야 하므로 운영 오버헤드가 높습니다.</p>`,
  disc: [{ ans:'B (59%) vs A (41%)', txt:'AWS 공식 문서에 따르면 서비스 관리 StackSet은 관리 계정을 제외하므로, 관리 계정에 별도 스택 배포가 필요합니다.' }]
},
{
  n: 337,
  en: `A company runs an application that stores artifacts in an Amazon S3 bucket. The application has a large user base. The application writes a high volume of objects to the S3 bucket. The company has enabled event notifications for the S3 bucket.<br>When the application writes an object to the S3 bucket, several processing tasks need to be performed simultaneously. The company's DevOps team needs to create an AWS Step Functions workflow to orchestrate the processing tasks.<br>Which combination of steps should the DevOps team take to meet these requirements with the LEAST operational overhead? (Choose two.)`,
  ko: `한 회사가 Amazon S3 버킷에 아티팩트를 저장하는 애플리케이션을 실행합니다. 애플리케이션은 사용자 기반이 크고 S3 버킷에 많은 양의 객체를 씁니다. 회사는 S3 버킷에 대한 이벤트 알림을 활성화했습니다.<br>애플리케이션이 S3 버킷에 객체를 쓸 때 여러 처리 작업을 동시에 수행해야 합니다. 회사의 DevOps 팀은 처리 작업을 조정하기 위해 AWS Step Functions 워크플로를 생성해야 합니다.<br>최소한의 운영 오버헤드로 이 요구 사항을 충족하기 위해 DevOps 팀이 취해야 하는 단계 조합은 무엇입니까? (2개 선택)`,
  type: 'multi', multiCount: 2,
  choices: [
    { k:'A', en:`Create a Standard workflow that contains a parallel state that defines the processing tasks. Create an Asynchronous Express workflow that contains a parallel state that defines the processing tasks.`, ko:`처리 작업을 정의하는 병렬 상태를 포함하는 표준 워크플로를 생성합니다. 처리 작업을 정의하는 병렬 상태를 포함하는 비동기 익스프레스 워크플로를 생성합니다.` },
    { k:'B', en:`Create a Synchronous Express workflow that contains a map state that defines the processing tasks.`, ko:`처리 작업을 정의하는 맵 상태를 포함하는 동기식 Express 워크플로를 생성합니다.` },
    { k:'C', en:`Create an Amazon EventBridge rule to match when a new S3 object is created. Configure the EventBridge rule to invoke an AWS Lambda function. Configure the Lambda function to start the processing workflow.`, ko:`새 S3 객체가 생성될 때 일치하도록 Amazon EventBridge 규칙을 생성합니다. AWS Lambda 함수를 호출하도록 EventBridge 규칙을 구성합니다. 처리 워크플로를 시작하도록 Lambda 함수를 구성합니다.` },
    { k:'D', en:`Create an Amazon EventBridge rule to match when a new S3 object is created. Configure the EventBridge rule to start the processing workflow.`, ko:`새 S3 객체가 생성될 때 일치하도록 Amazon EventBridge 규칙을 생성합니다. 처리 워크플로를 시작하도록 EventBridge 규칙을 구성합니다.` },
  ],
  answer: ['A','D'],
  vote: '83% AD',
  explain: `<p><span class="mark-ok">✅ A — 표준 워크플로 + 병렬 상태</span></p><p>여러 처리 작업을 동시에 수행하려면 Step Functions 표준 워크플로의 병렬 상태를 사용합니다. 표준 워크플로는 장기 실행, 내구성, 감사 가능한 워크플로에 적합합니다.</p><p><span class="mark-ok">✅ D — EventBridge 규칙으로 Step Functions 직접 호출</span></p><p>EventBridge는 Step Functions 워크플로를 Lambda 중간 단계 없이 직접 호출할 수 있습니다. 이는 운영 오버헤드를 줄이는 더 간단한 아키텍처입니다.</p>`,
  wrong: `<p><span class="mark-no">❌ B</span> — 맵 상태는 동일한 작업을 여러 항목에 대해 반복 실행하는 것이며, 여러 다른 작업을 동시에 수행하는 것이 아닙니다.</p><p><span class="mark-no">❌ C</span> — EventBridge가 Step Functions를 직접 호출할 수 있으므로 Lambda 중간 단계는 불필요합니다.</p>`,
  disc: [{ ans:'AD (83%)', txt:'표준 워크플로의 병렬 상태와 EventBridge의 Step Functions 직접 호출이 최소 오버헤드로 요구 사항을 충족합니다.' }]
},
{
  n: 338,
  en: `A DevOps team supports an application that runs in an Amazon Elastic Container Service (Amazon ECS) cluster behind an Application Load Balancer (ALB). Currently, the DevOps team uses AWS CodeDeploy to deploy the application by using a blue/green all-at-once strategy. Recently, the DevOps team had to roll back a deployment when a new version of the application dramatically increased response times for requests.<br>The DevOps team needs use to a deployment strategy that will allow the team to monitor a new version of the application before the team shifts all traffic to the new version. If a new version of the application increases response times, the deployment should be rolled back as quickly as possible.<br>Which combination of steps will meet these requirements? (Choose two.)`,
  ko: `DevOps 팀은 ALB 뒤의 Amazon ECS 클러스터에서 실행되는 애플리케이션을 지원합니다. 현재 AWS CodeDeploy를 사용하여 blue/green all-at-once 전략으로 애플리케이션을 배포합니다. 최근 새 버전의 애플리케이션이 응답 시간을 극적으로 늘리자 배포를 롤백해야 했습니다.<br>DevOps 팀은 모든 트래픽을 새 버전으로 전환하기 전에 팀이 애플리케이션의 새 버전을 모니터링할 수 있는 배포 전략을 사용해야 합니다. 응답 시간이 늘어나면 가능한 한 빨리 배포를 롤백해야 합니다.<br>이 요구 사항을 충족하는 단계 조합은 무엇입니까? (2개 선택)`,
  type: 'multi', multiCount: 2,
  choices: [
    { k:'A', en:`Modify the CodeDeploy deployment to use the CodeDeployDefault.ECSCanary10Percent5Minutes configuration.`, ko:`CodeDeployDefault.ECSCanary10Percent5Minutes 구성을 사용하도록 CodeDeploy 배포를 수정합니다.` },
    { k:'B', en:`Modify the CodeDeploy deployment to use the CodeDeployDefault.ECSLinear10PercentEvery3Minutes configuration.`, ko:`CodeDeployDefault.ECSLinear10PercentEvery3Minutes 구성을 사용하도록 CodeDeploy 배포를 수정합니다.` },
    { k:'C', en:`Create an Amazon CloudWatch alarm to monitor the UnHealthyHostCount metric for the ALB. Set the alarm to activate if the metric is higher than the desired value. Associate the alarm with the CodeDeploy deployment group. Modify the deployment group to roll back when a deployment fails.`, ko:`ALB에 대한 UnHealthyHostCount 메트릭을 모니터링하는 Amazon CloudWatch 알람을 생성합니다. 메트릭이 원하는 값보다 높으면 알람이 활성화되도록 설정합니다. 알람을 CodeDeploy 배포 그룹과 연결합니다. 배포가 실패하면 롤백하도록 배포 그룹을 수정합니다.` },
    { k:'D', en:`Create an Amazon CloudWatch alarm to monitor the TargetResponseTime metric for the ALB. Set the alarm to activate if the metric is higher than the desired value. Associate the alarm with the CodeDeploy deployment group. Modify the deployment group to roll back when alarm thresholds are met.`, ko:`ALB에 대한 TargetResponseTime 메트릭을 모니터링하는 Amazon CloudWatch 알람을 생성합니다. 메트릭이 원하는 값보다 높으면 알람이 활성화되도록 설정합니다. 알람을 CodeDeploy 배포 그룹과 연결합니다. 알람 임계값에 도달하면 롤백하도록 배포 그룹을 수정합니다.` },
    { k:'E', en:`Create an Amazon CloudWatch alarm to monitor the TargetConnectionErrorCount metric for the ALB. Set the alarm to activate if the metric is higher than the desired value. Associate the alarm with the CodeDeploy deployment group. Modify the deployment group to roll back when alarm thresholds are met.`, ko:`ALB에 대한 TargetConnectionErrorCount 메트릭을 모니터링하는 Amazon CloudWatch 알람을 생성합니다. 메트릭이 원하는 값보다 높으면 알람이 활성화되도록 설정합니다. 알람을 CodeDeploy 배포 그룹과 연결합니다. 알람 임계값에 도달하면 롤백하도록 배포 그룹을 수정합니다.` },
  ],
  answer: ['A','D'],
  vote: '100% AD',
  explain: `<p><span class="mark-ok">✅ A — ECSCanary10Percent5Minutes 배포 구성</span></p><p>카나리아 배포 전략으로 먼저 10%의 트래픽을 새 버전으로 전환하고 5분 동안 모니터링합니다. 문제가 없으면 나머지 트래픽을 전환합니다. 모든 트래픽 전환 전에 새 버전을 모니터링할 수 있습니다.</p><p><span class="mark-ok">✅ D — TargetResponseTime 알람 + 자동 롤백</span></p><p>응답 시간 문제가 발생했으므로 TargetResponseTime 메트릭을 모니터링하는 알람을 CodeDeploy 배포 그룹과 연결하면 임계값 초과 시 자동으로 롤백됩니다.</p>`,
  wrong: `<p><span class="mark-no">❌ B</span> — Linear 배포는 천천히 모든 트래픽을 이전하는 것으로 빠른 롤백보다는 점진적 이전에 초점입니다.</p><p><span class="mark-no">❌ C</span> — UnHealthyHostCount는 건강하지 않은 호스트를 감지하지만 응답 시간 증가를 직접 모니터링하지 않습니다.</p><p><span class="mark-no">❌ E</span> — TargetConnectionErrorCount는 연결 오류이며 응답 시간 증가와 다릅니다.</p>`,
  disc: [{ ans:'AD (100%)', txt:'카나리아 배포와 TargetResponseTime 기반 자동 롤백이 응답 시간 문제를 신속하게 감지하고 롤백하는 최적 조합입니다.' }]
},
{
  n: 339,
  en: `A security team must record the configuration of AWS resources, detect issues, and send notifications for findings. The main workload in the AWS account consists of an Amazon EC2 Auto Scaling group that scales in and out several times during the day.<br>The team wants to be notified within 2 days if any Amazon EC2 security group allows traffic on port 22 for 0.0.0.0/0. The team also needs a snapshot of the configuration of the AWS resources to be taken routinely.<br>The security team has already created and subscribed to an Amazon Simple Notification Service (Amazon SNS) topic.<br>Which solution meets these requirements?`,
  ko: `보안팀은 AWS 리소스 구성을 기록하고, 문제를 탐지하고, 결과에 대한 알림을 보내야 합니다. AWS 계정의 주요 워크로드는 하루 중 여러 번 확장 및 축소되는 Amazon EC2 Auto Scaling 그룹으로 구성됩니다.<br>팀은 EC2 보안 그룹이 0.0.0.0/0에 대해 포트 22에서 트래픽을 허용하는 경우 2일 이내에 알림을 받고 싶어합니다. 또한 AWS 리소스 구성의 스냅샷을 정기적으로 가져와야 합니다.<br>보안팀은 이미 Amazon SNS 토픽을 생성하고 구독했습니다.<br>이 요구 사항을 충족하는 솔루션은 무엇입니까?`,
  type: 'single',
  choices: [
    { k:'A', en:`Configure AWS Config to use periodic recording for the AWS account. Deploy the vpc-sg-port-restriction-check AWS Config managed rule. Configure AWS Config to use the SNS topic as the target for notifications.`, ko:`AWS Config를 구성하여 AWS 계정에 대한 주기적 기록을 사용합니다. vpc-sg-port-restriction-check AWS Config 관리 규칙을 배포합니다. AWS Config를 구성하여 알림 대상으로 SNS 토픽을 사용합니다.` },
    { k:'B', en:`Configure AWS Config to use configuration change recording for the AWS account. Deploy the vpc-sg-open-only-to-authorized-ports AWS Config managed rule. Configure AWS Config to use the SNS topic as the target for notifications.`, ko:`AWS Config를 구성하여 AWS 계정에 대한 구성 변경 기록을 사용합니다. vpc-sg-open-only-to-authorized-ports AWS Config 관리 규칙을 배포합니다. AWS Config를 구성하여 알림 대상으로 SNS 토픽을 사용합니다.` },
    { k:'C', en:`Configure AWS Config to use configuration change recording for the AWS account. Deploy the ssh-restricted AWS Config managed rule. Configure AWS Config to use the SNS topic as the target for notifications.`, ko:`AWS Config를 구성하여 AWS 계정에 대한 구성 변경 기록을 사용합니다. ssh-restricted AWS Config 관리 규칙을 배포합니다. AWS Config를 구성하여 알림 대상으로 SNS 토픽을 사용합니다.` },
    { k:'D', en:`Create an AWS Lambda function to evaluate security groups and publish a message to the SNS topic. Use an Amazon EventBridge rule to schedule the Lambda function to run once a day.`, ko:`보안 그룹을 평가하고 SNS 토픽에 메시지를 게시하는 AWS Lambda 함수를 생성합니다. Amazon EventBridge 규칙을 사용하여 Lambda 함수가 하루에 한 번 실행되도록 예약합니다.` },
  ],
  answer: ['C'],
  vote: '79% C',
  explain: `<p><span class="mark-ok">✅ C — 구성 변경 기록 + ssh-restricted 규칙 + SNS</span></p><p><code>ssh-restricted</code>는 0.0.0.0/0에서 포트 22(SSH) 트래픽을 허용하는 보안 그룹을 확인하는 AWS Config 관리형 규칙입니다. 구성 변경 기록은 Auto Scaling 그룹처럼 동적 환경에서 변경 시 즉시 기록되므로 적합합니다. SNS를 알림 대상으로 구성하면 2일 이내에 알림을 받을 수 있습니다.</p>`,
  wrong: `<p><span class="mark-no">❌ A</span> — 주기적 기록은 즉각적인 변경 감지가 아니지만, ssh-restricted 대신 vpe-sg-port-restriction-check도 다소 차이가 있습니다.</p><p><span class="mark-no">❌ B</span> — vpc-sg-open-only-to-authorized-ports는 특정 포트만 허용하는지 확인하는 규칙으로, SSH 전용은 아닙니다.</p><p><span class="mark-no">❌ D</span> — 사용자 지정 Lambda는 불필요한 복잡성을 추가합니다.</p>`,
  disc: [{ ans:'C (79%)', txt:'ssh-restricted 관리형 규칙과 구성 변경 기록이 포트 22 SSH 무제한 허용을 즉시 감지하는 최적의 솔루션입니다.' }]
},
{
  n: 340,
  en: `A company has proprietary data available by using an Amazon CloudFront distribution. The company needs to ensure that the distribution is accessible by only users from the corporate office that have a known set of IP address ranges. An AWS WAF web ACL is associated with the distribution and has a default action set to Count.<br>Which solution will meet these requirements with the LEAST operational overhead?`,
  ko: `한 회사가 Amazon CloudFront 배포를 사용하여 독점 데이터를 사용할 수 있습니다. 회사는 IP 주소 범위가 알려진 회사 사무실의 사용자만 배포에 액세스할 수 있도록 해야 합니다. AWS WAF 웹 ACL이 배포와 연결되어 있으며 기본 작업이 Count로 설정되어 있습니다.<br>가장 적은 운영 오버헤드로 이 요구 사항을 충족하는 솔루션은 무엇입니까?`,
  type: 'single',
  choices: [
    { k:'A', en:`Create a new regex pattern set. Add the regex pattern set to a new rule group. Create a new web ACL that has a default action set to Block. Associate the web ACL with the CloudFront distribution. Add a rule that allows traffic based on the new rule group.`, ko:`새 정규식 패턴 세트를 생성합니다. 정규식 패턴 세트를 새 규칙 그룹에 추가합니다. 기본 작업이 차단으로 설정된 새 웹 ACL을 생성합니다. 웹 ACL을 CloudFront 배포와 연결합니다. 새 규칙 그룹에 따라 트래픽을 허용하는 규칙을 추가합니다.` },
    { k:'B', en:`Create an AWS WAF IP address set that matches the corporate office IP address range. Create a new web ACL that has a default action set to Allow. Associate the web ACL with the CloudFront distribution. Add a rule that allows traffic from the IP address set.`, ko:`회사 사무실 IP 주소 범위와 일치하는 AWS WAF IP 주소 집합을 생성합니다. 기본 작업이 허용으로 설정된 새 웹 ACL을 생성합니다. 웹 ACL을 CloudFront 배포와 연결합니다. IP 주소 집합에서 트래픽을 허용하는 규칙을 추가합니다.` },
    { k:'C', en:`Create a new regex pattern set. Add the regex pattern set to a new rule group. Set the default action on the existing web ACL to Allow. Add a rule that has priority 0 that allows traffic based on the regex pattern set.`, ko:`새 정규식 패턴 세트를 생성합니다. 정규식 패턴 세트를 새 규칙 그룹에 추가합니다. 기존 웹 ACL의 기본 동작을 허용으로 설정합니다. 정규식 패턴 세트에 따라 트래픽을 허용하는 우선순위 0의 규칙을 추가합니다.` },
    { k:'D', en:`Create a WAF IP address set that matches the corporate office IP address range. Set the default action on the existing web ACL to Block. Add a rule that has priority 0 that allows traffic from the IP address set.`, ko:`회사 사무실 IP 주소 범위와 일치하는 WAF IP 주소 집합을 생성합니다. 기존 웹 ACL의 기본 동작을 차단으로 설정합니다. IP 주소 집합에서 트래픽을 허용하는 우선순위 0 규칙을 추가합니다.` },
  ],
  answer: ['D'],
  vote: '100% D',
  explain: `<p><span class="mark-ok">✅ D — 기존 WAF IP 주소 집합 + 기본 동작 차단 + 우선순위 0 허용 규칙</span></p><p>기존 웹 ACL을 재사용(새 ACL 생성 불필요)하므로 운영 오버헤드가 최소화됩니다. 기본 동작을 차단으로 설정하여 모든 트래픽을 차단하고, 우선순위 0(가장 높은 우선순위) 규칙으로 회사 IP 주소 집합의 트래픽만 허용합니다.</p>`,
  wrong: `<p><span class="mark-no">❌ A</span> — IP 주소에 정규식 패턴은 적합하지 않으며 새 웹 ACL 생성은 불필요합니다.</p><p><span class="mark-no">❌ B</span> — 기본 허용 + 규칙 허용은 논리적으로 맞지 않습니다. 기본 차단 + 허용 규칙이 올바른 패턴입니다.</p><p><span class="mark-no">❌ C</span> — 정규식은 IP 주소 범위 매칭에 적합하지 않습니다.</p>`,
  disc: [{ ans:'D (100%)', txt:'기존 WAF 웹 ACL을 재사용하고, 기본 차단 + IP 집합 허용 규칙으로 가장 간단하게 VPC 접근 제한을 구현합니다.' }]
}
];
