window.QS_SET32 = [
{
  n: 311,
  en: `A company uses an AWS Cloud Development Kit (AWS CDK) application for its infrastructure. The AWS CDK application creates AWS Lambda functions and the IAM roles that are attached to the functions. The company also uses AWS Organizations. The company's developers can assume the AWS CDK application deployment role.<br>The company's security team discovered that the developers and the role used to deploy the AWS CDK application have more permissions than necessary. The security team also discovered that the roles attached to the Lambda functions that the CDK application creates have more permissions than necessary. The developers must not have the ability to grant additional permissions.<br>Which solution will meet these requirements with the LEAST operational overhead?`,
  ko: `한 회사가 인프라에 AWS CDK 애플리케이션을 사용합니다. CDK 애플리케이션은 AWS Lambda 함수와 함수에 연결된 IAM 역할을 생성합니다. 회사는 AWS Organizations도 사용합니다. 개발자는 AWS CDK 애플리케이션 배포 역할을 수임할 수 있습니다.<br>보안 팀은 개발자와 CDK 애플리케이션 배포에 사용된 역할에 필요 이상의 권한이 있음을 발견했습니다. 또한 CDK 애플리케이션이 생성한 Lambda 함수에 연결된 역할에도 필요 이상의 권한이 있습니다. 개발자는 추가 권한을 부여할 수 없어야 합니다.<br>최소한의 운영 오버헤드로 이 요구 사항을 충족하는 솔루션은 무엇입니까?`,
  type: 'single',
  choices: [
    { k:'A', en:`Create an SCP that denies the iam:CreateRole action and the iam:UpdateRole action for the developer role and the AWS CDK application deployment role. Centrally create new IAM roles to attach to the Lambda functions for the developers to use to provision Lambda functions.`, ko:`개발자 역할과 AWS CDK 애플리케이션 배포 역할에 대해 iam:CreateRole 및 iam:UpdateRole 작업을 거부하는 SCP를 생성합니다. Lambda 함수에 연결할 새 IAM 역할을 중앙에서 생성합니다.` },
    { k:'B', en:`Create an IAM permission boundary policy. Define the maximum actions that the AWS CDK application requires in the policy. Update the account's AWS CDK bootstrapping to use the permission boundary. Update the configuration in the AWS CDK application for the default permissions boundary to use the policy.`, ko:`IAM 권한 경계 정책을 생성합니다. AWS CDK 애플리케이션이 필요로 하는 최대 작업을 정책에 정의합니다. 권한 경계를 사용하도록 계정의 AWS CDK 부트스트래핑을 업데이트합니다. 기본 권한 경계에 대해 해당 정책을 사용하도록 AWS CDK 애플리케이션의 구성을 업데이트합니다.` },
    { k:'C', en:`Create an IAM permission boundary policy. Define the maximum actions that the AWS CDK application requires in the policy. Instruct the developers to use the permission boundary policy name when they create a role in the AWS CDK application code.`, ko:`IAM 권한 경계 정책을 생성합니다. AWS CDK 애플리케이션이 필요로 하는 최대 작업을 정책에 정의합니다. AWS CDK 애플리케이션 코드에서 역할을 생성할 때 권한 경계 정책 이름을 사용하도록 개발자에게 지시합니다.` },
    { k:'D', en:`Create an SCP that denies the iam:CreateRole action and the iam:UpdateRole action for the developer role. Give the AWS CDK deployment role access to create roles associated with Lambda functions. Run AWS Identity and Access Management Access Analyzer to verify that the Lambda functions role does not have permissions.`, ko:`개발자 역할에 대해 iam:CreateRole 및 iam:UpdateRole 작업을 거부하는 SCP를 생성합니다. AWS CDK 배포 역할에 Lambda 함수와 연결된 역할을 생성할 수 있는 액세스 권한을 부여합니다. IAM Access Analyzer를 실행하여 Lambda 함수 역할에 권한이 없는지 확인합니다.` },
  ],
  answer: ['B'],
  vote: '63% B',
  explain: `<p><span class="mark-ok">✅ B — IAM 권한 경계 + CDK 부트스트래핑 업데이트</span></p><p>CDK 부트스트래핑 수준에서 권한 경계를 설정하면 CDK 애플리케이션이 생성하는 모든 IAM 역할(개발자 역할 포함, Lambda 역할 포함)에 자동으로 권한 경계가 적용됩니다. 이 방식은 사용자 지정 코드 없이 CDK 워크플로와 완벽하게 통합되어 운영 오버헤드를 최소화합니다.</p>`,
  wrong: `<p><span class="mark-no">❌ A</span> — SCP로 역할 생성을 거부하면 CDK 애플리케이션 자체가 역할을 생성할 수 없어 동작하지 않습니다.</p><p><span class="mark-no">❌ C</span> — 개발자에게 수동으로 정책 이름을 사용하도록 지시하는 것은 강제적이지 않고 오류 가능성이 있습니다.</p><p><span class="mark-no">❌ D</span> — Access Analyzer는 사후 감지 도구이며 예방적 통제가 아닙니다.</p>`,
  disc: [{ ans:'B (63%)', txt:'CDK 부트스트래핑에 권한 경계를 설정하면 모든 생성된 역할에 자동으로 적용된다는 의견이 우세합니다.' }]
},
{
  n: 312,
  en: `A company uses Amazon Elastic Container Registry (Amazon ECR) private registries to store container images.<br>A DevOps team needs to ensure that the container images are regularly scanned for software package vulnerabilities.<br>Which solution will meet this requirement?`,
  ko: `한 회사가 컨테이너 이미지를 저장하기 위해 Amazon ECR 프라이빗 레지스트리를 사용합니다.<br>DevOps 팀은 컨테이너 이미지가 소프트웨어 패키지 취약성에 대해 정기적으로 스캔되도록 해야 합니다.<br>이 요구 사항을 충족하는 솔루션은 무엇입니까?`,
  type: 'single',
  choices: [
    { k:'A', en:`Enable enhanced scanning for private registries in Amazon ECR.`, ko:`Amazon ECR에서 프라이빗 레지스트리에 대한 향상된 스캐닝을 활성화합니다.` },
    { k:'B', en:`Enable basic continuous scanning for private registries in Amazon ECR.`, ko:`Amazon ECR에서 프라이빗 레지스트리에 대한 기본적인 연속 스캔을 활성화합니다.` },
    { k:'C', en:`Create an AWS System Manager Automation document to scan images by using the AWS SDK. Configure the Automation document to run when a new image is pushed to an ECR registry.`, ko:`AWS SDK를 사용하여 이미지를 스캔하는 AWS Systems Manager Automation 문서를 생성합니다. ECR 레지스트리에 새 이미지가 푸시될 때 실행되도록 Automation 문서를 구성합니다.` },
    { k:'D', en:`Create an AWS Lambda function that scans all images in Amazon ECR by using the AWS SDK. Create an Amazon EventBridge rule to invoke the Lambda function each day.`, ko:`AWS SDK를 사용하여 Amazon ECR의 모든 이미지를 스캔하는 AWS Lambda 함수를 생성합니다. 매일 Lambda 함수를 호출하는 Amazon EventBridge 규칙을 생성합니다.` },
  ],
  answer: ['A'],
  vote: '100% A',
  explain: `<p><span class="mark-ok">✅ A — Amazon ECR 향상된 스캐닝 활성화</span></p><p>Amazon ECR의 향상된 스캐닝은 Amazon Inspector를 사용하여 컨테이너 이미지를 지속적으로 스캔합니다. 이미지 푸시 시 자동 스캔, 새 취약성 게시 시 재스캔을 지원하며 자세한 취약성 보고서를 제공합니다. AWS가 완전 관리하므로 운영 오버헤드가 최소화됩니다.</p>`,
  wrong: `<p><span class="mark-no">❌ B</span> — 기본 연속 스캔은 향상된 스캔보다 기능이 제한적입니다.</p><p><span class="mark-no">❌ C, D</span> — 사용자 지정 스캐닝 솔루션은 불필요한 복잡성을 추가합니다. AWS 관리형 스캐닝 기능을 사용하는 것이 효율적입니다.</p>`,
  disc: [{ ans:'A (100%)', txt:'향상된 스캐닝은 지속적 자동 스캔과 취약성 게시 시 재스캔을 제공하는 최적의 솔루션입니다.' }]
},
{
  n: 313,
  en: `A security team sets up a workflow that invokes an AWS Step Functions workflow when Amazon EventBridge matches specific events. The events can be generated by several AWS services. AWS CloudTrail records user activities.<br>The security team notices that some important events do not invoke the workflow as expected. The CloudTrail logs do not indicate any direct errors related to the missing events.<br>Which combination of steps will identify the root cause of the missing event invocations? (Choose three.)`,
  ko: `보안팀은 Amazon EventBridge가 특정 이벤트와 일치할 때 AWS Step Functions 워크플로를 호출하는 워크플로를 설정합니다. 이벤트는 여러 AWS 서비스에서 생성될 수 있습니다. AWS CloudTrail은 사용자 활동을 기록합니다.<br>보안팀은 일부 중요한 이벤트가 예상대로 워크플로를 호출하지 않는다는 것을 알아챕니다. CloudTrail 로그는 누락된 이벤트와 관련된 직접적인 오류를 나타내지 않습니다.<br>누락된 이벤트 호출의 근본 원인을 식별하는 단계 조합은 무엇입니까? (3개 선택)`,
  type: 'multi', multiCount: 3,
  choices: [
    { k:'A', en:`Enable EventBridge schema discovery on the event bus to determine whether the event patterns match the expected schema.`, ko:`이벤트 버스에서 EventBridge 스키마 검색을 활성화하여 이벤트 패턴이 예상 스키마와 일치하는지 확인합니다.` },
    { k:'B', en:`Configure Amazon CloudWatch to monitor EventBridge metrics and Step Functions metrics. Set up alerts for anomalies in event patterns and workflow invocations.`, ko:`Amazon CloudWatch를 구성하여 EventBridge 메트릭과 Step Functions 메트릭을 모니터링합니다. 이벤트 패턴과 워크플로 호출의 이상에 대한 알림을 설정합니다.` },
    { k:'C', en:`Configure an AWS Lambda logging function to monitor and log events from EventBridge to provide more details about the processed events.`, ko:`EventBridge에서 이벤트를 모니터링하고 기록하여 처리된 이벤트에 대한 자세한 정보를 제공하는 AWS Lambda 로깅 함수를 구성합니다.` },
    { k:'D', en:`Review the Step Functions execution history for patterns of failures or timeouts that could correlate to the missing event invocations.`, ko:`누락된 이벤트 호출과 연관이 있을 수 있는 실패 또는 시간 초과 패턴을 확인하기 위해 Step Functions 실행 기록을 검토합니다.` },
    { k:'E', en:`Review metrics for the EventBridge failed invocations to ensure that the IAM execution role that is attached to the rule has sufficient permissions.`, ko:`규칙에 연결된 IAM 실행 역할에 충분한 권한이 있는지 확인하기 위해 EventBridge 실패한 호출에 대한 메트릭을 검토합니다.` },
    { k:'F', en:`Verify that the Step Functions workflow has the correct permissions to be invoked by EventBridge.`, ko:`EventBridge에서 Step Functions 워크플로를 호출하는 데 필요한 올바른 권한이 있는지 확인합니다.` },
  ],
  answer: ['A','B','E'],
  vote: '100% ABE',
  explain: `<p><span class="mark-ok">✅ A — EventBridge 스키마 검색으로 이벤트 구조 검증</span></p><p>이벤트 패턴이 예상 스키마와 일치하지 않으면 EventBridge 규칙이 이벤트를 매칭하지 못합니다. 스키마 검색으로 이를 확인합니다.</p><p><span class="mark-ok">✅ B — CloudWatch 메트릭으로 이상 모니터링</span></p><p>EventBridge와 Step Functions 메트릭을 모니터링하여 이벤트 패턴과 워크플로 호출의 이상을 감지합니다.</p><p><span class="mark-ok">✅ E — EventBridge 실패 호출 메트릭 검토</span></p><p>EventBridge 규칙의 IAM 실행 역할에 Step Functions를 호출할 권한이 있는지 확인합니다. Step Functions는 리소스 기반 정책을 지원하지 않으므로 EventBridge 규칙의 역할 권한이 중요합니다.</p>`,
  wrong: `<p><span class="mark-no">❌ C</span> — Lambda 로깅 함수를 추가하는 것은 불필요한 복잡성을 추가합니다.</p><p><span class="mark-no">❌ D</span> — Step Functions 실행이 시작되지 않은 경우 실행 기록이 없으므로 근본 원인 파악에 도움이 안 됩니다.</p><p><span class="mark-no">❌ F</span> — Step Functions는 리소스 기반 정책이 없으므로 EventBridge 규칙의 역할 권한(E)이 올바른 접근입니다.</p>`,
  disc: [{ ans:'ABE (100%)', txt:'스키마 검증, CloudWatch 모니터링, EventBridge 실패 호출 메트릭 검토가 핵심 진단 단계라는 의견이 일치합니다.' }]
},
{
  n: 314,
  en: `A company's DevOps engineer uses AWS Systems Manager to perform maintenance tasks. The company has a few Amazon EC2 instances that require a restart after notifications from AWS Health.<br>The DevOps engineer must implement an automated solution that uses Amazon EventBridge to remediate the notifications during the company's scheduled maintenance windows.<br>How should the DevOps engineer configure an EventBridge rule to meet these requirements?`,
  ko: `회사의 DevOps 엔지니어는 AWS Systems Manager를 사용하여 유지 관리 작업을 수행합니다. 회사에는 AWS Health에서 알림을 받은 후 재시작이 필요한 Amazon EC2 인스턴스가 몇 개 있습니다.<br>DevOps 엔지니어는 회사의 예약된 유지 관리 기간 동안 알림을 수정하기 위해 Amazon EventBridge를 사용하는 자동화된 솔루션을 구현해야 합니다.<br>이 요구 사항을 충족하기 위해 EventBridge 규칙을 어떻게 구성해야 합니까?`,
  type: 'single',
  choices: [
    { k:'A', en:`Configure an event source of AWS Health. Configure event types that indicate scheduled instance termination and retirement. Target the AWS-RestartEC2Instance Systems Manager Automation runbook to restart the EC2 instances.`, ko:`AWS Health의 이벤트 소스를 구성합니다. 예약된 인스턴스 종료 및 서비스 해제를 나타내는 이벤트 유형을 구성합니다. EC2 인스턴스를 재시작하려면 AWS-RestartEC2Instance Systems Manager Automation 런북을 대상으로 합니다.` },
    { k:'B', en:`Configure an event source of Systems Manager. Configure an event type that indicates a maintenance window. Target the AWS-RestartEC2Instance Systems Manager Automation runbook to restart the EC2 instances.`, ko:`Systems Manager의 이벤트 소스를 구성합니다. 유지 관리 기간을 나타내는 이벤트 유형을 구성합니다. EC2 인스턴스를 재시작하려면 AWS-RestartEC2Instance Systems Manager Automation 런북을 대상으로 합니다.` },
    { k:'C', en:`Configure an event source of AWS Health. Configure event types that indicate scheduled instance termination and retirement. Target a newly created AWS Lambda function that registers a Systems Manager maintenance window task to restart the EC2 instances.`, ko:`AWS Health의 이벤트 소스를 구성합니다. 예약된 인스턴스 종료 및 서비스 해제를 나타내는 이벤트 유형을 구성합니다. EC2 인스턴스를 재시작하기 위해 Systems Manager 유지 관리 기간 작업을 등록하는 새로 생성된 AWS Lambda 함수를 대상으로 합니다.` },
    { k:'D', en:`Configure an event source of EC2. Configure an event type that indicates instance state notification. Target a newly created AWS Lambda function that registers a Systems Manager maintenance window task to restart the EC2 instances.`, ko:`EC2의 이벤트 소스를 구성합니다. 인스턴스 상태 알림을 나타내는 이벤트 유형을 구성합니다. EC2 인스턴스를 재시작하기 위해 Systems Manager 유지 관리 기간 작업을 등록하는 새로 생성된 AWS Lambda 함수를 대상으로 합니다.` },
  ],
  answer: ['A'],
  vote: '67% A',
  explain: `<p><span class="mark-ok">✅ A — AWS Health 이벤트 + AWS-RestartEC2Instance 런북</span></p><p>AWS Health는 예약된 인스턴스 종료 및 서비스 해제 이벤트를 발생시킵니다. EventBridge에서 이러한 이벤트를 감지하고 AWS-RestartEC2Instance Systems Manager Automation 런북을 직접 호출하면 중간 Lambda 함수 없이 간결한 솔루션이 됩니다. 유지 관리 기간과 통합된 SSM이 재시작을 관리합니다.</p>`,
  wrong: `<p><span class="mark-no">❌ B</span> — Systems Manager는 Health 알림과 관련된 이벤트 소스를 제공하지 않습니다.</p><p><span class="mark-no">❌ C</span> — Lambda로 유지 관리 기간 작업을 등록하는 방식은 불필요한 복잡성을 추가합니다.</p><p><span class="mark-no">❌ D</span> — EC2 인스턴스 상태 알림은 AWS Health 이벤트와 다릅니다.</p>`,
  disc: [{ ans:'A (67%) vs C (33%)', txt:'A가 간단하지만, C는 유지 관리 기간을 더 정확히 준수한다는 논쟁이 있습니다. AWS Health 이벤트가 인스턴스 재시작의 직접적 트리거로 적합합니다.' }]
},
{
  n: 315,
  en: `A DevOps engineer manages an AWS CodePipeline pipeline that builds and deploys a web application on AWS. The pipeline has a source stage, a build stage, and a deploy stage. When deployed properly, the web application responds with a 200 OK HTTP response code when the URL of the home page is requested.<br>The home page recently returned a 503 HTTP response code after CodePipeline deployed the application. The DevOps engineer needs to add an automated test into the pipeline. The automated test must ensure that the application returns a 200 OK HTTP response code after the application is deployed. The pipeline must fail if the response code is not present during the test. The DevOps engineer has added a CheckURL stage after the deploy stage in the pipeline.<br>What should the DevOps engineer do next to implement the automated test?`,
  ko: `DevOps 엔지니어는 AWS에서 웹 애플리케이션을 빌드하고 배포하는 AWS CodePipeline 파이프라인을 관리합니다. 파이프라인에는 소스, 빌드, 배포 스테이지가 있습니다. 올바르게 배포된 경우 웹 애플리케이션은 홈페이지 URL 요청 시 200 OK HTTP 응답 코드로 응답합니다.<br>최근에 CodePipeline이 애플리케이션을 배포한 후 홈페이지에서 503 HTTP 응답 코드가 반환되었습니다. 배포 후 애플리케이션이 200 OK HTTP 응답 코드를 반환하는지 확인하는 자동화된 테스트를 파이프라인에 추가해야 합니다. DevOps 엔지니어는 파이프라인의 배포 스테이지 뒤에 CheckURL 스테이지를 추가했습니다.<br>자동화된 테스트를 구현하기 위해 다음에 무엇을 해야 합니까?`,
  type: 'single',
  choices: [
    { k:'A', en:`Configure the CheckURL stage to use an Amazon CloudWatch action. Configure the action to use a canary synthetic monitoring check on the application URL and to report a success or failure to CodePipeline.`, ko:`CheckURL 스테이지를 구성하여 Amazon CloudWatch 작업을 사용합니다. 애플리케이션 URL에서 카나리아 합성 모니터링 검사를 사용하고 CodePipeline에 성공 또는 실패를 보고하도록 작업을 구성합니다.` },
    { k:'B', en:`Create an AWS Lambda function to check the response code status of the URL and to report a success or failure to CodePipeline. Configure an action in the CheckURL stage to invoke the Lambda function.`, ko:`URL의 응답 코드 상태를 확인하고 CodePipeline에 성공 또는 실패를 보고하는 AWS Lambda 함수를 생성합니다. CheckURL 스테이지에서 Lambda 함수를 호출하는 작업을 구성합니다.` },
    { k:'C', en:`Configure the CheckURL stage to use an AWS CodeDeploy action. Configure the action with an input artifact that is the URL of the application and to report a success or failure to CodePipeline.`, ko:`CheckURL 스테이지를 구성하여 AWS CodeDeploy 작업을 사용합니다. 애플리케이션 URL을 입력 아티팩트로 사용하고 CodePipeline에 성공 또는 실패를 보고하도록 작업을 구성합니다.` },
    { k:'D', en:`Deploy an Amazon API Gateway HTTP API that checks the response code status of the URL and that reports success or failure to CodePipeline. Configure the CheckURL stage to use the AWS Device Farm test action and to provide the API Gateway HTTP API as an input artifact.`, ko:`URL의 응답 코드 상태를 확인하고 CodePipeline에 성공 또는 실패를 보고하는 Amazon API Gateway HTTP API를 배포합니다. CheckURL 스테이지를 구성하여 AWS Device Farm 테스트 작업을 사용하고 API Gateway HTTP API를 입력 아티팩트로 제공합니다.` },
  ],
  answer: ['B'],
  vote: '100% B',
  explain: `<p><span class="mark-ok">✅ B — Lambda 함수로 URL 응답 코드 확인 + CodePipeline 보고</span></p><p>AWS Lambda 함수는 애플리케이션의 홈페이지 URL에 HTTP 요청을 보내고 응답 코드를 확인합니다. 200 OK가 아닌 경우 실패를 CodePipeline에 보고하면 파이프라인이 실패합니다. Lambda 작업은 CodePipeline과 기본 통합되어 있어 가장 직접적이고 간단한 구현 방법입니다.</p>`,
  wrong: `<p><span class="mark-no">❌ A</span> — CloudWatch 합성 모니터링은 지속적인 모니터링을 위한 것으로 파이프라인 단일 테스트에 적합하지 않습니다.</p><p><span class="mark-no">❌ C</span> — CodeDeploy는 애플리케이션 배포 도구로 URL 응답 코드 검사 기능이 없습니다.</p><p><span class="mark-no">❌ D</span> — API Gateway + Device Farm은 불필요하게 복잡합니다.</p>`,
  disc: [{ ans:'B (100%)', txt:'Lambda를 CheckURL 스테이지의 작업으로 사용하는 것이 가장 간단하고 직접적인 솔루션이라는 의견이 일치합니다.' }]
},
{
  n: 316,
  en: `A company has an application that uploads access logs to an Amazon CloudWatch Logs log group. The fields in the log lines include the response code and the application name.<br>The company wants to create a CloudWatch metric to track the number of requests by response code in a specific range and with a specific application name.<br>Which solution will meet these requirements?`,
  ko: `한 회사의 애플리케이션이 액세스 로그를 Amazon CloudWatch Logs 로그 그룹에 업로드합니다. 로그 줄의 필드에는 응답 코드와 애플리케이션 이름이 포함됩니다.<br>이 회사는 특정 범위와 특정 애플리케이션 이름을 가진 응답 코드별 요청 수를 추적하는 CloudWatch 메트릭을 생성하려 합니다.<br>이 요구 사항을 충족하는 솔루션은 무엇입니까?`,
  type: 'single',
  choices: [
    { k:'A', en:`Create a CloudWatch Logs log event filter on the CloudWatch Logs log stream to match the response code range. Configure the log event filter to increment a metric. Set the response code and application name as dimensions.`, ko:`CloudWatch Logs 로그 스트림에서 응답 코드 범위와 일치하도록 CloudWatch Logs 로그 이벤트 필터를 생성합니다. 메트릭을 증가시키도록 로그 이벤트 필터를 구성합니다. 응답 코드와 애플리케이션 이름을 차원으로 설정합니다.` },
    { k:'B', en:`Create a CloudWatch Logs metric filter on the CloudWatch Logs log group to match the response code range. Configure the metric filter to increment a metric. Set the response code and application name as dimensions.`, ko:`CloudWatch Logs 로그 그룹에서 응답 코드 범위와 일치하도록 CloudWatch Logs 메트릭 필터를 생성합니다. 메트릭을 증가시키도록 메트릭 필터를 구성합니다. 응답 코드와 애플리케이션 이름을 차원으로 설정합니다.` },
    { k:'C', en:`Create a CloudWatch Contributor Insights rule on the CloudWatch Logs log stream with a filter to match the response code range. Configure the Contributor Insights rule to increment a CloudWatch metric with the response code and application name as dimensions.`, ko:`응답 코드 범위와 일치하는 필터가 있는 CloudWatch Logs 로그 스트림에서 CloudWatch Contributor Insights 규칙을 생성합니다. 응답 코드와 애플리케이션 이름을 차원으로 사용하여 CloudWatch 메트릭을 증가시키도록 Contributor Insights 규칙을 구성합니다.` },
    { k:'D', en:`Create a CloudWatch Logs Insights query on the CloudWatch Logs log group to match the response code range. Configure the Logs Insights query to increment a CloudWatch metric with the response code and application name as dimensions.`, ko:`응답 코드 범위와 일치하도록 CloudWatch Logs 로그 그룹에 CloudWatch Logs Insights 쿼리를 생성합니다. 응답 코드와 애플리케이션 이름을 차원으로 사용하여 CloudWatch 메트릭을 증가시키도록 Logs Insights 쿼리를 구성합니다.` },
  ],
  answer: ['B'],
  vote: '100% B',
  explain: `<p><span class="mark-ok">✅ B — CloudWatch Logs 메트릭 필터 (로그 그룹 수준)</span></p><p>CloudWatch Logs 메트릭 필터는 로그 그룹 수준에서 특정 패턴을 추출하여 CloudWatch 메트릭을 생성합니다. 응답 코드 범위와 일치하는 필터 패턴을 설정하고, 응답 코드와 애플리케이션 이름을 메트릭 차원으로 지정하면 요청 수를 추적하는 메트릭을 생성할 수 있습니다.</p>`,
  wrong: `<p><span class="mark-no">❌ A</span> — "로그 이벤트 필터"는 로그 스트림 수준으로, 메트릭 필터와 다릅니다. 메트릭 생성은 로그 그룹 수준에서 지원됩니다.</p><p><span class="mark-no">❌ C</span> — Contributor Insights는 로그 기여자 분석을 위한 것으로 사용자 지정 메트릭을 직접 생성하지 않습니다.</p><p><span class="mark-no">❌ D</span> — Logs Insights 쿼리는 대화형 분석 도구이며 지속적인 메트릭 생성에 적합하지 않습니다.</p>`,
  disc: [{ ans:'B (100%)', txt:'로그 그룹에서 메트릭 필터를 생성하고 응답 코드와 애플리케이션 이름을 차원으로 사용하는 것이 올바른 방법이라는 의견이 일치합니다.' }]
},
{
  n: 317,
  en: `A DevOps engineer provisioned an Amazon Elastic Kubernetes Service (Amazon EKS) cluster with managed node groups. The DevOps engineer associated an OpenID Connect (OIDC) issuer with the cluster.<br>The DevOps engineer is configuring Amazon Elastic Block Store (Amazon EBS) General Purpose SSD (gp3) volumes for the cluster. The DevOps engineer attempts to initiate a PersistentVolumeClaim (PVC) request but is unable to provision a volume. To troubleshoot the issue, the DevOps engineer runs the <code>kubectl describe pvc</code> command. The DevOps engineer receives a failed to provision volume with StorageClass error and a could not create volume in EC2:UnauthorizedOperation error.<br>Which solution will resolve these errors?`,
  ko: `DevOps 엔지니어가 관리형 노드 그룹이 있는 Amazon EKS 클러스터를 프로비저닝했습니다. DevOps 엔지니어는 OIDC 발급자를 클러스터와 연결했습니다.<br>EKS 클러스터에 Amazon EBS gp3 볼륨을 구성하고 있습니다. PersistentVolumeClaim(PVC) 요청을 시작하려 하지만 볼륨을 프로비저닝할 수 없습니다. <code>kubectl describe pvc</code> 명령을 실행하면 StorageClass 오류와 함께 볼륨 프로비저닝 실패 및 EC2:UnauthorizedOperation 오류를 수신합니다.<br>이 오류를 해결하는 솔루션은 무엇입니까?`,
  type: 'single',
  choices: [
    { k:'A', en:`Create a Kubernetes cluster role that allows the persistent volumes to perform get, list, watch, create, and delete operations. Configure the cluster role to allow get, list, and watch operations for storage in the cluster.`, ko:`영구 볼륨이 get, list, watch, create, delete 작업을 수행할 수 있도록 하는 Kubernetes 클러스터 역할을 생성합니다. 클러스터의 스토리지에 대한 get, list, watch 작업을 허용하도록 클러스터 역할을 구성합니다.` },
    { k:'B', en:`Create an Amazon EBS Container Storage Interface (CSI) driver IAM role that has the required permissions and trust relationships. Attach the IAM role to the Amazon EBS CSI driver add-on in the cluster.`, ko:`필요한 권한과 신뢰 관계가 있는 Amazon EBS CSI 드라이버 IAM 역할을 생성합니다. 클러스터의 Amazon EBS CSI 드라이버 애드온에 IAM 역할을 연결합니다.` },
    { k:'C', en:`Add the ebs.csi.aws.com/volumeType:gp3 annotation to the PersistentVolumeClaim object in the cluster.`, ko:`클러스터의 PersistentVolumeClaim 객체에 ebs.csi.aws.com/volumeType:gp3 주석을 추가합니다.` },
    { k:'D', en:`Create a Kubernetes storage class object. Set the provisioner value to ebs.csi.aws.com. Set the volumeBindingMode value to WaitForFirstConsumer in the cluster.`, ko:`Kubernetes 스토리지 클래스 객체를 생성합니다. provisioner 값을 ebs.csi.aws.com으로 설정합니다. 클러스터에서 volumeBindingMode 값을 WaitForFirstConsumer로 설정합니다.` },
  ],
  answer: ['B'],
  vote: '100% B',
  explain: `<p><span class="mark-ok">✅ B — EBS CSI 드라이버 IAM 역할 생성 및 연결</span></p><p>오류 메시지 "EC2:UnauthorizedOperation"은 EBS CSI 드라이버에 EC2 API를 통해 EBS 볼륨을 프로비저닝하는 데 필요한 IAM 권한이 없음을 나타냅니다. OIDC가 구성되어 있으므로 IAM 역할을 생성하여 서비스 계정에 연결하고 EBS CSI 드라이버 애드온에 적용해야 합니다.</p>`,
  wrong: `<p><span class="mark-no">❌ A</span> — Kubernetes RBAC는 Kubernetes API 권한을 제어하며, EC2 API 호출 권한과 무관합니다.</p><p><span class="mark-no">❌ C</span> — 볼륨 유형 주석은 스토리지 유형을 지정하는 것으로 IAM 권한 오류를 해결하지 않습니다.</p><p><span class="mark-no">❌ D</span> — StorageClass 구성은 스토리지 프로비저닝 방식이지 IAM 권한 문제의 해결책이 아닙니다.</p>`,
  disc: [{ ans:'B (100%)', txt:'EC2:UnauthorizedOperation 오류는 EBS CSI 드라이버의 IAM 권한 부재가 원인이며, IAM 역할 생성 및 연결이 올바른 해결책입니다.' }]
},
{
  n: 318,
  en: `A company runs a fleet of Amazon EC2 instances in a VPC. The company's employees remotely access the EC2 instances by using the Remote Desktop Protocol (RDP).<br>The company wants to collect metrics about how many RDP sessions the employees initiate every day.<br>Which combination of steps will meet this requirement? (Choose three.)`,
  ko: `한 회사가 VPC에서 Amazon EC2 인스턴스 플릿을 운영합니다. 회사 직원들은 RDP(Remote Desktop Protocol)를 사용하여 EC2 인스턴스에 원격으로 액세스합니다.<br>회사는 직원들이 매일 시작하는 RDP 세션 수에 대한 메트릭을 수집하려 합니다.<br>이 요구 사항을 충족하는 단계 조합은 무엇입니까? (3개 선택)`,
  type: 'multi', multiCount: 3,
  choices: [
    { k:'A', en:`Create an Amazon EventBridge rule that reacts to EC2 Instance State-change Notification events.`, ko:`EC2 인스턴스 상태 변경 알림 이벤트에 반응하는 Amazon EventBridge 규칙을 생성합니다.` },
    { k:'B', en:`Create an Amazon CloudWatch Logs log group. Specify the log group as a target for the EventBridge rule.`, ko:`Amazon CloudWatch Logs 로그 그룹을 생성합니다. 로그 그룹을 EventBridge 규칙의 대상으로 지정합니다.` },
    { k:'C', en:`Create a flow log in VPC Flow Logs.`, ko:`VPC Flow Logs에 흐름 로그를 생성합니다.` },
    { k:'D', en:`Create an Amazon CloudWatch Logs log group. Specify the log group as a destination for the flow log.`, ko:`Amazon CloudWatch Logs 로그 그룹을 생성합니다. 로그 그룹을 흐름 로그의 대상으로 지정합니다.` },
    { k:'E', en:`Create a log group metric filter.`, ko:`로그 그룹 메트릭 필터를 생성합니다.` },
    { k:'F', en:`Create a log group subscription filter. Use EventBridge as the destination.`, ko:`로그 그룹 구독 필터를 생성합니다. EventBridge를 대상으로 사용합니다.` },
  ],
  answer: ['C','D','E'],
  vote: '90% CDE',
  explain: `<p><span class="mark-ok">✅ C — VPC Flow Logs 흐름 로그 생성</span></p><p>VPC Flow Logs는 TCP 포트 3389(RDP)를 포함한 VPC의 네트워크 트래픽을 캡처합니다. 에이전트 설치 없이 네트워크 관점에서 RDP 세션을 감지하는 유일한 방법입니다.</p><p><span class="mark-ok">✅ D — CloudWatch Logs 로그 그룹을 흐름 로그 대상으로 지정</span></p><p>흐름 로그 데이터를 CloudWatch Logs에 저장하여 분석할 수 있도록 합니다.</p><p><span class="mark-ok">✅ E — 로그 그룹 메트릭 필터 생성</span></p><p>포트 3389와 ACCEPT 작업을 필터링하는 메트릭 필터를 생성하여 RDP 연결 수를 계산하는 CloudWatch 메트릭을 만듭니다.</p>`,
  wrong: `<p><span class="mark-no">❌ A, B</span> — EC2 상태 변경 이벤트는 RDP 세션 시작과 직접 관련이 없습니다.</p><p><span class="mark-no">❌ F</span> — 구독 필터는 로그를 다른 서비스로 스트리밍하는 용도이며 메트릭 생성이 아닙니다.</p>`,
  disc: [{ ans:'CDE (90%)', txt:'VPC Flow Logs로 네트워크 트래픽 캡처, CloudWatch Logs로 저장, 메트릭 필터로 RDP 세션 수 계산하는 것이 올바른 패턴입니다.' }]
},
{
  n: 319,
  en: `A company is using Amazon Elastic Kubernetes Service (Amazon EKS) to run its applications. The EKS cluster is successfully running multiple pods. The company stores the pod images in Amazon Elastic Container Registry (Amazon ECR).<br>The company needs to configure Pod Identity access for the EKS cluster. The company has already updated the node IAM role by using the permissions for Pod Identity access.<br>Which solution will meet these requirements?`,
  ko: `한 회사가 Amazon EKS를 사용하여 애플리케이션을 실행합니다. EKS 클러스터는 여러 포드를 성공적으로 실행 중입니다. 회사는 포드 이미지를 Amazon ECR에 저장합니다.<br>회사는 EKS 클러스터에 대한 Pod Identity 액세스를 구성해야 합니다. 회사는 이미 Pod Identity 액세스 권한을 사용하여 노드 IAM 역할을 업데이트했습니다.<br>이 요구 사항을 충족하는 솔루션은 무엇입니까?`,
  type: 'single',
  choices: [
    { k:'A', en:`Create an IAM OpenID Connect (OIDC) provider for the EKS cluster.`, ko:`EKS 클러스터에 대한 IAM OpenID Connect(OIDC) 공급자를 생성합니다.` },
    { k:'B', en:`Ensure that the nodes can reach the EKS Auth API. Add and configure the EKS Pod Identity Agent add-on for the EKS cluster.`, ko:`노드가 EKS Auth API에 도달할 수 있는지 확인합니다. EKS 클러스터에 EKS Pod Identity Agent 애드온을 추가하고 구성합니다.` },
    { k:'C', en:`Create an EKS access entry that uses the API_AND_CONFIG_MAP cluster authentication mode.`, ko:`API_AND_CONFIG_MAP 클러스터 인증 모드를 사용하는 EKS 액세스 항목을 생성합니다.` },
    { k:'D', en:`Configure the AWS Security Token Service (AWS STS) endpoint for the Kubernetes service account that the pods in the EKS cluster use.`, ko:`EKS 클러스터의 포드가 사용하는 Kubernetes 서비스 계정에 대한 AWS STS 엔드포인트를 구성합니다.` },
  ],
  answer: ['B'],
  vote: '85% B',
  explain: `<p><span class="mark-ok">✅ B — EKS Pod Identity Agent 애드온 추가</span></p><p>EKS Pod Identity는 IRSA(서비스 계정용 IAM 역할)의 새로운 대안으로, OIDC에 의존하지 않습니다. Pod Identity를 사용하려면 다음이 필요합니다: (1) 노드 IAM 역할 업데이트(이미 완료), (2) EKS Auth API 접근 가능 여부 확인, (3) EKS Pod Identity Agent 애드온 설치 및 구성.</p>`,
  wrong: `<p><span class="mark-no">❌ A</span> — OIDC는 IRSA를 위한 것이며, Pod Identity는 OIDC가 필요 없습니다.</p><p><span class="mark-no">❌ C</span> — EKS 액세스 항목은 클러스터 인증 설정이며 Pod Identity와 무관합니다.</p><p><span class="mark-no">❌ D</span> — AWS STS 엔드포인트 구성은 Pod Identity 설정과 관련 없습니다.</p>`,
  disc: [{ ans:'B (85%)', txt:'EKS Pod Identity는 OIDC 불필요, Pod Identity Agent 애드온 설치가 핵심 단계라는 의견이 우세합니다.' }]
},
{
  n: 320,
  en: `A company has multiple AWS accounts in an organization in AWS Organizations that has all features enabled. The company's DevOps administrator needs to improve security across all the company's AWS accounts. The administrator needs to identify the top users and roles in use across all accounts.<br>Which solution will meet these requirements with the MOST operational efficiency?`,
  ko: `한 회사가 모든 기능이 활성화된 AWS Organizations의 조직에 여러 AWS 계정을 보유하고 있습니다. 회사의 DevOps 관리자는 모든 AWS 계정에서 보안을 개선해야 합니다. 관리자는 모든 계정에서 사용 중인 상위 사용자와 역할을 식별해야 합니다.<br>가장 높은 운영 효율성으로 이 요구 사항을 충족하는 솔루션은 무엇입니까?`,
  type: 'single',
  choices: [
    { k:'A', en:`Create a new organization trail in AWS CloudTrail. Configure the trail to send log events to Amazon CloudWatch Logs. Create a CloudWatch Contributor Insights rule for the userIdentity.arn log field. View the results in CloudWatch Contributor Insights.`, ko:`AWS CloudTrail에서 새 조직 트레일을 생성합니다. 로그 이벤트를 Amazon CloudWatch Logs로 보내도록 트레일을 구성합니다. userIdentity.arn 로그 필드에 대한 CloudWatch Contributor Insights 규칙을 생성합니다. CloudWatch Contributor Insights에서 결과를 확인합니다.` },
    { k:'B', en:`Use AWS Identity and Access Management Access Analyzer to create an unused access analysis for the organization. Review the analyzer results and determine if each finding has the intended level of permissions required for the workload.`, ko:`AWS IAM Access Analyzer를 사용하여 조직에 대한 사용되지 않은 액세스 분석을 생성합니다. 분석기 결과를 검토하고 각 결과에 워크로드에 필요한 의도된 수준의 권한이 있는지 확인합니다.` },
    { k:'C', en:`Create a new organization trail in AWS CloudTrail. Create a table in Amazon Athena that uses partition projection. Load the Athena table with CloudTrail data. Query the Athena table to find the top users and roles.`, ko:`AWS CloudTrail에서 새 조직 트레일을 생성합니다. 파티션 프로젝션을 사용하는 Amazon Athena에서 테이블을 생성합니다. CloudTrail 데이터로 Athena 테이블을 로드합니다. Athena 테이블을 쿼리하여 상위 사용자와 역할을 찾습니다.` },
    { k:'D', en:`Generate a Service access report for each account by using Organizations. From the results, pull the last accessed date and last accessed by account fields to find the top users and roles.`, ko:`Organizations를 사용하여 각 계정에 대한 서비스 액세스 보고서를 생성합니다. 결과에서 마지막으로 액세스한 날짜와 계정별 마지막으로 액세스한 필드를 가져와 상위 사용자와 역할을 찾습니다.` },
  ],
  answer: ['C'],
  vote: '58% C',
  explain: `<p><span class="mark-ok">✅ C — CloudTrail 조직 트레일 + Athena 파티션 프로젝션</span></p><p>조직 트레일로 모든 계정의 CloudTrail 로그를 집계하고, Athena의 파티션 프로젝션으로 대규모 로그를 효율적으로 쿼리합니다. SQL 쿼리로 자동화 반복 가능하게 상위 사용자와 역할을 파악할 수 있습니다.</p>`,
  wrong: `<p><span class="mark-no">❌ A</span> — Contributor Insights는 실시간 분석에 적합하지만, 대규모 멀티 계정 환경에서 역사적 데이터 분석은 Athena가 더 효율적입니다.</p><p><span class="mark-no">❌ B</span> — IAM Access Analyzer는 사용되지 않는 액세스를 찾는 도구로, 상위 사용자 식별과 목적이 다릅니다.</p><p><span class="mark-no">❌ D</span> — 서비스 액세스 보고서는 개별 사용자/역할별 활동을 추적하는 데 적합하지 않습니다.</p>`,
  disc: [{ ans:'C (58%) vs A (42%)', txt:'Athena 파티션 프로젝션이 운영 효율성 측면에서 더 강력하다는 의견과 Contributor Insights가 더 간단하다는 의견이 나뉩니다.' }]
}
];
