window.QS_SET04 = [
{
  n:31,
  ko:`한 회사가 컨테이너 기반 애플리케이션을 Amazon EKS로 마이그레이션했고 자동화된 이메일 알림을 설정하려고 합니다. 각 이메일 주소로 전송된 알림은 EKS 구성 요소와 관련된 특정 활동을 위한 것입니다. 이 솔루션에는 Amazon SNS 토픽과 들어오는 로그 이벤트를 평가하고 올바른 SNS 토픽에 메시지를 게시하는 AWS Lambda 함수가 포함됩니다.<br><br><strong>어떤 로깅 솔루션이 이러한 요구 사항을 지원할까요?</strong>`,
  en:`A company has migrated its container-based applications to Amazon EKS and want to establish automated email notifications. The notifications sent to each email address are for specific activities related to EKS components. The solution will include Amazon SNS topics and an AWS Lambda function to evaluate incoming log events and publish messages to the correct SNS topic. Which logging solution will support these requirements?`,
  type:'single',
  choices:[
    {k:'A', ko:`Amazon CloudWatch Logs를 활성화하여 EKS 구성 요소를 로깅합니다. Lambda를 구독 피드 대상으로 하여 각 구성 요소에 대한 CloudWatch 구독 필터를 만듭니다.`, en:`Enable Amazon CloudWatch Logs to log the EKS components. Create a CloudWatch subscription filter for each component with Lambda as the subscription feed destination.`},
    {k:'B', ko:`Amazon CloudWatch Logs를 활성화하여 EKS 구성 요소를 로깅합니다. Lambda를 호출하는 Amazon EventBridge 이벤트에 연결된 CloudWatch Logs Insights 쿼리를 만듭니다.`, en:`Enable Amazon CloudWatch Logs to log the EKS components. Create CloudWatch Logs Insights queries linked to Amazon EventBridge events that invoke Lambda.`},
    {k:'C', ko:`EKS 구성 요소에 대한 Amazon S3 로깅을 활성화합니다. Lambda를 구독 피드 대상으로 하여 각 구성 요소에 대한 Amazon CloudWatch 구독 필터를 구성합니다.`, en:`Enable Amazon S3 logging for the EKS components. Configure an Amazon CloudWatch subscription filter for each component with Lambda as the subscription feed destination.`},
    {k:'D', ko:`EKS 구성 요소에 대한 Amazon S3 로깅을 활성화합니다. AWS Lambda를 대상으로 S3 PUT Object 이벤트 알림을 구성합니다.`, en:`Enable Amazon S3 logging for the EKS components. Configure S3 PUT Object event notifications with AWS Lambda as the destination.`},
  ],
  answer:['A'],
  vote:'97% A',
  explain:`<p><span class="mark-ok">✅ A — CloudWatch Logs + 구독 필터 → Lambda</span></p><p>Amazon EKS는 CloudWatch Logs와 통합되어 클러스터 컴포넌트 로그를 수집합니다. CloudWatch Logs 구독 필터를 사용하면 특정 패턴의 로그 이벤트가 발생할 때 실시간으로 Lambda를 호출할 수 있습니다.</p>`,
  wrong:`<p><span class="mark-no">❌ C, D</span> — EKS는 S3에 직접 로그를 저장하는 네이티브 통합이 없습니다.</p>`,
  disc:[{ans:'A (97%)',txt:'CloudWatch Logs 구독 필터 → Lambda 패턴은 실시간 로그 처리의 표준 방식입니다.'}]
},
{
  n:32,
  ko:`한 회사가 Amazon Elastic Container Service(Amazon ECS) 클러스터를 구현하고 있습니다. 회사 아키텍처는 클러스터에서 여러 ECS 서비스를 실행합니다. 아키텍처에는 프런트 엔드에 Application Load Balancer가 포함되어 있으며 여러 대상 그룹을 사용하여 트래픽을 라우팅합니다. DevOps 엔지니어는 애플리케이션과 액세스 로그를 수집해야 합니다. 그런 다음 DevOps 엔지니어는 거의 실시간 분석을 위해 로그를 Amazon S3 버킷으로 보내야 합니다.<br><br><strong>이러한 요구 사항을 충족하기 위해 DevOps 엔지니어는 어떤 단계 조합을 취해야 합니까? (세 가지를 선택하세요.)</strong>`,
  en:`A company is implementing an Amazon Elastic Container Service (Amazon ECS) cluster to run its workload. The company architecture will run multiple ECS services on the cluster. The architecture includes an Application Load Balancer on the front end and uses multiple target groups to route traffic. A DevOps engineer must collect application and access logs. The DevOps engineer then needs to send the logs to an Amazon S3 bucket for near-real-time analysis. Which combination of steps must the DevOps engineer take to meet these requirements? (Choose three.)`,
  type:'multi',
  multiCount:3,
  choices:[
    {k:'A', ko:`AWS에서 Amazon CloudWatch Logs 컨테이너 인스턴스를 다운로드합니다. 이 인스턴스를 작업으로 구성합니다. 로깅 작업을 포함하도록 애플리케이션 서비스 정의를 업데이트합니다.`, en:`Download the Amazon CloudWatch Logs container instance from AWS. Configure this instance as a task. Update the application service definitions to include the logging task.`},
    {k:'B', ko:`ECS 인스턴스에 Amazon CloudWatch Logs 에이전트를 설치합니다. ECS 작업 정의의 로깅 드라이버를 awslogs로 변경합니다.`, en:`Install the Amazon CloudWatch Logs agent on the ECS instances. Change the logging driver in the ECS task definition to awslogs.`},
    {k:'C', ko:`Amazon EventBridge를 사용하여 60초마다 실행되고 Amazon CloudWatch Logs create-export-task 명령을 실행하는 AWS Lambda 함수를 예약합니다. 그런 다음 출력을 로깅 S3 버킷으로 가리킵니다.`, en:`Use Amazon EventBridge to schedule an AWS Lambda function that will run every 60 seconds and will run the Amazon CloudWatch Logs create-export-task command. Then point the output to the logging S3 bucket.`},
    {k:'D', ko:`ALB에서 액세스 로깅을 활성화합니다. 그런 다음 ALB를 로깅 S3 버킷으로 직접 가리킵니다.`, en:`Activate access logging on the ALB. Then point the ALB directly to the logging S3 bucket.`},
    {k:'E', ko:`ECS 서비스가 사용하는 대상 그룹에서 액세스 로깅을 활성화합니다. 그런 다음 로깅 S3 버킷으로 직접 로그를 보냅니다.`, en:`Activate access logging on the target groups that the ECS services use. Then send the logs directly to the logging S3 bucket.`},
    {k:'F', ko:`로깅 S3 버킷의 목적지가 있는 Amazon Kinesis Data Firehose 전달 스트림을 만듭니다. 그런 다음 Kinesis Data Firehose에 대한 Amazon CloudWatch Logs 구독 필터를 만듭니다.`, en:`Create an Amazon Kinesis Data Firehose delivery stream that has a destination of the logging S3 bucket. Then create an Amazon CloudWatch Logs subscription filter for Kinesis Data Firehose.`},
  ],
  answer:['B','D','F'],
  vote:'100% BDF',
  explain:`<p><span class="mark-ok">✅ B</span>: ECS 작업 정의에서 로깅 드라이버를 awslogs로 설정하면 컨테이너 로그가 CloudWatch Logs로 전송됩니다.</p><p style="margin-top:8px;"><span class="mark-ok">✅ D</span>: ALB 액세스 로그는 ALB에서 직접 S3 버킷으로 전송됩니다.</p><p style="margin-top:8px;"><span class="mark-ok">✅ F</span>: CloudWatch Logs → Kinesis Data Firehose → S3 경로는 거의 실시간 로그 전달을 제공합니다.</p>`,
  wrong:`<p><span class="mark-no">❌ E</span> — ALB 액세스 로그는 대상 그룹이 아닌 ALB 수준에서 설정합니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ C</span> — create-export-task는 비동기 배치 내보내기이며 거의 실시간이 아닙니다.</p>`,
  disc:[{ans:'BDF (100%)',txt:'B: 앱 로그 → CW, D: 액세스 로그 → S3 (ALB 직접), F: CW → Kinesis Firehose → S3 (거의 실시간).'}]
},
{
  n:33,
  ko:`전자 건강 기록을 사용하는 한 회사가 Amazon Linux 운영 체제를 사용하여 Amazon EC2 인스턴스 플릿을 실행하고 있습니다. 환자 개인 정보 보호 요구 사항의 일환으로 회사는 EC2 인스턴스에서 실행되는 운영 체제 및 애플리케이션에 대한 패치에 대한 지속적인 준수를 보장해야 합니다. 기본 및 사용자 지정 리포지토리를 사용하여 운영 체제 및 애플리케이션 패치의 배포를 자동화할 수 있는 방법은 무엇입니까?`,
  en:`A company that uses electronic health records is running a fleet of Amazon EC2 instances with an Amazon Linux operating system. As part of patient privacy requirements, the company must ensure continuous compliance for patches for operating system and applications running on the EC2 instances. How can the deployments of the operating system and application patches be automated using a default and custom repository?`,
  type:'single',
  choices:[
    {k:'A', ko:`AWS Systems Manager를 사용하여 사용자 정의 리포지토리를 포함한 새 패치 베이스라인을 만듭니다. run 명령을 사용하여 AWS-RunPatchBaseline 문서를 실행하여 패치를 확인하고 설치합니다.`, en:`Use AWS Systems Manager to create a new patch baseline including the custom repository. Run the AWS-RunPatchBaseline document using the run command to verify and install patches.`},
    {k:'B', ko:`AWS Direct Connect를 사용하여 기업 리포지토리를 통합하고 Amazon CloudWatch 예약 이벤트를 사용하여 패치를 배포한 다음 CloudWatch 대시보드를 사용하여 보고서를 만듭니다.`, en:`Use AWS Direct Connect to integrate the corporate repository and deploy the patches using Amazon CloudWatch scheduled events, then use the CloudWatch dashboard to create reports.`},
    {k:'C', ko:`yum-config-manager를 사용하여 /etc/yum.repos.d에 사용자 정의 저장소를 추가하고 yum-config-manager-enable을 실행하여 저장소를 활성화합니다.`, en:`Use yum-config-manager to add the custom repository under /etc/yum.repos.d and run yum-config-manager-enable to activate the repository.`},
    {k:'D', ko:`AWS Systems Manager를 사용하여 기업 리포지토리를 포함한 새로운 패치 베이스라인을 만듭니다. run 명령을 사용하여 AWS-AmazonLinuxDefaultPatchBaseline 문서를 실행하여 패치를 확인하고 설치합니다.`, en:`Use AWS Systems Manager to create a new patch baseline including the corporate repository. Run the AWS-AmazonLinuxDefaultPatchBaseline document using the run command to verify and install patches.`},
  ],
  answer:['A'],
  vote:'100% A',
  explain:`<p><span class="mark-ok">✅ A — SSM Patch Manager + AWS-RunPatchBaseline</span></p><p>AWS Systems Manager Patch Manager에서 사용자 지정 리포지토리를 포함하는 패치 베이스라인을 생성할 수 있습니다. <code>AWS-RunPatchBaseline</code> SSM 문서는 인스턴스에 등록된 패치 베이스라인(기본 + 사용자 지정 포함)을 기반으로 패치를 스캔하고 설치합니다.</p>`,
  wrong:`<p><span class="mark-no">❌ D</span> — <code>AWS-AmazonLinuxDefaultPatchBaseline</code>은 미리 정의된 기본 베이스라인을 적용하는 문서로 수정이 불가능하며, 사용자 지정 리포지토리를 포함할 수 없습니다.</p>`,
  disc:[{ans:'A (100%)',txt:'핵심 차이: AWS-RunPatchBaseline(A)은 사용자 정의 베이스라인 적용. AWS-AmazonLinuxDefaultPatchBaseline(D)은 수정 불가한 기본 베이스라인만 사용.'}]
},
{
  n:34,
  ko:`한 회사에서 AWS CodePipeline을 사용하여 릴리스 파이프라인을 자동화하고 있습니다. AWS CodeDeploy는 파이프라인에서 블루/그린 배포 모델을 사용하여 Amazon Elastic Container Service(Amazon ECS)에 애플리케이션을 배포하는 데 사용되고 있습니다. 이 회사는 트래픽을 전환하기 전에 그린 버전의 애플리케이션을 테스트하는 스크립트를 구현하려고 합니다. 이러한 스크립트는 5분 이내에 완료됩니다. 이러한 테스트 중에 오류가 발견되면 애플리케이션을 롤백해야 합니다.<br><br><strong>이러한 요구 사항을 충족하는 전략은 무엇입니까?</strong>`,
  en:`A company is using AWS CodePipeline to automate its release pipeline. AWS CodeDeploy is being used in the pipeline to deploy an application to Amazon Elastic Container Service (Amazon ECS) using the blue/green deployment model. The company wants to implement scripts to test the green version of the application before shifting traffic. These scripts will complete in 5 minutes or less. If errors are discovered during these tests, the application must be rolled back. Which strategy will meet these requirements?`,
  type:'single',
  choices:[
    {k:'A', ko:`소스와 배포 단계 사이에 CodePipeline 파이프라인에 단계를 추가합니다. AWS CodeBuild를 사용하여 런타임 환경을 만들고 buildspec 파일에서 명령을 빌드하여 테스트 스크립트를 호출합니다. 오류가 발견되면 aws deploy stop-deployment 명령을 사용하여 배포를 중지합니다.`, en:`Add a stage to the CodePipeline pipeline between the source and deploy stages. Use AWS CodeBuild to create a runtime environment and build commands in the buildspec file to invoke test scripts. If errors are found, use the aws deploy stop-deployment command to stop the deployment.`},
    {k:'B', ko:`소스와 배포 단계 사이에 CodePipeline 파이프라인에 단계를 추가합니다. 이 단계를 사용하여 테스트 스크립트를 실행하는 AWS Lambda 함수를 호출합니다. 오류가 발견되면 aws deploy stop-deployment 명령을 사용하여 배포를 중지합니다.`, en:`Add a stage to the CodePipeline pipeline between the source and deploy stages. Use this stage to invoke an AWS Lambda function that will run the test scripts. If errors are found, use the aws deploy stop-deployment command to stop the deployment.`},
    {k:'C', ko:`CodeDeploy AppSpec 파일에 hooks 섹션을 추가합니다. AfterAllowTestTraffic 라이프사이클 이벤트를 사용하여 AWS Lambda 함수를 호출하여 테스트 스크립트를 실행합니다. 오류가 발견되면 오류와 함께 Lambda 함수를 종료하여 롤백을 시작합니다.`, en:`Add a hooks section to the CodeDeploy AppSpec file. Use the AfterAllowTestTraffic lifecycle event to invoke an AWS Lambda function to run the test scripts. If errors are found, exit the Lambda function with an error to initiate rollback.`},
    {k:'D', ko:`CodeDeploy AppSpec 파일에 hooks 섹션을 추가합니다. AfterAllowTraffic 라이프사이클 이벤트를 사용하여 테스트 스크립트를 호출합니다. 오류가 발견되면 aws deploy stop-deployment CLI 명령을 사용하여 배포를 중지합니다.`, en:`Add a hooks section to the CodeDeploy AppSpec file. Use the AfterAllowTraffic lifecycle event to invoke the test scripts. If errors are found, use the aws deploy stop-deployment CLI command to stop the deployment.`},
  ],
  answer:['C'],
  vote:'100% C',
  explain:`<p><span class="mark-ok">✅ C — AfterAllowTestTraffic + Lambda 오류 종료 → 자동 롤백</span></p><p><code>AfterAllowTestTraffic</code>은 테스트 트래픽이 그린 환경으로 전환된 후, 전체 프로덕션 트래픽 전환 전에 실행됩니다. Lambda 함수에서 오류와 함께 종료(exit with error)하면 CodeDeploy가 자동 롤백을 시작합니다.</p>`,
  wrong:`<p><span class="mark-no">❌ A, B</span> — 소스와 배포 단계 사이의 테스트는 배포 전 테스트입니다. 그린 환경에 실제 배포된 후의 테스트가 아닙니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ D</span> — AfterAllowTraffic은 전체 트래픽이 전환된 후이며, stop-deployment는 롤백이 아닙니다.</p>`,
  disc:[{ans:'C (100%)',txt:'ECS Blue/Green 라이프사이클: AfterAllowTestTraffic에서 Lambda 오류 반환 시 롤백 트리거됨.'}]
},
{
  n:35,
  ko:`한 회사가 여러 리소스에서 사용하는 Amazon S3 버킷 앞에서 파일 게이트웨이 모드로 AWS Storage Gateway를 사용합니다. 업무가 시작되는 아침에 사용자는 전날 저녁에 타사에서 처리한 객체를 볼 수 없습니다. DevOps 엔지니어가 S3 버킷을 직접 보면 데이터는 있지만 Storage Gateway에는 없습니다.<br><br><strong>어떤 솔루션이 모든 업데이트된 타사 파일을 아침에 사용할 수 있도록 보장합니까?</strong>`,
  en:`A company uses AWS Storage Gateway in file gateway mode in front of an Amazon S3 bucket that is used by multiple resources. In the morning when business begins, users do not see the objects processed by a third party the previous evening. When a DevOps engineer looks directly at the S3 bucket, the data is there, but it is missing in Storage Gateway. Which solution ensures that all the updated third-party files are available in the morning?`,
  type:'single',
  choices:[
    {k:'A', ko:`Storage Gateway에 대한 RefreshCache 명령을 실행하기 위해 AWS Lambda 함수를 호출하도록 매일 밤 Amazon EventBridge 이벤트를 구성합니다.`, en:`Configure a nightly Amazon EventBridge event to invoke an AWS Lambda function to run the RefreshCache command for Storage Gateway.`},
    {k:'B', ko:`AWS Transfer for SFTP를 사용하여 제3자에게 S3 버킷에 데이터를 넣도록 지시합니다.`, en:`Instruct the third party to put data into the S3 bucket using AWS Transfer for SFTP.`},
    {k:'C', ko:`볼륨 게이트웨이 모드에서 실행되도록 Storage Gateway를 수정합니다.`, en:`Modify Storage Gateway to run in volume gateway mode.`},
    {k:'D', ko:`S3 동일 지역 복제를 사용하여 S3 버킷에서 직접 변경한 모든 내용을 Storage Gateway에 복제합니다.`, en:`Use S3 Same-Region Replication to replicate any changes made directly in the S3 bucket to Storage Gateway.`},
  ],
  answer:['A'],
  vote:'97% A',
  explain:`<p><span class="mark-ok">✅ A — EventBridge 야간 스케줄 + Lambda RefreshCache</span></p><p>Storage Gateway 파일 게이트웨이는 S3 버킷에 직접 업로드된 파일은 캐시를 자동 업데이트하지 않습니다. EventBridge 야간 스케줄로 Lambda를 실행하여 RefreshCache API를 호출하면 S3의 최신 상태가 게이트웨이에 반영됩니다.</p>`,
  wrong:`<p><span class="mark-no">❌ B</span> — AWS Transfer for SFTP를 사용해도 S3에 PutObject하는 것은 동일하며, Storage Gateway 캐시는 자동 갱신되지 않습니다.</p>`,
  disc:[{ans:'A (97%)',txt:'"Storage Gateway doesn\'t automatically update the cache when you upload a file directly to Amazon S3. You must perform a RefreshCache operation." — AWS 공식 문서'}]
},
{
  n:36,
  ko:`DevOps 엔지니어는 S3 크로스 리전 복제 기능을 사용하여 개인 버킷 정책이 있는 S3 버킷에 저장된 민감한 Amazon S3 객체를 백업해야 합니다. 객체를 다른 AWS 리전 및 계정의 대상 버킷에 복사해야 합니다.<br><br><strong>이 복제를 활성화하려면 어떤 작업 조합을 수행해야 합니까? (세 가지를 선택하세요.)</strong>`,
  en:`A DevOps engineer needs to back up sensitive Amazon S3 objects that are stored within an S3 bucket with a private bucket policy using S3 cross-Region replication functionality. The objects need to be copied to a target bucket in a different AWS Region and account. Which combination of actions should be performed to enable this replication? (Choose three.)`,
  type:'multi',
  multiCount:3,
  choices:[
    {k:'A', ko:`소스 계정에서 복제 IAM 역할 생성`, en:`Create a replication IAM role in the source account`},
    {k:'B', ko:`대상 계정에서 복제 IAM 역할을 생성합니다.`, en:`Create a replication IAM role in the target account.`},
    {k:'C', ko:`소스 버킷 정책에 명령문을 추가하여 복제 IAM 역할이 개체를 복제할 수 있도록 허용합니다.`, en:`Add statements to the source bucket policy allowing the replication IAM role to replicate objects.`},
    {k:'D', ko:`복제 IAM 역할이 개체를 복제할 수 있도록 대상 버킷 정책에 명령문을 추가합니다.`, en:`Add statements to the target bucket policy allowing the replication IAM role to replicate objects.`},
    {k:'E', ko:`복제를 활성화하려면 소스 버킷에서 복제 규칙을 만듭니다.`, en:`Create a replication rule in the source bucket to enable the replication.`},
    {k:'F', ko:`대상 버킷에서 복제 규칙을 생성하여 복제를 활성화합니다.`, en:`Create a replication rule in the target bucket to enable the replication.`},
  ],
  answer:['A','D','E'],
  vote:'100% ADE',
  explain:`<p><span class="mark-ok">✅ A</span>: S3가 객체를 복제하는 데 사용할 IAM 역할을 소스 계정에 생성합니다.</p><p style="margin-top:8px;"><span class="mark-ok">✅ D</span>: 교차 계정 복제 시 대상 계정의 버킷 정책에 소스 계정의 복제 역할이 객체를 쓸 수 있도록 허용하는 구문을 추가합니다.</p><p style="margin-top:8px;"><span class="mark-ok">✅ E</span>: 소스 버킷에 복제 규칙을 생성하여 복제를 활성화합니다.</p>`,
  wrong:`<p><span class="mark-no">❌ B</span> — 복제 IAM 역할은 소스 계정에 생성합니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ F</span> — 복제 규칙은 소스 버킷에 설정합니다.</p>`,
  disc:[{ans:'ADE (100%)',txt:'교차 계정 S3 복제 단계: 1) 소스 계정에 IAM 역할 생성 2) 대상 버킷 정책에 허용 구문 추가 3) 소스 버킷에 복제 규칙 생성.'}]
},
{
  n:37,
  ko:`회사에 AWS Organizations의 조직에 속하는 여러 멤버 계정이 있습니다. 보안팀은 모든 Amazon EC2 보안 그룹과 해당 인바운드 및 아웃바운드 규칙을 검토해야 합니다. 보안팀은 조직의 관리 계정에서 AWS Lambda 함수를 사용하여 멤버 계정에서 이 정보를 프로그래밍 방식으로 검색하려고 합니다.<br><br><strong>이러한 요구 사항을 충족하는 액세스 변경 조합은 무엇입니까? (세 가지를 선택하십시오.)</strong>`,
  en:`A company has multiple member accounts that are part of an organization in AWS Organizations. The security team needs to review every Amazon EC2 security group and their inbound and outbound rules. The security team wants to programmatically retrieve this information from the member accounts using an AWS Lambda function in the management account of the organization. Which combination of access changes will meet these requirements? (Choose three.)`,
  type:'multi',
  multiCount:3,
  choices:[
    {k:'A', ko:`멤버 계정의 사용자가 관리 계정 IAM 역할을 맡을 수 있도록 하는 신뢰 관계를 만듭니다.`, en:`Create a trust relationship that allows users in the member accounts to assume the management account IAM role.`},
    {k:'B', ko:`관리 계정의 사용자가 멤버 계정의 IAM 역할을 맡을 수 있도록 하는 신뢰 관계를 만듭니다.`, en:`Create a trust relationship that allows users in the management account to assume the IAM roles of the member accounts.`},
    {k:'C', ko:`AmazonEC2ReadOnlyAccess 관리 정책에 액세스할 수 있는 각 멤버 계정에 IAM 역할을 생성합니다.`, en:`Create an IAM role in each member account that has access to the AmazonEC2ReadOnlyAccess managed policy.`},
    {k:'D', ko:`각 구성원 계정에서 IAM 역할을 생성하여 관리 계정 IAM 역할의 ARN에 대해 sts:AssumeRole 작업을 허용합니다.`, en:`Create an IAM role in each member account to allow the sts:AssumeRole action against the management account IAM role's ARN.`},
    {k:'E', ko:`멤버 계정 IAM 역할의 ARN에 대해 sts:AssumeRole 작업을 허용하는 관리 계정에서 IAM 역할을 생성합니다.`, en:`Create an IAM role in the management account that allows the sts:AssumeRole action against the member account IAM role's ARN.`},
    {k:'F', ko:`AmazonEC2ReadOnlyAccess 관리 정책에 액세스할 수 있는 관리 계정에서 IAM 역할을 생성합니다.`, en:`Create an IAM role in the management account that has access to the AmazonEC2ReadOnlyAccess managed policy.`},
  ],
  answer:['B','C','E'],
  vote:'80% BCE',
  explain:`<p><span class="mark-ok">✅ B</span>: 관리 계정의 Lambda 역할이 멤버 계정 역할을 Assume할 수 있도록 신뢰 관계를 설정합니다.</p><p style="margin-top:8px;"><span class="mark-ok">✅ C</span>: 각 멤버 계정에 EC2 읽기 전용 권한을 가진 IAM 역할을 생성합니다.</p><p style="margin-top:8px;"><span class="mark-ok">✅ E</span>: 관리 계정에 멤버 계정 IAM 역할을 Assume할 수 있는 권한을 가진 IAM 역할을 생성합니다.</p>`,
  wrong:`<p><span class="mark-no">❌ A</span> — 방향이 반대입니다. 관리 계정이 멤버 계정 역할을 맡아야 합니다.</p>`,
  disc:[{ans:'BCE (80%)',txt:'교차 계정 접근 패턴: 관리 계정(Lambda) → AssumeRole → 멤버 계정 역할(EC2ReadOnly). B=신뢰관계, C=멤버역할(권한), E=관리역할(AssumeRole 권한).'}]
},
{
  n:38,
  ko:`우주 탐사 회사가 여러 위성에서 원격 측정 데이터를 수신합니다. 소량의 데이터 패킷은 Amazon API Gateway를 통해 수신되어 Amazon Simple Queue Service(Amazon SQS) 표준 대기열에 직접 배치됩니다. 사용자 지정 애플리케이션이 대기열에 구독되어 데이터를 표준 형식으로 변환합니다. 위성에서 생성되는 데이터의 불일치로 인해 애플리케이션이 가끔 데이터를 변환할 수 없습니다. 이러한 경우 메시지는 SQS 대기열에 남아 있습니다. DevOps 엔지니어는 실패한 메시지를 보관하고 과학자가 검토하고 향후 처리할 수 있도록 제공하는 솔루션을 개발해야 합니다.<br><br><strong>이러한 요구 사항을 충족하는 솔루션은 무엇입니까?</strong>`,
  en:`A space exploration company receives telemetry data from multiple satellites. Small packets of data are received through Amazon API Gateway and are placed directly into an Amazon Simple Queue Service (Amazon SQS) standard queue. A custom application is subscribed to the queue and transforms the data into a standard format. Because of inconsistencies in the data that the satellites produce, the application is occasionally unable to transform the data. In these cases, the messages remain in the SQS queue. A DevOps engineer must develop a solution that retains the failed messages and makes them available to scientists for review and future processing. Which solution will meet these requirements?`,
  type:'single',
  choices:[
    {k:'A', ko:`AWS Lambda를 구성하여 SQS 대기열을 폴링하고 Lambda 함수를 호출하여 대기열 메시지가 유효한지 확인합니다. 검증이 실패하면 유효하지 않은 데이터의 사본을 Amazon S3 버킷으로 보내 과학자가 데이터를 검토하고 수정할 수 있도록 합니다. 데이터가 수정되면 수정된 데이터로 재생 Lambda 함수를 사용하여 SQS 대기열의 메시지를 수정합니다.`, en:`Configure AWS Lambda to poll the SQS queue and invoke a Lambda function to check whether the queue messages are valid. If validation fails, send a copy of the data that is not valid to an Amazon S3 bucket so that the scientists can review and correct the data. When the data is corrected, amend the message in the SQS queue by using a replay Lambda function with the corrected data.`},
    {k:'B', ko:`SQS 표준 대기열을 SQS FIFO 대기열로 변환합니다. Amazon EventBridge 일정을 사용하여 10분마다 SQS 대기열을 폴링하도록 AWS Lambda를 구성합니다. Lambda 함수를 호출하여 5분보다 오래된 SentTimestamp 값이 있는 메시지를 식별하고, 데이터를 애플리케이션의 출력 위치와 동일한 위치로 푸시하고, 대기열에서 메시지를 제거합니다.`, en:`Convert the SQS standard queue to an SQS FIFO queue. Configure AWS Lambda to poll the SQS queue every 10 minutes by using an Amazon EventBridge schedule. Invoke the Lambda function to identify any messages with a SentTimestamp value that is older than 5 minutes, push the data to the same location as the application's output location, and remove the messages from the queue.`},
    {k:'C', ko:`SQS 배달 못한 편지 대기열을 만듭니다. 최대 수신 설정을 1로 설정하고 배달 못한 편지 대기열 ARN을 새로 만든 대기열의 ARN으로 설정하는 재구동 정책을 포함하여 기존 대기열을 수정합니다. 과학자들에게 배달 못한 편지 대기열을 사용하여 유효하지 않은 데이터를 검토하도록 지시합니다. 나중에 이 데이터를 다시 처리합니다.`, en:`Create an SQS dead-letter queue. Modify the existing queue by including a redrive policy that sets the Maximum Receives setting to 1 and sets the dead-letter queue ARN to the ARN of the newly created queue. Instruct the scientists to use the dead-letter queue to review the data that is not valid. Reprocess this data at a later time.`},
    {k:'D', ko:`API Gateway를 구성하여 각 위성에 대해 명명된 다른 SQS 가상 대기열에 메시지를 보냅니다. 변환할 수 없는 모든 데이터에 대해 새 가상 대기열을 사용하도록 애플리케이션을 업데이트하고 메시지를 새 가상 대기열로 보냅니다. 과학자들에게 가상 대기열을 사용하여 유효하지 않은 데이터를 검토하도록 지시합니다. 나중에 이 데이터를 다시 처리합니다.`, en:`Configure API Gateway to send messages to different SQS virtual queues that are named for each of the satellites. Update the application to use a new virtual queue for any data that it cannot transform, and send the message to the new virtual queue. Instruct the scientists to use the virtual queue to review the data that is not valid. Reprocess this data at a later time.`},
  ],
  answer:['C'],
  vote:'100% C',
  explain:`<p><span class="mark-ok">✅ C — SQS Dead-Letter Queue (DLQ)</span></p><p>SQS DLQ는 처리에 실패한 메시지를 자동으로 격리하는 AWS 표준 패턴입니다. Maximum Receives=1로 설정하면 애플리케이션이 한 번 변환에 실패한 메시지를 즉시 DLQ로 이동합니다. 과학자들은 DLQ에서 직접 메시지를 검토하고 나중에 재처리할 수 있습니다.</p>`,
  wrong:`<p><span class="mark-no">❌ A</span> — Lambda로 별도 검증 레이어를 추가하는 것은 복잡하며 SQS의 DLQ 메커니즘을 활용하는 것이 더 효율적입니다.</p>`,
  disc:[{ans:'C (100%)',txt:'DLQ 사용 사례: 처리 실패 메시지 격리, 분석, 재처리. Maximum Receives=1로 설정하면 한 번 실패 시 즉시 DLQ로 이동합니다.'}]
},
{
  n:39,
  ko:`한 회사가 인프라 배포에 AWS CloudFormation을 사용하고자 합니다. 이 회사는 엄격한 태그 지정 및 리소스 요구 사항을 가지고 있으며 배포를 두 개의 지역으로 제한하고자 합니다. 개발자는 동일한 애플리케이션의 여러 버전을 배포해야 합니다.<br><br><strong>어떤 솔루션이 회사 정책에 따라 리소스가 배포되도록 보장합니까?</strong>`,
  en:`A company wants to use AWS CloudFormation for infrastructure deployment. The company has strict tagging and resource requirements and wants to limit the deployment to two Regions. Developers will need to deploy multiple versions of the same application. Which solution ensures resources are deployed in accordance with company policy?`,
  type:'single',
  choices:[
    {k:'A', ko:`AWS Trusted Advisor 검사를 생성하여 승인되지 않은 CloudFormation StackSets를 찾아 해결합니다.`, en:`Create AWS Trusted Advisor checks to find and remediate unapproved CloudFormation StackSets.`},
    {k:'B', ko:`승인되지 않은 CloudFormation StackSets를 찾아 해결하기 위해 Cloud Formation 드리프트 감지 작업을 생성합니다.`, en:`Create a Cloud Formation drift detection operation to find and remediate unapproved CloudFormation StackSets.`},
    {k:'C', ko:`승인된 CloudFormation 템플릿을 사용하여 CloudFormation StackSets를 만듭니다.`, en:`Create CloudFormation StackSets with approved CloudFormation templates.`},
    {k:'D', ko:`승인된 CloudFormation 템플릿을 사용하여 AWS 서비스 카탈로그 제품을 만듭니다.`, en:`Create AWS Service Catalog products with approved CloudFormation templates.`},
  ],
  answer:['D'],
  vote:'78% D (22% C)',
  explain:`<p><span class="mark-ok">✅ D — AWS Service Catalog</span></p><p>AWS Service Catalog를 사용하면 승인된 CloudFormation 템플릿으로 제품을 만들고 배포 가능한 리전, 허용되는 인스턴스 유형, 필수 태그 등 제약을 강제할 수 있습니다. 개발자는 카탈로그에서 버전을 선택하여 배포하므로 회사 정책을 자동으로 준수합니다.</p>`,
  wrong:`<p><span class="mark-no">❌ C</span> — CloudFormation StackSets는 여러 계정/리전에 배포할 수 있지만, 개발자가 직접 사용하면 승인되지 않은 템플릿이나 다른 리전 선택을 막을 수 없습니다.</p>`,
  disc:[{ans:'D (78%) vs C (22%)',txt:'"Service Catalog를 사용하면 조직 내 최종 사용자는 조직이 설정한 제약에 따라 승인된 IT 서비스만 빠르게 배포할 수 있습니다." — AWS Service Catalog 문서.'}]
},
{
  n:40,
  ko:`어떤 회사에서는 내부적으로 마주하는 웹 애플리케이션이 고가용성을 요구합니다. 이 아키텍처는 Amazon EC2 웹 서버 인스턴스 하나와 업데이트 및 공개 데이터 액세스를 위한 아웃바운드 인터넷 액세스를 제공하는 NAT 인스턴스 하나로 구성됩니다.<br><br><strong>이 회사는 고가용성을 달성하기 위해 어떤 아키텍처 조정 조합을 구현해야 합니까? (두 가지를 선택하세요.)</strong>`,
  en:`A company requires that its internally facing web application be highly available. The architecture is made up of one Amazon EC2 web server instance and one NAT instance that provides outbound internet access for updates and accessing public data. Which combination of architecture adjustments should the company implement to achieve high availability? (Choose two.)`,
  type:'multi',
  multiCount:2,
  choices:[
    {k:'A', ko:`여러 가용성 영역에 걸쳐 있는 EC2 자동 확장 그룹에 NAT 인스턴스를 추가합니다. 경로 테이블을 업데이트합니다.`, en:`Add the NAT instance to an EC2 Auto Scaling group that spans multiple Availability Zones. Update the route tables.`},
    {k:'B', ko:`여러 가용성 영역에 걸쳐 추가 EC2 인스턴스를 만듭니다. 애플리케이션 로드 밸런서를 추가하여 로드를 이들 간에 분할합니다.`, en:`Create additional EC2 instances spanning multiple Availability Zones. Add an Application Load Balancer to split the load between them.`},
    {k:'C', ko:`EC2 인스턴스 앞에 애플리케이션 로드 밸런서를 구성합니다. 호스트 장애 시 EC2 인스턴스를 복구하도록 Amazon CloudWatch 알람을 구성합니다.`, en:`Configure an Application Load Balancer in front of the EC2 instance. Configure Amazon CloudWatch alarms to recover the EC2 instance upon host failure.`},
    {k:'D', ko:`각 가용성 영역에서 NAT 인스턴스를 NAT 게이트웨이로 교체합니다. 경로 테이블을 업데이트합니다.`, en:`Replace the NAT instance with a NAT gateway in each Availability Zone. Update the route tables.`},
    {k:'E', ko:`NAT 인스턴스를 여러 가용성 영역에 걸쳐 있는 NAT 게이트웨이로 교체합니다. 경로 테이블을 업데이트합니다.`, en:`Replace the NAT instance with a NAT gateway that spans multiple Availability Zones. Update the route tables.`},
  ],
  answer:['B','D'],
  vote:'82% BD',
  explain:`<p><span class="mark-ok">✅ B</span>: 여러 AZ에 EC2 인스턴스를 배포하고 ALB로 트래픽을 분산하면 단일 인스턴스 장애에도 서비스가 지속됩니다.</p><p style="margin-top:8px;"><span class="mark-ok">✅ D</span>: NAT 게이트웨이는 단일 AZ 내에서만 동작합니다. 고가용성을 위해 각 AZ에 하나의 NAT 게이트웨이를 배포합니다.</p>`,
  wrong:`<p><span class="mark-no">❌ E</span> — NAT 게이트웨이는 단일 서브넷(단일 AZ)에 배포됩니다. 여러 AZ에 걸쳐 있는 NAT 게이트웨이는 존재하지 않습니다.</p>`,
  disc:[{ans:'BD (82%)',txt:'"여러 AZ의 리소스가 하나의 NAT 게이트웨이를 공유하면, 해당 AZ가 다운될 때 다른 AZ의 리소스가 인터넷 액세스를 잃습니다. 각 AZ에 NAT 게이트웨이를 생성하세요." — AWS VPC 문서'}]
}
];
