window.QS_SET33 = [
{
  n: 321,
  en: `A company has an organization in AWS Organizations with many OUs that contain many AWS accounts. The organization has a dedicated delegated administrator AWS account.<br>The company needs the accounts in one OU to have server-side encryption enforced for all Amazon Elastic Block Store (Amazon EBS) volumes and Amazon Simple Queue Service (Amazon SQS) queues that are created or updated on an AWS CloudFormation stack.<br>Which solution will enforce this policy before a CloudFormation stack operation in the accounts of this OU?`,
  ko: `한 회사가 많은 AWS 계정이 포함된 여러 OU를 가진 AWS Organizations 조직을 보유하고 있습니다. 조직에는 전담 위임 관리자 AWS 계정이 있습니다.<br>회사는 한 OU의 계정에서 AWS CloudFormation 스택에서 생성되거나 업데이트되는 모든 Amazon EBS 볼륨과 Amazon SQS 대기열에 대해 서버 측 암호화가 적용되어야 합니다.<br>이 OU의 계정에서 CloudFormation 스택 작업 전에 이 정책을 적용하는 솔루션은 무엇입니까?`,
  type: 'single',
  choices: [
    { k:'A', en:`Activate trusted access to CloudFormation StackSets. Create a CloudFormation Hook that enforces server-side encryption on EBS volumes and SQS queues. Deploy the Hook across the accounts in the OU by using StackSets.`, ko:`CloudFormation StackSets에 대한 신뢰할 수 있는 액세스를 활성화합니다. EBS 볼륨과 SQS 대기열에 서버 측 암호화를 적용하는 CloudFormation Hook을 생성합니다. StackSets를 사용하여 OU의 계정 전체에 Hook을 배포합니다.` },
    { k:'B', en:`Set up AWS Config in all the accounts in the OU. Use AWS Systems Manager to deploy AWS Config rules that enforce server-side encryption for EBS volumes and SQS queues across the accounts in the OU.`, ko:`OU의 모든 계정에서 AWS Config를 설정합니다. AWS Systems Manager를 사용하여 OU의 계정 전체에서 EBS 볼륨과 SQS 대기열에 대한 서버 측 암호화를 적용하는 AWS Config 규칙을 배포합니다.` },
    { k:'C', en:`Write an SCP to deny the creation of EBS volumes and SQS queues unless the EBS volumes and SQS queues have server-side encryption. Attach the SCP to the OU.`, ko:`EBS 볼륨과 SQS 큐에 서버 측 암호화가 없는 한 EBS 볼륨과 SQS 큐의 생성을 거부하는 SCP를 작성합니다. SCP를 OU에 연결합니다.` },
    { k:'D', en:`Create an AWS Lambda function in the delegated administrator account that checks whether server-side encryption is enforced for EBS volumes and SQS queues. Create an IAM role to provide the Lambda function access to the accounts in the OU.`, ko:`위임된 관리자 계정에서 EBS 볼륨 및 SQS 대기열에 서버 측 암호화가 적용되는지 확인하는 AWS Lambda 함수를 생성합니다. Lambda 함수에 OU의 계정에 대한 액세스 권한을 제공하는 IAM 역할을 생성합니다.` },
  ],
  answer: ['A'],
  vote: '94% A',
  explain: `<p><span class="mark-ok">✅ A — CloudFormation Hooks + StackSets 배포</span></p><p>CloudFormation Hooks는 스택 작업 전에 리소스 구성을 검증하고 정책을 적용할 수 있습니다. EBS 볼륨과 SQS 대기열에 서버 측 암호화가 활성화되어 있는지 확인하는 Hook을 생성하고, StackSets로 OU 전체에 배포하면 스택 작업 전에 정책이 적용됩니다. 키워드: "CloudFormation 스택 작업 전에 적용"</p>`,
  wrong: `<p><span class="mark-no">❌ B</span> — AWS Config는 구성 후 감지 및 수정이며 스택 작업 전 예방적 통제가 아닙니다.</p><p><span class="mark-no">❌ C</span> — SCP는 CloudFormation을 통하지 않은 직접 API 호출에만 적용되며 CloudFormation 스택 작업 자체를 차단하지 않을 수 있습니다.</p><p><span class="mark-no">❌ D</span> — Lambda 기반 사후 검사는 스택 작업 전 정책 적용이 아닙니다.</p>`,
  disc: [{ ans:'A (94%)', txt:'CloudFormation Hooks가 스택 작업 전 암호화 정책을 적용하는 올바른 메커니즘이라는 의견이 압도적입니다.' }]
},
{
  n: 322,
  en: `A company is running an internal application in an Amazon Elastic Container Service (Amazon ECS) cluster on Amazon EC2. The ECS cluster instances can connect to the public internet. The ECS tasks that run on the cluster instances are configured to use images from both private Amazon Elastic Container Registry (Amazon ECR) repositories and a public ECR registry repository.<br>A new security policy requires the company to remove the ECS cluster's direct access to the internet. The company must remove any NAT gateways and internet gateways from the VPC that hosts the cluster. A DevOps engineer needs to ensure the ECS cluster can still download images from both the public ECR registry and the private ECR repositories. Images from the public ECR registry must remain up-to-date. New versions of the images must be available to the ECS cluster within 24 hours of publication.<br>Which combination of steps will meet these requirements with the LEAST operational overhead? (Choose three.)`,
  ko: `한 회사가 Amazon EC2의 Amazon ECS 클러스터에서 내부 애플리케이션을 실행하고 있습니다. ECS 클러스터 인스턴스는 퍼블릭 인터넷에 연결할 수 있습니다. 클러스터 인스턴스에서 실행되는 ECS 작업은 프라이빗 Amazon ECR 리포지토리와 퍼블릭 ECR 레지스트리 리포지토리의 이미지를 모두 사용하도록 구성되어 있습니다.<br>새 보안 정책에 따라 회사는 ECS 클러스터의 인터넷 직접 액세스를 제거해야 합니다. VPC에서 모든 NAT 게이트웨이와 인터넷 게이트웨이를 제거해야 합니다. ECS 클러스터가 퍼블릭 ECR 레지스트리와 프라이빗 ECR 리포지토리에서 이미지를 계속 다운로드할 수 있는지 확인해야 합니다. 퍼블릭 ECR 레지스트리의 이미지는 게시 후 24시간 이내에 ECS 클러스터에서 사용할 수 있어야 합니다.<br>운영 오버헤드를 최소화하면서 이 요구 사항을 충족하는 단계 조합은 무엇입니까? (3개 선택)`,
  type: 'multi', multiCount: 3,
  choices: [
    { k:'A', en:`Create an AWS CodeBuild project and a new private ECR repository for each image that is downloaded from the public ECR registry. Configure each project to pull the image from the public ECR repository and push the image to the new private ECR repository. Create an Amazon EventBridge rule that invokes the CodeBuild project once every 24 hours. Update each task definition in the ECS cluster to refer to the new private ECR repository.`, ko:`퍼블릭 ECR 레지스트리에서 다운로드한 각 이미지에 대해 AWS CodeBuild 프로젝트와 새 프라이빗 ECR 리포지토리를 생성합니다. 각 프로젝트를 구성하여 퍼블릭 ECR 리포지토리에서 이미지를 가져와 새 프라이빗 ECR 리포지토리에 푸시합니다. 24시간마다 CodeBuild 프로젝트를 호출하는 Amazon EventBridge 규칙을 생성합니다. 각 작업 정의를 업데이트하여 새 프라이빗 ECR 리포지토리를 참조합니다.` },
    { k:'B', en:`Create a new Amazon ECR pull through cache rule for each image that is downloaded from the public ECR registry. Create an AWS Lambda function that invokes each pull through cache rule. Create an Amazon EventBridge rule that invokes the Lambda function once every 24 hours. Update each task definition in the ECS cluster to refer to the image from the pull through cache.`, ko:`퍼블릭 ECR 레지스트리에서 다운로드한 각 이미지에 대해 새로운 Amazon ECR 풀스루 캐시 규칙을 생성합니다. 각 풀스루 캐시 규칙을 호출하는 AWS Lambda 함수를 생성합니다. 24시간마다 Lambda 함수를 호출하는 Amazon EventBridge 규칙을 생성합니다. 풀스루 캐시의 이미지를 참조하도록 각 작업 정의를 업데이트합니다.` },
    { k:'C', en:`Create a new Amazon ECR pull through cache rule for the public ECR registry. Update each task definition in the ECS cluster to refer to the image from the pull through cache. Ensure each public image has been downloaded through the pull through cache at least once before removing internet access from the VPC.`, ko:`퍼블릭 ECR 레지스트리에 대한 새로운 Amazon ECR 풀스루 캐시 규칙을 생성합니다. 풀스루 캐시의 이미지를 참조하도록 각 작업 정의를 업데이트합니다. VPC에서 인터넷 액세스를 제거하기 전에 각 퍼블릭 이미지가 풀스루 캐시를 통해 최소한 한 번 다운로드되었는지 확인합니다.` },
    { k:'D', en:`Create an Amazon ECR interface VPC endpoint for the public ECR repositories that are in the VPC.`, ko:`VPC에 있는 퍼블릭 ECR 리포지토리에 대한 Amazon ECR 인터페이스 VPC 엔드포인트를 생성합니다.` },
    { k:'E', en:`Create an Amazon ECR interface VPC endpoint for the private ECR repositories that are in the VPC.`, ko:`VPC에 있는 프라이빗 ECR 리포지토리에 대한 Amazon ECR 인터페이스 VPC 엔드포인트를 생성합니다.` },
    { k:'F', en:`Create an Amazon S3 gateway endpoint in the VPC.`, ko:`VPC에 Amazon S3 게이트웨이 엔드포인트를 생성합니다.` },
  ],
  answer: ['C','E','F'],
  vote: '100% CEF',
  explain: `<p><span class="mark-ok">✅ C — ECR 풀스루 캐시 규칙</span></p><p>퍼블릭 ECR 이미지를 프라이빗 ECR에 캐시하면 인터넷 없이 이미지에 접근 가능합니다. 새 버전이 게시되면 자동으로 업데이트됩니다.</p><p><span class="mark-ok">✅ E — 프라이빗 ECR 인터페이스 VPC 엔드포인트</span></p><p>인터넷 또는 NAT 게이트웨이 없이 VPC에서 프라이빗 ECR에 접근하기 위해 필요합니다.</p><p><span class="mark-ok">✅ F — S3 게이트웨이 엔드포인트</span></p><p>ECR은 이미지 레이어를 S3에 저장합니다. ECS가 이미지를 가져올 때 S3 레이어 다운로드가 필요하므로 S3 게이트웨이 엔드포인트가 필요합니다.</p>`,
  wrong: `<p><span class="mark-no">❌ A</span> — CodeBuild를 통한 수동 동기화는 불필요한 운영 오버헤드를 추가합니다.</p><p><span class="mark-no">❌ B</span> — Lambda로 풀스루 캐시를 수동 호출하는 것은 불필요합니다. 풀스루 캐시는 이미지 요청 시 자동 업데이트됩니다.</p><p><span class="mark-no">❌ D</span> — AWS 공식 문서에 따르면 VPC 엔드포인트는 퍼블릭 ECR 리포지토리를 직접 지원하지 않습니다. 풀스루 캐시로 프라이빗 ECR에 호스팅해야 합니다.</p>`,
  disc: [{ ans:'CEF (100%)', txt:'풀스루 캐시로 퍼블릭 이미지 호스팅, 프라이빗 ECR VPC 엔드포인트, S3 게이트웨이 엔드포인트가 인터넷 없는 ECS 이미지 접근의 올바른 패턴입니다.' }]
},
{
  n: 323,
  en: `A company has a continuous integration pipeline where the company creates container images by using AWS CodeBuild. The created images are stored in Amazon Elastic Container Registry (Amazon ECR).<br>Checking for and fixing the vulnerabilities in the images takes the company too much time. The company wants to identify the image vulnerabilities quickly and notify the security team of the vulnerabilities.<br>Which combination of steps will meet these requirements with the LEAST operational overhead? (Choose two.)`,
  ko: `한 회사에 AWS CodeBuild를 사용하여 컨테이너 이미지를 생성하는 지속적인 통합 파이프라인이 있습니다. 생성된 이미지는 Amazon ECR에 저장됩니다.<br>이미지의 취약성을 확인하고 수정하는 데 너무 많은 시간이 소모됩니다. 회사는 이미지 취약성을 신속하게 식별하고 보안 팀에 취약성을 알리고 싶어합니다.<br>운영 오버헤드를 최소화하면서 이 요구 사항을 충족하는 단계 조합은 무엇입니까? (2개 선택)`,
  type: 'multi', multiCount: 2,
  choices: [
    { k:'A', en:`Activate Amazon Inspector enhanced scanning for Amazon ECR. Configure the enhanced scanning to use continuous scanning. Set up a topic in Amazon Simple Notification Service (Amazon SNS).`, ko:`Amazon ECR에 대한 Amazon Inspector 향상된 스캐닝을 활성화합니다. 지속적인 스캐닝을 사용하도록 향상된 스캐닝을 구성합니다. Amazon SNS에서 토픽을 설정합니다.` },
    { k:'B', en:`Create an Amazon EventBridge rule for Amazon Inspector findings. Set an Amazon Simple Notification Service (Amazon SNS) topic as the rule target.`, ko:`Amazon Inspector 결과에 대한 Amazon EventBridge 규칙을 생성합니다. Amazon SNS 토픽을 규칙 대상으로 설정합니다.` },
    { k:'C', en:`Activate AWS Lambda enhanced scanning for Amazon ECR. Configure the enhanced scanning to use continuous scanning. Set up a topic in Amazon Simple Email Service (Amazon SES).`, ko:`Amazon ECR에 대한 AWS Lambda 향상된 스캐닝을 활성화합니다. 지속적인 스캐닝을 사용하도록 향상된 스캐닝을 구성합니다. Amazon SES에서 토픽을 설정합니다.` },
    { k:'D', en:`Create a new AWS Lambda function. Invoke the new Lambda function when scan findings are detected.`, ko:`새 AWS Lambda 함수를 생성합니다. 스캔 결과가 감지되면 새 Lambda 함수를 호출합니다.` },
    { k:'E', en:`Activate default basic scanning for Amazon ECR for all container images. Configure the default basic scanning to use continuous scanning. Set up a topic in Amazon Simple Notification Service (Amazon SNS).`, ko:`모든 컨테이너 이미지에 대해 Amazon ECR에 대한 기본 기본 스캐닝을 활성화합니다. 기본 기본 스캐닝을 구성하여 연속 스캐닝을 사용합니다. Amazon SNS에서 토픽을 설정합니다.` },
  ],
  answer: ['A','B'],
  vote: '100% AB',
  explain: `<p><span class="mark-ok">✅ A — Amazon Inspector 향상된 스캐닝 + SNS 토픽</span></p><p>Amazon Inspector는 ECR 이미지 푸시 시 자동 스캔 및 지속적 재스캔을 지원합니다. SNS 토픽 설정으로 알림 전송 준비를 합니다.</p><p><span class="mark-ok">✅ B — Inspector 결과에 대한 EventBridge 규칙 + SNS 대상</span></p><p>Inspector 결과가 EventBridge 이벤트로 생성됩니다. EventBridge 규칙으로 SNS에 알림을 전송하면 보안 팀이 즉시 통보됩니다. 사용자 지정 로직 불필요합니다.</p>`,
  wrong: `<p><span class="mark-no">❌ C</span> — "AWS Lambda 향상된 스캐닝"은 존재하지 않습니다. Amazon Inspector를 사용해야 합니다.</p><p><span class="mark-no">❌ D</span> — Lambda 함수 추가는 불필요한 복잡성을 추가합니다. EventBridge → SNS가 더 간단합니다.</p><p><span class="mark-no">❌ E</span> — 기본 스캐닝은 향상된 스캐닝보다 기능이 제한적입니다.</p>`,
  disc: [{ ans:'AB (100%)', txt:'Inspector 향상된 스캐닝과 EventBridge → SNS 알림 조합이 가장 적은 운영 오버헤드로 취약성 탐지 및 알림을 제공합니다.' }]
},
{
  n: 324,
  en: `A DevOps administrator is configuring a repository to store a company's container images. The administrator needs to configure a lifecycle rule that automatically deletes container images that have a specific tag and that are older than 15 days.<br>Which solution will meet these requirements with the MOST operational efficiency?`,
  ko: `DevOps 관리자가 회사의 컨테이너 이미지를 저장하기 위해 리포지토리를 구성하고 있습니다. 관리자는 특정 태그가 있고 15일 이상 된 컨테이너 이미지를 자동으로 삭제하는 수명 주기 규칙을 구성해야 합니다.<br>가장 높은 운영 효율성으로 이 요구 사항을 충족하는 솔루션은 무엇입니까?`,
  type: 'single',
  choices: [
    { k:'A', en:`Create a repository in Amazon Elastic Container Registry (Amazon ECR). Add a lifecycle policy to the repository to expire images that have the matching tag after 15 days.`, ko:`Amazon ECR에서 리포지토리를 생성합니다. 일치하는 태그가 있는 이미지를 15일 후에 만료시키는 수명 주기 정책을 리포지토리에 추가합니다.` },
    { k:'B', en:`Create a repository in AWS CodeArtifact. Add a repository policy to the CodeArtifact repository to expire old assets that have the matching tag after 15 days.`, ko:`AWS CodeArtifact에서 리포지토리를 생성합니다. 일치하는 태그가 있는 오래된 자산을 15일 후에 만료시키는 리포지토리 정책을 CodeArtifact 리포지토리에 추가합니다.` },
    { k:'C', en:`Create a bucket in Amazon S3. Add a bucket lifecycle policy to expire old objects that have the matching tag after 15 days.`, ko:`Amazon S3에 버킷을 생성합니다. 일치하는 태그가 있는 오래된 객체를 15일 후에 만료시키기 위한 버킷 수명 주기 정책을 추가합니다.` },
    { k:'D', en:`Create an EC2 Image Builder container recipe. Add a build component to expire the container that has the matching tag after 15 days.`, ko:`EC2 Image Builder 컨테이너 레시피를 생성합니다. 일치하는 태그가 있는 컨테이너를 15일 후에 만료시키는 빌드 컴포넌트를 추가합니다.` },
  ],
  answer: ['A'],
  vote: '100% A',
  explain: `<p><span class="mark-ok">✅ A — Amazon ECR 수명 주기 정책</span></p><p>Amazon ECR은 컨테이너 이미지의 보존 기간을 자동으로 관리하는 수명 주기 정책을 지원합니다. 특정 태그를 기준으로 이미지를 매칭하고 15일이 지난 이미지를 자동으로 삭제할 수 있습니다. 컨테이너 이미지 수명 주기 관리를 위해 특별히 설계된 솔루션입니다.</p>`,
  wrong: `<p><span class="mark-no">❌ B</span> — CodeArtifact는 패키지 저장소이며 컨테이너 이미지 저장에 적합하지 않습니다.</p><p><span class="mark-no">❌ C</span> — S3는 컨테이너 이미지를 위한 전용 서비스가 아닙니다.</p><p><span class="mark-no">❌ D</span> — EC2 Image Builder는 이미지 빌드 도구이며 수명 주기 관리 기능이 없습니다.</p>`,
  disc: [{ ans:'A (100%)', txt:'ECR의 수명 주기 정책이 컨테이너 이미지의 태그 기반 자동 만료를 위한 최적 솔루션입니다.' }]
},
{
  n: 325,
  en: `A company uses Amazon Redshift as its data warehouse solution. The company wants to create a dashboard to view changes to the Redshift users and the queries the users perform.<br>Which combination of steps will meet this requirement? (Choose two.)`,
  ko: `한 회사가 Amazon Redshift를 데이터 웨어하우스 솔루션으로 사용합니다. 회사는 Redshift 사용자와 사용자가 수행하는 쿼리에 대한 변경 사항을 볼 수 있는 대시보드를 생성하려 합니다.<br>이 요구 사항을 충족하는 단계 조합은 무엇입니까? (2개 선택)`,
  type: 'multi', multiCount: 2,
  choices: [
    { k:'A', en:`Create an Amazon CloudWatch log group. Create an AWS CloudTrail trail that writes to the CloudWatch log group.`, ko:`Amazon CloudWatch 로그 그룹을 생성합니다. CloudWatch 로그 그룹에 쓰는 AWS CloudTrail 트레일을 생성합니다.` },
    { k:'B', en:`Create a new Amazon S3 bucket. Configure default audit logging on the Redshift cluster. Configure the S3 bucket as the target.`, ko:`새 Amazon S3 버킷을 생성합니다. Redshift 클러스터에서 기본 감사 로깅을 구성합니다. S3 버킷을 대상으로 구성합니다.` },
    { k:'C', en:`Configure the Redshift cluster database audit logging to include user activity logs. Configure Amazon CloudWatch as the target.`, ko:`사용자 활동 로그를 포함하도록 Redshift 클러스터 데이터베이스 감사 로깅을 구성합니다. Amazon CloudWatch를 대상으로 구성합니다.` },
    { k:'D', en:`Create an Amazon CloudWatch dashboard that has a log widget. Configure the widget to display user details from the Redshift logs.`, ko:`로그 위젯이 있는 Amazon CloudWatch 대시보드를 생성합니다. Redshift 로그에서 사용자 세부 정보를 표시하도록 위젯을 구성합니다.` },
    { k:'E', en:`Create an AWS Lambda function that uses Amazon Athena to query the Redshift logs. Create an Amazon CloudWatch dashboard that has a custom widget type that uses the Lambda function.`, ko:`Amazon Athena를 사용하여 Redshift 로그를 쿼리하는 AWS Lambda 함수를 생성합니다. Lambda 함수를 사용하는 사용자 지정 위젯 유형이 있는 Amazon CloudWatch 대시보드를 생성합니다.` },
  ],
  answer: ['C','D'],
  vote: '80% CD',
  explain: `<p><span class="mark-ok">✅ C — Redshift 감사 로깅을 CloudWatch로 전송</span></p><p>사용자 활동 로그를 포함하는 Redshift 감사 로깅을 활성화하고 Amazon CloudWatch를 대상으로 설정합니다. 이를 통해 쿼리 실행과 사용자 활동이 기록됩니다.</p><p><span class="mark-ok">✅ D — CloudWatch 로그 위젯 대시보드</span></p><p>CloudWatch에 저장된 Redshift 로그를 로그 위젯으로 표시하는 대시보드를 생성합니다. E에서 요구하는 S3 기반 로그가 필요 없어 더 간단합니다.</p>`,
  wrong: `<p><span class="mark-no">❌ A</span> — CloudTrail은 API 호출을 기록하지만 Redshift SQL 쿼리 내용은 기록하지 않습니다.</p><p><span class="mark-no">❌ B</span> — S3를 대상으로 하면 E의 방식이 필요하지만, CloudWatch를 대상으로 하는 C + D가 더 간단합니다.</p><p><span class="mark-no">❌ E</span> — Lambda + Athena 방식은 로그가 S3에 있을 때 필요하며, C를 선택하면 불필요합니다.</p>`,
  disc: [{ ans:'CD (80%)', txt:'Redshift 감사 로깅을 CloudWatch로 전송하면 S3와 Athena 없이 직접 대시보드를 구성할 수 있어 더 효율적입니다.' }]
},
{
  n: 326,
  en: `A company uses an organization in AWS Organizations to manage its 500 AWS accounts. The organization has all features enabled. The AWS accounts are in a single OU. The developers need to use the CostCenter tag key for all resources in the organization's member accounts. Some teams do not use the CostCenter tag key to tag their Amazon EC2 instances.<br>The cloud team wrote a script that scans all EC2 instances in the organization's member accounts. If the EC2 instances do not have a CostCenter tag key, the script will notify AWS account administrators. To avoid this notification, some developers use the CostCenter tag key with an arbitrary string in the tag value.<br>The cloud team needs to ensure that all EC2 instances in the organization use a CostCenter tag key with the appropriate cost center value.<br>Which solution will meet these requirements?`,
  ko: `한 회사가 AWS Organizations의 조직을 사용하여 500개의 AWS 계정을 관리합니다. 조직에는 모든 기능이 활성화되어 있습니다. AWS 계정은 단일 OU에 있습니다. 개발자는 조직의 멤버 계정에 있는 모든 리소스에 CostCenter 태그 키를 사용해야 합니다. 일부 팀은 Amazon EC2 인스턴스에 CostCenter 태그 키를 사용하지 않습니다.<br>클라우드 팀은 스크립트를 작성하여 스캔합니다. 일부 개발자는 알림을 피하기 위해 임의의 문자열 값으로 CostCenter 태그 키를 사용합니다.<br>모든 EC2 인스턴스가 적절한 비용 센터 값이 있는 CostCenter 태그 키를 사용하도록 보장하는 솔루션은 무엇입니까?`,
  type: 'single',
  choices: [
    { k:'A', en:`Create an SCP that prevents the creation of EC2 instances without the CostCenter tag key. Create a tag policy that requires the CostCenter tag to be values from a known list of cost centers for all EC2 instances. Attach the policy to the OU. Update the script to scan the tag keys and tag values. Modify the script to update noncompliant resources with a default approved tag value for the CostCenter tag key.`, ko:`CostCenter 태그 키 없이 EC2 인스턴스를 생성하지 못하게 하는 SCP를 생성합니다. CostCenter 태그가 모든 EC2 인스턴스에 대해 알려진 비용 센터 목록에서 나온 값이 되도록 요구하는 태그 정책을 생성합니다. 정책을 OU에 연결합니다. 태그 키와 태그 값을 스캔하도록 스크립트를 업데이트합니다. 규정 미준수 리소스를 CostCenter 태그 키에 대한 기본 승인된 태그 값으로 업데이트하도록 스크립트를 수정합니다.` },
    { k:'B', en:`Create an SCP that prevents the creation of EC2 instances without the CostCenter tag key. Attach the policy to the OU. Update the script to scan the tag keys and tag values and notify the administrators when the tag values are not valid.`, ko:`CostCenter 태그 키 없이 EC2 인스턴스를 생성하지 못하게 하는 SCP를 생성합니다. 정책을 OU에 연결합니다. 태그 키와 태그 값을 스캔하고 태그 값이 유효하지 않을 때 관리자에게 알리도록 스크립트를 업데이트합니다.` },
    { k:'C', en:`Create an SCP that prevents the creation of EC2 instances without the CostCenter tag key. Attach the policy to the OU. Create an IAM permission boundary in the organization's member accounts that restricts the CostCenter tag values to a list of valid cost centers.`, ko:`CostCenter 태그 키 없이 EC2 인스턴스를 생성하지 못하게 하는 SCP를 생성합니다. 정책을 OU에 연결합니다. CostCenter 태그 값을 유효한 비용 센터 목록으로 제한하는 IAM 권한 경계를 조직의 멤버 계정에 생성합니다.` },
    { k:'D', en:`Create a tag policy that requires the CostCenter tag to be values from a known list of cost centers for all EC2 instances. Attach the policy to the OU. Configure an AWS Lambda function that adds an empty CostCenter tag key to an EC2 instance. Create an Amazon EventBridge rule that matches events to the RunInstances API action with the Lambda function as the target.`, ko:`CostCenter 태그가 모든 EC2 인스턴스에 대해 알려진 비용 센터 목록에서 나온 값이 되도록 요구하는 태그 정책을 생성합니다. 정책을 OU에 연결합니다. EC2 인스턴스에 빈 CostCenter 태그 키를 추가하는 AWS Lambda 함수를 구성합니다. RunInstances API 작업의 이벤트를 Lambda 함수를 대상으로 매칭하는 Amazon EventBridge 규칙을 생성합니다.` },
  ],
  answer: ['A'],
  vote: '100% A',
  explain: `<p><span class="mark-ok">✅ A — SCP + 태그 정책 + 스크립트 업데이트</span></p><p>세 가지 통제를 결합합니다: (1) SCP로 CostCenter 태그 없는 EC2 생성 방지, (2) 태그 정책으로 허용된 비용 센터 값 목록 적용, (3) 업데이트된 스크립트로 태그 값 검증 및 기존 미준수 리소스를 기본값으로 수정. 이는 태그 존재 여부와 값의 유효성 모두를 처리하는 종합적인 솔루션입니다.</p>`,
  wrong: `<p><span class="mark-no">❌ B</span> — 알림만으로는 태그 값 유효성 문제가 해결되지 않습니다.</p><p><span class="mark-no">❌ C</span> — IAM 권한 경계는 태그 값 제한에 적합한 메커니즘이 아닙니다.</p><p><span class="mark-no">❌ D</span> — 빈 태그 값으로 추가하는 것은 기존 문제(임의 문자열 값)를 해결하지 못합니다.</p>`,
  disc: [{ ans:'A (100%)', txt:'SCP, 태그 정책, 스크립트 업데이트의 조합이 태그 키 존재와 유효한 값을 모두 보장하는 종합적인 솔루션입니다.' }]
},
{
  n: 327,
  en: `A DevOps engineer uses a pipeline in AWS CodePipeline. The pipeline has a build action and a deploy action for a single-page web application that is delivered to an Amazon S3 bucket. Amazon CloudFront serves the web application. The build action creates an artifact for the web application.<br>The DevOps engineer has created an AWS CloudFormation template that defines the S3 bucket and configures the S3 bucket to host the application. The DevOps engineer has configured a CloudFormation deploy action before the S3 action. The CloudFormation deploy action creates the S3 bucket. The DevOps engineer needs to configure the S3 deploy action to use the S3 bucket from the CloudFormation template.<br>Which combination of steps will meet these requirements? (Choose two.)`,
  ko: `DevOps 엔지니어가 AWS CodePipeline에서 파이프라인을 사용합니다. 파이프라인에는 Amazon S3 버킷에 전달되는 단일 페이지 웹 애플리케이션에 대한 빌드 작업과 배포 작업이 있습니다. Amazon CloudFront가 웹 애플리케이션을 제공합니다.<br>DevOps 엔지니어는 S3 버킷을 정의하고 애플리케이션을 호스팅하도록 S3 버킷을 구성하는 AWS CloudFormation 템플릿을 생성했습니다. S3 작업 전에 CloudFormation 배포 작업을 구성했습니다. CloudFormation 배포 작업은 S3 버킷을 생성합니다. DevOps 엔지니어는 CloudFormation 템플릿의 S3 버킷을 사용하도록 S3 배포 작업을 구성해야 합니다.<br>이 요구 사항을 충족하는 단계 조합은 무엇입니까? (2개 선택)`,
  type: 'multi', multiCount: 2,
  choices: [
    { k:'A', en:`Add an output named BucketName to the CloudFormation template. Set the output's value to refer to the S3 bucket from the CloudFormation template. Configure the output value to export to an AWS::SSM::Parameter resource named Stackvariables.`, ko:`CloudFormation 템플릿에 BucketName이라는 이름의 출력을 추가합니다. 출력의 값을 CloudFormation 템플릿의 S3 버킷을 참조하도록 설정합니다. 출력 값을 Stackvariables라는 이름의 AWS::SSM::Parameter 리소스로 내보내도록 구성합니다.` },
    { k:'B', en:`Add an output named BucketName to the CloudFormation template. Set the output's value to refer to the S3 bucket from the CloudFormation template. Set the CloudFormation action's namespace to StackVariables in the pipeline.`, ko:`CloudFormation 템플릿에 BucketName이라는 이름의 출력을 추가합니다. 출력의 값을 CloudFormation 템플릿의 S3 버킷을 참조하도록 설정합니다. 파이프라인에서 CloudFormation 작업의 네임스페이스를 StackVariables로 설정합니다.` },
    { k:'C', en:`Configure the output artifacts of the CloudFormation action in the pipeline to be an AWS Systems Manager Parameter Store parameter named StackVariables. Name the artifact BucketName.`, ko:`파이프라인에서 CloudFormation 작업의 출력 아티팩트를 StackVariables라는 이름의 AWS Systems Manager Parameter Store 파라미터로 구성합니다. 아티팩트 이름을 BucketName으로 지정합니다.` },
    { k:'D', en:`Configure the build artifact from the build action as the input to the CodePipeline S3 deploy action. Configure the deploy action to deploy to the S3 bucket by using the StackVariables.BucketName variable.`, ko:`빌드 작업의 빌드 아티팩트를 CodePipeline S3 배포 작업의 입력으로 구성합니다. StackVariables.BucketName 변수를 사용하여 배포 작업을 S3 버킷에 배포하도록 구성합니다.` },
    { k:'E', en:`Configure the build artifact from the build action and the AWS Systems Manager parameter as the inputs to the deploy action. Configure the deploy action to deploy to the S3 bucket by using the StackVariables.BucketName variable.`, ko:`빌드 작업의 빌드 아티팩트와 AWS Systems Manager 파라미터를 배포 작업의 입력으로 구성합니다. StackVariables.BucketName 변수를 사용하여 S3 버킷에 배포하도록 배포 작업을 구성합니다.` },
  ],
  answer: ['B','D'],
  vote: '100% BD',
  explain: `<p><span class="mark-ok">✅ B — CloudFormation 템플릿에 BucketName 출력 + 네임스페이스 설정</span></p><p>CloudFormation 작업에 네임스페이스(StackVariables)를 설정하면 스택 출력(BucketName)이 파이프라인 변수로 노출됩니다. 다른 작업에서 <code>#{StackVariables.BucketName}</code>으로 참조할 수 있습니다.</p><p><span class="mark-ok">✅ D — 빌드 아티팩트를 S3 배포 작업 입력으로 + StackVariables.BucketName 사용</span></p><p>빌드 아티팩트를 S3 배포 작업의 입력으로 구성하고, CloudFormation 출력 변수를 사용하여 동적으로 S3 버킷을 지정합니다.</p>`,
  wrong: `<p><span class="mark-no">❌ A</span> — SSM Parameter로 내보내는 것은 파이프라인 변수를 사용하는 것보다 복잡합니다.</p><p><span class="mark-no">❌ C</span> — CloudFormation 작업 출력 아티팩트를 SSM 파라미터로 직접 구성할 수 없습니다.</p><p><span class="mark-no">❌ E</span> — SSM 파라미터를 추가 입력으로 구성하는 것은 불필요합니다.</p>`,
  disc: [{ ans:'BD (100%)', txt:'CloudFormation 네임스페이스 변수를 통해 스택 출력을 파이프라인 변수로 참조하는 것이 올바른 패턴입니다.' }]
},
{
  n: 328,
  en: `A company used a lift and shift strategy to migrate a workload to AWS. The company has an Auto Scaling group of Amazon EC2 instances. Each EC2 instance runs a web application, a database, and a Redis cache.<br>Users are experiencing large variations in the web application's response times. Requests to the web application go to a single EC2 instance that is under significant load. The company wants to separate the application components to improve availability and performance.<br>Which solution will meet these requirements?`,
  ko: `한 회사가 리프트 앤 시프트 전략을 사용하여 워크로드를 AWS로 마이그레이션했습니다. 회사에는 Amazon EC2 인스턴스의 Auto Scaling 그룹이 있습니다. 각 EC2 인스턴스는 웹 애플리케이션, 데이터베이스, Redis 캐시를 실행합니다.<br>사용자는 웹 애플리케이션의 응답 시간에 큰 차이를 경험하고 있습니다. 웹 애플리케이션에 대한 요청은 상당한 부하가 걸린 단일 EC2 인스턴스로 이동합니다. 회사는 가용성과 성능을 개선하기 위해 애플리케이션 구성 요소를 분리하려 합니다.<br>이 요구 사항을 충족하는 솔루션은 무엇입니까?`,
  type: 'single',
  choices: [
    { k:'A', en:`Create a Network Load Balancer and an Auto Scaling group for the web application. Migrate the database to an Amazon Aurora Serverless database. Create an Application Load Balancer and an Auto Scaling group for the Redis cache.`, ko:`웹 애플리케이션에 대한 Network Load Balancer와 Auto Scaling 그룹을 생성합니다. 데이터베이스를 Amazon Aurora Serverless 데이터베이스로 마이그레이션합니다. Redis 캐시에 대한 Application Load Balancer와 Auto Scaling 그룹을 생성합니다.` },
    { k:'B', en:`Create an Application Load Balancer and an Auto Scaling group for the web application. Migrate the database to an Amazon Aurora database that has a Multi-AZ deployment. Create a Network Load Balancer and an Auto Scaling group in a single Availability Zone for the Redis cache.`, ko:`웹 애플리케이션에 대한 Application Load Balancer와 Auto Scaling 그룹을 생성합니다. 데이터베이스를 Multi-AZ 배포가 있는 Amazon Aurora 데이터베이스로 마이그레이션합니다. Redis 캐시에 대한 단일 가용 영역의 Network Load Balancer와 Auto Scaling 그룹을 생성합니다.` },
    { k:'C', en:`Create a Network Load Balancer and an Auto Scaling group for the web application. Migrate the database to an Amazon Aurora Serverless database. Create an Amazon ElastiCache (Redis OSS) cluster for the cache. Create a target group that has a DNS target type that contains the ElastiCache (Redis OSS) cluster hostname.`, ko:`웹 애플리케이션에 대한 Network Load Balancer와 Auto Scaling 그룹을 생성합니다. 데이터베이스를 Amazon Aurora Serverless 데이터베이스로 마이그레이션합니다. 캐시에 대한 Amazon ElastiCache(Redis OSS) 클러스터를 생성합니다. ElastiCache(Redis OSS) 클러스터 호스트 이름이 포함된 DNS 대상 유형이 있는 대상 그룹을 생성합니다.` },
    { k:'D', en:`Create an Application Load Balancer and an Auto Scaling group for the web application. Migrate the database to an Amazon Aurora database that has a Multi-AZ deployment. Create an Amazon ElastiCache (Redis OSS) cluster for the cache.`, ko:`웹 애플리케이션에 대한 Application Load Balancer와 Auto Scaling 그룹을 생성합니다. 데이터베이스를 Multi-AZ 배포가 있는 Amazon Aurora 데이터베이스로 마이그레이션합니다. 캐시에 대한 Amazon ElastiCache(Redis OSS) 클러스터를 생성합니다.` },
  ],
  answer: ['D'],
  vote: '100% D',
  explain: `<p><span class="mark-ok">✅ D — ALB + Auto Scaling + Aurora Multi-AZ + ElastiCache</span></p><p>웹 애플리케이션: ALB + Auto Scaling 그룹으로 트래픽을 여러 인스턴스에 분산합니다. 데이터베이스: Aurora Multi-AZ 배포로 고가용성을 보장하고 EC2 인스턴스에서 DB 부하를 분리합니다. 캐시: ElastiCache(Redis OSS)로 캐싱을 전담 관리형 서비스로 분리합니다. 각 구성 요소를 분리하여 가용성과 성능을 개선합니다.</p>`,
  wrong: `<p><span class="mark-no">❌ A</span> — Redis 캐시에 ALB + Auto Scaling 그룹은 부적합합니다. ElastiCache가 올바른 솔루션입니다.</p><p><span class="mark-no">❌ B</span> — 단일 AZ의 Redis Auto Scaling 그룹은 고가용성을 제공하지 않습니다.</p><p><span class="mark-no">❌ C</span> — NLB는 HTTP 기반 웹 애플리케이션에 ALB보다 적합하지 않습니다.</p>`,
  disc: [{ ans:'D (100%)', txt:'ALB, Aurora Multi-AZ, ElastiCache의 조합이 각 구성 요소를 효과적으로 분리하고 가용성과 성능을 개선하는 최적 솔루션입니다.' }]
},
{
  n: 329,
  en: `A company is using AWS Organizations and wants to implement a governance strategy with the following requirements:<br>• AWS resource access is restricted to the same two Regions for all accounts.<br>• AWS services are limited to a specific group of authorized services for all accounts.<br>• Authentication is provided by Active Directory.<br>• Access permissions are organized by job function and are identical in each account.<br>Which solution will meet these requirements?`,
  ko: `한 회사가 AWS Organizations를 사용하고 있으며 다음 요구 사항을 갖춘 거버넌스 전략을 구현하려 합니다:<br>• AWS 리소스 액세스는 모든 계정에 대해 동일한 두 리전으로 제한됩니다.<br>• AWS 서비스는 모든 계정에 대해 특정 승인된 서비스 그룹으로 제한됩니다.<br>• 인증은 Active Directory에서 제공합니다.<br>• 액세스 권한은 직무별로 구성되며 각 계정에서 동일합니다.<br>이 요구 사항을 충족하는 솔루션은 무엇입니까?`,
  type: 'single',
  choices: [
    { k:'A', en:`Establish an organizational unit (OU) with group policies in the management account to restrict Regions and authorized services. Use AWS CloudFormation StackSets to provision roles with permissions for each job function, including an IAM trust policy for IAM identity provider authentication in each account.`, ko:`관리 계정에서 그룹 정책이 있는 OU를 설정하여 리전과 승인된 서비스를 제한합니다. AWS CloudFormation StackSets를 사용하여 각 계정에서 IAM ID 공급자 인증을 위한 IAM 신뢰 정책을 포함하여 각 직무에 대한 권한이 있는 역할을 프로비저닝합니다.` },
    { k:'B', en:`Establish a permission boundary in the management account to restrict Regions and authorized services. Use AWS CloudFormation StackSets to provision roles with permissions for each job function, including an IAM trust policy for IAM identity provider authentication in each account.`, ko:`관리 계정에서 권한 경계를 설정하여 리전과 승인된 서비스를 제한합니다. AWS CloudFormation StackSets를 사용하여 각 계정에서 IAM ID 공급자 인증을 위한 IAM 신뢰 정책을 포함하여 각 직무에 대한 권한이 있는 역할을 프로비저닝합니다.` },
    { k:'C', en:`Establish a service control policy in the management account to restrict Regions and authorized services. Use AWS Resource Access Manager (AWS RAM) to share management account roles with permissions for each job function, including AWS IAM Identity Center for authentication in each account.`, ko:`관리 계정에서 서비스 제어 정책을 수립하여 리전과 승인된 서비스를 제한합니다. AWS Resource Access Manager(AWS RAM)를 사용하여 각 계정의 인증을 위한 AWS IAM Identity Center를 포함하여 각 직무에 대한 권한과 관리 계정 역할을 공유합니다.` },
    { k:'D', en:`Establish a service control policy in the management account to restrict Regions and authorized services. Use AWS CloudFormation StackSets to provision roles with permissions for each job function, including an IAM trust policy for IAM identity provider authentication in each account.`, ko:`관리 계정에서 서비스 제어 정책을 수립하여 리전과 승인된 서비스를 제한합니다. AWS CloudFormation StackSets를 사용하여 각 계정에서 IAM ID 공급자 인증을 위한 IAM 신뢰 정책을 포함하여 각 직무에 대한 권한이 있는 역할을 프로비저닝합니다.` },
  ],
  answer: ['D'],
  vote: '100% D',
  explain: `<p><span class="mark-ok">✅ D — SCP(리전/서비스 제한) + StackSets(직무별 역할 + IAM ID 공급자)</span></p><p>SCP: 조직 수준에서 AWS 리전 및 서비스 액세스를 제한합니다. CloudFormation StackSets: 모든 계정에서 표준화된 직무별 역할을 자동으로 생성합니다. IAM 신뢰 정책: Active Directory(IAM ID 공급자)를 통한 인증을 허용합니다.</p>`,
  wrong: `<p><span class="mark-no">❌ A</span> — AWS Organizations는 그룹 정책(GPO)이 아닌 SCP를 사용합니다.</p><p><span class="mark-no">❌ B</span> — 권한 경계는 개별 계정 수준 통제이며 조직 전체 리전/서비스 제한에 적합하지 않습니다.</p><p><span class="mark-no">❌ C</span> — AWS RAM은 역할 공유에 적합하지 않으며, Active Directory 요구 사항에 IAM Identity Center가 부적합할 수 있습니다.</p>`,
  disc: [{ ans:'D (100%)', txt:'SCP + StackSets + IAM ID 공급자의 조합이 모든 거버넌스 요구 사항을 충족하는 표준 패턴입니다.' }]
},
{
  n: 330,
  en: `A company detects unusual login attempts in many of its AWS accounts. A DevOps engineer must implement a solution that sends a notification to the company's security team when multiple failed login attempts occur. The DevOps engineer has already created an Amazon Simple Notification Service (Amazon SNS) topic and has subscribed the security team to the SNS topic.<br>Which solution will provide the notification with the LEAST operational effort?`,
  ko: `한 회사가 여러 AWS 계정에서 비정상적인 로그인 시도를 감지했습니다. DevOps 엔지니어는 여러 번 로그인 시도가 실패하면 회사 보안 팀에 알림을 보내는 솔루션을 구현해야 합니다. DevOps 엔지니어는 이미 Amazon SNS 토픽을 생성했고 보안 팀을 SNS 토픽에 구독했습니다.<br>가장 적은 운영 노력으로 알림을 제공하는 솔루션은 무엇입니까?`,
  type: 'single',
  choices: [
    { k:'A', en:`Configure AWS CloudTrail to send management events to an Amazon CloudWatch Logs log group. Create a CloudWatch Logs metric filter to match failed ConsoleLogin events. Create a CloudWatch alarm that is based on the metric filter. Configure an alarm action to send messages to the SNS topic.`, ko:`AWS CloudTrail을 구성하여 관리 이벤트를 Amazon CloudWatch Logs 로그 그룹으로 보냅니다. 실패한 ConsoleLogin 이벤트와 일치하도록 CloudWatch Logs 메트릭 필터를 생성합니다. 메트릭 필터를 기반으로 하는 CloudWatch 알람을 생성합니다. SNS 토픽으로 메시지를 보내도록 알람 작업을 구성합니다.` },
    { k:'B', en:`Configure AWS CloudTrail to send management events to an Amazon S3 bucket. Create an Amazon Athena query that returns a failure if the query finds failed logins in the logs in the S3 bucket. Create an Amazon EventBridge rule to periodically run the query. Create a second EventBridge rule to detect when the query fails and to send a message to the SNS topic.`, ko:`AWS CloudTrail을 구성하여 관리 이벤트를 Amazon S3 버킷으로 보냅니다. S3 버킷의 로그에서 실패한 로그인을 발견하면 실패를 반환하는 Amazon Athena 쿼리를 생성합니다. Amazon EventBridge 규칙을 생성하여 주기적으로 쿼리를 실행합니다. 쿼리가 실패할 때를 감지하고 SNS 토픽에 메시지를 보내는 두 번째 EventBridge 규칙을 생성합니다.` },
    { k:'C', en:`Configure AWS CloudTrail to send data events to an Amazon CloudWatch Logs log group. Create a CloudWatch logs metric filter to match failed ConsoleLogin events. Create a CloudWatch alarm that is based on the metric filter. Configure an alarm action to send messages to the SNS topic.`, ko:`AWS CloudTrail을 구성하여 데이터 이벤트를 Amazon CloudWatch Logs 로그 그룹으로 전송합니다. 실패한 ConsoleLogin 이벤트와 일치하도록 CloudWatch Logs 메트릭 필터를 생성합니다. 메트릭 필터를 기반으로 하는 CloudWatch 알람을 생성합니다. SNS 토픽으로 메시지를 전송하도록 알람 작업을 구성합니다.` },
    { k:'D', en:`Configure AWS CloudTrail to send data events to an Amazon S3 bucket. Configure an Amazon S3 event notification for the s3:ObjectCreated event type. Filter the event type by ConsoleLogin failed events. Configure the event notification to forward to the SNS topic.`, ko:`AWS CloudTrail을 구성하여 데이터 이벤트를 Amazon S3 버킷으로 전송합니다. s3:ObjectCreated 이벤트 유형에 대한 Amazon S3 이벤트 알림을 구성합니다. ConsoleLogin 실패 이벤트로 이벤트 유형을 필터링합니다. 이벤트 알림을 SNS 토픽으로 전달하도록 구성합니다.` },
  ],
  answer: ['A'],
  vote: '93% A',
  explain: `<p><span class="mark-ok">✅ A — CloudTrail 관리 이벤트 → CloudWatch Logs → 메트릭 필터 → 알람 → SNS</span></p><p>ConsoleLogin은 CloudTrail 관리 이벤트입니다. CloudTrail을 CloudWatch Logs로 전송하도록 구성하면 메트릭 필터로 실패한 ConsoleLogin 이벤트를 감지하고, CloudWatch 알람이 임계값 초과 시 SNS로 알림을 전송합니다. 간단하고 통합된 워크플로입니다.</p>`,
  wrong: `<p><span class="mark-no">❌ B</span> — Athena + EventBridge 두 개 규칙 방식은 훨씬 복잡하고 운영 오버헤드가 높습니다.</p><p><span class="mark-no">❌ C</span> — ConsoleLogin은 데이터 이벤트가 아닌 관리 이벤트입니다.</p><p><span class="mark-no">❌ D</span> — S3 이벤트 알림은 CloudTrail 로그 파일 생성 이벤트를 감지하지만, 파일 내 특정 이벤트를 필터링할 수 없습니다.</p>`,
  disc: [{ ans:'A (93%)', txt:'CloudTrail 관리 이벤트를 CloudWatch Logs로 전송하고 메트릭 필터로 실패한 로그인을 감지하는 것이 가장 간단하고 직접적인 솔루션입니다.' }]
}
];
