window.QS_SET01 = [
{
  n:1,
  en:`A company has a mobile application that makes HTTP API calls to an Application Load Balancer (ALB). The ALB routes requests to an AWS Lambda function. Many different versions of the application are in use at any given time, including versions that are in testing by a subset of users. The version of the application is defined in the user-agent header that is sent with all requests to the API.<br><br>After a series of recent changes to the API, the company has observed issues with the application. The company needs to gather a metric for each API operation by response code for each version of the application that is in use. A DevOps engineer has modified the Lambda function to extract the API operation name, version information from the user-agent header and response code.<br><br><strong>Which additional set of actions should the DevOps engineer take to gather the required metrics?</strong>`,
  ko:`한 회사에 ALB(Application Load Balancer)로 HTTP API를 호출하는 모바일 애플리케이션이 있습니다. ALB는 요청을 AWS Lambda 함수로 라우팅합니다. 사용자 하위 집합이 테스트 중인 버전을 포함하여 언제든지 여러 다른 버전의 애플리케이션이 사용 중입니다. 애플리케이션 버전은 API에 대한 모든 요청과 함께 전송되는 user-agent 헤더에 정의되어 있습니다.<br><br>API에 대한 최근 일련의 변경 이후, 회사는 애플리케이션에 문제가 있음을 발견했습니다. 회사는 사용 중인 애플리케이션의 각 버전에 대한 응답 코드로 각 API 작업에 대한 메트릭을 수집해야 합니다. DevOps 엔지니어는 API 작업 이름, user-agent 헤더의 버전 정보 및 응답 코드를 추출하도록 Lambda 함수를 수정했습니다.<br><br><strong>필요한 메트릭을 수집하기 위해 DevOps 엔지니어가 추가로 수행해야 할 작업은 무엇입니까?</strong>`,
  type:'single',
  choices:[
    {k:'A', en:`Modify the Lambda function to write the API operation name, response code, and version number as a log line to an Amazon CloudWatch Logs log group. Configure a CloudWatch Logs metric filter that increments a metric for each API operation name. Specify response code and application version as dimensions for the metric.`, ko:`Lambda 함수를 수정하여 API 작업 이름, 응답 코드, 버전 번호를 Amazon CloudWatch Logs 로그 그룹에 로그 줄로 씁니다. 각 API 작업 이름에 대한 메트릭을 증가시키는 CloudWatch Logs 메트릭 필터를 구성합니다. 메트릭에 대한 차원으로 응답 코드와 애플리케이션 버전을 지정합니다.`},
    {k:'B', en:`Modify the Lambda function to write the API operation name, response code, and version number as a log line to an Amazon CloudWatch Logs log group. Configure a CloudWatch Logs Insights query to populate CloudWatch metrics from the log lines. Specify response code and application version as dimensions for the metric.`, ko:`Lambda 함수를 수정하여 API 작업 이름, 응답 코드, 버전 번호를 Amazon CloudWatch Logs 로그 그룹에 로그 줄로 씁니다. CloudWatch Logs Insights 쿼리를 구성하여 로그 줄에서 CloudWatch 메트릭을 채웁니다. 메트릭의 차원으로 응답 코드와 애플리케이션 버전을 지정합니다.`},
    {k:'C', en:`Configure the ALB access logs to write to an Amazon CloudWatch Logs log group. Modify the Lambda function to respond to the ALB with the API operation name, response code, and version number as response metadata. Configure a CloudWatch Logs metric filter that increments a metric for each API operation name. Specify response code and application version as dimensions for the metric.`, ko:`ALB 액세스 로그를 Amazon CloudWatch Logs 로그 그룹에 쓰도록 구성합니다. API 작업 이름, 응답 코드 및 버전 번호를 응답 메타데이터로 ALB에 응답하도록 Lambda 함수를 수정합니다. 각 API 작업 이름에 대한 메트릭을 증가시키는 CloudWatch Logs 메트릭 필터를 구성합니다. 메트릭의 차원으로 응답 코드와 애플리케이션 버전을 지정합니다.`},
    {k:'D', en:`Configure AWS X-Ray integration on the Lambda function. Modify the Lambda function to create an X-Ray subsegment with the API operation name, response code, and version number. Configure X-Ray insights to extract an aggregated metric for each API operation name and to publish the metric to Amazon CloudWatch. Specify response code and application version as dimensions for the metric.`, ko:`Lambda 함수에서 AWS X-Ray 통합을 구성합니다. API 작업 이름, 응답 코드 및 버전 번호로 X-Ray 하위 세그먼트를 만들도록 Lambda 함수를 수정합니다. X-Ray 인사이트를 구성하여 각 API 작업 이름에 대한 집계된 메트릭을 추출하고 Amazon CloudWatch에 게시합니다. 메트릭의 차원으로 응답 코드와 애플리케이션 버전을 지정합니다.`},
  ],
  answer:['A'],
  vote:'87% A',
  explain:`<p><span class="mark-ok">✅ A — CloudWatch Logs 메트릭 필터</span></p><p>Lambda에서 로그 줄을 CloudWatch Logs에 기록하고, <strong>메트릭 필터(Metric Filter)</strong>로 패턴을 파싱하여 메트릭을 생성하는 것이 AWS 권장 패턴입니다. 응답 코드와 애플리케이션 버전을 메트릭 차원으로 지정하면 버전·응답코드별 API 작업 메트릭을 자동으로 수집할 수 있습니다. 메트릭 필터는 시계열 데이터를 생성하여 알람, Lambda 트리거, 이상 탐지 모델 등에 활용 가능합니다.</p><p><a href="https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/FilterAndPatternSyntaxForMetricFilters.html" target="_blank">📎 AWS 공식 문서</a></p>`,
  wrong:`<p><span class="mark-no">❌ B</span> — CloudWatch Logs Insights는 대화형 임시 분석 도구이며, 쿼리 결과로 CloudWatch 메트릭을 자동으로 생성할 수 없습니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ C</span> — ALB 액세스 로그는 Lambda 응답 메타데이터를 직접 기록하지 않으며, 구성이 불필요하게 복잡합니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ D</span> — X-Ray는 분산 추적(tracing) 목적이며, 이 사용 사례에 과도하게 복잡한 솔루션입니다.</p>`,
  disc:[{ans:'A (87%)',txt:'메트릭 필터는 로그 데이터에서 자동으로 시계열 메트릭을 생성합니다. Logs Insights는 인터랙티브 분석용이며 자동 액션을 트리거할 수 없습니다. — AWS 공식 블로그'}]
},
{
  n:2,
  en:`A company provides an application to customers. The application has an Amazon API Gateway REST API that invokes an AWS Lambda function. On initialization, the Lambda function loads a large amount of data from an Amazon DynamoDB table. The data load process results in long cold-start times of 8-10 seconds. The DynamoDB table has DynamoDB Accelerator (DAX) configured.<br><br>Customers report that the application intermittently takes a long time to respond to requests. The application receives thousands of requests throughout the day. In the middle of the day, the application experiences 10 times more requests than at any other time of the day. Near the end of the day, the application's request volume decreases to 10% of its normal total.<br><br>A DevOps engineer needs to reduce the latency of the Lambda function at all times of the day.<br><br><strong>Which solution will meet these requirements?</strong>`,
  ko:`한 회사가 고객에게 애플리케이션을 제공합니다. 이 애플리케이션에는 AWS Lambda 함수를 호출하는 Amazon API Gateway REST API가 있습니다. 초기화 시 Lambda 함수는 Amazon DynamoDB 테이블에서 대량의 데이터를 로드합니다. 데이터 로드 프로세스로 인해 8~10초의 긴 콜드 스타트 시간이 발생합니다. DynamoDB 테이블에는 DynamoDB Accelerator(DAX)가 구성되어 있습니다.<br><br>고객들은 애플리케이션이 요청에 응답하는 데 간헐적으로 오랜 시간이 걸린다고 보고합니다. 이 애플리케이션은 하루 종일 수천 개의 요청을 받습니다. 하루 중간에 다른 시간대보다 10배 더 많은 요청을 경험합니다. 하루가 끝나갈 무렵 요청 볼륨은 일반적인 총량의 10%로 감소합니다.<br><br>DevOps 엔지니어는 하루 종일 Lambda 함수의 지연 시간을 줄여야 합니다.<br><br><strong>어떤 솔루션이 이러한 요구 사항을 충족합니까?</strong>`,
  type:'single',
  choices:[
    {k:'A', en:`Configure provisioned concurrency on the Lambda function with a concurrency value of 1. Delete the DAX cluster for the DynamoDB table.`, ko:`Lambda 함수에서 동시성 값 1로 프로비저닝된 동시성을 구성합니다. DynamoDB 테이블의 DAX 클러스터를 삭제합니다.`},
    {k:'B', en:`Configure reserved concurrency on the Lambda function with a concurrency value of 0.`, ko:`Lambda 함수에서 동시성 값 0으로 예약된 동시성을 구성합니다.`},
    {k:'C', en:`Configure provisioned concurrency on the Lambda function. Configure AWS Application Auto Scaling on the Lambda function with provisioned concurrency values set to a minimum of 1 and a maximum of 100.`, ko:`Lambda 함수에서 프로비저닝된 동시성을 구성합니다. Lambda 함수에서 AWS Application Auto Scaling을 프로비저닝된 동시성 값을 최소 1, 최대 100으로 설정하여 구성합니다.`},
    {k:'D', en:`Configure reserved concurrency on the Lambda function. Configure AWS Application Auto Scaling on the API Gateway API with a reserved concurrency maximum value of 100.`, ko:`Lambda 함수에서 예약된 동시성을 구성합니다. API Gateway API에서 예약된 동시성 최대값 100으로 AWS Application Auto Scaling을 구성합니다.`},
  ],
  answer:['C'],
  vote:'100% C',
  explain:`<p><span class="mark-ok">✅ C — 프로비저닝된 동시성 + Application Auto Scaling</span></p><p><strong>프로비저닝된 동시성</strong>은 미리 초기화된 실행 환경을 준비하여 콜드 스타트를 제거합니다. Application Auto Scaling을 함께 구성하면 낮에 트래픽이 10배 증가할 때 자동으로 확장(최대 100)하고, 하루 끝에 트래픽이 줄면 자동으로 축소(최소 1)하여 비용을 최적화합니다.</p><p><a href="https://docs.aws.amazon.com/lambda/latest/dg/provisioned-concurrency.html" target="_blank">📎 AWS 공식 문서</a></p>`,
  wrong:`<p><span class="mark-no">❌ A</span> — 동시성 1로 고정하면 트래픽 급증 시 대응 불가하며, DAX 삭제는 성능을 저하시킵니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ B</span> — 예약된 동시성 0은 Lambda 함수 호출을 완전히 차단합니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ D</span> — API Gateway에는 Auto Scaling으로 제어할 수 있는 동시성 개념이 없습니다.</p>`,
  disc:[{ans:'C (100%)',txt:'프로비저닝된 동시성(Provisioned Concurrency)은 콜드 스타트를 방지합니다. Application Auto Scaling과 함께 사용하면 시간대별 트래픽 변화에 자동으로 대응할 수 있습니다. — AWS Lambda 공식 문서'}]
},
{
  n:3,
  en:`A company is adopting AWS CodeDeploy to automate its application deployments for a Java-Apache Tomcat application with an Apache web server. The development team started with a proof of concept, created a deployment group for a developer environment, and performed functional tests within the application. After completion, the team will create additional deployment groups for staging and production.<br><br>The current log level is configured within the Apache settings, but the team wants to change this configuration dynamically when the deployment occurs, so that they can set different log level configurations depending on the deployment group without having a different application revision for each group.<br><br><strong>How can these requirements be met with the LEAST management overhead and without requiring different script versions for each deployment group?</strong>`,
  ko:`한 회사가 Apache 웹서버가 있는 Java-Apache Tomcat 애플리케이션에 대한 애플리케이션 배포를 자동화하기 위해 AWS CodeDeploy를 도입하고 있습니다. 개발팀은 개념 증명으로 시작하여 개발자 환경을 위한 배포 그룹을 만들고 애플리케이션 내에서 기능 테스트를 수행했습니다. 완료 후 팀은 스테이징 및 프로덕션을 위한 추가 배포 그룹을 만들 예정입니다.<br><br>현재 로그 수준은 Apache 설정 내에서 구성되지만, 팀은 배포가 발생할 때 이 구성을 동적으로 변경하여 각 그룹에 대해 다른 애플리케이션 개정 없이 배포 그룹에 따라 다른 로그 수준 구성을 설정하려고 합니다.<br><br><strong>각 배포 그룹에 대해 다른 스크립트 버전을 요구하지 않고도 최소한의 관리 오버헤드로 이러한 요구 사항을 어떻게 충족할 수 있습니까?</strong>`,
  type:'single',
  choices:[
    {k:'A', en:`Tag the Amazon EC2 instances depending on the deployment group. Then place a script into the application revision that calls the metadata service and the EC2 API to identify which deployment group the instance is part of. Use this information to configure the log level settings. Reference the script as part of the AfterInstall lifecycle hook in the appspec.yml file.`, ko:`배포 그룹에 따라 Amazon EC2 인스턴스에 태그를 지정합니다. 그런 다음 메타데이터 서비스와 EC2 API를 호출하여 인스턴스가 속한 배포 그룹을 식별하는 스크립트를 애플리케이션 개정판에 배치합니다. 이 정보를 사용하여 로그 수준 설정을 구성합니다. appspec.yml 파일에서 AfterInstall 라이프사이클 후크의 일부로 스크립트를 참조합니다.`},
    {k:'B', en:`Create a script that uses the CodeDeploy environment variable DEPLOYMENT_GROUP_NAME to identify which deployment group the instance is part of. Use this information to configure the log level settings. Reference this script as part of the BeforeInstall lifecycle hook in the appspec.yml file.`, ko:`CodeDeploy 환경 변수 DEPLOYMENT_GROUP_NAME을 사용하여 인스턴스가 속한 배포 그룹을 식별하는 스크립트를 만듭니다. 이 정보를 사용하여 로그 수준 설정을 구성합니다. appspec.yml 파일에서 BeforeInstall 라이프사이클 후크의 일부로 이 스크립트를 참조합니다.`},
    {k:'C', en:`Create a CodeDeploy custom environment variable for each environment. Then place a script into the application revision that checks this environment variable to identify which deployment group the instance is part of. Use this information to configure the log level settings. Reference this script as part of the ValidateService lifecycle hook in the appspec.yml file.`, ko:`각 환경에 대한 CodeDeploy 사용자 지정 환경 변수를 만듭니다. 그런 다음 인스턴스가 속한 배포 그룹을 식별하기 위해 이 환경 변수를 확인하는 스크립트를 애플리케이션 개정판에 넣습니다. 이 정보를 사용하여 로그 수준 설정을 구성합니다. appspec.yml 파일에서 ValidateService 라이프사이클 후크의 일부로 이 스크립트를 참조합니다.`},
    {k:'D', en:`Create a script that uses the CodeDeploy environment variable DEPLOYMENT_GROUP_ID to identify which deployment group the instance is part of to configure the log level settings. Reference this script as part of the Install lifecycle hook in the appspec.yml file.`, ko:`CodeDeploy 환경 변수 DEPLOYMENT_GROUP_ID를 사용하여 인스턴스가 속한 배포 그룹을 식별하여 로그 수준 설정을 구성하는 스크립트를 만듭니다. appspec.yml 파일에서 Install lifecycle 후크의 일부로 이 스크립트를 참조합니다.`},
  ],
  answer:['B'],
  vote:'73% B',
  explain:`<p><span class="mark-ok">✅ B — DEPLOYMENT_GROUP_NAME + BeforeInstall 후크</span></p><p>CodeDeploy는 <strong>DEPLOYMENT_GROUP_NAME</strong> 환경 변수를 제공하여 현재 배포 그룹 이름을 스크립트에서 바로 사용할 수 있습니다. 단일 스크립트에서 이 변수를 분기하여 각 그룹별 로그 수준을 설정합니다. <code>BeforeInstall</code> 후크에서 실행하면 설치 전에 Apache 설정을 사전 구성할 수 있습니다.</p><p><a href="https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure-hooks.html" target="_blank">📎 AWS 공식 문서</a></p>`,
  wrong:`<p><span class="mark-no">❌ D</span> — CodeDeploy AppSpec에서 <code>Install</code> 라이프사이클 이벤트는 스크립팅할 수 없습니다. (Start, Install, TestTraffic, AllowTraffic, End는 스크립트 불가)</p><p style="margin-top:8px;"><span class="mark-no">❌ A, C</span> — "애플리케이션 개정판에 스크립트 배치"는 각 그룹마다 다른 개정판이 필요하다는 것을 의미하여 요구사항에 위배됩니다.</p>`,
  disc:[{ans:'B (73%)',txt:'AWS 공식 블로그에서 정확히 이 시나리오를 설명합니다: DEPLOYMENT_GROUP_NAME을 사용하여 배포 그룹별 Apache 로그 수준 설정. BeforeInstall 후크에서 실행. — AWS DevOps Blog'}]
},
{
  n:4,
  en:`A company requires its developers to tag all Amazon Elastic Block Store (Amazon EBS) volumes in an account to indicate a desired backup frequency. This requirement includes EBS volumes that do not require backups. The company uses custom tags named Backup_Frequency that have values of none, daily, or weekly that correspond to the desired backup frequency. An audit finds that developers are occasionally not tagging the EBS volumes.<br><br>A DevOps engineer needs to ensure that all EBS volumes always have the Backup_Frequency tag so that the company can perform backups at least weekly unless a different value is specified.<br><br><strong>Which solution will meet these requirements?</strong>`,
  ko:`한 회사는 개발자가 계정의 모든 Amazon EBS(Elastic Block Store) 볼륨에 태그를 지정하여 원하는 백업 빈도를 표시하도록 요구합니다. 이 요구 사항에는 백업이 필요하지 않은 EBS 볼륨이 포함됩니다. 회사는 원하는 백업 빈도에 해당하는 none, daily, weekly 값을 갖는 Backup_Frequency라는 사용자 지정 태그를 사용합니다. 감사 결과 개발자가 가끔 EBS 볼륨에 태그를 지정하지 않는 것으로 나타났습니다.<br><br>DevOps 엔지니어는 다른 값이 지정되지 않는 한 회사에서 최소한 주 1회 백업을 수행할 수 있도록 모든 EBS 볼륨에 항상 Backup_Frequency 태그가 있는지 확인해야 합니다.<br><br><strong>어떤 솔루션이 이러한 요구 사항을 충족합니까?</strong>`,
  type:'single',
  choices:[
    {k:'A', en:`Set up AWS Config in the account. Create a custom rule that returns a compliance failure for all Amazon EC2 resources that do not have a Backup Frequency tag applied. Configure a remediation action that uses a custom AWS Systems Manager Automation runbook to apply the Backup_Frequency tag with a value of weekly.`, ko:`계정에서 AWS Config를 설정합니다. Backup Frequency 태그가 적용되지 않은 모든 Amazon EC2 리소스에 대해 규정 준수 실패를 반환하는 사용자 지정 규칙을 만듭니다. 사용자 지정 AWS Systems Manager Automation 런북을 사용하여 weekly 값으로 Backup_Frequency 태그를 적용하는 수정 작업을 구성합니다.`},
    {k:'B', en:`Set up AWS Config in the account. Use a managed rule that returns a compliance failure for EC2::Volume resources that do not have a Backup Frequency tag applied. Configure a remediation action that uses a custom AWS Systems Manager Automation runbook to apply the Backup_Frequency tag with a value of weekly.`, ko:`계정에서 AWS Config를 설정합니다. Backup Frequency 태그가 적용되지 않은 EC2::Volume 리소스에 대해 규정 준수 실패를 반환하는 관리형 규칙을 사용합니다. 사용자 지정 AWS Systems Manager Automation 런북을 사용하여 weekly 값으로 Backup_Frequency 태그를 적용하는 수정 작업을 구성합니다.`},
    {k:'C', en:`Turn on AWS CloudTrail in the account. Create an Amazon EventBridge rule that reacts to EBS CreateVolume events. Configure a custom AWS Systems Manager Automation runbook to apply the Backup_Frequency tag with a value of weekly. Specify the runbook as the target of the rule.`, ko:`계정에서 AWS CloudTrail을 켭니다. EBS CreateVolume 이벤트에 반응하는 Amazon EventBridge 규칙을 만듭니다. 사용자 지정 AWS Systems Manager Automation 런북을 구성하여 weekly 값으로 Backup_Frequency 태그를 적용합니다. 런북을 규칙의 대상으로 지정합니다.`},
    {k:'D', en:`Turn on AWS CloudTrail in the account. Create an Amazon EventBridge rule that reacts to EBS CreateVolume events or EBS ModifyVolume events. Configure a custom AWS Systems Manager Automation runbook to apply the Backup_Frequency tag with a value of weekly. Specify the runbook as the target of the rule.`, ko:`계정에서 AWS CloudTrail을 켭니다. EBS CreateVolume 이벤트 또는 EBS ModifyVolume 이벤트에 반응하는 Amazon EventBridge 규칙을 만듭니다. 사용자 지정 AWS Systems Manager Automation 런북을 구성하여 weekly 값으로 Backup_Frequency 태그를 적용합니다. 런북을 규칙의 대상으로 지정합니다.`},
  ],
  answer:['B'],
  vote:'95% B',
  explain:`<p><span class="mark-ok">✅ B — AWS Config 관리형 규칙(required-tags) + 사용자 지정 SSM 런북</span></p><p>AWS Config의 <strong>관리형 규칙 required-tags</strong>는 <code>EC2::Volume</code> 리소스 유형을 대상으로 특정 태그 존재 여부를 검사합니다. 비준수 볼륨에 대해 사용자 지정 SSM Automation 런북으로 자동 수정(weekly 태그 적용)을 구성합니다. 관리형 규칙은 EC2 볼륨에만 정확히 적용되어 불필요한 오버헤드가 없습니다.</p><p><a href="https://docs.aws.amazon.com/config/latest/developerguide/required-tags.html" target="_blank">📎 AWS 공식 문서</a></p>`,
  wrong:`<p><span class="mark-no">❌ A</span> — 사용자 지정 규칙은 <em>모든 EC2 리소스</em>(인스턴스, ELB 등 포함)에 적용되어 볼륨 이외의 리소스에도 불필요하게 규정 준수 오류를 반환합니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ C, D</span> — CloudTrail/EventBridge는 새로 생성된 볼륨에만 반응하며, 기존의 태그 없는 볼륨은 탐지하지 못합니다. AWS Config는 기존 리소스도 지속적으로 평가합니다.</p>`,
  disc:[{ans:'B (95%)',txt:'AWS Config required-tags 관리형 규칙은 EC2::Volume 리소스 유형을 지원합니다. 단, AWS-SetRequiredTags SSM 문서는 이 규칙의 수정에 사용 불가하므로 사용자 지정 런북이 필요합니다. — AWS Config 문서'}]
},
{
  n:5,
  en:`A company is using an Amazon Aurora cluster as the data store for its application. The Aurora cluster is configured with a single DB instance. The application performs read and write operations on the database by using the cluster's instance endpoint.<br><br>The company has scheduled an update to be applied to the cluster during an upcoming maintenance window. The cluster must remain available with the least possible interruption during the maintenance window.<br><br><strong>What should a DevOps engineer do to meet these requirements?</strong>`,
  ko:`한 회사가 애플리케이션의 데이터 저장소로 Amazon Aurora 클러스터를 사용하고 있습니다. Aurora 클러스터는 단일 DB 인스턴스로 구성되어 있습니다. 애플리케이션은 클러스터의 인스턴스 엔드포인트를 사용하여 데이터베이스에서 읽기 및 쓰기 작업을 수행합니다.<br><br>회사는 다가올 유지 관리 기간 동안 클러스터에 적용할 업데이트를 예약했습니다. 클러스터는 유지 관리 기간 동안 가능한 한 최소한의 중단으로 사용 가능해야 합니다.<br><br><strong>DevOps 엔지니어는 이러한 요구 사항을 충족하기 위해 무엇을 해야 합니까?</strong>`,
  type:'single',
  choices:[
    {k:'A', en:`Add a reader instance to the Aurora cluster. Update the application to use the Aurora cluster endpoint for write operations. Update the Aurora cluster's reader endpoint for reads.`, ko:`Aurora 클러스터에 리더 인스턴스를 추가합니다. 쓰기 작업에 Aurora 클러스터 엔드포인트를 사용하도록 애플리케이션을 업데이트합니다. 읽기에 Aurora 클러스터의 리더 엔드포인트를 업데이트합니다.`},
    {k:'B', en:`Add a reader instance to the Aurora cluster. Create a custom ANY endpoint for the cluster. Update the application to use the Aurora cluster's custom ANY endpoint for read and write operations.`, ko:`Aurora 클러스터에 리더 인스턴스를 추가합니다. 클러스터에 대한 사용자 정의 ANY 엔드포인트를 만듭니다. 읽기 및 쓰기 작업에 Aurora 클러스터의 사용자 정의 ANY 엔드포인트를 사용하도록 애플리케이션을 업데이트합니다.`},
    {k:'C', en:`Turn on the Multi-AZ option on the Aurora cluster. Update the application to use the Aurora cluster endpoint for write operations. Update the Aurora cluster's reader endpoint for reads.`, ko:`Aurora 클러스터에서 Multi-AZ 옵션을 켭니다. 쓰기 작업에 Aurora 클러스터 엔드포인트를 사용하도록 애플리케이션을 업데이트합니다. 읽기에 Aurora 클러스터의 리더 엔드포인트를 업데이트합니다.`},
    {k:'D', en:`Turn on the Multi-AZ option on the Aurora cluster. Create a custom ANY endpoint for the cluster. Update the application to use the Aurora cluster's custom ANY endpoint for read and write operations.`, ko:`Aurora 클러스터에서 Multi-AZ 옵션을 켭니다. 클러스터에 대한 사용자 지정 ANY 엔드포인트를 만듭니다. 읽기 및 쓰기 작업에 Aurora 클러스터의 사용자 지정 ANY 엔드포인트를 사용하도록 애플리케이션을 업데이트합니다.`},
  ],
  answer:['A'],
  vote:'77% A',
  explain:`<p><span class="mark-ok">✅ A — 리더 인스턴스 추가 + 클러스터/리더 엔드포인트 사용</span></p><p>리더 인스턴스를 추가하면 유지 관리 중에 기본 인스턴스가 업데이트될 때 <strong>리더 인스턴스가 자동으로 기본 인스턴스로 승격</strong>되어 서비스 중단을 최소화합니다. 쓰기에는 클러스터 엔드포인트(항상 현재 기본 인스턴스 가리킴), 읽기에는 리더 엔드포인트를 사용합니다. 이는 기존 Aurora 클러스터를 다중 AZ로 만드는 방법이기도 합니다.</p><p><a href="https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Concepts.AuroraHighAvailability.html" target="_blank">📎 AWS 공식 문서</a></p>`,
  wrong:`<p><span class="mark-no">❌ C, D</span> — Amazon Aurora에는 기존 클러스터에서 직접 활성화할 수 있는 "Multi-AZ 옵션"이 없습니다. 다중 AZ는 리더 인스턴스 추가로 달성합니다(옵션 A와 동일).</p><p style="margin-top:8px;"><span class="mark-no">❌ B, D</span> — Aurora는 사용자 정의 "ANY" 엔드포인트 유형을 지원하지 않습니다. 사용자 정의 엔드포인트는 읽기/쓰기 구분 없이 특정 인스턴스 그룹을 지정합니다.</p>`,
  disc:[{ans:'A (77%)',txt:'"새 리더 인스턴스를 추가하고 다른 AZ를 지정하여 기존 Aurora 클러스터를 다중 AZ 클러스터로 만들 수 있습니다." — AWS Aurora 공식 문서'}]
},
{
  n:6,
  en:`A company must encrypt all AMIs that the company shares across accounts. A DevOps engineer has access to a source account where an unencrypted custom AMI has been built. The DevOps engineer also has access to a target account where an Amazon EC2 Auto Scaling group will launch EC2 instances from the AMI. The DevOps engineer must share the AMI with the target account.<br><br>The company has created an AWS Key Management Service (AWS KMS) key in the source account.<br><br><strong>Which additional steps should the DevOps engineer perform to meet the requirements? (Choose three.)</strong>`,
  ko:`회사는 계정 간에 공유하는 모든 AMI를 암호화해야 합니다. DevOps 엔지니어는 암호화되지 않은 사용자 지정 AMI가 빌드된 소스 계정에 액세스할 수 있습니다. DevOps 엔지니어는 또한 Amazon EC2 Auto Scaling 그룹이 AMI에서 EC2 인스턴스를 시작할 대상 계정에 액세스할 수 있습니다. DevOps 엔지니어는 대상 계정과 AMI를 공유해야 합니다.<br><br>회사는 소스 계정에 AWS KMS(Key Management Service) 키를 생성했습니다.<br><br><strong>DevOps 엔지니어는 요구 사항을 충족하기 위해 어떤 추가 단계를 수행해야 합니까? (세 가지를 선택하십시오.)</strong>`,
  type:'multi',
  multiCount:3,
  choices:[
    {k:'A', en:`In the source account, copy the unencrypted AMI to an encrypted AMI. Specify the KMS key in the copy action.`, ko:`소스 계정에서 암호화되지 않은 AMI를 암호화된 AMI로 복사합니다. 복사 작업에서 KMS 키를 지정합니다.`},
    {k:'B', en:`In the source account, copy the unencrypted AMI to an encrypted AMI. Specify the default Amazon Elastic Block Store (Amazon EBS) encryption key in the copy action.`, ko:`소스 계정에서 암호화되지 않은 AMI를 암호화된 AMI로 복사합니다. 복사 작업에서 기본 Amazon EBS 암호화 키를 지정합니다.`},
    {k:'C', en:`In the source account, create a KMS grant that delegates permissions to the Auto Scaling group service-linked role in the target account.`, ko:`소스 계정에서 대상 계정의 Auto Scaling 그룹 서비스 연결 역할에 권한을 위임하는 KMS 권한 부여를 만듭니다.`},
    {k:'D', en:`In the source account, modify the key policy to give the target account permissions to create a grant. In the target account, create a KMS grant that delegates permissions to the Auto Scaling group service-linked role.`, ko:`소스 계정에서 키 정책을 수정하여 대상 계정에 권한 부여를 생성할 수 있는 권한을 부여합니다. 대상 계정에서 Auto Scaling 그룹 서비스 연결 역할에 권한을 위임하는 KMS 권한을 생성합니다.`},
    {k:'E', en:`In the source account, share the unencrypted AMI with the target account.`, ko:`소스 계정에서 암호화되지 않은 AMI를 대상 계정과 공유합니다.`},
    {k:'F', en:`In the source account, share the encrypted AMI with the target account.`, ko:`소스 계정에서 암호화된 AMI를 대상 계정과 공유합니다.`},
  ],
  answer:['A','D','F'],
  vote:'96% ADF',
  explain:`<p><span class="mark-ok">✅ A</span>: 소스 계정에서 생성된 KMS 키를 사용하여 암호화되지 않은 AMI를 암호화합니다.</p><p style="margin-top:8px;"><span class="mark-ok">✅ D</span>: 소스 계정의 KMS 키 정책을 수정하여 대상 계정이 KMS 권한 부여를 생성할 수 있게 합니다. 대상 계정에서는 Auto Scaling 서비스 연결 역할이 KMS 키를 사용할 수 있도록 권한 부여를 생성합니다.</p><p style="margin-top:8px;"><span class="mark-ok">✅ F</span>: 암호화된 AMI를 대상 계정과 공유합니다(암호화되지 않은 AMI 공유 불가).</p><p><a href="https://docs.aws.amazon.com/autoscaling/ec2/userguide/key-policy-requirements-EBS-encryption.html" target="_blank">📎 AWS 공식 문서</a></p>`,
  wrong:`<p><span class="mark-no">❌ B</span> — 회사가 직접 생성한 KMS 키를 사용해야 하며, 기본 EBS 암호화 키를 사용하면 교차 계정 공유 시 권한 관리가 복잡해집니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ C</span> — 소스 계정에서 다른 계정의 서비스 연결 역할에 대한 KMS 권한 부여를 직접 생성할 수 없습니다. 대상 계정에서 자체 서비스 연결 역할에 권한 부여를 생성해야 합니다.</p>`,
  disc:[{ans:'ADF (96%)',txt:'교차 계정 암호화 AMI 공유: 1) 소스에서 KMS로 AMI 암호화 2) KMS 키 정책에서 대상 계정 권한 부여 허용 3) 대상 계정에서 Auto Scaling 역할에 권한 부여 4) 암호화된 AMI 공유. — AWS EC2 Auto Scaling 문서'}]
},
{
  n:7,
  en:`A company uses AWS CodePipeline pipelines to automate releases of its application. A typical pipeline consists of three stages: build, test, and deployment. The company has been using a separate AWS CodeBuild project to run scripts for each stage. However, the company now wants to use AWS CodeDeploy to handle the deployment stage of the pipelines.<br><br>The company has packaged the application as an RPM package and must deploy the application to a fleet of Amazon EC2 instances. The EC2 instances are in an EC2 Auto Scaling group and are launched from a common AMI.<br><br><strong>Which combination of steps should a DevOps engineer perform to meet these requirements? (Choose two.)</strong>`,
  ko:`한 회사에서 AWS CodePipeline 파이프라인을 사용하여 애플리케이션 릴리스를 자동화합니다. 일반적인 파이프라인은 빌드, 테스트, 배포의 세 단계로 구성됩니다. 이 회사는 각 단계에 대한 스크립트를 실행하기 위해 별도의 AWS CodeBuild 프로젝트를 사용했습니다. 그러나 이제 AWS CodeDeploy를 사용하여 파이프라인의 배포 단계를 처리하려고 합니다.<br><br>회사는 애플리케이션을 RPM 패키지로 패키징했으며 Amazon EC2 인스턴스 플릿에 배포해야 합니다. EC2 인스턴스는 EC2 Auto Scaling 그룹에 있으며 공통 AMI에서 시작됩니다.<br><br><strong>DevOps 엔지니어는 이러한 요구 사항을 충족하기 위해 어떤 단계 조합을 수행해야 합니까? (두 가지를 선택하십시오.)</strong>`,
  type:'multi',
  multiCount:2,
  choices:[
    {k:'A', en:`Create a new version of the common AMI with the CodeDeploy agent installed. Update the IAM role of the EC2 instances to allow access to CodeDeploy.`, ko:`CodeDeploy 에이전트가 설치된 공통 AMI의 새 버전을 만듭니다. EC2 인스턴스의 IAM 역할을 업데이트하여 CodeDeploy에 대한 액세스를 허용합니다.`},
    {k:'B', en:`Create a new version of the common AMI with the CodeDeploy agent installed. Create an AppSpec file that contains application deployment scripts and grants access to CodeDeploy.`, ko:`CodeDeploy 에이전트가 설치된 공통 AMI의 새 버전을 만듭니다. 애플리케이션 배포 스크립트를 포함하고 CodeDeploy에 대한 액세스 권한을 부여하는 AppSpec 파일을 만듭니다.`},
    {k:'C', en:`Create an application in CodeDeploy. Configure an in-place deployment type. Specify the Auto Scaling group as the deployment target. Add a step to the CodePipeline pipeline to use EC2 Image Builder to create a new AMI. Configure CodeDeploy to deploy the newly created AMI.`, ko:`CodeDeploy에서 애플리케이션을 만듭니다. 인플레이스 배포 유형을 구성합니다. 배포 대상으로 Auto Scaling 그룹을 지정합니다. EC2 Image Builder를 사용하여 새 AMI를 만드는 CodePipeline 파이프라인에 단계를 추가합니다. 새로 만든 AMI를 배포하도록 CodeDeploy를 구성합니다.`},
    {k:'D', en:`Create an application in CodeDeploy. Configure an in-place deployment type. Specify the Auto Scaling group as the deployment target. Update the CodePipeline pipeline to use the CodeDeploy action to deploy the application.`, ko:`CodeDeploy에서 애플리케이션을 만듭니다. 인플레이스 배포 유형을 구성합니다. 배포 대상으로 Auto Scaling 그룹을 지정합니다. CodePipeline 파이프라인을 업데이트하여 CodeDeploy 작업을 사용하여 애플리케이션을 배포합니다.`},
    {k:'E', en:`Create an application in CodeDeploy. Configure an in-place deployment type. Specify the EC2 instances that are launched from the common AMI as the deployment target. Update the CodePipeline pipeline to use the CodeDeploy action to deploy the application.`, ko:`CodeDeploy에서 애플리케이션을 만듭니다. 인플레이스 배포 유형을 구성합니다. 배포 대상으로 공통 AMI에서 시작된 EC2 인스턴스를 지정합니다. CodePipeline 파이프라인을 업데이트하여 CodeDeploy 작업을 사용하여 애플리케이션을 배포합니다.`},
  ],
  answer:['A','D'],
  vote:'100% AD',
  explain:`<p><span class="mark-ok">✅ A</span>: CodeDeploy가 EC2 인스턴스와 통신하려면 인스턴스에 <strong>CodeDeploy 에이전트</strong>가 설치되어 있어야 하고, EC2의 IAM 역할에 CodeDeploy 및 S3 접근 권한이 필요합니다. 공통 AMI에 에이전트를 미리 설치합니다.</p><p style="margin-top:8px;"><span class="mark-ok">✅ D</span>: CodeDeploy에서 인플레이스 배포 애플리케이션을 만들고, <strong>Auto Scaling 그룹을 배포 대상</strong>으로 지정합니다. CodePipeline에 CodeDeploy 액션을 추가합니다.</p><p><a href="https://docs.aws.amazon.com/codedeploy/latest/userguide/integrations-aws-auto-scaling.html" target="_blank">📎 AWS 공식 문서</a></p>`,
  wrong:`<p><span class="mark-no">❌ B</span> — AppSpec 파일은 배포 지침을 정의하지만 CodeDeploy에 대한 "액세스 권한 부여" 기능은 없습니다. IAM 역할로 권한을 관리해야 합니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ C</span> — RPM 배포 시마다 새 AMI를 만드는 것은 불필요하고 비효율적입니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ E</span> — ASG의 인스턴스를 개별 지정하는 것은 확장성이 없습니다. ASG 자체를 대상으로 지정해야 합니다.</p>`,
  disc:[{ans:'AD (100%)',txt:'CodeDeploy로 EC2 배포 시 필수 사항: 1) EC2에 CodeDeploy 에이전트 설치 2) EC2 IAM 역할에 S3/CodeDeploy 접근 권한 3) CodeDeploy 애플리케이션 + 배포 그룹(ASG 타겟) 생성 4) CodePipeline에 CodeDeploy 액션 추가.'}]
},
{
  n:8,
  en:`A company's security team requires that all external Application Load Balancers (ALBs) and Amazon API Gateway APIs are associated with AWS WAF web ACLs. The company has hundreds of AWS accounts, all of which are included in a single organization in AWS Organizations. The company has configured AWS Config for the organization. During an audit, the company finds some externally facing ALBs that are not associated with AWS WAF web ACLs.<br><br><strong>Which combination of steps should a DevOps engineer take to prevent future violations? (Choose two.)</strong>`,
  ko:`한 회사의 보안팀은 모든 외부 ALB(Application Load Balancer)와 Amazon API Gateway API가 AWS WAF 웹 ACL과 연결되어야 한다고 요구합니다. 회사에는 수백 개의 AWS 계정이 있으며, 모두 AWS Organizations의 단일 조직에 포함되어 있습니다. 회사는 조직에 대한 AWS Config를 구성했습니다. 감사 중에 AWS WAF 웹 ACL과 연결되지 않은 외부 ALB를 발견했습니다.<br><br><strong>DevOps 엔지니어는 향후 위반을 방지하기 위해 어떤 단계 조합을 취해야 합니까? (두 가지를 선택하세요.)</strong>`,
  type:'multi',
  multiCount:2,
  choices:[
    {k:'A', en:`Delegate AWS Firewall Manager to a security account.`, ko:`AWS Firewall Manager를 보안 계정에 위임합니다.`},
    {k:'B', en:`Delegate Amazon GuardDuty to a security account.`, ko:`Amazon GuardDuty를 보안 계정에 위임합니다.`},
    {k:'C', en:`Create an AWS Firewall Manager policy to attach AWS WAF web ACLs to any newly created ALBs and API Gateway APIs.`, ko:`새로 생성된 ALB 및 API Gateway API에 AWS WAF 웹 ACL을 연결하기 위해 AWS Firewall Manager 정책을 생성합니다.`},
    {k:'D', en:`Create an Amazon GuardDuty policy to attach AWS WAF web ACLs to any newly created ALBs and API Gateway APIs.`, ko:`새로 생성된 ALB 및 API Gateway API에 AWS WAF 웹 ACL을 연결하기 위해 Amazon GuardDuty 정책을 생성합니다.`},
    {k:'E', en:`Configure an AWS Config managed rule to attach AWS WAF web ACLs to any newly created ALBs and API Gateway APIs.`, ko:`새로 생성된 ALB 및 API Gateway API에 AWS WAF 웹 ACL을 연결하도록 AWS Config 관리 규칙을 구성합니다.`},
  ],
  answer:['A','C'],
  vote:'96% AC',
  explain:`<p><span class="mark-ok">✅ A</span>: AWS Firewall Manager를 사용하려면 먼저 <strong>보안 계정에 위임(delegate)</strong>해야 합니다. 이는 필수 전제 조건입니다.</p><p style="margin-top:8px;"><span class="mark-ok">✅ C</span>: Firewall Manager 정책을 생성하면 조직 전체의 모든 계정에서 새로 생성되는 ALB/API Gateway에 <strong>자동으로 WAF 웹 ACL을 연결</strong>합니다. 비준수 리소스 자동 수정도 지원합니다.</p><p><a href="https://docs.aws.amazon.com/waf/latest/developerguide/waf-policies.html" target="_blank">📎 AWS 공식 문서</a></p>`,
  wrong:`<p><span class="mark-no">❌ B, D</span> — GuardDuty는 위협 탐지 서비스이며, WAF 웹 ACL 연결 정책을 생성하는 기능이 없습니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ E</span> — AWS Config 규칙은 준수 여부를 모니터링하고 알림을 제공하지만, WAF 웹 ACL을 자동으로 연결하는 직접적인 수정 기능은 없습니다(Lambda/SSM을 통한 별도 수정 필요). Firewall Manager가 이 목적에 더 적합합니다.</p>`,
  disc:[{ans:'AC (96%)',txt:'AWS Firewall Manager는 WAF, Shield, Security Groups를 조직 전체에 중앙에서 관리하는 서비스입니다. 필수 전제 조건: AWS Organizations 활성화, Config 활성화, Firewall Manager 관리자 계정 위임.'}]
},
{
  n:9,
  en:`A company uses AWS Key Management Service (AWS KMS) keys and manual key rotation to meet regulatory compliance requirements. The security team wants to be notified when any keys have not been rotated after 90 days.<br><br><strong>Which solution will accomplish this?</strong>`,
  ko:`한 회사에서 규정 준수 요구 사항을 충족하기 위해 AWS KMS(Key Management Service) 키와 수동 키 로테이션을 사용합니다. 보안 팀은 90일 후에도 키가 로테이션되지 않은 경우 알림을 받고 싶어합니다.<br><br><strong>어떤 솔루션이 이를 달성합니까?</strong>`,
  type:'single',
  choices:[
    {k:'A', en:`Configure AWS KMS to publish to an Amazon Simple Notification Service (Amazon SNS) topic when keys are more than 90 days old.`, ko:`키가 90일 이상 지난 경우 Amazon SNS 토픽에 게시하도록 AWS KMS를 구성합니다.`},
    {k:'B', en:`Configure an Amazon EventBridge event to launch an AWS Lambda function to call the AWS Trusted Advisor API and publish to an Amazon Simple Notification Service (Amazon SNS) topic.`, ko:`AWS Lambda 함수를 시작하여 AWS Trusted Advisor API를 호출하고 Amazon SNS 토픽에 게시하도록 Amazon EventBridge 이벤트를 구성합니다.`},
    {k:'C', en:`Develop an AWS Config custom rule that publishes to an Amazon Simple Notification Service (Amazon SNS) topic when keys are more than 90 days old.`, ko:`키가 90일 이상 경과한 경우 Amazon SNS 토픽에 게시하는 AWS Config 사용자 지정 규칙을 개발합니다.`},
    {k:'D', en:`Configure AWS Security Hub to publish to an Amazon Simple Notification Service (Amazon SNS) topic when keys are more than 90 days old.`, ko:`키가 90일 이상 경과한 경우 Amazon SNS 토픽에 게시하도록 AWS Security Hub를 구성합니다.`},
  ],
  answer:['C'],
  vote:'100% C',
  explain:`<p><span class="mark-ok">✅ C — AWS Config 사용자 지정 규칙</span></p><p>KMS 키의 마지막 로테이션 날짜를 기준으로 90일 초과 여부를 평가하는 <strong>사용자 지정 Config 규칙</strong>을 개발합니다. 비준수 키 발견 시 SNS 토픽에 게시하는 수정 작업을 구성합니다. AWS Config 관리형 규칙 <code>access-keys-rotated</code>는 IAM 액세스 키용이며 KMS 키에는 적용되지 않으므로 사용자 지정 규칙이 필요합니다.</p><p><a href="https://docs.aws.amazon.com/config/latest/developerguide/access-keys-rotated.html" target="_blank">📎 AWS 공식 문서</a></p>`,
  wrong:`<p><span class="mark-no">❌ A</span> — AWS KMS는 키 연령 기반 자동 SNS 게시 기능을 제공하지 않습니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ B</span> — AWS Trusted Advisor에는 KMS 키 로테이션 기간을 확인하는 검사가 없습니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ D</span> — Security Hub는 Config/GuardDuty 발견 사항을 집계하는 서비스이며, KMS 키 연령을 직접 모니터링하는 기능이 없습니다.</p>`,
  disc:[{ans:'C (100%)',txt:'AWS Config 사용자 지정 규칙(Lambda 기반): KMS DescribeKey API로 키 생성일 및 마지막 로테이션 날짜를 확인하여 90일 초과 시 NON_COMPLIANT 반환 후 SNS 알림.'}]
},
{
  n:10,
  en:`A security review has identified that an AWS CodeBuild project is downloading a database population script from an Amazon S3 bucket using an unauthenticated request. The security team does not allow unauthenticated requests to S3 buckets for this project.<br><br><strong>How can this issue be corrected in the MOST secure manner?</strong>`,
  ko:`보안 검토에서 AWS CodeBuild 프로젝트가 인증되지 않은 요청을 사용하여 Amazon S3 버킷에서 데이터베이스 채우기 스크립트를 다운로드하고 있다는 사실이 확인되었습니다. 보안팀은 이 프로젝트에 대해 S3 버킷에 대한 인증되지 않은 요청을 허용하지 않습니다.<br><br><strong>이 문제를 가장 안전한 방식으로 어떻게 수정할 수 있습니까?</strong>`,
  type:'single',
  choices:[
    {k:'A', en:`Add the bucket name to the AllowedBuckets section of the CodeBuild project settings. Update the build spec to use the AWS CLI to download the database population script.`, ko:`CodeBuild 프로젝트 설정의 AllowedBuckets 섹션에 버킷 이름을 추가합니다. AWS CLI를 사용하여 데이터베이스 채우기 스크립트를 다운로드하도록 빌드 사양을 업데이트합니다.`},
    {k:'B', en:`Modify the S3 bucket settings to enable HTTPS basic authentication and specify a token. Update the build spec to use cURL to pass the token and download the database population script.`, ko:`S3 버킷 설정을 수정하여 HTTPS 기본 인증을 활성화하고 토큰을 지정합니다. 빌드 사양을 업데이트하여 cURL을 사용하여 토큰을 전달하고 데이터베이스 채우기 스크립트를 다운로드합니다.`},
    {k:'C', en:`Remove unauthenticated access from the S3 bucket with a bucket policy. Modify the service role for the CodeBuild project to include Amazon S3 access. Use the AWS CLI to download the database population script.`, ko:`버킷 정책을 사용하여 S3 버킷에서 인증되지 않은 액세스를 제거합니다. CodeBuild 프로젝트의 서비스 역할을 수정하여 Amazon S3 액세스를 포함합니다. AWS CLI를 사용하여 데이터베이스 채우기 스크립트를 다운로드합니다.`},
    {k:'D', en:`Remove unauthenticated access from the S3 bucket with a bucket policy. Use the AWS CLI to download the database population script using an IAM access key and a secret access key.`, ko:`버킷 정책을 사용하여 S3 버킷에서 인증되지 않은 액세스를 제거합니다. AWS CLI를 사용하여 IAM 액세스 키와 비밀 액세스 키를 사용하여 데이터베이스 채우기 스크립트를 다운로드합니다.`},
  ],
  answer:['C'],
  vote:'100% C',
  explain:`<p><span class="mark-ok">✅ C — 버킷 정책으로 익명 접근 제거 + CodeBuild 서비스 역할에 S3 권한 추가</span></p><p>가장 안전한 방식은 <strong>서비스 역할(IAM 역할)</strong>을 사용하는 것입니다. 버킷 정책으로 익명 접근을 차단하고, CodeBuild 서비스 역할에 S3 읽기 권한을 부여합니다. AWS CLI는 서비스 역할의 임시 자격 증명을 자동으로 사용하여 인증된 요청을 수행합니다. 장기 자격 증명(액세스 키)이 아닌 임시 자격 증명을 사용하므로 보안 위험이 최소화됩니다.</p><p><a href="https://docs.aws.amazon.com/codebuild/latest/userguide/setting-up-service-role.html" target="_blank">📎 AWS 공식 문서</a></p>`,
  wrong:`<p><span class="mark-no">❌ D</span> — IAM 액세스 키와 비밀 액세스 키(장기 자격 증명)를 코드/환경 변수에 저장하는 것은 보안 위험이 있습니다. 서비스 역할의 임시 자격 증명이 더 안전합니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ A</span> — CodeBuild 프로젝트 설정에 "AllowedBuckets" 섹션은 존재하지 않습니다.</p><p style="margin-top:8px;"><span class="mark-no">❌ B</span> — Amazon S3는 HTTPS 기본 인증을 지원하지 않습니다.</p>`,
  disc:[{ans:'C (100%)',txt:'AWS 보안 모범 사례: IAM 역할(서비스 역할)을 사용하여 장기 자격 증명 노출을 방지합니다. CodeBuild는 실행 시 서비스 역할의 임시 자격 증명을 자동으로 AWS CLI에 제공합니다.'}]
}
];
