window.QS_SET23 = [
{
  n: 221,
  en: `A company manages multiple AWS accounts by using AWS Organizations with OUs for the different business divisions. The company is updating their corporate network to use new IP address ranges. The company has 10 Amazon S3 buckets in different AWS accounts. The S3 buckets store reports for the different divisions. The S3 bucket configurations allow only private corporate network IP addresses to access the S3 buckets.<br><br>A DevOps engineer needs to change the range of IP addresses that have permission to access the contents of the S3 buckets. The DevOps engineer also needs to revoke the permissions of two OUs in the company.<br><br>Which solution will meet these requirements?`,
  ko: `한 회사가 다양한 사업부별로 OU가 있는 AWS Organizations를 사용하여 여러 AWS 계정을 관리합니다. 이 회사는 새로운 IP 주소 범위를 사용하도록 회사 네트워크를 업데이트하고 있습니다. 이 회사는 다양한 AWS 계정에 Amazon S3 버킷 10개를 가지고 있습니다. S3 버킷은 다양한 사업부에 대한 보고서를 저장합니다. S3 버킷 구성은 개인 회사 네트워크 IP 주소만 S3 버킷에 액세스할 수 있도록 허용합니다.<br><br>DevOps 엔지니어는 S3 버킷의 콘텐츠에 액세스할 수 있는 권한이 있는 IP 주소 범위를 변경해야 합니다. 또한 DevOps 엔지니어는 회사의 두 OU에 대한 권한을 취소해야 합니다.<br><br>어떤 솔루션이 이러한 요구 사항을 충족할까요?`,
  type: 'single',
  choices: [
    { k:'A', en:`Create a new SCP that has two statements, one that allows access to the new range of IP addresses for all the S3 buckets and one that denies access to the old range of IP addresses for all the S3 buckets. Set a permissions boundary for the OrganizationAccountAccessRole role in the two OUs to deny access to the S3 buckets.`, ko:`두 개의 문장이 있는 새 SCP를 만듭니다. 하나는 모든 S3 버킷에 대한 새로운 IP 주소 범위에 대한 액세스를 허용하고 다른 하나는 모든 S3 버킷에 대한 이전 IP 주소 범위에 대한 액세스를 거부합니다. 두 OU에서 OrganizationAccountAccessRole 역할에 대한 권한 경계를 설정하여 S3 버킷에 대한 액세스를 거부합니다.` },
    { k:'B', en:`Create a new SCP that has a statement that allows only the new range of IP addresses to access the S3 buckets. Create another SCP that denies access to the S3 buckets. Attach the second SCP to the two OUs.`, ko:`S3 버킷에 액세스할 수 있는 새로운 IP 주소 범위만 허용하는 문장이 있는 새 SCP를 만듭니다. S3 버킷에 대한 액세스를 거부하는 또 다른 SCP를 만듭니다. 두 번째 SCP를 두 OU에 연결합니다.` },
    { k:'C', en:`On all the S3 buckets, configure resource-based policies that allow only the new range of IP addresses to access the S3 buckets. Create a new SCP that denies access to the S3 buckets. Attach the SCP to the two OUs.`, ko:`모든 S3 버킷에서 새 IP 주소 범위만 S3 버킷에 액세스할 수 있도록 허용하는 리소스 기반 정책을 구성합니다. S3 버킷에 대한 액세스를 거부하는 새 SCP를 만듭니다. SCP를 두 OU에 연결합니다.` },
    { k:'D', en:`On all the S3 buckets, configure resource-based policies that allow only the new range of IP addresses to access the S3 buckets. Set a permissions boundary for the OrganizationAccountAccessRole role in the two OUs to deny access to the S3 buckets.`, ko:`모든 S3 버킷에서 새 IP 주소 범위만 S3 버킷에 액세스할 수 있도록 허용하는 리소스 기반 정책을 구성합니다. 두 OU에서 OrganizationAccountAccessRole 역할에 대한 권한 경계를 설정하여 S3 버킷에 대한 액세스를 거부합니다.` },
  ],
  answer: ['C'],
  vote: '94% C',
  explain: `<p><span class="mark-ok">✅ C — S3 리소스 기반 정책으로 IP 업데이트 + SCP로 두 OU 차단</span></p><p>두 가지 요구 사항을 각각 적합한 도구로 해결합니다. IP 범위 변경은 S3 버킷 정책(리소스 기반 정책)을 통해 직접 적용하는 것이 가장 정확합니다. 두 OU에 대한 권한 취소는 SCP를 해당 OU에 연결하여 S3 버킷 액세스를 거부합니다.</p>`,
  wrong: `<p><span class="mark-no">❌ A, B</span> — SCP는 S3 버킷에 대한 IP 기반 허용 정책을 효과적으로 적용할 수 없습니다. SCP의 Allow 문은 권한을 부여하지 않으며, IP 기반 S3 접근 제어는 버킷 정책으로 구현해야 합니다.</p><p><span class="mark-no">❌ D</span> — 권한 경계는 IAM 역할의 최대 권한을 설정하는 것으로, 리소스 기반 정책(S3 버킷 정책)을 통한 직접 액세스를 차단하지 못합니다.</p>`,
  disc: [{ ans:'C (94%)', txt:'S3 IP 접근 제어 = 버킷 정책(리소스 기반), OU 차단 = SCP. 두 도구의 올바른 조합.' }]
},
{
  n: 222,
  en: `A company has started using AWS across several teams. Each team has multiple accounts and unique security profiles. The company manages the accounts in an organization in AWS Organizations. Each account has its own configuration and security controls.<br><br>The company's DevOps team wants to use preventive and detective controls to govern all accounts. The DevOps team needs to ensure the security of accounts now and in the future as the company creates new accounts in the organization.<br><br>Which solution will meet these requirements?`,
  ko: `한 회사가 여러 팀에서 AWS를 사용하기 시작했습니다. 각 팀에는 여러 계정과 고유한 보안 프로필이 있습니다. 이 회사는 AWS Organizations의 조직에서 계정을 관리합니다. 각 계정에는 고유한 구성과 보안 제어가 있습니다.<br><br>이 회사의 DevOps 팀은 예방적(preventive) 및 탐지적(detective) 컨트롤을 사용하여 모든 계정을 관리하려고 합니다. DevOps 팀은 현재와 미래에 회사가 조직에 새 계정을 만들 때 계정의 보안을 보장해야 합니다.<br><br>어떤 솔루션이 이러한 요구 사항을 충족할까요?`,
  type: 'single',
  choices: [
    { k:'A', en:`Use Organizations to create OUs that have appropriate SCPs attached for each team. Place team accounts in the appropriate OUs to apply security controls. Create any new team accounts in the appropriate OUs.`, ko:`Organizations를 사용하여 각 팀에 적합한 SCP가 연결된 OU를 만듭니다. 보안 제어를 적용하려면 적절한 OU에 팀 계정을 배치합니다. 적절한 OU에 새 팀 계정을 만듭니다.` },
    { k:'B', en:`Create an AWS Control Tower landing zone. Configure OUs and appropriate controls in AWS Control Tower for the existing teams. Configure trusted access for AWS Control Tower. Enroll the existing accounts in the appropriate OUs that match the appropriate security policies for each team. Use AWS Control Tower to provision any new accounts.`, ko:`AWS Control Tower 랜딩 존을 만듭니다. 기존 팀에 대한 AWS Control Tower에서 OU와 적절한 컨트롤을 구성합니다. AWS Control Tower에 대한 신뢰할 수 있는 액세스를 구성합니다. 각 팀의 적절한 보안 정책과 일치하는 적절한 OU에 기존 계정을 등록합니다. AWS Control Tower를 사용하여 모든 새 계정을 프로비저닝합니다.` },
    { k:'C', en:`Create AWS CloudFormation stack sets in the organization's management account. Configure a stack set that deploys AWS Config with configuration rules and remediation actions for all controls to each account in the organization. Update the stack sets to deploy to new accounts as the accounts are created.`, ko:`조직의 관리 계정에서 AWS CloudFormation 스택 세트를 만듭니다. 조직의 각 계정에 모든 컨트롤에 대한 구성 규칙 및 수정 조치와 함께 AWS Config를 배포하는 스택 세트를 구성합니다. 계정이 생성됨에 따라 새 계정에 배포하도록 스택 세트를 업데이트합니다.` },
    { k:'D', en:`Configure AWS Config to manage the AWS Config rules across all AWS accounts in the organization. Deploy conformance packs that provide AWS Config rules and remediation actions across the organization.`, ko:`조직의 모든 AWS 계정에서 AWS Config 규칙을 관리하도록 AWS Config를 구성합니다. 조직 전체에서 AWS Config 규칙과 수정 조치를 제공하는 적합성 팩을 배포합니다.` },
  ],
  answer: ['B'],
  vote: '100% B',
  explain: `<p><span class="mark-ok">✅ B — AWS Control Tower 랜딩 존 + 컨트롤 구성</span></p><p>AWS Control Tower는 예방적(SCP), 탐지적(AWS Config 규칙), 사전적(CloudFormation 후크) 컨트롤을 통합적으로 제공합니다. 랜딩 존을 설정하면 새 계정 프로비저닝 시 자동으로 기준 보안 제어가 적용되어 현재와 미래의 계정 모두를 일관되게 관리할 수 있습니다. Account Factory를 통해 새 계정을 프로비저닝하면 모든 컨트롤이 자동으로 상속됩니다.</p>`,
  wrong: `<p><span class="mark-no">❌ A</span> — SCP만으로는 예방적 컨트롤만 제공하며 탐지적 컨트롤이 없습니다. 새 계정에 대한 자동 기준선 적용도 보장하지 않습니다.</p><p><span class="mark-no">❌ C, D</span> — CloudFormation StackSets나 Config 적합성 팩은 탐지 컨트롤을 제공하지만, 예방적 컨트롤과 새 계정 자동 기준선 적용을 위한 통합 솔루션이 아닙니다.</p>`,
  disc: [{ ans:'B (100%)', txt:'키워드: 예방+탐지 컨트롤, 신규 계정 자동 적용 = AWS Control Tower의 핵심 기능. (docs.aws.amazon.com/controltower/latest/userguide/controls.html)' }]
},
{
  n: 223,
  en: `A company uses an AWS CodeCommit repository to store its source code and corresponding unit tests. The company has configured an AWS CodePipeline pipeline that includes an AWS CodeBuild project that runs when code is merged to the main branch of the repository.<br><br>The company wants the CodeBuild project to run the unit tests. If the unit tests pass, the CodeBuild project must tag the most recent commit.<br><br>How should the company configure the CodeBuild project to meet these requirements?`,
  ko: `한 회사가 AWS CodeCommit 리포지토리를 사용하여 소스 코드와 해당 단위 테스트를 저장합니다. 이 회사는 리포지토리의 메인 브랜치에 코드가 병합될 때 실행되는 AWS CodeBuild 프로젝트를 포함하는 AWS CodePipeline 파이프라인을 구성했습니다.<br><br>이 회사는 CodeBuild 프로젝트에서 단위 테스트를 실행하기를 원합니다. 단위 테스트가 통과하면 CodeBuild 프로젝트는 가장 최근의 커밋에 태그를 지정해야 합니다.<br><br>이 회사는 이러한 요구 사항을 충족하기 위해 CodeBuild 프로젝트를 어떻게 구성해야 합니까?`,
  type: 'single',
  choices: [
    { k:'A', en:`Configure the CodeBuild project to use native Git to clone the CodeCommit repository. Configure the project to run the unit tests. Configure the project to use native Git to create a tag and to push the Git tag to the repository if the code passes the unit tests.`, ko:`네이티브 Git을 사용하여 CodeCommit 리포지토리를 클론하도록 CodeBuild 프로젝트를 구성합니다. 단위 테스트를 실행하도록 프로젝트를 구성합니다. 코드가 단위 테스트를 통과하면 네이티브 Git을 사용하여 태그를 만들고 Git 태그를 리포지토리에 푸시하도록 프로젝트를 구성합니다.` },
    { k:'B', en:`Configure the CodeBuild project to use native Git to clone the CodeCommit repository. Configure the project to run the unit tests. Configure the project to use AWS CLI commands to create a new repository tag in the repository if the code passes the unit tests.`, ko:`네이티브 Git을 사용하여 CodeCommit 리포지토리를 클론하도록 CodeBuild 프로젝트를 구성합니다. 단위 테스트를 실행하도록 프로젝트를 구성합니다. 코드가 단위 테스트를 통과하면 AWS CLI 명령을 사용하여 리포지토리에 새 리포지토리 태그를 만들도록 프로젝트를 구성합니다.` },
    { k:'C', en:`Configure the CodeBuild project to use AWS CLI commands to copy the code from the CodeCommit repository. Configure the project to run the unit tests. Configure the project to use AWS CLI commands to create a new Git tag in the repository if the code passes the unit tests.`, ko:`AWS CLI 명령을 사용하여 CodeCommit 리포지토리에서 코드를 복사하도록 CodeBuild 프로젝트를 구성합니다. 단위 테스트를 실행하도록 프로젝트를 구성합니다. 코드가 단위 테스트를 통과하면 AWS CLI 명령을 사용하여 리포지토리에 새 Git 태그를 생성하도록 프로젝트를 구성합니다.` },
    { k:'D', en:`Configure the CodeBuild project to use AWS CLI commands to copy the code from the CodeCommit repository. Configure the project to run the unit tests. Configure the project to use AWS CLI commands to create a new repository tag in the repository if the code passes the unit tests.`, ko:`AWS CLI 명령을 사용하여 CodeCommit 리포지토리에서 코드를 복사하도록 CodeBuild 프로젝트를 구성합니다. 단위 테스트를 실행하도록 프로젝트를 구성합니다. 코드가 단위 테스트를 통과하면 AWS CLI 명령을 사용하여 리포지토리에 새 리포지토리 태그를 생성하도록 프로젝트를 구성합니다.` },
  ],
  answer: ['A'],
  vote: '100% A',
  explain: `<p><span class="mark-ok">✅ A — 네이티브 Git으로 클론 + Git 태그 생성 및 푸시</span></p><p>네이티브 Git을 사용하여 CodeCommit 리포지토리를 클론하면 전체 Git 기능(태그 생성, 푸시 등)을 사용할 수 있습니다. 단위 테스트 통과 후 <code>git tag</code> 명령으로 태그를 만들고 <code>git push origin &lt;tag&gt;</code>로 리포지토리에 푸시하는 것이 표준 Git 워크플로입니다.</p>`,
  wrong: `<p><span class="mark-no">❌ B</span> — AWS CLI의 <code>create-tag</code> 명령은 CodeCommit '리포지토리 태그'를 만드는 것으로, Git 태그와 다릅니다. 요건은 커밋에 Git 태그를 지정하는 것입니다.</p><p><span class="mark-no">❌ C, D</span> — AWS CLI로 코드를 '복사'하는 방식은 Git 저장소 컨텍스트가 없어 태그 생성 후 푸시할 수 없습니다.</p>`,
  disc: [{ ans:'A (100%)', txt:'Git 태그 = git tag + git push. 네이티브 Git 클론이 필수. CLI create-tag는 CodeCommit 리소스 태그로 Git 태그와 다름.' }]
},
{
  n: 224,
  en: `A DevOps engineer manages a company's Amazon Elastic Container Service (Amazon ECS) cluster. The cluster runs on several Amazon EC2 instances that are in an Auto Scaling group. The DevOps engineer must implement a solution that logs and reviews all stopped tasks for errors.<br><br>Which solution will meet these requirements?`,
  ko: `DevOps 엔지니어가 회사의 Amazon Elastic Container Service(Amazon ECS) 클러스터를 관리합니다. 클러스터는 Auto Scaling 그룹에 있는 여러 Amazon EC2 인스턴스에서 실행됩니다. DevOps 엔지니어는 중단된 모든 작업을 기록하고 오류를 검토하는 솔루션을 구현해야 합니다.<br><br>어떤 솔루션이 이러한 요구 사항을 충족할까요?`,
  type: 'single',
  choices: [
    { k:'A', en:`Create an Amazon EventBridge rule to capture task state changes. Send the event to Amazon CloudWatch Logs. Use CloudWatch Logs Insights to investigate stopped tasks.`, ko:`작업 상태 변경을 캡처하기 위한 Amazon EventBridge 규칙을 만듭니다. 이벤트를 Amazon CloudWatch Logs로 보냅니다. CloudWatch Logs Insights를 사용하여 중지된 작업을 조사합니다.` },
    { k:'B', en:`Configure tasks to write log data in the embedded metric format. Store the logs in Amazon CloudWatch Logs. Monitor the ContainerInstanceCount metric for changes.`, ko:`임베디드 메트릭 형식으로 로그 데이터를 작성하도록 작업을 구성합니다. Amazon CloudWatch Logs에 로그를 저장합니다. ContainerInstanceCount 메트릭의 변경 사항을 모니터링합니다.` },
    { k:'C', en:`Configure the EC2 instances to store logs in Amazon CloudWatch Logs. Create a CloudWatch Contributor Insights rule that uses the EC2 instance log data. Use the Contributor Insights rule to investigate stopped tasks.`, ko:`Amazon CloudWatch Logs에 로그를 저장하도록 EC2 인스턴스를 구성합니다. EC2 인스턴스 로그 데이터를 사용하는 CloudWatch Contributor Insights 규칙을 만듭니다. Contributor Insights 규칙을 사용하여 중지된 작업을 조사합니다.` },
    { k:'D', en:`Configure an EC2 Auto Scaling lifecycle hook for the EC2_INSTANCE_TERMINATING scale-in event. Write the SystemEventLog file to Amazon S3. Use Amazon Athena to query the log file for errors.`, ko:`EC2_INSTANCE_TERMINATING 스케일인 이벤트에 대한 EC2 Auto Scaling 라이프사이클 후크를 구성합니다. SystemEventLog 파일을 Amazon S3에 씁니다. Amazon Athena를 사용하여 로그 파일에서 오류를 쿼리합니다.` },
  ],
  answer: ['A'],
  vote: '90% A',
  explain: `<p><span class="mark-ok">✅ A — EventBridge로 ECS 작업 상태 변경 캡처 + CloudWatch Logs Insights</span></p><p>Amazon EventBridge는 ECS 작업 상태 변경 이벤트(예: <code>STOPPED</code>)를 직접 캡처할 수 있습니다. 이벤트를 CloudWatch Logs로 전송하면 CloudWatch Logs Insights를 사용하여 중지 이유, 오류 코드 등을 임시로 쿼리하고 분석할 수 있습니다.</p>`,
  wrong: `<p><span class="mark-no">❌ B</span> — ContainerInstanceCount 메트릭은 중지된 작업의 오류를 조사하는 데 관련이 없습니다.</p><p><span class="mark-no">❌ C</span> — Contributor Insights는 상위 기여자를 분석하는 도구로, ECS 작업 중지 오류를 조사하는 데 적합하지 않습니다. 또한 EC2 인스턴스 로그가 아닌 ECS 작업 이벤트를 추적해야 합니다.</p><p><span class="mark-no">❌ D</span> — EC2 인스턴스 종료 이벤트는 ECS 작업 중지와 다르며, S3 + Athena 방식은 불필요하게 복잡합니다.</p>`,
  disc: [{ ans:'A (90%)', txt:'ECS 작업 중지 = EventBridge로 상태 변경 이벤트 캡처 → CloudWatch Logs → Logs Insights로 분석. 표준 패턴.' }]
},
{
  n: 225,
  en: `A company wants to deploy a workload on several hundred Amazon EC2 instances. The company will provision the EC2 instances in an Auto Scaling group by using a launch template.<br><br>The workload will pull files from an Amazon S3 bucket, process the data, and put the results into a different S3 bucket. The EC2 instances must have least-privilege permissions and must use temporary security credentials.<br><br>Which combination of steps will meet these requirements? (Choose two.)`,
  ko: `한 회사가 수백 개의 Amazon EC2 인스턴스에 워크로드를 배포하려고 합니다. 이 회사는 시작 템플릿을 사용하여 Auto Scaling 그룹에서 EC2 인스턴스를 프로비저닝합니다.<br><br>워크로드는 Amazon S3 버킷에서 파일을 가져오고, 데이터를 처리하고, 결과를 다른 S3 버킷에 넣습니다. EC2 인스턴스는 최소 권한 권한이 있어야 하며 임시 보안 자격 증명을 사용해야 합니다.<br><br>이러한 요구 사항을 충족하는 단계 조합은 무엇입니까? (두 가지를 선택하세요.)`,
  type: 'multi', multiCount: 2,
  choices: [
    { k:'A', en:`Create an IAM role that has the appropriate permissions for S3 buckets. Add the IAM role to an instance profile.`, ko:`S3 버킷에 대한 적절한 권한이 있는 IAM 역할을 생성합니다. 인스턴스 프로필에 IAM 역할을 추가합니다.` },
    { k:'B', en:`Update the launch template to include the IAM instance profile.`, ko:`IAM 인스턴스 프로필을 포함하도록 시작 템플릿을 업데이트합니다.` },
    { k:'C', en:`Create an IAM user that has the appropriate permissions for Amazon S3. Generate a secret key and token.`, ko:`Amazon S3에 대한 적절한 권한이 있는 IAM 사용자를 생성합니다. 비밀 키와 토큰을 생성합니다.` },
    { k:'D', en:`Create a trust anchor and profile. Attach the IAM role to the profile.`, ko:`신뢰 앵커와 프로필을 만듭니다. 프로필에 IAM 역할을 연결합니다.` },
    { k:'E', en:`Update the launch template. Modify the user data to use the new secret key and token.`, ko:`시작 템플릿을 업데이트합니다. 새로운 비밀 키와 토큰을 사용하도록 사용자 데이터를 수정합니다.` },
  ],
  answer: ['A','B'],
  vote: '100% AB',
  explain: `<p><span class="mark-ok">✅ A — IAM 역할 생성 + 인스턴스 프로필 추가</span></p><p>EC2 인스턴스에 S3 접근 권한을 부여하는 IAM 역할을 만들고 인스턴스 프로필에 추가합니다. EC2 인스턴스 프로필을 통한 IAM 역할은 임시 보안 자격 증명(STS 토큰)을 자동으로 제공합니다.</p><p><span class="mark-ok">✅ B — 시작 템플릿에 인스턴스 프로필 포함</span></p><p>시작 템플릿에 IAM 인스턴스 프로필을 지정하면 Auto Scaling 그룹에서 시작되는 모든 EC2 인스턴스에 자동으로 IAM 역할이 연결됩니다.</p>`,
  wrong: `<p><span class="mark-no">❌ C</span> — IAM 사용자의 장기 자격 증명(액세스 키)을 사용하는 것은 임시 보안 자격 증명 요건을 위반하며 보안 위험이 있습니다.</p><p><span class="mark-no">❌ D</span> — 신뢰 앵커(Trust Anchor)는 IAM Roles Anywhere 서비스와 관련된 것으로, EC2 인스턴스의 IAM 역할 연결과 다릅니다.</p><p><span class="mark-no">❌ E</span> — 사용자 데이터에 비밀 키를 저장하는 것은 심각한 보안 위험이며, 임시 자격 증명이 아닙니다.</p>`,
  disc: [{ ans:'AB (100%)', txt:'EC2 + S3 최소 권한 + 임시 자격 증명의 표준 패턴 = IAM 역할 → 인스턴스 프로필 → 시작 템플릿.' }]
},
{
  n: 226,
  en: `A company is using AWS CodeDeploy to automate software deployment. The deployment must meet these requirements:<br><br>• A number of instances must be available to serve traffic during the deployment. Traffic must be balanced across those instances, and the instances must automatically heal in the event of failure. • A new fleet of instances must be launched for deploying a new revision automatically, with no manual provisioning.<br>• Traffic must be rerouted to the new environment to half of the new instances at a time. The deployment should succeed if traffic is rerouted to at least half of the instances; otherwise, it should fail.<br>• Before routing traffic to the new fleet of instances, the temporary files generated during the deployment process must be deleted.<br>• At the end of a successful deployment, the original instances in the deployment group must be deleted immediately to reduce costs.<br><br>How can a DevOps engineer meet these requirements?`,
  ko: `한 회사에서 AWS CodeDeploy를 사용하여 소프트웨어 배포를 자동화하고 있습니다. 배포는 다음 요구 사항을 충족해야 합니다.<br><br>• 배포 중에 트래픽을 처리할 수 있는 여러 인스턴스가 있어야 합니다. 트래픽은 해당 인스턴스 간에 균형을 이루어야 하며, 장애 발생 시 인스턴스가 자동으로 복구되어야 합니다. • 수동 프로비저닝 없이 새 개정판을 자동으로 배포하기 위해 새 인스턴스 플릿을 시작해야 합니다.<br>• 트래픽은 한 번에 새 인스턴스의 절반으로 새 환경으로 다시 라우팅해야 합니다. 트래픽이 인스턴스의 절반 이상으로 다시 라우팅되면 배포가 성공해야 합니다. 그렇지 않으면 실패해야 합니다.<br>• 새 인스턴스 플릿으로 트래픽을 라우팅하기 전에 배포 프로세스 중에 생성된 임시 파일을 삭제해야 합니다.<br>• 배포가 성공적으로 끝나면 비용을 줄이기 위해 배포 그룹의 원래 인스턴스를 즉시 삭제해야 합니다.<br><br>DevOps 엔지니어는 이러한 요구 사항을 어떻게 충족할 수 있습니까?`,
  type: 'single',
  choices: [
    { k:'A', en:`Use an Application Load Balancer and an in-place deployment. Associate the Auto Scaling group with the deployment group. Use the Automatically copy Auto Scaling group option, and use CodeDeployDefault.OneAtAtime as the deployment configuration. Instruct AWS CodeDeploy to terminate the original instances in the deployment group, and use the AllowTraffic hook within appspec.yml to delete the temporary files.`, ko:`Application Load Balancer와 인플레이스 배포를 사용합니다. 배포 그룹과 Auto Scaling 그룹을 연결합니다. Automatically copy Auto Scaling group 옵션을 사용하고 CodeDeployDefault.OneAtAtime을 배포 구성으로 사용합니다. AWS CodeDeploy에 배포 그룹의 원래 인스턴스를 종료하도록 지시하고 appspec.yml 내의 AllowTraffic 후크를 사용하여 임시 파일을 삭제합니다.` },
    { k:'B', en:`Use an Application Load Balancer and a blue/green deployment. Associate the Auto Scaling group and Application Load Balancer target group with the deployment group. Use the Automatically copy Auto Scaling group option, create a custom deployment configuration with minimum healthy hosts defined as 50%, and assign the configuration to the deployment group. Instruct AWS CodeDeploy to terminate the original instances in the deployment group, and use the BeforeBlockTraffic hook within appspec.yml to delete the temporary files.`, ko:`Application Load Balancer와 블루/그린 배포를 사용합니다. 배포 그룹과 Auto Scaling 그룹 및 Application Load Balancer 대상 그룹을 연결합니다. Automatically copy Auto Scaling group 옵션을 사용하고, 최소 정상 호스트를 50%로 정의하는 사용자 지정 배포 구성을 만들고 배포 그룹에 할당합니다. AWS CodeDeploy에 배포 그룹의 원래 인스턴스를 종료하도록 지시하고 appspec.yml 내의 BeforeBlockTraffic 후크를 사용하여 임시 파일을 삭제합니다.` },
    { k:'C', en:`Use an Application Load Balancer and a blue/green deployment. Associate the Auto Scaling group and the Application Load Balancer target group with the deployment group. Use the Automatically copy Auto Scaling group option, and use CodeDeployDefault.HalfAtAtime as the deployment configuration. Instruct AWS CodeDeploy to terminate the original instances in the deployment group, and use the BeforeAllowTraffic hook within appspec.yml to delete the temporary files.`, ko:`Application Load Balancer와 블루/그린 배포를 사용합니다. 배포 그룹과 Auto Scaling 그룹 및 Application Load Balancer 대상 그룹을 연결합니다. Automatically copy Auto Scaling group 옵션을 사용하고 CodeDeployDefault.HalfAtAtime을 배포 구성으로 사용합니다. AWS CodeDeploy에 배포 그룹의 원래 인스턴스를 종료하도록 지시하고 appspec.yml 내의 BeforeAllowTraffic 후크를 사용하여 임시 파일을 삭제합니다.` },
    { k:'D', en:`Use an Application Load Balancer and an in-place deployment. Associate the Auto Scaling group and Application Load Balancer target group with the deployment group. Use the Automatically copy Auto Scaling group option, and use CodeDeployDefault.AllAtOnce as a deployment configuration. Instruct AWS CodeDeploy to terminate the original instances in the deployment group, and use the BlockTraffic hook within appspec.yml to delete the temporary files.`, ko:`Application Load Balancer와 인플레이스 배포를 사용합니다. 배포 그룹과 Auto Scaling 그룹 및 Application Load Balancer 대상 그룹을 연결합니다. Automatically copy Auto Scaling group 옵션을 사용하고 CodeDeployDefault.AllAtOnce를 배포 구성으로 사용합니다. AWS CodeDeploy에 배포 그룹의 원래 인스턴스를 종료하도록 지시하고 appspec.yml 내의 BlockTraffic 후크를 사용하여 임시 파일을 삭제합니다.` },
  ],
  answer: ['C'],
  vote: '100% C',
  explain: `<p><span class="mark-ok">✅ C — 블루/그린 + ALB + HalfAtATime + BeforeAllowTraffic 후크</span></p><ul><li><strong>블루/그린 배포</strong>: 새 인스턴스 플릿 자동 시작(Automatically copy Auto Scaling group) 요건 충족</li><li><strong>ALB + Auto Scaling 연결</strong>: 트래픽 균형 및 자동 복구 요건 충족</li><li><strong>CodeDeployDefault.HalfAtAtime</strong>: 한 번에 절반씩 트래픽 전환, 절반 이상 성공 시 성공 요건 충족</li><li><strong>BeforeAllowTraffic 후크</strong>: 트래픽 허용 전 임시 파일 삭제 요건 충족</li><li><strong>원래 인스턴스 즉시 종료</strong>: 비용 절감 요건 충족</li></ul>`,
  wrong: `<p><span class="mark-no">❌ A, D</span> — 인플레이스 배포는 새 인스턴스 플릿을 시작하지 않으며, 원래 인스턴스 삭제와 맞지 않습니다.</p><p><span class="mark-no">❌ B</span> — BeforeBlockTraffic 후크는 기존 인스턴스에서 트래픽을 차단하기 전에 실행되는 것으로, 새 인스턴스로 트래픽 허용 전 임시 파일 삭제를 위한 올바른 타이밍이 아닙니다.</p>`,
  disc: [{ ans:'C (100%)', txt:'블루/그린 + HalfAtATime + BeforeAllowTraffic이 모든 요건(새 플릿, 절반 라우팅, 트래픽 전 정리, 즉시 종료)을 정확히 충족.' }]
},
{
  n: 227,
  en: `A company needs to adopt a multi-account strategy to deploy its applications and the associated CI/CD infrastructure. The company has created an organization in AWS Organizations that has all features enabled. The company has configured AWS Control Tower and has set up a landing zone.<br><br>The company needs to use AWS Control Tower controls (guardrails) in all AWS accounts in the organization. The company must create the accounts for a multi-environment application and must ensure that all accounts are configured to an initial baseline.<br><br>Which solution will meet these requirements with the LEAST operational overhead?`,
  ko: `한 회사에서 애플리케이션과 관련 CI/CD 인프라를 배포하기 위해 다중 계정 전략을 채택해야 합니다. 이 회사는 모든 기능이 활성화된 AWS Organizations에서 조직을 만들었습니다. 이 회사는 AWS Control Tower를 구성하고 랜딩 존을 설정했습니다.<br><br>이 회사는 조직의 모든 AWS 계정에서 AWS Control Tower 컨트롤(가드레일)을 사용해야 합니다. 이 회사는 다중 환경 애플리케이션에 대한 계정을 만들어야 하며 모든 계정이 초기 기준선에 맞게 구성되었는지 확인해야 합니다.<br><br>어떤 솔루션이 최소한의 운영 오버헤드로 이러한 요구 사항을 충족할까요?`,
  type: 'single',
  choices: [
    { k:'A', en:`Create an AWS Control Tower Account Factory Customization (AFC) blueprint that uses the baseline configuration. Use AWS Control Tower Account Factory to provision a dedicated AWS account for each environment and a CI/CD account by using the blueprint.`, ko:`기준 구성을 사용하는 AWS Control Tower Account Factory Customization(AFC) 블루프린트를 만듭니다. AWS Control Tower Account Factory를 사용하여 블루프린트를 통해 각 환경에 대한 전용 AWS 계정과 CI/CD 계정을 프로비저닝합니다.` },
    { k:'B', en:`Use AWS Control Tower Account Factory to provision a dedicated AWS account for each environment and a CI/CD account. Use AWS CloudFormation StackSets to apply the baseline configuration to the new accounts.`, ko:`AWS Control Tower Account Factory를 사용하여 각 환경에 대한 전용 AWS 계정과 CI/CD 계정을 프로비저닝합니다. AWS CloudFormation StackSets를 사용하여 기준 구성을 새 계정에 적용합니다.` },
    { k:'C', en:`Use Organizations to provision a multi-environment AWS account and a CI/CD account. In the Organizations management account, create an AWS Lambda function that assumes the Organizations access role to apply the baseline configuration to the new accounts.`, ko:`Organizations를 사용하여 다중 환경 AWS 계정과 CI/CD 계정을 프로비저닝합니다. Organizations 관리 계정에서 Organizations 액세스 역할을 수임하여 새 계정에 기준 구성을 적용하는 AWS Lambda 함수를 만듭니다.` },
    { k:'D', en:`Use Organizations to provision a dedicated AWS account for each environment, an audit account, and a CI/CD account. Use AWS CloudFormation StackSets to apply the baseline configuration to the new accounts.`, ko:`Organizations를 사용하여 각 환경에 대한 전용 AWS 계정, 감사 계정 및 CI/CD 계정을 프로비저닝합니다. AWS CloudFormation StackSets를 사용하여 기준 구성을 새 계정에 적용합니다.` },
  ],
  answer: ['A'],
  vote: '100% A',
  explain: `<p><span class="mark-ok">✅ A — AFC 블루프린트 + Account Factory</span></p><p>AWS Control Tower Account Factory Customization(AFC) 블루프린트를 사용하면 초기 기준선 구성을 코드로 정의하고, Account Factory로 계정을 프로비저닝할 때 블루프린트가 자동으로 적용됩니다. Control Tower 컨트롤(가드레일)도 자동으로 상속되어 운영 오버헤드가 최소화됩니다.</p>`,
  wrong: `<p><span class="mark-no">❌ B</span> — Account Factory만 사용하고 별도로 StackSets를 관리하는 것은 A보다 더 많은 운영 오버헤드가 필요합니다.</p><p><span class="mark-no">❌ C, D</span> — Organizations + Lambda 또는 StackSets 방식은 Control Tower의 기본 기능을 활용하지 않아 복잡성이 높습니다.</p>`,
  disc: [{ ans:'A (100%)', txt:'AFC 블루프린트 = 기준선 구성 자동화의 핵심. Control Tower + Account Factory 조합이 최소 운영 오버헤드로 가드레일+기준선 자동 적용.' }]
},
{
  n: 228,
  en: `A DevOps team has created a Custom Lambda rule in AWS Config. The rule monitors Amazon Elastic Container Repository (Amazon ECR) policy statements for ecr:* actions. When a noncompliant repository is detected, Amazon EventBridge uses Amazon Simple Notification Service (Amazon SNS) to route the notification to a security team.<br><br>When the custom AWS Config rule is evaluated, the AWS Lambda function fails to run.<br><br>Which solution will resolve the issue?`,
  ko: `DevOps 팀이 AWS Config에서 사용자 지정 Lambda 규칙을 만들었습니다. 이 규칙은 Amazon Elastic Container Repository(Amazon ECR) 정책 문에서 <code>ecr:*</code> 작업을 모니터링합니다. 규정을 준수하지 않는 리포지토리가 감지되면 Amazon EventBridge는 Amazon Simple Notification Service(Amazon SNS)를 사용하여 보안 팀으로 알림을 라우팅합니다.<br><br>사용자 지정 AWS Config 규칙이 평가되면 AWS Lambda 함수가 실행되지 않습니다.<br><br>어떤 솔루션으로 이 문제를 해결할 수 있을까요?`,
  type: 'single',
  choices: [
    { k:'A', en:`Modify the Lambda function's resource policy to grant AWS Config permission to invoke the function.`, ko:`Lambda 함수의 리소스 정책을 수정하여 AWS Config가 해당 함수를 호출할 수 있는 권한을 부여합니다.` },
    { k:'B', en:`Modify the SNS topic policy to include configuration changes for EventBridge to publish to the SNS topic.`, ko:`EventBridge가 SNS 토픽에 게시할 수 있도록 구성 변경 사항을 포함하도록 SNS 토픽 정책을 수정합니다.` },
    { k:'C', en:`Modify the Lambda function's execution role to include configuration changes for custom AWS Config rules.`, ko:`사용자 지정 AWS Config 규칙에 대한 구성 변경 사항을 포함하도록 Lambda 함수의 실행 역할을 수정합니다.` },
    { k:'D', en:`Modify all the ECR repository policies to grant AWS Config access to the necessary ECR API actions.`, ko:`모든 ECR 리포지토리 정책을 수정하여 AWS Config에 필요한 ECR API 작업에 대한 액세스 권한을 부여합니다.` },
  ],
  answer: ['A'],
  vote: '100% A',
  explain: `<p><span class="mark-ok">✅ A — Lambda 리소스 정책에 AWS Config 호출 권한 부여</span></p><p>AWS Config 사용자 지정 규칙에서 Lambda 함수를 사용할 때, Lambda 함수의 리소스 기반 정책(resource policy)에 <code>config.amazonaws.com</code> 서비스 주체가 <code>lambda:InvokeFunction</code>을 호출할 수 있도록 허용해야 합니다. 이 권한이 없으면 AWS Config가 Lambda 함수를 호출할 수 없어 규칙 평가가 실패합니다.</p>`,
  wrong: `<p><span class="mark-no">❌ B</span> — SNS 토픽 정책 수정은 Config→Lambda 호출 실패와 무관합니다. 이는 EventBridge→SNS 알림 경로의 문제입니다.</p><p><span class="mark-no">❌ C</span> — Lambda 실행 역할은 Lambda 함수가 다른 AWS 서비스에 접근하는 권한을 정의합니다. Config의 Lambda 호출을 허용하는 것은 Lambda 리소스 정책(A)으로 해결해야 합니다.</p><p><span class="mark-no">❌ D</span> — ECR 리포지토리 정책 수정은 Config의 Lambda 호출 권한과 무관합니다.</p>`,
  disc: [{ ans:'A (100%)', txt:'Config 사용자 지정 규칙에서 Lambda가 실행되지 않는 원인 = Lambda 리소스 정책에 config.amazonaws.com 호출 권한 부재.' }]
},
{
  n: 229,
  en: `A developer is creating a proof of concept for a new software as a service (SaaS) application. The application is in a shared development AWS account that is part of an organization in AWS Organizations.<br><br>The developer needs to create service-linked IAM roles for the AWS services that are being considered for the proof of concept. The solution needs to give the developer the ability to create and configure the service-linked roles only.<br><br>Which solution will meet these requirements?`,
  ko: `개발자가 새로운 SaaS(Software as a Service) 애플리케이션에 대한 개념 증명을 만들고 있습니다. 애플리케이션은 AWS Organizations의 조직에 속하는 공유 개발 AWS 계정에 있습니다.<br><br>개발자는 개념 증명을 위해 고려 중인 AWS 서비스에 대한 서비스 연결 IAM 역할을 만들어야 합니다. 솔루션은 개발자에게 서비스 연결 역할만 만들고 구성할 수 있는 기능을 제공해야 합니다.<br><br>어떤 솔루션이 이러한 요구 사항을 충족할까요?`,
  type: 'single',
  choices: [
    { k:'A', en:`Create an IAM user for the developer in the organization's management account. Configure a cross-account role in the development account for the developer to use. Limit the scope of the cross-account role to common services.`, ko:`조직의 관리 계정에서 개발자를 위한 IAM 사용자를 만듭니다. 개발자가 사용할 수 있도록 개발 계정에서 교차 계정 역할을 구성합니다. 교차 계정 역할의 범위를 공통 서비스로 제한합니다.` },
    { k:'B', en:`Add the developer to an IAM group. Attach the PowerUserAccess managed policy to the IAM group. Enforce multi-factor authentication (MFA) on the user account.`, ko:`개발자를 IAM 그룹에 추가합니다. PowerUserAccess 관리형 정책을 IAM 그룹에 연결합니다. 사용자 계정에 다중 요소 인증(MFA)을 적용합니다.` },
    { k:'C', en:`Add an SCP to the development account in Organizations. Configure the SCP with a Deny rule for iam:* to limit the developer's access.`, ko:`Organizations에서 개발 계정에 SCP를 추가합니다. 개발자의 액세스를 제한하기 위해 <code>iam:*</code>에 대한 Deny 규칙으로 SCP를 구성합니다.` },
    { k:'D', en:`Create an IAM role that has the necessary IAM access to allow the developer to create policies and roles. Create and attach a permissions boundary to the role. Grant the developer access to assume the role.`, ko:`개발자가 정책과 역할을 만들 수 있도록 필요한 IAM 액세스 권한이 있는 IAM 역할을 만듭니다. 역할에 권한 경계를 만들고 연결합니다. 개발자에게 역할을 수임할 수 있는 액세스 권한을 부여합니다.` },
  ],
  answer: ['D'],
  vote: '100% D',
  explain: `<p><span class="mark-ok">✅ D — 권한 경계가 있는 IAM 역할 + 역할 수임</span></p><p>권한 경계(Permissions Boundary)를 사용하면 IAM 역할이 가질 수 있는 최대 권한을 제한할 수 있습니다. 개발자가 서비스 연결 역할만 만들고 구성할 수 있도록 권한 경계를 설정하면 개발자가 의도된 범위를 초과하는 역할을 만드는 것을 방지합니다. 이것이 최소 권한 원칙을 준수하는 방법입니다.</p>`,
  wrong: `<p><span class="mark-no">❌ A</span> — 관리 계정 IAM 사용자 + 교차 계정 역할은 불필요한 복잡성을 추가합니다.</p><p><span class="mark-no">❌ B</span> — PowerUserAccess는 서비스 연결 역할 생성 이상의 광범위한 권한을 부여합니다. 최소 권한 원칙에 위배됩니다.</p><p><span class="mark-no">❌ C</span> — SCP는 권한을 부여하지 않고 제한만 합니다. <code>iam:*</code> 거부는 서비스 연결 역할 생성도 차단합니다.</p>`,
  disc: [{ ans:'D (100%)', txt:'권한 경계 = 개발자가 서비스 연결 역할 생성 권한을 갖되 과도한 권한을 부여하지 못하도록 제한. 최소 권한 원칙의 핵심 메커니즘.' }]
},
{
  n: 230,
  en: `A company uses AWS Organizations to manage its AWS accounts. The company wants its monitoring system to receive an alert when a root user logs in. The company also needs a dashboard to display any log activity that the root user generates.<br><br>Which combination of steps will meet these requirements? (Choose three.)`,
  ko: `한 회사가 AWS Organizations를 사용하여 AWS 계정을 관리합니다. 이 회사는 루트 사용자가 로그인할 때 모니터링 시스템에 알림을 받고 싶어합니다. 또한 이 회사는 루트 사용자가 생성하는 모든 로그 활동을 표시하는 대시보드가 필요합니다.<br><br>이러한 요구 사항을 충족하는 단계 조합은 무엇입니까? (세 가지를 선택하세요.)`,
  type: 'multi', multiCount: 3,
  choices: [
    { k:'A', en:`Enable AWS Config with a multi-account aggregator. Configure log forwarding to Amazon CloudWatch Logs.`, ko:`다중 계정 애그리게이터로 AWS Config를 활성화합니다. Amazon CloudWatch Logs로 로그 전달을 구성합니다.` },
    { k:'B', en:`Create an Amazon QuickSight dashboard that uses an Amazon CloudWatch Logs query.`, ko:`Amazon CloudWatch Logs 쿼리를 사용하는 Amazon QuickSight 대시보드를 만듭니다.` },
    { k:'C', en:`Create an Amazon CloudWatch Logs metric filter to match root user login events. Configure a CloudWatch alarm and an Amazon Simple Notification Service (Amazon SNS) topic to send alerts to the company's monitoring system.`, ko:`루트 사용자 로그인 이벤트와 일치하도록 Amazon CloudWatch Logs 메트릭 필터를 만듭니다. CloudWatch 알람과 Amazon Simple Notification Service(Amazon SNS) 토픽을 구성하여 회사 모니터링 시스템에 알림을 보냅니다.` },
    { k:'D', en:`Create an Amazon CloudWatch Logs subscription filter to match root user login events. Configure the filter to forward events to an Amazon Simple Notification Service (Amazon SNS) topic. Configure the SNS topic to send alerts to the company's monitoring system.`, ko:`루트 사용자 로그인 이벤트와 일치하도록 Amazon CloudWatch Logs 구독 필터를 만듭니다. SNS 토픽으로 이벤트를 전달하도록 필터를 구성합니다. 회사의 모니터링 시스템으로 알림을 보내도록 SNS 토픽을 구성합니다.` },
    { k:'E', en:`Create an AWS CloudTrail organization trail. Configure the organization trail to send events to Amazon CloudWatch Logs.`, ko:`AWS CloudTrail 조직 트레일을 만듭니다. 조직 트레일을 구성하여 Amazon CloudWatch Logs로 이벤트를 보냅니다.` },
    { k:'F', en:`Create an Amazon CloudWatch dashboard that uses a CloudWatch Logs Insights query.`, ko:`CloudWatch Logs Insights 쿼리를 사용하는 Amazon CloudWatch 대시보드를 만듭니다.` },
  ],
  answer: ['C','E','F'],
  vote: '100% CEF',
  explain: `<p><span class="mark-ok">✅ E — CloudTrail 조직 트레일 → CloudWatch Logs</span></p><p>조직 트레일을 만들면 조직의 모든 계정에서 루트 사용자 로그인을 포함한 모든 이벤트가 캡처됩니다. 이를 CloudWatch Logs로 전송하여 중앙에서 분석합니다.</p><p><span class="mark-ok">✅ C — 메트릭 필터 + CloudWatch 알람 + SNS</span></p><p>CloudWatch Logs의 메트릭 필터로 루트 사용자 로그인 이벤트 패턴을 감지하고, 알람이 트리거되면 SNS를 통해 모니터링 시스템에 알림을 보냅니다.</p><p><span class="mark-ok">✅ F — CloudWatch Logs Insights 쿼리 + 대시보드</span></p><p>CloudWatch Logs Insights 쿼리를 CloudWatch 대시보드에 추가하여 루트 사용자 활동 로그를 시각화합니다.</p>`,
  wrong: `<p><span class="mark-no">❌ A</span> — AWS Config는 리소스 구성 변경을 모니터링하며, 루트 사용자 로그인 이벤트 캡처에는 적합하지 않습니다. CloudTrail(E)이 올바른 도구입니다.</p><p><span class="mark-no">❌ B</span> — Amazon QuickSight는 비즈니스 인텔리전스 도구로, CloudWatch Logs를 직접 쿼리하지 않습니다. CloudWatch 대시보드(F)가 더 간단합니다.</p><p><span class="mark-no">❌ D</span> — 구독 필터는 로그를 실시간으로 Lambda나 Elasticsearch로 스트리밍하는 데 사용되며, 알람 기반 알림(C)이 더 적합합니다.</p>`,
  disc: [{ ans:'CEF (100%)', txt:'루트 로그인 모니터링: E(CloudTrail→Logs) → C(메트릭 필터+알람→SNS) → F(대시보드). 3단계 조합이 모든 요건 충족.' }]
}
];
