window.QS_SET31 = [
{
  n: 301,
  en: `A company uses AWS Systems Manager to manage a fleet of Amazon Linux EC2 instances that have SSM Agent installed. All EC2 instances are configured to use Instance Metadata Service Version 2 (IMDSv2) and are running in the same AWS account and AWS Region. Company policy requires developers to use only Amazon Linux.<br>The company wants to ensure that all new EC2 instances are automatically managed by Systems Manager after creation.<br>Which solution will meet these requirements with the MOST operational efficiency?`,
  ko: `한 회사에서 SSM Agent가 설치된 Amazon Linux EC2 인스턴스 플릿을 AWS Systems Manager로 관리합니다. 모든 EC2 인스턴스는 IMDSv2를 사용하도록 구성되었으며 동일한 AWS 계정 및 리전에서 실행됩니다. 회사 정책에 따라 개발자는 Amazon Linux만 사용해야 합니다.<br>이 회사는 새로운 EC2 인스턴스가 생성 후 Systems Manager에서 자동으로 관리되도록 하려고 합니다.<br>가장 높은 운영 효율성으로 이 요구 사항을 충족하는 솔루션은 무엇입니까?`,
  type: 'single',
  choices: [
    { k:'A', en:`Create an IAM role that has a trust policy that allows Systems Manager to assume the role. Attach the AmazonSSMManagedEC2InstanceDefaultPolicy policy to the role. Configure the default-ec2-instance-management-role SSM service setting to use the role.`, ko:`Systems Manager가 역할을 수임할 수 있도록 신뢰 정책이 있는 IAM 역할을 생성합니다. AmazonSSMManagedEC2InstanceDefaultPolicy 정책을 역할에 연결합니다. default-ec2-instance-management-role SSM 서비스 설정을 해당 역할을 사용하도록 구성합니다.` },
    { k:'B', en:`Ensure that AWS Config is set up. Create an AWS Config rule that validates if an EC2 instance has SSM Agent installed. Configure the rule to run on EC2 configuration changes. Configure automatic remediation for the rule to run the AWS-InstallSSMAgent SSM document to install SSM Agent.`, ko:`AWS Config가 설정되어 있는지 확인합니다. EC2 인스턴스에 SSM Agent가 설치되어 있는지 확인하는 AWS Config 규칙을 생성합니다. EC2 구성 변경 시 규칙이 실행되도록 구성합니다. 규칙의 자동 수정으로 AWS-InstallSSMAgent SSM 문서를 실행하여 SSM Agent를 설치하도록 구성합니다.` },
    { k:'C', en:`Configure Systems Manager Patch Manager. Create a patch baseline that automatically installs SSM Agent on all new EC2 instances. Create a patch group for all EC2 instances. Attach the patch baseline to the patch group. Create a maintenance window and maintenance window task to start installing SSM Agent daily.`, ko:`Systems Manager Patch Manager를 구성합니다. 모든 새 EC2 인스턴스에 SSM Agent를 자동으로 설치하는 패치 기준선을 생성합니다. 모든 EC2 인스턴스에 대한 패치 그룹을 생성합니다. 패치 기준선을 패치 그룹에 연결합니다. 매일 SSM Agent를 설치하는 유지 관리 기간과 유지 관리 기간 작업을 생성합니다.` },
    { k:'D', en:`Create an EC2 instance role that has a trust policy that allows Amazon EC2 to assume the role. Attach the AmazonSSMManagedInstanceCore policy to the role. Ensure that AWS Config is set up. Use the ec2-instance-profile-attached managed AWS Config rule to validate if an EC2 instance has the role attached. Configure the rule to run on EC2 configuration changes. Configure automatic remediation for the rule to run the AWS-SetupManagedRoleOnEc2Instance SSM document to attach the role to the EC2 instance.`, ko:`Amazon EC2가 역할을 수임할 수 있도록 신뢰 정책이 있는 EC2 인스턴스 역할을 생성합니다. AmazonSSMManagedInstanceCore 정책을 역할에 연결합니다. AWS Config가 설정되어 있는지 확인합니다. ec2-instance-profile-attached 관리형 AWS Config 규칙을 사용하여 EC2 인스턴스에 역할이 연결되었는지 확인합니다. EC2 구성 변경 시 규칙이 실행되도록 구성합니다. 규칙의 자동 수정으로 AWS-SetupManagedRoleOnEc2Instance SSM 문서를 실행하여 역할을 EC2 인스턴스에 연결하도록 구성합니다.` },
  ],
  answer: ['A'],
  vote: '100% A',
  explain: `<p><span class="mark-ok">✅ A — default-ec2-instance-management-role SSM 설정</span></p><p><code>default-ec2-instance-management-role</code> SSM 서비스 설정을 구성하면 새 EC2 인스턴스가 자동으로 해당 역할을 수임하여 Systems Manager에서 원활하게 관리됩니다. Amazon Linux에는 SSM Agent가 이미 설치되어 있으므로 별도 설치 단계가 필요 없습니다. IMDSv2 환경에서 이 설정은 가장 자동화된 방식으로 관리 인스턴스 등록을 지원합니다.</p>`,
  wrong: `<p><span class="mark-no">❌ B</span> — AWS Config 규칙 기반 수정 방식은 변경 감지 후 수정까지 지연이 발생하며, Amazon Linux에서는 SSM Agent가 이미 설치되어 있어 불필요합니다.</p><p><span class="mark-no">❌ C</span> — Patch Manager는 SSM Agent 자동 등록이 아닌 패치 배포 목적이며, 유지 관리 기간 설정은 운영 오버헤드가 높습니다.</p><p><span class="mark-no">❌ D</span> — 여러 단계(Config 규칙 + SSM 문서 + 수정)를 거쳐야 하므로 운영 오버헤드가 높습니다.</p>`,
  disc: [{ ans:'A (100%)', txt:'default-ec2-instance-management-role 설정을 구성하면 신규 인스턴스가 자동 등록되어 추가 설정이 불필요하다는 의견이 압도적입니다.' }]
},
{
  n: 302,
  en: `A company configured an Amazon S3 event source for an AWS Lambda function. The company needs the Lambda function to run when a new object is created or an existing object is modified in a specific S3 bucket. The Lambda function will use the S3 bucket name and the S3 object key of the incoming event to read the contents of the new or modified S3 object. The Lambda function will parse the contents and save the parsed contents to an Amazon DynamoDB table.<br>The Lambda function's execution role has permissions to read from the S3 bucket and to write to the DynamoDB table. During testing, a DevOps engineer discovers that the Lambda function does not run when objects are added to the S3 bucket or when existing objects are modified.<br>Which solution will resolve these problems?`,
  ko: `한 회사가 AWS Lambda 함수에 Amazon S3 이벤트 소스를 구성했습니다. 특정 S3 버킷에서 새 객체가 생성되거나 기존 객체가 수정될 때 Lambda 함수가 실행되어야 합니다. Lambda 함수의 실행 역할에는 S3 버킷 읽기 및 DynamoDB 테이블 쓰기 권한이 있습니다. 테스트 중 DevOps 엔지니어는 S3 버킷에 객체가 추가되거나 수정될 때 Lambda 함수가 실행되지 않는다는 것을 발견했습니다.<br>이 문제를 해결하는 솔루션은 무엇입니까?`,
  type: 'single',
  choices: [
    { k:'A', en:`Create an S3 bucket policy for the S3 bucket that grants the S3 bucket permission to invoke the Lambda function.`, ko:`S3 버킷에 Lambda 함수를 호출할 권한을 부여하는 S3 버킷 정책을 생성합니다.` },
    { k:'B', en:`Create a resource policy for the Lambda function to grant Amazon S3 permission to invoke the Lambda function on the S3 bucket.`, ko:`Amazon S3가 S3 버킷에서 Lambda 함수를 호출할 수 있도록 Lambda 함수에 대한 리소스 정책을 생성합니다.` },
    { k:'C', en:`Configure an Amazon Simple Queue Service (Amazon SQS) queue as an OnFailure destination for the Lambda function. Update the Lambda function to process messages from the SQS queue and the S3 event notifications.`, ko:`Lambda 함수의 OnFailure 대상으로 Amazon SQS 대기열을 구성합니다. Lambda 함수를 업데이트하여 SQS 대기열과 S3 이벤트 알림의 메시지를 처리합니다.` },
    { k:'D', en:`Configure an Amazon Simple Queue Service (Amazon SQS) queue as the destination for the S3 bucket event notifications. Update the Lambda function's execution role to have permission to read from the SQS queue. Update the Lambda function to consume messages from the SQS queue.`, ko:`S3 버킷 이벤트 알림의 대상으로 Amazon SQS 대기열을 구성합니다. Lambda 함수 실행 역할을 업데이트하여 SQS 대기열에서 읽을 수 있는 권한을 부여합니다. Lambda 함수를 업데이트하여 SQS 대기열에서 메시지를 소비합니다.` },
  ],
  answer: ['B'],
  vote: '90% B',
  explain: `<p><span class="mark-ok">✅ B — Lambda 함수에 리소스 정책 추가</span></p><p>Amazon S3가 Lambda 함수를 호출하려면 Lambda 함수의 리소스 기반 정책에 S3에 대한 <code>lambda:InvokeFunction</code> 권한이 명시적으로 허용되어야 합니다. S3는 SNS/SQS와 달리 서비스 역할로 자동 호출하지 않습니다. AWS 콘솔에서 설정하면 자동으로 생성되지만, CLI로 구성한 경우 수동으로 추가해야 합니다.</p>`,
  wrong: `<p><span class="mark-no">❌ A</span> — S3 버킷 정책은 버킷에 대한 액세스를 제어하는 것으로, Lambda를 호출하는 권한과 무관합니다.</p><p><span class="mark-no">❌ C</span> — OnFailure 대상은 실패 처리 용도이며 이벤트 트리거 문제 해결과 관련 없습니다.</p><p><span class="mark-no">❌ D</span> — 불필요한 SQS 도입으로 아키텍처가 복잡해집니다.</p>`,
  disc: [{ ans:'B (90%)', txt:'Lambda 리소스 정책에 s3.amazonaws.com principal과 lambda:InvokeFunction 허용이 필요하다는 의견이 지배적입니다.' }]
},
{
  n: 303,
  en: `A company recently configured AWS Control Tower in its organization in AWS Organizations. The company enrolled all existing AWS accounts in AWS Control Tower. The company wants to ensure that all new AWS accounts are automatically enrolled in AWS Control Tower.<br>The company has an existing AWS Step Functions workflow that creates new AWS accounts and performs any actions required as part of account creation. The Step Functions workflow is defined in the same AWS account as AWS Control Tower.<br>Which combination of steps should the company add to the Step Functions workflow to meet these requirements? (Choose two.)`,
  ko: `한 회사가 최근 AWS Organizations의 조직에 AWS Control Tower를 구성했습니다. 회사는 모든 기존 AWS 계정을 AWS Control Tower에 등록했습니다. 모든 새 AWS 계정이 AWS Control Tower에 자동 등록되도록 해야 합니다.<br>회사에는 새 AWS 계정을 생성하고 계정 생성의 일부로 필요한 작업을 수행하는 기존 AWS Step Functions 워크플로가 있습니다. 이 워크플로는 AWS Control Tower와 동일한 AWS 계정에 정의되어 있습니다.<br>이 요구 사항을 충족하기 위해 Step Functions 워크플로에 추가해야 하는 단계 조합은 무엇입니까? (2개 선택)`,
  type: 'multi', multiCount: 2,
  choices: [
    { k:'A', en:`Create an Amazon EventBridge event that has an aws.controltower source and a CreateManagedAccount detail-type. Add the details of the new AWS account to the detail field of the event.`, ko:`aws.controltower 소스와 CreateManagedAccount 세부 유형이 있는 Amazon EventBridge 이벤트를 생성합니다. 이벤트의 detail 필드에 새 AWS 계정의 세부 정보를 추가합니다.` },
    { k:'B', en:`Create an Amazon EventBridge event that has an aws.controltower source and a SetupLandingZone detail-type. Add the details of the new AWS account to the detail field of the event.`, ko:`aws.controltower 소스와 SetupLandingZone 세부 유형이 있는 Amazon EventBridge 이벤트를 생성합니다. 이벤트의 detail 필드에 새 AWS 계정의 세부 정보를 추가합니다.` },
    { k:'C', en:`Create an AWSControlTowerExecution role in the new AWS account. Configure the role to allow the AWS Control Tower administrator account to assume the role.`, ko:`새 AWS 계정에서 AWSControlTowerExecution 역할을 생성합니다. AWS Control Tower 관리자 계정이 해당 역할을 수임할 수 있도록 역할을 구성합니다.` },
    { k:'D', en:`Call the AWS Service Catalog ProvisionProduct API operation with the details of the new AWS account.`, ko:`새 AWS 계정의 세부 정보와 함께 AWS Service Catalog ProvisionProduct API 작업을 호출합니다.` },
    { k:'E', en:`Call the Organizations EnableAWSServiceAccess API operation with the controltower.amazonaws.com service name and the details of the new AWS account.`, ko:`controltower.amazonaws.com 서비스 이름과 새 AWS 계정의 세부 정보를 사용하여 Organizations EnableAWSServiceAccess API 작업을 호출합니다.` },
  ],
  answer: ['C','D'],
  vote: '75% CD',
  explain: `<p><span class="mark-ok">✅ C — AWSControlTowerExecution 역할 생성</span></p><p>AWS Control Tower가 계정을 관리하려면 각 관리 계정에 <code>AWSControlTowerExecution</code> 역할이 있어야 합니다. 이 역할은 Control Tower 관리자 계정이 수임하여 거버넌스 및 규정 준수 규칙을 적용합니다.</p><p><span class="mark-ok">✅ D — Service Catalog ProvisionProduct API 호출</span></p><p>AWS Control Tower는 AWS Service Catalog 제품을 사용하여 계정을 프로비저닝하고 관리합니다. ProvisionProduct API를 호출하면 Account Factory를 통해 새 계정을 Control Tower에 등록할 수 있습니다.</p>`,
  wrong: `<p><span class="mark-no">❌ A, B</span> — EventBridge 이벤트를 생성하는 것은 계정 등록을 위한 올바른 접근 방식이 아닙니다. Control Tower는 이벤트를 수신하는 것이지 게시하는 것이 아닙니다.</p><p><span class="mark-no">❌ E</span> — EnableAWSServiceAccess는 이미 Control Tower 초기 설정 시 완료되어야 하는 작업입니다.</p>`,
  disc: [{ ans:'CD (75%)', txt:'공식 AWS 블로그(aws.amazon.com/blogs/architecture)의 Python 코드 예제에서 ProvisionProduct API 호출이 확인됩니다.' }]
},
{
  n: 304,
  en: `A company's web application uses an Application Load Balancer (ALB) to direct traffic to Amazon EC2 instances across three Availability Zones.<br>The company has deployed a newer version of the application to one Availability Zone for testing. If a problem is detected with the application, the company wants to direct traffic away from the affected Availability Zone until the deployment has been rolled back. The application must remain available and maintain static stability during the rollback.<br>Which solution will meet these requirements with the MOST operational efficiency?`,
  ko: `회사의 웹 애플리케이션은 ALB(Application Load Balancer)를 사용하여 세 개의 가용 영역에 걸쳐 Amazon EC2 인스턴스로 트래픽을 전달합니다.<br>회사는 테스트를 위해 한 가용 영역에 새 버전의 애플리케이션을 배포했습니다. 문제가 감지되면 배포가 롤백될 때까지 영향을 받는 가용 영역에서 트래픽을 다른 곳으로 전환하려 합니다. 롤백 중에도 애플리케이션은 사용 가능하고 정적 안정성을 유지해야 합니다.<br>가장 높은 운영 효율성으로 이 요구 사항을 충족하는 솔루션은 무엇입니까?`,
  type: 'single',
  choices: [
    { k:'A', en:`Disable cross-zone load balancing on the ALB's target group. Initiate a zonal shift on the ALB to direct traffic away from the affected Availability Zone.`, ko:`ALB의 대상 그룹에서 크로스 존 로드 밸런싱을 비활성화합니다. ALB에서 존 이동(zonal shift)을 시작하여 영향을 받는 가용 영역에서 트래픽을 멀리합니다.` },
    { k:'B', en:`Disable cross-zone load balancing on the ALB's target group. Manually remove instances in the target group that belong to the affected Availability Zone.`, ko:`ALB의 대상 그룹에서 크로스 존 로드 밸런싱을 비활성화합니다. 영향을 받는 가용 영역에 속하는 대상 그룹의 인스턴스를 수동으로 제거합니다.` },
    { k:'C', en:`Configure cross-zone load balancing on the ALB's target group to inherit settings from the ALB. Initiate a zonal shift on the ALB to direct traffic away from the affected Availability Zone.`, ko:`ALB의 대상 그룹에서 크로스 존 로드 밸런싱을 ALB 설정을 상속하도록 구성합니다. ALB에서 존 이동을 시작하여 영향을 받는 가용 영역에서 트래픽을 멀리합니다.` },
    { k:'D', en:`Configure cross-zone load balancing on the ALB's target group to inherit settings from the ALB. Remove the subnet that is associated with the affected Availability Zone.`, ko:`ALB의 대상 그룹에서 크로스 존 로드 밸런싱을 ALB 설정을 상속하도록 구성합니다. 영향을 받는 가용 영역과 연결된 서브넷을 제거합니다.` },
  ],
  answer: ['A'],
  vote: '100% A',
  explain: `<p><span class="mark-ok">✅ A — 크로스 존 로드 밸런싱 비활성화 + Zonal Shift</span></p><p>크로스 존 로드 밸런싱을 비활성화하면 각 가용 영역이 자체 대상에 대한 트래픽만 처리합니다. 이후 AWS Route 53 Application Recovery Controller를 통해 존 이동(Zonal Shift)을 시작하면 영향을 받는 가용 영역에서 트래픽을 신속하게 리디렉션할 수 있습니다. 인스턴스 수동 제거나 서브넷 변경 없이 자동화된 트래픽 관리가 가능합니다.</p>`,
  wrong: `<p><span class="mark-no">❌ B</span> — 인스턴스 수동 제거는 운영 오버헤드가 높고 신속한 롤백에 적합하지 않습니다.</p><p><span class="mark-no">❌ C</span> — 크로스 존 로드 밸런싱이 활성화된 상태에서는 존 이동이 제대로 작동하지 않을 수 있습니다.</p><p><span class="mark-no">❌ D</span> — 서브넷 제거는 영구적인 변경으로 롤백 중 가용성에 영향을 미칩니다.</p>`,
  disc: [{ ans:'A (100%)', txt:'크로스 존 로드 밸런싱 비활성화 후 Zonal Shift를 사용하면 가장 효율적으로 특정 AZ에서 트래픽을 분리할 수 있다는 의견이 일치합니다.' }]
},
{
  n: 305,
  en: `A company has several AWS accounts. An Amazon Connect instance runs in each account. The company uses an Amazon EventBridge default event bus in each account for event handling.<br>A DevOps team needs to receive all the Amazon Connect events in a single DevOps account.<br>Which solution meets these requirements?`,
  ko: `한 회사에 여러 AWS 계정이 있습니다. 각 계정에서 Amazon Connect 인스턴스가 실행됩니다. 회사는 각 계정에서 이벤트 처리를 위해 Amazon EventBridge 기본 이벤트 버스를 사용합니다.<br>DevOps 팀은 단일 DevOps 계정에서 모든 Amazon Connect 이벤트를 수신해야 합니다.<br>이 요구 사항을 충족하는 솔루션은 무엇입니까?`,
  type: 'single',
  choices: [
    { k:'A', en:`Update the resource-based policy of the default event bus in each account to allow the DevOps account to replay events. Configure an EventBridge rule in the DevOps account that matches Amazon Connect events and has a target of the default event bus in the other accounts.`, ko:`각 계정의 기본 이벤트 버스의 리소스 기반 정책을 업데이트하여 DevOps 계정이 이벤트를 재생할 수 있도록 합니다. DevOps 계정에서 Amazon Connect 이벤트와 일치하고 다른 계정의 기본 이벤트 버스를 대상으로 하는 EventBridge 규칙을 구성합니다.` },
    { k:'B', en:`Update the resource-based policy of the default event bus in each account to allow the DevOps account to receive events. Configure an EventBridge rule in the DevOps account that matches Amazon Connect events and has a target of the default event bus in the other accounts.`, ko:`각 계정의 기본 이벤트 버스의 리소스 기반 정책을 업데이트하여 DevOps 계정이 이벤트를 수신할 수 있도록 합니다. DevOps 계정에서 Amazon Connect 이벤트와 일치하고 다른 계정의 기본 이벤트 버스를 대상으로 하는 EventBridge 규칙을 구성합니다.` },
    { k:'C', en:`Update the resource-based policy of the default event bus in the DevOps account. Update the policy to allow events to be received from the accounts. Configure an EventBridge rule in each account that matches Amazon Connect events and has a target of the DevOps account's default event bus.`, ko:`DevOps 계정의 기본 이벤트 버스의 리소스 기반 정책을 업데이트합니다. 계정에서 이벤트를 수신할 수 있도록 정책을 업데이트합니다. 각 계정에서 Amazon Connect 이벤트와 일치하고 DevOps 계정의 기본 이벤트 버스를 대상으로 하는 EventBridge 규칙을 구성합니다.` },
    { k:'D', en:`Update the resource-based policy of the default event bus in the DevOps account. Update the policy to allow events to be replayed by the accounts. Configure an EventBridge rule in each account that matches Amazon Connect events and has a target of the DevOps account's default event bus.`, ko:`DevOps 계정의 기본 이벤트 버스의 리소스 기반 정책을 업데이트합니다. 계정에서 이벤트를 재생할 수 있도록 정책을 업데이트합니다. 각 계정에서 Amazon Connect 이벤트와 일치하고 DevOps 계정의 기본 이벤트 버스를 대상으로 하는 EventBridge 규칙을 구성합니다.` },
  ],
  answer: ['C'],
  vote: '100% C',
  explain: `<p><span class="mark-ok">✅ C — DevOps 계정 이벤트 버스 정책 + 각 계정에 EventBridge 규칙</span></p><p>교차 계정 이벤트 라우팅의 올바른 패턴은 이벤트를 수신하는 DevOps 계정의 이벤트 버스에 리소스 기반 정책을 설정하여 다른 계정의 이벤트 게시를 허용하고, 소스 계정(각 Amazon Connect 계정)에서 DevOps 계정의 이벤트 버스를 대상으로 하는 EventBridge 규칙을 구성합니다.</p>`,
  wrong: `<p><span class="mark-no">❌ A, B</span> — 이벤트 흐름 방향이 반대입니다. 이벤트는 각 계정에서 DevOps 계정으로 전송되어야 합니다.</p><p><span class="mark-no">❌ D</span> — "replay" 대신 "receive"가 올바른 권한입니다.</p>`,
  disc: [{ ans:'C (100%)', txt:'EventBridge 공식 문서(eb-cross-account.html)에 따르면 수신 계정 이벤트 버스에 정책을 설정하고 소스 계정에 규칙을 생성하는 것이 올바른 패턴입니다.' }]
},
{
  n: 306,
  en: `A company has deployed an Amazon Elastic Kubernetes Service (Amazon EKS) cluster with Amazon EC2 node groups. The company's DevOps team uses the Kubernetes Horizontal Pod Autoscaler and recently installed a supported EKS cluster Autoscaler.<br>The DevOps team needs to implement a solution to collect metrics and logs of the EKS cluster to establish a baseline for performance. The DevOps team will create an initial set of thresholds for specific metrics and will update the thresholds over time as the cluster is used. The DevOps team must receive an Amazon Simple Notification Service (Amazon SNS) email notification if the initial set of thresholds is exceeded or if the EKS cluster Autoscaler is not functioning properly.<br>The solution must collect cluster, node, and pod metrics. The solution also must capture logs in Amazon CloudWatch.<br>Which combination of steps should the DevOps team take to meet these requirements? (Choose three.)`,
  ko: `한 회사가 Amazon EC2 노드 그룹이 있는 Amazon EKS 클러스터를 배포했습니다. DevOps 팀은 Kubernetes Horizontal Pod Autoscaler를 사용하고 EKS 클러스터 Autoscaler를 최근 설치했습니다.<br>DevOps 팀은 성능 기준선 수립을 위해 EKS 클러스터의 메트릭과 로그를 수집하는 솔루션을 구현해야 합니다. 초기 임계값을 설정하고 시간이 지남에 따라 업데이트합니다. 임계값 초과 또는 EKS 클러스터 Autoscaler가 제대로 작동하지 않으면 SNS 이메일 알림을 받아야 합니다.<br>솔루션은 클러스터, 노드, Pod 메트릭과 CloudWatch 로그를 캡처해야 합니다.<br>이 요구 사항을 충족하기 위해 취해야 하는 단계 조합은 무엇입니까? (3개 선택)`,
  type: 'multi', multiCount: 3,
  choices: [
    { k:'A', en:`Deploy the CloudWatch agent and Fluent Bit to the cluster. Ensure that the EKS cluster has appropriate permissions to send metrics and logs to CloudWatch.`, ko:`CloudWatch 에이전트와 Fluent Bit를 클러스터에 배포합니다. EKS 클러스터에 메트릭과 로그를 CloudWatch로 보낼 수 있는 적절한 권한이 있는지 확인합니다.` },
    { k:'B', en:`Deploy AWS Distro for OpenTelemetry to the cluster. Ensure that the EKS cluster has appropriate permissions to send metrics and logs to CloudWatch.`, ko:`AWS Distro for OpenTelemetry를 클러스터에 배포합니다. EKS 클러스터에 메트릭과 로그를 CloudWatch로 보낼 수 있는 적절한 권한이 있는지 확인합니다.` },
    { k:'C', en:`Create CloudWatch alarms to monitor the CPU, memory, and node failure metrics of the cluster. Configure the alarms to send an SNS email notification to the DevOps team if thresholds are exceeded.`, ko:`클러스터의 CPU, 메모리 및 노드 장애 메트릭을 모니터링하는 CloudWatch 알람을 생성합니다. 임계값 초과 시 DevOps 팀에 SNS 이메일 알림을 보내도록 알람을 구성합니다.` },
    { k:'D', en:`Create a CloudWatch composite alarm to monitor a metric log filter of the CPU, memory, and node metrics of the cluster. Configure the alarm to send an SNS email notification to the DevOps team when anomalies are detected.`, ko:`클러스터의 CPU, 메모리, 노드 메트릭의 메트릭 로그 필터를 모니터링하는 CloudWatch 복합 알람을 생성합니다. 이상 감지 시 DevOps 팀에 SNS 이메일 알림을 보내도록 알람을 구성합니다.` },
    { k:'E', en:`Create a CloudWatch alarm to monitor the logs of the Autoscaler deployments for errors. Configure the alarm to send an SNS email notification to the DevOps team if thresholds are exceeded.`, ko:`Autoscaler 배포 로그에서 오류를 모니터링하는 CloudWatch 알람을 생성합니다. 임계값 초과 시 DevOps 팀에 SNS 이메일 알림을 보내도록 알람을 구성합니다.` },
    { k:'F', en:`Create a CloudWatch alarm to monitor a metric log filter of the Autoscaler deployments for errors. Configure the alarm to send an SNS email notification to the DevOps team if thresholds are exceeded.`, ko:`Autoscaler 배포의 메트릭 로그 필터에서 오류를 모니터링하는 CloudWatch 알람을 생성합니다. 임계값 초과 시 DevOps 팀에 SNS 이메일 알림을 보내도록 알람을 구성합니다.` },
  ],
  answer: ['A','C','F'],
  vote: '73% ACF',
  explain: `<p><span class="mark-ok">✅ A — CloudWatch 에이전트 + Fluent Bit</span></p><p>CloudWatch 에이전트와 Fluent Bit를 EKS에 배포하면 클러스터, 노드, Pod 메트릭과 로그를 CloudWatch로 전송할 수 있습니다.</p><p><span class="mark-ok">✅ C — CPU/메모리/노드 알람</span></p><p>수집된 메트릭에 대한 CloudWatch 알람으로 성능 임계값 초과 시 SNS로 알림을 전송합니다.</p><p><span class="mark-ok">✅ F — Autoscaler 로그 필터 기반 알람</span></p><p>Autoscaler 배포 로그의 메트릭 로그 필터를 통해 오류를 모니터링하고 SNS로 알림을 전송합니다.</p>`,
  wrong: `<p><span class="mark-no">❌ B</span> — AWS Distro for OpenTelemetry도 동작하지만, CloudWatch 로그 캡처 요구사항에는 CloudWatch 에이전트와 Fluent Bit가 더 직접적입니다.</p><p><span class="mark-no">❌ D</span> — 복합 알람은 이상 탐지 기반으로 초기 임계값 설정과 맞지 않습니다.</p><p><span class="mark-no">❌ E</span> — 단순 로그 모니터링보다 메트릭 로그 필터 기반 알람(F)이 더 효과적입니다.</p>`,
  disc: [{ ans:'ACF (73%)', txt:'A로 로그/메트릭 수집, C로 성능 알람, F로 Autoscaler 오류 알람을 구성하는 것이 적합하다는 의견이 지배적입니다.' }]
},
{
  n: 307,
  en: `A company discovers that its production environment and disaster recovery (DR) environment are deployed to the same AWS Region. All the production applications run on Amazon EC2 instances and are deployed by AWS CloudFormation. The applications use an Amazon FSx for NetApp ONTAP volume for application storage. No application data resides on the EC2 instances.<br>A DevOps engineer copies the required AMIs to a new DR Region. The DevOps engineer also updates the CloudFormation code to accept a Region as a parameter. The storage needs to have an RPO of 10 minutes in the DR Region.<br>Which solution will meet these requirements?`,
  ko: `한 회사에서 프로덕션 환경과 DR 환경이 동일한 AWS 리전에 배포되어 있음을 발견했습니다. 모든 프로덕션 애플리케이션은 Amazon EC2 인스턴스에서 실행되고 AWS CloudFormation으로 배포됩니다. 애플리케이션은 Amazon FSx for NetApp ONTAP 볼륨을 사용합니다. EC2 인스턴스에는 애플리케이션 데이터가 없습니다.<br>DevOps 엔지니어는 필요한 AMI를 새 DR 리전에 복사하고 CloudFormation 코드를 업데이트하여 리전을 파라미터로 허용합니다. 스토리지는 DR 리전에서 10분의 RPO를 가져야 합니다.<br>이 요구 사항을 충족하는 솔루션은 무엇입니까?`,
  type: 'single',
  choices: [
    { k:'A', en:`Create an Amazon S3 bucket in both Regions. Configure S3 Cross-Region Replication (CRR) for the S3 buckets. Create a scheduled AWS Lambda function to copy any new content from the FSx for ONTAP volume to the S3 bucket in the production Region.`, ko:`두 리전 모두에 Amazon S3 버킷을 생성합니다. S3 버킷에 대해 S3 Cross-Region Replication(CRR)을 구성합니다. FSx for ONTAP 볼륨에서 프로덕션 리전의 S3 버킷으로 새 콘텐츠를 복사하는 예약된 AWS Lambda 함수를 생성합니다.` },
    { k:'B', en:`Use AWS Backup to create a backup vault and a custom backup plan that has a 10-minute frequency. Specify the DR Region as the target Region. Assign the EC2 instances in the production Region to the backup plan.`, ko:`AWS Backup을 사용하여 백업 볼트와 10분 주기의 사용자 지정 백업 계획을 생성합니다. DR 리전을 대상 리전으로 지정합니다. 프로덕션 리전의 EC2 인스턴스를 백업 계획에 할당합니다.` },
    { k:'C', en:`Create an AWS Lambda function to create snapshots of the instance store volumes that are attached to the EC2 instances. Configure the Lambda function to copy the snapshots to the DR Region and to remove the previous copies. Create an Amazon EventBridge scheduled rule that invokes the Lambda function every 10 minutes.`, ko:`EC2 인스턴스에 연결된 인스턴스 스토어 볼륨의 스냅샷을 생성하는 AWS Lambda 함수를 생성합니다. 스냅샷을 DR 리전에 복사하고 이전 복사본을 제거하도록 Lambda 함수를 구성합니다. 10분마다 Lambda 함수를 호출하는 Amazon EventBridge 예약 규칙을 생성합니다.` },
    { k:'D', en:`Create an FSx for ONTAP instance in the DR Region. Configure a 5-minute schedule for a volume-level NetApp SnapMirror to replicate the volume from the production Region to the DR Region.`, ko:`DR 리전에 FSx for ONTAP 인스턴스를 생성합니다. 프로덕션 리전에서 DR 리전으로 볼륨을 복제하는 볼륨 수준 NetApp SnapMirror에 대해 5분 일정을 구성합니다.` },
  ],
  answer: ['D'],
  vote: '100% D',
  explain: `<p><span class="mark-ok">✅ D — FSx for ONTAP SnapMirror 5분 일정</span></p><p>FSx for NetApp ONTAP은 NetApp SnapMirror를 통해 교차 리전 볼륨 복제를 지원합니다. 5분 간격 복제 일정을 설정하면 10분 RPO 요구 사항을 충족할 수 있습니다. 이는 애플리케이션 데이터가 FSx 볼륨에만 있는 상황에 가장 적합합니다.</p>`,
  wrong: `<p><span class="mark-no">❌ A</span> — FSx 볼륨 데이터를 S3로 복사하는 것은 FSx 파일시스템 구조를 보존하지 못하며 복잡성이 높습니다.</p><p><span class="mark-no">❌ B</span> — EC2 인스턴스에는 데이터가 없으므로 EC2 백업은 효과가 없습니다.</p><p><span class="mark-no">❌ C</span> — EC2 인스턴스 스토어 볼륨은 퍼시스턴트 스토리지가 아니며, 데이터는 FSx에 있습니다.</p>`,
  disc: [{ ans:'D (100%)', txt:'FSx for ONTAP의 SnapMirror 기능이 교차 리전 복제와 RPO 요구 사항을 가장 효율적으로 충족한다는 의견이 일치합니다.' }]
},
{
  n: 308,
  en: `During a security audit, a company discovered that some security groups allow SSH traffic from 0.0.0.0/0. A security team must implement a solution to detect and remediate this issue as soon as possible. The company uses one organization in AWS Organizations to manage all the company's AWS accounts.<br>Which solution will meet these requirements?`,
  ko: `보안 감사 중에 회사에서 일부 보안 그룹이 0.0.0.0/0에서 SSH 트래픽을 허용한다는 것을 발견했습니다. 보안 팀은 가능한 한 빨리 이 문제를 탐지하고 해결하는 솔루션을 구현해야 합니다. 회사는 AWS Organizations의 하나의 조직을 사용하여 모든 AWS 계정을 관리합니다.<br>이 요구 사항을 충족하는 솔루션은 무엇입니까?`,
  type: 'single',
  choices: [
    { k:'A', en:`Enable AWS Config for all AWS accounts. Use a periodic trigger to activate the vpe-sg-port-restriction-check AWS Config rule. Create an AWS Lambda function to remediate any noncompliant rules.`, ko:`모든 AWS 계정에 대해 AWS Config를 활성화합니다. 주기적 트리거를 사용하여 vpe-sg-port-restriction-check AWS Config 규칙을 활성화합니다. 규정 미준수 규칙을 수정하는 AWS Lambda 함수를 생성합니다.` },
    { k:'B', en:`Create an AWS Lambda function in each AWS account to delete all the security group rules. Create an Amazon EventBridge rule to match security group update events or creation events. Set the Lambda function in each account as a target for the rule.`, ko:`각 AWS 계정에서 모든 보안 그룹 규칙을 삭제하는 AWS Lambda 함수를 생성합니다. 보안 그룹 업데이트 또는 생성 이벤트와 일치하도록 Amazon EventBridge 규칙을 생성합니다. 각 계정의 Lambda 함수를 규칙의 대상으로 설정합니다.` },
    { k:'C', en:`Enable AWS Config for all AWS accounts. Create a custom AWS Config rule to run on the restricted-ssh configuration change trigger. Configure the rule to invoke an AWS Lambda function to remediate any noncompliant resources.`, ko:`모든 AWS 계정에 대해 AWS Config를 활성화합니다. restricted-ssh 구성 변경 트리거에서 실행할 사용자 지정 AWS Config 규칙을 생성합니다. 규칙이 규정 미준수 리소스를 수정하기 위해 AWS Lambda 함수를 호출하도록 구성합니다.` },
    { k:'D', en:`Create an AWS Systems Manager Automation document in each account to inspect all security groups and to delete noncompliant rules. Use an Amazon EventBridge rule to run the Automation document every hour.`, ko:`각 계정에서 모든 보안 그룹을 검사하고 규정 미준수 규칙을 삭제하는 AWS Systems Manager Automation 문서를 생성합니다. Amazon EventBridge 규칙을 사용하여 매시간 Automation 문서를 실행합니다.` },
  ],
  answer: ['C'],
  vote: '100% C',
  explain: `<p><span class="mark-ok">✅ C — AWS Config restricted-ssh 규칙 + Lambda 자동 수정</span></p><p><code>restricted-ssh</code>는 AWS Config 관리형 규칙으로, 0.0.0.0/0에서 포트 22(SSH) 트래픽을 허용하는 보안 그룹을 탐지합니다. 구성 변경 트리거를 사용하면 실시간 감지가 가능하며, Lambda 자동 수정으로 규정 미준수 리소스를 즉시 해결할 수 있습니다.</p>`,
  wrong: `<p><span class="mark-no">❌ A</span> — 주기적 트리거는 실시간 감지가 아니며, vpe-sg-port-restriction-check는 이 특정 사용 사례에 최적화된 규칙이 아닙니다.</p><p><span class="mark-no">❌ B</span> — 모든 보안 그룹 규칙 삭제는 과도한 조치입니다.</p><p><span class="mark-no">❌ D</span> — 매시간 실행은 즉각적인 수정이 되지 않습니다.</p>`,
  disc: [{ ans:'C (100%)', txt:'restricted-ssh 관리형 규칙과 변경 트리거 기반 Lambda 수정이 즉각적이고 정확한 탐지 및 수정을 제공한다는 의견이 일치합니다.' }]
},
{
  n: 309,
  en: `A company's DevOps engineer must install a software package on 30 on-premises VMs and 15 Amazon EC2 instances.<br>The DevOps engineer needs to ensure that all VMs receive the package in a process that is auditable and that any configuration drift on the VMs is automatically identified and alerted on. The company uses AWS Direct Connect to connect its on-premises data center to AWS.<br>Which solution will meet these requirements with the MOST operational efficiency?`,
  ko: `회사의 DevOps 엔지니어는 30개의 온프레미스 VM과 15개의 Amazon EC2 인스턴스에 소프트웨어 패키지를 설치해야 합니다.<br>모든 VM이 감사 가능한 프로세스에서 패키지를 수신하고, VM의 모든 구성 드리프트가 자동으로 식별되어 경고되도록 해야 합니다. 회사는 AWS Direct Connect를 사용하여 온프레미스 데이터 센터를 AWS에 연결합니다.<br>가장 높은 운영 효율성으로 이 요구 사항을 충족하는 솔루션은 무엇입니까?`,
  type: 'single',
  choices: [
    { k:'A', en:`Write a script that iterates through the list of VMs once a week. Configure the script to check for the package and install the package if the package is not found. Configure the script to send an email message notification to the system administrator if the package is not found.`, ko:`일주일에 한 번 VM 목록을 반복하는 스크립트를 작성합니다. 패키지를 확인하고 없으면 설치하도록 구성합니다. 패키지가 없으면 시스템 관리자에게 이메일 알림을 보내도록 구성합니다.` },
    { k:'B', en:`Install the AWS Systems Manager Agent (SSM Agent) on all VMs. Use the SSM Agent to install the package. Use AWS Config to monitor for configuration drift. Use Amazon Simple Notification Service (Amazon SNS) to notify the system administrator if any drift is found.`, ko:`모든 VM에 AWS Systems Manager Agent(SSM Agent)를 설치합니다. SSM Agent를 사용하여 패키지를 설치합니다. AWS Config를 사용하여 구성 드리프트를 모니터링합니다. 드리프트가 발견되면 Amazon SNS를 사용하여 시스템 관리자에게 알립니다.` },
    { k:'C', en:`Write a script that checks if the package is installed across the environment. Configure the script to create a list of all VMs that are noncompliant. Configure the script to send the list to the system administrator, who will install the package on the noncompliant VMs.`, ko:`환경 전체에서 패키지가 설치되어 있는지 확인하는 스크립트를 작성합니다. 규정 미준수 VM 목록을 생성하도록 구성합니다. 목록을 시스템 관리자에게 전송하도록 구성합니다.` },
    { k:'D', en:`Log in to each VM. Use a local package manager to install the package. Use AWS Config to monitor the AWS resources for configuration changes. Write a script to monitor the on-premises resources.`, ko:`각 VM에 로그인합니다. 로컬 패키지 관리자를 사용하여 패키지를 설치합니다. AWS Config를 사용하여 AWS 리소스의 구성 변경 사항을 모니터링합니다. 온프레미스 리소스를 모니터링하는 스크립트를 작성합니다.` },
  ],
  answer: ['B'],
  vote: '100% B',
  explain: `<p><span class="mark-ok">✅ B — SSM Agent + AWS Config + SNS</span></p><p>AWS Systems Manager Agent를 온프레미스 VM과 EC2 인스턴스 모두에 설치하면 AWS Direct Connect를 통해 하이브리드 환경에서 통합 관리가 가능합니다. Run Command로 패키지 설치 과정이 감사 가능하며, AWS Config로 구성 드리프트를 자동으로 감지하고 SNS로 알림을 전송합니다.</p>`,
  wrong: `<p><span class="mark-no">❌ A, C</span> — 스크립트 기반 접근 방식은 자동화 수준이 낮고 운영 오버헤드가 높습니다.</p><p><span class="mark-no">❌ D</span> — 수동 로그인 방식은 확장성이 없고 감사 추적이 어렵습니다.</p>`,
  disc: [{ ans:'B (100%)', txt:'SSM Agent를 통한 하이브리드 환경 통합 관리와 Config를 통한 드리프트 감지가 최적의 솔루션이라는 의견이 일치합니다.' }]
},
{
  n: 310,
  en: `A company has an AWS CodePipeline pipeline in the eu-west-1 Region. The pipeline stores the build artifacts in an Amazon S3 bucket. The pipeline builds and deploys an AWS Lambda function by using an AWS CloudFormation deploy action.<br>A DevOps engineer needs to update the existing pipeline to also deploy the Lambda function to the us-east-1 Region. The pipeline has already been updated to create an additional artifact to deploy to us-east-1.<br>Which combination of steps should the DevOps engineer take to meet these requirements? (Choose two.)`,
  ko: `한 회사가 eu-west-1 리전에 AWS CodePipeline 파이프라인을 보유하고 있습니다. 이 파이프라인은 Amazon S3 버킷에 빌드 아티팩트를 저장합니다. 파이프라인은 AWS CloudFormation 배포 작업을 사용하여 AWS Lambda 함수를 빌드하고 배포합니다.<br>DevOps 엔지니어는 기존 파이프라인을 업데이트하여 Lambda 함수를 us-east-1 리전에도 배포해야 합니다. 파이프라인은 이미 us-east-1에 배포할 추가 아티팩트를 생성하도록 업데이트되었습니다.<br>이 요구 사항을 충족하기 위해 취해야 하는 단계 조합은 무엇입니까? (2개 선택)`,
  type: 'multi', multiCount: 2,
  choices: [
    { k:'A', en:`Modify the CloudFormation template to include a parameter for the Lambda function code's .zip file location. Create a new CloudFormation deploy action for us-east-1 in the pipeline. Configure the new deploy action to pass in the us-east-1 artifact location as a parameter override.`, ko:`Lambda 함수 코드의 .zip 파일 위치에 대한 파라미터를 포함하도록 CloudFormation 템플릿을 수정합니다. 파이프라인에서 us-east-1에 대한 새 CloudFormation 배포 작업을 생성합니다. us-east-1 아티팩트 위치를 파라미터 재정의로 전달하도록 새 배포 작업을 구성합니다.` },
    { k:'B', en:`Create a new CloudFormation deploy action for us-east-1 in the pipeline. Configure the new deploy action to use the CloudFormation template from the additional artifact that was created for us-east-1.`, ko:`파이프라인에서 us-east-1에 대한 새 CloudFormation 배포 작업을 생성합니다. us-east-1용으로 생성된 추가 아티팩트의 CloudFormation 템플릿을 사용하도록 새 배포 작업을 구성합니다.` },
    { k:'C', en:`Create an S3 bucket in us-east-1. Configure the S3 bucket policy to allow CodePipeline to have read and write access.`, ko:`us-east-1에 S3 버킷을 생성합니다. CodePipeline에 읽기 및 쓰기 액세스 권한을 부여하도록 S3 버킷 정책을 구성합니다.` },
    { k:'D', en:`Create an S3 bucket in us-east-1. Configure S3 Cross-Region Replication (CRR) from the S3 bucket in eu-west-1 to the S3 bucket in us-east-1.`, ko:`us-east-1에 S3 버킷을 생성합니다. eu-west-1의 S3 버킷에서 us-east-1의 S3 버킷으로 S3 Cross-Region Replication(CRR)을 구성합니다.` },
    { k:'E', en:`Modify the pipeline to include the S3 bucket for us-east-1 as an artifact store. Create a new CloudFormation deploy action for us-east-1 in the pipeline. Configure the new deploy action to use the CloudFormation template from the us-east-1 artifact.`, ko:`파이프라인을 수정하여 us-east-1의 S3 버킷을 아티팩트 저장소로 포함합니다. 파이프라인에서 us-east-1에 대한 새 CloudFormation 배포 작업을 생성합니다. us-east-1 아티팩트의 CloudFormation 템플릿을 사용하도록 새 배포 작업을 구성합니다.` },
  ],
  answer: ['C','E'],
  vote: '92% CE',
  explain: `<p><span class="mark-ok">✅ C — us-east-1에 S3 버킷 생성 및 CodePipeline 접근 허용</span></p><p>CodePipeline이 여러 리전에 배포하려면 각 대상 리전에 아티팩트 저장소(S3 버킷)가 필요합니다. CodePipeline 서비스 역할에 읽기/쓰기 권한이 있어야 합니다.</p><p><span class="mark-ok">✅ E — 파이프라인 아티팩트 저장소 업데이트 + 새 배포 작업</span></p><p>파이프라인에 us-east-1 S3 버킷을 아티팩트 저장소로 추가하고, us-east-1 아티팩트의 CloudFormation 템플릿을 사용하는 새 배포 작업을 생성합니다. 리전별 독립적인 템플릿이 필요합니다.</p>`,
  wrong: `<p><span class="mark-no">❌ A</span> — 기존 템플릿에 파라미터만 추가하는 것은 리전별 VPC ID, 서브넷 등 다른 구성을 처리할 수 없습니다.</p><p><span class="mark-no">❌ B</span> — 파이프라인에 아티팩트 저장소(S3 버킷)를 추가하지 않으면 교차 리전 배포가 작동하지 않습니다.</p><p><span class="mark-no">❌ D</span> — CRR은 필요하지 않으며, CodePipeline이 각 리전에 직접 아티팩트를 관리합니다.</p>`,
  disc: [{ ans:'CE (92%)', txt:'교차 리전 CodePipeline 배포에는 각 리전의 아티팩트 저장소와 리전별 독립 배포 작업이 필요하다는 의견이 지배적입니다.' }]
}
];
