window.QS_SET40 = [
{
  n: 391,
  en: `A company manages environments for its application in multiple AWS accounts. Each environment account is in a different OU in AWS Organizations.<br><br>A DevOps team is responsible for the application deployment process across the environments. The deployment process uses an AWS CodePipeline pipeline in a Shared Services account. The DevOps team members are in the same user group. The team members have administrative access to all accounts through AWS IAM Identity Center.<br><br>A recent deployment problem in the development environment required the DevOps team to perform manual steps. The deployment to the production environment then resulted in an incident that caused the pipeline to fail, which blocked new deployments for several hours.<br><br>A DevOps engineer needs to ensure that only the pipeline can perform deployments in the production environment. The DevOps engineer must have access to the environment in case of an emergency.<br><br>Which solution will meet these requirements with the MOST operational efficiency?`,
  ko: `한 회사가 여러 AWS 계정에서 애플리케이션 환경을 관리합니다. 각 환경 계정은 AWS Organizations의 서로 다른 OU에 속해 있습니다.<br><br>DevOps 팀은 이러한 환경 전반에 걸친 애플리케이션 배포 프로세스를 담당합니다. 배포 프로세스는 공유 서비스 계정의 AWS CodePipeline 파이프라인을 사용합니다. DevOps 팀 구성원들은 모두 동일한 사용자 그룹에 속해 있으며, AWS IAM Identity Center를 통해 모든 계정에 대한 관리자 권한을 가지고 있습니다.<br><br>최근 개발 환경에서 발생한 배포 문제로 인해 DevOps 팀이 수동으로 작업을 수행해야 했습니다. 그 결과 프로덕션 환경으로의 배포 과정에서 파이프라인 오류가 발생하여 몇 시간 동안 새로운 배포가 중단되었습니다.<br><br>DevOps 엔지니어는 프로덕션 환경에서는 파이프라인을 통해서만 배포가 이루어지도록 해야 하며, 비상 상황 발생 시 해당 환경에 접근할 수 있어야 합니다.<br><br>이러한 요구 사항을 가장 효율적으로 충족하는 솔루션은 무엇일까요?`,
  type: 'single',
  choices: [
    { k:'A', en:`Update the DevOps group to have the ReadOnlyAccess permission set for the production accounts. Configure the DevOps engineer user with a new permission set that has AdministratorAccess permissions and that allows the user to assume the pipeline role. Add an SCP that denies modification of resources by any entity other than the pipeline role.`, ko:`DevOps 그룹에 프로덕션 계정에 대한 읽기 전용 액세스(ReadOnlyAccess) 권한을 부여하도록 업데이트합니다. DevOps 엔지니어 사용자에게 관리자 액세스(AdministratorAccess) 권한을 포함하고 파이프라인 역할을 수행할 수 있도록 하는 새로운 권한 집합을 구성합니다. 파이프라인 역할 이외의 다른 주체가 리소스를 수정하지 못하도록 하는 SCP를 추가합니다.` },
    { k:'B', en:`Create an SCP that denies all write actions for the DevOps team members on the production OU. Configure a new user in IAM Identity Center for the DevOps engineer with a new permission set that has AdministratorAccess permissions. Add an SCP that denies modification of resources by any entity other than the pipeline role.`, ko:`프로덕션 OU에서 DevOps 팀 구성원의 모든 쓰기 작업을 거부하는 SCP를 생성합니다. DevOps 엔지니어를 위해 IAM Identity Center에서 관리자 액세스 권한이 있는 새 권한 집합을 가진 새 사용자를 구성합니다. 파이프라인 역할 이외의 모든 엔터티가 리소스를 수정하지 못하도록 하는 SCP를 추가합니다.` },
    { k:'C', en:`Update the DevOps group to be able to assume the pipeline role for the production accounts. Configure a new user in IAM Identity Center for the DevOps engineer with a new permission set that has AdministratorAccess permissions. Add an SCP that denies modification of resources by any entity other than the DevOps engineer.`, ko:`DevOps 그룹이 프로덕션 계정에 대한 파이프라인 역할을 수행할 수 있도록 업데이트합니다. DevOps 엔지니어를 위해 IAM Identity Center에서 관리자 액세스 권한이 있는 새 권한 집합을 가진 새 사용자를 구성합니다. DevOps 엔지니어 이외의 다른 주체가 리소스를 수정하지 못하도록 하는 SCP를 추가합니다.` },
    { k:'D', en:`Create an SCP that denies all write actions for the DevOps team members on the production OU. Use a specific tag to tag the resources that CodePipeline provisions. Add an SCP that denies modification of tagged resources by any entity other than the DevOps engineer.`, ko:`프로덕션 OU에서 DevOps 팀 구성원의 모든 쓰기 작업을 거부하는 SCP를 생성합니다. CodePipeline에서 프로비저닝하는 리소스에 특정 태그를 지정합니다. DevOps 엔지니어 이외의 다른 주체가 태그가 지정된 리소스를 수정하지 못하도록 하는 SCP를 추가합니다.` },
  ],
  answer: ['A'],
  vote: '100% A',
  explain: `<p><span class="mark-ok">✅ A — 핵심 이유</span></p><p>A는 세 가지 요구사항을 모두 충족합니다. 첫째, 일반 DevOps 그룹은 ReadOnlyAccess만 가지므로 프로덕션에 직접 변경을 가할 수 없습니다. 둘째, SCP가 파이프라인 역할 외 모든 주체의 리소스 수정을 차단하므로 파이프라인을 통해서만 배포가 가능합니다. 셋째, DevOps 엔지니어는 별도의 새 권한 집합(AdministratorAccess + 파이프라인 역할 수임 가능)을 통해 비상 시에도 접근할 수 있습니다.</p>`,
  wrong: `<p><span class="mark-no">❌ B</span> — 새 사용자를 별도로 생성해야 하므로 운영 효율성이 낮고, SCP가 두 개 겹쳐 관리 복잡성이 증가합니다.</p><p><span class="mark-no">❌ C</span> — SCP가 DevOps 엔지니어 외 수정을 거부하므로 파이프라인 역할도 차단될 수 있어 요구사항 위반입니다.</p><p><span class="mark-no">❌ D</span> — 태그 기반 SCP는 파이프라인이 프로비저닝한 리소스 이외의 신규 리소스 보호가 어렵고, 비상 접근 권한 구성이 불완전합니다.</p>`,
  disc: [{ ans:'A', txt:'읽기 전용 그룹 + 별도 비상 권한 집합 + 파이프라인 역할만 허용하는 SCP 조합이 가장 명확하고 효율적인 구성입니다.' }]
},
{
  n: 392,
  en: `A company builds container images and stores them on Amazon Elastic Container Registry (Amazon ECR) in the company's primary AWS Region.<br><br>A DevOps engineer wants to replicate all the company's ECR repository images to a secondary Region. The DevOps engineer creates a new ECR repository in the secondary Region and configures permission on the new repository to allow replication.<br><br>Which solution will meet these requirements with the MOST operational efficiency?`,
  ko: `한 회사가 컨테이너 이미지를 빌드하여 자사 주 AWS 리전의 Amazon Elastic Container Registry(Amazon ECR)에 저장합니다.<br><br>DevOps 엔지니어는 회사 ECR 저장소에 있는 모든 이미지를 보조 리전으로 복제하려고 합니다. DevOps 엔지니어는 보조 리전에 새 ECR 저장소를 생성하고 복제를 허용하도록 권한을 구성합니다.<br><br>이러한 요구 사항을 가장 운영 효율적으로 충족하는 솔루션은 무엇일까요?`,
  type: 'single',
  choices: [
    { k:'A', en:`Pull the existing primary ECR images and then push the images to the secondary ECR repository. Create a replication rule on the primary ECR registry to replicate the images to the secondary ECR registry.`, ko:`기존 기본 ECR 이미지를 가져온 다음 보조 ECR 저장소로 푸시합니다. 기본 ECR 레지스트리에 복제 규칙을 생성하여 이미지를 보조 ECR 레지스트리로 복제합니다.` },
    { k:'B', en:`Pull the existing primary ECR images and then push the images to the secondary ECR repository. Configure permission on the primary ECR registry to allow access from the secondary Region.`, ko:`기존 기본 ECR 이미지를 가져온 다음 보조 ECR 저장소로 푸시합니다. 보조 리전에서 액세스할 수 있도록 기본 ECR 레지스트리에 대한 권한을 구성합니다.` },
    { k:'C', en:`Configure permission on the primary ECR registry to allow access from the secondary Region. Create a replication rule on the primary ECR registry to replicate the images to the secondary ECR registry.`, ko:`보조 리전에서 접근할 수 있도록 기본 ECR 레지스트리에 대한 권한을 구성합니다. 기본 ECR 레지스트리에 복제 규칙을 생성하여 이미지를 보조 ECR 레지스트리로 복제합니다.` },
    { k:'D', en:`Configure an AWS Lambda function to automatically save the ECR images to an Amazon S3 bucket. Configure cross-Region replication for the S3 bucket. Configure a second Lambda function to push the images to ECR repositories in the replication destination Region when images are replicated to the S3 bucket.`, ko:`ECR 이미지를 Amazon S3 버킷에 자동으로 저장하는 AWS Lambda 함수를 구성합니다. S3 버킷에 대해 리전 간 복제를 구성합니다. 이미지가 S3 버킷으로 복제되면 복제 대상 리전의 ECR 리포지토리로 이미지를 푸시하는 두 번째 Lambda 함수를 구성합니다.` },
  ],
  answer: ['A'],
  vote: '100% A',
  explain: `<p><span class="mark-ok">✅ A — 핵심 이유</span></p><p>Amazon ECR 복제는 "푸시 기반" 모델로, 복제 규칙 생성 이전에 존재하던 기존 이미지는 자동으로 복제되지 않습니다. 따라서 기존 이미지는 수동으로 pull → push하여 보조 리전에 복사하고, 이후 신규 이미지는 복제 규칙으로 자동 처리하는 두 단계가 필요합니다. A만이 이 두 단계를 모두 수행합니다.</p>`,
  wrong: `<p><span class="mark-no">❌ C</span> — 복제 규칙만 생성하면 신규 이미지는 복제되지만, 기존 이미지는 복제되지 않으므로 "모든 이미지 복제" 요건을 충족하지 못합니다.</p><p><span class="mark-no">❌ B</span> — 권한 구성 없이 수동 push만 하므로 이후 신규 이미지가 자동 복제되지 않습니다.</p><p><span class="mark-no">❌ D</span> — Lambda + S3 + Kinesis 구조는 불필요하게 복잡하며 운영 오버헤드가 큽니다.</p>`,
  disc: [{ ans:'A', txt:'ECR 복제는 기존 이미지 소급 적용 불가 — 기존 이미지는 수동 pull/push, 이후 이미지는 복제 규칙으로 처리하는 A가 정답.' }]
},
{
  n: 393,
  en: `A company is experiencing failures in its AWS CodeDeploy deployments for a critical application. The application is deployed on Amazon EC2 instances. A DevOps engineer must analyze the failed deployments to identify the root cause of the failures.<br><br>Which solution will provide the appropriate information to troubleshoot the deployment issues?`,
  ko: `한 회사가 핵심 애플리케이션의 AWS CodeDeploy 배포에서 오류를 겪고 있습니다. 해당 애플리케이션은 Amazon EC2 인스턴스에 배포되어 있습니다. DevOps 엔지니어는 실패한 배포를 분석하여 근본 원인을 파악해야 합니다.<br><br>어떤 솔루션이 배포 문제를 해결하는 데 필요한 적절한 정보를 제공할까요?`,
  type: 'single',
  choices: [
    { k:'A', en:`Configure VPC Flow Logs to monitor network traffic. Use Amazon Inspector to detect non-network deployment issues. Use Amazon Detective to analyze the findings.`, ko:`VPC Flow Logs를 구성하여 네트워크 트래픽을 모니터링합니다. Amazon Inspector를 사용하여 네트워크 관련이 아닌 배포 문제를 감지합니다. Amazon Detective를 사용하여 발견 사항을 분석합니다.` },
    { k:'B', en:`Enable detailed monitoring on the EC2 instances. Use AWS Systems Manager Run Command to run troubleshooting scripts on all the EC2 instances simultaneously. Analyze the results in AWS CloudTrail logs.`, ko:`EC2 인스턴스에 대한 상세 모니터링을 활성화합니다. AWS Systems Manager의 명령 실행 기능을 사용하여 모든 EC2 인스턴스에서 동시에 문제 해결 스크립트를 실행합니다. AWS CloudTrail 로그에서 결과를 분석합니다.` },
    { k:'C', en:`Use Amazon CloudWatch Logs to review application logs. Analyze CodeDeploy deployment logs in the /opt/codedeploy-agent/deployment-root/ directory on the EC2 instances. Use AWS X-Ray to trace requests through the application components.`, ko:`Amazon CloudWatch Logs를 사용하여 애플리케이션 로그를 검토합니다. EC2 인스턴스의 /opt/codedeploy-agent/deployment-root/ 디렉터리에 있는 CodeDeploy 배포 로그를 분석합니다. AWS X-Ray를 사용하여 애플리케이션 구성 요소를 통한 요청을 추적합니다.` },
    { k:'D', en:`Examine AWS Trusted Advisor checks for the CodeDeploy deployments. Use the AWS Health Dashboard to monitor application health. Analyze performance metrics in Amazon CloudWatch dashboards.`, ko:`CodeDeploy 배포에 대한 AWS Trusted Advisor 검사를 검토합니다. AWS Health 대시보드를 사용하여 애플리케이션 상태를 모니터링합니다. Amazon CloudWatch 대시보드에서 성능 지표를 분석합니다.` },
  ],
  answer: ['C'],
  vote: '100% C',
  explain: `<p><span class="mark-ok">✅ C — 핵심 이유</span></p><p>CodeDeploy 배포 실패를 분석하는 가장 직접적인 방법은 CloudWatch Logs로 애플리케이션 로그를 검토하고, EC2 인스턴스의 <code>/opt/codedeploy-agent/deployment-root/</code> 디렉터리에서 CodeDeploy 에이전트 로그를 확인하는 것입니다. X-Ray는 배포 후 런타임 요청 추적에 활용됩니다.</p>`,
  wrong: `<p><span class="mark-no">❌ A</span> — VPC Flow Logs와 Inspector/Detective는 네트워크/보안 분석 도구로, CodeDeploy 배포 실패 원인 파악에 적합하지 않습니다.</p><p><span class="mark-no">❌ B</span> — CloudTrail은 API 호출 감사용이며 배포 스크립트 실패 원인 분석에는 부적합합니다.</p><p><span class="mark-no">❌ D</span> — Trusted Advisor와 Health Dashboard는 CodeDeploy 배포 라이프사이클 이벤트 수준의 상세 로그를 제공하지 않습니다.</p>`,
  disc: []
},
{
  n: 394,
  en: `A company has developed a web application that conducts seasonal sales on public holidays. The web application is deployed on AWS and uses AWS services for storage, database, computing, and encryption. During seasonal sales, the company expects high network traffic from a large number of users. The company must receive insights regarding any unexpected behavior during the sale.<br><br>A DevOps team wants to review the insights upon detecting anomalous behaviors during the sale. The DevOps team wants to receive recommended actions to resolve the anomalous behaviors. The recommendations must be provided on the provisioned infrastructure to address the issues that might occur in the future.<br><br>Which combination of steps will meet these requirements with the LEAST operational overhead? (Choose two.)`,
  ko: `한 회사가 공휴일에 시즌 세일을 진행하는 웹 애플리케이션을 개발했습니다. 이 웹 애플리케이션은 AWS에 배포되어 있으며 스토리지, 데이터베이스, 컴퓨팅 및 암호화에 AWS 서비스를 사용합니다. 시즌 세일 기간 동안에는 많은 사용자로 인해 네트워크 트래픽이 급증할 것으로 예상됩니다. 회사는 세일 기간 중 발생할 수 있는 예상치 못한 동작에 대한 인사이트를 수집해야 합니다.<br><br>DevOps 팀은 세일 기간 중 이상 동작이 감지되면 이러한 인사이트를 검토하고, 이상 동작을 해결하기 위한 권장 조치를 받고자 합니다. 이러한 권장 사항은 향후 발생할 수 있는 문제를 해결하기 위해 프로비저닝된 인프라에 적용되어야 합니다.<br><br>이러한 요구 사항을 최소한의 운영 오버헤드로 충족하는 단계 조합은 무엇일까요? (두 가지를 선택하세요.)`,
  type: 'multi', multiCount: 2,
  choices: [
    { k:'A', en:`Enable Amazon DevOps Guru in the AWS account. Determine the coverage for DevOps Guru for all supported AWS resources in the account. Use the DevOps Guru dashboard to find the analysis, recommendations, and related metrics.`, ko:`AWS 계정에서 Amazon DevOps Guru를 활성화합니다. 계정 내 지원되는 모든 AWS 리소스에 대해 DevOps Guru 적용 범위를 설정합니다. DevOps Guru 대시보드를 사용하여 분석, 권장 사항 및 관련 지표를 확인합니다.` },
    { k:'B', en:`Create an Amazon Simple Notification Service (Amazon SNS) topic. Configure Amazon DevOps Guru to send notifications about important events to the company when anomalies are identified.`, ko:`Amazon Simple Notification Service(Amazon SNS) 토픽을 생성합니다. 이상 징후가 감지될 때 회사에 중요한 이벤트에 대한 알림을 보내도록 Amazon DevOps Guru를 구성합니다.` },
    { k:'C', en:`Create an Amazon S3 bucket. Store Amazon CloudWatch logs, AWS CloudTrail data, and AWS Config data in the S3 bucket. Use Amazon Athena to generate insights on the data. Create a dashboard by using Amazon QuickSight.`, ko:`Amazon S3 버킷을 생성합니다. Amazon CloudWatch 로그, AWS CloudTrail 데이터 및 AWS Config 데이터를 S3 버킷에 저장합니다. Amazon Athena를 사용하여 데이터에 대한 인사이트를 생성합니다. Amazon QuickSight를 사용하여 대시보드를 생성합니다.` },
    { k:'D', en:`Configure email message reports for an Amazon QuickSight dashboard. Schedule and send the email reports to the company.`, ko:`Amazon QuickSight 대시보드용 이메일 메시지 보고서를 구성합니다. 이메일 보고서를 예약하고 회사에 전송합니다.` },
    { k:'E', en:`Create an Amazon Simple Notification Service (Amazon SNS) topic. Configure Amazon Athena to send query results about important events to the company when anomalies are identified.`, ko:`Amazon Simple Notification Service(Amazon SNS) 토픽을 생성합니다. 이상 징후가 감지될 때 중요한 이벤트에 대한 쿼리 결과를 회사에 전송하도록 Amazon Athena를 구성합니다.` },
  ],
  answer: ['A','B'],
  vote: '100% AB',
  explain: `<p><span class="mark-ok">✅ A+B — 핵심 이유</span></p><p>Amazon DevOps Guru는 AWS 리소스의 이상 동작을 ML로 자동 감지하고 대시보드에서 분석·권장 조치를 제공합니다(A). SNS 토픽과 연동하면 이상 감지 시 즉시 알림을 받을 수 있어(B), 별도 로그 파이프라인 구축 없이도 최소 운영 오버헤드로 요구사항을 충족합니다.</p>`,
  wrong: `<p><span class="mark-no">❌ C</span> — S3+Athena+QuickSight 구성은 운영 오버헤드가 크고 실시간 이상 감지가 어렵습니다.</p><p><span class="mark-no">❌ D</span> — 이메일 예약 보고서는 실시간 이상 감지 요건을 충족하지 못합니다.</p><p><span class="mark-no">❌ E</span> — Athena는 쿼리 실행 도구이며 이상 감지 시 자동 알림 기능이 없습니다.</p>`,
  disc: []
},
{
  n: 395,
  en: `A DevOps engineer needs to design a cloud-based solution to standardize deployment artifacts for AWS Cloud deployments and on-premises deployments. There is currently no routing traffic between the on-premises data center and the AWS environment.<br><br>The solution must be able to consume downstream packages from public repositories and must be highly available. Data must be encrypted in transit and at rest. The solution must store the deployment artifacts in object storage and deploy the deployment artifacts into Amazon Elastic Container Service (Amazon ECS). The deployment artifacts must be encrypted in transit if the deployment artifacts travel across the public internet.<br><br>The DevOps engineer needs to deploy this solution in less than two weeks.<br><br>Which solution will meet these requirements?`,
  ko: `DevOps 엔지니어는 AWS 클라우드 배포와 온프레미스 배포를 위한 배포 아티팩트를 표준화하는 클라우드 기반 솔루션을 설계해야 합니다. 현재 온프레미스 데이터 센터와 AWS 환경 간에는 라우팅 트래픽이 없습니다.<br><br>이 솔루션은 퍼블릭 리포지토리에서 다운스트림 패키지를 사용할 수 있어야 하며 고가용성을 보장해야 합니다. 데이터는 전송 중과 저장 시 모두 암호화되어야 합니다. 솔루션은 배포 아티팩트를 객체 스토리지에 저장하고 Amazon Elastic Container Service(Amazon ECS)에 배포해야 합니다. 배포 아티팩트가 공용 인터넷을 통해 전송되는 경우 전송 중에도 암호화되어야 합니다.<br><br>DevOps 엔지니어는 2주 이내에 이 솔루션을 배포해야 합니다.<br><br>이러한 요구 사항을 충족하는 솔루션은 무엇일까요?`,
  type: 'single',
  choices: [
    { k:'B', en:`Use an AWS Direct Connect connection and a VPN connection to connect the on-premises data center to AWS. Deploy third-party artifact management software on Amazon EC2 instances.`, ko:`AWS Direct Connect 연결과 VPN 연결을 사용하여 온프레미스 데이터 센터를 AWS에 연결합니다. 타사 아티팩트 관리 소프트웨어를 Amazon EC2 인스턴스에 배포합니다.` },
    { k:'C', en:`Use two AWS VPN connections to connect the on-premises data center to AWS. Use AWS CodeArtifact to store the deployment artifacts.`, ko:`온프레미스 데이터 센터를 AWS에 연결하기 위해 두 개의 AWS VPN 연결을 사용합니다. 배포 아티팩트는 AWS CodeArtifact를 사용하여 저장합니다.` },
    { k:'D', en:`Use parallel AWS Direct Connect connections to connect the on-premises data center to AWS. Deploy third-party artifact management software on Amazon EC2 instances.`, ko:`병렬 AWS Direct Connect 연결을 사용하여 온프레미스 데이터 센터를 AWS에 연결합니다. 타사 아티팩트 관리 소프트웨어를 Amazon EC2 인스턴스에 배포합니다.` },
  ],
  answer: ['C'],
  vote: '100% C',
  explain: `<p><span class="mark-ok">✅ C — 핵심 이유</span></p><p>AWS CodeArtifact는 완전 관리형 아티팩트 저장소로 퍼블릭 리포지토리 업스트림 연동, 고가용성, 전송 중·저장 시 암호화를 기본 제공합니다. VPN 두 개를 사용하면 고가용성 연결도 확보됩니다. 2주 내 배포 가능하며, 직접 코드 없이 관리형 서비스로 요구사항을 모두 충족합니다.</p>`,
  wrong: `<p><span class="mark-no">❌ B</span> — Direct Connect 프로비저닝은 수주가 소요되어 2주 내 배포 불가하며, 타사 소프트웨어 설치는 운영 오버헤드를 증가시킵니다.</p><p><span class="mark-no">❌ D</span> — 병렬 Direct Connect 역시 배포 기간 초과 및 타사 소프트웨어 관리 부담이 있습니다.</p>`,
  disc: []
},
{
  n: 396,
  en: `A DevOps engineer successfully creates an Amazon Elastic Kubernetes Service (Amazon EKS) cluster that includes managed node groups. When the DevOps engineer tries to add node groups to the cluster, the cluster returns an error that states, "NodeCreationFailure: Instances failed to join the Kubernetes cluster."<br><br>The DevOps engineer confirms that the EC2 worker nodes are running and that the EKS cluster is in an active state.<br><br>How should the DevOps engineer troubleshoot this issue?`,
  ko: `DevOps 엔지니어가 관리형 노드 그룹이 포함된 Amazon Elastic Kubernetes Service(Amazon EKS) 클러스터를 성공적으로 생성했습니다. 하지만 클러스터에 노드 그룹을 추가하려고 하면 "NodeCreationFailure: 인스턴스가 Kubernetes 클러스터에 참여하지 못했습니다."라는 오류가 발생합니다.<br><br>DevOps 엔지니어는 EC2 워커 노드가 실행 중이고 EKS 클러스터가 활성 상태임을 확인했습니다.<br><br>이 문제를 어떻게 해결해야 할까요?`,
  type: 'single',
  choices: [
    { k:'A', en:`Ensure that the EKS cluster's VPC subnets do not overlap with the 172.17.0.0/16 CIDR range.`, ko:`EKS 클러스터의 VPC 서브넷이 172.17.0.0/16 CIDR 범위와 겹치지 않도록 하십시오.` },
    { k:'B', en:`Use kubectl to update the kubeconfig file to use the credentials that created the cluster.`, ko:`kubectl 명령어를 사용하여 클러스터를 생성할 때 사용한 자격 증명을 사용하도록 kubeconfig 파일을 업데이트합니다.` },
    { k:'C', en:`Run the AWSSupport-TroubleshootEKSWorkerNode runbook.`, ko:`AWSSupport-TroubleshootEKSWorkerNode 런북을 실행합니다.` },
    { k:'D', en:`Create an AWS Identity and Access Management (IAM) OpenID Connect (OIDC) provider for the cluster.`, ko:`클러스터용 AWS Identity and Access Management(IAM) OpenID Connect(OIDC) 공급자를 생성합니다.` },
  ],
  answer: ['C'],
  vote: '100% C',
  explain: `<p><span class="mark-ok">✅ C — 핵심 이유</span></p><p>"NodeCreationFailure: Instances failed to join the Kubernetes cluster" 오류는 네트워킹, IAM 권한, 사용자 데이터 구성 등 다양한 원인으로 발생할 수 있는 일반적인 오류입니다. AWS는 이 상황을 위해 <code>AWSSupport-TroubleshootEKSWorkerNode</code>라는 Systems Manager 자동화 런북을 제공하며, 가장 일반적인 원인을 자동으로 점검하여 체계적으로 문제를 진단합니다.</p>`,
  wrong: `<p><span class="mark-no">❌ A</span> — CIDR 충돌은 한 가지 특정 원인만 점검하며, 포괄적인 문제 해결에 부족합니다.</p><p><span class="mark-no">❌ B</span> — kubeconfig 자격 증명 문제는 kubectl 접근 오류를 유발하지, 노드 클러스터 합류 실패와는 무관합니다.</p><p><span class="mark-no">❌ D</span> — OIDC 공급자는 서비스 계정용 IAM 역할 연동에 필요하며 노드 합류 실패의 직접적 원인이 아닙니다.</p>`,
  disc: [{ ans:'C', txt:'NodeCreationFailure는 다양한 원인을 가진 포괄적 오류 — AWS 공식 런북으로 체계적 진단이 올바른 접근입니다.' }]
},
{
  n: 397,
  en: `A company is developing an ecommerce application that has a backend that runs on Amazon EC2 instances. The application has a static frontend website that is hosted in an Amazon S3 bucket.<br><br>The company uses a GitHub repository for version control and must automate builds and deployments whenever code is pushed to the main branch. The company must deploy changes to the frontend and backend independently of each other.<br><br>Which solution will meet these requirements?`,
  ko: `한 회사가 Amazon EC2 인스턴스에서 실행되는 백엔드를 가진 전자상거래 애플리케이션을 개발 중입니다. 이 애플리케이션은 Amazon S3 버킷에 호스팅되는 정적 프런트엔드 웹사이트를 사용합니다.<br><br>회사는 버전 관리를 위해 GitHub 저장소를 사용하며, 메인 브랜치에 코드가 푸시될 때마다 빌드 및 배포를 자동화해야 합니다. 또한 프런트엔드와 백엔드의 변경 사항은 서로 독립적으로 배포해야 합니다.<br><br>이러한 요구 사항을 충족하는 솔루션은 무엇일까요?`,
  type: 'single',
  choices: [
    { k:'A', en:`Create a single AWS CodePipeline pipeline to use for the frontend and the backend. Specify the GitHub repository as the source. Configure two build stages that use AWS CodeBuild as the action provider to build the frontend components and backend components, respectively. Configure two deployment stages that use AWS CodeDeploy as the action provider to deploy the frontend and backend, respectively.`, ko:`프런트엔드와 백엔드에 사용할 단일 AWS CodePipeline 파이프라인을 생성합니다. 소스로 GitHub 리포지토리를 지정합니다. AWS CodeBuild를 액션 프로바이더로 사용하여 프런트엔드 구성 요소와 백엔드 구성 요소를 각각 빌드하는 두 개의 빌드 단계를 구성합니다. AWS CodeDeploy를 액션 프로바이더로 사용하여 프런트엔드와 백엔드를 각각 배포하는 두 개의 배포 단계를 구성합니다.` },
    { k:'B', en:`Create a single AWS CodePipeline pipeline to use for the frontend and the backend. Specify the GitHub repository as the source. Configure two build stages that use AWS CodeBuild as the action provider to build the frontend components and backend components, respectively. Configure two deployment stages. For the backend stage, use AWS CodeDeploy as the action provider to deploy the backend to the EC2 instances. For the frontend stage, use Amazon S3 as the action provider to deploy the frontend to the S3 bucket.`, ko:`프런트엔드와 백엔드에 사용할 단일 AWS CodePipeline 파이프라인을 생성합니다. 소스로 GitHub 리포지토리를 지정합니다. AWS CodeBuild를 액션 프로바이더로 사용하여 프런트엔드 구성 요소와 백엔드 구성 요소를 각각 빌드하는 두 개의 빌드 단계를 구성합니다. 두 개의 배포 단계를 구성합니다. 백엔드 단계에서는 AWS CodeDeploy를 액션 프로바이더로 사용하여 백엔드를 EC2 인스턴스에 배포합니다. 프런트엔드 단계에서는 Amazon S3를 액션 프로바이더로 사용하여 프런트엔드를 S3 버킷에 배포합니다.` },
    { k:'C', en:`Create two AWS CodePipeline pipelines: one for the frontend and one for the backend. Specify the GitHub repository as the source. Configure a build stage that uses AWS CodeBuild as the action provider for each pipeline to build the frontend and the backend. Configure a deployment stage that uses AWS CodeDeploy as the action provider for each pipeline to deploy the frontend and the backend.`, ko:`프런트엔드용과 백엔드용으로 각각 하나씩, 총 두 개의 AWS CodePipeline 파이프라인을 생성합니다. 소스로는 GitHub 리포지토리를 지정합니다. 각 파이프라인에 대해 AWS CodeBuild를 액션 프로바이더로 사용하는 빌드 단계를 구성하여 프런트엔드와 백엔드를 빌드합니다. 또한, 각 파이프라인에 대해 AWS CodeDeploy를 액션 프로바이더로 사용하는 배포 단계를 구성하여 프런트엔드와 백엔드를 배포합니다.` },
    { k:'D', en:`Create two AWS CodePipeline pipelines: one for the frontend and one for the backend. Specify the GitHub repository as the source. Configure a build stage that uses AWS CodeBuild as the action provider for each pipeline to build the frontend and the backend. For the backend pipeline, use AWS CodeDeploy as the action provider to deploy the backend to the EC2 instances. For the frontend pipeline, use Amazon S3 as the action provider to deploy the frontend to the S3 bucket.`, ko:`AWS CodePipeline 파이프라인 두 개를 생성합니다. 하나는 프런트엔드용이고 다른 하나는 백엔드용입니다. 소스로는 GitHub 리포지토리를 지정합니다. 각 파이프라인에 대해 AWS CodeBuild를 액션 프로바이더로 사용하여 프런트엔드와 백엔드를 빌드하는 빌드 단계를 구성합니다. 백엔드 파이프라인의 경우, AWS CodeDeploy를 액션 프로바이더로 사용하여 백엔드를 EC2 인스턴스에 배포합니다. 프런트엔드 파이프라인의 경우, Amazon S3를 액션 프로바이더로 사용하여 프런트엔드를 S3 버킷에 배포합니다.` },
  ],
  answer: ['D'],
  vote: '100% D',
  explain: `<p><span class="mark-ok">✅ D — 핵심 이유</span></p><p>프런트엔드와 백엔드를 독립적으로 배포하려면 별도의 파이프라인이 필요합니다. 프런트엔드(S3 정적 웹사이트)는 Amazon S3 액션 프로바이더로, 백엔드(EC2)는 AWS CodeDeploy 액션 프로바이더로 배포하는 것이 각 환경에 맞는 올바른 구성입니다.</p>`,
  wrong: `<p><span class="mark-no">❌ A/B</span> — 단일 파이프라인은 프런트엔드와 백엔드를 독립적으로 배포할 수 없습니다. 하나가 변경되면 다른 것도 함께 실행됩니다.</p><p><span class="mark-no">❌ C</span> — 두 파이프라인을 사용하지만 프런트엔드 배포에 CodeDeploy를 사용하는 것은 S3 정적 사이트에 부적합합니다.</p>`,
  disc: []
},
{
  n: 398,
  en: `A company has an RPO of 24 hours and an RTO of 10 minutes for a critical web application that runs on Amazon EC2 instances. The company uses AWS Organizations to manage its AWS account. The company wants to set up AWS Backup for its AWS environment.<br><br>A DevOps engineer configures AWS Organizations for AWS Backup. The DevOps engineer creates a new centralized AWS account to store the backups. Each EC2 instance has four Amazon Elastic Block Store (Amazon EBS) volumes attached.<br><br>Which solution will meet this requirement MOST securely?`,
  ko: `한 회사의 중요 웹 애플리케이션(Amazon EC2 인스턴스에서 실행됨)에 대해 RPO는 24시간, RTO는 10분입니다. 이 회사는 AWS Organizations를 사용하여 AWS 계정을 관리합니다. 이제 AWS 환경에 AWS Backup을 설정하려고 합니다.<br><br>DevOps 엔지니어가 AWS Backup을 위해 AWS Organizations를 구성하고, 백업을 저장할 새로운 중앙 집중식 AWS 계정을 생성합니다. 각 EC2 인스턴스에는 4개의 Amazon Elastic Block Store(Amazon EBS) 볼륨이 연결되어 있습니다.<br><br>이 요구 사항을 가장 안전하게 충족하는 솔루션은 무엇일까요?`,
  type: 'single',
  choices: [
    { k:'A', en:`Create encrypted backup vaults and customer managed AWS KMS keys in both accounts. Configure AWS Backup to create full EC2 backups as AMIs. Copy the backups to the centralized vault.`, ko:`두 계정 모두에 암호화된 백업 볼트와 고객 관리형 AWS KMS 키를 생성합니다. AWS Backup을 구성하여 전체 EC2 백업을 AMI로 생성합니다. 생성된 백업을 중앙 집중식 볼트로 복사합니다.` },
    { k:'B', en:`Create encrypted vaults in both accounts by using the source account's AWS KMS key. Configure AWS Backup to create EC2 AMIs. Copy the AMIs to the centralized vault.`, ko:`소스 계정의 AWS KMS 키를 사용하여 두 계정 모두에 암호화된 볼트를 생성합니다. AWS Backup을 구성하여 EC2 AMI를 생성합니다. 생성된 AMI를 중앙 집중식 볼트로 복사합니다.` },
    { k:'C', en:`Create backup vaults in both accounts. Use AWS managed keys for encryption. Configure AWS Backup to create EC2 AMIs. Copy the AMIs to the centralized vault.`, ko:`두 계정 모두에 백업 볼트를 생성합니다. 암호화에는 AWS 관리형 키를 사용합니다. AWS Backup이 EC2 AMI를 생성하도록 구성합니다. 생성된 AMI를 중앙 집중식 볼트로 복사합니다.` },
    { k:'D', en:`Create encrypted vaults in both accounts. Use a customer managed KMS key in the source account. Use an AWS managed key in the centralized account. Configure AWS Backup to create EC2 AMIs. Copy the AMIs to the centralized vault.`, ko:`두 계정 모두에 암호화된 볼트를 생성합니다. 소스 계정에는 고객 관리형 KMS 키를 사용하고, 중앙 집중식 계정에는 AWS 관리형 키를 사용합니다. AWS Backup을 구성하여 EC2 AMI를 생성하고, 생성된 AMI를 중앙 집중식 볼트로 복사합니다.` },
  ],
  answer: ['A'],
  vote: '100% A',
  explain: `<p><span class="mark-ok">✅ A — 핵심 이유</span></p><p>가장 안전한 구성은 양쪽 계정 모두에 고객 관리형 KMS 키(CMK)를 사용하는 것입니다. CMK는 키 사용 정책, 키 회전, 접근 제어를 세밀하게 관리할 수 있어 AWS 관리형 키보다 보안성이 높습니다. EC2 전체 백업(AMI)으로 EBS 볼륨 4개를 포함한 완전한 복구가 가능하며 RTO 10분을 충족합니다.</p>`,
  wrong: `<p><span class="mark-no">❌ B</span> — 소스 계정의 KMS 키만 사용하면 교차 계정 복사 시 키 정책 관리가 복잡해지고 보안상 취약점이 생깁니다.</p><p><span class="mark-no">❌ C</span> — AWS 관리형 키는 교차 계정 공유가 불가능하여 중앙 계정으로 백업 복사 시 문제가 발생합니다.</p><p><span class="mark-no">❌ D</span> — 혼합 키 사용은 일관성이 없으며, 중앙 계정에 AWS 관리형 키 사용 시 교차 계정 복사 제한이 있습니다.</p>`,
  disc: []
},
{
  n: 399,
  en: `A company wants to proactively monitor and respond to AWS service issues that might affect an application. The company must correlate AWS Health events with application performance metrics and must set up automated alerts. The solution must give the company the ability to archive events, test the application's latency in different scenarios, and create custom metrics.<br><br>Which solution will meet these requirements?`,
  ko: `한 기업이 애플리케이션에 영향을 미칠 수 있는 AWS 서비스 문제를 사전에 모니터링하고 대응하고자 합니다. AWS 상태 이벤트와 애플리케이션 성능 지표 간의 상관관계를 파악하고 자동화된 알림을 설정해야 합니다. 또한, 이벤트 아카이빙, 다양한 시나리오에서의 애플리케이션 지연 시간 테스트, 사용자 지정 지표 생성 기능도 제공해야 합니다.<br><br>이러한 요구 사항을 충족하는 솔루션은 무엇일까요?`,
  type: 'single',
  choices: [
    { k:'A', en:`Use AWS CloudTrail to log all AWS Health events. Use Amazon Athena to query the logs and to correlate the logs with application metrics stored in Amazon Timestream for LiveAnalytics. Set up AWS Chatbot for real-time notifications.`, ko:`AWS CloudTrail을 사용하여 모든 AWS 상태 이벤트를 기록합니다. Amazon Athena를 사용하여 로그를 쿼리하고 Amazon Timestream for LiveAnalytics에 저장된 애플리케이션 메트릭과 로그를 연관시킵니다. 실시간 알림을 위해 AWS Chatbot을 설정합니다.` },
    { k:'B', en:`Use Amazon EventBridge to route AWS Health events to Amazon CloudWatch Logs. Create a metric filter for AWS Health events. Create custom metrics in CloudWatch that are based on application performance data. Set up CloudWatch alarms that correlate AWS Health events with the custom metrics.`, ko:`Amazon EventBridge를 사용하여 AWS Health 이벤트를 Amazon CloudWatch Logs로 라우팅합니다. AWS Health 이벤트에 대한 메트릭 필터를 생성합니다. 애플리케이션 성능 데이터를 기반으로 CloudWatch에 사용자 지정 메트릭을 생성합니다. AWS Health 이벤트와 사용자 지정 메트릭을 연관시키는 CloudWatch 알람을 설정합니다.` },
    { k:'C', en:`Configure the AWS Health Dashboard to send notifications to Amazon Simple Notification Service (Amazon SNS). Use AWS Lambda to correlate the notifications with metrics and to update custom metrics in Amazon CloudWatch. Set up CloudWatch alarms for the custom metrics. Use AWS Systems Manager for automated remediation.`, ko:`AWS Health Dashboard를 구성하여 Amazon Simple Notification Service(Amazon SNS)로 알림을 전송합니다. AWS Lambda를 사용하여 알림과 메트릭을 연관시키고 Amazon CloudWatch의 사용자 지정 메트릭을 업데이트합니다. 사용자 지정 메트릭에 대한 CloudWatch 알람을 설정합니다. AWS Systems Manager를 사용하여 자동화된 문제 해결을 수행합니다.` },
    { k:'D', en:`Configure AWS X-Ray to trace AWS Health events and application performance. Use Amazon QuickSight to visualize the correlations between events and metrics. Use Amazon GuardDuty to detect anomalies in the application's behavior and to provide alerts.`, ko:`AWS X-Ray를 구성하여 AWS Health 이벤트 및 애플리케이션 성능을 추적합니다. Amazon QuickSight를 사용하여 이벤트와 메트릭 간의 상관관계를 시각화합니다. Amazon GuardDuty를 사용하여 애플리케이션 동작의 이상 징후를 감지하고 경고를 제공합니다.` },
  ],
  answer: ['B'],
  vote: '100% B',
  explain: `<p><span class="mark-ok">✅ B — 핵심 이유</span></p><p>EventBridge는 AWS Health 이벤트를 라우팅하고 아카이빙(이벤트 아카이브 기능)할 수 있습니다. CloudWatch Logs의 메트릭 필터로 Health 이벤트 기반 사용자 지정 메트릭을 생성하고, CloudWatch Synthetics 카나리로 지연 시간 테스트도 가능합니다. CloudWatch 알람으로 Health 이벤트와 성능 지표를 연관시켜 자동 알림을 설정합니다.</p>`,
  wrong: `<p><span class="mark-no">❌ A</span> — CloudTrail은 AWS Health 이벤트 전용 로깅 도구가 아니며, Timestream 연동은 불필요한 복잡성을 더합니다.</p><p><span class="mark-no">❌ C</span> — Health Dashboard에서 SNS 직접 알림 구성은 지원되지 않으며, EventBridge를 거쳐야 합니다.</p><p><span class="mark-no">❌ D</span> — X-Ray는 AWS Health 이벤트 추적 도구가 아니며, GuardDuty는 보안 위협 탐지용입니다.</p>`,
  disc: []
},
{
  n: 400,
  en: `A company uses a CI/CD pipeline to deploy its workload in the ap-southeast-2 Region. The company receives images through a Network Load Balancer (NLB) and processes the images in AWS Fargate tasks on an Amazon Elastic Container Service (Amazon ECS) cluster.<br><br>An Amazon Elastic Container Registry (Amazon ECR) repository stores the images as Docker images. The company uses Amazon Route 53 to configure DNS. The company saves the images in an Amazon S3 bucket and saves the metadata from the images in an Amazon DynamoDB table.<br><br>The company wants to expand the workload to a second Region. A DevOps engineer needs to build a highly available and resilient design to expand the workload to the eu-west-2 Region.<br><br>Which combination of steps will meet these requirements with the FEWEST configuration changes? (Choose three.)`,
  ko: `한 회사가 CI/CD 파이프라인을 사용하여 ap-southeast-2 리전에 워크로드를 배포합니다. 회사는 네트워크 로드 밸런서(NLB)를 통해 이미지를 수신하고 Amazon Elastic Container Service(Amazon ECS) 클러스터의 AWS Fargate 태스크에서 이미지를 처리합니다.<br><br>Amazon Elastic Container Registry(Amazon ECR) 리포지토리에는 Docker 이미지가 저장됩니다. 회사는 Amazon Route 53을 사용하여 DNS를 구성합니다. 이미지는 Amazon S3 버킷에 저장하고 이미지의 메타데이터는 Amazon DynamoDB 테이블에 저장합니다.<br><br>이 회사는 워크로드를 두 번째 리전으로 확장하려고 합니다. DevOps 엔지니어는 워크로드를 eu-west-2 리전으로 확장하기 위한 고가용성 및 복원력 있는 설계를 구축해야 합니다.<br><br>최소한의 구성 변경으로 이러한 요구 사항을 충족하는 단계 조합은 무엇입니까? (세 가지를 선택하십시오.)`,
  type: 'multi', multiCount: 3,
  choices: [
    { k:'A', en:`Configure ECR replication to eu-west-2 on the repository. Configure an NLB in eu-west-2 that resolves to Fargate tasks in an ECS cluster in eu-west-2. Configure a latency routing policy in Route 53 for the two workloads.`, ko:`저장소에서 eu-west-2로 ECR 복제를 구성합니다. eu-west-2에 있는 ECS 클러스터의 Fargate 태스크로 확인되는 NLB를 구성합니다. 두 워크로드에 대해 Route 53에서 지연 시간 라우팅 정책을 구성합니다.` },
    { k:'B', en:`Configure the DynamoDB table as a global table with a replica in eu-west-2. Configure the Fargate tasks to interact with the DynamoDB table in ap-southeast-2.`, ko:`DynamoDB 테이블을 eu-west-2에 복제본을 가진 글로벌 테이블로 구성합니다. Fargate 태스크가 ap-southeast-2의 DynamoDB 테이블과 상호 작용하도록 구성합니다.` },
    { k:'C', en:`Configure the DynamoDB table as a global table with a replica in eu-west-2. Configure the Fargate tasks to interact with the DynamoDB table in the same Region that the tasks run in.`, ko:`DynamoDB 테이블을 eu-west-2 리전에 복제본을 가진 글로벌 테이블로 구성합니다. Fargate 태스크가 실행되는 리전과 동일한 리전의 DynamoDB 테이블과 상호 작용하도록 구성합니다.` },
    { k:'D', en:`Configure a new S3 bucket in eu-west-2. Configure data replication between the S3 bucket in ap-southeast-2 and the S3 bucket in eu-west-2. Configure the Fargate tasks to use the S3 bucket in the same Region that the tasks run in to perform S3 PUT operations and GET operations.`, ko:`eu-west-2 리전에 새 S3 버킷을 구성합니다. ap-southeast-2 리전의 S3 버킷과 eu-west-2 리전의 S3 버킷 간에 데이터 복제를 구성합니다. Fargate 태스크가 S3 PUT 및 GET 작업을 수행할 때 태스크가 실행되는 리전과 동일한 리전의 S3 버킷을 사용하도록 구성합니다.` },
    { k:'E', en:`Configure an S3 Multi-Region Access Point for the S3 bucket in ap-southeast-2 and a new S3 bucket in eu-west-2. Configure two-way replication on the S3 buckets. Configure the workloads to use the Multi-Region Access Point for S3 PUT operations and GET operations.`, ko:`ap-southeast-2의 S3 버킷과 eu-west-2의 새 S3 버킷에 대해 S3 멀티 리전 액세스 포인트를 구성합니다. S3 버킷에 양방향 복제를 구성합니다. 워크로드가 S3 PUT 및 GET 작업에 멀티 리전 액세스 포인트를 사용하도록 구성합니다.` },
    { k:'F', en:`Configure the CI/CD pipeline to deploy ECR images to both Regions. Configure an NLB in eu-west-2 that resolves to Fargate tasks in an ECS cluster in eu-west-2. Configure a failover routing policy in Route 53 for the two workloads.`, ko:`CI/CD 파이프라인을 구성하여 ECR 이미지를 두 리전 모두에 배포합니다. eu-west-2 리전에 있는 ECS 클러스터의 Fargate 태스크로 연결되는 NLB를 구성합니다. 두 워크로드에 대한 Route 53의 페일오버 라우팅 정책을 구성합니다.` },
  ],
  answer: ['A','C','E'],
  vote: '100% ACE',
  explain: `<p><span class="mark-ok">✅ A+C+E — 핵심 이유</span></p><p><strong>A</strong>: ECR 레지스트리 복제로 Docker 이미지를 eu-west-2에 자동 복제하고, NLB+ECS Fargate를 구성하며, Route 53 지연 시간 라우팅으로 사용자를 가장 가까운 리전으로 라우팅합니다.</p><p><strong>C</strong>: DynamoDB 글로벌 테이블로 양 리전에 메타데이터를 복제하고, 각 태스크가 로컬 리전 테이블과 통신하여 지연 시간을 최소화합니다.</p><p><strong>E</strong>: S3 멀티 리전 액세스 포인트는 애플리케이션 코드 변경 없이 단일 엔드포인트로 양 리전 S3에 접근하고, 양방향 복제로 데이터 일관성을 유지합니다.</p>`,
  wrong: `<p><span class="mark-no">❌ B</span> — eu-west-2 태스크가 ap-southeast-2 DynamoDB에 연결하면 교차 리전 지연이 발생하여 고가용성 설계에 부적합합니다.</p><p><span class="mark-no">❌ D</span> — 별도 버킷+복제 구성은 가능하나, 멀티 리전 액세스 포인트(E) 대비 애플리케이션 코드 변경이 필요합니다.</p><p><span class="mark-no">❌ F</span> — CI/CD 파이프라인을 양 리전에 배포하는 방식은 ECR 복제(A)보다 구성 변경이 많습니다.</p>`,
  disc: []
}
];
