정리

#009: 90일 후에도 키가 로테이션 되지 않는경우 알림 : 키가 90일 이상 경과한 경우 Amazon SNS 주제에 게시하는 AWS Config 사용자 지정 규칙을 개발
#010: AWS CodeBuild Prj가 인증안된 요청으로 S3에서 DB초기화 스크립트 다운로드하는 문제 : S3버킷정책 미인증 접근제거, CodeBuild 서비스역할에 S3 접근포함수정, AWS CLI로 스크립트 다운로드
#011: 최소권한 원칙을 적용하여 팀 자체 리소스만 빌드하고 관리하는 강력한 권한모델 : IdP에서 그룹생성 및 사용자 할당, IAM Identity Center에서 속성기반 access제어 활성화 및 Idp 속성 매핑, 권한집합 생성 및 인라인 정책첨부
#012: 주문 내역 페이지에 주문 처리 상태반영 지연 : SQS 대기열의 ApproximateAgeOfOldestMessage 지표 확인, Lambda 함수 동시성 제한 증가, DynamoDB 테이블의 WriteThrottleEvents 지표 확인 및 최대 쓰기 용량 단위(WCU) 증가 
#013: 실행 중인 모든 EC2 인스턴스에 EC2 인스턴스 프로필이 연결되도록 보장 : ec2-instance-profile-attached AWS Config 관리 규칙 구성, 구성변경시 기본 인스턴스 프로필을 EC2인스턴스에 연결하는 런북 호출되도록 트리거 구성
#014: AWS Lambda 함수를 사용하는 서버리스 애플리케이션 배포실패 영향 최소화 : AWS Serverless Application Model(AWS SAM) 템플릿, Canary10Percent15Minutes 배포 유형으로 Lambda 함수 배포
#015: EC2가 인터넷에 액세스할 수 없도록 설정 상태에서 APP 미설치 문제 : APP을 S3에 업로드, S3에 대한 VPC 엔드포인트 생성, EC2에 IAM 인스턴스 프로필을 할당하여 S3에서 APP 접근 권한부여
#016: CodeCommit 리포지토리에 코드 변경 사항 푸시했지만 10분이 지나도 파이프라인 반응이 없음 : Amazon EventBridge 규칙이 메인 브랜치에 대한 트리거로 올바르게 설정되었는지 확인필요
#017: 사용자가 무제한 보안 그룹 규칙을 만들 때 이를 감지하는 솔루션 : Amazon EventBridge 이벤트 규칙 생성, EC2 보안 그룹의 생성 및 수정 이벤트 패턴 정의, 해당 규칙이 Lambda 함수 호출하도록 규칙 구성.
#018: IPv6 클라이언트가 프라이빗 서브넷의 EC2 인스턴스 뒤에 있는 웹 서비스에 접근할 수 있도록 하려면 : VPC 및 서브넷에 IPv6 CIDR 블록 추가하여 IPv6 트레픽 수용, ALB에서 IP 주소 유형을 'dualstack'으로 설정, 포트 443에 리스너 생성, 대상 그룹 생성 및 EC2 인스턴스 추가, 이를 ALB의 리스너와 연결
#019: Enterprise Support 플랜으로 새 계정을 프로비저닝하는 솔루션을 구현 : AFT 배포 입력 구성에서 aft_feature_enterprise_support 기능 플래그를 True로 설정한 후, AFT를 재배포하여 변경 사항을 적용
#020: AWS Health로부터 Amazon EC2 인스턴스의 재시작이 필요하다는 알림 자동화 : EventBridge 규칙의 이벤트 소스를 EC2의 서비스인 AWS Health로 설정, 이벤트 유형을 인스턴스 유지 관리로 지정, EC2 인스턴스를 재시작하는 Systems Manager 문서를 대상으로 지정.
